In [ ]:
import pandas as pd
df = pd.read_excel("WikiRelationsToVerify.xlsx", sheet_name="Relations with limited PMI")

In [ ]:
import requests
import pandas as pd

def fetch_wikidata_labels(ids):
    """Fetches labels for a list of Wikidata QIDs or PIDs in batches."""
    unique_ids = list(set(ids))
    id_to_label = {}
    batch_size = 500

    for i in range(0, len(unique_ids), batch_size):
        batch = unique_ids[i:i+batch_size]
        values_str = " ".join(f"wd:{item}" for item in batch if pd.notna(item) and str(item).startswith(('Q', 'P')))
        if not values_str:
            continue

        query = f"""
        SELECT ?item ?itemLabel WHERE {{
          VALUES ?item {{ {values_str} }}
          SERVICE wikibase:label {{ bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }}
        }}
        """

        url = 'https://query.wikidata.org/sparql'
        headers = {
            'User-Agent': 'ColabNotebook/1.0 (contact@example.com)',
            'Accept': 'application/json'
        }

        try:
            response = requests.get(url, params={'query': query, 'format': 'json'}, headers=headers)
            if response.status_code == 200:
                results = response.json().get('results', {}).get('bindings', [])
                for row in results:
                    item_uri = row.get('item', {}).get('value', '')
                    item_id = item_uri.split('/')[-1]
                    label = row.get('itemLabel', {}).get('value', '')
                    id_to_label[item_id] = label
            else:
                print(f"Failed batch {i // batch_size + 1}: Status {response.status_code}")
        except Exception as e:
            print(f"Error fetching batch: {e}")

    return id_to_label

# Gather all unique QIDs/PIDs that need to be resolved
all_ids = pd.concat([df['subject'], df['object'], df['prop']]).dropna().unique()

# Fetch labels from Wikidata
print(f"Fetching labels for {len(all_ids)} unique IDs...")
labels_map = fetch_wikidata_labels(all_ids)

# Map labels back to the dataframe
df['subject_label'] = df['subject'].map(labels_map)
df['object_label'] = df['object'].map(labels_map)
df['prop_label'] = df['prop'].map(labels_map)

# Display a sample of the resulting DataFrame
df.head()

Fetching labels for 6806 unique IDs...

,subject,subjectID,object,objectID,prop,PMI,subject_label,object_label,prop_label
0,Q58833983,D064726,Q12136,D004194,P31,-5.731662,triple-negative breast neoplasm,disease,instance of
1,Q4082046,D063146,Q623,D002244,P527,-5.628619,polycomb-group proteins,carbon,has part(s)
2,Q382370,D045908,Q835153,D010808,P923,-5.225243,mpox,physical examination,medical examination
3,Q155098,D007922,Q166774,D011480,P924,-5.046738,leptospirosis,protease inhibitor,possible treatment
4,Q1059765,D010510,Q120569,D005762,P1995,-4.978983,periodontal disease,gastroenterology,health specialty

In [ ]:
!pip install typesafe-sdk

Collecting typesafe-sdk
  Downloading typesafe_sdk-0.7.2-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: httpx2>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from typesafe-sdk) (2.13.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.13/dist-packages (from typesafe-sdk) (2.13.5)
Requirement already satisfied: pydantic-core>=2.41.1 in /usr/local/lib/python3.13/dist-packages (from typesafe-sdk) (2.46.5)
Requirement already satisfied: tenacity>=9.0.0 in /usr/local/lib/python3.13/dist-packages (from typesafe-sdk) (9.1.4)
Requirement already satisfied: typing-extensions>=4.13.0 in /usr/local/lib/python3.13/dist-packages (from typesafe-sdk) (4.16.0)
Requirement already satisfied: anyio>=4.10 in /usr/local/lib/python3.13/dist-packages (from httpx2>=2.0.0->typesafe-sdk) (4.15.1)
Requirement already satisfied: httpcore2==2.13.0 in /usr/local/lib/python3.13/dist-packages (from httpx2>=2.0.0->typesafe-sdk) (2.13.0)
Requirement already satisfied: idna>=3.18 in /usr/local/lib/python3.13/dist-packages (from httpx2>=2.0.0->typesafe-sdk) (3.19)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2>=2.0.0->typesafe-sdk) (0.10.4)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore2==2.13.0->httpx2>=2.0.0->typesafe-sdk) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.12.0->typesafe-sdk) (0.8.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.12.0->typesafe-sdk) (0.4.4)
Downloading typesafe_sdk-0.7.2-py3-none-any.whl (36 kB)
Installing collected packages: typesafe-sdk
Successfully installed typesafe-sdk-0.7.2

In [ ]:
!uv add typesafe-sdk

error: No `pyproject.toml` found in current directory or any parent directory

In [ ]:
import os
os.environ["TYPESAFE_API_KEY"] = "YOUR_API_KEY" # Replace with your actual API key

In [ ]:
from typesafe_sdk import Choice, TypeSafeClient
from tqdm import tqdm

findings = []
with TypeSafeClient() as client:
  for rel in tqdm(df.iloc):
    inst=f"Determine whether the semantic relation where {rel["subject_label"]} is the subject, {rel["prop_label"]} is the predicate, and {rel["object_label"]} is the object constitutes an accurate semantic relation."
    print(inst)
    response = client.system_one(
        state={"document": "You are evaluating candidate relations extracted from a knowledge graph. The goal is to determine whether the subject-predicate–object triple represents a valid and meaningful relationship according to established scientific knowledge and terminology."},
        questions={
            "category": Choice(
                instructions=inst,
                criteria={"true": None, "maybe": None, "false": None},
            ),
        },
    )
    findings.append(response.choices["category"].choice)
    print(response.choices["category"].choice)

0it [00:00, ?it/s]

Determine whether the semantic relation where triple-negative breast neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2it [00:00,  4.63it/s]

true
Determine whether the semantic relation where polycomb-group proteins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mpox is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

4it [00:00,  4.97it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, possible treatment is the predicate, and protease inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where periodontal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

5it [00:01,  5.13it/s]

false
Determine whether the semantic relation where glucagon-like peptide-1 is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7it [00:01,  4.91it/s]

false
Determine whether the semantic relation where brain infarction is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where accelerometry is the subject, has use is the predicate, and biology is the object constitutes an accurate semantic relation.

8it [00:01,  5.06it/s]

true
Determine whether the semantic relation where Kearns-Sayre syndrome is the subject, field of work is the predicate, and medicine is the object constitutes an accurate semantic relation.

10it [00:02,  4.49it/s]

false
Determine whether the semantic relation where foot-and-mouth disease is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dacarbazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12it [00:02,  4.87it/s]

true
Determine whether the semantic relation where ventilator-associated pneumonia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plant is the subject, has part(s) is the predicate, and germ layer is the object constitutes an accurate semantic relation.

14it [00:02,  4.99it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nocardiosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

15it [00:03,  5.10it/s]

false
Determine whether the semantic relation where hydrogen is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

16it [00:03,  4.81it/s]

true
Determine whether the semantic relation where tamoxifen is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

17it [00:03,  4.83it/s]

true
Determine whether the semantic relation where leukemia is the subject, symptoms and signs is the predicate, and angina pectoris is the object constitutes an accurate semantic relation.

19it [00:03,  4.90it/s]

false
Determine whether the semantic relation where multidrug-resistant tuberculosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where multidrug-resistant tuberculosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

21it [00:04,  5.19it/s]

true
Determine whether the semantic relation where conjunctival disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ceftriaxone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

23it [00:04,  4.98it/s]

true
Determine whether the semantic relation where salivary gland disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where corneal disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

25it [00:05,  5.06it/s]

false
Determine whether the semantic relation where castration-resistant prostatic neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

26it [00:05,  5.24it/s]

Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 19 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chancroid is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

28it [00:05,  5.33it/s]

false
Determine whether the semantic relation where melioidosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diltiazem is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

29it [00:05,  5.24it/s]

false
Determine whether the semantic relation where visceral leishmaniasis is the subject, anatomical location is the predicate, and bone is the object constitutes an accurate semantic relation.

30it [00:06,  4.64it/s]

false
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and heart arrhythmia is the object constitutes an accurate semantic relation.

32it [00:06,  4.82it/s]

true
Determine whether the semantic relation where vincristine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where connective tissue neoplasm is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

34it [00:06,  5.12it/s]

false
Determine whether the semantic relation where endemic typhus is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peptide nucleic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

36it [00:07,  5.23it/s]

true
Determine whether the semantic relation where radiometric dating is the subject, subclass of is the predicate, and scientific method is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ostertagiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

37it [00:07,  5.36it/s]

true
Determine whether the semantic relation where krypton is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

38it [00:07,  5.21it/s]

false
Determine whether the semantic relation where MEDLINE is the subject, main subject is the predicate, and biophysics is the object constitutes an accurate semantic relation.

39it [00:07,  4.76it/s]

false
Determine whether the semantic relation where goldfish is the subject, invasive to is the predicate, and Australia is the object constitutes an accurate semantic relation.

40it [00:08,  4.76it/s]

false
Determine whether the semantic relation where bovine spongiform encephalopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

41it [00:08,  4.80it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

43it [00:08,  4.92it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

44it [00:08,  4.82it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

46it [00:09,  4.86it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and bromocriptine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, afflicts is the predicate, and human eye is the object constitutes an accurate semantic relation.

47it [00:09,  4.60it/s]

false
Determine whether the semantic relation where postpartum depression is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

49it [00:10,  4.80it/s]

true
Determine whether the semantic relation where yellow fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where muscimol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

50it [00:10,  5.13it/s]

true
Determine whether the semantic relation where periodical is the subject, has characteristic is the predicate, and periodicity is the object constitutes an accurate semantic relation.

52it [00:10,  5.08it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, possible treatment is the predicate, and anti-inflammatory agent is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where D-sorbitol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

53it [00:10,  5.19it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

55it [00:11,  4.89it/s]

false
Determine whether the semantic relation where theileriasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where norepinephrine is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

56it [00:11,  4.93it/s]

false
Determine whether the semantic relation where diazepam is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

58it [00:11,  4.71it/s]

false
Determine whether the semantic relation where solitary pulmonary nodule is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where solitary pulmonary nodule is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

60it [00:12,  5.01it/s]

false
Determine whether the semantic relation where threatened abortion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mebendazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

62it [00:12,  5.26it/s]

false
Determine whether the semantic relation where glanders is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BRCA2 is the subject, expressed in is the predicate, and bone marrow cell is the object constitutes an accurate semantic relation.

64it [00:13,  4.92it/s]

false
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where norepinephrine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

65it [00:13,  4.42it/s]

false
Determine whether the semantic relation where muscimol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

66it [00:13,  4.56it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

67it [00:13,  3.97it/s]

true
Determine whether the semantic relation where dopamine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

68it [00:14,  4.10it/s]

false
Determine whether the semantic relation where Serpin family G member 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

70it [00:14,  4.51it/s]

false
Determine whether the semantic relation where choroid disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where apomorphine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

71it [00:14,  4.75it/s]

false
Determine whether the semantic relation where forskolin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

73it [00:15,  4.84it/s]

true
Determine whether the semantic relation where cyclin dependent kinase inhibitor 2A is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taenia solium is the subject, main food source is the predicate, and glucose is the object constitutes an accurate semantic relation.

74it [00:15,  4.87it/s]

false
Determine whether the semantic relation where visceral leishmaniasis is the subject, subclass of is the predicate, and bone disease is the object constitutes an accurate semantic relation.

75it [00:15,  4.61it/s]

false
Determine whether the semantic relation where listeriosis is the subject, has natural reservoir is the predicate, and soil is the object constitutes an accurate semantic relation.

76it [00:15,  4.35it/s]

true
Determine whether the semantic relation where HIV seropositivity is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

77it [00:15,  4.48it/s]

false
Determine whether the semantic relation where proteostasis deficiency is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

79it [00:16,  4.81it/s]

false
Determine whether the semantic relation where yersiniosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where staphyloenterotoxemia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

81it [00:16,  4.85it/s]

true
Determine whether the semantic relation where mouth disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where endoleak is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

83it [00:17,  5.06it/s]

true
Determine whether the semantic relation where sleep apnea is the subject, different from is the predicate, and amnesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amnesia is the subject, different from is the predicate, and sleep apnea is the object constitutes an accurate semantic relation.

84it [00:17,  5.06it/s]

true
Determine whether the semantic relation where plague is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

86it [00:17,  4.96it/s]

false
Determine whether the semantic relation where mitral valve insufficiency is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

87it [00:17,  5.14it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

88it [00:18,  5.01it/s]

true
Determine whether the semantic relation where fenoterol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

90it [00:18,  5.15it/s]

false
Determine whether the semantic relation where mpox is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where non-small-cell lung carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

91it [00:18,  5.01it/s]

true
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.

92it [00:19,  4.71it/s]

false
Determine whether the semantic relation where Dictyocaulus infectious disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

94it [00:19,  4.93it/s]

true
Determine whether the semantic relation where pulse is the subject, part of is the predicate, and haematopoietic system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gums is the subject, instance of is the predicate, and animal structure is the object constitutes an accurate semantic relation.

95it [00:19,  5.02it/s]

false
Determine whether the semantic relation where diphtheria is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

96it [00:19,  4.99it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and nervous system is the object constitutes an accurate semantic relation.

98it [00:20,  5.09it/s]

maybe
Determine whether the semantic relation where dicrocoeliasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

100it [00:20,  5.18it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where purpura is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

101it [00:20,  5.20it/s]

false
Determine whether the semantic relation where epidemic typhus is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

103it [00:21,  5.08it/s]

false
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

105it [00:21,  5.23it/s]

true
Determine whether the semantic relation where methylphenidate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

106it [00:21,  5.13it/s]

true
Determine whether the semantic relation where BRCA2 is the subject, expressed in is the predicate, and testicle is the object constitutes an accurate semantic relation.
false

108it [00:22,  5.04it/s]

Determine whether the semantic relation where meso-DAP is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uhlenhuth test is the subject, country is the predicate, and Germany is the object constitutes an accurate semantic relation.

110it [00:22,  5.02it/s]

false
Determine whether the semantic relation where motion sickness is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cannabidiol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

112it [00:22,  5.17it/s]

false
Determine whether the semantic relation where azathioprine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

114it [00:23,  5.22it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and human musculoskeletal system is the object constitutes an accurate semantic relation.

116it [00:23,  4.87it/s]

false
Determine whether the semantic relation where Epstein–Barr virus infection is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where goldfish is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

118it [00:24,  5.10it/s]

false
Determine whether the semantic relation where cholera is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where MYC is the subject, expressed in is the predicate, and human penis is the object constitutes an accurate semantic relation.

120it [00:24,  5.32it/s]

false
Determine whether the semantic relation where histamine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where skin absorption is the subject, subclass of is the predicate, and pathogen transmission is the object constitutes an accurate semantic relation.

121it [00:24,  5.06it/s]

false
Determine whether the semantic relation where intracranial arterial disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

123it [00:25,  4.88it/s]

false
Determine whether the semantic relation where xanthogranulomatous pyelonephritis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system vascular malformation is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

124it [00:25,  4.96it/s]

false
Determine whether the semantic relation where pancreatic ductal carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

126it [00:25,  4.98it/s]

true
Determine whether the semantic relation where plague is the subject, possible treatment is the predicate, and anti-inflammatory agent is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

128it [00:26,  5.06it/s]

false
Determine whether the semantic relation where beclomethasone dipropionate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

130it [00:26,  5.22it/s]

true
Determine whether the semantic relation where Barrett's esophagus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tooth ankylosis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

131it [00:26,  5.01it/s]

false
Determine whether the semantic relation where meningioma is the subject, drug or therapy used for treatment is the predicate, and cytarabine is the object constitutes an accurate semantic relation.

133it [00:27,  4.90it/s]

false
Determine whether the semantic relation where cytarabine is the subject, medical condition treated is the predicate, and meningioma is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and hypotension is the object constitutes an accurate semantic relation.

135it [00:27,  4.94it/s]

true
Determine whether the semantic relation where ehrlichiosis is the subject, has natural reservoir is the predicate, and fish is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where losartan is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

136it [00:27,  4.95it/s]

false
Determine whether the semantic relation where metformin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

138it [00:28,  4.97it/s]

false
Determine whether the semantic relation where amebiasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where smallpox is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

139it [00:28,  5.06it/s]

false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

141it [00:28,  5.11it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium is the subject, instance of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

143it [00:29,  5.12it/s]

false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

145it [00:29,  5.21it/s]

true
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where photography is the subject, subclass of is the predicate, and industry is the object constitutes an accurate semantic relation.

147it [00:29,  5.31it/s]

false
Determine whether the semantic relation where substance P is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular hemostatic disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

149it [00:30,  5.25it/s]

false
Determine whether the semantic relation where arginine vasopressin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BRCA1 is the subject, expressed in is the predicate, and bone marrow cell is the object constitutes an accurate semantic relation.

151it [00:30,  5.33it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase 4 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichostrongyloidosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

153it [00:30,  5.39it/s]

true
Determine whether the semantic relation where pilonidal cyst is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lacrimal apparatus disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

155it [00:31,  5.23it/s]

false
Determine whether the semantic relation where boutonneuse fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sarcocystosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

157it [00:31,  5.24it/s]

true
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where omeprazole is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

159it [00:32,  5.39it/s]

true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adipokine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

160it [00:32,  5.39it/s]

false
Determine whether the semantic relation where luteinizing hormone/choriogonadotropin receptor is the subject, biological process is the predicate, and cognition is the object constitutes an accurate semantic relation.

161it [00:32,  5.02it/s]

false
Determine whether the semantic relation where thorium dioxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

163it [00:33,  4.70it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lip disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

165it [00:33,  5.01it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

166it [00:33,  4.77it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

168it [00:34,  4.35it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thalidomide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

170it [00:34,  4.62it/s]

false
Determine whether the semantic relation where chickenpox is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where molluscum contagiosum is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

172it [00:34,  4.95it/s]

false
Determine whether the semantic relation where tremor is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hepatic echinococcosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

173it [00:35,  5.05it/s]

true
Determine whether the semantic relation where coronary artery anomaly is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

175it [00:35,  5.09it/s]

false
Determine whether the semantic relation where leukemia is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where candidemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

177it [00:35,  5.20it/s]

true
Determine whether the semantic relation where haloperidol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

179it [00:36,  5.22it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.
true

180it [00:36,  5.23it/s]

Determine whether the semantic relation where arginine vasopressin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

182it [00:36,  5.19it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where serous cystadenocarcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

183it [00:37,  5.08it/s]

true
Determine whether the semantic relation where Interleukin 7 receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

185it [00:37,  5.09it/s]

false
Determine whether the semantic relation where Rotaviral gastroenteritis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where methylenetetrahydrofolate reductase is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.

187it [00:37,  5.03it/s]

false
Determine whether the semantic relation where methicillin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nifedipine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

189it [00:38,  5.04it/s]

true
Determine whether the semantic relation where cefazolin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorhexidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

191it [00:38,  5.14it/s]

false
Determine whether the semantic relation where signet ring cell adenocarcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leishmaniasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

192it [00:38,  5.17it/s]

false
Determine whether the semantic relation where hyperalgesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

194it [00:39,  4.94it/s]

false
Determine whether the semantic relation where (RS)-fenfluramine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where niobium is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

196it [00:39,  5.03it/s]

false
Determine whether the semantic relation where Lyme disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where saccharin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

198it [00:40,  5.30it/s]

true
Determine whether the semantic relation where alcoholic liver disease is the subject, possible treatment is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Macau is the object constitutes an accurate semantic relation.

199it [00:40,  5.38it/s]

false
Determine whether the semantic relation where Macau is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

201it [00:40,  5.07it/s]

false
Determine whether the semantic relation where dopamine is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

203it [00:41,  5.14it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where catalepsy is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

205it [00:41,  5.24it/s]

false
Determine whether the semantic relation where precursor lymphoblastic lymphoma/leukemia is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where metabolic dysfunction–associated steatotic liver disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

207it [00:41,  5.26it/s]

true
Determine whether the semantic relation where azathioprine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where breast neoplasm is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

209it [00:42,  5.43it/s]

false
Determine whether the semantic relation where prosthesis-related infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trichostrongyloidosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

211it [00:42,  5.45it/s]

true
Determine whether the semantic relation where mupirocin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where periodontal fiber is the subject, instance of is the predicate, and animal structure is the object constitutes an accurate semantic relation.

213it [00:42,  5.37it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

214it [00:43,  5.42it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

216it [00:43,  5.09it/s]

false
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prostatic intraepithelial neoplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

217it [00:43,  5.13it/s]

true
Determine whether the semantic relation where diabetic foot is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

219it [00:44,  4.99it/s]

false
Determine whether the semantic relation where listeriosis is the subject, has natural reservoir is the predicate, and water is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where loratadine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

221it [00:44,  4.95it/s]

false
Determine whether the semantic relation where Lemierre's syndrome is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetrabenazine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

223it [00:44,  5.19it/s]

false
Determine whether the semantic relation where blood plasma is the subject, studied by is the predicate, and physician is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

224it [00:45,  5.21it/s]

true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

226it [00:45,  5.26it/s]

true
Determine whether the semantic relation where glucagon-like peptide-1 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where albendazol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

227it [00:45,  5.00it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and chlordiazepoxide is the object constitutes an accurate semantic relation.

229it [00:46,  5.06it/s]

false
Determine whether the semantic relation where appendicitis is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where human follitropin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

230it [00:46,  5.10it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

232it [00:46,  4.35it/s]

false
Determine whether the semantic relation where amoxicillin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where capsaicin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

233it [00:47,  4.46it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.

235it [00:47,  4.77it/s]

true
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where West Nile fever is the subject, possible treatment is the predicate, and anticonvulsant agent is the object constitutes an accurate semantic relation.

236it [00:47,  5.00it/s]

true
Determine whether the semantic relation where erythema infectiosum is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

238it [00:47,  5.08it/s]

false
Determine whether the semantic relation where abnormal spinal curvature is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.

240it [00:48,  5.16it/s]

false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true

241it [00:48,  5.12it/s]

Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nasal irrigation is the subject, instance of is the predicate, and technology is the object constitutes an accurate semantic relation.

243it [00:48,  5.19it/s]

true
Determine whether the semantic relation where deoxycytidine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rift Valley fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

245it [00:49,  5.26it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

247it [00:49,  5.32it/s]

false
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lipofuscin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

248it [00:49,  5.27it/s]

false
Determine whether the semantic relation where fractures of human teeth is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

250it [00:50,  5.17it/s]

false
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scrub typhus is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

252it [00:50,  5.33it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

254it [00:51,  5.36it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and aneuploidy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mucocutaneous leishmaniasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

256it [00:51,  5.20it/s]

true
Determine whether the semantic relation where cataract is the subject, afflicts is the predicate, and Reptilia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

257it [00:51,  5.28it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

258it [00:51,  5.05it/s]

true
Determine whether the semantic relation where Epiregulin is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

259it [00:52,  4.47it/s]

false
Determine whether the semantic relation where anthrax is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

261it [00:52,  4.88it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral leishmaniasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

263it [00:52,  5.14it/s]

false
Determine whether the semantic relation where pulpitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Strongylus is the subject, has effect is the predicate, and medicine is the object constitutes an accurate semantic relation.

265it [00:53,  5.16it/s]

false
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eye injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

266it [00:53,  5.09it/s]

false
Determine whether the semantic relation where dengue fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

268it [00:53,  5.13it/s]

false
Determine whether the semantic relation where Apolipoprotein B is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myocardial reperfusion injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

270it [00:54,  5.31it/s]

true
Determine whether the semantic relation where pancreatic polypeptide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytidine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

272it [00:54,  5.29it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

274it [00:54,  5.34it/s]

false
Determine whether the semantic relation where avian influenza is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BRCA1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

276it [00:55,  5.28it/s]

false
Determine whether the semantic relation where magnesium is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

277it [00:55,  5.13it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

279it [00:55,  4.96it/s]

true
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.

281it [00:56,  5.05it/s]

true
Determine whether the semantic relation where lysergic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, biological process is the predicate, and hemopoiesis is the object constitutes an accurate semantic relation.

283it [00:56,  5.03it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

285it [00:57,  5.19it/s]

false
Determine whether the semantic relation where melioidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

286it [00:57,  5.30it/s]

false
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

288it [00:57,  5.19it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, possible treatment is the predicate, and analgesic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

289it [00:57,  5.15it/s]

true
Determine whether the semantic relation where (S)-(−)-colchicine is the subject, has use is the predicate, and medical research is the object constitutes an accurate semantic relation.

291it [00:58,  5.11it/s]

true
Determine whether the semantic relation where europium is the subject, named after is the predicate, and Europe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytidine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

293it [00:58,  5.14it/s]

true
Determine whether the semantic relation where glycated haemoglobin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cryptosporidiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

295it [00:59,  5.06it/s]

true
Determine whether the semantic relation where mesothelial neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

296it [00:59,  5.14it/s]

Determine whether the semantic relation where eyelid disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Alzheimer's disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

298it [00:59,  5.12it/s]

false
Determine whether the semantic relation where leukemia is the subject, symptoms and signs is the predicate, and dizziness is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

300it [01:00,  5.30it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lysergic acid diethylamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

302it [01:00,  5.34it/s]

true
Determine whether the semantic relation where migraine is the subject, drug or therapy used for treatment is the predicate, and buprenorphine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where buprenorphine is the subject, medical condition treated is the predicate, and migraine is the object constitutes an accurate semantic relation.

304it [01:00,  5.03it/s]

false
Determine whether the semantic relation where 2,4-dinitrochlorobenzene is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poliomyelitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

306it [01:01,  5.27it/s]

true
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.

307it [01:01,  5.48it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and tonsillitis is the object constitutes an accurate semantic relation.

308it [01:01,  5.31it/s]

maybe
Determine whether the semantic relation where captopril is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

310it [01:01,  5.24it/s]

true
Determine whether the semantic relation where cefuroxime is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where touching (physically feeling) is the subject, contributing factor of is the predicate, and infection is the object constitutes an accurate semantic relation.

312it [01:02,  4.55it/s]

maybe
Determine whether the semantic relation where sodium is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Equatorial Guinea is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

314it [01:02,  4.90it/s]

true
Determine whether the semantic relation where avian malaria is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Equatorial Guinea is the object constitutes an accurate semantic relation.

316it [01:03,  5.12it/s]

true
Determine whether the semantic relation where mesothelioma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lewy body dementia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

318it [01:03,  5.11it/s]

false
Determine whether the semantic relation where venous thromboembolism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

319it [01:03,  5.15it/s]

Determine whether the semantic relation where chorionic gonadotropin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chronic hepatitis C is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

321it [01:04,  5.26it/s]

false
Determine whether the semantic relation where glyco-Lutropin [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ramipril is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

322it [01:04,  5.32it/s]

false
Determine whether the semantic relation where Central African Republic is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

323it [01:04,  5.14it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Central African Republic is the object constitutes an accurate semantic relation.

324it [01:04,  4.94it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and endothelium is the object constitutes an accurate semantic relation.

326it [01:05,  4.82it/s]

true
Determine whether the semantic relation where bismuth is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where preterm birth is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

327it [01:05,  4.80it/s]

false
Determine whether the semantic relation where albendazol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

328it [01:05,  4.67it/s]

false
Determine whether the semantic relation where pasteurellosis is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

330it [01:06,  4.89it/s]

true
Determine whether the semantic relation where scarlet fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HIV/AIDS is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

332it [01:06,  5.08it/s]

false
Determine whether the semantic relation where Chad is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Babesiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

334it [01:06,  5.17it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Chad is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thrombotic microangiopathy is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

336it [01:07,  5.17it/s]

maybe
Determine whether the semantic relation where nonvital tooth is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where rhinitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

338it [01:07,  5.00it/s]

maybe
Determine whether the semantic relation where sex hormone binding globulin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, possible treatment is the predicate, and tranquilizer is the object constitutes an accurate semantic relation.

340it [01:08,  5.30it/s]

false
Determine whether the semantic relation where growth hormone releasing hormone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where childhood obesity is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

341it [01:08,  5.19it/s]

true
Determine whether the semantic relation where ethidium bromide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

343it [01:08,  5.15it/s]

Determine whether the semantic relation where dextroamphetamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where problem gambling is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

345it [01:08,  5.25it/s]

true
Determine whether the semantic relation where indican is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbohydrate metabolic disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

346it [01:09,  5.25it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

347it [01:09,  5.04it/s]

true
Determine whether the semantic relation where chickenpox is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

348it [01:09,  4.95it/s]

false
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, first aid measures is the predicate, and artificial respiration is the object constitutes an accurate semantic relation.

350it [01:10,  5.07it/s]

true
Determine whether the semantic relation where bromocriptine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.

352it [01:10,  5.18it/s]

true
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where droperidol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

353it [01:10,  5.24it/s]

false
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and hepatitis is the object constitutes an accurate semantic relation.

355it [01:10,  5.32it/s]

false
Determine whether the semantic relation where lead poisoning is the subject, first aid measures is the predicate, and artificial respiration is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bromocriptine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

357it [01:11,  5.24it/s]

false
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and insomnia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pectus excavatum is the subject, health specialty is the predicate, and genetics is the object constitutes an accurate semantic relation.

358it [01:11,  5.31it/s]

false
Determine whether the semantic relation where clozapine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

359it [01:11,  5.05it/s]

true
Determine whether the semantic relation where infectious mononucleosis is the subject, possible treatment is the predicate, and histamine antagonist is the object constitutes an accurate semantic relation.

360it [01:12,  3.44it/s]

false
Determine whether the semantic relation where Honduras is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

361it [01:12,  3.70it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Honduras is the object constitutes an accurate semantic relation.

362it [01:12,  3.87it/s]

true
Determine whether the semantic relation where arteriosclerosis is the subject, has cause is the predicate, and man is the object constitutes an accurate semantic relation.

363it [01:12,  4.01it/s]

false
Determine whether the semantic relation where brucellosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

365it [01:13,  4.28it/s]

false
Determine whether the semantic relation where life is the subject, has part(s) is the predicate, and metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where life is the subject, has characteristic is the predicate, and metabolism is the object constitutes an accurate semantic relation.

367it [01:13,  4.62it/s]

true
Determine whether the semantic relation where cefuroxime is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sumatriptan is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

369it [01:14,  4.87it/s]

false
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cefoxitin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

371it [01:14,  5.03it/s]

true
Determine whether the semantic relation where Asperger syndrome is the subject, different from is the predicate, and Alzheimer's disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Alzheimer's disease is the subject, different from is the predicate, and Asperger syndrome is the object constitutes an accurate semantic relation.

372it [01:14,  5.04it/s]

true
Determine whether the semantic relation where hymenolepiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

373it [01:14,  4.80it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

375it [01:15,  4.96it/s]

false
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ornithosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

377it [01:15,  5.06it/s]

false
Determine whether the semantic relation where hepatitis E is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gonorrhea is the subject, anatomical location is the predicate, and meninges is the object constitutes an accurate semantic relation.

378it [01:15,  5.10it/s]

false
Determine whether the semantic relation where zalcitabine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

380it [01:16,  5.03it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

382it [01:16,  5.25it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

384it [01:17,  5.18it/s]

true
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

386it [01:17,  5.19it/s]

true
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where hypertrophic cardiomyopathy is the subject, symptoms and signs is the predicate, and vertigo is the object constitutes an accurate semantic relation.

388it [01:17,  5.33it/s]

true
Determine whether the semantic relation where Matrix metallopeptidase 3 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lyme disease is the subject, symptoms and signs is the predicate, and hypertrophic cardiomyopathy is the object constitutes an accurate semantic relation.

389it [01:18,  5.22it/s]

false
Determine whether the semantic relation where yaws is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

391it [01:18,  4.99it/s]

false
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adenosquamous carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

392it [01:18,  5.01it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and insomnia is the object constitutes an accurate semantic relation.

393it [01:18,  4.87it/s]

true
Determine whether the semantic relation where muscarine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

394it [01:19,  4.85it/s]

false
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and ulcer is the object constitutes an accurate semantic relation.

396it [01:19,  4.98it/s]

false
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mediterranean Sea is the subject, basin country is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

398it [01:19,  5.16it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytidine triphosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

399it [01:20,  4.77it/s]

true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and cardiac arrest is the object constitutes an accurate semantic relation.

401it [01:20,  4.98it/s]

maybe
Determine whether the semantic relation where verapamil is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

403it [01:20,  5.03it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Norway is the object constitutes an accurate semantic relation.

405it [01:21,  5.12it/s]

false
Determine whether the semantic relation where diverticulitis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

407it [01:21,  5.14it/s]

true
Determine whether the semantic relation where avian sarcoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

409it [01:22,  5.32it/s]

false
Determine whether the semantic relation where dopamine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where life is the subject, studied by is the predicate, and life sciences is the object constitutes an accurate semantic relation.

411it [01:22,  5.13it/s]

true
Determine whether the semantic relation where tongue disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false

412it [01:22,  5.11it/s]

Determine whether the semantic relation where life sciences is the subject, is the study of is the predicate, and life is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 7 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

413it [01:22,  5.17it/s]

true
Determine whether the semantic relation where bromodeoxyuridine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

414it [01:23,  5.06it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

415it [01:23,  4.97it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

417it [01:23,  5.02it/s]

true
Determine whether the semantic relation where geographic atrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where experimental autoimmune encephalomyelitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

419it [01:24,  5.21it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

420it [01:24,  4.78it/s]

true
Determine whether the semantic relation where carcinosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

421it [01:24,  4.79it/s]

true
Determine whether the semantic relation where dengue fever is the subject, possible treatment is the predicate, and diuretic is the object constitutes an accurate semantic relation.

423it [01:24,  4.92it/s]

false
Determine whether the semantic relation where Machado-Joseph disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Gabon is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

425it [01:25,  5.02it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Gabon is the object constitutes an accurate semantic relation.
true

426it [01:25,  5.02it/s]

Determine whether the semantic relation where chromoblastomycosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where RAST test is the subject, subclass of is the predicate, and blood test is the object constitutes an accurate semantic relation.

428it [01:25,  5.05it/s]

true
Determine whether the semantic relation where thyrotropin-releasing hormone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

430it [01:26,  5.22it/s]

false
Determine whether the semantic relation where atypical hemolytic uremic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatocellular carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

431it [01:26,  5.25it/s]

true
Determine whether the semantic relation where solute carrier family 4 member 1 (Diego blood group) is the subject, biological process is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.

433it [01:26,  5.19it/s]

false
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

434it [01:27,  4.88it/s]

true
Determine whether the semantic relation where plant disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

436it [01:27,  4.97it/s]

true
Determine whether the semantic relation where amyloidosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

438it [01:27,  5.08it/s]

true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smallpox is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

440it [01:28,  5.16it/s]

true
Determine whether the semantic relation where pneumonia is the subject, symptoms and signs is the predicate, and snoring is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where clavulanic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

441it [01:28,  4.97it/s]

true
Determine whether the semantic relation where nasopharyngeal disease is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

443it [01:28,  5.03it/s]

false
Determine whether the semantic relation where transitional cell carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibrinolysin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

445it [01:29,  5.14it/s]

false
Determine whether the semantic relation where glucose is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where infectious mononucleosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

447it [01:29,  5.11it/s]

false
Determine whether the semantic relation where paroxetine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fasciitis is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

448it [01:29,  5.24it/s]

false
Determine whether the semantic relation where pressure ulcer is the subject, drug or therapy used for treatment is the predicate, and nitric oxide is the object constitutes an accurate semantic relation.

449it [01:30,  4.20it/s]

false
Determine whether the semantic relation where typhoid fever is the subject, possible treatment is the predicate, and diet is the object constitutes an accurate semantic relation.

450it [01:30,  4.25it/s]

true
Determine whether the semantic relation where vitamin B12 deficiency is the subject, symptoms and signs is the predicate, and cardiomyopathy is the object constitutes an accurate semantic relation.

452it [01:30,  4.62it/s]

true
Determine whether the semantic relation where meningococcal disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

453it [01:30,  4.74it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

455it [01:31,  4.82it/s]

false
Determine whether the semantic relation where Retinol binding protein 4 is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

457it [01:31,  4.98it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

458it [01:31,  5.08it/s]

true
Determine whether the semantic relation where parasitic pregnancy complication is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

460it [01:32,  4.91it/s]

true
Determine whether the semantic relation where anaplastic thyroid carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic atrophic rhinitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

461it [01:32,  4.99it/s]

false
Determine whether the semantic relation where pouchitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

462it [01:32,  4.97it/s]

true
Determine whether the semantic relation where tularemia is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

464it [01:33,  4.97it/s]

false
Determine whether the semantic relation where Marburg virus disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where necrotizing enterocolitis is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

465it [01:33,  5.08it/s]

false
Determine whether the semantic relation where mebendazole is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

467it [01:33,  4.92it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Togo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where physostigmine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

468it [01:34,  4.71it/s]

false
Determine whether the semantic relation where Togo is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

470it [01:34,  4.65it/s]

true
Determine whether the semantic relation where acute myeloid leukemia is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prostate neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

472it [01:34,  4.78it/s]

true
Determine whether the semantic relation where ketorolac is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where influenza is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

474it [01:35,  4.75it/s]

false
Determine whether the semantic relation where actinomycosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where electrostimulation is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

475it [01:35,  4.84it/s]

true
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

476it [01:35,  4.80it/s]

false
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

478it [01:36,  4.71it/s]

false
Determine whether the semantic relation where bladder disease is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hematoma is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

479it [01:36,  4.77it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and heart is the object constitutes an accurate semantic relation.

481it [01:36,  4.70it/s]

false
Determine whether the semantic relation where bladder neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

482it [01:36,  4.92it/s]

Determine whether the semantic relation where chordoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where giardiasis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

484it [01:37,  5.21it/s]

true
Determine whether the semantic relation where folinic acid is the subject, subclass of is the predicate, and lactam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where serotonin is the subject, found in taxon is the predicate, and Q146555 is the object constitutes an accurate semantic relation.

486it [01:37,  5.19it/s]

false
Determine whether the semantic relation where pulicosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

488it [01:38,  5.32it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

490it [01:38,  5.34it/s]

true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bismuth is the subject, medical condition treated is the predicate, and viral infectious disease is the object constitutes an accurate semantic relation.

491it [01:38,  5.36it/s]

false
Determine whether the semantic relation where viral infectious disease is the subject, drug or therapy used for treatment is the predicate, and bismuth is the object constitutes an accurate semantic relation.

492it [01:38,  5.22it/s]

false
Determine whether the semantic relation where cefoxitin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

493it [01:39,  4.93it/s]

true
Determine whether the semantic relation where cholangiocarcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

495it [01:39,  4.95it/s]

true
Determine whether the semantic relation where filarial elephantiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chikungunya is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

497it [01:39,  4.91it/s]

true
Determine whether the semantic relation where chikungunya is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

498it [01:40,  4.75it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

499it [01:40,  4.47it/s]

true
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

501it [01:40,  4.39it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nasopharyngeal neoplasm is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

503it [01:41,  4.67it/s]

false
Determine whether the semantic relation where post-concussion syndrome is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

505it [01:41,  5.10it/s]

false
Determine whether the semantic relation where intraductal carcinoma of the breast is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

507it [01:42,  5.27it/s]

false
Determine whether the semantic relation where metabolic syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where necrotizing enterocolitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

509it [01:42,  5.09it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and immune system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where appendicitis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

511it [01:42,  5.11it/s]

false
Determine whether the semantic relation where listeriosis is the subject, has natural reservoir is the predicate, and grain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

513it [01:43,  5.19it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipid pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

515it [01:43,  5.18it/s]

false
Determine whether the semantic relation where Proliferating cell nuclear antigen is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxalic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

517it [01:43,  5.20it/s]

false
Determine whether the semantic relation where adolescent psychology is the subject, instance of is the predicate, and specialization is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

518it [01:44,  5.24it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

520it [01:44,  4.89it/s]

false
Determine whether the semantic relation where histology is the subject, different from is the predicate, and history is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where history is the subject, different from is the predicate, and histology is the object constitutes an accurate semantic relation.

521it [01:44,  5.02it/s]

false
Determine whether the semantic relation where Western equine encephalitis is the subject, anatomical location is the predicate, and brain is the object constitutes an accurate semantic relation.

523it [01:45,  4.97it/s]

true
Determine whether the semantic relation where hepatic encephalopathy is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

525it [01:45,  5.20it/s]

false
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

527it [01:45,  5.22it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

528it [01:46,  5.14it/s]

true
Determine whether the semantic relation where Togo is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

529it [01:46,  4.67it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Togo is the object constitutes an accurate semantic relation.

531it [01:46,  4.66it/s]

true
Determine whether the semantic relation where artificial animal shelter is the subject, creator is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, biological process is the predicate, and feeding behavior is the object constitutes an accurate semantic relation.

532it [01:47,  4.79it/s]

false
Determine whether the semantic relation where methylmalonic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

534it [01:47,  4.88it/s]

true
Determine whether the semantic relation where guanethidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, anatomical location is the predicate, and blood vessel is the object constitutes an accurate semantic relation.

536it [01:47,  4.93it/s]

false
Determine whether the semantic relation where Taenia solium is the subject, main food source is the predicate, and amino acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Turkmenistan is the object constitutes an accurate semantic relation.

538it [01:48,  5.23it/s]

true
Determine whether the semantic relation where Turkmenistan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where levomepromazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

539it [01:48,  4.86it/s]

true
Determine whether the semantic relation where West Nile fever is the subject, possible treatment is the predicate, and diuretic is the object constitutes an accurate semantic relation.

540it [01:48,  4.86it/s]

false
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

542it [01:49,  4.89it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, afflicts is the predicate, and skin is the object constitutes an accurate semantic relation.

544it [01:49,  5.14it/s]

true
Determine whether the semantic relation where Phytoplasma is the subject, Gram staining is the predicate, and gram-positive bacteria is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carcinoma is the subject, drug or therapy used for treatment is the predicate, and lidocaine is the object constitutes an accurate semantic relation.

545it [01:49,  5.18it/s]

false
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

547it [01:50,  5.06it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blastocystosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

549it [01:50,  4.98it/s]

true
Determine whether the semantic relation where lysergic acid diethylamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where deoxythymidine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

551it [01:50,  5.00it/s]

false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where menopause is the subject, part of is the predicate, and development of the human body is the object constitutes an accurate semantic relation.

552it [01:51,  5.09it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

554it [01:51,  5.01it/s]

true
Determine whether the semantic relation where asbestosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DNA repair is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.

556it [01:51,  5.21it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Silybum marianum is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

558it [01:52,  4.99it/s]

true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

559it [01:52,  4.71it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

561it [01:52,  4.85it/s]

false
Determine whether the semantic relation where heroin dependence is the subject, symptoms and signs is the predicate, and cognitive dysfunction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vinblastine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

562it [01:53,  4.69it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

564it [01:53,  4.78it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam War is the subject, participant is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

565it [01:53,  4.95it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

566it [01:53,  4.92it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

568it [01:54,  4.97it/s]

true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pilocarpine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

570it [01:54,  4.82it/s]

false
Determine whether the semantic relation where Raynaud disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Guinea-Bissau is the object constitutes an accurate semantic relation.

572it [01:55,  4.85it/s]

true
Determine whether the semantic relation where Guinea-Bissau is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

574it [01:55,  5.07it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, first aid measures is the predicate, and airway management is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where β-alanine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

575it [01:55,  5.11it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

577it [01:56,  5.03it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

578it [01:56,  5.04it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.

580it [01:56,  4.95it/s]

true
Determine whether the semantic relation where toxoplasmosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.

582it [01:57,  5.15it/s]

true
Determine whether the semantic relation where aseptic meningitis is the subject, medical examination is the predicate, and microscopy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 9 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

584it [01:57,  5.10it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

585it [01:57,  5.00it/s]

true
Determine whether the semantic relation where myometrium is the subject, has use is the predicate, and reflex is the object constitutes an accurate semantic relation.

587it [01:58,  5.04it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

589it [01:58,  5.19it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

591it [01:58,  5.24it/s]

false
Determine whether the semantic relation where epidemic typhus is the subject, anatomical location is the predicate, and central nervous system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

592it [01:59,  5.04it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

594it [01:59,  4.95it/s]

true
Determine whether the semantic relation where equine Strongyle infections is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thalidomide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

596it [01:59,  5.00it/s]

false
Determine whether the semantic relation where hematoporphyrin derivative is the subject, instance of is the predicate, and complex mixture is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

597it [02:00,  5.03it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

598it [02:00,  4.77it/s]

true
Determine whether the semantic relation where pelvic floor is the subject, subclass of is the predicate, and animal structure is the object constitutes an accurate semantic relation.

599it [02:00,  4.73it/s]

true
Determine whether the semantic relation where anastomotic leak is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

601it [02:01,  4.57it/s]

false
Determine whether the semantic relation where Lassa fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tamoxifen is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

603it [02:01,  4.84it/s]

false
Determine whether the semantic relation where bisphosphonate-associated osteonecrosis of the jaw is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary schistosomiasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

604it [02:01,  4.95it/s]

true
Determine whether the semantic relation where guanine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

606it [02:02,  4.97it/s]

false
Determine whether the semantic relation where cysticercosis is the subject, subclass of is the predicate, and heart disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where noise-induced hearing loss is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

608it [02:02,  5.09it/s]

false
Determine whether the semantic relation where myofascial pain syndrome is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chikungunya is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

610it [02:02,  5.23it/s]

false
Determine whether the semantic relation where omeprazole is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

611it [02:03,  5.21it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

613it [02:03,  5.07it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true

614it [02:03,  5.09it/s]

Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

616it [02:04,  5.15it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

617it [02:04,  5.28it/s]

true
Determine whether the semantic relation where cryptosporidiosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

618it [02:04,  5.15it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

620it [02:04,  5.05it/s]

true
Determine whether the semantic relation where human digestive system is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where drug-induced hepatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

621it [02:05,  5.08it/s]

true
Determine whether the semantic relation where drug-induced hepatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

623it [02:05,  5.04it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and human digestive system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis C is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

625it [02:05,  4.97it/s]

true
Determine whether the semantic relation where Helicobacter infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where esthesioneuroblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

627it [02:06,  4.85it/s]

true
Determine whether the semantic relation where residual neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

628it [02:06,  4.85it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

630it [02:06,  4.55it/s]

true
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true

631it [02:07,  4.81it/s]

Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

633it [02:07,  4.87it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

635it [02:08,  4.56it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ketorolac is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

636it [02:08,  4.78it/s]

false
Determine whether the semantic relation where n-pentyl nitrite is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

638it [02:08,  4.81it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cameroon is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

640it [02:09,  5.02it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Cameroon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where technetium is the subject, location of discovery is the predicate, and Italy is the object constitutes an accurate semantic relation.

642it [02:09,  5.25it/s]

false
Determine whether the semantic relation where middle age is the subject, subclass of is the predicate, and development of the human body is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where leprosy is the subject, drug or therapy used for treatment is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

643it [02:09,  5.09it/s]

true
Determine whether the semantic relation where fasciolosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

645it [02:09,  5.11it/s]

true
Determine whether the semantic relation where fasciolosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fenofibrate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

647it [02:10,  5.15it/s]

false
Determine whether the semantic relation where animal feed is the subject, subclass of is the predicate, and disposable product is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trachoma is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

649it [02:10,  5.30it/s]

false
Determine whether the semantic relation where postterm pregnancy is the subject, has effect is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

650it [02:10,  5.18it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

651it [02:11,  4.89it/s]

true
Determine whether the semantic relation where hepatitis B is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

653it [02:11,  4.88it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

654it [02:11,  5.00it/s]

true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

656it [02:12,  4.95it/s]

false
Determine whether the semantic relation where saccharin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

658it [02:12,  5.06it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pseudouridine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

659it [02:12,  5.14it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

660it [02:12,  5.00it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

662it [02:13,  4.87it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and medical ultrasonography is the object constitutes an accurate semantic relation.

664it [02:13,  4.47it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

665it [02:14,  4.45it/s]

true
Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

666it [02:14,  4.33it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

668it [02:14,  4.74it/s]

true
Determine whether the semantic relation where ameloblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

670it [02:15,  5.01it/s]

true
Determine whether the semantic relation where local neoplasm recurrence is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

672it [02:15,  5.16it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyanide poisoning is the subject, subclass of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

674it [02:15,  5.29it/s]

false
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and back pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anisakiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

675it [02:16,  5.39it/s]

true
Determine whether the semantic relation where oxycodone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

677it [02:16,  5.15it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and echocardiography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where silicotuberculosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

679it [02:16,  5.25it/s]

true
Determine whether the semantic relation where lipid storage disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

681it [02:17,  5.31it/s]

true
Determine whether the semantic relation where dihydroergotamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

683it [02:17,  5.35it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

684it [02:17,  4.70it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

685it [02:18,  4.72it/s]

false
Determine whether the semantic relation where lac repressor is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

686it [02:18,  4.50it/s]

false
Determine whether the semantic relation where uric acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

688it [02:18,  4.72it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

690it [02:19,  4.98it/s]

true
Determine whether the semantic relation where nitroglycerin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where RNA folding is the subject, subclass of is the predicate, and cellular process or phenomenon is the object constitutes an accurate semantic relation.

692it [02:19,  5.12it/s]

true
Determine whether the semantic relation where piracetam is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

694it [02:19,  5.17it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

696it [02:20,  5.04it/s]

true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

697it [02:20,  4.80it/s]

false
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

699it [02:20,  4.85it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

701it [02:21,  5.21it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

703it [02:21,  5.28it/s]

true
Determine whether the semantic relation where in situ carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

705it [02:22,  5.27it/s]

false
Determine whether the semantic relation where sulindac is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chad is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

706it [02:22,  5.15it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, first aid measures is the predicate, and artificial respiration is the object constitutes an accurate semantic relation.

708it [02:22,  4.98it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Chad is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diverticulitis of colon is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

710it [02:23,  5.10it/s]

true
Determine whether the semantic relation where pancreatic polypeptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where substance P is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

712it [02:23,  5.04it/s]

false
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false

713it [02:23,  5.24it/s]

Determine whether the semantic relation where St. Louis encephalitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tyrosine kinase with immunoglobulin like and EGF like domains 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

715it [02:24,  5.38it/s]

false
Determine whether the semantic relation where post-thrombotic syndrome is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

717it [02:24,  5.31it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, biological process is the predicate, and fertilization is the object constitutes an accurate semantic relation.

718it [02:24,  5.39it/s]

false
Determine whether the semantic relation where East Germany is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

720it [02:24,  5.22it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and East Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amantadine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

722it [02:25,  5.14it/s]

true
Determine whether the semantic relation where Gabon is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, possible treatment is the predicate, and diet is the object constitutes an accurate semantic relation.

724it [02:25,  5.34it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Gabon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

726it [02:26,  4.94it/s]

true
Determine whether the semantic relation where RUNX family transcription factor 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where guanine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

727it [02:26,  5.00it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.

728it [02:26,  4.76it/s]

true
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

729it [02:26,  4.54it/s]

true
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

730it [02:27,  4.51it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.

732it [02:27,  4.72it/s]

true
Determine whether the semantic relation where trichotillomania is the subject, has cause is the predicate, and stress is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clindamycin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

734it [02:27,  4.94it/s]

true
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where enalapril is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

736it [02:28,  5.19it/s]

false
Determine whether the semantic relation where Bahrain is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Bahrain is the object constitutes an accurate semantic relation.

738it [02:28,  5.20it/s]

true
Determine whether the semantic relation where listeriosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (−)-nicotine is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

739it [02:28,  5.14it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

741it [02:29,  5.16it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lassa fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

742it [02:29,  5.18it/s]

false
Determine whether the semantic relation where tooth brushing is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true

743it [02:29,  5.11it/s]

Determine whether the semantic relation where cocaine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

745it [02:30,  5.03it/s]

true
Determine whether the semantic relation where cartilage fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mupirocin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

747it [02:30,  5.16it/s]

true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily D member 6 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.

749it [02:30,  5.25it/s]

false
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erysipelas is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

750it [02:31,  4.48it/s]

false
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false

752it [02:31,  4.81it/s]

Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

754it [02:31,  5.00it/s]

true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

756it [02:32,  4.60it/s]

false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

757it [02:32,  4.64it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false

758it [02:32,  4.73it/s]

Determine whether the semantic relation where pulse wave analysis is the subject, instance of is the predicate, and engineering is the object constitutes an accurate semantic relation.

760it [02:33,  4.85it/s]

false
Determine whether the semantic relation where lansoprazole is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholera is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

762it [02:33,  5.03it/s]

false
Determine whether the semantic relation where Porcine enzootic pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thy-1 cell surface antigen is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

764it [02:33,  5.12it/s]

false
Determine whether the semantic relation where serotonin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and fear is the object constitutes an accurate semantic relation.

765it [02:34,  5.12it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

767it [02:34,  5.01it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

768it [02:34,  5.05it/s]

true
Determine whether the semantic relation where bronchopulmonary dysplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

770it [02:35,  5.06it/s]

true
Determine whether the semantic relation where Taiwan is the subject, religion or worldview is the predicate, and Islam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bed is the subject, has use is the predicate, and human sexual behavior is the object constitutes an accurate semantic relation.

771it [02:35,  5.10it/s]

false
Determine whether the semantic relation where life is the subject, studied by is the predicate, and biology is the object constitutes an accurate semantic relation.

773it [02:35,  5.07it/s]

true
Determine whether the semantic relation where biology is the subject, is the study of is the predicate, and life is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

775it [02:36,  5.09it/s]

true
Determine whether the semantic relation where pancreatic polypeptide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

777it [02:36,  5.20it/s]

true
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.

778it [02:36,  5.29it/s]

false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

780it [02:37,  5.16it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

782it [02:37,  5.27it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where virulence factor is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.

784it [02:37,  5.04it/s]

false
Determine whether the semantic relation where mantle cell lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Parkinson's disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

786it [02:38,  5.22it/s]

false
Determine whether the semantic relation where guanosine is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alpha-melanocyte-stimulating hormone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

787it [02:38,  5.11it/s]

false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily D member 6 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

789it [02:38,  5.01it/s]

true
Determine whether the semantic relation where ramipril is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where postmenopausal osteoporosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

791it [02:39,  5.02it/s]

true
Determine whether the semantic relation where animal disease model is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

793it [02:39,  5.22it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where corneal endothelial cell loss is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

795it [02:40,  5.24it/s]

false
Determine whether the semantic relation where phalloidin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.

796it [02:40,  4.86it/s]

false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

797it [02:40,  4.51it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

799it [02:40,  4.69it/s]

true
Determine whether the semantic relation where ehrlichiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chenodiol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

801it [02:41,  4.99it/s]

true
Determine whether the semantic relation where toxemia is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where molecular docking is the subject, has use is the predicate, and science is the object constitutes an accurate semantic relation.

803it [02:41,  5.02it/s]

false
Determine whether the semantic relation where (RS)-ibotenic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where avian influenza is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

805it [02:42,  5.11it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Turkey is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

806it [02:42,  5.21it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

808it [02:42,  5.04it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, biological process is the predicate, and fertilization is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sulindac is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

810it [02:43,  5.29it/s]

true
Determine whether the semantic relation where sirolimus is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

812it [02:43,  5.28it/s]

true
Determine whether the semantic relation where leukemia is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where swine erysipelas is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

813it [02:43,  4.92it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

815it [02:44,  4.94it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diphenhydramine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

817it [02:44,  5.14it/s]

false
Determine whether the semantic relation where tobacco use disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-deoxy-D-glucose is the subject, subject has role is the predicate, and antiviral agent is the object constitutes an accurate semantic relation.

819it [02:44,  5.07it/s]

false
Determine whether the semantic relation where measles is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where uric acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

821it [02:45,  4.75it/s]

false
Determine whether the semantic relation where agglutinin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

822it [02:45,  4.44it/s]

true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, medical condition treated is the predicate, and amyloidosis is the object constitutes an accurate semantic relation.

823it [02:45,  4.53it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

825it [02:46,  4.74it/s]

true
Determine whether the semantic relation where amyloidosis is the subject, drug or therapy used for treatment is the predicate, and N-acetyl-L-cysteine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and unconsciousness is the object constitutes an accurate semantic relation.

827it [02:46,  5.07it/s]

true
Determine whether the semantic relation where doxorubicin is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

829it [02:46,  5.22it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psychoanalysis is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

831it [02:47,  4.92it/s]

true
Determine whether the semantic relation where mucinous cystadenoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and sleep-wake disorder is the object constitutes an accurate semantic relation.

832it [02:47,  4.87it/s]

false
Determine whether the semantic relation where sleep-wake disorder is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

834it [02:47,  4.91it/s]

false
Determine whether the semantic relation where podofilox is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichomoniasis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

835it [02:48,  4.90it/s]

false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

836it [02:48,  4.90it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

838it [02:48,  4.92it/s]

false
Determine whether the semantic relation where psoriatic arthritis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ifosfamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

840it [02:49,  4.99it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

841it [02:49,  5.13it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

843it [02:49,  5.15it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sarcoidosis is the subject, possible treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

845it [02:50,  5.24it/s]

false
Determine whether the semantic relation where leishmaniasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin ethylsuccinate is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

847it [02:50,  5.17it/s]

false
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

849it [02:50,  5.31it/s]

true
Determine whether the semantic relation where nervous system lysosomal storage disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

851it [02:51,  5.27it/s]

true
Determine whether the semantic relation where Guinea-Bissau is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

853it [02:51,  5.29it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

855it [02:52,  5.05it/s]

false
Determine whether the semantic relation where Fli-1 proto-oncogene, ETS transcription factor is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

856it [02:52,  5.07it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

858it [02:52,  5.14it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mumps is the subject, anatomical location is the predicate, and meninges is the object constitutes an accurate semantic relation.

860it [02:53,  5.25it/s]

false
Determine whether the semantic relation where basophil adenoma is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

861it [02:53,  5.37it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

863it [02:53,  5.22it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

865it [02:54,  5.27it/s]

true
Determine whether the semantic relation where jaw disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where animal helminthiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

867it [02:54,  5.38it/s]

true
Determine whether the semantic relation where sulfasalazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where synovial sarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

868it [02:54,  5.46it/s]

true
Determine whether the semantic relation where Gerstmann-Straussler-Scheinker syndrome is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

870it [02:54,  5.18it/s]

false
Determine whether the semantic relation where clavulanic acid is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false

871it [02:55,  5.26it/s]

Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

873it [02:55,  5.24it/s]

false
Determine whether the semantic relation where hand, foot and mouth disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenogenital disease is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

875it [02:55,  5.15it/s]

false
Determine whether the semantic relation where taurocholic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where programmed cell death 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

876it [02:56,  4.98it/s]

true
Determine whether the semantic relation where oxycodone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

878it [02:56,  4.84it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

879it [02:56,  4.82it/s]

true
Determine whether the semantic relation where Suriname is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

881it [02:57,  4.83it/s]

true
Determine whether the semantic relation where Neuropeptide Y is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Suriname is the object constitutes an accurate semantic relation.

882it [02:57,  4.95it/s]

true
Determine whether the semantic relation where tungsten is the subject, location of discovery is the predicate, and Spain is the object constitutes an accurate semantic relation.

884it [02:57,  5.00it/s]

false
Determine whether the semantic relation where nifedipine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metastasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

886it [02:58,  5.26it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

888it [02:58,  5.26it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

890it [02:58,  5.22it/s]

true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and hallucination is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nevirapine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

891it [02:59,  5.22it/s]

false
Determine whether the semantic relation where erysipelothrix rhusiopathiae infectious disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

893it [02:59,  4.99it/s]

false
Determine whether the semantic relation where lipoma is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ras subfamily is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

894it [02:59,  4.33it/s]

false
Determine whether the semantic relation where scrapie is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

896it [03:00,  4.60it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

898it [03:00,  4.61it/s]

true
Determine whether the semantic relation where placenta praevia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

900it [03:01,  4.88it/s]

true
Determine whether the semantic relation where dirofilariasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bulbar polio is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

901it [03:01,  4.93it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.

903it [03:01,  4.98it/s]

false
Determine whether the semantic relation where hepatitis B is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitronectin is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

904it [03:01,  5.11it/s]

false
Determine whether the semantic relation where bone development disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

906it [03:02,  5.03it/s]

false
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

907it [03:02,  5.20it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

909it [03:02,  5.05it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ERBB2 is the subject, expressed in is the predicate, and kidney is the object constitutes an accurate semantic relation.

910it [03:03,  5.02it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

911it [03:03,  4.93it/s]

true
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

912it [03:03,  4.91it/s]

true
Determine whether the semantic relation where scrub typhus is the subject, anatomical location is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

914it [03:03,  5.09it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

916it [03:04,  5.20it/s]

true
Determine whether the semantic relation where chlorhexidine is the subject, inhibitor of is the predicate, and growth is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where disease of cellular proliferation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

918it [03:04,  5.12it/s]

true
Determine whether the semantic relation where iodine is the subject, location of discovery is the predicate, and Paris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where invasive pulmonary aspergillosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

919it [03:04,  5.14it/s]

true
Determine whether the semantic relation where tuberous sclerosis is the subject, different from is the predicate, and tuberculosis is the object constitutes an accurate semantic relation.

921it [03:05,  5.01it/s]

true
Determine whether the semantic relation where urethral neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ritter's disease is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.

922it [03:05,  4.86it/s]

true
Determine whether the semantic relation where AT-rich interaction domain 4A is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

923it [03:05,  4.81it/s]

false
Determine whether the semantic relation where giant cell arteritis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

925it [03:06,  4.82it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

927it [03:06,  4.89it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

929it [03:06,  5.06it/s]

true
Determine whether the semantic relation where hymenolepiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dicyclohexylcarbodiimide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

931it [03:07,  5.10it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and endocrine system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where loratadine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

933it [03:07,  5.02it/s]

false
Determine whether the semantic relation where Lyme disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, symptoms and signs is the predicate, and paralysis is the object constitutes an accurate semantic relation.

934it [03:07,  4.75it/s]

true
Determine whether the semantic relation where wood is the subject, subclass of is the predicate, and tissue is the object constitutes an accurate semantic relation.

936it [03:08,  4.93it/s]

false
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

938it [03:08,  5.20it/s]

true
Determine whether the semantic relation where cefuroxime is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fluoxetine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

940it [03:09,  5.30it/s]

false
Determine whether the semantic relation where martial arts is the subject, subclass of is the predicate, and art is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily D member 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

941it [03:09,  5.15it/s]

false
Determine whether the semantic relation where Eswatini is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

943it [03:09,  5.14it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Eswatini is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

944it [03:09,  4.92it/s]

false
Determine whether the semantic relation where serous glue ear is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

946it [03:10,  5.05it/s]

false
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxytocin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

947it [03:10,  5.10it/s]

false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

949it [03:10,  5.03it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where morphine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

951it [03:11,  5.27it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

953it [03:11,  5.29it/s]

true
Determine whether the semantic relation where ciguatera is the subject, symptoms and signs is the predicate, and cardiovascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-citrulline is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

954it [03:11,  4.80it/s]

false
Determine whether the semantic relation where Japanese encephalitis is the subject, possible treatment is the predicate, and diuretic is the object constitutes an accurate semantic relation.

956it [03:12,  4.63it/s]

false
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where argon is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

957it [03:12,  4.86it/s]

false
Determine whether the semantic relation where Rwanda is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

959it [03:12,  4.89it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Rwanda is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thyroid-stimulating hormone is the subject, subclass of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

960it [03:13,  5.01it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

962it [03:13,  5.20it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KiSS-1 metastasis suppressor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

963it [03:13,  5.24it/s]

true
Determine whether the semantic relation where Kawasaki disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

964it [03:13,  4.70it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true

966it [03:14,  4.94it/s]

Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethionamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

968it [03:14,  4.76it/s]

true
Determine whether the semantic relation where mitochondrial disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and heart failure is the object constitutes an accurate semantic relation.

969it [03:14,  4.92it/s]

false
Determine whether the semantic relation where adult T-cell leukemia/lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

970it [03:15,  4.94it/s]

Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

971it [03:15,  4.88it/s]

true
Determine whether the semantic relation where campylobacteriosis is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

973it [03:15,  5.03it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ovarian hyperstimulation syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

975it [03:16,  4.80it/s]

true
Determine whether the semantic relation where myalgic encephalomyelitis/chronic fatigue syndrome is the subject, symptoms and signs is the predicate, and lymph node is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fluphenazine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

977it [03:16,  4.95it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

978it [03:16,  5.10it/s]

true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

980it [03:17,  5.21it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neuropeptide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

982it [03:17,  5.41it/s]

false
Determine whether the semantic relation where bovine malignant catarrhal fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where galantamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

984it [03:17,  5.34it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

985it [03:18,  5.16it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

987it [03:18,  5.19it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

989it [03:18,  5.20it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Egypt is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

991it [03:19,  5.21it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylenetetrahydrofolate reductase is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

993it [03:19,  5.08it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

995it [03:20,  5.13it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

997it [03:20,  5.05it/s]

false
Determine whether the semantic relation where Pepsinogen A5 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where knee osteoarthritis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

999it [03:20,  5.03it/s]

true
Determine whether the semantic relation where tick infestation is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pseudomembranous colitis is the subject, symptoms and signs is the predicate, and itch is the object constitutes an accurate semantic relation.

1000it [03:21,  5.14it/s]

false
Determine whether the semantic relation where classical swine fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1002it [03:21,  4.37it/s]

true
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

1003it [03:21,  4.59it/s]

true
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1005it [03:22,  4.84it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

1007it [03:22,  5.12it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

1009it [03:22,  5.22it/s]

true
Determine whether the semantic relation where cimetidine is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where premature atrial contraction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1011it [03:23,  5.19it/s]

false
Determine whether the semantic relation where inflammatory breast cancer is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and thrombosis is the object constitutes an accurate semantic relation.

1013it [03:23,  5.31it/s]

false
Determine whether the semantic relation where 5-hydroxyindole-3-acetic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

1015it [03:24,  5.28it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lithium carbonate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1017it [03:24,  5.20it/s]

true
Determine whether the semantic relation where screw worm infectious disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1019it [03:24,  5.13it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rhesus macaque is the subject, habitat is the predicate, and forest is the object constitutes an accurate semantic relation.

1021it [03:25,  5.03it/s]

true
Determine whether the semantic relation where optic nerve injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bupropion is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1023it [03:25,  5.10it/s]

false
Determine whether the semantic relation where β-lactulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

1025it [03:26,  5.22it/s]

true
Determine whether the semantic relation where fentanyl is the subject, medical condition treated is the predicate, and arthritis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where rainbow trout is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1026it [03:26,  5.16it/s]

false
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and pleural cavity is the object constitutes an accurate semantic relation.

1028it [03:26,  5.06it/s]

false
Determine whether the semantic relation where fallopian tube neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cod liver oil is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1030it [03:27,  5.06it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

1031it [03:27,  5.03it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

1033it [03:27,  5.12it/s]

true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cephalosporin antibiotic is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1034it [03:27,  5.04it/s]

true
Determine whether the semantic relation where Adenine phosphoribosyltransferase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

1035it [03:28,  4.93it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true

1037it [03:28,  5.01it/s]

Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Acanthamoeba keratitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1039it [03:28,  5.04it/s]

true
Determine whether the semantic relation where retinal vein occlusion is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nitrogen is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

1040it [03:29,  4.87it/s]

true
Determine whether the semantic relation where procarbazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1041it [03:29,  4.48it/s]

true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1042it [03:29,  4.55it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

1044it [03:29,  4.82it/s]

true
Determine whether the semantic relation where pyrethrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcitriol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1045it [03:30,  5.02it/s]

true
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, biological process is the predicate, and hemostasis is the object constitutes an accurate semantic relation.

1046it [03:30,  4.89it/s]

false
Determine whether the semantic relation where methylprednisolone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1047it [03:30,  4.63it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1049it [03:30,  4.80it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.

1050it [03:31,  4.83it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and The Gambia is the object constitutes an accurate semantic relation.

1051it [03:31,  4.79it/s]

false
Determine whether the semantic relation where drinking is the subject, uses is the predicate, and hand is the object constitutes an accurate semantic relation.

1052it [03:31,  4.80it/s]

false
Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1053it [03:31,  4.77it/s]

false
Determine whether the semantic relation where The Gambia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1054it [03:32,  4.72it/s]

false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

1056it [03:32,  4.94it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

1057it [03:32,  4.79it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

1059it [03:33,  4.80it/s]

true
Determine whether the semantic relation where spermatic cord torsion is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1060it [03:33,  5.00it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

1061it [03:33,  4.57it/s]

false
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1063it [03:33,  4.66it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1065it [03:34,  4.96it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

1067it [03:34,  5.04it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

1069it [03:35,  4.98it/s]

true
Determine whether the semantic relation where quinidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1071it [03:35,  4.99it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral leishmaniasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1073it [03:35,  4.93it/s]

true
Determine whether the semantic relation where metformin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cynara scolymus is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1075it [03:36,  5.18it/s]

false
Determine whether the semantic relation where nucleosome is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

1077it [03:36,  5.40it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Birnaviridae infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1079it [03:37,  5.41it/s]

false
Determine whether the semantic relation where bovine trypanosomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echinococcosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1081it [03:37,  5.28it/s]

true
Determine whether the semantic relation where fetal hemoglobin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1082it [03:37,  5.31it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.

1084it [03:38,  5.11it/s]

true
Determine whether the semantic relation where Wnt family member 3A is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where microvasculature remodeling is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1086it [03:38,  5.30it/s]

false
Determine whether the semantic relation where arsenic poisoning is the subject, has effect is the predicate, and lymphoma is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smallpox is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

1088it [03:38,  5.44it/s]

true
Determine whether the semantic relation where amebiasis is the subject, possible treatment is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystadenocarcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1090it [03:39,  5.34it/s]

true
Determine whether the semantic relation where amoxicillin is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where necatoriasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1092it [03:39,  4.81it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and respiratory system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1094it [03:39,  5.07it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1096it [03:40,  5.11it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anisakiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1098it [03:40,  5.10it/s]

true
Determine whether the semantic relation where pertussis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

1100it [03:41,  5.23it/s]

true
Determine whether the semantic relation where genetic disease is the subject, opposite of is the predicate, and environmental disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where environmental disease is the subject, opposite of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

1101it [03:41,  5.34it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Niger is the object constitutes an accurate semantic relation.

1103it [03:41,  5.21it/s]

true
Determine whether the semantic relation where Niger is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eosinophilic esophagitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1105it [03:42,  5.20it/s]

true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where MDMA is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1107it [03:42,  5.06it/s]

false
Determine whether the semantic relation where paired box 2 is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

1109it [03:42,  5.28it/s]

true
Determine whether the semantic relation where calcium oxalate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1111it [03:43,  5.13it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Madagascar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cephalosporin antibiotic is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1113it [03:43,  5.27it/s]

false
Determine whether the semantic relation where fluoxetine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

1115it [03:44,  5.26it/s]

false
Determine whether the semantic relation where zirconium is the subject, location of discovery is the predicate, and Germany is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where antibiotic is the subject, named after is the predicate, and life is the object constitutes an accurate semantic relation.

1117it [03:44,  5.18it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

1118it [03:44,  4.85it/s]

true
Determine whether the semantic relation where marker of proliferation Ki-67 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

1120it [03:45,  4.66it/s]

false
Determine whether the semantic relation where esophageal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

1122it [03:45,  4.94it/s]

true
Determine whether the semantic relation where ceftriaxone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echinococcosis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

1124it [03:45,  4.91it/s]

true
Determine whether the semantic relation where endotoxemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where struma ovarii is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1126it [03:46,  5.16it/s]

true
Determine whether the semantic relation where struma ovarii is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

1127it [03:46,  4.60it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1129it [03:46,  4.82it/s]

false
Determine whether the semantic relation where serotonin is the subject, found in taxon is the predicate, and Brassica is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Eritrea is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1130it [03:47,  4.83it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Eritrea is the object constitutes an accurate semantic relation.

1132it [03:47,  5.07it/s]

true
Determine whether the semantic relation where simvastatin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where rhabdomyolysis is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

1134it [03:47,  4.90it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1136it [03:48,  5.03it/s]

true
Determine whether the semantic relation where diltiazem is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sphingolipidosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

1138it [03:48,  5.11it/s]

false
Determine whether the semantic relation where World War I is the subject, located in/on physical feature is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where food is the subject, subclass of is the predicate, and disposable product is the object constitutes an accurate semantic relation.

1140it [03:49,  5.21it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chondroblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1142it [03:49,  5.30it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

1144it [03:49,  5.18it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

1145it [03:50,  5.29it/s]

true
Determine whether the semantic relation where 5-HTP is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1146it [03:50,  5.02it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1148it [03:50,  5.02it/s]

false
Determine whether the semantic relation where sinus arrhythmia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where endemic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1150it [03:51,  5.17it/s]

true
Determine whether the semantic relation where Ludwig's angina is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1152it [03:51,  5.18it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coronavirus disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1154it [03:51,  5.32it/s]

true
Determine whether the semantic relation where suggestion is the subject, different from is the predicate, and guideline is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

1156it [03:52,  5.29it/s]

true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypotension is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

1157it [03:52,  5.37it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

1159it [03:52,  5.15it/s]

false
Determine whether the semantic relation where muscimol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

1161it [03:53,  5.21it/s]

false
Determine whether the semantic relation where refusal of medical assistance is the subject, facet of is the predicate, and first aid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1162it [03:53,  5.32it/s]

true
Determine whether the semantic relation where Central African Republic is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1164it [03:53,  5.24it/s]

true
Determine whether the semantic relation where degenerative disc disease is the subject, symptoms and signs is the predicate, and dehydration is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxymorphone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1165it [03:53,  5.13it/s]

true
Determine whether the semantic relation where fluphenazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1167it [03:54,  5.09it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and heart disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

1169it [03:54,  5.18it/s]

false
Determine whether the semantic relation where levonordefrin is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and levonordefrin is the object constitutes an accurate semantic relation.

1170it [03:54,  5.29it/s]

false
Determine whether the semantic relation where viral pneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1172it [03:55,  5.08it/s]

true
Determine whether the semantic relation where embryonal carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tree is the subject, has part(s) of the class is the predicate, and cell is the object constitutes an accurate semantic relation.

1174it [03:55,  4.89it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

1175it [03:55,  5.01it/s]

true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1176it [03:56,  4.68it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

1177it [03:56,  4.66it/s]

true
Determine whether the semantic relation where mitoxantrone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1179it [03:56,  4.75it/s]

false
Determine whether the semantic relation where tumor protein p53 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Duane retraction syndrome is the subject, health specialty is the predicate, and genetics is the object constitutes an accurate semantic relation.

1180it [03:57,  4.83it/s]

false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

1182it [03:57,  4.81it/s]

true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pentagastrin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1184it [03:57,  4.90it/s]

false
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

1186it [03:58,  5.07it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and Concanavalin A is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sexually transmitted infection is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

1188it [03:58,  5.06it/s]

true
Determine whether the semantic relation where postoperative nausea and vomiting is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where animal Salmonella infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1190it [03:59,  5.05it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, possible treatment is the predicate, and antioxidant is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trifluoperazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1192it [03:59,  5.21it/s]

true
Determine whether the semantic relation where 5-methylcytosine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1194it [03:59,  4.90it/s]

true
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true

1195it [04:00,  4.98it/s]

Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

1197it [04:00,  5.21it/s]

true
Determine whether the semantic relation where Rac family small GTPase 1 is the subject, biological process is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1199it [04:00,  5.17it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where penicillin v is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1200it [04:01,  5.19it/s]

false
Determine whether the semantic relation where oxygen is the subject, location of discovery is the predicate, and Sweden is the object constitutes an accurate semantic relation.

1202it [04:01,  5.01it/s]

false
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

1203it [04:01,  5.12it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

1205it [04:02,  5.11it/s]

true
Determine whether the semantic relation where comminuted fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Carboxypeptidase E is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

1206it [04:02,  5.28it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

1208it [04:02,  4.87it/s]

true
Determine whether the semantic relation where Interleukin 9 receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetanus is the subject, possible treatment is the predicate, and cardiac glycoside is the object constitutes an accurate semantic relation.

1210it [04:03,  5.11it/s]

false
Determine whether the semantic relation where diphyllobothriasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lac repressor is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

1212it [04:03,  5.40it/s]

false
Determine whether the semantic relation where photography is the subject, has use is the predicate, and pleasure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where isosorbide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

1213it [04:03,  5.43it/s]

false
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and nasal congestion is the object constitutes an accurate semantic relation.

1215it [04:03,  5.23it/s]

true
Determine whether the semantic relation where HIV seropositivity is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Peyronie's disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1217it [04:04,  4.88it/s]

true
Determine whether the semantic relation where Peyronie's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1219it [04:04,  5.09it/s]

true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

1220it [04:04,  5.09it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

1222it [04:05,  4.64it/s]

true
Determine whether the semantic relation where iron metabolism disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where eosinophilia is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

1223it [04:05,  4.70it/s]

false
Determine whether the semantic relation where visual verbal agnosia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

1225it [04:06,  4.90it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

1226it [04:06,  5.05it/s]

true
Determine whether the semantic relation where concussion is the subject, drug or therapy used for treatment is the predicate, and non-steroidal anti-inflammatory drug is the object constitutes an accurate semantic relation.

1227it [04:06,  4.65it/s]

true
Determine whether the semantic relation where sparganosis is the subject, subclass of is the predicate, and urinary system disease is the object constitutes an accurate semantic relation.

1229it [04:06,  4.84it/s]

false
Determine whether the semantic relation where photography is the subject, country of origin is the predicate, and England is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and circulatory system is the object constitutes an accurate semantic relation.

1231it [04:07,  5.04it/s]

true
Determine whether the semantic relation where tamoxifen is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where umbilical hernia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

1233it [04:07,  5.13it/s]

false
Determine whether the semantic relation where inducible T cell costimulator is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspartame is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1235it [04:08,  5.11it/s]

true
Determine whether the semantic relation where ATP citrate lyase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 1,6-diphenylhexatriene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1237it [04:08,  5.25it/s]

true
Determine whether the semantic relation where Rett syndrome is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1239it [04:08,  5.00it/s]

true
Determine whether the semantic relation where fibrosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.

1241it [04:09,  5.27it/s]

true
Determine whether the semantic relation where corneal dystrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

1243it [04:09,  5.33it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

1245it [04:09,  5.26it/s]

true
Determine whether the semantic relation where umbilical cord is the subject, instance of is the predicate, and biomedical waste is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vincristine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1246it [04:10,  5.26it/s]

true
Determine whether the semantic relation where trichinosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1248it [04:10,  5.17it/s]

true
Determine whether the semantic relation where cefapirin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carboplatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1250it [04:10,  5.27it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

1252it [04:11,  5.21it/s]

true
Determine whether the semantic relation where isopropylidenediphenyl bisoxyhydroxypropyl methacrylate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

1254it [04:11,  5.28it/s]

false
Determine whether the semantic relation where rheumatoid arthritis is the subject, drug or therapy used for treatment is the predicate, and enalapril is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where enalapril is the subject, medical condition treated is the predicate, and rheumatoid arthritis is the object constitutes an accurate semantic relation.

1255it [04:11,  5.33it/s]

false
Determine whether the semantic relation where erysipelothrix rhusiopathiae infectious disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1256it [04:12,  4.80it/s]

false
Determine whether the semantic relation where E2F transcription factor 4 is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

1258it [04:12,  4.97it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

1260it [04:12,  5.06it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1262it [04:13,  5.23it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

1264it [04:13,  5.26it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

1266it [04:14,  5.24it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

1268it [04:14,  5.28it/s]

false
Determine whether the semantic relation where Pisum sativum is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where autotrophy is the subject, subclass of is the predicate, and nutrition is the object constitutes an accurate semantic relation.

1270it [04:14,  5.21it/s]

false
Determine whether the semantic relation where disease susceptibility is the subject, has cause is the predicate, and sex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cimetidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1271it [04:15,  4.87it/s]

true
Determine whether the semantic relation where 6-thioguanine is the subject, found in taxon is the predicate, and Pseudomonas is the object constitutes an accurate semantic relation.

1272it [04:15,  4.88it/s]

false
Determine whether the semantic relation where ergotamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1273it [04:15,  4.55it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Guinea is the object constitutes an accurate semantic relation.

1275it [04:16,  4.35it/s]

true
Determine whether the semantic relation where Guinea is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ornithosis is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

1276it [04:16,  3.94it/s]

false
Determine whether the semantic relation where sirolimus is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1277it [04:16,  4.09it/s]

false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1279it [04:16,  4.37it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pressure ulcer is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1281it [04:17,  4.91it/s]

true
Determine whether the semantic relation where Kuru is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mesenteric vascular occlusion is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

1283it [04:17,  5.08it/s]

false
Determine whether the semantic relation where Interleukin 37 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

1284it [04:17,  5.22it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

1286it [04:18,  5.06it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

1288it [04:18,  5.26it/s]

false
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where periodic fever syndrome is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

1289it [04:18,  5.34it/s]

false
Determine whether the semantic relation where alopecia is the subject, instance of is the predicate, and buttocks is the object constitutes an accurate semantic relation.

1290it [04:19,  5.22it/s]

false
Determine whether the semantic relation where indomethacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1292it [04:19,  5.18it/s]

false
Determine whether the semantic relation where Ewing sarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and hepatitis is the object constitutes an accurate semantic relation.

1293it [04:19,  5.26it/s]

false
Determine whether the semantic relation where procaine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1294it [04:19,  4.99it/s]

true
Determine whether the semantic relation where contracture is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

1295it [04:20,  4.93it/s]

false
Determine whether the semantic relation where DL-ofloxacin is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.

1297it [04:20,  4.91it/s]

false
Determine whether the semantic relation where peripheral T-cell lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cobalamin binding intrinsic factor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

1298it [04:20,  4.94it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

1299it [04:20,  4.88it/s]

true
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

1300it [04:21,  4.64it/s]

true
Determine whether the semantic relation where Chagas disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1301it [04:21,  4.30it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

1303it [04:21,  4.48it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

1305it [04:22,  4.76it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

1307it [04:22,  5.07it/s]

true
Determine whether the semantic relation where Major histocompatibility complex, class II, DQ alpha 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lovastatin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1308it [04:22,  5.18it/s]

true
Determine whether the semantic relation where ornithosis is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

1310it [04:23,  4.94it/s]

false
Determine whether the semantic relation where isoprenaline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mauritania is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1312it [04:23,  4.53it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mauritania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1313it [04:23,  4.73it/s]

true
Determine whether the semantic relation where Comoros is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1314it [04:24,  4.77it/s]

true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

1316it [04:24,  4.76it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Comoros is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ghrelin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

1318it [04:24,  4.93it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

1320it [04:25,  5.07it/s]

false
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

1322it [04:25,  5.28it/s]

true
Determine whether the semantic relation where methicillin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

1324it [04:26,  5.26it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.

1326it [04:26,  5.27it/s]

true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, symptoms and signs is the predicate, and ataxia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where forskolin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1328it [04:26,  5.44it/s]

false
Determine whether the semantic relation where Natriuretic peptide A is the subject, biological process is the predicate, and protein folding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BRCA1 is the subject, expressed in is the predicate, and testicle is the object constitutes an accurate semantic relation.

1329it [04:27,  5.11it/s]

false
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

1331it [04:27,  5.05it/s]

true
Determine whether the semantic relation where azathioprine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where squalene is the subject, found in taxon is the predicate, and Pseudomonas is the object constitutes an accurate semantic relation.

1333it [04:27,  5.21it/s]

false
Determine whether the semantic relation where orbital disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acetylcholine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1335it [04:28,  5.26it/s]

true
Determine whether the semantic relation where AMP-activated protein kinases is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where losartan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1337it [04:28,  5.21it/s]

false
Determine whether the semantic relation where Meniere's disease is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where choriocarcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1339it [04:29,  5.08it/s]

true
Determine whether the semantic relation where trimetazidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nimodipine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1341it [04:29,  5.27it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

1343it [04:29,  4.99it/s]

false
Determine whether the semantic relation where middle cerebral artery infarction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenoceptor beta 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

1344it [04:30,  4.98it/s]

false
Determine whether the semantic relation where herpes gestationis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1346it [04:30,  4.72it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mentha × piperita is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1348it [04:30,  4.96it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transient cerebral isolation is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.

1350it [04:31,  5.27it/s]

false
Determine whether the semantic relation where spinal epidural hematoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1352it [04:31,  5.24it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine diphosphate is the subject, found in taxon is the predicate, and Musca domestica is the object constitutes an accurate semantic relation.

1354it [04:31,  5.12it/s]

false
Determine whether the semantic relation where choriogonadotropin subunit beta is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1356it [04:32,  5.29it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pasteurization is the subject, P642 is the predicate, and medicine is the object constitutes an accurate semantic relation.

1358it [04:32,  4.84it/s]

false
Determine whether the semantic relation where hepatitis B is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where travel is the subject, subclass of is the predicate, and motion is the object constitutes an accurate semantic relation.

1359it [04:33,  4.87it/s]

true
Determine whether the semantic relation where gastrin releasing peptide is the subject, biological process is the predicate, and social behavior is the object constitutes an accurate semantic relation.

1361it [04:33,  4.86it/s]

false
Determine whether the semantic relation where 6-aminonicotinamide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hepatitis B is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

1363it [04:33,  4.92it/s]

true
Determine whether the semantic relation where lysosomal storage disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where car is the subject, source of energy is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

1364it [04:34,  4.98it/s]

maybe
Determine whether the semantic relation where T-cell leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1366it [04:34,  4.96it/s]

true
Determine whether the semantic relation where promazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1368it [04:34,  4.97it/s]

false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true

1369it [04:35,  5.00it/s]

Determine whether the semantic relation where botulism is the subject, has natural reservoir is the predicate, and soil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

1371it [04:35,  5.10it/s]

true
Determine whether the semantic relation where quinolone antibiotic is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where California encephalitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

1372it [04:35,  5.09it/s]

false
Determine whether the semantic relation where papillary carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1374it [04:36,  5.14it/s]

true
Determine whether the semantic relation where respiratory acidosis is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hydrology is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

1376it [04:36,  5.17it/s]

true
Determine whether the semantic relation where finger injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iraq War is the subject, has cause is the predicate, and fossil fuel is the object constitutes an accurate semantic relation.

1378it [04:36,  5.09it/s]

maybe
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

1379it [04:37,  5.10it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

1381it [04:37,  5.16it/s]

true
Determine whether the semantic relation where zimelidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1382it [04:37,  5.18it/s]

true
Determine whether the semantic relation where Luchelli is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1383it [04:37,  4.83it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

1385it [04:38,  5.04it/s]

true
Determine whether the semantic relation where T-cell large granular lymphocyte leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cysticercosis is the subject, subclass of is the predicate, and intestinal disease is the object constitutes an accurate semantic relation.

1387it [04:38,  4.98it/s]

false
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prochlorperazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1388it [04:38,  5.21it/s]

true
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1390it [04:39,  5.19it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1392it [04:39,  5.33it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulindac is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

1394it [04:39,  5.29it/s]

false
Determine whether the semantic relation where Eswatini is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Eswatini is the object constitutes an accurate semantic relation.

1395it [04:40,  5.39it/s]

true
Determine whether the semantic relation where Secretoglobin family 2A member 2 is the subject, cell component is the predicate, and cellular component is the object constitutes an accurate semantic relation.

1397it [04:40,  5.18it/s]

false
Determine whether the semantic relation where splenic disease is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where disaster preparedness is the subject, subclass of is the predicate, and protective factor is the object constitutes an accurate semantic relation.

1398it [04:40,  5.30it/s]

false
Determine whether the semantic relation where loiasis is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

1400it [04:41,  4.63it/s]

true
Determine whether the semantic relation where arsphenamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Timor-Leste is the object constitutes an accurate semantic relation.

1401it [04:41,  4.59it/s]

true
Determine whether the semantic relation where Timor-Leste is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1402it [04:41,  4.51it/s]

true
Determine whether the semantic relation where Q18555290 is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1404it [04:42,  4.75it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

1405it [04:42,  4.90it/s]

true
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

1407it [04:42,  5.05it/s]

true
Determine whether the semantic relation where mitral valve stenosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glutamyl-prolyl-tRNA synthetase 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

1408it [04:42,  4.83it/s]

false
Determine whether the semantic relation where sigmoid colon is the subject, innervated by is the predicate, and spinal nerve is the object constitutes an accurate semantic relation.

1409it [04:43,  4.75it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1410it [04:43,  4.57it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

1412it [04:43,  4.76it/s]

true
Determine whether the semantic relation where vascular graft occlusion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lentinan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1413it [04:43,  4.71it/s]

false
Determine whether the semantic relation where pyridoxal is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1415it [04:44,  4.90it/s]

false
Determine whether the semantic relation where research participant is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cyanide poisoning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

1417it [04:44,  5.17it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

1419it [04:45,  4.89it/s]

true
Determine whether the semantic relation where BRCA1 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cameroon is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1420it [04:45,  5.07it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Cameroon is the object constitutes an accurate semantic relation.

1422it [04:45,  5.05it/s]

true
Determine whether the semantic relation where abnormal lordosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1424it [04:46,  5.20it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bile duct neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1425it [04:46,  5.25it/s]

true
Determine whether the semantic relation where wild boar is the subject, invasive to is the predicate, and Australia is the object constitutes an accurate semantic relation.

1427it [04:46,  5.04it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and The Gambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where The Gambia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1428it [04:46,  4.99it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1430it [04:47,  4.97it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin G is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

1432it [04:47,  5.18it/s]

false
Determine whether the semantic relation where pedophilia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.

1434it [04:48,  5.24it/s]

true
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where penicillin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1436it [04:48,  4.80it/s]

false
Determine whether the semantic relation where choriogonadotropin subunit beta is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where suramin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1438it [04:48,  5.20it/s]

true
Determine whether the semantic relation where hereditary angioedema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mescaline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1439it [04:49,  5.10it/s]

true
Determine whether the semantic relation where death is the subject, has part(s) is the predicate, and cell death is the object constitutes an accurate semantic relation.

1441it [04:49,  5.01it/s]

false
Determine whether the semantic relation where Far East scarlet-like fever is the subject, possible treatment is the predicate, and non-steroidal anti-inflammatory drug is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Low density lipoprotein receptor is the subject, biological process is the predicate, and long-term memory is the object constitutes an accurate semantic relation.

1442it [04:49,  4.70it/s]

false
Determine whether the semantic relation where retinopathy of prematurity is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

1444it [04:50,  4.99it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Sweden is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where familial hypercholesterolemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1446it [04:50,  5.17it/s]

true
Determine whether the semantic relation where DL-lactic acid is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and DL-lactic acid is the object constitutes an accurate semantic relation.

1448it [04:50,  5.19it/s]

false
Determine whether the semantic relation where temporal lobe epilepsy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis E is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

1450it [04:51,  5.30it/s]

true
Determine whether the semantic relation where lidocaine is the subject, medical condition treated is the predicate, and esophageal disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ranula is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1452it [04:51,  5.35it/s]

true
Determine whether the semantic relation where esophageal disease is the subject, drug or therapy used for treatment is the predicate, and lidocaine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1454it [04:52,  5.18it/s]

true
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.

1456it [04:52,  5.25it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tumor protein p53 is the subject, part of is the predicate, and pore-forming toxin is the object constitutes an accurate semantic relation.

1458it [04:52,  5.35it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1459it [04:52,  5.26it/s]

true
Determine whether the semantic relation where terbutaline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1460it [04:53,  4.99it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

1462it [04:53,  4.94it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

1464it [04:54,  5.14it/s]

false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and vinblastine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where paclitaxel is the subject, found in taxon is the predicate, and Aspergillus flavus is the object constitutes an accurate semantic relation.

1465it [04:54,  5.15it/s]

false
Determine whether the semantic relation where ibogaine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1466it [04:54,  4.86it/s]

true
Determine whether the semantic relation where pseudomembranous colitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1467it [04:54,  4.88it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.

1469it [04:55,  4.89it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

1470it [04:55,  5.07it/s]

true
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1472it [04:55,  5.10it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1474it [04:56,  5.21it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where postoperative hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1475it [04:56,  5.22it/s]

false
Determine whether the semantic relation where Victoria is the subject, official symbol is the predicate, and gold is the object constitutes an accurate semantic relation.

1476it [04:56,  5.09it/s]

false
Determine whether the semantic relation where (S)-AMPA is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1478it [04:56,  5.02it/s]

true
Determine whether the semantic relation where butterfly is the subject, named after is the predicate, and woman is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Burundi is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1480it [04:57,  4.96it/s]

true
Determine whether the semantic relation where HIV infection is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Burundi is the object constitutes an accurate semantic relation.

1481it [04:57,  4.79it/s]

true
Determine whether the semantic relation where dirofilariasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1483it [04:57,  4.89it/s]

true
Determine whether the semantic relation where oligoclonal band is the subject, studied by is the predicate, and medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where motilin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1485it [04:58,  4.91it/s]

false
Determine whether the semantic relation where thymine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

1487it [04:58,  5.13it/s]

true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebrosides is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1489it [04:59,  5.31it/s]

true
Determine whether the semantic relation where squamous cell carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heat shock protein family D (Hsp60) member 1 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

1490it [04:59,  5.34it/s]

false
Determine whether the semantic relation where altretamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1492it [04:59,  5.23it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1494it [04:59,  5.30it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

1496it [05:00,  5.08it/s]

false
Determine whether the semantic relation where neoplasm of oropharynx is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where norepinephrine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1497it [05:00,  4.62it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1499it [05:01,  4.83it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

1501it [05:01,  4.99it/s]

true
Determine whether the semantic relation where obturator hernia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

1502it [05:01,  5.13it/s]

true
Determine whether the semantic relation where GATA binding protein 4 is the subject, biological process is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.
false

1504it [05:02,  5.18it/s]

Determine whether the semantic relation where Coronavirus spike protein is the subject, subclass of is the predicate, and protein precursor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

1506it [05:02,  5.45it/s]

false
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 3 receptor subunit alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

1508it [05:02,  5.23it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

1509it [05:02,  5.25it/s]

false
Determine whether the semantic relation where brain hypoxia-ischemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1510it [05:03,  4.42it/s]

true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

1511it [05:03,  4.15it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

1513it [05:03,  4.59it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

1515it [05:04,  4.89it/s]

true
Determine whether the semantic relation where intracranial arteriosclerosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (R)-amygdalin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

1516it [05:04,  4.92it/s]

false
Determine whether the semantic relation where West Nile fever is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

1518it [05:04,  4.92it/s]

true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where AIDS-related lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1520it [05:05,  5.23it/s]

true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

1522it [05:05,  5.12it/s]

true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

1524it [05:06,  5.14it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.

1525it [05:06,  5.06it/s]

false
Determine whether the semantic relation where rabies is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1527it [05:06,  5.06it/s]

true
Determine whether the semantic relation where rabies is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where breast neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1529it [05:07,  5.07it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

1530it [05:07,  5.19it/s]

true
Determine whether the semantic relation where Burundi is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true

1532it [05:07,  5.27it/s]

Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, biological process is the predicate, and sex differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where penile neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1534it [05:08,  5.15it/s]

true
Determine whether the semantic relation where ATP citrate lyase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where etomidate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1536it [05:08,  5.19it/s]

false
Determine whether the semantic relation where vascular endothelial growth factor A is the subject, biological process is the predicate, and lactation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fasciolosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1537it [05:08,  5.30it/s]

true
Determine whether the semantic relation where binge drinking is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

1538it [05:08,  4.75it/s]

false
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1539it [05:09,  4.59it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

1541it [05:09,  4.97it/s]

true
Determine whether the semantic relation where non-odontogenic cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis D is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

1543it [05:09,  5.23it/s]

false
Determine whether the semantic relation where congenital lower extremity deformity is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melena is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

1544it [05:10,  5.26it/s]

false
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1545it [05:10,  5.15it/s]

false
Determine whether the semantic relation where amoxicillin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1547it [05:10,  4.93it/s]

false
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

1548it [05:10,  5.15it/s]

false
Determine whether the semantic relation where deoxycytidine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

1550it [05:11,  5.06it/s]

false
Determine whether the semantic relation where Venezuelan equine encephalitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where crystallin alpha B is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.

1552it [05:11,  5.02it/s]

false
Determine whether the semantic relation where Guinea-Bissau is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Guinea-Bissau is the object constitutes an accurate semantic relation.

1554it [05:12,  5.21it/s]

true
Determine whether the semantic relation where schizotypal personality disorder is the subject, has cause is the predicate, and genetics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

1556it [05:12,  5.19it/s]

true
Determine whether the semantic relation where metabolic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dermatomyositis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

1558it [05:12,  5.31it/s]

false
Determine whether the semantic relation where hydroxy(4-hydroxy-3-methoxyphenyl)acetic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trypanosomiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1559it [05:13,  4.92it/s]

true
Determine whether the semantic relation where pleomorphic adenoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1560it [05:13,  4.88it/s]

true
Determine whether the semantic relation where pleomorphic adenoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1561it [05:13,  3.74it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.

1563it [05:14,  4.28it/s]

false
Determine whether the semantic relation where vagina is the subject, named after is the predicate, and ship is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where AIDS dementia complex is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1565it [05:14,  4.65it/s]

true
Determine whether the semantic relation where uterine cervix neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and constipation is the object constitutes an accurate semantic relation.

1567it [05:14,  4.99it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular calcification is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1569it [05:15,  5.15it/s]

true
Determine whether the semantic relation where quinacrine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lisinopril is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1571it [05:15,  5.25it/s]

false
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and deafness is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

1573it [05:15,  5.29it/s]

true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1575it [05:16,  5.21it/s]

true
Determine whether the semantic relation where methoxsalen is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

1577it [05:16,  5.32it/s]

true
Determine whether the semantic relation where thiomersal is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where abscess is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

1578it [05:16,  5.29it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

1580it [05:17,  5.15it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

1582it [05:17,  5.33it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1584it [05:18,  5.32it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where periodontal attachment loss is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1585it [05:18,  5.40it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

1586it [05:18,  5.23it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

1587it [05:18,  4.69it/s]

true
Determine whether the semantic relation where epidemiology of obesity is the subject, instance of is the predicate, and epidemiology is the object constitutes an accurate semantic relation.

1588it [05:18,  4.63it/s]

false
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1589it [05:19,  4.62it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

1591it [05:19,  4.48it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1593it [05:19,  4.77it/s]

true
Determine whether the semantic relation where yohimbine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

1594it [05:20,  4.87it/s]

Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

1595it [05:20,  5.04it/s]

true
Determine whether the semantic relation where ergometrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1597it [05:20,  5.05it/s]

false
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.

1599it [05:21,  5.13it/s]

true
Determine whether the semantic relation where saccharin is the subject, subclass of is the predicate, and lactam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Niger is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1601it [05:21,  5.09it/s]

true
Determine whether the semantic relation where acute-phase proteins is the subject, studied by is the predicate, and clinical pathology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

1603it [05:21,  5.31it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Bahrain is the object constitutes an accurate semantic relation.

1605it [05:22,  5.28it/s]

true
Determine whether the semantic relation where Bahrain is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1607it [05:22,  5.25it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, named after is the predicate, and silver is the object constitutes an accurate semantic relation.

1608it [05:22,  5.24it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

1610it [05:23,  4.90it/s]

true
Determine whether the semantic relation where benzylpenicillin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2,4-dinitrochlorobenzene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1611it [05:23,  4.96it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1613it [05:23,  4.64it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

1615it [05:24,  4.98it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scabies is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1617it [05:24,  5.36it/s]

true
Determine whether the semantic relation where scabies is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1619it [05:25,  4.96it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

1620it [05:25,  5.11it/s]

false
Determine whether the semantic relation where saxitoxin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1622it [05:25,  5.12it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

1623it [05:25,  5.26it/s]

true
Determine whether the semantic relation where scabies is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

1625it [05:26,  4.86it/s]

false
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1627it [05:26,  5.14it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glioblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1628it [05:26,  5.22it/s]

true
Determine whether the semantic relation where orotic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1630it [05:27,  5.03it/s]

false
Determine whether the semantic relation where Venezuela is the subject, shares border with is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

1632it [05:27,  5.13it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where labor induction is the subject, has goal is the predicate, and health is the object constitutes an accurate semantic relation.

1634it [05:28,  5.34it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

1636it [05:28,  5.17it/s]

true
Determine whether the semantic relation where D-methamphetamine is the subject, medical condition treated is the predicate, and obesity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Niemann–Pick disease, type C is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1638it [05:28,  5.00it/s]

true
Determine whether the semantic relation where obesity is the subject, drug or therapy used for treatment is the predicate, and D-methamphetamine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1640it [05:29,  5.11it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Reoviridae infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1642it [05:29,  5.00it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

1644it [05:30,  5.12it/s]

true
Determine whether the semantic relation where Kuru is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where viral hepatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1646it [05:30,  5.11it/s]

true
Determine whether the semantic relation where ampicillin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leukotriene B4 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1648it [05:30,  5.17it/s]

false
Determine whether the semantic relation where Manitoba is the subject, official symbol is the predicate, and nickel is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where measles is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

1650it [05:31,  5.23it/s]

true
Determine whether the semantic relation where asymptomatic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dysplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1651it [05:31,  4.96it/s]

true
Determine whether the semantic relation where gas gangrene is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1652it [05:31,  4.87it/s]

true
Determine whether the semantic relation where Western equine encephalitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false

1654it [05:32,  5.07it/s]

Determine whether the semantic relation where clarithromycin is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isoniazid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1656it [05:32,  5.28it/s]

true
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where renal cell carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1657it [05:32,  5.32it/s]

true
Determine whether the semantic relation where androstenedione is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

1658it [05:32,  5.15it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase 4 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1660it [05:33,  5.17it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1662it [05:33,  4.91it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemophilia B is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1664it [05:34,  5.15it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

1666it [05:34,  5.19it/s]

true
Determine whether the semantic relation where sialic acids is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 8 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

1667it [05:34,  4.94it/s]

false
Determine whether the semantic relation where nocodazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1669it [05:35,  4.70it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where minocycline is the subject, medical condition treated is the predicate, and amebiasis is the object constitutes an accurate semantic relation.

1670it [05:35,  4.92it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

1672it [05:35,  4.77it/s]

true
Determine whether the semantic relation where amebiasis is the subject, drug or therapy used for treatment is the predicate, and minocycline is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Korea is the subject, religion or worldview is the predicate, and Catholicism is the object constitutes an accurate semantic relation.

1673it [05:35,  4.98it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

1675it [05:36,  5.07it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sex work is the subject, subclass of is the predicate, and work is the object constitutes an accurate semantic relation.

1676it [05:36,  5.23it/s]

true
Determine whether the semantic relation where congenital foot deformity is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

1678it [05:36,  4.95it/s]

false
Determine whether the semantic relation where aneurysm of heart is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1680it [05:37,  5.00it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

1681it [05:37,  5.03it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and human eye is the object constitutes an accurate semantic relation.

1683it [05:37,  4.88it/s]

false
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transthyretin is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

1685it [05:38,  5.07it/s]

false
Determine whether the semantic relation where inborn error of lipid metabolism is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where epidemic typhus is the subject, possible treatment is the predicate, and diuretic is the object constitutes an accurate semantic relation.

1687it [05:38,  5.26it/s]

false
Determine whether the semantic relation where Sandhoff disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

1689it [05:39,  5.28it/s]

true
Determine whether the semantic relation where honey is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

1691it [05:39,  5.51it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where type-1 diabetes is the subject, drug or therapy used for treatment is the predicate, and methyldopa is the object constitutes an accurate semantic relation.

1693it [05:39,  5.54it/s]

false
Determine whether the semantic relation where Bhutan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methyldopa is the subject, medical condition treated is the predicate, and type-1 diabetes is the object constitutes an accurate semantic relation.

1694it [05:39,  5.53it/s]

false
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1696it [05:40,  5.25it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1698it [05:40,  5.36it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1699it [05:40,  5.17it/s]

true
Determine whether the semantic relation where Tooth fusion is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

1700it [05:41,  5.08it/s]

maybe
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.

1702it [05:41,  5.13it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ret proto-oncogene is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1704it [05:41,  5.35it/s]

false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1706it [05:42,  5.44it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acne is the subject, has cause is the predicate, and genetic variation is the object constitutes an accurate semantic relation.

1708it [05:42,  5.48it/s]

true
Determine whether the semantic relation where olfactory mucosa is the subject, found in taxon is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1710it [05:42,  5.53it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

1712it [05:43,  4.75it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1713it [05:43,  4.93it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

1715it [05:44,  4.95it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

1717it [05:44,  4.97it/s]

true
Determine whether the semantic relation where sirolimus is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1718it [05:44,  4.91it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

1720it [05:45,  4.97it/s]

false
Determine whether the semantic relation where ampicillin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Joining chain of multimeric IgA and IgM is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

1722it [05:45,  5.28it/s]

true
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where propiolactone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

1724it [05:45,  5.31it/s]

true
Determine whether the semantic relation where metaproterenol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1726it [05:46,  5.39it/s]

true
Determine whether the semantic relation where aspirin-exacerbated respiratory disease is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where renin is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

1728it [05:46,  5.44it/s]

false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.

1730it [05:46,  5.40it/s]

true
Determine whether the semantic relation where protoporphyrins is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

1732it [05:47,  5.39it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

1734it [05:47,  5.39it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heptanoic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1736it [05:48,  5.29it/s]

false
Determine whether the semantic relation where domperidone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tooth ankylosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1738it [05:48,  5.30it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1740it [05:48,  5.35it/s]

true
Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

1742it [05:49,  5.04it/s]

false
Determine whether the semantic relation where alprenolol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1744it [05:49,  5.06it/s]

false
Determine whether the semantic relation where kainic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where El Salvador is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1746it [05:49,  5.14it/s]

true
Determine whether the semantic relation where anthracosis is the subject, has effect is the predicate, and stroke is the object constitutes an accurate semantic relation.
false

1747it [05:50,  5.16it/s]

Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and El Salvador is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gonorrhea is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

1749it [05:50,  4.99it/s]

true
Determine whether the semantic relation where extranodal NK/T-cell lymphoma, nasal type is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1751it [05:51,  4.96it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where primary effusion lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1752it [05:51,  5.15it/s]

true
Determine whether the semantic relation where anthrax is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

1754it [05:51,  5.22it/s]

true
Determine whether the semantic relation where 4-aminosalicylic acid is the subject, subject has role is the predicate, and cyclooxygenase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (RS)-sulpiride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1756it [05:51,  5.22it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

1758it [05:52,  4.99it/s]

false
Determine whether the semantic relation where benzylpenicillin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

1760it [05:52,  5.39it/s]

true
Determine whether the semantic relation where Diagnostic and Statistical Manual of Mental Disorders is the subject, instance of is the predicate, and reference work is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Guinea is the object constitutes an accurate semantic relation.

1761it [05:52,  5.45it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

1763it [05:53,  5.26it/s]

true
Determine whether the semantic relation where Guinea is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

1765it [05:53,  5.20it/s]

true
Determine whether the semantic relation where Republic of the Congo is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.

1767it [05:54,  5.34it/s]

true
Determine whether the semantic relation where EPH receptor A5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where familial amyloid neuropathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1768it [05:54,  5.34it/s]

true
Determine whether the semantic relation where simvastatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1770it [05:54,  5.13it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1772it [05:55,  5.20it/s]

true
Determine whether the semantic relation where capsaicin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Q155867 is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1774it [05:55,  5.19it/s]

true
Determine whether the semantic relation where kynurenic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pityriasis rosea is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1776it [05:55,  5.28it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1778it [05:56,  5.01it/s]

false
Determine whether the semantic relation where CD274 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1780it [05:56,  5.03it/s]

true
Determine whether the semantic relation where estrogen receptor 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1781it [05:56,  5.07it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

1783it [05:57,  5.06it/s]

true
Determine whether the semantic relation where toluene 2,4-diisocyanate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

1785it [05:57,  4.81it/s]

false
Determine whether the semantic relation where keratin 20 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1786it [05:57,  4.99it/s]

false
Determine whether the semantic relation where hepatitis C is the subject, anatomical location is the predicate, and lymphatic system is the object constitutes an accurate semantic relation.

1788it [05:58,  4.96it/s]

false
Determine whether the semantic relation where benperidol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

1790it [05:58,  5.20it/s]

true
Determine whether the semantic relation where ocular onchocerciasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

1792it [05:59,  5.27it/s]

false
Determine whether the semantic relation where sparganosis is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where speech sound disorder is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

1794it [05:59,  5.14it/s]

false
Determine whether the semantic relation where Mannosidase beta is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Histamine receptor H1 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

1795it [05:59,  5.29it/s]

false
Determine whether the semantic relation where life is the subject, has characteristic is the predicate, and biodiversity is the object constitutes an accurate semantic relation.

1797it [05:59,  5.16it/s]

false
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

1799it [06:00,  5.19it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

1800it [06:00,  4.59it/s]

true
Determine whether the semantic relation where Botswana is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1802it [06:01,  4.84it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Botswana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

1804it [06:01,  5.25it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1806it [06:01,  5.41it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

1808it [06:02,  5.28it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aflatoxins is the subject, subclass of is the predicate, and polyketide is the object constitutes an accurate semantic relation.

1809it [06:02,  5.28it/s]

true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and obesity is the object constitutes an accurate semantic relation.

1811it [06:02,  4.93it/s]

false
Determine whether the semantic relation where calcinosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1813it [06:03,  5.18it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KiSS-1 metastasis suppressor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

1814it [06:03,  5.28it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

1815it [06:03,  5.15it/s]

true
Determine whether the semantic relation where cefazolin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1817it [06:03,  5.05it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where molybdenum is the subject, location of discovery is the predicate, and Sweden is the object constitutes an accurate semantic relation.

1819it [06:04,  5.35it/s]

true
Determine whether the semantic relation where BAK1 is the subject, expressed in is the predicate, and duodenum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where raccoon is the subject, invasive to is the predicate, and Russia is the object constitutes an accurate semantic relation.

1820it [06:04,  5.42it/s]

false
Determine whether the semantic relation where TP53 is the subject, expressed in is the predicate, and rectum is the object constitutes an accurate semantic relation.

1822it [06:04,  4.99it/s]

false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

1824it [06:05,  5.09it/s]

true
Determine whether the semantic relation where nitrofurazone is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

1825it [06:05,  5.22it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

1827it [06:05,  5.19it/s]

true
Determine whether the semantic relation where harmine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyaluronic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1829it [06:06,  5.31it/s]

false
Determine whether the semantic relation where East Germany is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where filarial elephantiasis is the subject, symptoms and signs is the predicate, and abscess is the object constitutes an accurate semantic relation.

1830it [06:06,  5.22it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and East Germany is the object constitutes an accurate semantic relation.

1832it [06:06,  5.21it/s]

false
Determine whether the semantic relation where acetaldehyde is the subject, found in taxon is the predicate, and Staphylococcus aureus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where echinococcosis is the subject, anatomical location is the predicate, and brain is the object constitutes an accurate semantic relation.

1834it [06:07,  5.23it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetanus is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

1836it [06:07,  5.37it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Montenegro is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Montenegro is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1837it [06:07,  5.34it/s]

true
Determine whether the semantic relation where atrazine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

1838it [06:07,  5.15it/s]

false
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true

1840it [06:08,  5.13it/s]

Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cataract is the subject, afflicts is the predicate, and bird is the object constitutes an accurate semantic relation.

1842it [06:08,  5.24it/s]

false
Determine whether the semantic relation where transthyretin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands Antilles is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

1844it [06:09,  5.25it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Netherlands Antilles is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pseudomembranous colitis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

1846it [06:09,  5.37it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

1847it [06:09,  5.09it/s]

true
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1849it [06:10,  4.90it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intracranial thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

1851it [06:10,  5.06it/s]

false
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Spinacia oleracea is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1853it [06:10,  5.10it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

1855it [06:11,  5.30it/s]

true
Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where choroiditis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

1857it [06:11,  5.34it/s]

false
Determine whether the semantic relation where multiple pulmonary nodules is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and air pollution is the object constitutes an accurate semantic relation.

1859it [06:12,  5.37it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

1860it [06:12,  5.00it/s]

true
Determine whether the semantic relation where lead poisoning of the nervous system is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1862it [06:12,  4.96it/s]

true
Determine whether the semantic relation where alphavirus infections is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulpitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1864it [06:13,  5.20it/s]

true
Determine whether the semantic relation where Pseudomonas infection is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Protein C, inactivator of coagulation factors Va and VIIIa is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

1865it [06:13,  5.28it/s]

false
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1867it [06:13,  5.12it/s]

true
Determine whether the semantic relation where clotrimazole is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.

1869it [06:14,  5.17it/s]

true
Determine whether the semantic relation where adenovirus infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

1871it [06:14,  5.16it/s]

true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

1872it [06:14,  5.22it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

1874it [06:15,  5.11it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where persistent fetal circulation syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1876it [06:15,  5.26it/s]

true
Determine whether the semantic relation where nitroglycerin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tay-Sachs disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

1877it [06:15,  5.07it/s]

true
Determine whether the semantic relation where robotics is the subject, part of is the predicate, and industry is the object constitutes an accurate semantic relation.

1878it [06:15,  4.83it/s]

true
Determine whether the semantic relation where cyclic ADP-ribose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1879it [06:16,  4.50it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

1881it [06:16,  4.55it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where raccoon is the subject, invasive to is the predicate, and Italy is the object constitutes an accurate semantic relation.

1882it [06:16,  4.62it/s]

false
Determine whether the semantic relation where neonatal abstinence syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1884it [06:17,  4.85it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

1886it [06:17,  4.83it/s]

true
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and Enterococcus faecalis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where genistein is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1888it [06:17,  5.02it/s]

true
Determine whether the semantic relation where acariasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1889it [06:18,  5.15it/s]

false
Determine whether the semantic relation where prosthesis-related infection is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1890it [06:18,  4.87it/s]

true
Determine whether the semantic relation where pantothenic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1892it [06:18,  5.04it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

1894it [06:19,  5.28it/s]

true
Determine whether the semantic relation where population growth is the subject, subclass of is the predicate, and growth is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hunger is the subject, different from is the predicate, and Hungary is the object constitutes an accurate semantic relation.

1895it [06:19,  5.10it/s]

false
Determine whether the semantic relation where DNA nucleotidylexotransferase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

1897it [06:19,  4.83it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

1898it [06:19,  4.64it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1900it [06:20,  4.88it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

1902it [06:20,  5.10it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where flavin mononucleotide is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

1903it [06:20,  5.16it/s]

false
Determine whether the semantic relation where Somalia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

1905it [06:21,  5.18it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Somalia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where interleukin-13 receptor is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

1907it [06:21,  5.30it/s]

true
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.

1908it [06:21,  4.88it/s]

true
Determine whether the semantic relation where programmed cell death 1 ligand 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

1910it [06:22,  5.06it/s]

true
Determine whether the semantic relation where giant-cell tumor of bone is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

1912it [06:22,  5.21it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

1914it [06:23,  5.21it/s]

true
Determine whether the semantic relation where liver parasitic disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

1915it [06:23,  5.25it/s]

Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Honduras is the object constitutes an accurate semantic relation.

1916it [06:23,  5.30it/s]

true
Determine whether the semantic relation where Honduras is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true

1918it [06:23,  5.24it/s]

Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apigenin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1920it [06:24,  5.23it/s]

true
Determine whether the semantic relation where diphyllobothriasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diabetic nephropathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1922it [06:24,  4.89it/s]

true
Determine whether the semantic relation where bladder disease is the subject, drug or therapy used for treatment is the predicate, and neostigmine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neostigmine is the subject, medical condition treated is the predicate, and bladder disease is the object constitutes an accurate semantic relation.

1923it [06:24,  4.71it/s]

true
Determine whether the semantic relation where pyelonephritis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

1925it [06:25,  4.90it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

1927it [06:25,  4.67it/s]

true
Determine whether the semantic relation where mannans is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ventricular fibrillation is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.

1929it [06:26,  4.49it/s]

false
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

1931it [06:26,  4.82it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where total complement activity is the subject, instance of is the predicate, and blood test is the object constitutes an accurate semantic relation.

1933it [06:26,  5.11it/s]

true
Determine whether the semantic relation where suicidal ideation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

1935it [06:27,  5.23it/s]

true
Determine whether the semantic relation where Russia is the subject, designated as terrorist by is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

1936it [06:27,  5.33it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

1938it [06:27,  5.21it/s]

true
Determine whether the semantic relation where proopiomelanocortin is the subject, cell component is the predicate, and peroxisome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where occupational dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1939it [06:28,  5.25it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

1940it [06:28,  4.90it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

1942it [06:28,  5.01it/s]

true
Determine whether the semantic relation where placenta accreta is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where betamethasone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1943it [06:28,  5.05it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

1945it [06:29,  5.08it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

1947it [06:29,  5.06it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where berylliosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1948it [06:29,  5.08it/s]

true
Determine whether the semantic relation where thalidomide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1950it [06:30,  5.01it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

1952it [06:30,  4.60it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 15 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

1953it [06:31,  4.43it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

1954it [06:31,  4.43it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

1956it [06:31,  4.70it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholecalciferol is the subject, medical condition treated is the predicate, and cardiovascular disease is the object constitutes an accurate semantic relation.

1958it [06:32,  4.49it/s]

maybe
Determine whether the semantic relation where cardiovascular disease is the subject, drug or therapy used for treatment is the predicate, and cholecalciferol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trophoblastic neoplasm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1959it [06:32,  4.74it/s]

true
Determine whether the semantic relation where diabetic foot is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

1961it [06:32,  4.84it/s]

false
Determine whether the semantic relation where histoplasmosis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

1963it [06:33,  5.03it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where male breast neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1964it [06:33,  4.47it/s]

true
Determine whether the semantic relation where liposarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

1965it [06:33,  4.47it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1967it [06:34,  4.57it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

1969it [06:34,  4.84it/s]

false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lithium carbonate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

1971it [06:34,  5.13it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New York City is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

1973it [06:35,  4.91it/s]

true
Determine whether the semantic relation where sucralfate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where biliary tract neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1975it [06:35,  5.12it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

1976it [06:35,  5.24it/s]

true
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

1978it [06:36,  5.15it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

1980it [06:36,  5.33it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pyrus is the subject, source of energy is the predicate, and protein is the object constitutes an accurate semantic relation.

1982it [06:36,  5.44it/s]

false
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

1984it [06:37,  5.20it/s]

true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where obstructive sleep apnea is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

1986it [06:37,  5.16it/s]

false
Determine whether the semantic relation where L-glutamine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.

1987it [06:37,  5.11it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.

1988it [06:38,  5.04it/s]

true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

1990it [06:38,  4.84it/s]

true
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

1991it [06:38,  4.90it/s]

false
Determine whether the semantic relation where dopamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

1993it [06:39,  4.82it/s]

true
Determine whether the semantic relation where erythromycin estolate is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intra-abdominal hypertension is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

1994it [06:39,  4.70it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

1996it [06:39,  4.89it/s]

true
Determine whether the semantic relation where Bhutan is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

1997it [06:40,  5.04it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Bhutan is the object constitutes an accurate semantic relation.

1998it [06:40,  4.93it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

1999it [06:40,  4.81it/s]

false
Determine whether the semantic relation where hydromorphone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2000it [06:40,  4.79it/s]

true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

2002it [06:41,  4.80it/s]

true
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Thailand is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

2004it [06:41,  5.14it/s]

false
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where calcium is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.

2006it [06:41,  5.41it/s]

false
Determine whether the semantic relation where legionnaires' disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascariasis is the subject, medical examination is the predicate, and microscopy is the object constitutes an accurate semantic relation.

2007it [06:42,  5.29it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true

2009it [06:42,  5.26it/s]

Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chagas cardiomyopathy is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2010it [06:42,  5.31it/s]

true
Determine whether the semantic relation where papaverine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2012it [06:42,  5.19it/s]

true
Determine whether the semantic relation where ruptured aneurysm is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

2014it [06:43,  5.34it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czechoslovakia is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.

2016it [06:43,  5.29it/s]

false
Determine whether the semantic relation where diphtheria is the subject, symptoms and signs is the predicate, and heart failure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where renin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

2018it [06:44,  5.28it/s]

false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

2020it [06:44,  5.24it/s]

true
Determine whether the semantic relation where necrotizing fasciitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malignant hyperthermia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2022it [06:44,  5.22it/s]

false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.

2024it [06:45,  5.12it/s]

true
Determine whether the semantic relation where acarbose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2026it [06:45,  5.33it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hiatus hernia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

2028it [06:46,  4.56it/s]

false
Determine whether the semantic relation where folinic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cefazolin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

2029it [06:46,  4.67it/s]

false
Determine whether the semantic relation where Wolff–Parkinson–White syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

2031it [06:46,  4.83it/s]

true
Determine whether the semantic relation where zalcitabine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mumps is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

2032it [06:46,  4.95it/s]

false
Determine whether the semantic relation where Interleukin 4 receptor is the subject, biological process is the predicate, and ovulation is the object constitutes an accurate semantic relation.

2033it [06:47,  4.80it/s]

false
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2035it [06:47,  4.86it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

2037it [06:48,  5.00it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

2039it [06:48,  5.36it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and smooth endoplasmic reticulum is the object constitutes an accurate semantic relation.

2040it [06:48,  5.41it/s]

false
Determine whether the semantic relation where biliverdin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2042it [06:48,  5.27it/s]

true
Determine whether the semantic relation where chlorhexidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where maxillary disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

2043it [06:49,  5.36it/s]

false
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

2045it [06:49,  5.07it/s]

false
Determine whether the semantic relation where acinar cell carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein B is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

2047it [06:49,  4.88it/s]

false
Determine whether the semantic relation where heparin is the subject, instance of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Haiti is the object constitutes an accurate semantic relation.

2049it [06:50,  5.19it/s]

true
Determine whether the semantic relation where Haiti is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zanamivir is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2050it [06:50,  5.33it/s]

true
Determine whether the semantic relation where Eastern equine encephalitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

2052it [06:50,  5.24it/s]

false
Determine whether the semantic relation where penicillin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pefloxacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2054it [06:51,  5.22it/s]

true
Determine whether the semantic relation where MEDLINE is the subject, main subject is the predicate, and chemistry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phytol is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

2055it [06:51,  5.12it/s]

false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

2056it [06:51,  5.01it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true

2058it [06:52,  5.01it/s]

Determine whether the semantic relation where Haiti is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Haiti is the object constitutes an accurate semantic relation.

2059it [06:52,  5.16it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

2061it [06:52,  5.24it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where galantamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2062it [06:52,  5.29it/s]

true
Determine whether the semantic relation where helium is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

2064it [06:53,  5.22it/s]

false
Determine whether the semantic relation where potassium is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diet is the subject, has contributing factor is the predicate, and instinct is the object constitutes an accurate semantic relation.

2065it [06:53,  5.18it/s]

maybe
Determine whether the semantic relation where Russian Empire is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

2067it [06:53,  5.04it/s]

false
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

2069it [06:54,  4.71it/s]

true
Determine whether the semantic relation where central nervous system vasculitis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dyssomnia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

2070it [06:54,  4.62it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2072it [06:54,  4.80it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2074it [06:55,  5.05it/s]

true
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2076it [06:55,  5.15it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heptanoic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2078it [06:56,  5.41it/s]

true
Determine whether the semantic relation where CD34 molecule is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Suriname is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2080it [06:56,  5.47it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Suriname is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peripheral artery disease is the subject, risk factor is the predicate, and tobacco use disorder is the object constitutes an accurate semantic relation.

2082it [06:56,  5.51it/s]

false
Determine whether the semantic relation where amyloid neuropathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spondylolisthesis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

2084it [06:57,  5.35it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

2085it [06:57,  5.19it/s]

true
Determine whether the semantic relation where inhibitor of DNA binding 1, HLH protein is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

2087it [06:57,  5.19it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

2089it [06:58,  5.39it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanosine cyclic 3',5'-phosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2091it [06:58,  5.48it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lesotho is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2092it [06:58,  5.39it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Lesotho is the object constitutes an accurate semantic relation.

2094it [06:59,  5.16it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

2096it [06:59,  5.41it/s]

true
Determine whether the semantic relation where Coagulation factor II, thrombin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2097it [06:59,  5.42it/s]

true
Determine whether the semantic relation where campylobacteriosis is the subject, has natural reservoir is the predicate, and Rodent is the object constitutes an accurate semantic relation.

2098it [06:59,  5.24it/s]

false
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

2100it [07:00,  5.17it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

2102it [07:00,  5.35it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

2104it [07:00,  5.55it/s]

true
Determine whether the semantic relation where premature ejaculation is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mammary Paget's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2106it [07:01,  5.52it/s]

true
Determine whether the semantic relation where entamoebiasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where appendiceal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2108it [07:01,  5.40it/s]

true
Determine whether the semantic relation where post-concussion syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pleural tuberculosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2109it [07:01,  4.99it/s]

true
Determine whether the semantic relation where hepatocellular carcinoma is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

2111it [07:02,  4.81it/s]

true
Determine whether the semantic relation where busulfan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where complement C3 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

2112it [07:02,  4.74it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

2114it [07:02,  4.95it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and gastroenteritis is the object constitutes an accurate semantic relation.

2116it [07:03,  5.09it/s]

true
Determine whether the semantic relation where haloperidol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aphthous stomatitis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

2118it [07:03,  5.33it/s]

false
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where corneal perforation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2120it [07:04,  5.49it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2122it [07:04,  5.65it/s]

true
Determine whether the semantic relation where African trypanosomiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Dominican Republic is the object constitutes an accurate semantic relation.

2124it [07:04,  5.51it/s]

true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

2126it [07:05,  5.40it/s]

false
Determine whether the semantic relation where Dominican Republic is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2128it [07:05,  5.51it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where busulfan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2129it [07:05,  4.97it/s]

false
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

2131it [07:06,  4.98it/s]

true
Determine whether the semantic relation where (2E,6E)-farnesol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Morpholino is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2133it [07:06,  5.11it/s]

false
Determine whether the semantic relation where ondansetron is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

2134it [07:06,  5.10it/s]

true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true

2136it [07:07,  5.10it/s]

Determine whether the semantic relation where sarcocystosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, subject has role is the predicate, and xenobiotic is the object constitutes an accurate semantic relation.

2138it [07:07,  5.37it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Romania is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

2140it [07:07,  5.51it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Ciona intestinalis is the object constitutes an accurate semantic relation.

2142it [07:08,  5.49it/s]

false
Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.

2143it [07:08,  5.47it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and The Gambia is the object constitutes an accurate semantic relation.

2145it [07:08,  5.28it/s]

true
Determine whether the semantic relation where The Gambia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jun proto-oncogene, AP-1 transcription factor subunit is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.

2147it [07:09,  5.23it/s]

true
Determine whether the semantic relation where TNF superfamily member 13b is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where captopril is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2149it [07:09,  5.33it/s]

true
Determine whether the semantic relation where rhinosporidiosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

2150it [07:09,  5.13it/s]

true
Determine whether the semantic relation where thromboangiitis obliterans is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2151it [07:09,  5.06it/s]

false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

2153it [07:10,  4.83it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where developmental language disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2155it [07:10,  5.28it/s]

false
Determine whether the semantic relation where calcium sensing receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

2156it [07:10,  5.17it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

2158it [07:11,  4.05it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2160it [07:11,  4.67it/s]

true
Determine whether the semantic relation where ambroxol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where psilocybin is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

2161it [07:12,  4.80it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

2163it [07:12,  4.87it/s]

true
Determine whether the semantic relation where sucrose is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Flaviviridae infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2164it [07:12,  4.92it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

2166it [07:13,  4.99it/s]

true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

2167it [07:13,  5.02it/s]

true
Determine whether the semantic relation where gout is the subject, afflicts is the predicate, and man is the object constitutes an accurate semantic relation.

2169it [07:13,  5.00it/s]

true
Determine whether the semantic relation where N-acetylneuraminic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

2171it [07:14,  4.96it/s]

true
Determine whether the semantic relation where ranitidine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

2173it [07:14,  4.91it/s]

true
Determine whether the semantic relation where oxymetazoline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

2175it [07:14,  5.02it/s]

true
Determine whether the semantic relation where aconitine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium is the subject, named after is the predicate, and headache is the object constitutes an accurate semantic relation.

2176it [07:15,  5.19it/s]

false
Determine whether the semantic relation where amphotericin B is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

2177it [07:15,  5.08it/s]

false
Determine whether the semantic relation where (RS)-ibotenic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2178it [07:15,  4.80it/s]

true
Determine whether the semantic relation where reserpine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2180it [07:15,  5.02it/s]

false
Determine whether the semantic relation where carotid artery thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2181it [07:16,  4.97it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2182it [07:16,  4.80it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2183it [07:16,  4.83it/s]

true
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2185it [07:17,  4.93it/s]

true
Determine whether the semantic relation where albuminuria is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

2186it [07:17,  4.91it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

2188it [07:17,  4.98it/s]

true
Determine whether the semantic relation where adenocarcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenocarcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2190it [07:18,  4.99it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

2191it [07:18,  4.75it/s]

true
Determine whether the semantic relation where metaproterenol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2192it [07:18,  4.63it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

2193it [07:18,  4.55it/s]

false
Determine whether the semantic relation where paragonimiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2195it [07:19,  4.68it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

2196it [07:19,  4.83it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

2198it [07:19,  4.98it/s]

true
Determine whether the semantic relation where tenosynovitis is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

2199it [07:19,  5.05it/s]

true
Determine whether the semantic relation where ancylostomiasis is the subject, subclass of is the predicate, and eye disease is the object constitutes an accurate semantic relation.

2201it [07:20,  5.06it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

2202it [07:20,  5.03it/s]

true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

2204it [07:20,  4.90it/s]

true
Determine whether the semantic relation where renal tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where germanium is the subject, named after is the predicate, and Germany is the object constitutes an accurate semantic relation.

2206it [07:21,  5.00it/s]

true
Determine whether the semantic relation where germanium is the subject, location of discovery is the predicate, and Germany is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Rwanda is the object constitutes an accurate semantic relation.

2207it [07:21,  5.06it/s]

true
Determine whether the semantic relation where Rwanda is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2208it [07:21,  5.02it/s]

true
Determine whether the semantic relation where violence is the subject, has effect is the predicate, and pain is the object constitutes an accurate semantic relation.
true

2210it [07:22,  5.05it/s]

Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

2212it [07:22,  4.98it/s]

true
Determine whether the semantic relation where abscess is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Q146555 is the object constitutes an accurate semantic relation.

2214it [07:22,  5.02it/s]

false
Determine whether the semantic relation where hepatic echinococcosis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where hepatitis is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

2216it [07:23,  5.14it/s]

false
Determine whether the semantic relation where ondansetron is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where junctional ectopic tachycardia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2218it [07:23,  5.23it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 10 is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

2220it [07:24,  5.25it/s]

false
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

2222it [07:24,  5.17it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

2223it [07:24,  5.40it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

2224it [07:24,  5.18it/s]

true
Determine whether the semantic relation where cytosine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

2226it [07:25,  5.16it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

2228it [07:25,  5.10it/s]

true
Determine whether the semantic relation where bone resorption is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

2230it [07:26,  5.19it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

2231it [07:26,  5.11it/s]

true
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

2233it [07:26,  5.04it/s]

true
Determine whether the semantic relation where tumor protein p53 is the subject, biological process is the predicate, and gastrulation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2235it [07:26,  5.30it/s]

true
Determine whether the semantic relation where heroin dependence is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

2237it [07:27,  5.39it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quinic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2239it [07:27,  5.26it/s]

false
Determine whether the semantic relation where tranylcypromine is the subject, medical condition treated is the predicate, and post-traumatic stress disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where post-traumatic stress disorder is the subject, drug or therapy used for treatment is the predicate, and tranylcypromine is the object constitutes an accurate semantic relation.

2240it [07:27,  5.30it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

2241it [07:28,  4.37it/s]

true
Determine whether the semantic relation where trachoma is the subject, possible treatment is the predicate, and surgical procedure is the object constitutes an accurate semantic relation.

2242it [07:28,  4.20it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2244it [07:28,  4.61it/s]

true
Determine whether the semantic relation where lincomycin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where poliomyelitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

2245it [07:29,  4.85it/s]

false
Determine whether the semantic relation where uridine 5'-triphosphoric acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2247it [07:29,  4.84it/s]

true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

2249it [07:29,  4.90it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and muscular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where yellow fever is the subject, possible treatment is the predicate, and liver transplantation is the object constitutes an accurate semantic relation.

2250it [07:30,  4.97it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

2251it [07:30,  4.74it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

2253it [07:30,  4.87it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Poland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sulfasalazine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

2255it [07:31,  5.13it/s]

false
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

2256it [07:31,  5.30it/s]

true
Determine whether the semantic relation where mandibular injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2257it [07:31,  5.10it/s]

false
Determine whether the semantic relation where sparganosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2258it [07:31,  5.02it/s]

true
Determine whether the semantic relation where anti-neutrophil cytoplasmic antibody-associated vasculitis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2260it [07:32,  4.80it/s]

false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

2262it [07:32,  5.14it/s]

true
Determine whether the semantic relation where hypotension is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aminolevulinic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2264it [07:32,  5.19it/s]

true
Determine whether the semantic relation where (+/-)-8-hydroxy-2-(di-N-propylamino)tetralin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

2266it [07:33,  5.23it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

2268it [07:33,  5.45it/s]

false
Determine whether the semantic relation where KEL is the subject, expressed in is the predicate, and lymph node is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2269it [07:33,  5.33it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

2271it [07:34,  5.19it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

2272it [07:34,  5.13it/s]

true
Determine whether the semantic relation where glycocalyx is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

2273it [07:34,  4.91it/s]

false
Determine whether the semantic relation where adrenal gland is the subject, follows is the predicate, and mesoderm is the object constitutes an accurate semantic relation.

2274it [07:34,  4.91it/s]

false
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2276it [07:35,  4.97it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Madagascar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitoxantrone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2278it [07:35,  4.98it/s]

true
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where perphenazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2279it [07:35,  4.97it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2281it [07:36,  5.02it/s]

false
Determine whether the semantic relation where melioidosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where risperidone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2282it [07:36,  4.94it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2284it [07:36,  4.96it/s]

true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where polymyositis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2285it [07:37,  4.66it/s]

false
Determine whether the semantic relation where DL-lactic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

2286it [07:37,  4.68it/s]

false
Determine whether the semantic relation where paragonimiasis is the subject, anatomical location is the predicate, and skin is the object constitutes an accurate semantic relation.

2288it [07:37,  4.90it/s]

false
Determine whether the semantic relation where (RS)-baclofen is the subject, medical condition treated is the predicate, and vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2289it [07:37,  4.96it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Russian Empire is the object constitutes an accurate semantic relation.

2291it [07:38,  5.06it/s]

true
Determine whether the semantic relation where Russian Empire is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russian Empire is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2292it [07:38,  5.21it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true

2294it [07:38,  5.16it/s]

Determine whether the semantic relation where L-selenocysteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

2295it [07:39,  4.92it/s]

true
Determine whether the semantic relation where spironolactone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

2297it [07:39,  4.90it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true

2298it [07:39,  5.04it/s]

Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

2299it [07:39,  4.99it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

2301it [07:40,  4.99it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phospholipase A2 group VI is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

2303it [07:40,  5.14it/s]

false
Determine whether the semantic relation where physostigmine is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amoxicillin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2305it [07:41,  5.33it/s]

false
Determine whether the semantic relation where scarlet fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2306it [07:41,  4.47it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

2308it [07:41,  4.37it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

2310it [07:42,  4.65it/s]

true
Determine whether the semantic relation where Galanin and GMAP prepropeptide is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tooth mobility is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2311it [07:42,  4.80it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

2312it [07:42,  4.75it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

2313it [07:42,  4.68it/s]

true
Determine whether the semantic relation where end-stage liver disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2315it [07:43,  4.96it/s]

true
Determine whether the semantic relation where sulfasalazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

2317it [07:43,  5.12it/s]

true
Determine whether the semantic relation where trigger finger disorder is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prednisolone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2319it [07:44,  5.10it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

2320it [07:44,  5.18it/s]

false
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2322it [07:44,  4.77it/s]

false
Determine whether the semantic relation where phencyclidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chondrosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2324it [07:45,  5.13it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carboplatin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

2326it [07:45,  5.03it/s]

false
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2328it [07:45,  5.17it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lupus nephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2330it [07:46,  5.46it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Botswana is the object constitutes an accurate semantic relation.

2331it [07:46,  5.53it/s]

true
Determine whether the semantic relation where Botswana is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2333it [07:46,  5.17it/s]

true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily B member 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pre-eclampsia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

2335it [07:47,  4.89it/s]

false
Determine whether the semantic relation where nitroglycerin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

2337it [07:47,  5.09it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

2338it [07:47,  5.14it/s]

true
Determine whether the semantic relation where Luxembourg is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2339it [07:48,  5.01it/s]

true
Determine whether the semantic relation where growth hormone releasing hormone is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

2341it [07:48,  5.06it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Luxembourg is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paraneoplastic neurologic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2343it [07:48,  5.10it/s]

true
Determine whether the semantic relation where lung neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 11b is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

2345it [07:49,  5.07it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

2347it [07:49,  5.09it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

2349it [07:49,  5.21it/s]

true
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2350it [07:50,  4.81it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.

2351it [07:50,  4.57it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2353it [07:50,  4.78it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dental fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2355it [07:51,  4.99it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where kidney disease is the subject, drug or therapy used for treatment is the predicate, and dopamine is the object constitutes an accurate semantic relation.

2357it [07:51,  5.12it/s]

false
Determine whether the semantic relation where dopamine is the subject, medical condition treated is the predicate, and kidney disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

2359it [07:52,  5.23it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prostacyclin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2361it [07:52,  5.33it/s]

true
Determine whether the semantic relation where Guinea is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Histamine receptor H2 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

2363it [07:52,  5.22it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

2365it [07:53,  5.19it/s]

true
Determine whether the semantic relation where ataxia telangiectasia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Gabon is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2367it [07:53,  4.57it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Gabon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where virulent Newcastle disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2368it [07:53,  4.76it/s]

true
Determine whether the semantic relation where thiabendazole is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

2369it [07:54,  4.78it/s]

true
Determine whether the semantic relation where angiostatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2371it [07:54,  4.86it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2373it [07:54,  5.08it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2375it [07:55,  5.35it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

2377it [07:55,  5.26it/s]

true
Determine whether the semantic relation where piracetam is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2379it [07:55,  5.34it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 37 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

2381it [07:56,  5.29it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2383it [07:56,  5.23it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

2385it [07:57,  5.02it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

2387it [07:57,  4.82it/s]

true
Determine whether the semantic relation where anticipation is the subject, instance of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fasciolosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

2389it [07:58,  4.90it/s]

true
Determine whether the semantic relation where infectious bovine rhinotracheitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where embryo loss is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2391it [07:58,  5.15it/s]

false
Determine whether the semantic relation where psoriasis is the subject, risk factor is the predicate, and stress is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

2392it [07:58,  5.11it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

2394it [07:58,  4.96it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and anxiety is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin C is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

2396it [07:59,  5.30it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

2398it [07:59,  4.98it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

2399it [07:59,  4.99it/s]

true
Determine whether the semantic relation where chronic myeloid leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2401it [08:00,  4.63it/s]

true
Determine whether the semantic relation where pasteurellosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2402it [08:00,  4.41it/s]

true
Determine whether the semantic relation where cytokine is the subject, different from is the predicate, and cytokinin is the object constitutes an accurate semantic relation.

2403it [08:00,  4.39it/s]

true
Determine whether the semantic relation where cytokinin is the subject, different from is the predicate, and cytokine is the object constitutes an accurate semantic relation.

2404it [08:01,  4.48it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

2406it [08:01,  4.71it/s]

true
Determine whether the semantic relation where cowpox is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (±)-promethazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2408it [08:01,  5.05it/s]

true
Determine whether the semantic relation where ajmaline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

2410it [08:02,  5.03it/s]

false
Determine whether the semantic relation where Singapore is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

2412it [08:02,  5.12it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where public housing is the subject, country is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2414it [08:03,  5.27it/s]

false
Determine whether the semantic relation where infection is the subject, has effect is the predicate, and heart failure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

2416it [08:03,  5.35it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poly(methyl methacrylate) is the subject, subclass of is the predicate, and ester is the object constitutes an accurate semantic relation.

2418it [08:03,  5.05it/s]

false
Determine whether the semantic relation where heart failure is the subject, has cause is the predicate, and infection is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where smallpox is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

2419it [08:04,  5.18it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Liechtenstein is the object constitutes an accurate semantic relation.

2420it [08:04,  4.84it/s]

true
Determine whether the semantic relation where histamine N-methyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

2421it [08:04,  4.71it/s]

true
Determine whether the semantic relation where nitrous oxide is the subject, medical condition treated is the predicate, and infarction is the object constitutes an accurate semantic relation.

2423it [08:04,  4.85it/s]

false
Determine whether the semantic relation where infarction is the subject, drug or therapy used for treatment is the predicate, and nitrous oxide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where p-chloroamphetamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2425it [08:05,  5.11it/s]

true
Determine whether the semantic relation where Liechtenstein is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where recall is the subject, different from is the predicate, and information retrieval is the object constitutes an accurate semantic relation.

2427it [08:05,  5.09it/s]

false
Determine whether the semantic relation where scrapie is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where information retrieval is the subject, different from is the predicate, and recall is the object constitutes an accurate semantic relation.

2429it [08:06,  5.14it/s]

false
Determine whether the semantic relation where proopiomelanocortin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (R)-2,5-dimethoxy-4-methylamphetamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2430it [08:06,  5.18it/s]

true
Determine whether the semantic relation where trimeprazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2431it [08:06,  4.83it/s]

true
Determine whether the semantic relation where integrin subunit beta 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

2432it [08:06,  4.70it/s]

false
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

2434it [08:07,  4.68it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where G protein-coupled receptor kinase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

2436it [08:07,  4.80it/s]

false
Determine whether the semantic relation where respiratory tract neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inclusion conjunctivitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2438it [08:07,  5.10it/s]

true
Determine whether the semantic relation where central nervous system protozoal infection is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where xylitol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

2440it [08:08,  5.16it/s]

false
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.

2442it [08:08,  5.27it/s]

true
Determine whether the semantic relation where Cambodia is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2443it [08:08,  5.19it/s]

true
Determine whether the semantic relation where Q2839152 is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2445it [08:09,  5.13it/s]

true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

2447it [08:09,  5.36it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, has natural reservoir is the predicate, and fish is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 2',3'-cyclic nucleotide 3' phosphodiesterase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

2448it [08:09,  5.20it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

2450it [08:10,  5.06it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2452it [08:10,  4.70it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

2454it [08:11,  4.89it/s]

false
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where presbyopia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2455it [08:11,  4.45it/s]

true
Determine whether the semantic relation where arachnoiditis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false

2456it [08:11,  4.59it/s]

Determine whether the semantic relation where stomach neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2458it [08:12,  4.82it/s]

true
Determine whether the semantic relation where jejunal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where betamethasone is the subject, medical condition treated is the predicate, and multiple sclerosis is the object constitutes an accurate semantic relation.

2460it [08:12,  4.99it/s]

true
Determine whether the semantic relation where experimental diabetes mellitus is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where The Bahamas is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2462it [08:12,  5.16it/s]

true
Determine whether the semantic relation where multiple sclerosis is the subject, drug or therapy used for treatment is the predicate, and betamethasone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and The Bahamas is the object constitutes an accurate semantic relation.

2463it [08:12,  5.23it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and myocarditis is the object constitutes an accurate semantic relation.

2464it [08:13,  5.12it/s]

false
Determine whether the semantic relation where adenoma is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

2466it [08:13,  5.22it/s]

false
Determine whether the semantic relation where frontotemporal dementia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

2467it [08:13,  5.16it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

2468it [08:14,  4.02it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

2470it [08:14,  4.38it/s]

true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanosine cyclic 3',5'-phosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2471it [08:14,  4.69it/s]

true
Determine whether the semantic relation where gestational trophoblastic disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2473it [08:15,  4.82it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where articaine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2475it [08:15,  5.04it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lice infestation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2477it [08:15,  5.21it/s]

true
Determine whether the semantic relation where Djibouti is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Amphibia is the subject, has use is the predicate, and biological pest control is the object constitutes an accurate semantic relation.

2479it [08:16,  5.23it/s]

true
Determine whether the semantic relation where sodium is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where malignant pleural effusion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2480it [08:16,  4.96it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Djibouti is the object constitutes an accurate semantic relation.

2482it [08:16,  4.78it/s]

true
Determine whether the semantic relation where pharmacy is the subject, part of is the predicate, and biology is the object constitutes an accurate semantic relation.
false

2483it [08:17,  4.90it/s]

Determine whether the semantic relation where melatonin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2485it [08:17,  4.98it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2487it [08:17,  4.99it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true

2488it [08:18,  5.07it/s]

Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.

2490it [08:18,  5.20it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

2492it [08:18,  5.35it/s]

true
Determine whether the semantic relation where Q25241 is the subject, opposite of is the predicate, and invertebrate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Amylo-alpha-1, 6-glucosidase, 4-alpha-glucanotransferase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

2493it [08:19,  5.13it/s]

false
Determine whether the semantic relation where invertebrate is the subject, opposite of is the predicate, and Q25241 is the object constitutes an accurate semantic relation.

2495it [08:19,  4.35it/s]

false
Determine whether the semantic relation where carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lithium is the subject, location of discovery is the predicate, and Sweden is the object constitutes an accurate semantic relation.

2496it [08:19,  4.58it/s]

true
Determine whether the semantic relation where tonsillar neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2497it [08:20,  4.44it/s]

true
Determine whether the semantic relation where major histocompatibility complex, class I, B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

2499it [08:20,  4.69it/s]

true
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2500it [08:20,  4.83it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

2502it [08:21,  4.93it/s]

true
Determine whether the semantic relation where vancomycin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where stereotypic movement disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

2504it [08:21,  5.11it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2506it [08:21,  5.29it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Guyana is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2508it [08:22,  5.42it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Guyana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

2510it [08:22,  5.36it/s]

true
Determine whether the semantic relation where Asperger syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

2512it [08:22,  5.26it/s]

false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

2514it [08:23,  5.27it/s]

true
Determine whether the semantic relation where zeaxanthin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2516it [08:23,  5.18it/s]

true
Determine whether the semantic relation where Colorado tick fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydrogen cyanide is the subject, has characteristic is the predicate, and odor is the object constitutes an accurate semantic relation.

2518it [08:24,  4.90it/s]

true
Determine whether the semantic relation where Alzheimer's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where deoxycytidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2519it [08:24,  4.92it/s]

true
Determine whether the semantic relation where glucose-6-phosphate dehydrogenase deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2521it [08:24,  4.98it/s]

true
Determine whether the semantic relation where lower leg proper is the subject, instance of is the predicate, and animal structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2523it [08:25,  5.23it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

2525it [08:25,  5.30it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where curcumin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

2526it [08:25,  5.28it/s]

true
Determine whether the semantic relation where human musculoskeletal system is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.

2528it [08:26,  5.10it/s]

true
Determine whether the semantic relation where n-pentyl nitrite is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

2529it [08:26,  5.13it/s]

Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and human musculoskeletal system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leishmaniasis is the subject, medical examination is the predicate, and hematology is the object constitutes an accurate semantic relation.

2531it [08:26,  5.22it/s]

false
Determine whether the semantic relation where hydromorphone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where premenstrual syndrome is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

2533it [08:27,  5.25it/s]

true
Determine whether the semantic relation where Papillomavirus infections is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitoxantrone is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

2534it [08:27,  4.92it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and mitoxantrone is the object constitutes an accurate semantic relation.

2536it [08:27,  4.96it/s]

false
Determine whether the semantic relation where oxalic acid is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prader–Willi syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2537it [08:27,  5.13it/s]

false
Determine whether the semantic relation where corneal disease is the subject, drug or therapy used for treatment is the predicate, and deferoxamine is the object constitutes an accurate semantic relation.

2539it [08:28,  5.09it/s]

false
Determine whether the semantic relation where deferoxamine is the subject, medical condition treated is the predicate, and corneal disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where human is the subject, physically interacts with is the predicate, and Earth is the object constitutes an accurate semantic relation.

2540it [08:28,  4.82it/s]

true
Determine whether the semantic relation where ureterolithiasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

2541it [08:28,  4.86it/s]

Determine whether the semantic relation where primary prevention is the subject, facet of is the predicate, and disease is the object constitutes an accurate semantic relation.

2543it [08:29,  4.72it/s]

false
Determine whether the semantic relation where fatigue is the subject, has cause is the predicate, and diabetes is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melanoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2545it [08:29,  4.92it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

2547it [08:29,  5.06it/s]

false
Determine whether the semantic relation where conduct disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 12B is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

2549it [08:30,  5.02it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

2551it [08:30,  5.23it/s]

true
Determine whether the semantic relation where Endothelin 2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Complement C5 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

2552it [08:30,  5.24it/s]

false
Determine whether the semantic relation where degenerative disc disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

2554it [08:31,  4.93it/s]

maybe
Determine whether the semantic relation where cerebral palsy is the subject, medical examination is the predicate, and genetic testing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pethidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2556it [08:31,  4.76it/s]

true
Determine whether the semantic relation where Coagulation factor VIII is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where metabolic syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

2557it [08:31,  4.83it/s]

true
Determine whether the semantic relation where intracranial aneurysm is the subject, has cause is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.

2559it [08:32,  4.91it/s]

true
Determine whether the semantic relation where barium sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arteriovenous malformation is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

2560it [08:32,  5.00it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2561it [08:32,  4.74it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

2563it [08:33,  4.83it/s]

true
Determine whether the semantic relation where sexually transmitted infection is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where systemic inflammatory response syndrome is the subject, health specialty is the predicate, and anaesthesia is the object constitutes an accurate semantic relation.

2565it [08:33,  5.02it/s]

false
Determine whether the semantic relation where D-glucosamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where renal hypertension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2566it [08:33,  5.12it/s]

false
Determine whether the semantic relation where HIV/AIDS is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

2568it [08:34,  5.04it/s]

true
Determine whether the semantic relation where haemophilus meningitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2570it [08:34,  4.71it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alprenolol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2572it [08:35,  4.91it/s]

true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

2574it [08:35,  4.91it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where piroxicam is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2575it [08:35,  4.82it/s]

true
Determine whether the semantic relation where malunited fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2576it [08:35,  4.83it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

2577it [08:36,  4.70it/s]

true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2579it [08:36,  4.82it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

2580it [08:36,  4.98it/s]

true
Determine whether the semantic relation where fluphenazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

2581it [08:36,  4.69it/s]

false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily B member 6 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

2583it [08:37,  4.92it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Neurofibromin 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

2585it [08:37,  5.08it/s]

true
Determine whether the semantic relation where primidone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

2586it [08:37,  5.18it/s]

true
Determine whether the semantic relation where dengue fever is the subject, possible treatment is the predicate, and antihemorrhagic is the object constitutes an accurate semantic relation.

2588it [08:38,  5.06it/s]

false
Determine whether the semantic relation where Tourette syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium hydroxide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

2590it [08:38,  5.07it/s]

false
Determine whether the semantic relation where integrin subunit alpha 5 is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ancylostomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2591it [08:38,  5.05it/s]

true
Determine whether the semantic relation where developmental coordination disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2592it [08:39,  4.88it/s]

true
Determine whether the semantic relation where lymphatic system is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.

2594it [08:39,  3.79it/s]

true
Determine whether the semantic relation where central diabetes insipidus is the subject, subclass of is the predicate, and pancreas disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Bombyx is the object constitutes an accurate semantic relation.

2596it [08:40,  4.48it/s]

false
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and lymphatic system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

2597it [08:40,  4.76it/s]

true
Determine whether the semantic relation where trichuriasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2598it [08:40,  4.59it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

2600it [08:41,  4.55it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Solute carrier family 5 member 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

2602it [08:41,  5.00it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (R)-amygdalin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2604it [08:41,  5.09it/s]

true
Determine whether the semantic relation where buprenorphine is the subject, medical condition treated is the predicate, and arthritis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where arthritis is the subject, drug or therapy used for treatment is the predicate, and buprenorphine is the object constitutes an accurate semantic relation.

2605it [08:41,  5.20it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

2607it [08:42,  5.08it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystic, mucinous, and serous neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2609it [08:42,  5.02it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 22 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

2611it [08:43,  5.10it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where The Bahamas is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2613it [08:43,  5.11it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and The Bahamas is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Greece is the object constitutes an accurate semantic relation.

2614it [08:43,  4.87it/s]

false
Determine whether the semantic relation where heavy chain disease is the subject, subclass of is the predicate, and type IV hypersensitivity is the object constitutes an accurate semantic relation.

2616it [08:44,  5.00it/s]

false
Determine whether the semantic relation where sulbactam is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where The Bahamas is the subject, shares border with is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2618it [08:44,  5.14it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2620it [08:44,  5.19it/s]

true
Determine whether the semantic relation where muscle rigidity is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fludeoxyglucose (18F) is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

2622it [08:45,  5.05it/s]

true
Determine whether the semantic relation where granulomatosis with polyangiitis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ghrelin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

2624it [08:45,  5.21it/s]

false
Determine whether the semantic relation where cefixime is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cerebral toxoplasmosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2626it [08:46,  5.40it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Grenada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Grenada is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2628it [08:46,  5.45it/s]

true
Determine whether the semantic relation where metronidazole is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and metronidazole is the object constitutes an accurate semantic relation.

2630it [08:46,  5.39it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 11-deoxycortisol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2632it [08:47,  5.25it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nimodipine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2633it [08:47,  5.31it/s]

true
Determine whether the semantic relation where codeine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2635it [08:47,  5.27it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

2636it [08:48,  5.19it/s]

true
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2638it [08:48,  5.18it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

2640it [08:48,  5.16it/s]

false
Determine whether the semantic relation where rubella is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where reproductive behavior is the subject, subclass of is the predicate, and animal behavior is the object constitutes an accurate semantic relation.

2642it [08:49,  5.19it/s]

true
Determine whether the semantic relation where theophylline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Oenothera biennis is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2644it [08:49,  5.13it/s]

true
Determine whether the semantic relation where nectar is the subject, subclass of is the predicate, and secretion or excretion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

2646it [08:49,  5.35it/s]

false
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and ascites is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

2647it [08:50,  5.28it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

2649it [08:50,  5.12it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

2650it [08:50,  5.05it/s]

false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2651it [08:50,  4.96it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

2653it [08:51,  5.10it/s]

true
Determine whether the semantic relation where Nucleotide binding oligomerization domain containing 2 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

2655it [08:51,  5.11it/s]

true
Determine whether the semantic relation where hyperbaric medicine is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2657it [08:52,  5.23it/s]

true
Determine whether the semantic relation where Cuba is the subject, shares border with is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where basil is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2659it [08:52,  5.22it/s]

false
Determine whether the semantic relation where leishmaniasis is the subject, risk factor is the predicate, and malnutrition is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (R)-2,5-dimethoxy-4-methylamphetamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2660it [08:52,  5.21it/s]

true
Determine whether the semantic relation where perimeningeal infections is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2662it [08:53,  5.15it/s]

true
Determine whether the semantic relation where thrombophlebitis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Utah is the subject, official symbol is the predicate, and copper is the object constitutes an accurate semantic relation.

2664it [08:53,  5.07it/s]

false
Determine whether the semantic relation where gum guaicum is the subject, has use is the predicate, and antioxidant is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphangioleiomyomatosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2665it [08:53,  4.88it/s]

true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

2666it [08:53,  4.86it/s]

false
Determine whether the semantic relation where organoplatinum compounds is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2668it [08:54,  4.81it/s]

true
Determine whether the semantic relation where fms related receptor tyrosine kinase 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Matrix metallopeptidase 13 is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

2669it [08:54,  4.85it/s]

false
Determine whether the semantic relation where ondansetron is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2671it [08:54,  5.01it/s]

true
Determine whether the semantic relation where fat embolism is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carotid artery thrombosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2672it [08:55,  5.14it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

2674it [08:55,  5.10it/s]

true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

2676it [08:55,  5.02it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uridine 5'-triphosphoric acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

2678it [08:56,  5.16it/s]

false
Determine whether the semantic relation where intense pulsed light is the subject, instance of is the predicate, and technology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2680it [08:56,  5.13it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urea is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

2682it [08:57,  5.21it/s]

false
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2684it [08:57,  5.00it/s]

true
Determine whether the semantic relation where ptosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2686it [08:57,  5.17it/s]

true
Determine whether the semantic relation where methylthiouracil is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

2688it [08:58,  5.24it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

2689it [08:58,  5.33it/s]

false
Determine whether the semantic relation where liver disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false

2691it [08:58,  5.34it/s]

Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

2693it [08:59,  5.32it/s]

true
Determine whether the semantic relation where Natriuretic peptide A is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where drug allergy is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

2695it [08:59,  5.14it/s]

false
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

2697it [08:59,  5.19it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3,3'-diaminobenzidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2698it [09:00,  5.16it/s]

true
Determine whether the semantic relation where Nepal is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

2700it [09:00,  5.19it/s]

false
Determine whether the semantic relation where homovanillic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dracunculiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2702it [09:00,  5.26it/s]

true
Determine whether the semantic relation where hepatitis C is the subject, anatomical location is the predicate, and bone marrow is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ethosuximide is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

2703it [09:01,  5.26it/s]

false
Determine whether the semantic relation where Burkina Faso is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2704it [09:01,  5.16it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Burkina Faso is the object constitutes an accurate semantic relation.

2705it [09:01,  4.95it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

2707it [09:01,  5.03it/s]

true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coagulation factor IX is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

2708it [09:02,  5.08it/s]

true
Determine whether the semantic relation where fluorine is the subject, location of discovery is the predicate, and France is the object constitutes an accurate semantic relation.

2710it [09:02,  5.02it/s]

false
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urogenital neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2711it [09:02,  5.12it/s]

true
Determine whether the semantic relation where Potassium voltage-gated channel subfamily Q member 1 is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.
false

2712it [09:02,  5.08it/s]

Determine whether the semantic relation where quinine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2714it [09:03,  5.04it/s]

true
Determine whether the semantic relation where oxymetazoline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where African trypanosomiasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

2715it [09:03,  5.00it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2716it [09:03,  4.98it/s]

true
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.

2718it [09:04,  5.01it/s]

true
Determine whether the semantic relation where urease complex is the subject, part of is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2719it [09:04,  5.08it/s]

true
Determine whether the semantic relation where nasopharyngeal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2721it [09:04,  5.11it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

2723it [09:05,  5.26it/s]

true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pneumocystis infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2725it [09:05,  5.47it/s]

true
Determine whether the semantic relation where meglumine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where captopril is the subject, medical condition treated is the predicate, and rheumatoid arthritis is the object constitutes an accurate semantic relation.

2727it [09:05,  5.47it/s]

false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rheumatoid arthritis is the subject, drug or therapy used for treatment is the predicate, and captopril is the object constitutes an accurate semantic relation.

2729it [09:06,  5.43it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 19 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

2731it [09:06,  5.30it/s]

true
Determine whether the semantic relation where atrial fibrillation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Meckel's diverticulum is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

2732it [09:06,  4.98it/s]

false
Determine whether the semantic relation where pharynx neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2734it [09:07,  5.04it/s]

true
Determine whether the semantic relation where neurocytoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carrageenan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2736it [09:07,  5.09it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Turkmenistan is the object constitutes an accurate semantic relation.

2738it [09:07,  5.17it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkmenistan is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

2739it [09:08,  5.08it/s]

true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

2740it [09:08,  5.03it/s]

true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2741it [09:08,  4.82it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

2742it [09:08,  4.83it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2744it [09:09,  5.02it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peptide nucleic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2746it [09:09,  4.99it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where agricultural irrigation is the subject, subclass of is the predicate, and transport is the object constitutes an accurate semantic relation.

2748it [09:10,  4.83it/s]

false
Determine whether the semantic relation where conjoined twins is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

2750it [09:10,  4.79it/s]

true
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycopeptide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2752it [09:10,  4.92it/s]

false
Determine whether the semantic relation where Chromogranin A is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fibroblast growth factor 8 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

2754it [09:11,  5.23it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sparganosis is the subject, has natural reservoir is the predicate, and bird is the object constitutes an accurate semantic relation.

2755it [09:11,  5.07it/s]

true
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2757it [09:11,  5.15it/s]

true
Determine whether the semantic relation where nicotinic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pepsinogen is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2759it [09:12,  4.57it/s]

false
Determine whether the semantic relation where Alexander disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

2761it [09:12,  4.92it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

2763it [09:13,  4.86it/s]

false
Determine whether the semantic relation where dexamethasone is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pharmacokinetics is the subject, part of is the predicate, and pharmacy is the object constitutes an accurate semantic relation.

2764it [09:13,  4.76it/s]

true
Determine whether the semantic relation where endometrial neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2766it [09:13,  4.81it/s]

true
Determine whether the semantic relation where L-ornithine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

2767it [09:13,  4.73it/s]

true
Determine whether the semantic relation where dysplasia is the subject, subclass of is the predicate, and congenital abnormality is the object constitutes an accurate semantic relation.

2769it [09:14,  4.76it/s]

true
Determine whether the semantic relation where calcium gluconate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

2770it [09:14,  4.73it/s]

true
Determine whether the semantic relation where croup is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2772it [09:15,  4.74it/s]

true
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where binge eating disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2774it [09:15,  5.09it/s]

true
Determine whether the semantic relation where dermatitis is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sparganosis is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

2775it [09:15,  5.26it/s]

false
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

2777it [09:15,  5.26it/s]

true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Solanum nigrum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cowpox is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

2779it [09:16,  5.14it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cerebrovascular trauma is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2781it [09:16,  5.18it/s]

false
Determine whether the semantic relation where animal toxoplasmosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and cognition is the object constitutes an accurate semantic relation.

2783it [09:17,  5.39it/s]

false
Determine whether the semantic relation where factor XIa [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where serpin family A member 6 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

2785it [09:17,  5.31it/s]

true
Determine whether the semantic relation where clear-cell sarcoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bupropion is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

2787it [09:17,  5.33it/s]

false
Determine whether the semantic relation where suramin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

2789it [09:18,  5.34it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and intestine is the object constitutes an accurate semantic relation.

2790it [09:18,  4.98it/s]

false
Determine whether the semantic relation where berberine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2791it [09:18,  4.95it/s]

true
Determine whether the semantic relation where cerebrospinal fluid rhinorrhoea is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

2793it [09:19,  5.06it/s]

false
Determine whether the semantic relation where ependymoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and lumbar puncture is the object constitutes an accurate semantic relation.

2795it [09:19,  5.25it/s]

maybe
Determine whether the semantic relation where brain ischemia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aminocaproic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2797it [09:19,  5.34it/s]

true
Determine whether the semantic relation where Surfactant protein D is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

2799it [09:20,  5.31it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, religion or worldview is the predicate, and Catholicism is the object constitutes an accurate semantic relation.

2801it [09:20,  5.28it/s]

true
Determine whether the semantic relation where breast disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

2802it [09:20,  5.30it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

2804it [09:21,  4.99it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

2805it [09:21,  5.07it/s]

true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Turkey is the object constitutes an accurate semantic relation.

2807it [09:21,  5.04it/s]

true
Determine whether the semantic relation where hydatidiform mole is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.

2808it [09:21,  5.13it/s]

true
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

2810it [09:22,  5.11it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and gallstone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where encephalopathy is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

2812it [09:22,  5.22it/s]

false
Determine whether the semantic relation where nitrogen mustard is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where precursor B-cell lymphoblastic leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2814it [09:23,  5.05it/s]

true
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where irritable bowel syndrome is the subject, possible treatment is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

2815it [09:23,  5.13it/s]

maybe
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

2816it [09:23,  4.95it/s]

false
Determine whether the semantic relation where pimozide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2817it [09:23,  4.36it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Madagascar is the object constitutes an accurate semantic relation.

2818it [09:24,  4.37it/s]

true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, biological process is the predicate, and long-term potentiation is the object constitutes an accurate semantic relation.

2820it [09:24,  4.57it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

2822it [09:24,  4.91it/s]

true
Determine whether the semantic relation where osmium tetroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tomatine is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

2823it [09:25,  4.98it/s]

true
Determine whether the semantic relation where thymidine monophosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2824it [09:25,  4.80it/s]

true
Determine whether the semantic relation where contagious pustular dermatitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2826it [09:25,  4.84it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

2827it [09:25,  4.93it/s]

false
Determine whether the semantic relation where Neuropeptide Y is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

2829it [09:26,  4.67it/s]

false
Determine whether the semantic relation where pneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where St. Louis encephalitis is the subject, anatomical location is the predicate, and spinal cord is the object constitutes an accurate semantic relation.

2831it [09:26,  5.11it/s]

false
Determine whether the semantic relation where neuropeptide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DL-homocysteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2832it [09:26,  5.16it/s]

true
Determine whether the semantic relation where otorhinolaryngologic neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2834it [09:27,  4.94it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.
true

2835it [09:27,  4.94it/s]

Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parasitic skin disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2837it [09:27,  5.11it/s]

true
Determine whether the semantic relation where azithromycin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2839it [09:28,  5.04it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

2840it [09:28,  4.78it/s]

true
Determine whether the semantic relation where loiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2841it [09:28,  4.59it/s]

true
Determine whether the semantic relation where myelitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

2843it [09:29,  4.75it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

2844it [09:29,  4.79it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2846it [09:29,  4.97it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where snakebite is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2847it [09:29,  5.06it/s]

false
Determine whether the semantic relation where genital herpes is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2849it [09:30,  5.05it/s]

true
Determine whether the semantic relation where islet amyloid polypeptide is the subject, cell component is the predicate, and inclusion body is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EGFR is the subject, expressed in is the predicate, and human penis is the object constitutes an accurate semantic relation.

2851it [09:30,  5.22it/s]

false
Determine whether the semantic relation where droperidol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2853it [09:31,  5.30it/s]

true
Determine whether the semantic relation where coagulation factor IX is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

2855it [09:31,  5.30it/s]

true
Determine whether the semantic relation where nicotinic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.

2857it [09:31,  5.45it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Niger is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

2859it [09:32,  5.52it/s]

true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Niger is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2861it [09:32,  5.55it/s]

false
Determine whether the semantic relation where ocular hypertension is the subject, drug or therapy used for treatment is the predicate, and urea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urea is the subject, medical condition treated is the predicate, and ocular hypertension is the object constitutes an accurate semantic relation.

2862it [09:32,  5.19it/s]

false
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

2864it [09:33,  5.07it/s]

true
Determine whether the semantic relation where PAF is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gestational diabetes is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2866it [09:33,  5.10it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and bradycardia is the object constitutes an accurate semantic relation.

2867it [09:33,  4.52it/s]

false
Determine whether the semantic relation where artificial intelligence is the subject, influenced by is the predicate, and psychology is the object constitutes an accurate semantic relation.

2869it [09:34,  4.80it/s]

true
Determine whether the semantic relation where artificial intelligence is the subject, influenced by is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acetylcarnitine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2871it [09:34,  4.96it/s]

false
Determine whether the semantic relation where Kallikrein related peptidase 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eating is the subject, location is the predicate, and workplace is the object constitutes an accurate semantic relation.

2873it [09:35,  5.21it/s]

false
Determine whether the semantic relation where plasmid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where harmaline is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2874it [09:35,  5.28it/s]

true
Determine whether the semantic relation where life is the subject, has use is the predicate, and reproduction is the object constitutes an accurate semantic relation.

2876it [09:35,  5.15it/s]

false
Determine whether the semantic relation where life is the subject, has characteristic is the predicate, and reproduction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoprotein(a) is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

2878it [09:36,  5.20it/s]

false
Determine whether the semantic relation where hepatitis B is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

2879it [09:36,  5.29it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

2881it [09:36,  5.06it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true

2882it [09:36,  5.04it/s]

Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where multibacillary leprosy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2884it [09:37,  5.17it/s]

true
Determine whether the semantic relation where jaundice is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

2886it [09:37,  5.21it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

2887it [09:37,  4.97it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2889it [09:38,  5.07it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uterine neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2891it [09:38,  5.09it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

2892it [09:38,  5.13it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

2894it [09:39,  4.99it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where enterobactin is the subject, subclass of is the predicate, and macrolides is the object constitutes an accurate semantic relation.

2896it [09:39,  5.09it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where type 2 diabetes is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2898it [09:39,  5.17it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Republic of the Congo is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2900it [09:40,  5.30it/s]

true
Determine whether the semantic relation where strophanthidin is the subject, subclass of is the predicate, and aldehydes is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trazodone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2902it [09:40,  5.42it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2904it [09:41,  5.20it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2905it [09:41,  5.11it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

2907it [09:41,  4.87it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

2908it [09:41,  4.89it/s]

true
Determine whether the semantic relation where synthetic biology is the subject, part of is the predicate, and biophysics is the object constitutes an accurate semantic relation.

2910it [09:42,  4.70it/s]

false
Determine whether the semantic relation where acetylcholine receptor is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.

2911it [09:42,  4.87it/s]

false
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

2912it [09:42,  4.83it/s]

false
Determine whether the semantic relation where chlorpheniramine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

2913it [09:42,  4.79it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

2915it [09:43,  4.88it/s]

true
Determine whether the semantic relation where speech audiometry is the subject, instance of is the predicate, and physical examination is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2916it [09:43,  4.99it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

2918it [09:43,  5.03it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

2920it [09:44,  5.28it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sialolithiasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2922it [09:44,  5.13it/s]

true
Determine whether the semantic relation where sialolithiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ovulation induction is the subject, health specialty is the predicate, and obstetrics is the object constitutes an accurate semantic relation.

2923it [09:44,  5.11it/s]

false
Determine whether the semantic relation where Wnt family member 3A is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.

2925it [09:45,  5.04it/s]

false
Determine whether the semantic relation where Liberia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Liberia is the object constitutes an accurate semantic relation.

2926it [09:45,  4.89it/s]

true
Determine whether the semantic relation where Korean War is the subject, participant is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

2927it [09:45,  4.11it/s]

true
Determine whether the semantic relation where vesicoureteral reflux is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

2928it [09:46,  4.29it/s]

true
Determine whether the semantic relation where pulmonary edema is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2930it [09:46,  4.62it/s]

false
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

2932it [09:46,  4.89it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where toxoplasmosis is the subject, disease transmission process is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.

2933it [09:47,  4.83it/s]

true
Determine whether the semantic relation where growth hormone releasing hormone is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

2935it [09:47,  5.03it/s]

false
Determine whether the semantic relation where (R)-amygdalin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

2936it [09:47,  5.08it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.

2937it [09:47,  4.96it/s]

true
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

2939it [09:48,  4.94it/s]

false
Determine whether the semantic relation where filariasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metabolic brain disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

2940it [09:48,  5.13it/s]

false
Determine whether the semantic relation where atrial flutter is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2942it [09:48,  5.02it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

2944it [09:49,  5.13it/s]

true
Determine whether the semantic relation where tick-borne encephalitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where G protein-coupled receptor kinase 2 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

2945it [09:49,  5.04it/s]

false
Determine whether the semantic relation where aggressive fibromatosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2947it [09:49,  4.61it/s]

true
Determine whether the semantic relation where ventral nuclear group is the subject, subclass of is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cotinine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2949it [09:50,  4.80it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

2950it [09:50,  4.79it/s]

true
Determine whether the semantic relation where opisthorchiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

2952it [09:51,  4.76it/s]

true
Determine whether the semantic relation where pyridoxal is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where leukemia is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

2953it [09:51,  4.94it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

2954it [09:51,  4.19it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

2955it [09:51,  4.06it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.

2957it [09:52,  4.56it/s]

true
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Cucumis sativus is the object constitutes an accurate semantic relation.

2959it [09:52,  5.00it/s]

false
Determine whether the semantic relation where intestinal volvulus is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where onion is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2961it [09:52,  5.23it/s]

false
Determine whether the semantic relation where risperidone is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where methylphenidate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

2962it [09:53,  5.07it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, drug or therapy used for treatment is the predicate, and dexamethasone is the object constitutes an accurate semantic relation.

2964it [09:53,  5.02it/s]

false
Determine whether the semantic relation where blood is the subject, has characteristic is the predicate, and blood pressure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vulvar neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

2966it [09:53,  5.05it/s]

true
Determine whether the semantic relation where cognitive dysfunction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, anatomical location is the predicate, and blood vessel is the object constitutes an accurate semantic relation.

2968it [09:54,  5.23it/s]

false
Determine whether the semantic relation where complement C4A (Rodgers blood group) is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where seasonal affective disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

2970it [09:54,  5.20it/s]

true
Determine whether the semantic relation where granuloma inguinale is the subject, possible treatment is the predicate, and surgical procedure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neural cell adhesion molecule 1 is the subject, biological process is the predicate, and viral entry into host cell is the object constitutes an accurate semantic relation.

2972it [09:55,  5.50it/s]

false
Determine whether the semantic relation where bovine virus diarrhea is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metformin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2974it [09:55,  5.40it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastroesophageal reflux disease is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

2975it [09:55,  5.31it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

2977it [09:56,  5.18it/s]

true
Determine whether the semantic relation where TNF receptor superfamily member 11a is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isoflurane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

2979it [09:56,  5.12it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Dominican Republic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Dominican Republic is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

2981it [09:56,  5.29it/s]

true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 4 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tyramine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

2983it [09:57,  5.30it/s]

false
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

2985it [09:57,  5.17it/s]

true
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

2986it [09:57,  4.55it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

2988it [09:58,  4.70it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

2990it [09:58,  5.04it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, drug or therapy used for treatment is the predicate, and aprotinin is the object constitutes an accurate semantic relation.

2992it [09:59,  5.10it/s]

false
Determine whether the semantic relation where dichlorvos is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lewy body dementia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

2994it [09:59,  5.24it/s]

maybe
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intracranial embolism and thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

2996it [09:59,  5.06it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

2998it [10:00,  5.22it/s]

true
Determine whether the semantic relation where coronary occlusion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where female reproductive system neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3000it [10:00,  5.23it/s]

true
Determine whether the semantic relation where balantidiasis is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

3002it [10:00,  4.94it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

3004it [10:01,  4.78it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3005it [10:01,  4.82it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

3006it [10:01,  4.76it/s]

false
Determine whether the semantic relation where Hong Kong is the subject, religion or worldview is the predicate, and Islam is the object constitutes an accurate semantic relation.

3007it [10:02,  4.77it/s]

false
Determine whether the semantic relation where flood is the subject, has effect is the predicate, and death is the object constitutes an accurate semantic relation.

3008it [10:02,  4.78it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

3009it [10:02,  4.80it/s]

true
Determine whether the semantic relation where dyslexia is the subject, has cause is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

3010it [10:02,  4.73it/s]

maybe
Determine whether the semantic relation where apigenin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3012it [10:03,  4.93it/s]

true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

3014it [10:03,  5.15it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sphingosine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3016it [10:03,  5.37it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anhedonia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

3018it [10:04,  5.46it/s]

false
Determine whether the semantic relation where C-X-C motif chemokine ligand 9 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

3019it [10:04,  5.11it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

3021it [10:04,  5.02it/s]

true
Determine whether the semantic relation where cotinine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alcoholic liver disease is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

3022it [10:05,  4.99it/s]

true
Determine whether the semantic relation where myogenic differentiation 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

3024it [10:05,  4.49it/s]

false
Determine whether the semantic relation where systolic heart failure is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Agouti signaling protein is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3025it [10:05,  4.35it/s]

true
Determine whether the semantic relation where 7,12-dimethylbenzanthracene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true

3027it [10:06,  4.72it/s]

Determine whether the semantic relation where Acrodynia is the subject, subclass of is the predicate, and occupational disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3028it [10:06,  4.84it/s]

true
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

3029it [10:06,  4.76it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3031it [10:06,  4.93it/s]

true
Determine whether the semantic relation where renin is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prochlorperazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3033it [10:07,  5.32it/s]

false
Determine whether the semantic relation where Sierra Leone is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ossification of the posterior longitudinal ligament is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

3035it [10:07,  5.30it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Sierra Leone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fungal meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3036it [10:07,  5.36it/s]

true
Determine whether the semantic relation where neural cell adhesion molecule 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

3037it [10:08,  4.89it/s]

false
Determine whether the semantic relation where cinnarizine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3039it [10:08,  4.95it/s]

true
Determine whether the semantic relation where Iraq War is the subject, country is the predicate, and Poland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where onchocerciasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3041it [10:08,  4.98it/s]

true
Determine whether the semantic relation where woman is the subject, has characteristic is the predicate, and female human reproductive system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily D member 6 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

3042it [10:09,  5.06it/s]

false
Determine whether the semantic relation where Gamma-glutamyl hydrolase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3043it [10:09,  4.96it/s]

false
Determine whether the semantic relation where isosorbide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3045it [10:09,  4.89it/s]

true
Determine whether the semantic relation where anatomy is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brassica napus is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

3047it [10:10,  5.19it/s]

false
Determine whether the semantic relation where sarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anaplasmosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3049it [10:10,  5.20it/s]

true
Determine whether the semantic relation where propionic acidemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

3050it [10:10,  5.31it/s]

Determine whether the semantic relation where epichlorohydrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

3052it [10:11,  5.38it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where insulin receptor is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

3054it [10:11,  5.27it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sialic acids is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3055it [10:11,  5.38it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

3057it [10:12,  5.14it/s]

true
Determine whether the semantic relation where contactin 2 is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where polyethylene terephthalate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3059it [10:12,  5.21it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3061it [10:12,  5.26it/s]

true
Determine whether the semantic relation where pyrroloquinolinedione tricarboxylic acid is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fms related receptor tyrosine kinase 4 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

3062it [10:12,  5.15it/s]

false
Determine whether the semantic relation where trichostrongylosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3064it [10:13,  5.11it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorpromazine is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

3066it [10:13,  5.18it/s]

false
Determine whether the semantic relation where CCK-4 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perennial allergic rhinitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3067it [10:13,  5.14it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

3069it [10:14,  4.97it/s]

true
Determine whether the semantic relation where radius fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

3071it [10:14,  5.02it/s]

true
Determine whether the semantic relation where Keratin 19 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cocaine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3072it [10:14,  5.12it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

3074it [10:15,  5.11it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

3076it [10:15,  4.97it/s]

true
Determine whether the semantic relation where paracoccidioidomycosis is the subject, anatomical location is the predicate, and bone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

3078it [10:16,  5.12it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HIV-associated lipodystrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3080it [10:16,  5.18it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

3082it [10:16,  5.29it/s]

true
Determine whether the semantic relation where cefuroxime is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where doxylamine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3084it [10:17,  5.26it/s]

false
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where edentulous jaw is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3086it [10:17,  5.36it/s]

false
Determine whether the semantic relation where central nervous system cyst is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.

3088it [10:18,  5.33it/s]

true
Determine whether the semantic relation where meningocele is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

3089it [10:18,  4.96it/s]

true
Determine whether the semantic relation where cutaneous larva migrans is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3091it [10:18,  4.60it/s]

true
Determine whether the semantic relation where signal transducer and activator of transcription 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where East Germany is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.

3092it [10:19,  4.43it/s]

false
Determine whether the semantic relation where hepatitis A is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

3093it [10:19,  4.55it/s]

true
Determine whether the semantic relation where cystoisosporiasis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

3095it [10:19,  4.83it/s]

false
Determine whether the semantic relation where tinea pedis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dentistry is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

3097it [10:19,  5.19it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cantharidin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3099it [10:20,  5.25it/s]

true
Determine whether the semantic relation where dracunculiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

3101it [10:20,  5.30it/s]

true
Determine whether the semantic relation where anticipation is the subject, studied by is the predicate, and medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mikulicz disease is the subject, subclass of is the predicate, and autoimmune disease of the nervous system is the object constitutes an accurate semantic relation.

3103it [10:21,  5.16it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3105it [10:21,  5.11it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

3107it [10:21,  5.24it/s]

true
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD274 molecule is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

3108it [10:22,  5.33it/s]

false
Determine whether the semantic relation where anthrax is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3109it [10:22,  5.09it/s]

true
Determine whether the semantic relation where nitrogen mustard is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3110it [10:22,  4.97it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3112it [10:22,  5.22it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phlebotomus fever is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

3114it [10:23,  5.27it/s]

false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where furosemide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3116it [10:23,  5.15it/s]

false
Determine whether the semantic relation where strontium is the subject, location of discovery is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where theobromine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3117it [10:23,  5.23it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

3118it [10:24,  4.93it/s]

true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3120it [10:24,  5.03it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where proteinuria is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

3121it [10:24,  4.87it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

3122it [10:24,  4.60it/s]

true
Determine whether the semantic relation where metabolic syndrome is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.

3123it [10:25,  4.68it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3125it [10:25,  4.95it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oroantral fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3127it [10:25,  5.05it/s]

true
Determine whether the semantic relation where chikungunya is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

3129it [10:26,  5.13it/s]

true
Determine whether the semantic relation where ethionamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where AIDS related disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3130it [10:26,  5.24it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

3131it [10:26,  4.88it/s]

false
Determine whether the semantic relation where biotin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3132it [10:26,  4.77it/s]

false
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3134it [10:27,  5.02it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where histology is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

3136it [10:27,  5.15it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where jaw is the subject, subclass of is the predicate, and animal structure is the object constitutes an accurate semantic relation.

3138it [10:28,  5.18it/s]

true
Determine whether the semantic relation where clozapine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

3139it [10:28,  5.07it/s]

true
Determine whether the semantic relation where epoxy resins is the subject, instance of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.

3140it [10:28,  5.02it/s]

false
Determine whether the semantic relation where gout is the subject, has contributing factor is the predicate, and genetics is the object constitutes an accurate semantic relation.
true

3141it [10:28,  5.00it/s]

Determine whether the semantic relation where carbon monoxide poisoning is the subject, afflicts is the predicate, and blood is the object constitutes an accurate semantic relation.

3142it [10:28,  4.92it/s]

false
Determine whether the semantic relation where crystallization is the subject, subclass of is the predicate, and stochastic process is the object constitutes an accurate semantic relation.

3144it [10:29,  4.90it/s]

false
Determine whether the semantic relation where horizontal gene transfer is the subject, subclass of is the predicate, and cellular process or phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3145it [10:29,  4.70it/s]

true
Determine whether the semantic relation where Dominican Republic is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3147it [10:29,  4.64it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

3149it [10:30,  5.01it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pethidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3150it [10:30,  4.89it/s]

true
Determine whether the semantic relation where anesthetic is the subject, different from is the predicate, and aesthetics is the object constitutes an accurate semantic relation.

3151it [10:30,  4.45it/s]

false
Determine whether the semantic relation where histology is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.

3152it [10:31,  4.56it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and (RS)-mianserin is the object constitutes an accurate semantic relation.

3154it [10:31,  4.63it/s]

false
Determine whether the semantic relation where Japanese encephalitis is the subject, symptoms and signs is the predicate, and mental confusion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

3156it [10:31,  4.97it/s]

false
Determine whether the semantic relation where Far East scarlet-like fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital toxoplasmosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3157it [10:32,  4.92it/s]

false
Determine whether the semantic relation where extrinsic allergic alveolitis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

3159it [10:32,  5.04it/s]

true
Determine whether the semantic relation where virulent Newcastle disease is the subject, symptoms and signs is the predicate, and paralysis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diagnosis is the subject, part of is the predicate, and problem solving is the object constitutes an accurate semantic relation.

3161it [10:32,  4.51it/s]

false
Determine whether the semantic relation where sigmoid neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where D-methamphetamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3162it [10:33,  4.65it/s]

true
Determine whether the semantic relation where hereditary haemochromatosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

3163it [10:33,  4.72it/s]

true
Determine whether the semantic relation where traffic collision is the subject, has contributing factor is the predicate, and weather is the object constitutes an accurate semantic relation.

3165it [10:33,  4.82it/s]

true
Determine whether the semantic relation where heroin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.

3166it [10:33,  4.86it/s]

false
Determine whether the semantic relation where Calnexin is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

3168it [10:34,  4.90it/s]

false
Determine whether the semantic relation where casein is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mucin 6, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

3169it [10:34,  4.96it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3171it [10:35,  4.98it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

3172it [10:35,  4.93it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

3173it [10:35,  4.84it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.

3174it [10:35,  4.58it/s]

true
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3175it [10:35,  4.33it/s]

true
Determine whether the semantic relation where phase III clinical trial is the subject, participant is the predicate, and patient is the object constitutes an accurate semantic relation.

3177it [10:36,  4.55it/s]

false
Determine whether the semantic relation where natural language processing is the subject, subclass of is the predicate, and industry is the object constitutes an accurate semantic relation.
false

3178it [10:36,  4.70it/s]

Determine whether the semantic relation where circadian rhythm sleep disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where borderline personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3180it [10:36,  4.94it/s]

true
Determine whether the semantic relation where glycogen phosphorylase, muscle associated is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanosine triphosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3181it [10:37,  4.51it/s]

true
Determine whether the semantic relation where hepatoblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3182it [10:37,  4.55it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

3184it [10:37,  4.63it/s]

false
Determine whether the semantic relation where nalidixic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and procainamide is the object constitutes an accurate semantic relation.

3186it [10:38,  4.76it/s]

true
Determine whether the semantic relation where procainamide is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where endocrine bone disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

3188it [10:38,  4.71it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

3189it [10:38,  4.87it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and inflammation is the object constitutes an accurate semantic relation.

3191it [10:39,  4.81it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, medical examination is the predicate, and microscopy is the object constitutes an accurate semantic relation.
true

3192it [10:39,  4.90it/s]

Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

3193it [10:39,  5.01it/s]

false
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3195it [10:40,  4.89it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where brucellosis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

3197it [10:40,  5.16it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where curcumin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3198it [10:40,  5.10it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and chronic renal insufficiency is the object constitutes an accurate semantic relation.
true

3200it [10:41,  5.15it/s]

Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and peptic ulcer disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where air embolism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3202it [10:41,  5.26it/s]

true
Determine whether the semantic relation where dipetalonemiasis is the subject, subclass of is the predicate, and eye disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq War is the subject, country is the predicate, and Australia is the object constitutes an accurate semantic relation.

3204it [10:41,  5.10it/s]

false
Determine whether the semantic relation where Iraq War is the subject, participant is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3206it [10:42,  5.11it/s]

true
Determine whether the semantic relation where gastric ulcer is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

3208it [10:42,  5.09it/s]

true
Determine whether the semantic relation where Australia is the subject, participant in is the predicate, and Iraq War is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where migraine is the subject, drug or therapy used for treatment is the predicate, and fentanyl is the object constitutes an accurate semantic relation.

3210it [10:43,  4.99it/s]

false
Determine whether the semantic relation where fentanyl is the subject, medical condition treated is the predicate, and migraine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where T-cell lymphoma is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

3211it [10:43,  5.01it/s]

true
Determine whether the semantic relation where N-acetylneuraminic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3212it [10:43,  4.77it/s]

true
Determine whether the semantic relation where corticotropin releasing hormone is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3214it [10:43,  5.00it/s]

false
Determine whether the semantic relation where botulism is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where psilocybin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3215it [10:44,  5.05it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

3216it [10:44,  5.01it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3218it [10:44,  4.86it/s]

true
Determine whether the semantic relation where vascular system injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where abdominal aortic aneurysm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3220it [10:45,  5.06it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and (RS)-sulpiride is the object constitutes an accurate semantic relation.

3222it [10:45,  5.13it/s]

true
Determine whether the semantic relation where (RS)-sulpiride is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3223it [10:45,  5.11it/s]

true
Determine whether the semantic relation where Chagas disease is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

3225it [10:46,  5.15it/s]

false
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where renin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3227it [10:46,  5.25it/s]

false
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and bronchitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where type I site-specific deoxyribonuclease complex is the subject, part of is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3229it [10:46,  5.18it/s]

false
Determine whether the semantic relation where empyema is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholera is the subject, symptoms and signs is the predicate, and hypotension is the object constitutes an accurate semantic relation.

3230it [10:47,  5.27it/s]

true
Determine whether the semantic relation where Mexico is the subject, participant in is the predicate, and World War II is the object constitutes an accurate semantic relation.

3231it [10:47,  5.10it/s]

true
Determine whether the semantic relation where cilazapril is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

3233it [10:47,  4.70it/s]

true
Determine whether the semantic relation where logic is the subject, has part(s) is the predicate, and causality is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where causality is the subject, part of is the predicate, and logic is the object constitutes an accurate semantic relation.

3235it [10:48,  4.70it/s]

false
Determine whether the semantic relation where hydroxyethylrutoside is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true

3236it [10:48,  4.77it/s]

Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.
true

3237it [10:48,  4.85it/s]

Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

3239it [10:48,  4.86it/s]

true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where posterior pituitary hormones is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3240it [10:49,  4.60it/s]

false
Determine whether the semantic relation where aspirin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3241it [10:49,  4.67it/s]

false
Determine whether the semantic relation where heptanoic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3242it [10:49,  4.12it/s]

true
Determine whether the semantic relation where auranofin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3244it [10:50,  4.53it/s]

true
Determine whether the semantic relation where uracil is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

3246it [10:50,  4.84it/s]

true
Determine whether the semantic relation where MDMA is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

3248it [10:50,  5.09it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

3249it [10:51,  4.71it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

3250it [10:51,  4.74it/s]

true
Determine whether the semantic relation where cefaclor is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

3252it [10:51,  4.88it/s]

false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

3253it [10:51,  4.92it/s]

true
Determine whether the semantic relation where electrostimulation is the subject, has use is the predicate, and research is the object constitutes an accurate semantic relation.

3254it [10:52,  4.92it/s]

true
Determine whether the semantic relation where myalgia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3255it [10:52,  4.88it/s]

false
Determine whether the semantic relation where Pseudomonas infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

3257it [10:52,  5.01it/s]

Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HIV/AIDS is the subject, instance of is the predicate, and pandemic is the object constitutes an accurate semantic relation.

3259it [10:53,  5.25it/s]

true
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascariasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3260it [10:53,  5.31it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.

3262it [10:53,  5.18it/s]

true
Determine whether the semantic relation where alcohol consumption is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

3263it [10:53,  5.22it/s]

false
Determine whether the semantic relation where curare is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3264it [10:54,  4.91it/s]

false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

3266it [10:54,  4.95it/s]

true
Determine whether the semantic relation where maltose is the subject, found in taxon is the predicate, and Staphylococcus aureus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and Astragalus membranaceus is the object constitutes an accurate semantic relation.

3267it [10:54,  4.90it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

3269it [10:55,  4.38it/s]

true
Determine whether the semantic relation where Taiwan is the subject, significant event is the predicate, and World War II is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Interleukin 10 receptor subunit alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

3270it [10:55,  4.55it/s]

true
Determine whether the semantic relation where DL-dopa is the subject, subclass of is the predicate, and polyphenol is the object constitutes an accurate semantic relation.

3272it [10:55,  4.52it/s]

false
Determine whether the semantic relation where tauopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tauopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3274it [10:56,  4.94it/s]

true
Determine whether the semantic relation where avian influenza is the subject, symptoms and signs is the predicate, and pneumonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 2C is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3276it [10:56,  5.06it/s]

true
Determine whether the semantic relation where thyrotropin-releasing hormone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

3278it [10:57,  5.08it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where corneal damage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3280it [10:57,  4.96it/s]

false
Determine whether the semantic relation where glial fibrillary acidic protein is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psoralen is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3282it [10:57,  5.08it/s]

false
Determine whether the semantic relation where cerebral arteriovenous malformation is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

3284it [10:58,  5.08it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

3285it [10:58,  5.20it/s]

true
Determine whether the semantic relation where choline O-acetyltransferase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

3287it [10:58,  5.19it/s]

false
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

3289it [10:59,  5.37it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protein unfolding is the subject, subclass of is the predicate, and cellular process or phenomenon is the object constitutes an accurate semantic relation.

3291it [10:59,  5.31it/s]

true
Determine whether the semantic relation where biophysics is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where biophysics is the subject, part of is the predicate, and biology is the object constitutes an accurate semantic relation.

3292it [10:59,  5.22it/s]

true
Determine whether the semantic relation where renin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

3294it [11:00,  4.89it/s]

false
Determine whether the semantic relation where photogrammetry is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where copying is the subject, used by is the predicate, and DNA replication is the object constitutes an accurate semantic relation.

3295it [11:00,  4.72it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

3297it [11:00,  4.81it/s]

true
Determine whether the semantic relation where nephritis is the subject, drug or therapy used for treatment is the predicate, and magnesium sulfate is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

3299it [11:01,  5.03it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3300it [11:01,  5.20it/s]

true
Determine whether the semantic relation where hypothalamic disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3301it [11:01,  5.09it/s]

true
Determine whether the semantic relation where foscarnet is the subject, subject has role is the predicate, and Q50315890 is the object constitutes an accurate semantic relation.

3303it [11:02,  5.04it/s]

false
Determine whether the semantic relation where ehrlichiosis is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebrospinal fluid leak is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3304it [11:02,  4.95it/s]

false
Determine whether the semantic relation where Synuclein is the subject, subclass of is the predicate, and pore-forming toxin is the object constitutes an accurate semantic relation.

3305it [11:02,  4.82it/s]

false
Determine whether the semantic relation where digestive system neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3306it [11:02,  4.74it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

3308it [11:03,  4.70it/s]

false
Determine whether the semantic relation where human trafficking is the subject, instance of is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Meckel's diverticulum is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

3310it [11:03,  4.91it/s]

false
Determine whether the semantic relation where calcium is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlorpromazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3311it [11:03,  5.04it/s]

true
Determine whether the semantic relation where piperacillin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

3313it [11:04,  5.05it/s]

false
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Suriname is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3314it [11:04,  5.07it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Suriname is the object constitutes an accurate semantic relation.

3316it [11:04,  4.94it/s]

true
Determine whether the semantic relation where Chromogranin A is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

3318it [11:05,  5.14it/s]

false
Determine whether the semantic relation where ectopic pregnancy is the subject, health specialty is the predicate, and midwifery is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neurological disorder is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

3320it [11:05,  5.34it/s]

true
Determine whether the semantic relation where bovine tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where collagen disease is the subject, afflicts is the predicate, and muscle is the object constitutes an accurate semantic relation.

3322it [11:05,  5.17it/s]

maybe
Determine whether the semantic relation where adenovirus infection is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where body size is the subject, used by is the predicate, and biostatistics is the object constitutes an accurate semantic relation.

3324it [11:06,  5.21it/s]

false
Determine whether the semantic relation where diagnosis is the subject, subclass of is the predicate, and classification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inborn errors of purine–pyrimidine metabolism is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

3326it [11:06,  5.19it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

3327it [11:06,  5.27it/s]

false
Determine whether the semantic relation where 5-HTP is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3329it [11:07,  5.10it/s]

true
Determine whether the semantic relation where glycocalyx is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where topotecan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3331it [11:07,  4.98it/s]

false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

3333it [11:08,  5.08it/s]

true
Determine whether the semantic relation where astemizole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

3335it [11:08,  5.31it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Honduras is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

3337it [11:08,  5.40it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Honduras is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3339it [11:09,  5.24it/s]

false
Determine whether the semantic relation where biotin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

3341it [11:09,  5.25it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

3343it [11:09,  5.15it/s]

true
Determine whether the semantic relation where hymenolepiasis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thyroid stimulating hormone receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

3344it [11:10,  5.17it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

3345it [11:10,  5.05it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

3347it [11:10,  5.02it/s]

false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where body surface area is the subject, P642 is the predicate, and medicine is the object constitutes an accurate semantic relation.

3349it [11:11,  5.15it/s]

false
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyritinol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3351it [11:11,  5.24it/s]

true
Determine whether the semantic relation where lac repressor is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where laryngeal disease is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

3353it [11:11,  5.03it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, afflicts is the predicate, and human eye is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichostrongyloidosis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

3355it [11:12,  5.13it/s]

true
Determine whether the semantic relation where quintuplets is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

3357it [11:12,  5.01it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenine is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

3359it [11:13,  4.49it/s]

false
Determine whether the semantic relation where deslanoside is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where atypical chemokine receptor 1 (Duffy blood group) is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

3361it [11:13,  4.72it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and pergolide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where esophageal and gastric varices is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3363it [11:14,  4.80it/s]

true
Determine whether the semantic relation where histone deacetylase 1 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

3364it [11:14,  4.95it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

3365it [11:14,  4.83it/s]

true
Determine whether the semantic relation where lipoma is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

3366it [11:14,  4.84it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and marsh frog is the object constitutes an accurate semantic relation.

3368it [11:15,  4.94it/s]

false
Determine whether the semantic relation where foot-and-mouth disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

3370it [11:15,  5.04it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart failure is the subject, has cause is the predicate, and alcoholism is the object constitutes an accurate semantic relation.

3372it [11:15,  5.14it/s]

true
Determine whether the semantic relation where alcoholism is the subject, has effect is the predicate, and heart failure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cefoxitin is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

3373it [11:15,  5.27it/s]

true
Determine whether the semantic relation where CDKN2A is the subject, expressed in is the predicate, and tongue is the object constitutes an accurate semantic relation.
false

3374it [11:16,  5.17it/s]

Determine whether the semantic relation where complete edentulism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3376it [11:16,  4.96it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3378it [11:17,  5.09it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

3380it [11:17,  4.99it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3381it [11:17,  5.10it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

3383it [11:18,  4.88it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Italy is the object constitutes an accurate semantic relation.
false

3384it [11:18,  5.00it/s]

Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

3386it [11:18,  5.25it/s]

true
Determine whether the semantic relation where forskolin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HELLP syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3388it [11:18,  5.18it/s]

true
Determine whether the semantic relation where hypertriglyceridemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where skin disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

3389it [11:19,  5.10it/s]

true
Determine whether the semantic relation where coronary aneurysm is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

3390it [11:19,  5.03it/s]

true
Determine whether the semantic relation where major depressive disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3391it [11:19,  4.96it/s]

true
Determine whether the semantic relation where Anseriformes is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3393it [11:19,  5.05it/s]

true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

3395it [11:20,  5.07it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ciprofloxacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3397it [11:20,  5.20it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

3399it [11:21,  4.75it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucagon is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3401it [11:21,  5.11it/s]

false
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where post-polio syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3403it [11:21,  5.18it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

3405it [11:22,  5.20it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ammonium chloride is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

3407it [11:22,  4.90it/s]

true
Determine whether the semantic relation where neuroblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scrub typhus is the subject, anatomical location is the predicate, and endothelium is the object constitutes an accurate semantic relation.

3409it [11:23,  4.95it/s]

true
Determine whether the semantic relation where sulfamethizole is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where manganese is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

3411it [11:23,  4.98it/s]

false
Determine whether the semantic relation where JUN is the subject, expressed in is the predicate, and gastric mucosa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where selenious acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3413it [11:24,  5.05it/s]

true
Determine whether the semantic relation where HIV/AIDS is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TP53 is the subject, expressed in is the predicate, and monocyte is the object constitutes an accurate semantic relation.

3415it [11:24,  5.16it/s]

false
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tooth demineralization is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3416it [11:24,  5.24it/s]

false
Determine whether the semantic relation where glandular and epithelial neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3418it [11:24,  5.25it/s]

true
Determine whether the semantic relation where Turkmenistan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Turkmenistan is the object constitutes an accurate semantic relation.

3420it [11:25,  5.38it/s]

true
Determine whether the semantic relation where sucralfate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mitogen-activated protein kinase kinase kinase 5 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

3422it [11:25,  5.35it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

3424it [11:26,  5.34it/s]

true
Determine whether the semantic relation where erectile dysfunction is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rett syndrome is the subject, symptoms and signs is the predicate, and cognitive dysfunction is the object constitutes an accurate semantic relation.

3426it [11:26,  5.24it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Botswana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Botswana is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3427it [11:26,  5.16it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, subclass of is the predicate, and skin infection is the object constitutes an accurate semantic relation.

3429it [11:27,  5.04it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Botswana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Botswana is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3431it [11:27,  5.03it/s]

true
Determine whether the semantic relation where stress is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where legionnaires' disease is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

3432it [11:27,  4.99it/s]

maybe
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3434it [11:28,  5.05it/s]

true
Determine whether the semantic relation where peritonitis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MDMA is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3436it [11:28,  5.19it/s]

true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

3438it [11:28,  4.84it/s]

true
Determine whether the semantic relation where enterocolitis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3439it [11:29,  4.91it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

3440it [11:29,  4.78it/s]

false
Determine whether the semantic relation where cholesterol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3442it [11:29,  4.87it/s]

false
Determine whether the semantic relation where artificial lens implant migration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where methemoglobinemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3443it [11:29,  4.95it/s]

true
Determine whether the semantic relation where type III site-specific deoxyribonuclease complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

3445it [11:30,  4.96it/s]

true
Determine whether the semantic relation where perphenazine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where particulates is the subject, has effect is the predicate, and cardiovascular disease is the object constitutes an accurate semantic relation.

3446it [11:30,  4.97it/s]

true
Determine whether the semantic relation where deoxythymidine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3448it [11:30,  5.09it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

3450it [11:31,  5.21it/s]

true
Determine whether the semantic relation where whiplash injuries is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

3452it [11:31,  5.03it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where short bowel syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3453it [11:31,  4.49it/s]

true
Determine whether the semantic relation where (S)-(−)-colchicine is the subject, has use is the predicate, and science is the object constitutes an accurate semantic relation.

3455it [11:32,  4.66it/s]

false
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

3457it [11:32,  5.04it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and shock is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, afflicts is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

3458it [11:32,  5.01it/s]

true
Determine whether the semantic relation where phenmetrazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3459it [11:33,  4.95it/s]

true
Determine whether the semantic relation where malignant hyperthermia is the subject, subclass of is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.

3461it [11:33,  5.05it/s]

false
Determine whether the semantic relation where ornithosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

3462it [11:33,  5.18it/s]

false
Determine whether the semantic relation where levofloxacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3463it [11:33,  5.02it/s]

true
Determine whether the semantic relation where tubocurarine is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

3464it [11:34,  4.99it/s]

false
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and kidney is the object constitutes an accurate semantic relation.

3466it [11:34,  4.99it/s]

false
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, possible treatment is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Kallikrein related peptidase 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

3468it [11:34,  5.07it/s]

false
Determine whether the semantic relation where Clock circadian regulator is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteopenia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

3469it [11:35,  5.01it/s]

false
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3471it [11:35,  4.97it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

3472it [11:35,  4.95it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

3473it [11:36,  4.74it/s]

true
Determine whether the semantic relation where thyroid nodule is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3474it [11:36,  4.77it/s]

false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3476it [11:36,  4.62it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3477it [11:36,  4.75it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.

3479it [11:37,  5.02it/s]

false
Determine whether the semantic relation where Duchenne muscular dystrophy is the subject, possible treatment is the predicate, and occupational therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

3481it [11:37,  5.09it/s]

true
Determine whether the semantic relation where coarctation of the aorta is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true

3482it [11:37,  5.15it/s]

Determine whether the semantic relation where hydroxylapatite is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

3484it [11:38,  5.22it/s]

true
Determine whether the semantic relation where ossification of the posterior longitudinal ligament is the subject, subclass of is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where loiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3485it [11:38,  5.13it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3487it [11:38,  4.90it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypophosphatemic rickets is the subject, health specialty is the predicate, and nutrition is the object constitutes an accurate semantic relation.

3488it [11:39,  5.03it/s]

false
Determine whether the semantic relation where integrin subunit beta 2 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

3490it [11:39,  4.94it/s]

false
Determine whether the semantic relation where cimetidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

3491it [11:39,  5.05it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 10 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

3493it [11:40,  4.78it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

3495it [11:40,  5.08it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where denture stomatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3497it [11:40,  4.98it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

3498it [11:41,  5.03it/s]

true
Determine whether the semantic relation where methylmalonic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

3500it [11:41,  5.01it/s]

false
Determine whether the semantic relation where chronic kidney failure is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3502it [11:41,  5.12it/s]

true
Determine whether the semantic relation where DNA polymerase beta is the subject, cell component is the predicate, and microtubule is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chymopapain is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

3503it [11:42,  4.86it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3504it [11:42,  4.83it/s]

true
Determine whether the semantic relation where Republic of the Congo is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3506it [11:42,  4.96it/s]

true
Determine whether the semantic relation where familial hypercholesterolemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.

3508it [11:43,  5.17it/s]

true
Determine whether the semantic relation where hemarthrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

3509it [11:43,  5.29it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

3511it [11:43,  5.13it/s]

true
Determine whether the semantic relation where furanocoumarin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.

3512it [11:43,  5.02it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

3514it [11:44,  3.97it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3516it [11:44,  4.39it/s]

true
Determine whether the semantic relation where thromboxane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central auditory disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3518it [11:45,  4.86it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 25 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where maxillary fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3520it [11:45,  5.14it/s]

false
Determine whether the semantic relation where oligodendroglioma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urocanate hydratase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

3522it [11:46,  5.03it/s]

true
Determine whether the semantic relation where urocanate hydratase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Erdheim-Chester disease is the subject, subclass of is the predicate, and connective tissue neoplasm is the object constitutes an accurate semantic relation.

3524it [11:46,  5.32it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3526it [11:46,  5.12it/s]

true
Determine whether the semantic relation where ghrelin is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Histamine receptor H3 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

3528it [11:47,  4.81it/s]

false
Determine whether the semantic relation where alkaptonuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

3530it [11:47,  4.89it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dynorphin is the subject, subclass of is the predicate, and pore-forming toxin is the object constitutes an accurate semantic relation.

3532it [11:48,  5.05it/s]

false
Determine whether the semantic relation where pacifier is the subject, made from material is the predicate, and plastic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where growth hormone releasing hormone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3534it [11:48,  5.09it/s]

false
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

3536it [11:48,  5.31it/s]

true
Determine whether the semantic relation where tendinopathy is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where strongyloidiasis is the subject, subclass of is the predicate, and central nervous system disease is the object constitutes an accurate semantic relation.

3538it [11:49,  5.31it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

3539it [11:49,  5.17it/s]

true
Determine whether the semantic relation where X-linked hypophosphatemic rickets is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

3541it [11:49,  4.77it/s]

true
Determine whether the semantic relation where pentetrazol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where satellite imagery is the subject, subclass of is the predicate, and photography is the object constitutes an accurate semantic relation.

3543it [11:50,  4.85it/s]

true
Determine whether the semantic relation where arachidonic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bacterial vaginosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3544it [11:50,  4.67it/s]

true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

3545it [11:50,  4.61it/s]

true
Determine whether the semantic relation where actinomycosis is the subject, anatomical location is the predicate, and muscle is the object constitutes an accurate semantic relation.

3546it [11:50,  4.61it/s]

false
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3547it [11:51,  4.68it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

3549it [11:51,  4.91it/s]

false
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

3551it [11:51,  5.15it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

3552it [11:52,  4.93it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

3554it [11:52,  5.06it/s]

true
Determine whether the semantic relation where cytosine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chronic granulomatous disease is the subject, anatomical location is the predicate, and bone is the object constitutes an accurate semantic relation.

3555it [11:52,  5.03it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

3557it [11:53,  4.88it/s]

true
Determine whether the semantic relation where endemic typhus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypertensive encephalopathy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

3558it [11:53,  4.96it/s]

false
Determine whether the semantic relation where acute coronary syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3560it [11:53,  4.69it/s]

true
Determine whether the semantic relation where genodermatosis is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coccidiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3562it [11:54,  4.99it/s]

true
Determine whether the semantic relation where phenylethyl alcohol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3563it [11:54,  5.17it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

3564it [11:54,  4.72it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

3565it [11:54,  4.63it/s]

true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

3566it [11:55,  4.48it/s]

false
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Momordica charantia is the object constitutes an accurate semantic relation.

3567it [11:55,  3.68it/s]

false
Determine whether the semantic relation where cartilage oligomeric matrix protein is the subject, biological process is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.

3568it [11:55,  3.81it/s]

false
Determine whether the semantic relation where C-peptide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3570it [11:56,  4.36it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3571it [11:56,  4.51it/s]

true
Determine whether the semantic relation where chromatography is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

3573it [11:56,  4.72it/s]

false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.

3575it [11:57,  5.02it/s]

true
Determine whether the semantic relation where oviposition is the subject, subclass of is the predicate, and reproductive behavior is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ovarian neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3577it [11:57,  5.10it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and electrocardiography is the object constitutes an accurate semantic relation.

3579it [11:57,  5.09it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

3580it [11:58,  5.19it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3582it [11:58,  5.01it/s]

true
Determine whether the semantic relation where GNAS complex locus is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3584it [11:58,  5.22it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

3586it [11:59,  5.33it/s]

false
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amantadine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3587it [11:59,  5.10it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

3589it [11:59,  5.07it/s]

true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psilocybin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3590it [12:00,  5.11it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Rwanda is the object constitutes an accurate semantic relation.

3592it [12:00,  5.10it/s]

true
Determine whether the semantic relation where Rwanda is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyclic ADP-ribose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3593it [12:00,  5.25it/s]

true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

3595it [12:01,  5.16it/s]

false
Determine whether the semantic relation where sexually transmitted infection is the subject, symptoms and signs is the predicate, and myalgic encephalomyelitis/chronic fatigue syndrome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where avian tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3596it [12:01,  4.96it/s]

true
Determine whether the semantic relation where cysticercosis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

3597it [12:01,  4.66it/s]

false
Determine whether the semantic relation where urease complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

3598it [12:01,  4.65it/s]

false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and amitriptyline is the object constitutes an accurate semantic relation.

3599it [12:01,  4.59it/s]

false
Determine whether the semantic relation where ceftriaxone is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

3601it [12:02,  4.73it/s]

false
Determine whether the semantic relation where insect-inflicted wound is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where CD27 molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3602it [12:02,  4.89it/s]

true
Determine whether the semantic relation where domperidone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3603it [12:02,  4.89it/s]

false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 9 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

3605it [12:03,  4.87it/s]

true
Determine whether the semantic relation where hypothalamic hormones is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hexosaminidase subunit alpha is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

3607it [12:03,  4.86it/s]

true
Determine whether the semantic relation where glutamic-pyruvic transaminase is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where opportunistic infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3609it [12:03,  5.09it/s]

true
Determine whether the semantic relation where dactinomycin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

3611it [12:04,  5.22it/s]

true
Determine whether the semantic relation where Somalia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3613it [12:04,  5.12it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Somalia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis C is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

3615it [12:05,  5.21it/s]

false
Determine whether the semantic relation where maltose is the subject, found in taxon is the predicate, and Drosophila melanogaster is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alpha-linolenic acid is the subject, medical condition treated is the predicate, and arthritis is the object constitutes an accurate semantic relation.

3616it [12:05,  5.21it/s]

maybe
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

3617it [12:05,  5.08it/s]

true
Determine whether the semantic relation where Interleukin 5 receptor subunit alpha is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

3618it [12:05,  4.80it/s]

false
Determine whether the semantic relation where arthritis is the subject, drug or therapy used for treatment is the predicate, and alpha-linolenic acid is the object constitutes an accurate semantic relation.

3620it [12:06,  4.76it/s]

maybe
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bromine is the subject, location of discovery is the predicate, and France is the object constitutes an accurate semantic relation.

3622it [12:06,  5.06it/s]

false
Determine whether the semantic relation where typhoid fever is the subject, possible treatment is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3624it [12:06,  5.15it/s]

true
Determine whether the semantic relation where cytochrome P450 family 11 subfamily B member 1 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where West Nile fever is the subject, symptoms and signs is the predicate, and splenomegaly is the object constitutes an accurate semantic relation.

3626it [12:07,  5.18it/s]

false
Determine whether the semantic relation where Adenine phosphoribosyltransferase is the subject, biological process is the predicate, and lactation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where concussion is the subject, drug or therapy used for treatment is the predicate, and paracetamol is the object constitutes an accurate semantic relation.

3627it [12:07,  5.11it/s]

maybe
Determine whether the semantic relation where Aleutian disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3629it [12:07,  4.76it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

3630it [12:08,  4.81it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

3632it [12:08,  4.75it/s]

true
Determine whether the semantic relation where Coagulation factor VIII is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perineum is the subject, different from is the predicate, and fibula is the object constitutes an accurate semantic relation.

3634it [12:08,  5.05it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

3636it [12:09,  5.34it/s]

true
Determine whether the semantic relation where mucilage is the subject, has part(s) is the predicate, and glycoprotein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diethyl ether is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

3638it [12:09,  5.56it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and diethyl ether is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3640it [12:10,  5.39it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CDKN2A is the subject, expressed in is the predicate, and pituitary gland is the object constitutes an accurate semantic relation.

3641it [12:10,  4.67it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

3643it [12:10,  4.69it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intussusception is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

3644it [12:10,  4.78it/s]

false
Determine whether the semantic relation where bromhexine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3646it [12:11,  5.03it/s]

true
Determine whether the semantic relation where CD34 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3648it [12:11,  4.12it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

3650it [12:12,  4.65it/s]

true
Determine whether the semantic relation where syphilis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japanese encephalitis is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

3651it [12:12,  4.76it/s]

maybe
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

3653it [12:12,  4.89it/s]

true
Determine whether the semantic relation where cytosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

3655it [12:13,  5.12it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and Parkinson's disease is the object constitutes an accurate semantic relation.

3656it [12:13,  4.98it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

3658it [12:13,  5.00it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

3660it [12:14,  5.18it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase 2 is the subject, cell component is the predicate, and Y chromosome is the object constitutes an accurate semantic relation.

3662it [12:14,  5.13it/s]

false
Determine whether the semantic relation where Eritrea is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Eritrea is the object constitutes an accurate semantic relation.

3664it [12:15,  5.00it/s]

true
Determine whether the semantic relation where Sierra Leone is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Sierra Leone is the object constitutes an accurate semantic relation.

3666it [12:15,  5.17it/s]

true
Determine whether the semantic relation where inborn metabolic brain disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

3668it [12:15,  5.29it/s]

false
Determine whether the semantic relation where Nucleotide binding oligomerization domain containing 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

3670it [12:16,  5.34it/s]

true
Determine whether the semantic relation where S-nitroso-N-acetyl-D-penicillamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

3671it [12:16,  5.41it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

3673it [12:16,  5.40it/s]

true
Determine whether the semantic relation where glioma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxytocin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3675it [12:17,  5.21it/s]

false
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
false

3676it [12:17,  5.15it/s]

Determine whether the semantic relation where Matrix metallopeptidase 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mouth disease is the subject, subclass of is the predicate, and gastrointestinal system disease is the object constitutes an accurate semantic relation.

3678it [12:17,  5.10it/s]

false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

3680it [12:18,  5.16it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

3681it [12:18,  5.30it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

3683it [12:18,  5.21it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where facioscapulohumeral muscular dystrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3685it [12:19,  5.21it/s]

true
Determine whether the semantic relation where adenosine diphosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aldehyde dehydrogenase 6 family member A1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

3686it [12:19,  5.29it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3688it [12:19,  5.25it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

3690it [12:20,  5.24it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

3692it [12:20,  5.30it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Surfactant protein D is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3693it [12:20,  5.31it/s]

true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3694it [12:20,  5.16it/s]

true
Determine whether the semantic relation where status asthmaticus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3696it [12:21,  5.07it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

3697it [12:21,  5.16it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

3699it [12:21,  5.06it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where research expedition is the subject, subclass of is the predicate, and data collection is the object constitutes an accurate semantic relation.

3700it [12:22,  5.12it/s]

false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3702it [12:22,  5.23it/s]

true
Determine whether the semantic relation where fibrinogen complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

3704it [12:22,  5.30it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis E is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

3706it [12:23,  5.29it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic phase chronic myelogenous leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3708it [12:23,  4.98it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

3710it [12:24,  5.03it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

3711it [12:24,  5.20it/s]

true
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3713it [12:24,  5.17it/s]

true
Determine whether the semantic relation where Martinique is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peptide nucleic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3715it [12:25,  4.57it/s]

false
Determine whether the semantic relation where Galanin and GMAP prepropeptide is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where infant respiratory distress syndrome is the subject, drug or therapy used for treatment is the predicate, and nitric oxide is the object constitutes an accurate semantic relation.

3716it [12:25,  4.79it/s]

true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

3718it [12:25,  4.49it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, ethnic group is the predicate, and Arabs is the object constitutes an accurate semantic relation.

3720it [12:26,  4.89it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

3722it [12:26,  4.97it/s]

true
Determine whether the semantic relation where Castleman's disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where sumatriptan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3723it [12:26,  5.15it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

3725it [12:27,  5.14it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-ofloxacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

3727it [12:27,  5.19it/s]

true
Determine whether the semantic relation where Kallikrein related peptidase 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where balantidiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3729it [12:27,  5.45it/s]

true
Determine whether the semantic relation where N-bromosuccinimide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malondialdehyde is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3731it [12:28,  5.26it/s]

true
Determine whether the semantic relation where polylysine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

3733it [12:28,  5.21it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true

3734it [12:28,  5.25it/s]

Determine whether the semantic relation where aspergilloma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where daunorubicin is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

3736it [12:29,  5.25it/s]

true
Determine whether the semantic relation where animal disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Regenerating family member 1 alpha is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3737it [12:29,  4.72it/s]

false
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3739it [12:30,  4.29it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nikethamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3740it [12:30,  4.39it/s]

false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3742it [12:30,  4.68it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

3744it [12:31,  4.92it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hong Kong is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3746it [12:31,  4.92it/s]

false
Determine whether the semantic relation where Lyme disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Hong Kong is the object constitutes an accurate semantic relation.

3748it [12:31,  5.10it/s]

false
Determine whether the semantic relation where cellular communication network factor 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3749it [12:31,  5.21it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

3751it [12:32,  5.09it/s]

true
Determine whether the semantic relation where epinephrine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vestibular schwannoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3753it [12:32,  4.98it/s]

true
Determine whether the semantic relation where collapse therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Neurofibromin 1 is the subject, biological process is the predicate, and cognition is the object constitutes an accurate semantic relation.

3755it [12:33,  5.10it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where post-concussion syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

3756it [12:33,  5.00it/s]

true
Determine whether the semantic relation where pethidine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

3757it [12:33,  4.87it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase 2 is the subject, cell component is the predicate, and X chromosome is the object constitutes an accurate semantic relation.

3759it [12:34,  4.90it/s]

false
Determine whether the semantic relation where parasitology is the subject, part of is the predicate, and botany is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Matrix metallopeptidase 12 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3761it [12:34,  5.12it/s]

false
Determine whether the semantic relation where osteoradionecrosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

3763it [12:34,  5.20it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hereditary breast ovarian cancer is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

3765it [12:35,  5.31it/s]

true
Determine whether the semantic relation where Borna disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Perilla frutescens is the object constitutes an accurate semantic relation.

3767it [12:35,  5.35it/s]

false
Determine whether the semantic relation where cephalosporin antibiotic is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, cause of death is the predicate, and respiratory failure is the object constitutes an accurate semantic relation.

3769it [12:35,  5.34it/s]

maybe
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and respiratory failure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3771it [12:36,  5.27it/s]

true
Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, symptoms and signs is the predicate, and nasal congestion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malaria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3773it [12:36,  5.28it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

3775it [12:37,  5.36it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

3777it [12:37,  5.17it/s]

true
Determine whether the semantic relation where bisacodyl is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, shares border with is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

3779it [12:37,  5.25it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.

3781it [12:38,  5.11it/s]

true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and procainamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where premature ejaculation is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

3783it [12:38,  5.32it/s]

maybe
Determine whether the semantic relation where premature ejaculation is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

3785it [12:38,  5.23it/s]

true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where procainamide is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

3787it [12:39,  5.24it/s]

true
Determine whether the semantic relation where hypoactive sexual desire disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteochondritis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

3788it [12:39,  4.57it/s]

true
Determine whether the semantic relation where enalapril is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3790it [12:40,  4.72it/s]

false
Determine whether the semantic relation where Nuclear receptor subfamily 3 group C member 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tubal pregnancy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3792it [12:40,  5.04it/s]

true
Determine whether the semantic relation where campylobacteriosis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bacteriuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3793it [12:40,  5.12it/s]

true
Determine whether the semantic relation where gastrointestinal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3795it [12:41,  5.01it/s]

true
Determine whether the semantic relation where pseudoaneurysm is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

3797it [12:41,  5.15it/s]

false
Determine whether the semantic relation where klebsiellosis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fallopia japonica is the subject, invasive to is the predicate, and Canada is the object constitutes an accurate semantic relation.

3799it [12:41,  5.29it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

3800it [12:41,  5.34it/s]

true
Determine whether the semantic relation where Burkitt lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3801it [12:42,  5.19it/s]

true
Determine whether the semantic relation where ribitol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true

3803it [12:42,  5.14it/s]

Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

3805it [12:42,  4.97it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3807it [12:43,  5.11it/s]

true
Determine whether the semantic relation where oxyphilic adenoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plant structure is the subject, different from is the predicate, and animal structure is the object constitutes an accurate semantic relation.

3809it [12:43,  5.11it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where animal structure is the subject, different from is the predicate, and plant structure is the object constitutes an accurate semantic relation.

3811it [12:44,  5.17it/s]

true
Determine whether the semantic relation where complement factor properdin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

3813it [12:44,  5.00it/s]

true
Determine whether the semantic relation where gum arabic is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where haloperidol is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

3815it [12:44,  5.18it/s]

false
Determine whether the semantic relation where Ephrin B1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where LDL receptor related protein 6 is the subject, biological process is the predicate, and chemical synaptic transmission is the object constitutes an accurate semantic relation.

3816it [12:45,  5.27it/s]

false
Determine whether the semantic relation where tobacco use disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

3818it [12:45,  5.04it/s]

true
Determine whether the semantic relation where hyper IgM syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prenatal exposure delayed effects is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3820it [12:45,  5.14it/s]

false
Determine whether the semantic relation where zinc sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paraffin wax is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

3821it [12:46,  5.12it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

3823it [12:46,  5.00it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prenatal injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3825it [12:46,  5.10it/s]

false
Determine whether the semantic relation where forearm injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

3826it [12:47,  5.09it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

3828it [12:47,  4.89it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

3830it [12:47,  5.13it/s]

true
Determine whether the semantic relation where dacarbazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where allergic contact dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3831it [12:48,  5.16it/s]

true
Determine whether the semantic relation where forensic science is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

3833it [12:48,  5.09it/s]

true
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aspirin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

3834it [12:48,  5.08it/s]

false
Determine whether the semantic relation where amino acid metabolic disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

3836it [12:49,  5.06it/s]

maybe
Determine whether the semantic relation where nutrition disorder is the subject, drug or therapy used for treatment is the predicate, and L-tyrosine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-tyrosine is the subject, medical condition treated is the predicate, and nutrition disorder is the object constitutes an accurate semantic relation.

3838it [12:49,  5.10it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

3840it [12:49,  5.14it/s]

true
Determine whether the semantic relation where Natriuretic peptide A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF superfamily member 11 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

3842it [12:50,  5.10it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where genistein is the subject, found in taxon is the predicate, and Pseudomonas is the object constitutes an accurate semantic relation.

3844it [12:50,  5.20it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Africa is the object constitutes an accurate semantic relation.

3845it [12:50,  4.84it/s]

false
Determine whether the semantic relation where congenital hyperinsulinism is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

3846it [12:51,  4.81it/s]

true
Determine whether the semantic relation where War in Afghanistan (2001–2021) is the subject, participant is the predicate, and Australia is the object constitutes an accurate semantic relation.

3848it [12:51,  4.90it/s]

true
Determine whether the semantic relation where heavy water is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, participant in is the predicate, and War in Afghanistan (2001–2021) is the object constitutes an accurate semantic relation.

3849it [12:51,  5.06it/s]

true
Determine whether the semantic relation where pneumoperitoneum is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

3851it [12:52,  4.80it/s]

false
Determine whether the semantic relation where uridine 5'-triphosphoric acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Adenine phosphoribosyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

3853it [12:52,  5.07it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hospital volunteer is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

3854it [12:52,  5.04it/s]

true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 11 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

3856it [12:53,  5.03it/s]

false
Determine whether the semantic relation where Janus kinase 1 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

3857it [12:53,  5.15it/s]

true
Determine whether the semantic relation where Aconitase 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

3858it [12:53,  5.05it/s]

false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3860it [12:53,  5.00it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydrogen is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

3861it [12:54,  4.81it/s]

false
Determine whether the semantic relation where tension headache is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3863it [12:54,  4.63it/s]

true
Determine whether the semantic relation where silver is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

3865it [12:54,  4.97it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Babesiosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

3867it [12:55,  5.02it/s]

true
Determine whether the semantic relation where galantamine is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where radiation sickness is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3869it [12:55,  5.21it/s]

true
Determine whether the semantic relation where tetracycline is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystoisosporiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3871it [12:56,  5.24it/s]

true
Determine whether the semantic relation where urinary system neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 14 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3872it [12:56,  4.91it/s]

true
Determine whether the semantic relation where influenza is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3873it [12:56,  4.77it/s]

true
Determine whether the semantic relation where seminoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3874it [12:56,  4.60it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

3876it [12:57,  4.84it/s]

true
Determine whether the semantic relation where ataxia telangiectasia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cherubism is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

3877it [12:57,  4.96it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

3878it [12:57,  4.95it/s]

true
Determine whether the semantic relation where paragonimiasis is the subject, medical examination is the predicate, and medical ultrasonography is the object constitutes an accurate semantic relation.

3879it [12:57,  4.85it/s]

false
Determine whether the semantic relation where Bahrain is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3880it [12:58,  4.83it/s]

true
Determine whether the semantic relation where maxillofacial injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

3882it [12:58,  4.85it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Bahrain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lesotho is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3883it [12:58,  4.93it/s]

true
Determine whether the semantic relation where Bone morphogenetic protein 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3885it [12:59,  5.04it/s]

false
Determine whether the semantic relation where fetal alcohol spectrum disorders is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where umbilical hernia is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

3886it [12:59,  5.15it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Lesotho is the object constitutes an accurate semantic relation.
true

3888it [12:59,  5.25it/s]

Determine whether the semantic relation where Interleukin 15 receptor subunit alpha is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

3890it [12:59,  5.36it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chorioamnionitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3891it [13:00,  5.35it/s]

true
Determine whether the semantic relation where ehrlichiosis is the subject, disease transmission process is the predicate, and hospital-acquired infection is the object constitutes an accurate semantic relation.

3893it [13:00,  5.08it/s]

false
Determine whether the semantic relation where haloperidol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

3894it [13:00,  5.06it/s]

true
Determine whether the semantic relation where ganciclovir is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

3896it [13:01,  4.89it/s]

false
Determine whether the semantic relation where fluoroquinolone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vimentin is the subject, cell component is the predicate, and peroxisome is the object constitutes an accurate semantic relation.

3897it [13:01,  4.99it/s]

false
Determine whether the semantic relation where folic acid is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

3899it [13:01,  4.90it/s]

true
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.

3901it [13:02,  4.83it/s]

true
Determine whether the semantic relation where pentetrazol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

3903it [13:02,  4.40it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true

3904it [13:02,  4.65it/s]

Determine whether the semantic relation where retinopathy of prematurity is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 10 receptor subunit beta is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

3906it [13:03,  4.97it/s]

true
Determine whether the semantic relation where fasciolosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

3907it [13:03,  5.01it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

3909it [13:03,  4.95it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dihydromorphine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3911it [13:04,  5.16it/s]

true
Determine whether the semantic relation where nephrogenic systemic fibrosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

3912it [13:04,  5.02it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

3914it [13:04,  4.89it/s]

true
Determine whether the semantic relation where canine transmissible venereal tumor is the subject, instance of is the predicate, and sexually transmitted infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vector is the subject, different from is the predicate, and genetic vector is the object constitutes an accurate semantic relation.

3916it [13:05,  5.09it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where yersiniosis is the subject, has natural reservoir is the predicate, and soil is the object constitutes an accurate semantic relation.

3917it [13:05,  5.11it/s]

false
Determine whether the semantic relation where genetic vector is the subject, different from is the predicate, and vector is the object constitutes an accurate semantic relation.

3918it [13:05,  5.04it/s]

false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

3920it [13:06,  4.97it/s]

false
Determine whether the semantic relation where lanolin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (S)-AMPA is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3921it [13:06,  4.92it/s]

true
Determine whether the semantic relation where disease is the subject, handled, mitigated, or managed by is the predicate, and therapy is the object constitutes an accurate semantic relation.

3923it [13:06,  4.87it/s]

true
Determine whether the semantic relation where bromhexine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholecalciferol is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

3925it [13:07,  5.19it/s]

false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

3926it [13:07,  5.25it/s]

true
Determine whether the semantic relation where pica is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

3927it [13:07,  5.09it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

3929it [13:07,  4.98it/s]

true
Determine whether the semantic relation where hydrocodone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

3931it [13:08,  5.09it/s]

true
Determine whether the semantic relation where tooth eruption is the subject, has effect is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ellagic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3933it [13:08,  4.99it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choriogonadotropin subunit beta is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

3935it [13:09,  5.02it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where electron is the subject, interaction is the predicate, and gravity is the object constitutes an accurate semantic relation.

3937it [13:09,  4.71it/s]

false
Determine whether the semantic relation where microscopic polyangiitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

3939it [13:09,  4.85it/s]

true
Determine whether the semantic relation where quinine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (R)-amygdalin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3941it [13:10,  5.04it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

3942it [13:10,  4.94it/s]

true
Determine whether the semantic relation where cataract is the subject, afflicts is the predicate, and fish is the object constitutes an accurate semantic relation.

3944it [13:10,  4.92it/s]

false
Determine whether the semantic relation where 4-hexylresorcinol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

3946it [13:11,  5.01it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where schizoid personality disorder is the subject, has cause is the predicate, and genetics is the object constitutes an accurate semantic relation.

3948it [13:11,  5.10it/s]

true
Determine whether the semantic relation where strychnine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

3949it [13:11,  5.12it/s]

false
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

3951it [13:12,  5.11it/s]

false
Determine whether the semantic relation where C-reactive protein is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

3953it [13:12,  4.89it/s]

false
Determine whether the semantic relation where Nigeria is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and pulmonary fibrosis is the object constitutes an accurate semantic relation.

3954it [13:12,  4.96it/s]

false
Determine whether the semantic relation where penicillin v is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3956it [13:13,  5.11it/s]

false
Determine whether the semantic relation where hypokalemia is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

3957it [13:13,  4.89it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

3959it [13:14,  4.83it/s]

true
Determine whether the semantic relation where insulin receptor is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sn-glycero-3-phosphocholine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

3961it [13:14,  4.99it/s]

false
Determine whether the semantic relation where Melatonin receptor 1B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uridine 5'-triphosphoric acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3962it [13:14,  4.90it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

3964it [13:15,  4.99it/s]

true
Determine whether the semantic relation where C-C motif chemokine receptor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bilateral hearing loss is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

3966it [13:15,  4.94it/s]

false
Determine whether the semantic relation where TNF superfamily member 13b is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leiomyosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3967it [13:15,  4.61it/s]

true
Determine whether the semantic relation where diazepam is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

3969it [13:16,  4.74it/s]

false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

3971it [13:16,  4.92it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

3972it [13:16,  5.09it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

3974it [13:17,  4.98it/s]

false
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, three Ig domains and long cytoplasmic tail 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

3976it [13:17,  5.08it/s]

true
Determine whether the semantic relation where glycogen is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

3977it [13:17,  4.99it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

3979it [13:18,  4.87it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where shoulder impingement syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

3981it [13:18,  4.99it/s]

true
Determine whether the semantic relation where choline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clodronic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

3983it [13:18,  5.19it/s]

true
Determine whether the semantic relation where punishment is the subject, opposite of is the predicate, and award is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3985it [13:19,  5.31it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

3986it [13:19,  5.22it/s]

true
Determine whether the semantic relation where award is the subject, opposite of is the predicate, and punishment is the object constitutes an accurate semantic relation.

3987it [13:19,  4.84it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

3988it [13:19,  4.84it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

3989it [13:20,  4.67it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

3991it [13:20,  4.76it/s]

true
Determine whether the semantic relation where pectin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

3992it [13:20,  4.82it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

3993it [13:20,  4.63it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.

3995it [13:21,  4.93it/s]

false
Determine whether the semantic relation where thioridazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where virulent Newcastle disease is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

3996it [13:21,  4.90it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

3997it [13:21,  4.86it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

3998it [13:22,  4.65it/s]

true
Determine whether the semantic relation where neuroendocrine tumor is the subject, symptoms and signs is the predicate, and back pain is the object constitutes an accurate semantic relation.

4000it [13:22,  4.86it/s]

true
Determine whether the semantic relation where membranous glomerulonephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inducible T cell costimulator is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4002it [13:22,  4.61it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4004it [13:23,  4.91it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adenine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

4006it [13:23,  5.05it/s]

false
Determine whether the semantic relation where bacillary angiomatosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

4008it [13:24,  5.32it/s]

false
Determine whether the semantic relation where accelerometry is the subject, has use is the predicate, and spaceflight is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytidine triphosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4010it [13:24,  5.39it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

4012it [13:24,  5.25it/s]

true
Determine whether the semantic relation where peptic ulcer disease is the subject, drug or therapy used for treatment is the predicate, and glycine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glycine is the subject, medical condition treated is the predicate, and peptic ulcer disease is the object constitutes an accurate semantic relation.

4013it [13:24,  5.29it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

4014it [13:25,  5.02it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4015it [13:25,  4.89it/s]

true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4016it [13:25,  4.69it/s]

true
Determine whether the semantic relation where Rotaviral gastroenteritis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4017it [13:25,  4.60it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

4018it [13:26,  4.66it/s]

true
Determine whether the semantic relation where experimental nervous system autoimmune disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4019it [13:26,  4.57it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

4021it [13:26,  4.80it/s]

true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, cell component is the predicate, and microvillus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4023it [13:27,  5.09it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

4025it [13:27,  5.17it/s]

true
Determine whether the semantic relation where keratoconus is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

4027it [13:27,  5.28it/s]

false
Determine whether the semantic relation where disease outbreak is the subject, has part(s) is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Apiaceae is the object constitutes an accurate semantic relation.

4028it [13:28,  5.22it/s]

false
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4030it [13:28,  5.17it/s]

false
Determine whether the semantic relation where Comoros is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serpin family G member 1 is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

4032it [13:28,  5.33it/s]

false
Determine whether the semantic relation where fosinopril is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Comoros is the object constitutes an accurate semantic relation.

4034it [13:29,  5.22it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4035it [13:29,  5.32it/s]

true
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and voriconazole is the object constitutes an accurate semantic relation.

4036it [13:29,  4.68it/s]

true
Determine whether the semantic relation where hypercholesterolemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

4038it [13:30,  4.81it/s]

false
Determine whether the semantic relation where oral cavity neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where corticotropin releasing hormone is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4040it [13:30,  4.84it/s]

false
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ITGA1:ITGB1 [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

4042it [13:30,  5.05it/s]

true
Determine whether the semantic relation where phthalic anhydride is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastric fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4043it [13:31,  4.89it/s]

true
Determine whether the semantic relation where polydimethylsiloxane is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

4044it [13:31,  4.71it/s]

true
Determine whether the semantic relation where pyrazolone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4046it [13:31,  4.92it/s]

true
Determine whether the semantic relation where phase II clinical trial is the subject, participant is the predicate, and patient is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4048it [13:32,  4.98it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parathyroid hormone is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

4050it [13:32,  5.19it/s]

false
Determine whether the semantic relation where pyelonephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

4052it [13:32,  5.33it/s]

true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4054it [13:33,  5.17it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

4055it [13:33,  4.99it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

4056it [13:33,  4.93it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

4058it [13:34,  4.75it/s]

true
Determine whether the semantic relation where S100 calcium binding protein B is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4060it [13:34,  5.00it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

4061it [13:34,  4.98it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4063it [13:35,  5.05it/s]

true
Determine whether the semantic relation where paracetamol is the subject, significant drug interaction is the predicate, and rifabutin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ubiquitin C is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4064it [13:35,  5.04it/s]

false
Determine whether the semantic relation where glycophorin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4065it [13:35,  4.97it/s]

false
Determine whether the semantic relation where indomethacin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4067it [13:35,  4.82it/s]

true
Determine whether the semantic relation where Anti-Mullerian hormone is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where batra is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4069it [13:36,  5.02it/s]

false
Determine whether the semantic relation where dental pulp disease is the subject, subclass of is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

4071it [13:36,  5.17it/s]

false
Determine whether the semantic relation where Kleine-Levin syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melanoma cell adhesion molecule is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4073it [13:37,  5.16it/s]

false
Determine whether the semantic relation where aneurysmal bone cyst is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lovastatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4074it [13:37,  5.21it/s]

true
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Penicillium is the object constitutes an accurate semantic relation.

4076it [13:37,  5.14it/s]

false
Determine whether the semantic relation where methyl cellulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where megestrol acetate is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

4078it [13:38,  4.98it/s]

true
Determine whether the semantic relation where Luxembourg is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3'-phosphoadenosine 5'-phosphosulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4079it [13:38,  4.56it/s]

true
Determine whether the semantic relation where machine language is the subject, used by is the predicate, and human is the object constitutes an accurate semantic relation.

4080it [13:38,  4.57it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Luxembourg is the object constitutes an accurate semantic relation.

4081it [13:38,  4.65it/s]

true
Determine whether the semantic relation where schistosomiasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

4083it [13:39,  4.44it/s]

true
Determine whether the semantic relation where Neuropeptide Y is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false

4084it [13:39,  4.72it/s]

Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Vanuatu is the object constitutes an accurate semantic relation.

4085it [13:39,  4.89it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4086it [13:39,  4.84it/s]

true
Determine whether the semantic relation where procaine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4087it [13:40,  4.85it/s]

true
Determine whether the semantic relation where Vanuatu is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

4089it [13:40,  4.83it/s]

true
Determine whether the semantic relation where Kuru is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

4090it [13:40,  4.83it/s]

true
Determine whether the semantic relation where Plasmodium vivax malaria is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4092it [13:41,  4.99it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

4094it [13:41,  4.79it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

4095it [13:41,  4.60it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

4097it [13:42,  4.77it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, shares border with is the predicate, and Brazil is the object constitutes an accurate semantic relation.

4098it [13:42,  5.00it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

4100it [13:42,  4.53it/s]

true
Determine whether the semantic relation where Brazil is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

4101it [13:43,  4.60it/s]

true
Determine whether the semantic relation where dicrocoeliasis is the subject, has natural reservoir is the predicate, and dog is the object constitutes an accurate semantic relation.

4102it [13:43,  4.64it/s]

false
Determine whether the semantic relation where trench fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4103it [13:43,  4.48it/s]

true
Determine whether the semantic relation where androgen receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4105it [13:43,  4.89it/s]

false
Determine whether the semantic relation where niacinamide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where IgA glomerulonephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4106it [13:44,  4.90it/s]

true
Determine whether the semantic relation where echinococcosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

4108it [13:44,  4.97it/s]

true
Determine whether the semantic relation where cefotaxime is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sodium benzoate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4110it [13:44,  5.10it/s]

true
Determine whether the semantic relation where neuroschistosomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 3 receptor subunit alpha is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4112it [13:45,  5.10it/s]

false
Determine whether the semantic relation where Sertoli-Leydig cell tumor is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Thromboxane A synthase 1 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

4113it [13:45,  4.88it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4114it [13:45,  4.88it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

4116it [13:46,  4.77it/s]

true
Determine whether the semantic relation where hand disinfection is the subject, contributing factor of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where motion sickness is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4118it [13:46,  5.00it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

4120it [13:46,  5.21it/s]

true
Determine whether the semantic relation where Datura stramonium is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where contracture is the subject, health specialty is the predicate, and traumatology is the object constitutes an accurate semantic relation.

4122it [13:47,  5.07it/s]

false
Determine whether the semantic relation where bullous pemphigoid is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

4124it [13:47,  5.19it/s]

true
Determine whether the semantic relation where genistein is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where syphilis is the subject, drug or therapy used for treatment is the predicate, and clindamycin is the object constitutes an accurate semantic relation.

4125it [13:47,  4.58it/s]

false
Determine whether the semantic relation where spondylolisthesis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

4126it [13:48,  4.67it/s]

false
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

4128it [13:48,  4.46it/s]

true
Determine whether the semantic relation where fluoxetine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where postterm pregnancy is the subject, contributing factor of is the predicate, and malnutrition is the object constitutes an accurate semantic relation.

4129it [13:48,  4.73it/s]

false
Determine whether the semantic relation where prodynorphin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4131it [13:49,  4.97it/s]

false
Determine whether the semantic relation where vascular system injury is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where organ system cancer is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4132it [13:49,  5.08it/s]

true
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4133it [13:49,  5.00it/s]

true
Determine whether the semantic relation where eicosapentaenoic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4135it [13:49,  5.02it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyclosporiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4137it [13:50,  5.07it/s]

true
Determine whether the semantic relation where defensive medicine is the subject, has part(s) of the class is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lymphedema is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

4139it [13:50,  4.91it/s]

false
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where enterobiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4140it [13:50,  5.05it/s]

true
Determine whether the semantic relation where terbutaline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4141it [13:51,  4.72it/s]

false
Determine whether the semantic relation where CD33 molecule is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4143it [13:51,  4.95it/s]

false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where breast fibroadenoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4144it [13:51,  4.77it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

4146it [13:52,  4.98it/s]

true
Determine whether the semantic relation where pica is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pica is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

4148it [13:52,  5.27it/s]

false
Determine whether the semantic relation where kainic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epirubicin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

4150it [13:52,  5.18it/s]

false
Determine whether the semantic relation where methylazoxymethanol acetate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mauritania is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4151it [13:53,  4.73it/s]

true
Determine whether the semantic relation where secretin is the subject, subclass of is the predicate, and recombinant protein is the object constitutes an accurate semantic relation.

4153it [13:53,  4.79it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Mauritania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

4154it [13:53,  4.72it/s]

maybe
Determine whether the semantic relation where intraabdominal infection is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4155it [13:54,  4.76it/s]

true
Determine whether the semantic relation where dexamethasone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4157it [13:54,  4.89it/s]

false
Determine whether the semantic relation where celebrity is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where MET proto-oncogene, receptor tyrosine kinase is the subject, biological process is the predicate, and phagocytosis is the object constitutes an accurate semantic relation.

4159it [13:54,  4.88it/s]

false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4161it [13:55,  5.10it/s]

true
Determine whether the semantic relation where fibroepithelial neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fabry disease is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

4163it [13:55,  5.30it/s]

true
Determine whether the semantic relation where blood glucose is the subject, anatomical location is the predicate, and blood serum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

4165it [13:56,  4.96it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fly ash is the subject, has effect is the predicate, and asthma is the object constitutes an accurate semantic relation.

4166it [13:56,  5.04it/s]

true
Determine whether the semantic relation where mast cell leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4168it [13:56,  5.08it/s]

true
Determine whether the semantic relation where febrile seizure is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where astrocytoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4170it [13:57,  5.09it/s]

true
Determine whether the semantic relation where amyloidosis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where diethyl pyrocarbonate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4172it [13:57,  5.17it/s]

false
Determine whether the semantic relation where Cameroon is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true

4173it [13:57,  5.11it/s]

Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true

4174it [13:57,  5.12it/s]

Determine whether the semantic relation where Down syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acne is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

4176it [13:58,  5.27it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Cameroon is the object constitutes an accurate semantic relation.

4177it [13:58,  5.38it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4179it [13:58,  5.18it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where portrait is the subject, depicts is the predicate, and person is the object constitutes an accurate semantic relation.

4181it [13:59,  5.18it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

4183it [13:59,  5.28it/s]

true
Determine whether the semantic relation where intracranial hypertension is the subject, drug or therapy used for treatment is the predicate, and urea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urea is the subject, medical condition treated is the predicate, and intracranial hypertension is the object constitutes an accurate semantic relation.

4184it [13:59,  5.23it/s]

true
Determine whether the semantic relation where CD2 molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4185it [13:59,  5.09it/s]

true
Determine whether the semantic relation where osteoarticular tuberculosis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

4186it [14:00,  5.03it/s]

maybe
Determine whether the semantic relation where bufotenine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4187it [14:00,  4.84it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, cause of death is the predicate, and pulmonary edema is the object constitutes an accurate semantic relation.

4189it [14:00,  4.90it/s]

maybe
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and pulmonary edema is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

4191it [14:01,  4.94it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3-quinuclidinyl-benzilate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4193it [14:01,  5.04it/s]

true
Determine whether the semantic relation where hyperkalemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where NMR spectroscopy is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

4195it [14:01,  5.26it/s]

false
Determine whether the semantic relation where cytosine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 13 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4197it [14:02,  5.07it/s]

false
Determine whether the semantic relation where creatine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melatonin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4198it [14:02,  4.20it/s]

true
Determine whether the semantic relation where complement factor properdin is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

4200it [14:03,  4.51it/s]

false
Determine whether the semantic relation where amlodipine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where organ culture is the subject, instance of is the predicate, and technology is the object constitutes an accurate semantic relation.

4202it [14:03,  4.71it/s]

true
Determine whether the semantic relation where colorectal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where experimental radiation injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4204it [14:03,  4.94it/s]

true
Determine whether the semantic relation where fms related receptor tyrosine kinase 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4206it [14:04,  5.04it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pregnancy outcome is the subject, studied by is the predicate, and medicine is the object constitutes an accurate semantic relation.

4207it [14:04,  5.10it/s]

true
Determine whether the semantic relation where distomatosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4209it [14:04,  5.15it/s]

true
Determine whether the semantic relation where prednisolone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mosaicism is the subject, subclass of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.

4211it [14:05,  5.16it/s]

true
Determine whether the semantic relation where paper chromatography is the subject, has part(s) is the predicate, and water is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thiamine(1+) diphosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4212it [14:05,  5.22it/s]

true
Determine whether the semantic relation where amylose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4214it [14:05,  5.01it/s]

false
Determine whether the semantic relation where C8 [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hypersensitivity is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4216it [14:06,  5.09it/s]

false
Determine whether the semantic relation where Signal transducer and activator of transcription 4 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4217it [14:06,  5.14it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

4219it [14:06,  5.14it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, shares border with is the predicate, and Brazil is the object constitutes an accurate semantic relation.

4221it [14:07,  5.09it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where accelerometry is the subject, has use is the predicate, and physics is the object constitutes an accurate semantic relation.

4223it [14:07,  5.09it/s]

false
Determine whether the semantic relation where dysthymic disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ulcerative colitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4224it [14:07,  5.15it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

4226it [14:08,  5.09it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

4228it [14:08,  5.14it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

4229it [14:08,  4.88it/s]

true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

4230it [14:09,  4.72it/s]

true
Determine whether the semantic relation where erectile dysfunction is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

4232it [14:09,  4.89it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where albuminuria is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

4234it [14:09,  5.15it/s]

false
Determine whether the semantic relation where T-cell leukemia is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intraductal papilloma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4236it [14:10,  5.01it/s]

true
Determine whether the semantic relation where twin-to-twin transfusion syndrome is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tinea capitis vale is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4238it [14:10,  5.05it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

4240it [14:11,  5.00it/s]

true
Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD80 molecule is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4242it [14:11,  5.08it/s]

false
Determine whether the semantic relation where pityriasis versicolor is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4243it [14:11,  4.22it/s]

true
Determine whether the semantic relation where parasitic pneumonia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4245it [14:12,  4.51it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4247it [14:12,  4.82it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

4248it [14:12,  4.98it/s]

true
Determine whether the semantic relation where pituitary neoplasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4250it [14:13,  4.72it/s]

false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acquired foot deformity is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

4252it [14:13,  5.09it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

4254it [14:13,  5.03it/s]

true
Determine whether the semantic relation where Lemierre's syndrome is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and syndactyly is the object constitutes an accurate semantic relation.

4255it [14:14,  5.09it/s]

false
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and England is the object constitutes an accurate semantic relation.

4257it [14:14,  4.37it/s]

true
Determine whether the semantic relation where bumetanide is the subject, medical condition treated is the predicate, and liver disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where liver disease is the subject, drug or therapy used for treatment is the predicate, and bumetanide is the object constitutes an accurate semantic relation.

4258it [14:14,  4.64it/s]

false
Determine whether the semantic relation where attention deficit hyperactivity disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4260it [14:15,  4.56it/s]

true
Determine whether the semantic relation where ursodiol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where drug reaction with eosinophilia and systemic symptoms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4261it [14:15,  4.81it/s]

true
Determine whether the semantic relation where fusariosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4263it [14:15,  4.93it/s]

true
Determine whether the semantic relation where hypoxia is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anal fistula is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

4264it [14:16,  5.04it/s]

true
Determine whether the semantic relation where United Nations is the subject, headquarters location is the predicate, and New York City is the object constitutes an accurate semantic relation.

4265it [14:16,  4.77it/s]

true
Determine whether the semantic relation where neuroleptic malignant syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4266it [14:16,  4.81it/s]

false
Determine whether the semantic relation where berberine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4268it [14:16,  4.93it/s]

true
Determine whether the semantic relation where UDP-glucose 6-dehydrogenase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbonic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

4270it [14:17,  5.23it/s]

false
Determine whether the semantic relation where nose neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where atypical chronic myeloid leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4272it [14:17,  5.20it/s]

true
Determine whether the semantic relation where tracheitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dihydroalprenolol is the subject, subject has role is the predicate, and antihypertensive drug is the object constitutes an accurate semantic relation.

4273it [14:18,  4.25it/s]

true
Determine whether the semantic relation where voice disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4275it [14:18,  4.57it/s]

false
Determine whether the semantic relation where colonic neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tongue neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4277it [14:18,  4.91it/s]

true
Determine whether the semantic relation where polychlorinated biphenyl is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parasitic helminthiasis infectious disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4278it [14:19,  4.82it/s]

true
Determine whether the semantic relation where periapical disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4279it [14:19,  4.54it/s]

true
Determine whether the semantic relation where inositol is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

4280it [14:19,  4.56it/s]

false
Determine whether the semantic relation where heat illness is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4281it [14:19,  4.49it/s]

true
Determine whether the semantic relation where retrograde degeneration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4283it [14:20,  4.74it/s]

true
Determine whether the semantic relation where duodenal neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where piracetam is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4285it [14:20,  4.89it/s]

false
Determine whether the semantic relation where hydroxysteroid 11-beta dehydrogenase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false

4286it [14:20,  5.07it/s]

Determine whether the semantic relation where ethylmorphine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MPTP is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4288it [14:21,  5.03it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4290it [14:21,  5.00it/s]

true
Determine whether the semantic relation where anaplastic large-cell lymphoma is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hookworm disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4291it [14:21,  4.74it/s]

true
Determine whether the semantic relation where stable angina is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4293it [14:22,  4.91it/s]

true
Determine whether the semantic relation where rhabdomyosarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myelencephalon is the subject, instance of is the predicate, and embryonic structure is the object constitutes an accurate semantic relation.

4295it [14:22,  5.01it/s]

true
Determine whether the semantic relation where oral tuberculosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sirolimus is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

4296it [14:22,  4.99it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Suriname is the object constitutes an accurate semantic relation.

4298it [14:23,  5.05it/s]

false
Determine whether the semantic relation where Suriname is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adrenomedullin is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

4300it [14:23,  5.27it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and The Gambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where The Gambia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4302it [14:23,  5.12it/s]

true
Determine whether the semantic relation where Japan is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chemotherapy-induced acral erythema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4304it [14:24,  5.24it/s]

true
Determine whether the semantic relation where Extravasation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major histocompatibility complex, class I, A is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4306it [14:24,  5.14it/s]

true
Determine whether the semantic relation where guanosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where spina bifida occulta is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4308it [14:25,  5.15it/s]

true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

4310it [14:25,  5.15it/s]

true
Determine whether the semantic relation where cyanocobalamin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

4312it [14:25,  5.30it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

4314it [14:26,  5.36it/s]

true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Valeriana officinalis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where AT-rich interaction domain 4A is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

4316it [14:26,  5.26it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4318it [14:26,  5.37it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

4320it [14:27,  5.33it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and ammonium chloride is the object constitutes an accurate semantic relation.

4322it [14:27,  5.36it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clonorchiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4324it [14:28,  5.26it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 13b is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4325it [14:28,  5.29it/s]

true
Determine whether the semantic relation where vasculitis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

4327it [14:28,  4.46it/s]

false
Determine whether the semantic relation where tic disorder is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where congenital toxoplasmosis is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

4328it [14:29,  4.39it/s]

true
Determine whether the semantic relation where ear disease is the subject, drug or therapy used for treatment is the predicate, and acetic acid is the object constitutes an accurate semantic relation.

4329it [14:29,  4.47it/s]

true
Determine whether the semantic relation where acetic acid is the subject, medical condition treated is the predicate, and ear disease is the object constitutes an accurate semantic relation.

4331it [14:29,  4.80it/s]

false
Determine whether the semantic relation where perphenazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

4333it [14:30,  4.97it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true

4334it [14:30,  5.06it/s]

Determine whether the semantic relation where 2,3-diphosphoglyceric acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

4335it [14:30,  5.22it/s]

true
Determine whether the semantic relation where Mus is the subject, main food source is the predicate, and insect is the object constitutes an accurate semantic relation.

4337it [14:30,  5.08it/s]

maybe
Determine whether the semantic relation where apolipoprotein C is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lynch syndrome II is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4339it [14:31,  5.10it/s]

true
Determine whether the semantic relation where intestinal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4341it [14:31,  5.28it/s]

true
Determine whether the semantic relation where FOS is the subject, expressed in is the predicate, and trachea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fabry disease is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

4342it [14:31,  4.83it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4343it [14:32,  4.85it/s]

true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

4345it [14:32,  4.80it/s]

false
Determine whether the semantic relation where head and neck neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choristoma is the subject, health specialty is the predicate, and pathology is the object constitutes an accurate semantic relation.

4346it [14:32,  4.92it/s]

false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4347it [14:32,  4.75it/s]

true
Determine whether the semantic relation where alpha fetoprotein is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

4349it [14:33,  4.82it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salicylic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

4351it [14:33,  4.72it/s]

false
Determine whether the semantic relation where bipolar disorder is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

4353it [14:34,  5.11it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4355it [14:34,  5.22it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where high-risk pregnancy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4357it [14:34,  5.31it/s]

false
Determine whether the semantic relation where vascular calcification is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ventricular fibrillation is the subject, symptoms and signs is the predicate, and vertigo is the object constitutes an accurate semantic relation.

4359it [14:35,  5.38it/s]

false
Determine whether the semantic relation where acute erythroid leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alcoholism is the subject, afflicts is the predicate, and child is the object constitutes an accurate semantic relation.

4361it [14:35,  5.30it/s]

false
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic renal insufficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4362it [14:35,  4.65it/s]

true
Determine whether the semantic relation where intussusception is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

4364it [14:36,  4.07it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4366it [14:36,  4.30it/s]

true
Determine whether the semantic relation where appendiceal neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4368it [14:37,  4.70it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and premenstrual syndrome is the object constitutes an accurate semantic relation.

4370it [14:37,  4.97it/s]

true
Determine whether the semantic relation where premenstrual syndrome is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Creutzfeldt-Jakob disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4371it [14:37,  4.90it/s]

true
Determine whether the semantic relation where factor IXa [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

4373it [14:38,  5.01it/s]

false
Determine whether the semantic relation where rhinophyma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

4375it [14:38,  5.22it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ampicillin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4376it [14:38,  5.15it/s]

false
Determine whether the semantic relation where dracunculiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

4378it [14:39,  5.05it/s]

true
Determine whether the semantic relation where trifluoperazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

4380it [14:39,  4.95it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where experimental autoimmune encephalomyelitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4382it [14:40,  5.17it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

4384it [14:40,  5.19it/s]

true
Determine whether the semantic relation where Q20986771 is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hemoperitoneum is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

4386it [14:40,  5.26it/s]

false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S-nitroso-N-acetyl-D-penicillamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4387it [14:41,  5.15it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

4389it [14:41,  5.05it/s]

true
Determine whether the semantic relation where batra is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fibroblast growth factor 10 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4391it [14:41,  5.17it/s]

false
Determine whether the semantic relation where Saint Vincent and the Grenadines is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colony stimulating factor 3 receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4393it [14:42,  5.17it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Saint Vincent and the Grenadines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rheumatic heart disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

4394it [14:42,  5.31it/s]

true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and deafness is the object constitutes an accurate semantic relation.

4395it [14:42,  5.18it/s]

false
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4397it [14:42,  5.27it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amoxicillin is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.

4399it [14:43,  5.27it/s]

false
Determine whether the semantic relation where cisplatin is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where yaws is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4401it [14:43,  5.15it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tiger is the subject, main food source is the predicate, and fish is the object constitutes an accurate semantic relation.

4402it [14:43,  5.18it/s]

false
Determine whether the semantic relation where periodic limb movement disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4403it [14:44,  4.94it/s]

true
Determine whether the semantic relation where periodic limb movement disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4405it [14:44,  4.88it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Creutzfeldt-Jakob disease is the subject, possible treatment is the predicate, and palliative care is the object constitutes an accurate semantic relation.

4407it [14:44,  5.10it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myristic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4409it [14:45,  5.08it/s]

true
Determine whether the semantic relation where Cefotetan is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dengue hemorrhagic fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4411it [14:45,  5.13it/s]

true
Determine whether the semantic relation where yaws is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4413it [14:46,  5.05it/s]

false
Determine whether the semantic relation where byssinosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

4415it [14:46,  5.02it/s]

false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pulmonary alveolar proteinosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4417it [14:46,  5.21it/s]

true
Determine whether the semantic relation where paroxetine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

4418it [14:47,  5.24it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4420it [14:47,  4.96it/s]

false
Determine whether the semantic relation where anorexia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

4421it [14:47,  4.89it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4422it [14:48,  4.85it/s]

true
Determine whether the semantic relation where anxiety is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

4424it [14:48,  4.94it/s]

true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ketosis is the subject, instance of is the predicate, and physiology is the object constitutes an accurate semantic relation.

4426it [14:48,  4.96it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

4428it [14:49,  5.17it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4430it [14:49,  5.04it/s]

false
Determine whether the semantic relation where oxalic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blood group incompatibility is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4432it [14:49,  5.10it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

4434it [14:50,  4.96it/s]

true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chitosan is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

4435it [14:50,  4.93it/s]

false
Determine whether the semantic relation where depressed skull fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4436it [14:50,  4.74it/s]

false
Determine whether the semantic relation where mercaptopurine is the subject, medical condition treated is the predicate, and chronic lymphocytic leukemia is the object constitutes an accurate semantic relation.

4438it [14:51,  4.67it/s]

false
Determine whether the semantic relation where chronic lymphocytic leukemia is the subject, drug or therapy used for treatment is the predicate, and mercaptopurine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where female breast is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.

4440it [14:51,  4.82it/s]

true
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

4442it [14:52,  5.14it/s]

true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily A member 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where common cold is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4444it [14:52,  4.88it/s]

true
Determine whether the semantic relation where nasopharyngeal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

4446it [14:52,  4.74it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where saponin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4448it [14:53,  5.00it/s]

false
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trichinosis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

4449it [14:53,  5.19it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

4451it [14:53,  4.85it/s]

true
Determine whether the semantic relation where disease susceptibility is the subject, has cause is the predicate, and socioeconomic status is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, anatomical location is the predicate, and blood vessel is the object constitutes an accurate semantic relation.

4452it [14:54,  5.07it/s]

false
Determine whether the semantic relation where complement C3 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

4453it [14:54,  5.00it/s]

maybe
Determine whether the semantic relation where FOS is the subject, expressed in is the predicate, and tibial nerve is the object constitutes an accurate semantic relation.

4455it [14:54,  4.72it/s]

false
Determine whether the semantic relation where tularemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystoisosporiasis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

4457it [14:55,  5.02it/s]

false
Determine whether the semantic relation where adrenomedullin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

4459it [14:55,  4.93it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 37 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4460it [14:55,  5.00it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4462it [14:56,  5.00it/s]

true
Determine whether the semantic relation where patent ductus arteriosus is the subject, drug or therapy used for treatment is the predicate, and L-lysine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where death is the subject, facet of is the predicate, and development of the human body is the object constitutes an accurate semantic relation.

4464it [14:56,  4.98it/s]

false
Determine whether the semantic relation where L-lysine is the subject, medical condition treated is the predicate, and patent ductus arteriosus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nursing diagnosis is the subject, subclass of is the predicate, and diagnosis is the object constitutes an accurate semantic relation.

4465it [14:56,  4.98it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

4467it [14:57,  5.07it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4469it [14:57,  5.19it/s]

true
Determine whether the semantic relation where RRR-alpha-tocopherol is the subject, medical condition treated is the predicate, and hemolytic anemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nephrosis is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

4470it [14:57,  5.26it/s]

false
Determine whether the semantic relation where drug resistance is the subject, subclass of is the predicate, and adverse drug reaction is the object constitutes an accurate semantic relation.

4472it [14:58,  5.24it/s]

false
Determine whether the semantic relation where hemolytic anemia is the subject, drug or therapy used for treatment is the predicate, and RRR-alpha-tocopherol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

4473it [14:58,  5.14it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.

4475it [14:58,  5.15it/s]

false
Determine whether the semantic relation where dengue fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

4477it [14:59,  5.10it/s]

true
Determine whether the semantic relation where clinical decision support system is the subject, field of work is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

4478it [14:59,  4.80it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4479it [14:59,  4.62it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

4481it [15:00,  4.59it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

4483it [15:00,  5.03it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where osteoblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4484it [15:00,  5.06it/s]

true
Determine whether the semantic relation where naphazoline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4486it [15:01,  5.05it/s]

true
Determine whether the semantic relation where Interleukin 12B is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leg dermatosis is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

4488it [15:01,  5.20it/s]

maybe
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and leg dermatosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cocaine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

4490it [15:01,  4.99it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and cocaine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where S-adenosyl-L-homocysteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4492it [15:02,  4.65it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon dioxide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

4494it [15:02,  5.01it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Leigh disease is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

4496it [15:03,  5.06it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sezary's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4497it [15:03,  5.15it/s]

true
Determine whether the semantic relation where magnet is the subject, different from is the predicate, and magnesium is the object constitutes an accurate semantic relation.

4498it [15:03,  4.98it/s]

true
Determine whether the semantic relation where nitrofurantoin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

4500it [15:03,  4.83it/s]

false
Determine whether the semantic relation where keratin 20 is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

4501it [15:04,  4.94it/s]

true
Determine whether the semantic relation where ribonuclease T1 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4502it [15:04,  4.85it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

4503it [15:04,  4.73it/s]

true
Determine whether the semantic relation where cocaine is the subject, medical condition treated is the predicate, and cough is the object constitutes an accurate semantic relation.

4504it [15:04,  4.76it/s]

false
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

4506it [15:05,  4.69it/s]

true
Determine whether the semantic relation where cholecystokinin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cough is the subject, drug or therapy used for treatment is the predicate, and cocaine is the object constitutes an accurate semantic relation.

4508it [15:05,  4.81it/s]

false
Determine whether the semantic relation where tacrolimus is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4510it [15:06,  4.32it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cysticercosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4511it [15:06,  4.62it/s]

true
Determine whether the semantic relation where (−)-sparteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4513it [15:06,  4.78it/s]

true
Determine whether the semantic relation where pulmonary injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium lauryl sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4514it [15:06,  5.02it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4515it [15:07,  4.96it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

4517it [15:07,  4.97it/s]

true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and scalp dermatosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4519it [15:07,  5.06it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where moya moya disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4520it [15:08,  5.15it/s]

true
Determine whether the semantic relation where scalp dermatosis is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

4522it [15:08,  5.12it/s]

true
Determine whether the semantic relation where hepatorenal syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenoxybenzamine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

4523it [15:08,  5.08it/s]

false
Determine whether the semantic relation where coagulation factor V is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4525it [15:09,  4.99it/s]

true
Determine whether the semantic relation where inflammatory bowel diseases is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammatory bowel diseases is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4527it [15:09,  5.01it/s]

true
Determine whether the semantic relation where hydrocodone is the subject, medical condition treated is the predicate, and obstructive lung disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.

4528it [15:09,  5.08it/s]

true
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4529it [15:09,  5.00it/s]

true
Determine whether the semantic relation where hepatitis is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.

4530it [15:10,  4.51it/s]

true
Determine whether the semantic relation where inhibin complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

4532it [15:10,  4.74it/s]

false
Determine whether the semantic relation where obstructive lung disease is the subject, drug or therapy used for treatment is the predicate, and hydrocodone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (EZ)-aconitic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4534it [15:10,  5.01it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vesicular exanthema of swine is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4536it [15:11,  5.19it/s]

true
Determine whether the semantic relation where hypochlorous acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New England is the subject, named after is the predicate, and England is the object constitutes an accurate semantic relation.

4538it [15:11,  5.29it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

4540it [15:12,  5.23it/s]

false
Determine whether the semantic relation where female reproductive system disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptococcosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4542it [15:12,  5.21it/s]

true
Determine whether the semantic relation where Serpin family E member 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where latamoxef is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

4544it [15:12,  5.28it/s]

false
Determine whether the semantic relation where reperfusion injury is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tamoxifen is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

4545it [15:13,  5.28it/s]

false
Determine whether the semantic relation where myocardial infarction is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

4546it [15:13,  4.93it/s]

true
Determine whether the semantic relation where Cyclin D2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

4548it [15:13,  4.94it/s]

false
Determine whether the semantic relation where saponin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nucleotide binding oligomerization domain containing 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4550it [15:14,  5.24it/s]

false
Determine whether the semantic relation where gibberellins is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metildigoxin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

4551it [15:14,  4.95it/s]

false
Determine whether the semantic relation where stuttering is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4553it [15:14,  4.66it/s]

true
Determine whether the semantic relation where El Salvador is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and El Salvador is the object constitutes an accurate semantic relation.

4554it [15:14,  4.83it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

4556it [15:15,  4.97it/s]

true
Determine whether the semantic relation where major histocompatibility complex, class I, B is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4558it [15:15,  5.22it/s]

true
Determine whether the semantic relation where hemophilia A is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

4560it [15:16,  5.26it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4562it [15:16,  5.35it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanosine triphosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4563it [15:16,  5.34it/s]

true
Determine whether the semantic relation where SMAD family member 7 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

4564it [15:16,  5.17it/s]

false
Determine whether the semantic relation where renal artery obstruction is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

4566it [15:17,  5.08it/s]

false
Determine whether the semantic relation where acute myeloid leukemia is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

4568it [15:17,  5.20it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mauritius is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mauritius is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4570it [15:18,  4.84it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.
true

4571it [15:18,  4.95it/s]

Determine whether the semantic relation where chlormerodrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

4573it [15:18,  5.07it/s]

true
Determine whether the semantic relation where TP53 is the subject, expressed in is the predicate, and smooth muscle tissue is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where relapsing fever borreliosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4575it [15:18,  5.22it/s]

true
Determine whether the semantic relation where cellular communication network factor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and 5-methoxytryptamine is the object constitutes an accurate semantic relation.

4576it [15:19,  5.07it/s]

false
Determine whether the semantic relation where hand washing is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.

4578it [15:19,  4.95it/s]

true
Determine whether the semantic relation where hand washing is the subject, contributing factor of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dissociative identity disorder is the subject, possible treatment is the predicate, and counseling is the object constitutes an accurate semantic relation.

4580it [15:19,  5.14it/s]

true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where extremities is the subject, part of is the predicate, and anatomy is the object constitutes an accurate semantic relation.

4581it [15:20,  5.14it/s]

true
Determine whether the semantic relation where lethal midline granuloma is the subject, subclass of is the predicate, and nervous system neoplasm is the object constitutes an accurate semantic relation.

4582it [15:20,  4.93it/s]

false
Determine whether the semantic relation where hypereosinophilic syndrome is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

4584it [15:20,  4.94it/s]

true
Determine whether the semantic relation where hepatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4586it [15:21,  5.08it/s]

false
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where orbital cellulitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4587it [15:21,  5.20it/s]

true
Determine whether the semantic relation where corneal transplantation is the subject, subclass of is the predicate, and organ transplantation is the object constitutes an accurate semantic relation.
true

4589it [15:21,  5.20it/s]

Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypertrophic cardiomyopathy is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

4590it [15:21,  5.25it/s]

true
Determine whether the semantic relation where D-mannopyranose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4591it [15:22,  5.15it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

4592it [15:22,  4.73it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

4593it [15:22,  4.69it/s]

true
Determine whether the semantic relation where renovascular hypertension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

4595it [15:23,  4.79it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

4597it [15:23,  4.96it/s]

false
Determine whether the semantic relation where heparin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where O-phospho-L-serine is the subject, found in taxon is the predicate, and Streptococcus pneumoniae is the object constitutes an accurate semantic relation.

4599it [15:23,  5.04it/s]

false
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bursitis is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.

4601it [15:24,  5.27it/s]

true
Determine whether the semantic relation where meat is the subject, natural product of taxon is the predicate, and Amphibia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thromboxane B2 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4602it [15:24,  5.32it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

4604it [15:24,  5.10it/s]

true
Determine whether the semantic relation where guanosine monophosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

4605it [15:24,  5.15it/s]

maybe
Determine whether the semantic relation where contact dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4606it [15:25,  5.02it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

4608it [15:25,  5.07it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lead poisoning is the subject, route of administration is the predicate, and Q10268830 is the object constitutes an accurate semantic relation.

4609it [15:25,  4.82it/s]

false
Determine whether the semantic relation where diphenhydramine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4610it [15:26,  4.67it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

4611it [15:26,  4.68it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4612it [15:26,  4.47it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4613it [15:26,  4.24it/s]

true
Determine whether the semantic relation where metabolic skin disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

4614it [15:26,  4.29it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

4616it [15:27,  4.61it/s]

true
Determine whether the semantic relation where chilblains is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4617it [15:27,  4.82it/s]

true
Determine whether the semantic relation where spinal stenosis is the subject, has cause is the predicate, and rheumatoid arthritis is the object constitutes an accurate semantic relation.

4619it [15:28,  4.75it/s]

maybe
Determine whether the semantic relation where olfaction disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coagulation factor V is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

4621it [15:28,  5.03it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

4623it [15:28,  5.13it/s]

false
Determine whether the semantic relation where histiocytoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycogen storage disease II is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4624it [15:28,  5.07it/s]

true
Determine whether the semantic relation where paranasal sinus disease is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

4625it [15:29,  4.74it/s]

false
Determine whether the semantic relation where vasoactive intestinal peptide is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4626it [15:29,  4.80it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

4628it [15:29,  4.83it/s]

true
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and rhinitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

4630it [15:30,  4.96it/s]

true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

4631it [15:30,  3.84it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

4632it [15:30,  4.04it/s]

true
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

4633it [15:31,  4.19it/s]

false
Determine whether the semantic relation where Interleukin 4 receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4634it [15:31,  4.16it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

4636it [15:31,  4.50it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tungiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4638it [15:32,  4.90it/s]

true
Determine whether the semantic relation where chronic hepatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

4640it [15:32,  5.07it/s]

false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4642it [15:32,  5.29it/s]

true
Determine whether the semantic relation where CCAAT enhancer binding protein beta is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxypurinol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4643it [15:33,  5.04it/s]

true
Determine whether the semantic relation where cytidine is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.

4645it [15:33,  5.07it/s]

false
Determine whether the semantic relation where homovanillic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where influenza is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4647it [15:33,  5.21it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastroschisis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4649it [15:34,  5.25it/s]

true
Determine whether the semantic relation where integrin subunit alpha 5 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where immunoadsorption is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

4650it [15:34,  5.22it/s]

true
Determine whether the semantic relation where tocopherol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4651it [15:34,  5.05it/s]

true
Determine whether the semantic relation where Galanin and GMAP prepropeptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4652it [15:34,  4.71it/s]

false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4654it [15:35,  4.91it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

4655it [15:35,  4.87it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4657it [15:35,  4.97it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where linoleic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

4659it [15:36,  4.93it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4660it [15:36,  4.93it/s]

true
Determine whether the semantic relation where altretamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4661it [15:36,  4.54it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Mauritius is the object constitutes an accurate semantic relation.

4663it [15:37,  4.52it/s]

true
Determine whether the semantic relation where Mauritius is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit alpha V is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

4664it [15:37,  4.76it/s]

false
Determine whether the semantic relation where Caspase 3 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

4666it [15:37,  4.90it/s]

false
Determine whether the semantic relation where eye injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4667it [15:37,  5.08it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4668it [15:38,  5.02it/s]

true
Determine whether the semantic relation where muscular dystrophy is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

4670it [15:38,  5.04it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Guadeloupe is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

4671it [15:38,  5.15it/s]

true
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

4673it [15:39,  5.14it/s]

true
Determine whether the semantic relation where doxorubicin is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dyssomnia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

4675it [15:39,  5.05it/s]

false
Determine whether the semantic relation where dyssomnia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and thiostrepton is the object constitutes an accurate semantic relation.

4677it [15:39,  5.13it/s]

false
Determine whether the semantic relation where docosahexaenoic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiostrepton is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.

4679it [15:40,  5.15it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 4 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tropomyosin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4681it [15:40,  5.06it/s]

false
Determine whether the semantic relation where hepatitis A is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prolactinoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

4683it [15:41,  5.07it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Datura stramonium is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fabry disease is the subject, symptoms and signs is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

4685it [15:41,  5.17it/s]

true
Determine whether the semantic relation where zidovudine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4687it [15:41,  5.16it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true

4688it [15:42,  5.29it/s]

Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-X-C motif chemokine receptor 4 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4689it [15:42,  5.11it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

4691it [15:42,  4.96it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amyloid P component, serum is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4693it [15:43,  5.05it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where triflupromazine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

4694it [15:43,  4.99it/s]

false
Determine whether the semantic relation where CD40 ligand is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4696it [15:43,  4.86it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and triflupromazine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where antithrombin III deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4698it [15:44,  5.05it/s]

true
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

4700it [15:44,  5.06it/s]

false
Determine whether the semantic relation where vascular myelopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.

4701it [15:44,  5.08it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false

4702it [15:44,  5.05it/s]

Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

4703it [15:45,  4.85it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

4705it [15:45,  4.83it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

4707it [15:45,  5.13it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leprosy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4709it [15:46,  4.76it/s]

true
Determine whether the semantic relation where calcium sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tick-borne encephalitis is the subject, symptoms and signs is the predicate, and coma is the object constitutes an accurate semantic relation.

4710it [15:46,  4.85it/s]

true
Determine whether the semantic relation where protein tyrosine phosphatase non-receptor type 6 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4712it [15:47,  4.90it/s]

false
Determine whether the semantic relation where folate deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4714it [15:47,  5.07it/s]

true
Determine whether the semantic relation where dissociative identity disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

4715it [15:47,  5.08it/s]

true
Determine whether the semantic relation where hypothalamic neoplasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4717it [15:48,  4.35it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

4719it [15:48,  4.73it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aortic rupture is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

4720it [15:48,  4.82it/s]

false
Determine whether the semantic relation where phospholipase D is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4721it [15:48,  4.68it/s]

false
Determine whether the semantic relation where erysipelas is the subject, possible treatment is the predicate, and histamine antagonist is the object constitutes an accurate semantic relation.

4723it [15:49,  4.83it/s]

false
Determine whether the semantic relation where Solute carrier family 12, member 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Beta vulgaris is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4725it [15:49,  4.99it/s]

true
Determine whether the semantic relation where vitamin B12 deficiency is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4727it [15:50,  5.09it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where enoxaparin sodium is the subject, subclass of is the predicate, and polymer is the object constitutes an accurate semantic relation.

4728it [15:50,  4.88it/s]

false
Determine whether the semantic relation where lignan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4730it [15:50,  4.96it/s]

true
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ulnar neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4732it [15:51,  5.09it/s]

true
Determine whether the semantic relation where uterine disease is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

4733it [15:51,  5.07it/s]

false
Determine whether the semantic relation where bone fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4734it [15:51,  4.84it/s]

false
Determine whether the semantic relation where fetal alcohol spectrum disorders is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4736it [15:52,  4.78it/s]

true
Determine whether the semantic relation where Daucus carota is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and bradycardia is the object constitutes an accurate semantic relation.

4738it [15:52,  5.14it/s]

false
Determine whether the semantic relation where LDL receptor related protein 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4740it [15:52,  5.11it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and saliva secretion is the object constitutes an accurate semantic relation.

4742it [15:53,  5.07it/s]

false
Determine whether the semantic relation where calcium hydroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipoprotein is the subject, subclass of is the predicate, and nanoparticle is the object constitutes an accurate semantic relation.

4743it [15:53,  5.11it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

4745it [15:53,  5.20it/s]

true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycoside is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4747it [15:54,  5.11it/s]

true
Determine whether the semantic relation where transposition of great vessels is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

4748it [15:54,  5.02it/s]

false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4750it [15:54,  4.99it/s]

true
Determine whether the semantic relation where psilocybin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.

4751it [15:54,  4.97it/s]

true
Determine whether the semantic relation where astigmatism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4753it [15:55,  4.92it/s]

true
Determine whether the semantic relation where astigmatism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and cisapride is the object constitutes an accurate semantic relation.

4755it [15:55,  5.11it/s]

true
Determine whether the semantic relation where cisapride is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4756it [15:55,  5.15it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

4757it [15:56,  4.91it/s]

true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

4759it [15:56,  4.93it/s]

false
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

4761it [15:56,  5.04it/s]

false
Determine whether the semantic relation where osteonecrosis of the femoral head is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and ketanserin is the object constitutes an accurate semantic relation.

4763it [15:57,  5.03it/s]

maybe
Determine whether the semantic relation where midwifery is the subject, country is the predicate, and Colombia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cyclin dependent kinase 1 is the subject, biological process is the predicate, and viral entry into host cell is the object constitutes an accurate semantic relation.

4764it [15:57,  4.97it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 3 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4765it [15:57,  4.79it/s]

false
Determine whether the semantic relation where micronutrient is the subject, subclass of is the predicate, and growth substances is the object constitutes an accurate semantic relation.

4767it [15:58,  4.87it/s]

false
Determine whether the semantic relation where benzydamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

4768it [15:58,  4.96it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

4770it [15:58,  4.83it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where birth is the subject, part of is the predicate, and life is the object constitutes an accurate semantic relation.

4771it [15:59,  4.80it/s]

true
Determine whether the semantic relation where cytidine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

4772it [15:59,  4.80it/s]

false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

4773it [15:59,  4.82it/s]

true
Determine whether the semantic relation where parathyroid hormone is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4774it [15:59,  4.73it/s]

false
Determine whether the semantic relation where 5-HTP is the subject, medical condition treated is the predicate, and major depressive disorder is the object constitutes an accurate semantic relation.

4776it [16:00,  4.90it/s]

maybe
Determine whether the semantic relation where major depressive disorder is the subject, drug or therapy used for treatment is the predicate, and 5-HTP is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where methyl green is the subject, subject has role is the predicate, and contrast agent is the object constitutes an accurate semantic relation.

4778it [16:00,  5.06it/s]

false
Determine whether the semantic relation where post-traumatic stress disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rac-salbutamol is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

4779it [16:00,  5.18it/s]

false
Determine whether the semantic relation where congenital toxoplasmosis is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

4781it [16:01,  5.06it/s]

false
Determine whether the semantic relation where Histamine receptor H1 is the subject, physically interacts with is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorpromazine is the subject, physically interacts with is the predicate, and Histamine receptor H1 is the object constitutes an accurate semantic relation.

4783it [16:01,  5.18it/s]

true
Determine whether the semantic relation where lauryl alcohol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

4784it [16:01,  4.97it/s]

true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and rac-salbutamol is the object constitutes an accurate semantic relation.

4785it [16:01,  4.84it/s]

false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

4786it [16:02,  4.76it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

4788it [16:02,  4.89it/s]

true
Determine whether the semantic relation where SMAD family member 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

4790it [16:02,  4.93it/s]

false
Determine whether the semantic relation where chikungunya is the subject, symptoms and signs is the predicate, and neurological disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tricuspid atresia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4791it [16:03,  4.86it/s]

true
Determine whether the semantic relation where bacterial sexually transmitted disease is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

4792it [16:03,  4.87it/s]

true
Determine whether the semantic relation where Mus is the subject, main food source is the predicate, and root is the object constitutes an accurate semantic relation.

4794it [16:03,  4.94it/s]

false
Determine whether the semantic relation where pim-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ciprofloxacin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

4796it [16:04,  5.10it/s]

false
Determine whether the semantic relation where allergic rhinitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

4798it [16:04,  5.20it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4800it [16:04,  5.24it/s]

true
Determine whether the semantic relation where DNA gyrase is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lung abscess is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

4801it [16:05,  5.02it/s]

false
Determine whether the semantic relation where (S)-(−)-colchicine is the subject, has use is the predicate, and therapy is the object constitutes an accurate semantic relation.

4803it [16:05,  5.07it/s]

false
Determine whether the semantic relation where magnesium hydroxide is the subject, medical condition treated is the predicate, and metabolic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where substance-related disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4804it [16:05,  5.16it/s]

true
Determine whether the semantic relation where epoxy resins is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4806it [16:06,  5.12it/s]

true
Determine whether the semantic relation where pindolol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4807it [16:06,  5.01it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

4808it [16:06,  4.98it/s]

true
Determine whether the semantic relation where stereotypy is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

4809it [16:06,  4.78it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

4810it [16:06,  4.81it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

4812it [16:07,  5.07it/s]

true
Determine whether the semantic relation where heroin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HIV/AIDS is the subject, symptoms and signs is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.

4814it [16:07,  5.21it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ocular paraneoplastic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4816it [16:08,  5.33it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sarcoidosis is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

4818it [16:08,  5.40it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MDMA is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4819it [16:08,  5.31it/s]

true
Determine whether the semantic relation where vagus nerve injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

4820it [16:08,  5.19it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

4822it [16:09,  5.08it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true

4823it [16:09,  5.09it/s]

Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

4825it [16:09,  4.99it/s]

true
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peritoneal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4826it [16:09,  5.16it/s]

true
Determine whether the semantic relation where dissociative identity disorder is the subject, medical examination is the predicate, and questionnaire is the object constitutes an accurate semantic relation.

4827it [16:10,  4.87it/s]

false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

4828it [16:10,  4.84it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

4830it [16:10,  5.00it/s]

true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesteatoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4832it [16:11,  5.05it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psoriatic arthritis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4833it [16:11,  4.85it/s]

true
Determine whether the semantic relation where psoriatic arthritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

4835it [16:11,  5.21it/s]

Determine whether the semantic relation where theobromine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sparganosis is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

4837it [16:12,  5.12it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where animal is the subject, studied by is the predicate, and biology is the object constitutes an accurate semantic relation.

4839it [16:12,  5.23it/s]

true
Determine whether the semantic relation where myelofibrosis is the subject, comorbidity is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatocellular adenoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4841it [16:12,  5.08it/s]

true
Determine whether the semantic relation where argininemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

4843it [16:13,  4.95it/s]

true
Determine whether the semantic relation where accelerometry is the subject, has use is the predicate, and engineering is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4845it [16:13,  5.02it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true

4846it [16:13,  5.00it/s]

Determine whether the semantic relation where 2,4-dinitrochlorobenzene is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true

4847it [16:14,  5.09it/s]

Determine whether the semantic relation where bone conduction is the subject, instance of is the predicate, and technology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

4848it [16:14,  5.12it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

4849it [16:14,  5.05it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4851it [16:14,  5.13it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4852it [16:15,  5.23it/s]

true
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

4854it [16:15,  4.71it/s]

true
Determine whether the semantic relation where nitrilotriacetic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spiroplasma is the subject, Gram staining is the predicate, and gram-positive bacteria is the object constitutes an accurate semantic relation.

4856it [16:15,  5.04it/s]

false
Determine whether the semantic relation where 3,4-methylenedioxyamphetamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4858it [16:16,  5.08it/s]

false
Determine whether the semantic relation where Kikuchi disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where international normalized ratio is the subject, part of is the predicate, and blood test is the object constitutes an accurate semantic relation.

4860it [16:16,  5.36it/s]

true
Determine whether the semantic relation where (−)-sparteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

4862it [16:17,  5.29it/s]

true
Determine whether the semantic relation where Fibroblast growth factor 5 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4864it [16:17,  5.26it/s]

true
Determine whether the semantic relation where space motion sickness is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vascular dementia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

4865it [16:17,  5.15it/s]

false
Determine whether the semantic relation where parasitic protozoa infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4867it [16:18,  5.17it/s]

true
Determine whether the semantic relation where serpin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pilocarpine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4869it [16:18,  5.25it/s]

false
Determine whether the semantic relation where methane is the subject, found in taxon is the predicate, and Aspergillus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bezoar is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4871it [16:18,  5.36it/s]

false
Determine whether the semantic relation where fenofibrate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mercury poisoning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

4873it [16:19,  5.43it/s]

false
Determine whether the semantic relation where CDKN2A is the subject, expressed in is the predicate, and pericardium is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bahrain is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

4875it [16:19,  5.07it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Bahrain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where electrostimulation is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.

4877it [16:19,  5.28it/s]

true
Determine whether the semantic relation where materials testing is the subject, subclass of is the predicate, and scientific method is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Montenegro is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4879it [16:20,  5.21it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Montenegro is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 20 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

4881it [16:20,  5.08it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

4883it [16:21,  5.00it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and sumatriptan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

4884it [16:21,  4.96it/s]

true
Determine whether the semantic relation where slipped capital femoral epiphysis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

4885it [16:21,  4.80it/s]

false
Determine whether the semantic relation where hyaluronic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4887it [16:22,  4.75it/s]

false
Determine whether the semantic relation where neoplasm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

4888it [16:22,  4.92it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

4890it [16:22,  5.07it/s]

true
Determine whether the semantic relation where growth hormone secretagogue receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gluten is the subject, instance of is the predicate, and adhesive is the object constitutes an accurate semantic relation.

4892it [16:23,  5.10it/s]

false
Determine whether the semantic relation where glucagon is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vasoactive intestinal peptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4893it [16:23,  5.12it/s]

true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, possible treatment is the predicate, and glucocorticoid is the object constitutes an accurate semantic relation.

4894it [16:23,  4.83it/s]

true
Determine whether the semantic relation where apolipoprotein(a) is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

4896it [16:23,  4.63it/s]

false
Determine whether the semantic relation where omeprazole is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

4897it [16:24,  4.72it/s]

false
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

4899it [16:24,  4.69it/s]

true
Determine whether the semantic relation where aconitine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

4901it [16:24,  4.85it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4903it [16:25,  4.97it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

4905it [16:25,  5.10it/s]

false
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where achalasia is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

4906it [16:25,  5.25it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

4908it [16:26,  5.09it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where POU class 4 homeobox 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4910it [16:26,  4.98it/s]

false
Determine whether the semantic relation where Interleukin 13 receptor subunit alpha 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cichorium intybus is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

4912it [16:27,  4.99it/s]

true
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.

4914it [16:27,  5.17it/s]

false
Determine whether the semantic relation where alpha fetoprotein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Adenine phosphoribosyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

4916it [16:27,  5.28it/s]

true
Determine whether the semantic relation where azoospermia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where asbestos is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4917it [16:28,  5.06it/s]

false
Determine whether the semantic relation where vinblastine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4919it [16:28,  5.19it/s]

true
Determine whether the semantic relation where subclavian steal syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

4920it [16:28,  5.28it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

4921it [16:28,  5.02it/s]

true
Determine whether the semantic relation where erythropoietic protoporphyria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4923it [16:29,  5.02it/s]

true
Determine whether the semantic relation where onychomycosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

4925it [16:29,  5.22it/s]

true
Determine whether the semantic relation where Mus is the subject, main food source is the predicate, and food is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

4927it [16:30,  5.39it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

4928it [16:30,  5.40it/s]

true
Determine whether the semantic relation where KIT ligand is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

4929it [16:30,  4.93it/s]

false
Determine whether the semantic relation where medical error is the subject, subclass of is the predicate, and social issue is the object constitutes an accurate semantic relation.

4930it [16:30,  4.93it/s]

true
Determine whether the semantic relation where Cathepsin A is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

4932it [16:31,  4.72it/s]

false
Determine whether the semantic relation where clotrimazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salmonellosis is the subject, possible treatment is the predicate, and gastric lavage is the object constitutes an accurate semantic relation.

4933it [16:31,  4.80it/s]

false
Determine whether the semantic relation where gingival neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4935it [16:31,  4.86it/s]

true
Determine whether the semantic relation where ethylene oxide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where African trypanosomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

4937it [16:32,  5.12it/s]

true
Determine whether the semantic relation where histamine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hymenolepiasis is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.

4939it [16:32,  5.16it/s]

true
Determine whether the semantic relation where BAK1 is the subject, expressed in is the predicate, and rectum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

4941it [16:32,  5.40it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pityriasis versicolor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4942it [16:33,  5.23it/s]

true
Determine whether the semantic relation where chlorpyrifos is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

4943it [16:33,  4.87it/s]

false
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4945it [16:33,  5.03it/s]

false
Determine whether the semantic relation where AIDS-related complex is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Takayasu's arteritis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

4947it [16:34,  5.24it/s]

false
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

4949it [16:34,  5.35it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blood is the subject, part of is the predicate, and circulatory system is the object constitutes an accurate semantic relation.

4951it [16:34,  5.26it/s]

true
Determine whether the semantic relation where vasoactive intestinal peptide is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

4953it [16:35,  5.17it/s]

true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

4955it [16:35,  5.07it/s]

true
Determine whether the semantic relation where acute myeloid leukemia is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where taurine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

4957it [16:35,  5.08it/s]

false
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperuricemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4959it [16:36,  5.28it/s]

true
Determine whether the semantic relation where RUNX family transcription factor 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

4961it [16:36,  5.32it/s]

true
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ketorolac is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

4963it [16:37,  5.21it/s]

true
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and lung is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

4965it [16:37,  5.09it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urticaria pigmentosa is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

4966it [16:37,  4.96it/s]

false
Determine whether the semantic relation where tetanus is the subject, possible treatment is the predicate, and beta blocker is the object constitutes an accurate semantic relation.

4968it [16:38,  4.90it/s]

false
Determine whether the semantic relation where guanosine cyclic 3',5'-phosphate is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bleeding gums is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4970it [16:38,  5.05it/s]

false
Determine whether the semantic relation where delirium is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where delirium is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

4971it [16:38,  4.84it/s]

false
Determine whether the semantic relation where multiple myeloma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

4972it [16:38,  4.84it/s]

true
Determine whether the semantic relation where multiple myeloma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4974it [16:39,  4.63it/s]

true
Determine whether the semantic relation where Vanuatu is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Vanuatu is the object constitutes an accurate semantic relation.

4976it [16:39,  5.07it/s]

true
Determine whether the semantic relation where subependymal glioma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, main food source is the predicate, and fish is the object constitutes an accurate semantic relation.

4977it [16:39,  5.15it/s]

false
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

4979it [16:40,  5.03it/s]

true
Determine whether the semantic relation where S-nitroso-N-acetyl-D-penicillamine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastrointestinal system disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

4981it [16:40,  5.09it/s]

true
Determine whether the semantic relation where bacterial pneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where halothane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

4982it [16:40,  5.15it/s]

true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

4984it [16:41,  5.09it/s]

false
Determine whether the semantic relation where hemolysis is the subject, health specialty is the predicate, and pathology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ovarian disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

4985it [16:41,  5.12it/s]

true
Determine whether the semantic relation where anisometropia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

4987it [16:41,  5.08it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

4988it [16:42,  5.05it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

4990it [16:42,  5.01it/s]

true
Determine whether the semantic relation where uremia is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

4992it [16:42,  4.99it/s]

true
Determine whether the semantic relation where niacinamide is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anisakiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

4993it [16:43,  4.92it/s]

true
Determine whether the semantic relation where CD86 molecule is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

4995it [16:43,  4.99it/s]

false
Determine whether the semantic relation where myeloid leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poliomyelitis is the subject, anatomical location is the predicate, and peripheral nervous system is the object constitutes an accurate semantic relation.

4997it [16:43,  5.17it/s]

false
Determine whether the semantic relation where coercion is the subject, has effect is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

4999it [16:44,  5.20it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 11a is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tourette syndrome is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

5000it [16:44,  5.09it/s]

false
Determine whether the semantic relation where sirolimus is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

5002it [16:45,  4.64it/s]

false
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hereditary breast ovarian cancer is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5003it [16:45,  4.20it/s]

true
Determine whether the semantic relation where anthracosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5005it [16:45,  4.38it/s]

true
Determine whether the semantic relation where Cyclin-dependent serine/threonine-protein kinase CDC28 YBR160W is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amylopectin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5007it [16:46,  4.84it/s]

false
Determine whether the semantic relation where gastric mucosal hypertrophy is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where animal testing is the subject, followed by is the predicate, and clinical trial is the object constitutes an accurate semantic relation.

5008it [16:46,  4.99it/s]

false
Determine whether the semantic relation where 3-hydroxybutyric acid is the subject, subclass of is the predicate, and fatty alcohol is the object constitutes an accurate semantic relation.

5010it [16:46,  5.02it/s]

false
Determine whether the semantic relation where clinical trial is the subject, follows is the predicate, and animal testing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where varicocele is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5012it [16:47,  4.99it/s]

true
Determine whether the semantic relation where erysipelas is the subject, possible treatment is the predicate, and ultraviolet radiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cephalothin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

5014it [16:47,  5.17it/s]

false
Determine whether the semantic relation where C-reactive protein is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neuroectodermal tumor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5016it [16:47,  5.22it/s]

true
Determine whether the semantic relation where conflict of interest is the subject, subclass of is the predicate, and risk is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dextrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5018it [16:48,  5.15it/s]

false
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

5020it [16:48,  5.46it/s]

true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Cucumis sativus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where endothelin 1 is the subject, cell component is the predicate, and transport vesicle is the object constitutes an accurate semantic relation.

5022it [16:49,  5.32it/s]

false
Determine whether the semantic relation where oxygen is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diethylhexyl phthalate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5024it [16:49,  5.32it/s]

true
Determine whether the semantic relation where 4-aminobenzoic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chorionic gonadotropin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5026it [16:49,  5.23it/s]

false
Determine whether the semantic relation where pneumonia is the subject, risk factor is the predicate, and diabetes is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pancreatic neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5028it [16:50,  5.14it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, afflicts is the predicate, and respiratory system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paratyphoid fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

5030it [16:50,  5.15it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

5031it [16:50,  5.26it/s]

true
Determine whether the semantic relation where tennis elbow is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

5033it [16:51,  5.20it/s]

true
Determine whether the semantic relation where xylazine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily C member 8 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

5035it [16:51,  5.44it/s]

true
Determine whether the semantic relation where β-alanine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dicrocoeliasis is the subject, has natural reservoir is the predicate, and Felidae is the object constitutes an accurate semantic relation.

5037it [16:51,  5.45it/s]

false
Determine whether the semantic relation where growth differentiation factor 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where atrial fibrillation is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

5039it [16:52,  5.22it/s]

false
Determine whether the semantic relation where anterior pituitary hormones is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ceftizoxime is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

5041it [16:52,  5.22it/s]

false
Determine whether the semantic relation where erythrocyte membrane is the subject, subclass of is the predicate, and biological membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulindac is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

5043it [16:53,  5.05it/s]

false
Determine whether the semantic relation where transcription factor 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where necrotizing sialometaplasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5045it [16:53,  5.10it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heparin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5047it [16:53,  5.17it/s]

true
Determine whether the semantic relation where TEK receptor tyrosine kinase is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, medical examination is the predicate, and complement fixation test is the object constitutes an accurate semantic relation.

5049it [16:54,  5.18it/s]

false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5051it [16:54,  5.28it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary system disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

5052it [16:54,  5.24it/s]

true
Determine whether the semantic relation where Meleagris is the subject, named after is the predicate, and Peru is the object constitutes an accurate semantic relation.

5053it [16:55,  5.13it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

5055it [16:55,  5.28it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

5057it [16:55,  5.13it/s]

true
Determine whether the semantic relation where pravastatin is the subject, medical condition treated is the predicate, and acute myeloid leukemia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

5058it [16:55,  5.08it/s]

true
Determine whether the semantic relation where protein engineering is the subject, part of is the predicate, and biochemistry is the object constitutes an accurate semantic relation.

5060it [16:56,  5.07it/s]

true
Determine whether the semantic relation where chlorpyrifos is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.

5062it [16:56,  5.25it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

5064it [16:57,  5.31it/s]

false
Determine whether the semantic relation where Proteolipid protein 1 is the subject, biological process is the predicate, and chemical synaptic transmission is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

5066it [16:57,  5.07it/s]

true
Determine whether the semantic relation where environment is the subject, different from is the predicate, and lifestyle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5068it [16:57,  5.14it/s]

true
Determine whether the semantic relation where Pappalysin 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lifestyle is the subject, different from is the predicate, and environment is the object constitutes an accurate semantic relation.

5069it [16:58,  5.09it/s]

false
Determine whether the semantic relation where Huntington's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5071it [16:58,  4.96it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperglycemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5072it [16:58,  5.05it/s]

true
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

5074it [16:59,  5.08it/s]

false
Determine whether the semantic relation where Pasteurellaceae infections is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diethylhexyl phthalate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5076it [16:59,  5.31it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

5077it [16:59,  5.37it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.

5079it [17:00,  5.05it/s]

false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular endothelial growth factor A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5081it [17:00,  5.31it/s]

false
Determine whether the semantic relation where anthrax is the subject, has natural reservoir is the predicate, and Q25312 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where priapism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5082it [17:00,  5.39it/s]

true
Determine whether the semantic relation where Giardia lamblia is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

5083it [17:00,  5.13it/s]

true
Determine whether the semantic relation where dicrocoeliasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5084it [17:01,  4.75it/s]

true
Determine whether the semantic relation where serotonin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5086it [17:01,  4.83it/s]

true
Determine whether the semantic relation where HAM is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 2 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

5088it [17:01,  5.11it/s]

true
Determine whether the semantic relation where adenosine diphosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

5090it [17:02,  5.16it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South America is the subject, shares border with is the predicate, and North America is the object constitutes an accurate semantic relation.

5091it [17:02,  5.19it/s]

true
Determine whether the semantic relation where arterial hypertension is the subject, drug or therapy used for treatment is the predicate, and ubidecarenone is the object constitutes an accurate semantic relation.

5092it [17:02,  4.65it/s]

false
Determine whether the semantic relation where carnosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5093it [17:02,  4.71it/s]

true
Determine whether the semantic relation where North America is the subject, shares border with is the predicate, and South America is the object constitutes an accurate semantic relation.

5094it [17:03,  4.59it/s]

true
Determine whether the semantic relation where ubidecarenone is the subject, medical condition treated is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

5095it [17:03,  4.46it/s]

false
Determine whether the semantic relation where esomeprazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5097it [17:03,  4.70it/s]

true
Determine whether the semantic relation where Republic of the Congo is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where type-1 diabetes is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5098it [17:04,  4.72it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.

5100it [17:04,  4.92it/s]

true
Determine whether the semantic relation where tumor of testis and paratestis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where wheat allergy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5101it [17:04,  5.06it/s]

true
Determine whether the semantic relation where Cystatin C is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

5103it [17:05,  4.90it/s]

false
Determine whether the semantic relation where Indonesia is the subject, ethnic group is the predicate, and Arabs is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

5105it [17:05,  4.86it/s]

true
Determine whether the semantic relation where gallic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

5107it [17:05,  5.17it/s]

true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

5109it [17:06,  4.93it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smoking is the subject, has effect is the predicate, and tuberculosis is the object constitutes an accurate semantic relation.

5111it [17:06,  5.22it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where liver parasitic disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

5113it [17:06,  5.21it/s]

true
Determine whether the semantic relation where phentermine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

5115it [17:07,  5.22it/s]

true
Determine whether the semantic relation where bruxism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, basic form of government is the predicate, and democracy is the object constitutes an accurate semantic relation.

5117it [17:07,  5.31it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-citrulline is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

5118it [17:08,  4.31it/s]

false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

5119it [17:08,  4.47it/s]

true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

5120it [17:08,  4.57it/s]

true
Determine whether the semantic relation where Burkitt lymphoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

5122it [17:08,  4.70it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Montenegro is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

5124it [17:09,  4.69it/s]

true
Determine whether the semantic relation where Montenegro is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5125it [17:09,  4.88it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

5127it [17:09,  5.05it/s]

false
Determine whether the semantic relation where silver nitrate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5129it [17:10,  4.93it/s]

false
Determine whether the semantic relation where dexamethasone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where etoposide is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

5131it [17:10,  5.09it/s]

false
Determine whether the semantic relation where parotid gland neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where triacetin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5133it [17:11,  5.25it/s]

true
Determine whether the semantic relation where Behçet's disease is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

5135it [17:11,  5.23it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where obesity is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5136it [17:11,  5.30it/s]

true
Determine whether the semantic relation where onchocerciasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5137it [17:12,  3.75it/s]

true
Determine whether the semantic relation where fungal infection of the central nervous system is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

5139it [17:12,  4.18it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

5141it [17:12,  4.68it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fibroblast growth factor 10 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5143it [17:13,  5.04it/s]

false
Determine whether the semantic relation where Dihydroorotate dehydrogenase (quinone) is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rh disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

5145it [17:13,  5.11it/s]

false
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and flecainide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where secretin is the subject, cell component is the predicate, and cellular component is the object constitutes an accurate semantic relation.

5147it [17:14,  5.20it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where flecainide is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

5149it [17:14,  5.19it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amebiasis is the subject, drug or therapy used for treatment is the predicate, and doxycycline is the object constitutes an accurate semantic relation.

5150it [17:14,  5.18it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

5151it [17:14,  4.85it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5153it [17:15,  4.83it/s]

true
Determine whether the semantic relation where neostigmine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tick-borne encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5154it [17:15,  4.81it/s]

true
Determine whether the semantic relation where vascular malformation is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

5155it [17:15,  4.65it/s]

false
Determine whether the semantic relation where rhinoscleroma is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5157it [17:16,  4.86it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Cucumis melo is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

5159it [17:16,  4.61it/s]

true
Determine whether the semantic relation where actinomycosis is the subject, anatomical location is the predicate, and skin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5161it [17:16,  4.93it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5162it [17:17,  5.07it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

5163it [17:17,  4.93it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

5164it [17:17,  4.92it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

5165it [17:17,  4.78it/s]

true
Determine whether the semantic relation where von Willebrand's disease is the subject, symptoms and signs is the predicate, and subarachnoid hemorrhage is the object constitutes an accurate semantic relation.

5167it [17:18,  4.87it/s]

false
Determine whether the semantic relation where cyclodextrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

5169it [17:18,  5.10it/s]

true
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and bronchitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

5171it [17:18,  5.17it/s]

true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5173it [17:19,  5.14it/s]

true
Determine whether the semantic relation where EPH receptor A3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Addison's disease is the subject, subclass of is the predicate, and male reproductive system disease is the object constitutes an accurate semantic relation.

5175it [17:19,  5.21it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5176it [17:19,  5.03it/s]

true
Determine whether the semantic relation where Botswana is the subject, separated from is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5178it [17:20,  5.01it/s]

false
Determine whether the semantic relation where nasopharyngitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5180it [17:20,  4.99it/s]

true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prolactinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5182it [17:21,  4.82it/s]

true
Determine whether the semantic relation where prolactinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ehrlichiosis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

5183it [17:21,  4.66it/s]

true
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and ketorolac is the object constitutes an accurate semantic relation.

5185it [17:21,  4.97it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where galactosemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5187it [17:22,  5.15it/s]

true
Determine whether the semantic relation where Venezuela is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5189it [17:22,  5.32it/s]

true
Determine whether the semantic relation where trench fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5190it [17:22,  5.40it/s]

true
Determine whether the semantic relation where rectal prolapse is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

5192it [17:23,  5.16it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

5194it [17:23,  5.12it/s]

true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

5195it [17:23,  5.17it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

5197it [17:24,  5.15it/s]

true
Determine whether the semantic relation where Behçet's disease is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperlipidemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

5199it [17:24,  4.92it/s]

maybe
Determine whether the semantic relation where quinolinic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alfadex is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5200it [17:24,  4.81it/s]

false
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5202it [17:25,  4.90it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

5203it [17:25,  4.98it/s]

true
Determine whether the semantic relation where complement C3 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

5205it [17:25,  4.86it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hereditary CNS demyelinating disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

5206it [17:26,  4.98it/s]

false
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, biological process is the predicate, and excitatory postsynaptic potential is the object constitutes an accurate semantic relation.

5208it [17:26,  5.03it/s]

false
Determine whether the semantic relation where cod liver oil is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where periventricular leukomalacia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5210it [17:26,  5.08it/s]

true
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where graft-versus-host disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5212it [17:27,  5.11it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5213it [17:27,  5.19it/s]

true
Determine whether the semantic relation where cryptosporidiosis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

5215it [17:27,  4.95it/s]

true
Determine whether the semantic relation where peracetic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and arginine vasopressin is the object constitutes an accurate semantic relation.

5216it [17:28,  4.91it/s]

false
Determine whether the semantic relation where arginine vasopressin is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.

5217it [17:28,  4.77it/s]

true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

5219it [17:28,  4.97it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Djibouti is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

5220it [17:28,  4.79it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5222it [17:29,  4.73it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Djibouti is the object constitutes an accurate semantic relation.

5224it [17:29,  5.02it/s]

true
Determine whether the semantic relation where dental erosion is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5226it [17:30,  4.90it/s]

true
Determine whether the semantic relation where meningeal carcinomatosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phalloidin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5228it [17:30,  5.09it/s]

true
Determine whether the semantic relation where glycerol is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and glycerol is the object constitutes an accurate semantic relation.

5229it [17:30,  5.27it/s]

false
Determine whether the semantic relation where giardiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5231it [17:31,  4.81it/s]

true
Determine whether the semantic relation where tuberculous empyema is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vesicular stomatitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5232it [17:31,  4.43it/s]

true
Determine whether the semantic relation where ETS proto-oncogene 1, transcription factor is the subject, biological process is the predicate, and estrous cycle is the object constitutes an accurate semantic relation.

5233it [17:31,  4.55it/s]

false
Determine whether the semantic relation where Von Hippel-Lindau tumor suppressor is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

5234it [17:31,  4.52it/s]

true
Determine whether the semantic relation where Glial cell derived neurotrophic factor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

5235it [17:32,  4.43it/s]

false
Determine whether the semantic relation where adenosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5236it [17:32,  3.66it/s]

true
Determine whether the semantic relation where caregiver is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

5237it [17:32,  3.89it/s]

false
Determine whether the semantic relation where Apolipoprotein A2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5239it [17:33,  4.30it/s]

true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

5240it [17:33,  4.49it/s]

true
Determine whether the semantic relation where vasoactive intestinal peptide is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

5241it [17:33,  4.31it/s]

true
Determine whether the semantic relation where otitis externa is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5242it [17:33,  4.44it/s]

true
Determine whether the semantic relation where Momordica charantia is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5243it [17:33,  4.39it/s]

true
Determine whether the semantic relation where HAM is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false

5244it [17:34,  4.55it/s]

Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5246it [17:34,  4.40it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 4 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

5248it [17:35,  4.60it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5249it [17:35,  4.45it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

5251it [17:35,  4.68it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

5252it [17:35,  4.73it/s]

true
Determine whether the semantic relation where plasmacytoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5253it [17:36,  4.79it/s]

true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5255it [17:36,  4.83it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5256it [17:36,  4.98it/s]

true
Determine whether the semantic relation where poly(methyl methacrylate) is the subject, subject has role is the predicate, and vasodilator agent is the object constitutes an accurate semantic relation.

5258it [17:37,  5.05it/s]

false
Determine whether the semantic relation where triage is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where S-nitrosoglutathione is the subject, subject has role is the predicate, and anti-infective agent is the object constitutes an accurate semantic relation.

5259it [17:37,  5.13it/s]

false
Determine whether the semantic relation where binge eating disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

5261it [17:37,  4.92it/s]

true
Determine whether the semantic relation where Complement factor H is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where plague is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

5262it [17:38,  4.43it/s]

false
Determine whether the semantic relation where boutonneuse fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

5263it [17:38,  4.58it/s]

Determine whether the semantic relation where alpha fetoprotein is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5264it [17:38,  4.42it/s]

true
Determine whether the semantic relation where endometrium is the subject, subclass of is the predicate, and mucous membrane is the object constitutes an accurate semantic relation.

5266it [17:38,  4.68it/s]

true
Determine whether the semantic relation where deoxycholic acid is the subject, found in taxon is the predicate, and Pseudomonas syringae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ehrlichiosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5267it [17:39,  4.94it/s]

true
Determine whether the semantic relation where Matrix metallopeptidase 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

5269it [17:39,  4.96it/s]

false
Determine whether the semantic relation where cerebral infarction is the subject, drug or therapy used for treatment is the predicate, and dantrolene is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dantrolene is the subject, medical condition treated is the predicate, and cerebral infarction is the object constitutes an accurate semantic relation.

5271it [17:39,  5.08it/s]

false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Coffea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Matrix metallopeptidase 12 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

5273it [17:40,  5.24it/s]

false
Determine whether the semantic relation where galactose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Paradental cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5275it [17:40,  5.29it/s]

true
Determine whether the semantic relation where carbohydrate metabolic disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where T-cell prolymphocytic leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5276it [17:40,  5.05it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5278it [17:41,  5.07it/s]

true
Determine whether the semantic relation where fungal infection of the central nervous system is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

5280it [17:41,  5.24it/s]

true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nephrosis is the subject, different from is the predicate, and necrosis is the object constitutes an accurate semantic relation.

5281it [17:41,  5.30it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

5282it [17:41,  5.18it/s]

true
Determine whether the semantic relation where African horse sickness is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5284it [17:42,  5.02it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dry eye syndrome is the subject, drug or therapy used for treatment is the predicate, and sodium chloride is the object constitutes an accurate semantic relation.

5285it [17:42,  5.10it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

5287it [17:42,  5.14it/s]

true
Determine whether the semantic relation where sodium chloride is the subject, medical condition treated is the predicate, and dry eye syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5288it [17:43,  5.21it/s]

true
Determine whether the semantic relation where penicillin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5290it [17:43,  5.12it/s]

true
Determine whether the semantic relation where acute myeloid leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitamin E is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5292it [17:43,  5.25it/s]

true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

5294it [17:44,  5.23it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, shares border with is the predicate, and Suriname is the object constitutes an accurate semantic relation.

5296it [17:44,  5.14it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Suriname is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Suriname is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.

5298it [17:45,  5.15it/s]

true
Determine whether the semantic relation where Suriname is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diabetes is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5300it [17:45,  5.18it/s]

true
Determine whether the semantic relation where allergic bronchopulmonary aspergillosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and Sweden is the object constitutes an accurate semantic relation.

5301it [17:45,  4.90it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

5302it [17:45,  4.89it/s]

true
Determine whether the semantic relation where chimera is the subject, different from is the predicate, and conjoined twins is the object constitutes an accurate semantic relation.

5304it [17:46,  4.92it/s]

true
Determine whether the semantic relation where conjoined twins is the subject, different from is the predicate, and chimera is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where propranolol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5305it [17:46,  4.99it/s]

false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

5307it [17:46,  4.97it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where afferent loop syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5309it [17:47,  4.99it/s]

true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, possible treatment is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

5311it [17:47,  5.09it/s]

false
Determine whether the semantic relation where carmine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toxoplasmosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5313it [17:48,  5.27it/s]

true
Determine whether the semantic relation where hepatitis A is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where factitious disorder imposed on another is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5315it [17:48,  5.16it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Natriuretic peptide A is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

5317it [17:48,  5.18it/s]

false
Determine whether the semantic relation where ghrelin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

5318it [17:49,  5.26it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

5320it [17:49,  5.25it/s]

true
Determine whether the semantic relation where breast disease is the subject, subclass of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chitin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5322it [17:49,  5.21it/s]

false
Determine whether the semantic relation where glycerol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ethylene oxide is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.

5324it [17:50,  5.17it/s]

true
Determine whether the semantic relation where hereditary elliptocytosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eye movement desensitization and reprocessing is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

5325it [17:50,  5.24it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

5327it [17:50,  5.16it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

5328it [17:50,  5.02it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

5330it [17:51,  5.09it/s]

true
Determine whether the semantic relation where Great Lakes region is the subject, country is the predicate, and Canada is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where spinal cord injury is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

5332it [17:51,  5.01it/s]

false
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5333it [17:51,  5.00it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.

5335it [17:52,  4.98it/s]

true
Determine whether the semantic relation where ret proto-oncogene is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where laryngeal nerve injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

5336it [17:52,  5.06it/s]

false
Determine whether the semantic relation where Coagulation factor XII is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5338it [17:53,  5.03it/s]

false
Determine whether the semantic relation where femoral neck fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where REM sleep parasomnia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5340it [17:53,  5.10it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

5342it [17:53,  5.25it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aluminum hydroxide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5343it [17:53,  5.23it/s]

false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

5344it [17:54,  5.10it/s]

true
Determine whether the semantic relation where osteomyelitis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5346it [17:54,  5.10it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.

5348it [17:54,  4.85it/s]

true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

5350it [17:55,  5.02it/s]

true
Determine whether the semantic relation where neurilemmoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prednisolone is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5352it [17:55,  5.10it/s]

true
Determine whether the semantic relation where naphazoline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where isopropylidenediphenyl bisoxyhydroxypropyl methacrylate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5353it [17:55,  5.07it/s]

true
Determine whether the semantic relation where spine trauma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5355it [17:56,  4.48it/s]

true
Determine whether the semantic relation where leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone inflammation disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5356it [17:56,  4.40it/s]

true
Determine whether the semantic relation where narcotherapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

5358it [17:57,  4.59it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

5360it [17:57,  4.91it/s]

true
Determine whether the semantic relation where signal transducer and activator of transcription 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fibroblast growth factor receptor 4 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

5362it [17:57,  5.06it/s]

false
Determine whether the semantic relation where 4-aminobenzoic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

5364it [17:58,  5.19it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and diabetes is the object constitutes an accurate semantic relation.

5365it [17:58,  5.23it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

5366it [17:58,  4.43it/s]

maybe
Determine whether the semantic relation where bone neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5367it [17:58,  4.57it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

5369it [17:59,  4.74it/s]

true
Determine whether the semantic relation where clofibrate is the subject, medical condition treated is the predicate, and coronary artery disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coronary artery disease is the subject, drug or therapy used for treatment is the predicate, and clofibrate is the object constitutes an accurate semantic relation.

5370it [17:59,  4.52it/s]

false
Determine whether the semantic relation where accelerometry is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

5371it [17:59,  4.52it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

5373it [18:00,  4.72it/s]

true
Determine whether the semantic relation where anthrax is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

5375it [18:00,  5.07it/s]

true
Determine whether the semantic relation where ovarian hyperstimulation syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5376it [18:00,  5.11it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.

5377it [18:01,  4.94it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

5378it [18:01,  4.78it/s]

true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

5380it [18:01,  4.42it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and central nervous system disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where beta-1,3-glucuronyltransferase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

5382it [18:02,  4.65it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.
false

5383it [18:02,  4.80it/s]

Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tick-borne encephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5384it [18:02,  4.81it/s]

true
Determine whether the semantic relation where aspirin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5385it [18:02,  4.70it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

5386it [18:03,  4.69it/s]

true
Determine whether the semantic relation where bromodeoxyuridine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5387it [18:03,  4.61it/s]

true
Determine whether the semantic relation where cholecalciferol is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

5389it [18:03,  4.58it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbenicillin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

5390it [18:03,  4.78it/s]

false
Determine whether the semantic relation where Mus is the subject, main food source is the predicate, and leaf is the object constitutes an accurate semantic relation.

5391it [18:04,  4.74it/s]

maybe
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

5393it [18:04,  4.74it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where computational science is the subject, has use is the predicate, and chemistry is the object constitutes an accurate semantic relation.

5395it [18:04,  4.97it/s]

true
Determine whether the semantic relation where corticotropin releasing hormone is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

5397it [18:05,  5.05it/s]

true
Determine whether the semantic relation where Rift Valley fever is the subject, symptoms and signs is the predicate, and blindness is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lobeline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5399it [18:05,  5.21it/s]

false
Determine whether the semantic relation where Bence Jones protein is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

5400it [18:05,  5.10it/s]

false
Determine whether the semantic relation where Crohn's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5402it [18:06,  5.03it/s]

true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where programmed cell death 1 ligand 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5403it [18:06,  5.09it/s]

true
Determine whether the semantic relation where tuberculosis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

5405it [18:06,  5.16it/s]

true
Determine whether the semantic relation where Parkinson's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where severity of illness index is the subject, facet of is the predicate, and disease is the object constitutes an accurate semantic relation.

5407it [18:07,  5.18it/s]

false
Determine whether the semantic relation where thiomersal is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alcoholic liver disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5409it [18:07,  5.32it/s]

true
Determine whether the semantic relation where abdominal obesity is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thyroid neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5410it [18:07,  5.24it/s]

true
Determine whether the semantic relation where beta-glucan is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5412it [18:08,  5.16it/s]

false
Determine whether the semantic relation where non-Hodgkin lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where asthma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5414it [18:08,  5.30it/s]

true
Determine whether the semantic relation where ileus is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where signal transducer and activator of transcription 3 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

5416it [18:08,  5.28it/s]

maybe
Determine whether the semantic relation where hair is the subject, subclass of is the predicate, and biomaterial is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where germinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5417it [18:09,  5.16it/s]

true
Determine whether the semantic relation where factor Va [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

5418it [18:09,  5.07it/s]

false
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

5419it [18:09,  4.96it/s]

false
Determine whether the semantic relation where neuroendocrine tumor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5421it [18:10,  4.89it/s]

true
Determine whether the semantic relation where uroporphyrinogen decarboxylase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New York is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

5422it [18:10,  5.02it/s]

true
Determine whether the semantic relation where New York is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

5424it [18:10,  4.93it/s]

true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and sedentary lifestyle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where legionnaires' disease is the subject, possible treatment is the predicate, and oxygen therapy is the object constitutes an accurate semantic relation.

5426it [18:11,  4.99it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bhutan is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

5427it [18:11,  5.03it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Bhutan is the object constitutes an accurate semantic relation.

5429it [18:11,  5.10it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

5430it [18:11,  5.03it/s]

true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

5432it [18:12,  5.00it/s]

true
Determine whether the semantic relation where Glutamate metabotropic receptor 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brassica rapa is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

5434it [18:12,  5.14it/s]

true
Determine whether the semantic relation where precocious puberty is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KiSS-1 metastasis suppressor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

5436it [18:12,  5.31it/s]

true
Determine whether the semantic relation where cadaverine is the subject, named after is the predicate, and corpse is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quercetin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5437it [18:13,  4.76it/s]

false
Determine whether the semantic relation where lipodystrophy is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

5438it [18:13,  4.73it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5440it [18:13,  4.98it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Venezuela is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

5442it [18:14,  5.06it/s]

false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5444it [18:14,  5.26it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transient global amnesia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5446it [18:14,  5.35it/s]

true
Determine whether the semantic relation where Volkmann's contracture is the subject, subclass of is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bufotenine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5448it [18:15,  5.29it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

5450it [18:15,  5.21it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 11 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cardiogenic shock is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5452it [18:16,  5.17it/s]

true
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lansoprazole is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

5454it [18:16,  5.35it/s]

false
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercuric chloride is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

5456it [18:16,  5.31it/s]

true
Determine whether the semantic relation where mucin 5AC, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paclitaxel is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

5458it [18:17,  5.29it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fentanyl is the subject, medical condition treated is the predicate, and fibromyalgia is the object constitutes an accurate semantic relation.

5459it [18:17,  5.15it/s]

false
Determine whether the semantic relation where Opioid receptor delta 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5461it [18:17,  4.69it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

5463it [18:18,  4.94it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coagulation factor VII is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

5465it [18:18,  5.02it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where staphylococcal infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5467it [18:19,  5.18it/s]

true
Determine whether the semantic relation where tricuspid atresia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

5469it [18:19,  5.03it/s]

true
Determine whether the semantic relation where eukaryotic cell is the subject, part of is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parasomnia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

5471it [18:19,  4.95it/s]

false
Determine whether the semantic relation where parasomnia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where secretion or excretion is the subject, facet of is the predicate, and physiology is the object constitutes an accurate semantic relation.

5473it [18:20,  5.20it/s]

true
Determine whether the semantic relation where Diclofenac is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where desipramine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

5475it [18:20,  5.23it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and desipramine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholecystokinin is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

5477it [18:21,  5.30it/s]

false
Determine whether the semantic relation where placenta disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where EGFR is the subject, expressed in is the predicate, and urethra is the object constitutes an accurate semantic relation.

5478it [18:21,  5.15it/s]

false
Determine whether the semantic relation where cortisol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5479it [18:21,  4.95it/s]

false
Determine whether the semantic relation where Japan is the subject, shares border with is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

5480it [18:21,  4.66it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

5482it [18:22,  4.67it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and Japan is the object constitutes an accurate semantic relation.

5484it [18:22,  4.99it/s]

false
Determine whether the semantic relation where hepatitis B is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

5485it [18:22,  5.10it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

5487it [18:23,  5.21it/s]

true
Determine whether the semantic relation where sarin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phencyclidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5489it [18:23,  5.20it/s]

true
Determine whether the semantic relation where GNAS complex locus is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5491it [18:23,  5.37it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nova Scotia is the subject, named after is the predicate, and Scotland is the object constitutes an accurate semantic relation.

5493it [18:24,  5.51it/s]

true
Determine whether the semantic relation where T-cell lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and urinary system is the object constitutes an accurate semantic relation.

5495it [18:24,  5.45it/s]

true
Determine whether the semantic relation where paragonimiasis is the subject, anatomical location is the predicate, and brain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where The Gambia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5497it [18:24,  5.55it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and The Gambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydroxycarbamide is the subject, medical condition treated is the predicate, and non-small-cell lung carcinoma is the object constitutes an accurate semantic relation.

5499it [18:25,  5.19it/s]

false
Determine whether the semantic relation where ribosomal RNA is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where otoscopy is the subject, instance of is the predicate, and physical examination is the object constitutes an accurate semantic relation.

5501it [18:25,  5.16it/s]

true
Determine whether the semantic relation where non-small-cell lung carcinoma is the subject, drug or therapy used for treatment is the predicate, and hydroxycarbamide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where torticollis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5502it [18:25,  5.30it/s]

false
Determine whether the semantic relation where Cape Verde is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5504it [18:26,  5.17it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Cape Verde is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where galactorrhea is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

5506it [18:26,  5.18it/s]

false
Determine whether the semantic relation where uranyl nitrate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

5508it [18:27,  5.45it/s]

true
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastrointestinal tuberculosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

5509it [18:27,  5.50it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

5511it [18:27,  5.30it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (−)-ephedrine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5513it [18:27,  5.38it/s]

true
Determine whether the semantic relation where fluphenazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where telangiectasia is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5515it [18:28,  5.37it/s]

false
Determine whether the semantic relation where apomorphine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where boutonneuse fever is the subject, has natural reservoir is the predicate, and rabbit is the object constitutes an accurate semantic relation.

5517it [18:28,  5.23it/s]

false
Determine whether the semantic relation where pneumococcal meningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

5518it [18:28,  5.31it/s]

Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

5519it [18:29,  5.34it/s]

true
Determine whether the semantic relation where granulomatous mastitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5521it [18:29,  5.25it/s]

true
Determine whether the semantic relation where 2'-deoxyguanosine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-ornithine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

5523it [18:29,  5.36it/s]

false
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

5525it [18:30,  5.44it/s]

true
Determine whether the semantic relation where Matrix metallopeptidase 7 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

5526it [18:30,  5.39it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

5528it [18:30,  5.26it/s]

true
Determine whether the semantic relation where creatinine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where risk is the subject, has part(s) is the predicate, and selection is the object constitutes an accurate semantic relation.

5529it [18:31,  5.34it/s]

false
Determine whether the semantic relation where apigenin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5531it [18:31,  5.09it/s]

false
Determine whether the semantic relation where Q21659 is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gastric fistula is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

5533it [18:31,  5.33it/s]

true
Determine whether the semantic relation where noscapine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 7 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5535it [18:32,  5.40it/s]

true
Determine whether the semantic relation where epidemic pleurodynia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylthiouracil is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5537it [18:32,  5.29it/s]

true
Determine whether the semantic relation where Liberia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

5539it [18:32,  5.17it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zygomycosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5541it [18:33,  5.33it/s]

true
Determine whether the semantic relation where Caplan's syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Liberia is the object constitutes an accurate semantic relation.

5542it [18:33,  5.28it/s]

true
Determine whether the semantic relation where Rift Valley fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

5544it [18:33,  5.16it/s]

true
Determine whether the semantic relation where aurothioglucose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

5546it [18:34,  5.32it/s]

false
Determine whether the semantic relation where Kyrgyzstan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5547it [18:34,  5.36it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true

5548it [18:34,  5.24it/s]

Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.

5550it [18:35,  4.99it/s]

true
Determine whether the semantic relation where pulmonary embolism is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

5552it [18:35,  4.22it/s]

false
Determine whether the semantic relation where heptose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

5554it [18:36,  4.74it/s]

true
Determine whether the semantic relation where fludeoxyglucose (18F) is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

5556it [18:36,  5.03it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

5558it [18:36,  5.41it/s]

true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

5560it [18:37,  5.34it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 37 is the subject, subject has role is the predicate, and angiogenesis inhibitor is the object constitutes an accurate semantic relation.

5561it [18:37,  5.46it/s]

false
Determine whether the semantic relation where neurotic disorder is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

5562it [18:37,  5.20it/s]

false
Determine whether the semantic relation where noma is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

5564it [18:37,  5.17it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

5566it [18:38,  5.22it/s]

true
Determine whether the semantic relation where Prader–Willi syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteomyelitis is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5568it [18:38,  5.35it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where theophylline is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

5570it [18:39,  5.29it/s]

false
Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coagulation factor VII is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5572it [18:39,  5.26it/s]

false
Determine whether the semantic relation where hyperhomocysteinemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plant sap is the subject, subclass of is the predicate, and secretion or excretion is the object constitutes an accurate semantic relation.

5574it [18:39,  5.29it/s]

true
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pentetic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5576it [18:40,  5.08it/s]

true
Determine whether the semantic relation where Receptor activity modifying protein 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where EGFR is the subject, expressed in is the predicate, and placenta is the object constitutes an accurate semantic relation.

5578it [18:40,  5.19it/s]

false
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where feline acquired immunodeficiency syndrome is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

5580it [18:40,  5.19it/s]

true
Determine whether the semantic relation where benign paroxysmal positional nystagmus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acridine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5582it [18:41,  4.92it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Luxembourg is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Luxembourg is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

5583it [18:41,  4.94it/s]

false
Determine whether the semantic relation where solute carrier family 6 member 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5585it [18:42,  5.01it/s]

false
Determine whether the semantic relation where benzydamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Gaucher's disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

5587it [18:42,  5.19it/s]

false
Determine whether the semantic relation where grey wolf is the subject, main food source is the predicate, and Arvicolinae is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

5589it [18:42,  5.30it/s]

true
Determine whether the semantic relation where metronidazole is the subject, medical condition treated is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pulmonary adenomatosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5591it [18:43,  5.13it/s]

true
Determine whether the semantic relation where americium is the subject, named after is the predicate, and Americas is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spinal neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5593it [18:43,  5.30it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.

5595it [18:43,  5.23it/s]

false
Determine whether the semantic relation where protein biosynthesis is the subject, subclass of is the predicate, and polymerization is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

5597it [18:44,  5.22it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

5598it [18:44,  5.24it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

5599it [18:44,  4.98it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

5601it [18:45,  5.08it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where reserpine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

5603it [18:45,  5.33it/s]

false
Determine whether the semantic relation where engineering is the subject, uses is the predicate, and chemistry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where androgen receptor is the subject, biological process is the predicate, and fertilization is the object constitutes an accurate semantic relation.

5604it [18:45,  5.28it/s]

false
Determine whether the semantic relation where paratyphoid fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

5606it [18:46,  4.98it/s]

false
Determine whether the semantic relation where toxoplasmosis is the subject, drug or therapy used for treatment is the predicate, and chloroquine is the object constitutes an accurate semantic relation.
false

5607it [18:46,  5.10it/s]

Determine whether the semantic relation where acute stress reaction is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where infectious bone disease is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5608it [18:46,  5.20it/s]

true
Determine whether the semantic relation where parathyroid hormone is the subject, biological process is the predicate, and regulation of gene expression is the object constitutes an accurate semantic relation.

5610it [18:46,  5.11it/s]

true
Determine whether the semantic relation where Paired box 5 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where transthyretin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5612it [18:47,  5.29it/s]

true
Determine whether the semantic relation where paratyphoid fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

5613it [18:47,  5.33it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.

5615it [18:47,  5.20it/s]

true
Determine whether the semantic relation where benzoyl peroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 2 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

5616it [18:47,  5.21it/s]

false
Determine whether the semantic relation where rheumatoid arthritis is the subject, drug or therapy used for treatment is the predicate, and thalidomide is the object constitutes an accurate semantic relation.

5618it [18:48,  4.89it/s]

false
Determine whether the semantic relation where thalidomide is the subject, medical condition treated is the predicate, and rheumatoid arthritis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

5620it [18:48,  4.57it/s]

false
Determine whether the semantic relation where erythritol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

5621it [18:49,  4.65it/s]

false
Determine whether the semantic relation where spina bifida cystica is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5623it [18:49,  4.79it/s]

true
Determine whether the semantic relation where major histocompatibility complex, class I, A is the subject, biological process is the predicate, and protein ubiquitination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Cape Verde is the object constitutes an accurate semantic relation.

5625it [18:49,  5.13it/s]

true
Determine whether the semantic relation where herpes zoster is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Cape Verde is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

5626it [18:50,  5.07it/s]

true
Determine whether the semantic relation where salivary gland disease is the subject, subclass of is the predicate, and gastrointestinal system disease is the object constitutes an accurate semantic relation.

5627it [18:50,  4.89it/s]

false
Determine whether the semantic relation where keratin 20 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5629it [18:50,  4.96it/s]

true
Determine whether the semantic relation where microtubule associated protein tau is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

5630it [18:50,  4.79it/s]

false
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false

5632it [18:51,  4.98it/s]

Determine whether the semantic relation where diabetic ketoacidosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diabetic ketoacidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5633it [18:51,  4.94it/s]

true
Determine whether the semantic relation where schistosomiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5634it [18:51,  4.92it/s]

true
Determine whether the semantic relation where hypoplastic left heart syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5635it [18:51,  4.87it/s]

true
Determine whether the semantic relation where ectodysplasin A2 receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

5637it [18:52,  4.99it/s]

false
Determine whether the semantic relation where medullary carcinoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bladder exstrophy is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

5638it [18:52,  5.01it/s]

false
Determine whether the semantic relation where arterial hypertension is the subject, drug or therapy used for treatment is the predicate, and bepridil is the object constitutes an accurate semantic relation.

5639it [18:52,  4.96it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

5640it [18:52,  4.95it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

5642it [18:53,  4.81it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bepridil is the subject, medical condition treated is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

5643it [18:53,  4.52it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

5644it [18:53,  4.49it/s]

true
Determine whether the semantic relation where mucin 5AC, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false

5646it [18:54,  4.76it/s]

Determine whether the semantic relation where morphine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glycerol is the subject, subject has role is the predicate, and allergen is the object constitutes an accurate semantic relation.

5648it [18:54,  5.12it/s]

false
Determine whether the semantic relation where isoprenaline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stress fracture is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5650it [18:55,  4.98it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-chloroethan-1-ol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5652it [18:55,  5.13it/s]

true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

5654it [18:55,  5.13it/s]

true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where permethrin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5656it [18:56,  5.32it/s]

true
Determine whether the semantic relation where Sirtuin 2 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and tetrodotoxin is the object constitutes an accurate semantic relation.

5658it [18:56,  5.04it/s]

false
Determine whether the semantic relation where polyendocrine metabolic ovarian syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true

5659it [18:56,  5.17it/s]

Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where smoking is the subject, has effect is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

5661it [18:57,  5.29it/s]

true
Determine whether the semantic relation where acne keloidalis nuchae is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, has cause is the predicate, and smoking is the object constitutes an accurate semantic relation.

5663it [18:57,  5.49it/s]

true
Determine whether the semantic relation where pneumonia is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, three Ig domains and short cytoplasmic tail 1 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

5664it [18:57,  5.38it/s]

true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5666it [18:58,  5.00it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and meclofenamic acid is the object constitutes an accurate semantic relation.

5667it [18:58,  5.05it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

5669it [18:58,  4.84it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meclofenamic acid is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

5671it [18:59,  5.00it/s]

true
Determine whether the semantic relation where fetal alcohol spectrum disorders is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where metrifonate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5672it [18:59,  5.13it/s]

false
Determine whether the semantic relation where sirtuin 1 is the subject, cell component is the predicate, and nuclear envelope is the object constitutes an accurate semantic relation.

5674it [18:59,  5.17it/s]

false
Determine whether the semantic relation where calcium gluconate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cellulitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5675it [18:59,  5.02it/s]

true
Determine whether the semantic relation where intracranial embolism is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

5677it [19:00,  4.80it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

5678it [19:00,  5.00it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Ecuador is the object constitutes an accurate semantic relation.

5679it [19:00,  4.95it/s]

true
Determine whether the semantic relation where Ecuador is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

5680it [19:01,  4.50it/s]

true
Determine whether the semantic relation where Interleukin 12A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5682it [19:01,  4.60it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

5683it [19:01,  4.75it/s]

true
Determine whether the semantic relation where selenium is the subject, location of discovery is the predicate, and Sweden is the object constitutes an accurate semantic relation.

5684it [19:01,  4.75it/s]

true
Determine whether the semantic relation where sphingosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5686it [19:02,  4.97it/s]

false
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, three Ig domains and long cytoplasmic tail 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choledocholithiasis is the subject, subclass of is the predicate, and endocrine system disease is the object constitutes an accurate semantic relation.

5687it [19:02,  5.09it/s]

false
Determine whether the semantic relation where goiter is the subject, health specialty is the predicate, and nuclear medicine is the object constitutes an accurate semantic relation.

5688it [19:02,  4.99it/s]

false
Determine whether the semantic relation where photodermatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5689it [19:02,  4.85it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

5691it [19:03,  4.95it/s]

true
Determine whether the semantic relation where amoebic dysentery is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

5693it [19:03,  5.13it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

5695it [19:04,  5.40it/s]

true
Determine whether the semantic relation where (RS)-fenfluramine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anogenital venereal wart is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5697it [19:04,  4.86it/s]

true
Determine whether the semantic relation where anogenital venereal wart is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where caffeine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5699it [19:04,  5.07it/s]

true
Determine whether the semantic relation where survivor is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myelin basic protein is the subject, biological process is the predicate, and chemical synaptic transmission is the object constitutes an accurate semantic relation.

5701it [19:05,  5.19it/s]

false
Determine whether the semantic relation where otitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Agouti signaling protein is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

5702it [19:05,  5.22it/s]

false
Determine whether the semantic relation where Dopamine receptor D3 is the subject, biological process is the predicate, and autophagy is the object constitutes an accurate semantic relation.

5704it [19:05,  5.03it/s]

false
Determine whether the semantic relation where appendectomy is the subject, field of work is the predicate, and medicine is the object constitutes an accurate semantic relation.
false

5705it [19:06,  5.10it/s]

Determine whether the semantic relation where myoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neuroleptic malignant syndrome is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

5707it [19:06,  5.08it/s]

true
Determine whether the semantic relation where angiotensins is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

5709it [19:06,  5.14it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5711it [19:07,  5.09it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and pentamidine is the object constitutes an accurate semantic relation.

5713it [19:07,  5.17it/s]

true
Determine whether the semantic relation where pentamidine is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oral lichen planus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5715it [19:08,  5.09it/s]

true
Determine whether the semantic relation where verapamil is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and pericardium is the object constitutes an accurate semantic relation.

5716it [19:08,  4.90it/s]

true
Determine whether the semantic relation where prostaglandin reductase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

5718it [19:08,  4.96it/s]

true
Determine whether the semantic relation where pyrazolone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 10 receptor subunit alpha is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5720it [19:09,  5.23it/s]

false
Determine whether the semantic relation where psoriasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psoriasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5722it [19:09,  5.17it/s]

true
Determine whether the semantic relation where adenovirus infection is the subject, symptoms and signs is the predicate, and rhinitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascariasis is the subject, medical examination is the predicate, and chest radiograph is the object constitutes an accurate semantic relation.

5723it [19:09,  5.34it/s]

false
Determine whether the semantic relation where mycoplasma infection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5724it [19:09,  5.20it/s]

false
Determine whether the semantic relation where oculocutaneous albinism is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

5726it [19:10,  5.01it/s]

false
Determine whether the semantic relation where Poxviridae infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Peyronie's disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

5728it [19:10,  5.29it/s]

false
Determine whether the semantic relation where alpha-beta T cell receptor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rabies is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5730it [19:10,  5.22it/s]

true
Determine whether the semantic relation where propranolol is the subject, side effect is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where digital dermatitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5731it [19:11,  5.26it/s]

true
Determine whether the semantic relation where animal is the subject, studied by is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

5733it [19:11,  5.09it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

5735it [19:11,  5.28it/s]

true
Determine whether the semantic relation where TEK receptor tyrosine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and gingivitis is the object constitutes an accurate semantic relation.

5736it [19:12,  5.33it/s]

false
Determine whether the semantic relation where morphine is the subject, medical condition treated is the predicate, and fibromyalgia is the object constitutes an accurate semantic relation.

5738it [19:12,  5.14it/s]

false
Determine whether the semantic relation where fibroblast growth factor receptor 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5740it [19:12,  5.24it/s]

false
Determine whether the semantic relation where protein folding is the subject, subclass of is the predicate, and cellular process or phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

5742it [19:13,  5.30it/s]

true
Determine whether the semantic relation where (RS)-clenbuterol is the subject, medical condition treated is the predicate, and chronic obstructive pulmonary disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chronic obstructive pulmonary disease is the subject, drug or therapy used for treatment is the predicate, and (RS)-clenbuterol is the object constitutes an accurate semantic relation.

5743it [19:13,  5.13it/s]

false
Determine whether the semantic relation where CD34 molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5744it [19:13,  4.92it/s]

false
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5746it [19:14,  4.68it/s]

false
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where biotin is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5748it [19:14,  5.13it/s]

false
Determine whether the semantic relation where nebramycin is the subject, instance of is the predicate, and complex mixture is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where temporomandibular joint pathology is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5749it [19:14,  5.19it/s]

false
Determine whether the semantic relation where DL-aspartic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

5751it [19:15,  5.08it/s]

false
Determine whether the semantic relation where subcutaneous emphysema is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paraquat dichloride is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5753it [19:15,  5.16it/s]

true
Determine whether the semantic relation where sinusitis is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and sinusitis is the object constitutes an accurate semantic relation.

5755it [19:15,  5.29it/s]

false
Determine whether the semantic relation where epidermal growth factor is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5757it [19:16,  5.23it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

5758it [19:16,  5.28it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

5760it [19:16,  5.10it/s]

true
Determine whether the semantic relation where paclitaxel is the subject, subject has role is the predicate, and immunologic adjuvant is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where epiglottitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5762it [19:17,  5.27it/s]

true
Determine whether the semantic relation where Interleukin 37 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where miliaria is the subject, different from is the predicate, and malaria is the object constitutes an accurate semantic relation.

5764it [19:17,  5.46it/s]

true
Determine whether the semantic relation where oral hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

5765it [19:17,  5.22it/s]

false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

5767it [19:18,  5.22it/s]

true
Determine whether the semantic relation where Pseudomonas infection is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5769it [19:18,  5.10it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyrogallol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5770it [19:18,  5.14it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

5772it [19:19,  5.11it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5773it [19:19,  5.07it/s]

true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5775it [19:19,  4.99it/s]

true
Determine whether the semantic relation where proteinuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Neuropeptide Y is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5777it [19:20,  5.29it/s]

true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

5778it [19:20,  5.12it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

5780it [19:20,  5.08it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

5781it [19:20,  5.19it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

5783it [19:21,  5.08it/s]

true
Determine whether the semantic relation where KIT proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where biuret is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5785it [19:21,  5.18it/s]

true
Determine whether the semantic relation where bacterial meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and hand dermatosis is the object constitutes an accurate semantic relation.

5787it [19:22,  5.24it/s]

false
Determine whether the semantic relation where adenosine triphosphate is the subject, found in taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hand dermatosis is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

5789it [19:22,  5.30it/s]

true
Determine whether the semantic relation where monosodium L-glutamate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5791it [19:22,  5.25it/s]

true
Determine whether the semantic relation where glucose intolerance is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

5793it [19:23,  5.39it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

5794it [19:23,  5.15it/s]

true
Determine whether the semantic relation where epidermodysplasia verruciformis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5796it [19:23,  5.14it/s]

true
Determine whether the semantic relation where phenylketonuria is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenylketonuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5798it [19:24,  5.05it/s]

true
Determine whether the semantic relation where Surfactant protein B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tyrosine kinase 2 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

5799it [19:24,  5.07it/s]

false
Determine whether the semantic relation where dexamethasone is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.

5800it [19:24,  4.95it/s]

true
Determine whether the semantic relation where hepatitis is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

5802it [19:25,  4.95it/s]

true
Determine whether the semantic relation where autosomal dominant polycystic kidney is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nicotinic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5803it [19:25,  5.07it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

5805it [19:25,  5.05it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where isatin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5807it [19:25,  5.26it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

5808it [19:26,  5.30it/s]

true
Determine whether the semantic relation where pelvic neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5810it [19:26,  5.19it/s]

true
Determine whether the semantic relation where dementia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5811it [19:26,  5.37it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

5813it [19:27,  5.06it/s]

true
Determine whether the semantic relation where anti-streptolysin O is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5814it [19:27,  4.95it/s]

true
Determine whether the semantic relation where casein kinase 1 delta is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5816it [19:27,  4.92it/s]

false
Determine whether the semantic relation where Cyclin D1 is the subject, biological process is the predicate, and lactation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where language disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

5818it [19:28,  4.80it/s]

false
Determine whether the semantic relation where lecithin is the subject, different from is the predicate, and lectin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CHARGE syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5820it [19:28,  4.85it/s]

true
Determine whether the semantic relation where peptidase inhibitor 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coronavirus disease is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

5821it [19:28,  5.05it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.

5823it [19:29,  4.95it/s]

true
Determine whether the semantic relation where paracoccidioidomycosis is the subject, subclass of is the predicate, and bone disease is the object constitutes an accurate semantic relation.
false

5824it [19:29,  5.06it/s]

Determine whether the semantic relation where cryptogenic organizing pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.

5826it [19:29,  5.23it/s]

maybe
Determine whether the semantic relation where cholera is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czechoslovakia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

5828it [19:30,  5.35it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Czechoslovakia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and social behavior is the object constitutes an accurate semantic relation.

5830it [19:30,  5.42it/s]

false
Determine whether the semantic relation where embolization is the subject, subclass of is the predicate, and hemostasis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cerebrovascular trauma is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

5831it [19:30,  5.26it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

5832it [19:30,  4.93it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

5834it [19:31,  4.67it/s]

true
Determine whether the semantic relation where sodium hypochlorite is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where taurodeoxycholic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5835it [19:31,  4.18it/s]

false
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false

5837it [19:32,  4.55it/s]

Determine whether the semantic relation where S-adenosyl-L-homocysteine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

5839it [19:32,  5.00it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where betahistine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5841it [19:32,  5.05it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and (±)-deprenyl is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Follicle stimulating hormone subunit beta is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5843it [19:33,  4.74it/s]

false
Determine whether the semantic relation where porphyria is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where iron deficiency anemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5844it [19:33,  4.74it/s]

true
Determine whether the semantic relation where methanol is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5846it [19:33,  4.98it/s]

false
Determine whether the semantic relation where impulse control disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

5848it [19:34,  4.97it/s]

true
Determine whether the semantic relation where apolipoprotein(a) is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

5850it [19:34,  5.16it/s]

true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sepharose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5852it [19:35,  5.16it/s]

false
Determine whether the semantic relation where keratin 13 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

5854it [19:35,  5.27it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, has part(s) is the predicate, and pancreatitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Regenerating family member 1 alpha is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

5855it [19:35,  4.72it/s]

true
Determine whether the semantic relation where herpes simplex is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5857it [19:36,  4.80it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where limb-girdle muscular dystrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5859it [19:36,  5.10it/s]

true
Determine whether the semantic relation where ehrlichiosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

5860it [19:36,  5.26it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

5862it [19:37,  5.00it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

5863it [19:37,  5.15it/s]

true
Determine whether the semantic relation where sodium benzoate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5865it [19:37,  5.02it/s]

true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where liver is the subject, innervated by is the predicate, and vagus nerve is the object constitutes an accurate semantic relation.

5867it [19:38,  5.18it/s]

true
Determine whether the semantic relation where liver is the subject, innervates is the predicate, and vagus nerve is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

5869it [19:38,  5.19it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

5870it [19:38,  5.14it/s]

true
Determine whether the semantic relation where vagus nerve is the subject, innervates is the predicate, and liver is the object constitutes an accurate semantic relation.

5872it [19:39,  5.20it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where premelanosome protein is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5873it [19:39,  5.04it/s]

false
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

5875it [19:39,  5.17it/s]

true
Determine whether the semantic relation where arachnoiditis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.

5876it [19:39,  4.90it/s]

true
Determine whether the semantic relation where quinidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5877it [19:40,  4.86it/s]

true
Determine whether the semantic relation where epispadias is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5878it [19:40,  4.79it/s]

true
Determine whether the semantic relation where gram-negative bacterial infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5879it [19:40,  4.78it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

5880it [19:40,  4.63it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

5881it [19:40,  4.58it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

5882it [19:41,  4.46it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

5884it [19:41,  4.74it/s]

true
Determine whether the semantic relation where Secretory leukocyte peptidase inhibitor is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where focal nodular hyperplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

5886it [19:42,  4.89it/s]

true
Determine whether the semantic relation where thoracic diaphragm is the subject, muscle insertion is the predicate, and lumbar vertebrae is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurogranin is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

5888it [19:42,  5.21it/s]

false
Determine whether the semantic relation where mouth is the subject, has use is the predicate, and breathing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium benzoate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

5890it [19:42,  5.29it/s]

true
Determine whether the semantic relation where milk allergy is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

5892it [19:43,  5.18it/s]

true
Determine whether the semantic relation where clotrimazole is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false

5893it [19:43,  5.33it/s]

Determine whether the semantic relation where POU class 4 homeobox 3 is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

5894it [19:43,  4.56it/s]

true
Determine whether the semantic relation where insulin receptor is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

5896it [19:44,  4.86it/s]

false
Determine whether the semantic relation where hydrocodone is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eicosapentaenoic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5898it [19:44,  5.02it/s]

false
Determine whether the semantic relation where diphenhydramine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

5900it [19:44,  5.19it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic kidney disease-mineral and bone disorder is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

5902it [19:45,  5.14it/s]

false
Determine whether the semantic relation where maple syrup urine disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where disopyramide is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

5904it [19:45,  5.22it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and disopyramide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where depression is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5906it [19:45,  5.21it/s]

true
Determine whether the semantic relation where Neuropeptide Y is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where toluidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5908it [19:46,  5.33it/s]

true
Determine whether the semantic relation where maleic anhydride is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where obesity hypoventilation syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

5910it [19:46,  5.40it/s]

false
Determine whether the semantic relation where eye disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

5912it [19:47,  5.29it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, symptoms and signs is the predicate, and meningitis is the object constitutes an accurate semantic relation.

5914it [19:47,  5.27it/s]

true
Determine whether the semantic relation where small cell carcinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where limb-girdle muscular dystrophy is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.

5915it [19:47,  5.24it/s]

true
Determine whether the semantic relation where butylated hydroxytoluene is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

5917it [19:48,  4.88it/s]

true
Determine whether the semantic relation where riboflavin is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where citric acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

5918it [19:48,  5.02it/s]

false
Determine whether the semantic relation where CD5 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

5920it [19:48,  5.00it/s]

true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptosporidiosis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

5921it [19:48,  4.60it/s]

false
Determine whether the semantic relation where endarteritis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false

5922it [19:49,  4.71it/s]

Determine whether the semantic relation where 2,2′-bipyridine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

5923it [19:49,  4.72it/s]

false
Determine whether the semantic relation where fluorouracil is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

5925it [19:49,  4.83it/s]

false
Determine whether the semantic relation where ochronosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where noscapine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

5926it [19:49,  4.91it/s]

true
Determine whether the semantic relation where coagulation factor V is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5928it [19:50,  4.84it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

5930it [19:50,  5.09it/s]

true
Determine whether the semantic relation where DL-amphetamine is the subject, significant drug interaction is the predicate, and procarbazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where irritable bowel syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

5931it [19:50,  5.21it/s]

true
Determine whether the semantic relation where tumor lysis syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

5933it [19:51,  5.01it/s]

true
Determine whether the semantic relation where ectopic atrial tachycardia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5935it [19:51,  4.96it/s]

true
Determine whether the semantic relation where butyric acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 5 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

5937it [19:52,  4.83it/s]

true
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5938it [19:52,  4.99it/s]

true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Belgium is the object constitutes an accurate semantic relation.
false

5940it [19:52,  5.07it/s]

Determine whether the semantic relation where user guide is the subject, subclass of is the predicate, and documentation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5942it [19:53,  5.33it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

5944it [19:53,  5.37it/s]

false
Determine whether the semantic relation where heart conduction disease is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where viral pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

5946it [19:53,  5.24it/s]

true
Determine whether the semantic relation where neurturin is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where C-X-C motif chemokine ligand 13 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

5947it [19:54,  5.17it/s]

true
Determine whether the semantic relation where brain transplantation is the subject, subclass of is the predicate, and organ transplantation is the object constitutes an accurate semantic relation.

5949it [19:54,  5.17it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Siberia is the subject, different from is the predicate, and Serbia is the object constitutes an accurate semantic relation.

5951it [19:54,  5.34it/s]

true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where biomimetics is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

5953it [19:55,  5.28it/s]

false
Determine whether the semantic relation where ambroxol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anorexia nervosa is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5955it [19:55,  5.41it/s]

true
Determine whether the semantic relation where activated protein C resistance is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poliomyelitis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

5957it [19:55,  5.44it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiomyoma is the subject, subclass of is the predicate, and vascular disease is the object constitutes an accurate semantic relation.

5959it [19:56,  5.06it/s]

true
Determine whether the semantic relation where Alström syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Alström syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5960it [19:56,  5.00it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

5961it [19:56,  4.91it/s]

true
Determine whether the semantic relation where opium is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

5963it [19:57,  4.89it/s]

false
Determine whether the semantic relation where sudden infant death syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

5964it [19:57,  4.84it/s]

true
Determine whether the semantic relation where SRC proto-oncogene, non-receptor tyrosine kinase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

5966it [19:57,  4.91it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5968it [19:58,  5.17it/s]

true
Determine whether the semantic relation where oxypurinol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 21 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

5970it [19:58,  5.31it/s]

true
Determine whether the semantic relation where lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD19 molecule is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

5971it [19:58,  5.42it/s]

false
Determine whether the semantic relation where Niger is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

5972it [19:58,  5.24it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Niger is the object constitutes an accurate semantic relation.

5974it [19:59,  5.19it/s]

true
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and skin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

5976it [19:59,  5.43it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and Datura stramonium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lung disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5977it [19:59,  4.94it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

5979it [20:00,  4.97it/s]

true
Determine whether the semantic relation where somatosensory disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Epstein–Barr virus infection is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

5981it [20:00,  5.17it/s]

false
Determine whether the semantic relation where neurogenic inflammation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Guyana is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

5983it [20:01,  5.41it/s]

true
Determine whether the semantic relation where KIT proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Guyana is the object constitutes an accurate semantic relation.

5984it [20:01,  5.14it/s]

true
Determine whether the semantic relation where diabetic retinopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5985it [20:01,  4.57it/s]

true
Determine whether the semantic relation where porphyria cutanea tarda is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5987it [20:01,  4.60it/s]

true
Determine whether the semantic relation where myocardial infarction is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where echinococcosis is the subject, anatomical location is the predicate, and muscle is the object constitutes an accurate semantic relation.

5989it [20:02,  4.82it/s]

false
Determine whether the semantic relation where dumping syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

5991it [20:02,  5.11it/s]

true
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where EPH receptor A1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

5993it [20:03,  5.24it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-ornithine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

5994it [20:03,  5.30it/s]

false
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

5996it [20:03,  4.88it/s]

false
Determine whether the semantic relation where uranyl nitrate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and serotonin is the object constitutes an accurate semantic relation.

5997it [20:03,  5.03it/s]

false
Determine whether the semantic relation where gastrinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

5999it [20:04,  4.88it/s]

true
Determine whether the semantic relation where chronic progressive external ophthalmoplegia is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
true

6000it [20:04,  4.99it/s]

Determine whether the semantic relation where intracranial hypotension is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pentetic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6002it [20:05,  4.36it/s]

true
Determine whether the semantic relation where Earth is the subject, has part(s) is the predicate, and Asia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Asia is the subject, part of is the predicate, and Earth is the object constitutes an accurate semantic relation.

6004it [20:05,  4.71it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

6006it [20:05,  4.95it/s]

true
Determine whether the semantic relation where osteochondritis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

6008it [20:06,  5.08it/s]

true
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

6009it [20:06,  5.18it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

6011it [20:06,  5.14it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Janus kinase 2 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

6013it [20:07,  5.21it/s]

true
Determine whether the semantic relation where trichuriasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where insulinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6014it [20:07,  4.93it/s]

true
Determine whether the semantic relation where cryoglobulinemia is the subject, subclass of is the predicate, and type IV hypersensitivity is the object constitutes an accurate semantic relation.

6015it [20:07,  4.89it/s]

false
Determine whether the semantic relation where Adenylosuccinate lyase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

6017it [20:08,  4.76it/s]

true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

6019it [20:08,  5.10it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hemoglobin J is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6020it [20:08,  5.08it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

6022it [20:09,  4.99it/s]

true
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

6023it [20:09,  4.94it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

6025it [20:09,  4.83it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

6026it [20:09,  4.86it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

6027it [20:10,  4.77it/s]

true
Determine whether the semantic relation where streptodornase and streptokinase is the subject, instance of is the predicate, and pharmaceutical preparation is the object constitutes an accurate semantic relation.

6028it [20:10,  4.80it/s]

false
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

6030it [20:10,  4.56it/s]

true
Determine whether the semantic relation where dysplastic nevus syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

6032it [20:11,  4.85it/s]

true
Determine whether the semantic relation where occupational burnout is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ventricular fibrillation is the subject, drug or therapy used for treatment is the predicate, and arginine vasopressin is the object constitutes an accurate semantic relation.

6034it [20:11,  5.01it/s]

true
Determine whether the semantic relation where arginine vasopressin is the subject, medical condition treated is the predicate, and ventricular fibrillation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

6036it [20:12,  5.05it/s]

false
Determine whether the semantic relation where Surfactant protein D is the subject, biological process is the predicate, and developmental process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where norfloxacin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6038it [20:12,  5.20it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and bronchitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6040it [20:12,  5.21it/s]

true
Determine whether the semantic relation where insulin receptor is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6041it [20:12,  5.27it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

6042it [20:13,  5.11it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

6044it [20:13,  5.15it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Carthamus tinctorius is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where seasonal allergic rhinitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6046it [20:13,  5.29it/s]

true
Determine whether the semantic relation where urethane is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ETS transcription factor ELK1 is the subject, cell component is the predicate, and axon terminus is the object constitutes an accurate semantic relation.

6048it [20:14,  5.18it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

6050it [20:14,  4.62it/s]

true
Determine whether the semantic relation where prosopagnosia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thyroid hormone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6051it [20:15,  4.86it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true

6053it [20:15,  4.96it/s]

Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and coloboma is the object constitutes an accurate semantic relation.

6055it [20:15,  5.16it/s]

false
Determine whether the semantic relation where haemonchiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

6057it [20:16,  5.37it/s]

true
Determine whether the semantic relation where amoxicillin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

6058it [20:16,  5.28it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.

6059it [20:16,  4.57it/s]

true
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.
true

6061it [20:17,  4.86it/s]

Determine whether the semantic relation where calcium oxalate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and black pepper is the object constitutes an accurate semantic relation.

6062it [20:17,  4.88it/s]

false
Determine whether the semantic relation where SRC proto-oncogene, non-receptor tyrosine kinase is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

6064it [20:17,  5.05it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and fatigue is the object constitutes an accurate semantic relation.

6066it [20:17,  5.24it/s]

true
Determine whether the semantic relation where secretin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

6067it [20:18,  5.37it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

6069it [20:18,  5.24it/s]

true
Determine whether the semantic relation where ifosfamide is the subject, medical condition treated is the predicate, and chronic lymphocytic leukemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Antigua and Barbuda is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6071it [20:18,  4.93it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Antigua and Barbuda is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and extracellular fluid is the object constitutes an accurate semantic relation.

6073it [20:19,  5.10it/s]

true
Determine whether the semantic relation where chronic lymphocytic leukemia is the subject, drug or therapy used for treatment is the predicate, and ifosfamide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diphenhydramine is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.

6075it [20:19,  5.38it/s]

false
Determine whether the semantic relation where protein-energy malnutrition is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where actinomycosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6077it [20:20,  5.32it/s]

true
Determine whether the semantic relation where infectious mononucleosis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mycoplasma is the subject, different from is the predicate, and Mycobacterium is the object constitutes an accurate semantic relation.

6078it [20:20,  5.39it/s]

true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

6080it [20:20,  5.18it/s]

true
Determine whether the semantic relation where type II site-specific deoxyribonuclease complex is the subject, part of is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and delusion is the object constitutes an accurate semantic relation.

6081it [20:20,  4.83it/s]

true
Determine whether the semantic relation where Pakistan is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

6083it [20:21,  4.70it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

6084it [20:21,  4.26it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6086it [20:22,  4.72it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apigenin is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

6088it [20:22,  4.91it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Mytilus edulis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cardiac arrest is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.

6089it [20:22,  4.96it/s]

false
Determine whether the semantic relation where chylomicron remnant is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

6090it [20:22,  4.67it/s]

false
Determine whether the semantic relation where malathion is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

6091it [20:23,  4.10it/s]

maybe
Determine whether the semantic relation where ovine progressive interstitial pneumonia is the subject, subclass of is the predicate, and viral pneumonia is the object constitutes an accurate semantic relation.

6093it [20:23,  4.57it/s]

false
Determine whether the semantic relation where Tourette syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bleomycin is the subject, subject has role is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

6095it [20:23,  4.78it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

6096it [20:24,  4.81it/s]

true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

6097it [20:24,  4.70it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6098it [20:24,  4.63it/s]

true
Determine whether the semantic relation where lorazepam is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

6100it [20:25,  4.82it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where toluene 2,4-diisocyanate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6102it [20:25,  5.07it/s]

true
Determine whether the semantic relation where meningioma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where etomidate is the subject, medical condition treated is the predicate, and closed head injury is the object constitutes an accurate semantic relation.

6103it [20:25,  5.10it/s]

false
Determine whether the semantic relation where West Nile fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

6104it [20:25,  4.33it/s]

true
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

6106it [20:26,  4.58it/s]

true
Determine whether the semantic relation where polymyositis is the subject, different from is the predicate, and poliomyelitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

6108it [20:26,  4.72it/s]

true
Determine whether the semantic relation where closed head injury is the subject, drug or therapy used for treatment is the predicate, and etomidate is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ditiocarb is the subject, subject has role is the predicate, and antiviral agent is the object constitutes an accurate semantic relation.

6110it [20:27,  5.04it/s]

false
Determine whether the semantic relation where naloxone is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6111it [20:27,  4.93it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

6112it [20:27,  4.89it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

6113it [20:27,  4.62it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

6115it [20:28,  4.92it/s]

true
Determine whether the semantic relation where reproductive tract infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chickenpox is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

6116it [20:28,  4.96it/s]

true
Determine whether the semantic relation where atopic dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6118it [20:28,  4.93it/s]

true
Determine whether the semantic relation where prostatic hypertrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, has natural reservoir is the predicate, and Rattus is the object constitutes an accurate semantic relation.

6119it [20:28,  5.05it/s]

true
Determine whether the semantic relation where cytidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6121it [20:29,  4.97it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

6123it [20:29,  5.18it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, C is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where filariasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6124it [20:29,  5.27it/s]

true
Determine whether the semantic relation where BRCA2 is the subject, expressed in is the predicate, and lymph node is the object constitutes an accurate semantic relation.

6126it [20:30,  5.08it/s]

false
Determine whether the semantic relation where yellow fever is the subject, medical examination is the predicate, and immunoassay is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cannabis smoking is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

6128it [20:30,  5.22it/s]

false
Determine whether the semantic relation where integrin subunit alpha 3 is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thymidine phosphorylase is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

6130it [20:31,  5.28it/s]

false
Determine whether the semantic relation where mucormycosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.

6132it [20:31,  4.81it/s]

true
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone retroversion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6134it [20:31,  5.17it/s]

false
Determine whether the semantic relation where methylphenidate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

6136it [20:32,  5.07it/s]

true
Determine whether the semantic relation where blackwater fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6138it [20:32,  5.13it/s]

true
Determine whether the semantic relation where dientamoebiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chikungunya is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

6139it [20:32,  5.07it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

6141it [20:33,  5.03it/s]

true
Determine whether the semantic relation where polyendocrine metabolic ovarian syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit alpha 2 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

6143it [20:33,  4.98it/s]

false
Determine whether the semantic relation where gonorrhea is the subject, anatomical location is the predicate, and joint is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where growth differentiation factor 6 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

6144it [20:33,  4.73it/s]

true
Determine whether the semantic relation where register is the subject, subclass of is the predicate, and catalog is the object constitutes an accurate semantic relation.

6146it [20:34,  4.63it/s]

false
Determine whether the semantic relation where register is the subject, partially coincident with is the predicate, and catalog is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where catalog is the subject, partially coincident with is the predicate, and register is the object constitutes an accurate semantic relation.

6148it [20:34,  4.92it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q10915 is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

6149it [20:35,  4.94it/s]

false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

6151it [20:35,  4.99it/s]

true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where linoleic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

6153it [20:35,  5.16it/s]

false
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastrin releasing peptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6155it [20:36,  5.16it/s]

true
Determine whether the semantic relation where postcataract aphakia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mannans is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6156it [20:36,  4.90it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

6158it [20:36,  4.56it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Luchelli is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

6160it [20:37,  3.77it/s]

false
Determine whether the semantic relation where rhinitis is the subject, subclass of is the predicate, and bacterial infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

6162it [20:37,  4.34it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypotension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6163it [20:38,  4.52it/s]

false
Determine whether the semantic relation where Secernentea infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6164it [20:38,  4.58it/s]

false
Determine whether the semantic relation where Malawi is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6166it [20:38,  4.74it/s]

true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false

6167it [20:38,  4.83it/s]

Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Malawi is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tumor of hematopoietic and lymphoid tissues is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6169it [20:39,  4.97it/s]

true
Determine whether the semantic relation where glyceryl trioleate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where infantile myofibromatosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6171it [20:39,  4.87it/s]

true
Determine whether the semantic relation where meclofenoxate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paraphilia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6173it [20:40,  5.17it/s]

false
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and portal hypertension is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

6174it [20:40,  4.90it/s]

false
Determine whether the semantic relation where Japan is the subject, shares border with is the predicate, and Russia is the object constitutes an accurate semantic relation.

6175it [20:41,  2.37it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

6176it [20:41,  2.74it/s]

true
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and Japan is the object constitutes an accurate semantic relation.

6178it [20:41,  3.50it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

6180it [20:42,  4.28it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where barbering is the subject, instance of is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.

6182it [20:42,  4.75it/s]

true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

6184it [20:43,  5.21it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD63 molecule is the subject, biological process is the predicate, and pigmentation is the object constitutes an accurate semantic relation.

6185it [20:43,  4.96it/s]

false
Determine whether the semantic relation where biotin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6187it [20:43,  4.98it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypokalemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6188it [20:43,  5.11it/s]

false
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

6190it [20:44,  4.31it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Babesiosis is the subject, risk factor is the predicate, and immunosuppression is the object constitutes an accurate semantic relation.

6191it [20:44,  4.61it/s]

true
Determine whether the semantic relation where endodermal sinus tumor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6192it [20:44,  4.68it/s]

true
Determine whether the semantic relation where blood vessel is the subject, contains is the predicate, and blood is the object constitutes an accurate semantic relation.

6194it [20:45,  4.77it/s]

true
Determine whether the semantic relation where diphenylamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S-adenosylmethionine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

6195it [20:45,  4.95it/s]

false
Determine whether the semantic relation where mastitis is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

6197it [20:45,  4.63it/s]

false
Determine whether the semantic relation where phenylalanine hydroxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true

6198it [20:46,  4.81it/s]

Determine whether the semantic relation where Kawasaki disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transthyretin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6200it [20:46,  4.85it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptococcal meningitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6202it [20:46,  4.97it/s]

true
Determine whether the semantic relation where intracranial aneurysm is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uromodulin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6203it [20:47,  5.14it/s]

true
Determine whether the semantic relation where biuret is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6205it [20:47,  5.15it/s]

true
Determine whether the semantic relation where Von Willebrand factor is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Gulf War is the subject, participant is the predicate, and France is the object constitutes an accurate semantic relation.

6206it [20:47,  5.02it/s]

true
Determine whether the semantic relation where thymidine phosphorylase is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

6208it [20:48,  4.83it/s]

false
Determine whether the semantic relation where erectile dysfunction is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erectile dysfunction is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

6210it [20:48,  4.90it/s]

maybe
Determine whether the semantic relation where meningitis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dysgerminoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6212it [20:48,  5.04it/s]

true
Determine whether the semantic relation where iliac aneurysm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ubidecarenone is the subject, medical condition treated is the predicate, and angina pectoris is the object constitutes an accurate semantic relation.

6213it [20:49,  5.03it/s]

false
Determine whether the semantic relation where angina pectoris is the subject, drug or therapy used for treatment is the predicate, and ubidecarenone is the object constitutes an accurate semantic relation.

6215it [20:49,  5.01it/s]

false
Determine whether the semantic relation where secondary hyperparathyroidism is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sick building syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6217it [20:49,  4.99it/s]

true
Determine whether the semantic relation where guanine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary tuberculosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6219it [20:50,  5.01it/s]

true
Determine whether the semantic relation where Protein C, inactivator of coagulation factors Va and VIIIa is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myelin basic protein is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

6221it [20:50,  5.04it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Bahrain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where scimitar syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

6222it [20:50,  4.87it/s]

false
Determine whether the semantic relation where Bahrain is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

6223it [20:51,  4.81it/s]

false
Determine whether the semantic relation where Mycoplasmatales infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6225it [20:51,  4.89it/s]

true
Determine whether the semantic relation where integrin subunit alpha 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where disseminated intravascular coagulation is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

6226it [20:51,  5.09it/s]

true
Determine whether the semantic relation where stanozolol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6228it [20:52,  5.05it/s]

true
Determine whether the semantic relation where premelanosome protein is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where subacute sclerosing panencephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6229it [20:52,  4.82it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

6230it [20:52,  4.78it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6231it [20:52,  4.63it/s]

true
Determine whether the semantic relation where Eukaryotic translation initiation factor 5 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

6233it [20:53,  4.77it/s]

false
Determine whether the semantic relation where ectoparasitism is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isoniazid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6235it [20:53,  5.03it/s]

false
Determine whether the semantic relation where zoology is the subject, is the study of is the predicate, and animal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where animal is the subject, studied by is the predicate, and zoology is the object constitutes an accurate semantic relation.

6236it [20:53,  5.07it/s]

true
Determine whether the semantic relation where hearing test is the subject, instance of is the predicate, and physical examination is the object constitutes an accurate semantic relation.

6238it [20:54,  5.03it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiamine(1+) diphosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6239it [20:54,  5.13it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Grenada is the object constitutes an accurate semantic relation.

6240it [20:54,  4.99it/s]

true
Determine whether the semantic relation where polyendocrine metabolic ovarian syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

6242it [20:55,  4.87it/s]

false
Determine whether the semantic relation where polyendocrine metabolic ovarian syndrome is the subject, has cause is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Grenada is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

6243it [20:55,  5.07it/s]

true
Determine whether the semantic relation where rutin is the subject, found in taxon is the predicate, and Gossypium is the object constitutes an accurate semantic relation.

6244it [20:55,  4.95it/s]

true
Determine whether the semantic relation where NECA is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.

6245it [20:55,  4.94it/s]

true
Determine whether the semantic relation where foot-and-mouth disease is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

6246it [20:55,  4.77it/s]

true
Determine whether the semantic relation where tennis is the subject, country of origin is the predicate, and England is the object constitutes an accurate semantic relation.

6247it [20:56,  4.66it/s]

true
Determine whether the semantic relation where kidney neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6248it [20:56,  4.68it/s]

true
Determine whether the semantic relation where saponin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6250it [20:56,  4.50it/s]

false
Determine whether the semantic relation where acute myeloid leukemia is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vagus nerve disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6251it [20:57,  4.58it/s]

true
Determine whether the semantic relation where clemastine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6253it [20:57,  4.61it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, member of is the predicate, and Organization for Economic Cooperation and Development is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-alanine is the subject, part of is the predicate, and gelatin is the object constitutes an accurate semantic relation.

6255it [20:57,  4.93it/s]

true
Determine whether the semantic relation where influenza vaccine is the subject, instance of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 3 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

6257it [20:58,  5.13it/s]

true
Determine whether the semantic relation where combat disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6258it [20:58,  5.11it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

6259it [20:58,  4.81it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.

6260it [20:58,  4.56it/s]

false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6261it [20:59,  4.54it/s]

true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

6263it [20:59,  4.81it/s]

true
Determine whether the semantic relation where Q433152 is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

6265it [20:59,  5.01it/s]

false
Determine whether the semantic relation where Histidine ammonia-lyase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where β-alanine is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

6267it [21:00,  5.14it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where High mobility group box 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6269it [21:00,  5.08it/s]

false
Determine whether the semantic relation where leishmaniasis is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6271it [21:01,  5.27it/s]

true
Determine whether the semantic relation where mental fatigue is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where enterobiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6273it [21:01,  5.26it/s]

true
Determine whether the semantic relation where pneumoconiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dehydration is the subject, health specialty is the predicate, and intensive care medicine is the object constitutes an accurate semantic relation.

6275it [21:01,  5.49it/s]

false
Determine whether the semantic relation where carnitine O-acetyltransferase is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

6277it [21:02,  5.42it/s]

true
Determine whether the semantic relation where mansonelliasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

6279it [21:02,  5.17it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lactose intolerance is the subject, medical examination is the predicate, and chromatography is the object constitutes an accurate semantic relation.

6281it [21:02,  5.10it/s]

false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary tract infection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6282it [21:03,  4.93it/s]

true
Determine whether the semantic relation where pefloxacin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6284it [21:03,  4.98it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thoracic aortic aneurysm is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6285it [21:03,  5.13it/s]

true
Determine whether the semantic relation where problem gambling is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

6286it [21:04,  4.84it/s]

true
Determine whether the semantic relation where chylous ascites is the subject, subclass of is the predicate, and vascular disease is the object constitutes an accurate semantic relation.

6288it [21:04,  4.96it/s]

false
Determine whether the semantic relation where interleukin-3 receptor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and barium is the object constitutes an accurate semantic relation.

6289it [21:04,  4.84it/s]

false
Determine whether the semantic relation where cataract is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

6291it [21:05,  4.86it/s]

false
Determine whether the semantic relation where tumor of testis and paratestis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BAK1 is the subject, expressed in is the predicate, and spleen is the object constitutes an accurate semantic relation.

6293it [21:05,  5.08it/s]

false
Determine whether the semantic relation where insomnia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trypanosomiasis is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

6295it [21:05,  4.85it/s]

false
Determine whether the semantic relation where benzylpenicillin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where soft tissue neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6297it [21:06,  4.98it/s]

true
Determine whether the semantic relation where carboxymethyl cellulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where injury is the subject, drug or therapy used for treatment is the predicate, and oxycodone is the object constitutes an accurate semantic relation.

6298it [21:06,  5.00it/s]

false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

6300it [21:06,  5.02it/s]

true
Determine whether the semantic relation where tyramine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxycodone is the subject, medical condition treated is the predicate, and injury is the object constitutes an accurate semantic relation.

6302it [21:07,  5.05it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where iopanoic acid is the subject, subject has role is the predicate, and radiopharmaceutical is the object constitutes an accurate semantic relation.

6304it [21:07,  5.17it/s]

true
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bronchopneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6306it [21:08,  5.27it/s]

true
Determine whether the semantic relation where MPL proto-oncogene, thrombopoietin receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

6308it [21:08,  5.04it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where triamcinolone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6310it [21:08,  4.95it/s]

true
Determine whether the semantic relation where Lycopersicon esculentum is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

6311it [21:09,  5.03it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

6312it [21:09,  4.99it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

6314it [21:09,  5.07it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where parkinsonian syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6316it [21:10,  5.19it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

6318it [21:10,  5.28it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amyloid P component, serum is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

6320it [21:10,  5.37it/s]

false
Determine whether the semantic relation where yttrium chloride is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

6322it [21:11,  5.04it/s]

false
Determine whether the semantic relation where neurturin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF receptor superfamily member 25 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6324it [21:11,  4.53it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

6326it [21:12,  4.90it/s]

true
Determine whether the semantic relation where arbutin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glucagon is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

6327it [21:12,  5.08it/s]

false
Determine whether the semantic relation where autocrine motility factor receptor is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

6328it [21:12,  4.99it/s]

false
Determine whether the semantic relation where plague is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6330it [21:12,  5.11it/s]

true
Determine whether the semantic relation where benzocaine is the subject, medical condition treated is the predicate, and herpes simplex is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where herpes simplex is the subject, drug or therapy used for treatment is the predicate, and benzocaine is the object constitutes an accurate semantic relation.

6332it [21:13,  5.17it/s]

false
Determine whether the semantic relation where Lactuca sativa is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where estrogen receptor 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6333it [21:13,  5.29it/s]

false
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6335it [21:13,  5.18it/s]

true
Determine whether the semantic relation where cisapride is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glutamate carboxypeptidase II is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6337it [21:14,  5.20it/s]

false
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and cisapride is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protochlorophyllide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6339it [21:14,  5.24it/s]

false
Determine whether the semantic relation where opisthorchiasis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iraq War is the subject, has cause is the predicate, and human rights is the object constitutes an accurate semantic relation.

6340it [21:14,  5.17it/s]

false
Determine whether the semantic relation where glycogen phosphorylase, muscle associated is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6342it [21:15,  4.93it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

6343it [21:15,  4.94it/s]

false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6344it [21:15,  4.65it/s]

maybe
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Gossypium is the object constitutes an accurate semantic relation.

6346it [21:16,  4.85it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Potassium voltage-gated channel subfamily Q member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6347it [21:16,  4.75it/s]

false
Determine whether the semantic relation where inositol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

6349it [21:16,  4.86it/s]

false
Determine whether the semantic relation where L-isoleucine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tricuspid valve stenosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6350it [21:16,  4.89it/s]

true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

6351it [21:17,  4.76it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

6353it [21:17,  4.99it/s]

true
Determine whether the semantic relation where grounded theory is the subject, instance of is the predicate, and scientific method is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myofascial pain syndrome is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

6355it [21:17,  5.09it/s]

maybe
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

6356it [21:18,  5.12it/s]

true
Determine whether the semantic relation where L-selenocysteine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6358it [21:18,  4.98it/s]

true
Determine whether the semantic relation where platelet and endothelial cell adhesion molecule 1 is the subject, biological process is the predicate, and phagocytosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6360it [21:18,  5.00it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

6362it [21:19,  5.15it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 11 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

6364it [21:19,  5.04it/s]

false
Determine whether the semantic relation where parathyroid hormone 1 receptor is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and delirium is the object constitutes an accurate semantic relation.

6366it [21:20,  5.19it/s]

true
Determine whether the semantic relation where S-adenosylmethionine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where multiple sclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6367it [21:20,  4.52it/s]

true
Determine whether the semantic relation where aspergillosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6369it [21:20,  4.42it/s]

true
Determine whether the semantic relation where gynecomastia is the subject, has cause is the predicate, and malnutrition is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where respiratory tract infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6370it [21:21,  4.41it/s]

true
Determine whether the semantic relation where kidney failure is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6372it [21:21,  4.46it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

6374it [21:21,  4.82it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pancreatic polypeptide is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6376it [21:22,  5.13it/s]

true
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coronavirus disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6378it [21:22,  4.87it/s]

true
Determine whether the semantic relation where tetralogy of Fallot is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where molecular model is the subject, subclass of is the predicate, and physical model is the object constitutes an accurate semantic relation.

6380it [21:23,  5.18it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and cataract is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Chagas disease is the subject, symptoms and signs is the predicate, and hepatomegaly is the object constitutes an accurate semantic relation.

6382it [21:23,  5.29it/s]

true
Determine whether the semantic relation where Williams-Beuren syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

6384it [21:23,  5.13it/s]

false
Determine whether the semantic relation where Kawasaki disease is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where docosahexaenoic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6385it [21:24,  5.11it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6386it [21:24,  4.88it/s]

true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, drug or therapy used for treatment is the predicate, and prednisolone is the object constitutes an accurate semantic relation.

6388it [21:24,  4.90it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

6390it [21:25,  4.97it/s]

true
Determine whether the semantic relation where ariboflavinosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ariboflavinosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6392it [21:25,  4.95it/s]

true
Determine whether the semantic relation where gastroenteritis is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and gastroenteritis is the object constitutes an accurate semantic relation.

6393it [21:25,  5.04it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Russia is the object constitutes an accurate semantic relation.

6394it [21:25,  4.89it/s]

false
Determine whether the semantic relation where subdural empyema is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6396it [21:26,  4.96it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Xanthine dehydrogenase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6397it [21:26,  5.14it/s]

false
Determine whether the semantic relation where gold is the subject, instance of is the predicate, and allergen is the object constitutes an accurate semantic relation.

6399it [21:26,  4.86it/s]

false
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bromocriptine is the subject, has part(s) is the predicate, and bromine is the object constitutes an accurate semantic relation.

6401it [21:27,  5.04it/s]

false
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

6403it [21:27,  5.00it/s]

true
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, afflicts is the predicate, and lung is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cannabinoid receptor 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

6405it [21:28,  5.13it/s]

false
Determine whether the semantic relation where trimecaine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

6406it [21:28,  5.03it/s]

true
Determine whether the semantic relation where tyramine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6408it [21:28,  4.82it/s]

false
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where California encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6410it [21:29,  5.00it/s]

true
Determine whether the semantic relation where gamma wave is the subject, different from is the predicate, and gamma ray is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Lactuca sativa is the object constitutes an accurate semantic relation.

6411it [21:29,  4.91it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6413it [21:29,  4.89it/s]

false
Determine whether the semantic relation where gamma ray is the subject, different from is the predicate, and gamma wave is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KIT proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6415it [21:30,  5.07it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

6417it [21:30,  5.16it/s]

true
Determine whether the semantic relation where methanol is the subject, subject has role is the predicate, and neurotoxin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where internal carotid artery dissection is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6419it [21:30,  5.21it/s]

true
Determine whether the semantic relation where phenobarbital is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6420it [21:31,  5.37it/s]

true
Determine whether the semantic relation where inulin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6421it [21:31,  4.98it/s]

false
Determine whether the semantic relation where histiocytosis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

6423it [21:31,  5.01it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6424it [21:31,  4.87it/s]

false
Determine whether the semantic relation where osteoarthritis is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

6426it [21:32,  4.68it/s]

true
Determine whether the semantic relation where hearing disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Amphibia is the subject, main food source is the predicate, and Isopoda is the object constitutes an accurate semantic relation.

6427it [21:32,  4.87it/s]

false
Determine whether the semantic relation where adenomyosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6428it [21:32,  4.25it/s]

true
Determine whether the semantic relation where Chagas disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6429it [21:33,  4.43it/s]

true
Determine whether the semantic relation where prisoner of war is the subject, instance of is the predicate, and role is the object constitutes an accurate semantic relation.

6431it [21:33,  4.72it/s]

false
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

6432it [21:33,  4.83it/s]

true
Determine whether the semantic relation where Lesotho is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

6433it [21:33,  4.83it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

6434it [21:34,  4.75it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6436it [21:34,  4.84it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Lesotho is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where premenstrual syndrome is the subject, drug or therapy used for treatment is the predicate, and paracetamol is the object constitutes an accurate semantic relation.

6437it [21:34,  4.92it/s]

true
Determine whether the semantic relation where ranitidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6438it [21:34,  4.79it/s]

false
Determine whether the semantic relation where hepatic encephalopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6439it [21:35,  4.80it/s]

true
Determine whether the semantic relation where monosodium L-glutamate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6441it [21:35,  4.89it/s]

true
Determine whether the semantic relation where monosodium L-glutamate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6442it [21:35,  4.83it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

6444it [21:36,  5.04it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

6445it [21:36,  5.05it/s]

true
Determine whether the semantic relation where venous thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6447it [21:36,  4.89it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

6449it [21:37,  5.06it/s]

true
Determine whether the semantic relation where spinal cord injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

6451it [21:37,  5.08it/s]

true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

6452it [21:37,  4.91it/s]

true
Determine whether the semantic relation where Kleine-Levin syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

6453it [21:37,  4.92it/s]

true
Determine whether the semantic relation where Southeast Asia is the subject, country is the predicate, and United States is the object constitutes an accurate semantic relation.

6455it [21:38,  5.10it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and sweet potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Earth is the subject, has part(s) is the predicate, and Africa is the object constitutes an accurate semantic relation.

6456it [21:38,  5.10it/s]

true
Determine whether the semantic relation where Africa is the subject, part of is the predicate, and Earth is the object constitutes an accurate semantic relation.

6457it [21:38,  4.91it/s]

true
Determine whether the semantic relation where uracil is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6459it [21:39,  4.97it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bronchial neoplasm is the subject, subclass of is the predicate, and bronchospasm is the object constitutes an accurate semantic relation.

6461it [21:39,  5.17it/s]

false
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ETS transcription factor ELK1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

6462it [21:39,  5.28it/s]

false
Determine whether the semantic relation where procaine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6464it [21:40,  5.19it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

6466it [21:40,  5.21it/s]

true
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

6468it [21:40,  5.10it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thromboxane A synthase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

6470it [21:41,  5.20it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and muscle weakness is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fatigue is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

6472it [21:41,  5.25it/s]

false
Determine whether the semantic relation where (R)-mevalonic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

6473it [21:41,  5.15it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

6475it [21:42,  5.12it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Potassium voltage-gated channel subfamily Q member 1 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

6477it [21:42,  4.99it/s]

false
Determine whether the semantic relation where meibomian cyst is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blood plasma is the subject, has part(s) is the predicate, and table salt is the object constitutes an accurate semantic relation.

6479it [21:43,  5.32it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

6481it [21:43,  5.09it/s]

true
Determine whether the semantic relation where dirofilariasis is the subject, medical examination is the predicate, and medical imaging is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

6483it [21:43,  4.60it/s]

true
Determine whether the semantic relation where aphakia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where retinal neovascularization is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6484it [21:44,  4.85it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

6486it [21:44,  4.94it/s]

true
Determine whether the semantic relation where ficoll is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where galactosylceramidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

6488it [21:44,  5.12it/s]

true
Determine whether the semantic relation where Hong Kong is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystic fibrosis is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

6490it [21:45,  5.28it/s]

true
Determine whether the semantic relation where extrinsic allergic alveolitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

6492it [21:45,  5.29it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

6493it [21:45,  5.29it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

6495it [21:46,  4.72it/s]

false
Determine whether the semantic relation where couples therapy is the subject, instance of is the predicate, and health profession is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

6496it [21:46,  4.50it/s]

true
Determine whether the semantic relation where parasitic infectious diseases is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6497it [21:46,  4.51it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

6499it [21:47,  4.70it/s]

true
Determine whether the semantic relation where ergotamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

6501it [21:47,  4.99it/s]

true
Determine whether the semantic relation where 3-MCPD is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smallpox is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6502it [21:47,  5.09it/s]

true
Determine whether the semantic relation where meso-DAP is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6504it [21:48,  5.20it/s]

true
Determine whether the semantic relation where marker of proliferation Ki-67 is the subject, biological process is the predicate, and meiosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

6506it [21:48,  5.18it/s]

false
Determine whether the semantic relation where Lyme disease is the subject, symptoms and signs is the predicate, and vertigo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human sexual behavior is the subject, instance of is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.

6507it [21:48,  5.31it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, biological process is the predicate, and chemotaxis is the object constitutes an accurate semantic relation.

6509it [21:49,  5.19it/s]

true
Determine whether the semantic relation where protoporphyrins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KEL is the subject, expressed in is the predicate, and spleen is the object constitutes an accurate semantic relation.

6511it [21:49,  5.10it/s]

false
Determine whether the semantic relation where dyslexia is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Aconitase 1 is the subject, biological process is the predicate, and intestinal absorption is the object constitutes an accurate semantic relation.

6513it [21:49,  5.22it/s]

false
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

6515it [21:50,  5.25it/s]

true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

6516it [21:50,  5.15it/s]

true
Determine whether the semantic relation where person is the subject, has characteristic is the predicate, and pseudonym is the object constitutes an accurate semantic relation.

6517it [21:50,  5.06it/s]

true
Determine whether the semantic relation where melanocortin 1 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6518it [21:50,  4.73it/s]

true
Determine whether the semantic relation where adrenoceptor beta 3 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.

6519it [21:51,  4.46it/s]

true
Determine whether the semantic relation where acrylamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6520it [21:51,  4.43it/s]

true
Determine whether the semantic relation where elastin is the subject, biological process is the predicate, and blood circulation is the object constitutes an accurate semantic relation.

6522it [21:51,  4.78it/s]

false
Determine whether the semantic relation where porphobilinogen is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

6524it [21:52,  5.16it/s]

false
Determine whether the semantic relation where V-set domain containing T cell activation inhibitor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

6526it [21:52,  5.07it/s]

false
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where liver disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6527it [21:52,  5.12it/s]

true
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

6528it [21:52,  5.03it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

6530it [21:53,  5.00it/s]

true
Determine whether the semantic relation where rectal administration is the subject, instance of is the predicate, and route of administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

6532it [21:53,  5.35it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

6534it [21:54,  5.22it/s]

true
Determine whether the semantic relation where ureterocele is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where collagen disease is the subject, afflicts is the predicate, and lung is the object constitutes an accurate semantic relation.

6535it [21:54,  4.90it/s]

maybe
Determine whether the semantic relation where fatigue is the subject, has cause is the predicate, and malnutrition is the object constitutes an accurate semantic relation.

6537it [21:54,  4.98it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where renal tubular transport disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6539it [21:55,  5.26it/s]

false
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

6540it [21:55,  5.03it/s]

true
Determine whether the semantic relation where echinococcosis is the subject, anatomical location is the predicate, and kidney is the object constitutes an accurate semantic relation.

6541it [21:55,  4.85it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

6542it [21:55,  4.75it/s]

true
Determine whether the semantic relation where guanosine 5'-diphosphate (RRSR form) is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6543it [21:55,  4.75it/s]

true
Determine whether the semantic relation where kynurenic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6544it [21:56,  4.59it/s]

false
Determine whether the semantic relation where panuveitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6545it [21:56,  4.68it/s]

false
Determine whether the semantic relation where no reflow phenomenon is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

6547it [21:56,  4.94it/s]

false
Determine whether the semantic relation where guanosine 5'-diphosphate (RRSR form) is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fluphenazine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6549it [21:57,  4.98it/s]

false
Determine whether the semantic relation where hemifacial spasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium salicylate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6551it [21:57,  5.02it/s]

true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Janus kinase 2 is the subject, biological process is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.

6552it [21:57,  5.14it/s]

false
Determine whether the semantic relation where halothane is the subject, medical condition treated is the predicate, and asthma is the object constitutes an accurate semantic relation.

6554it [21:58,  5.19it/s]

false
Determine whether the semantic relation where asthma is the subject, drug or therapy used for treatment is the predicate, and halothane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mercury poisoning is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

6556it [21:58,  5.22it/s]

true
Determine whether the semantic relation where Utah is the subject, named after is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where antibiotic prophylaxis is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.

6558it [21:58,  5.34it/s]

true
Determine whether the semantic relation where L-threonine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.

6559it [21:59,  5.04it/s]

false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

6561it [21:59,  5.08it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where probucol is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

6562it [21:59,  5.18it/s]

false
Determine whether the semantic relation where stroke is the subject, drug or therapy used for treatment is the predicate, and pentoxifylline is the object constitutes an accurate semantic relation.

6564it [22:00,  4.92it/s]

false
Determine whether the semantic relation where Eastern equine encephalitis is the subject, medical examination is the predicate, and electroencephalography is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wilson disease is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

6566it [22:00,  4.60it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and probucol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where distomatosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6568it [22:01,  4.88it/s]

true
Determine whether the semantic relation where acetylcholine is the subject, found in taxon is the predicate, and black pepper is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Diclofenac is the subject, medical condition treated is the predicate, and fibromyalgia is the object constitutes an accurate semantic relation.

6570it [22:01,  5.13it/s]

false
Determine whether the semantic relation where Prostaglandin E receptor 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6571it [22:01,  5.04it/s]

true
Determine whether the semantic relation where Earth is the subject, has part(s) is the predicate, and Europe is the object constitutes an accurate semantic relation.

6572it [22:01,  4.82it/s]

true
Determine whether the semantic relation where Europe is the subject, part of is the predicate, and Earth is the object constitutes an accurate semantic relation.

6573it [22:02,  4.84it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

6574it [22:02,  4.76it/s]

true
Determine whether the semantic relation where carbamazepin is the subject, medical condition treated is the predicate, and post-traumatic stress disorder is the object constitutes an accurate semantic relation.

6575it [22:02,  4.64it/s]

false
Determine whether the semantic relation where post-traumatic stress disorder is the subject, drug or therapy used for treatment is the predicate, and carbamazepin is the object constitutes an accurate semantic relation.

6576it [22:02,  4.72it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.

6577it [22:02,  4.71it/s]

true
Determine whether the semantic relation where frontotemporal lobar degeneration is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

6578it [22:03,  4.64it/s]

true
Determine whether the semantic relation where tear gas is the subject, has effect is the predicate, and bleeding is the object constitutes an accurate semantic relation.

6580it [22:03,  4.78it/s]

false
Determine whether the semantic relation where Keratin 19 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

6582it [22:03,  5.07it/s]

false
Determine whether the semantic relation where brain abscess is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Behçet's disease is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

6583it [22:04,  5.17it/s]

true
Determine whether the semantic relation where ornithosis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

6585it [22:04,  5.07it/s]

true
Determine whether the semantic relation where triiodothyronine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Somalia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

6586it [22:04,  5.21it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Somalia is the object constitutes an accurate semantic relation.

6588it [22:05,  5.24it/s]

true
Determine whether the semantic relation where N-acetylneuraminic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where liver failure is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6590it [22:05,  5.26it/s]

true
Determine whether the semantic relation where interleukin enhancer binding factor 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspartame is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6591it [22:05,  5.27it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.

6592it [22:05,  5.06it/s]

true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true

6594it [22:06,  5.07it/s]

Determine whether the semantic relation where multiple myeloma is the subject, drug or therapy used for treatment is the predicate, and cisplatin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where candidiasis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

6595it [22:06,  5.01it/s]

maybe
Determine whether the semantic relation where blindness is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6597it [22:06,  4.94it/s]

false
Determine whether the semantic relation where cisplatin is the subject, medical condition treated is the predicate, and multiple myeloma is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichomoniasis is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

6599it [22:07,  4.72it/s]

maybe
Determine whether the semantic relation where endocarditis is the subject, health specialty is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where meclofenoxate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6601it [22:07,  4.99it/s]

false
Determine whether the semantic relation where nervous system lysosomal storage disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6602it [22:07,  5.18it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

6604it [22:08,  5.06it/s]

false
Determine whether the semantic relation where Indonesia is the subject, religion or worldview is the predicate, and Catholicism is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where embryonal rhabdomyosarcoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6606it [22:08,  5.07it/s]

true
Determine whether the semantic relation where proopiomelanocortin is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where obstructive lung disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6608it [22:09,  5.22it/s]

true
Determine whether the semantic relation where obstructive lung disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetraplegia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6609it [22:09,  5.20it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

6610it [22:09,  4.81it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6612it [22:09,  4.99it/s]

true
Determine whether the semantic relation where telencephalon is the subject, instance of is the predicate, and embryonic structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Epiregulin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6614it [22:10,  5.07it/s]

true
Determine whether the semantic relation where C-peptide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false

6615it [22:10,  5.14it/s]

Determine whether the semantic relation where chemically induced disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart disease is the subject, has contributing factor is the predicate, and obesity is the object constitutes an accurate semantic relation.

6616it [22:10,  5.21it/s]

true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6618it [22:11,  4.61it/s]

true
Determine whether the semantic relation where congenital cystic adenomatoid malformation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

6620it [22:11,  4.72it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Notch receptor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6621it [22:11,  4.84it/s]

true
Determine whether the semantic relation where thyroid gland disease is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

6623it [22:12,  4.87it/s]

false
Determine whether the semantic relation where intrauterine growth restriction is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hepatitis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

6624it [22:12,  4.73it/s]

true
Determine whether the semantic relation where eukaryotic translation initiation factor is the subject, found in taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.

6625it [22:12,  4.73it/s]

true
Determine whether the semantic relation where Vanuatu is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6626it [22:12,  4.72it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Vanuatu is the object constitutes an accurate semantic relation.

6627it [22:13,  4.73it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

6628it [22:13,  4.20it/s]

false
Determine whether the semantic relation where Mexico is the subject, member of is the predicate, and National Aeronautics and Space Administration is the object constitutes an accurate semantic relation.

6630it [22:13,  4.46it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, afflicts is the predicate, and skin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where toluene 2,4-diisocyanate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6631it [22:13,  4.70it/s]

true
Determine whether the semantic relation where cladribine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

6633it [22:14,  4.84it/s]

true
Determine whether the semantic relation where recurrent laryngeal nerve injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thrombopoietin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6635it [22:14,  5.14it/s]

true
Determine whether the semantic relation where The Bahamas is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetranitromethane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6636it [22:14,  5.31it/s]

true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

6637it [22:15,  5.04it/s]

false
Determine whether the semantic relation where trichuriasis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

6639it [22:15,  4.71it/s]

true
Determine whether the semantic relation where hydroxamic acid is the subject, subclass of is the predicate, and ketone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and The Bahamas is the object constitutes an accurate semantic relation.

6641it [22:15,  5.08it/s]

true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hazard analysis and critical control points is the subject, country of origin is the predicate, and United States is the object constitutes an accurate semantic relation.

6643it [22:16,  5.24it/s]

false
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mixed connective tissue disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

6645it [22:16,  5.14it/s]

true
Determine whether the semantic relation where clonorchiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adult-onset Still's disease is the subject, afflicts is the predicate, and spleen is the object constitutes an accurate semantic relation.

6647it [22:17,  5.26it/s]

true
Determine whether the semantic relation where CD40 molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where overweight is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

6649it [22:17,  5.21it/s]

false
Determine whether the semantic relation where teriparatide is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chitosan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6651it [22:17,  5.20it/s]

true
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and terfenadine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where terfenadine is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

6653it [22:18,  4.70it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebral hypoxia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6654it [22:18,  3.68it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

6656it [22:19,  4.29it/s]

true
Determine whether the semantic relation where remedial teaching is the subject, country is the predicate, and Belgium is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prostaglandin E2 is the subject, medical condition treated is the predicate, and uterine disease is the object constitutes an accurate semantic relation.

6657it [22:19,  4.62it/s]

false
Determine whether the semantic relation where glial fibrillary acidic protein is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

6659it [22:19,  4.78it/s]

false
Determine whether the semantic relation where Uridine phosphorylase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uterine disease is the subject, drug or therapy used for treatment is the predicate, and prostaglandin E2 is the object constitutes an accurate semantic relation.

6661it [22:20,  4.91it/s]

false
Determine whether the semantic relation where interleukin-15 receptor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where G protein subunit alpha i2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

6663it [22:20,  5.08it/s]

false
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phosphinic acids is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6665it [22:20,  5.00it/s]

true
Determine whether the semantic relation where luteinizing hormone subunit beta is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false

6666it [22:21,  5.16it/s]

Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

6667it [22:21,  4.63it/s]

true
Determine whether the semantic relation where cyanogen bromide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6669it [22:21,  4.86it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6670it [22:22,  4.56it/s]

true
Determine whether the semantic relation where peptide YY is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

6672it [22:22,  4.32it/s]

false
Determine whether the semantic relation where connective and soft tissue neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

6674it [22:22,  4.75it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where health impact assessment is the subject, subclass of is the predicate, and scientific method is the object constitutes an accurate semantic relation.

6676it [22:23,  4.84it/s]

true
Determine whether the semantic relation where acute respiratory distress syndrome is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sepsis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6677it [22:23,  4.31it/s]

true
Determine whether the semantic relation where hypoxia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6679it [22:24,  4.69it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

6681it [22:24,  5.16it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sacroiliitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6683it [22:24,  5.20it/s]

true
Determine whether the semantic relation where capsule opacification is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

6685it [22:25,  5.05it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

6687it [22:25,  4.96it/s]

true
Determine whether the semantic relation where diurnal enuresis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where selenious acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6688it [22:25,  4.83it/s]

true
Determine whether the semantic relation where tularemia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6690it [22:26,  4.80it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false

6691it [22:26,  4.90it/s]

Determine whether the semantic relation where postural orthostatic tachycardia syndrome is the subject, symptoms and signs is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where digitoxin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

6693it [22:26,  4.59it/s]

true
Determine whether the semantic relation where L-ornithine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

6695it [22:27,  4.82it/s]

true
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

6696it [22:27,  5.02it/s]

true
Determine whether the semantic relation where Armenia is the subject, official religion is the predicate, and Christianity is the object constitutes an accurate semantic relation.

6697it [22:27,  4.77it/s]

true
Determine whether the semantic relation where deafness is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6698it [22:27,  4.77it/s]

false
Determine whether the semantic relation where cerebrovascular disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6700it [22:28,  5.02it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 8 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Latin America is the object constitutes an accurate semantic relation.

6702it [22:28,  4.97it/s]

true
Determine whether the semantic relation where Latin America is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sea water is the subject, instance of is the predicate, and solution is the object constitutes an accurate semantic relation.

6704it [22:29,  4.11it/s]

true
Determine whether the semantic relation where chitin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major depressive disorder is the subject, has cause is the predicate, and genetics is the object constitutes an accurate semantic relation.

6705it [22:29,  4.32it/s]

true
Determine whether the semantic relation where hypophosphatemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6706it [22:29,  3.92it/s]

false
Determine whether the semantic relation where Lyme disease is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

6708it [22:30,  4.47it/s]

false
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where berberine is the subject, subject has role is the predicate, and aromatase inhibitors is the object constitutes an accurate semantic relation.

6710it [22:30,  4.84it/s]

false
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.

6712it [22:31,  5.01it/s]

true
Determine whether the semantic relation where dissociative identity disorder is the subject, medical examination is the predicate, and interview is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where insulin like growth factor 2 receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

6714it [22:31,  5.16it/s]

false
Determine whether the semantic relation where Netherlands Antilles is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

6716it [22:31,  5.22it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

6718it [22:32,  5.40it/s]

true
Determine whether the semantic relation where premature infant disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

6719it [22:32,  4.96it/s]

true
Determine whether the semantic relation where ifosfamide is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

6720it [22:32,  4.77it/s]

true
Determine whether the semantic relation where mucin 5B, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6721it [22:32,  4.80it/s]

false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

6722it [22:33,  4.67it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

6723it [22:33,  4.39it/s]

true
Determine whether the semantic relation where Korean War is the subject, participant is the predicate, and Canada is the object constitutes an accurate semantic relation.

6725it [22:33,  4.67it/s]

true
Determine whether the semantic relation where Coagulation factor II, thrombin is the subject, biological process is the predicate, and regulation of gene expression is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

6726it [22:33,  4.85it/s]

true
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

6727it [22:34,  4.85it/s]

true
Determine whether the semantic relation where tetanus is the subject, possible treatment is the predicate, and antipyretic is the object constitutes an accurate semantic relation.

6728it [22:34,  4.82it/s]

false
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

6729it [22:34,  4.71it/s]

false
Determine whether the semantic relation where chronic granulomatous disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

6730it [22:34,  4.75it/s]

true
Determine whether the semantic relation where bilirubin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6732it [22:35,  4.77it/s]

true
Determine whether the semantic relation where POU class 4 homeobox 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Abortion Applicants is the subject, subclass of is the predicate, and patient is the object constitutes an accurate semantic relation.

6734it [22:35,  4.92it/s]

true
Determine whether the semantic relation where traumatic subarachnoid hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aspiration pneumonia is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

6736it [22:35,  5.13it/s]

true
Determine whether the semantic relation where paracetamol is the subject, significant drug interaction is the predicate, and acenocoumarol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart valve disease is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

6737it [22:36,  5.22it/s]

false
Determine whether the semantic relation where Erdheim-Chester disease is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

6738it [22:36,  5.14it/s]

true
Determine whether the semantic relation where diverticulitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6740it [22:36,  5.16it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipid metabolism disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6742it [22:37,  5.05it/s]

true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

6743it [22:37,  5.18it/s]

false
Determine whether the semantic relation where chickenpox is the subject, medical examination is the predicate, and real-time polymerase chain reaction is the object constitutes an accurate semantic relation.

6744it [22:37,  5.10it/s]

false
Determine whether the semantic relation where asthma is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.

6746it [22:37,  5.13it/s]

false
Determine whether the semantic relation where proopiomelanocortin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where central nervous system trauma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6747it [22:38,  5.25it/s]

false
Determine whether the semantic relation where premenstrual dysphoric disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

6749it [22:38,  5.14it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kallikrein related peptidase 3 is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

6751it [22:38,  5.12it/s]

true
Determine whether the semantic relation where cerebral palsy is the subject, medical examination is the predicate, and medical ultrasonography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cor triatriatum is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6753it [22:39,  5.04it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adult T-cell leukemia/lymphoma is the subject, instance of is the predicate, and sexually transmitted infection is the object constitutes an accurate semantic relation.

6755it [22:39,  5.19it/s]

false
Determine whether the semantic relation where Behçet's disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where farmer's lung is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6757it [22:40,  5.14it/s]

true
Determine whether the semantic relation where coagulation factor V is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where immune system phenomenon is the subject, subclass of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.

6758it [22:40,  5.04it/s]

true
Determine whether the semantic relation where coarctation of the aorta is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

6759it [22:40,  4.80it/s]

true
Determine whether the semantic relation where ovotesticular disorder of sex development is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6761it [22:40,  4.80it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and (RS)-sulpiride is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-sulpiride is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

6762it [22:41,  4.95it/s]

true
Determine whether the semantic relation where KIT ligand is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6763it [22:41,  4.74it/s]

false
Determine whether the semantic relation where retinal artery occlusion is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

6764it [22:41,  4.63it/s]

true
Determine whether the semantic relation where Interleukin 12B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6765it [22:41,  4.72it/s]

true
Determine whether the semantic relation where hand, foot and mouth disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6767it [22:42,  4.89it/s]

true
Determine whether the semantic relation where azathioprine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acarbose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6769it [22:42,  4.93it/s]

false
Determine whether the semantic relation where Mauritania is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ephrin A4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6771it [22:42,  5.08it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Mauritania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

6773it [22:43,  4.99it/s]

false
Determine whether the semantic relation where urethral stricture is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxyquinoline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6774it [22:43,  5.08it/s]

true
Determine whether the semantic relation where spermine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6775it [22:43,  4.83it/s]

true
Determine whether the semantic relation where crystal violet is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

6777it [22:44,  4.70it/s]

true
Determine whether the semantic relation where Calbindin 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6778it [22:44,  4.93it/s]

true
Determine whether the semantic relation where Fabry disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6779it [22:44,  4.86it/s]

false
Determine whether the semantic relation where cytochrome P450 family 21 subfamily A member 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

6781it [22:45,  4.86it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coronary artery disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6782it [22:45,  4.99it/s]

true
Determine whether the semantic relation where Melatonin receptor 1A is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

6783it [22:45,  4.79it/s]

true
Determine whether the semantic relation where IKAROS family zinc finger 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6784it [22:45,  4.75it/s]

false
Determine whether the semantic relation where harmaline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

6786it [22:46,  4.80it/s]

false
Determine whether the semantic relation where opisthorchiasis is the subject, medical examination is the predicate, and microscopy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6787it [22:46,  4.98it/s]

false
Determine whether the semantic relation where Nuclear factor kappa B subunit 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6789it [22:46,  4.82it/s]

false
Determine whether the semantic relation where Fibroblast growth factor 4 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Lamin A/C is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

6790it [22:46,  4.80it/s]

false
Determine whether the semantic relation where osteoporosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6791it [22:47,  4.59it/s]

true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, subclass of is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

6793it [22:47,  4.82it/s]

false
Determine whether the semantic relation where solute carrier family 3 member 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hypothermia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6794it [22:47,  4.63it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

6796it [22:48,  4.82it/s]

false
Determine whether the semantic relation where taurine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and metitepine is the object constitutes an accurate semantic relation.

6798it [22:48,  5.07it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Belize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chronic pancreatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6800it [22:48,  5.19it/s]

true
Determine whether the semantic relation where insomnia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fabry disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6801it [22:49,  5.24it/s]

true
Determine whether the semantic relation where Sly syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6803it [22:49,  5.01it/s]

true
Determine whether the semantic relation where Belize is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where saccharin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6804it [22:49,  5.04it/s]

true
Determine whether the semantic relation where haptic perception is the subject, uses is the predicate, and temperature is the object constitutes an accurate semantic relation.

6806it [22:50,  5.09it/s]

false
Determine whether the semantic relation where autophagy is the subject, found in taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where biofilm is the subject, subclass of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

6808it [22:50,  5.21it/s]

false
Determine whether the semantic relation where drug discovery is the subject, subclass of is the predicate, and biochemistry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toxemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6809it [22:50,  5.11it/s]

true
Determine whether the semantic relation where gum arabic is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6810it [22:50,  5.00it/s]

false
Determine whether the semantic relation where risperidone is the subject, subject has role is the predicate, and H1 antagonist is the object constitutes an accurate semantic relation.
true

6811it [22:51,  4.98it/s]

Determine whether the semantic relation where Protein C, inactivator of coagulation factors Va and VIIIa is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6812it [22:51,  4.93it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

6813it [22:51,  4.89it/s]

true
Determine whether the semantic relation where bacterial eye infection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6815it [22:51,  4.81it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where autoimmune disease is the subject, has effect is the predicate, and nodding disease is the object constitutes an accurate semantic relation.

6817it [22:52,  5.08it/s]

false
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hereditary haemochromatosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6819it [22:52,  5.14it/s]

maybe
Determine whether the semantic relation where prochlorperazine is the subject, medical condition treated is the predicate, and dementia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nodding disease is the subject, has cause is the predicate, and autoimmune disease is the object constitutes an accurate semantic relation.

6821it [22:53,  5.26it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

6822it [22:53,  5.29it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6824it [22:53,  5.21it/s]

true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

6825it [22:53,  5.24it/s]

true
Determine whether the semantic relation where glucaric acid is the subject, subclass of is the predicate, and fatty acid is the object constitutes an accurate semantic relation.

6826it [22:54,  5.13it/s]

false
Determine whether the semantic relation where glycopeptide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6828it [22:54,  5.06it/s]

false
Determine whether the semantic relation where hypophyseal portal system is the subject, instance of is the predicate, and portal venous system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypophyseal portal system is the subject, subclass of is the predicate, and portal venous system is the object constitutes an accurate semantic relation.

6830it [22:54,  5.29it/s]

true
Determine whether the semantic relation where neurofibromatosis type II is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyproheptadine is the subject, medical condition treated is the predicate, and schizophrenia is the object constitutes an accurate semantic relation.

6831it [22:55,  5.34it/s]

false
Determine whether the semantic relation where lincomycin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6832it [22:55,  5.07it/s]

true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, biological process is the predicate, and vasodilation is the object constitutes an accurate semantic relation.

6833it [22:55,  4.21it/s]

false
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

6835it [22:56,  4.51it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

6836it [22:56,  4.79it/s]

true
Determine whether the semantic relation where acute respiratory distress syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6837it [22:56,  4.74it/s]

true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6839it [22:56,  4.88it/s]

false
Determine whether the semantic relation where liver disease is the subject, subclass of is the predicate, and endocrine system disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paratyphoid fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

6841it [22:57,  5.01it/s]

false
Determine whether the semantic relation where vertebrobasilar insufficiency is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastroesophageal reflux disease is the subject, drug or therapy used for treatment is the predicate, and isosorbide is the object constitutes an accurate semantic relation.

6843it [22:57,  5.07it/s]

false
Determine whether the semantic relation where isosorbide is the subject, medical condition treated is the predicate, and gastroesophageal reflux disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

6845it [22:57,  5.23it/s]

true
Determine whether the semantic relation where panic disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6846it [22:58,  5.16it/s]

false
Determine whether the semantic relation where tumor protein p53 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

6848it [22:58,  4.88it/s]

false
Determine whether the semantic relation where brain abscess is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where atrial heart septal defect is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

6850it [22:59,  5.00it/s]

false
Determine whether the semantic relation where Methylmalonyl-CoA mutase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pancreatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6852it [22:59,  4.75it/s]

true
Determine whether the semantic relation where diabetic neuropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lovastatin is the subject, significant drug interaction is the predicate, and lopinavir is the object constitutes an accurate semantic relation.

6853it [22:59,  4.93it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

6854it [22:59,  4.93it/s]

true
Determine whether the semantic relation where autoimmune disease of the nervous system is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

6856it [23:00,  4.88it/s]

false
Determine whether the semantic relation where rupture is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where methylenetetrahydrofolate reductase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

6858it [23:00,  4.99it/s]

false
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, route of administration is the predicate, and Q10268830 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

6860it [23:01,  5.21it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

6862it [23:01,  5.09it/s]

true
Determine whether the semantic relation where Cathepsin B is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

6864it [23:01,  5.27it/s]

true
Determine whether the semantic relation where peptidoglycan is the subject, subclass of is the predicate, and biopolymer is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bites and stings is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6866it [23:02,  5.20it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 11b is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

6868it [23:02,  5.21it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

6870it [23:02,  5.22it/s]

true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where High mobility group box 1 is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

6871it [23:03,  5.29it/s]

false
Determine whether the semantic relation where aspirin is the subject, has use is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

6872it [23:03,  4.95it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, has natural reservoir is the predicate, and Q25916 is the object constitutes an accurate semantic relation.

6874it [23:03,  5.06it/s]

true
Determine whether the semantic relation where polysaccharide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Legg–Calvé–Perthes disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

6876it [23:04,  5.10it/s]

true
Determine whether the semantic relation where human is the subject, has characteristic is the predicate, and full name is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where wrist injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6878it [23:04,  5.28it/s]

false
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and human digestive system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tear is the subject, has part(s) is the predicate, and water is the object constitutes an accurate semantic relation.

6879it [23:04,  5.25it/s]

true
Determine whether the semantic relation where hand washing is the subject, instance of is the predicate, and grooming behavior is the object constitutes an accurate semantic relation.

6881it [23:05,  4.91it/s]

true
Determine whether the semantic relation where oxime is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Amidophosphoribosyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

6883it [23:05,  5.16it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium oxybate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6885it [23:05,  5.28it/s]

true
Determine whether the semantic relation where leiomyoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

6887it [23:06,  5.34it/s]

true
Determine whether the semantic relation where Thy-1 cell surface antigen is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ruptured aneurysm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6889it [23:06,  5.00it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

6891it [23:07,  4.90it/s]

true
Determine whether the semantic relation where urogenital tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where irritable bowel syndrome is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

6893it [23:07,  4.63it/s]

false
Determine whether the semantic relation where Melkersson-Rosenthal syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nerve compression syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

6895it [23:08,  4.92it/s]

true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intracranial aneurysm is the subject, symptoms and signs is the predicate, and mental confusion is the object constitutes an accurate semantic relation.

6897it [23:08,  5.09it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6898it [23:08,  5.14it/s]

false
Determine whether the semantic relation where CD44 molecule (Indian blood group) is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

6900it [23:08,  5.08it/s]

false
Determine whether the semantic relation where North America is the subject, country is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where melena is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

6901it [23:09,  4.90it/s]

false
Determine whether the semantic relation where butyrolactone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

6903it [23:09,  5.06it/s]

true
Determine whether the semantic relation where Scutellaria baicalensis is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.

6904it [23:09,  4.79it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, G is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

6905it [23:10,  4.59it/s]

false
Determine whether the semantic relation where human is the subject, studied by is the predicate, and anthropology is the object constitutes an accurate semantic relation.

6906it [23:10,  4.36it/s]

true
Determine whether the semantic relation where cheilitis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

6907it [23:10,  4.39it/s]

true
Determine whether the semantic relation where cheilitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

6909it [23:10,  4.59it/s]

true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, disease transmission process is the predicate, and organ transplantation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where physical phenomenon is the subject, part of is the predicate, and nature is the object constitutes an accurate semantic relation.

6911it [23:11,  4.98it/s]

false
Determine whether the semantic relation where Q21173788 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q21173788 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

6913it [23:11,  5.15it/s]

true
Determine whether the semantic relation where psoriasis is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

6915it [23:12,  5.24it/s]

true
Determine whether the semantic relation where apigenin is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carrageenan is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

6917it [23:12,  5.10it/s]

false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

6918it [23:12,  4.90it/s]

false
Determine whether the semantic relation where prodigiosin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

6920it [23:13,  4.83it/s]

false
Determine whether the semantic relation where bemegride is the subject, subject has role is the predicate, and respiratory system agents is the object constitutes an accurate semantic relation.
false

6921it [23:13,  4.88it/s]

Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and transport vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where LIF receptor subunit alpha is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

6923it [23:13,  5.04it/s]

true
Determine whether the semantic relation where kidney papillary necrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where brucellosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

6925it [23:14,  5.18it/s]

true
Determine whether the semantic relation where histamine N-methyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where airway management is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

6926it [23:14,  4.81it/s]

false
Determine whether the semantic relation where constrictive pericarditis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

6928it [23:14,  4.63it/s]

true
Determine whether the semantic relation where hepatitis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peroxisomal disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

6930it [23:15,  5.08it/s]

false
Determine whether the semantic relation where bovine spongiform encephalopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipoblastoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6932it [23:15,  5.19it/s]

true
Determine whether the semantic relation where yellow fever is the subject, medical examination is the predicate, and immunohistochemistry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tajikistan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6934it [23:15,  5.02it/s]

true
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where interleukin-2 is the subject, subject has role is the predicate, and non-opioid analgesic is the object constitutes an accurate semantic relation.

6936it [23:16,  4.83it/s]

false
Determine whether the semantic relation where Na+/K+-ATPase is the subject, found in taxon is the predicate, and animal is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where epidemiology is the subject, is the study of is the predicate, and pandemic is the object constitutes an accurate semantic relation.

6938it [23:16,  5.06it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.

6940it [23:17,  5.05it/s]

true
Determine whether the semantic relation where AMP deaminase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, risk factor is the predicate, and heart failure is the object constitutes an accurate semantic relation.

6942it [23:17,  5.19it/s]

false
Determine whether the semantic relation where thrombophilia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where flail chest is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6944it [23:17,  5.24it/s]

false
Determine whether the semantic relation where chromosomal disease is the subject, has cause is the predicate, and pathology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where receptor activity modifying protein 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

6945it [23:18,  5.33it/s]

true
Determine whether the semantic relation where sucrose is the subject, found in taxon is the predicate, and Q132557 is the object constitutes an accurate semantic relation.

6947it [23:18,  5.04it/s]

false
Determine whether the semantic relation where CNS demyelinating autoimmune diseases is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true

6948it [23:18,  5.13it/s]

Determine whether the semantic relation where radiation-induced abnormality is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where soman is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

6950it [23:19,  5.24it/s]

false
Determine whether the semantic relation where knee dislocation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

6952it [23:19,  5.22it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

6954it [23:19,  5.13it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where probiotics is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.

6956it [23:20,  5.20it/s]

false
Determine whether the semantic relation where busulfan is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.

6958it [23:20,  5.30it/s]

true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

6960it [23:21,  5.09it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

6962it [23:21,  5.09it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6964it [23:21,  5.09it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyhydramnios is the subject, health specialty is the predicate, and obstetrics is the object constitutes an accurate semantic relation.

6966it [23:22,  5.23it/s]

false
Determine whether the semantic relation where Calcitonin receptor is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where soybean is the subject, endemic to is the predicate, and Zambia is the object constitutes an accurate semantic relation.

6967it [23:22,  5.12it/s]

false
Determine whether the semantic relation where leprosy is the subject, subclass of is the predicate, and testicular disease is the object constitutes an accurate semantic relation.

6969it [23:22,  5.08it/s]

false
Determine whether the semantic relation where insomnia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Valeriana officinalis is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

6970it [23:23,  4.96it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, afflicts is the predicate, and circulatory system is the object constitutes an accurate semantic relation.

6972it [23:23,  4.65it/s]

false
Determine whether the semantic relation where listeriosis is the subject, health specialty is the predicate, and neonatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where insulin coma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6974it [23:23,  4.92it/s]

true
Determine whether the semantic relation where female organism is the subject, subclass of is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where azacitidine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

6975it [23:24,  5.06it/s]

false
Determine whether the semantic relation where El Salvador is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

6977it [23:24,  4.93it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and El Salvador is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clinical trial is the subject, participant is the predicate, and patient is the object constitutes an accurate semantic relation.

6979it [23:24,  5.25it/s]

false
Determine whether the semantic relation where quercetin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

6981it [23:25,  5.16it/s]

true
Determine whether the semantic relation where fungi is the subject, parent taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dyscalculia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6983it [23:25,  5.05it/s]

true
Determine whether the semantic relation where omeprazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plant is the subject, parent taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.

6985it [23:26,  4.59it/s]

false
Determine whether the semantic relation where animal is the subject, parent taxon is the predicate, and eukaryote is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ceftriaxone is the subject, medical condition treated is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.

6987it [23:26,  4.93it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where endometriosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

6988it [23:26,  5.09it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

6989it [23:26,  4.94it/s]

true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and cranial trauma is the object constitutes an accurate semantic relation.

6991it [23:27,  4.42it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myalgic encephalomyelitis/chronic fatigue syndrome is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

6992it [23:27,  4.57it/s]

false
Determine whether the semantic relation where Nuclear receptor corepressor 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

6993it [23:27,  4.66it/s]

true
Determine whether the semantic relation where female reproductive system disease is the subject, drug or therapy used for treatment is the predicate, and ceftriaxone is the object constitutes an accurate semantic relation.

6995it [23:28,  4.71it/s]

true
Determine whether the semantic relation where piroxicam is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where disease is the subject, studied by is the predicate, and pathology is the object constitutes an accurate semantic relation.

6997it [23:28,  5.10it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paucibacillary leprosy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

6999it [23:29,  5.25it/s]

true
Determine whether the semantic relation where sirolimus is the subject, subject has role is the predicate, and antibiotic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urinary incontinence is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7000it [23:29,  5.12it/s]

true
Determine whether the semantic relation where Marburg virus disease is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

7002it [23:29,  4.92it/s]

false
Determine whether the semantic relation where focal segmental glomerulosclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bacterial infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7003it [23:29,  5.08it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

7005it [23:30,  4.97it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where potato is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

7007it [23:30,  4.99it/s]

false
Determine whether the semantic relation where behavior is the subject, found in taxon is the predicate, and animal is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dog is the subject, has use is the predicate, and therapy is the object constitutes an accurate semantic relation.

7009it [23:31,  5.22it/s]

true
Determine whether the semantic relation where bipolar disorder is the subject, symptoms and signs is the predicate, and aphasia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where scrub typhus is the subject, anatomical location is the predicate, and lymph node is the object constitutes an accurate semantic relation.

7010it [23:31,  4.84it/s]

false
Determine whether the semantic relation where Endothelin 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7012it [23:31,  4.83it/s]

true
Determine whether the semantic relation where pyridoxine kinase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true

7013it [23:31,  4.94it/s]

Determine whether the semantic relation where municipal hospital is the subject, instance of is the predicate, and government agency is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, symptoms and signs is the predicate, and hypoxia is the object constitutes an accurate semantic relation.

7014it [23:32,  4.94it/s]

true
Determine whether the semantic relation where angiotensins is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

7015it [23:32,  4.89it/s]

false
Determine whether the semantic relation where organogold compound is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7016it [23:32,  4.79it/s]

true
Determine whether the semantic relation where goldfish is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

7018it [23:32,  4.93it/s]

false
Determine whether the semantic relation where glucagon is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where methylphenidate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7019it [23:33,  4.65it/s]

true
Determine whether the semantic relation where cholera toxin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

7021it [23:33,  4.87it/s]

true
Determine whether the semantic relation where giardiasis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where guanine deaminase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

7023it [23:33,  4.97it/s]

true
Determine whether the semantic relation where pentetrazol is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cutaneous fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7024it [23:34,  4.65it/s]

true
Determine whether the semantic relation where nicorandil is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7026it [23:34,  4.65it/s]

false
Determine whether the semantic relation where transient and migrant people is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Plasmodium falciparum malaria is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7027it [23:34,  3.97it/s]

true
Determine whether the semantic relation where AIDS dementia complex is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

7028it [23:35,  4.05it/s]

true
Determine whether the semantic relation where peritoneal macrophage is the subject, subclass of is the predicate, and histiocyte is the object constitutes an accurate semantic relation.

7030it [23:35,  4.43it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD5 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7031it [23:35,  4.65it/s]

true
Determine whether the semantic relation where diethylhexyl phthalate is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

7032it [23:36,  4.71it/s]

false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

7034it [23:36,  4.82it/s]

true
Determine whether the semantic relation where heart disease is the subject, symptoms and signs is the predicate, and ascites is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

7036it [23:36,  5.00it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

7038it [23:37,  5.05it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

7039it [23:37,  5.17it/s]

false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7041it [23:37,  5.02it/s]

true
Determine whether the semantic relation where mandibular fracture is the subject, health specialty is the predicate, and traumatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sporotrichosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7043it [23:38,  5.01it/s]

true
Determine whether the semantic relation where rhinitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral pneumonia is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

7045it [23:38,  4.98it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 15 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

7047it [23:38,  5.10it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where wild boar is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

7049it [23:39,  5.13it/s]

false
Determine whether the semantic relation where peripheral artery disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hodgkin lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7051it [23:39,  5.22it/s]

true
Determine whether the semantic relation where EPH receptor B4 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ondansetron is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

7053it [23:40,  5.34it/s]

true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and ondansetron is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart is the subject, found in taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7054it [23:40,  4.91it/s]

false
Determine whether the semantic relation where malnutrition is the subject, health specialty is the predicate, and intensive care medicine is the object constitutes an accurate semantic relation.

7055it [23:40,  4.83it/s]

false
Determine whether the semantic relation where vincamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7056it [23:40,  4.80it/s]

false
Determine whether the semantic relation where leukotriene a4 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7057it [23:40,  4.81it/s]

true
Determine whether the semantic relation where paraldehyde is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7058it [23:41,  4.83it/s]

true
Determine whether the semantic relation where TNF superfamily member 11 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7060it [23:41,  4.76it/s]

true
Determine whether the semantic relation where Interleukin 2 receptor subunit gamma is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenytoin is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

7061it [23:41,  4.67it/s]

false
Determine whether the semantic relation where phaeohyphomycosis is the subject, subclass of is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

7063it [23:42,  4.72it/s]

false
Determine whether the semantic relation where hepatocellular carcinoma is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptogenic organizing pneumonia is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7064it [23:42,  4.56it/s]

false
Determine whether the semantic relation where animal behavior is the subject, found in taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7066it [23:42,  4.67it/s]

false
Determine whether the semantic relation where dimethyltryptamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where animal is the subject, has characteristic is the predicate, and animal behavior is the object constitutes an accurate semantic relation.

7067it [23:43,  4.93it/s]

true
Determine whether the semantic relation where amoxicillin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7069it [23:43,  4.97it/s]

false
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paracoccidioidomycosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7070it [23:43,  5.13it/s]

true
Determine whether the semantic relation where medulloblastoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

7071it [23:43,  5.05it/s]

true
Determine whether the semantic relation where skeleton is the subject, part of is the predicate, and animal is the object constitutes an accurate semantic relation.
true

7073it [23:44,  5.09it/s]

Determine whether the semantic relation where aluminum hydroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system protozoal infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7075it [23:44,  4.78it/s]

true
Determine whether the semantic relation where tumor necrosis factor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascariasis is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.

7076it [23:44,  4.64it/s]

true
Determine whether the semantic relation where psoriatic arthritis is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

7078it [23:45,  4.65it/s]

false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and bumetanide is the object constitutes an accurate semantic relation.
maybe

7079it [23:45,  4.74it/s]

Determine whether the semantic relation where autocrine motility factor receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where osteoid osteoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7081it [23:46,  4.96it/s]

true
Determine whether the semantic relation where fetish is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quercetin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7083it [23:46,  5.00it/s]

false
Determine whether the semantic relation where L-isoleucine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Melkersson-Rosenthal syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

7084it [23:46,  5.14it/s]

true
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

7086it [23:46,  5.12it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

7088it [23:47,  5.21it/s]

true
Determine whether the semantic relation where (4RS)-4-hydroxy-DL-proline is the subject, subclass of is the predicate, and alkanolamine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

7089it [23:47,  5.21it/s]

true
Determine whether the semantic relation where chronobiology disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7091it [23:47,  5.22it/s]

false
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

7092it [23:48,  5.31it/s]

true
Determine whether the semantic relation where vascular headache is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7094it [23:48,  5.17it/s]

true
Determine whether the semantic relation where breast disease is the subject, health specialty is the predicate, and gynaecology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where microvascular angina is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

7096it [23:48,  4.82it/s]

true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

7098it [23:49,  4.94it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nialamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7099it [23:49,  5.11it/s]

true
Determine whether the semantic relation where angiotensin II receptor type 2 is the subject, biological process is the predicate, and exploration behavior is the object constitutes an accurate semantic relation.

7101it [23:49,  5.05it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where humpback whale is the subject, does not have part is the predicate, and tooth is the object constitutes an accurate semantic relation.

7103it [23:50,  5.09it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bovine trypanosomiasis is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

7105it [23:50,  5.17it/s]

true
Determine whether the semantic relation where E1A binding protein p300 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-thioctic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

7106it [23:50,  5.17it/s]

true
Determine whether the semantic relation where angiotensins is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7107it [23:51,  4.99it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

7108it [23:51,  4.81it/s]

true
Determine whether the semantic relation where South Korea is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

7109it [23:51,  4.62it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

7110it [23:51,  4.37it/s]

true
Determine whether the semantic relation where dysentery is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

7112it [23:52,  4.66it/s]

false
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

7114it [23:52,  4.87it/s]

true
Determine whether the semantic relation where polyphloretin phosphate is the subject, instance of is the predicate, and complex mixture is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cognitive disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

7115it [23:52,  4.97it/s]

false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

7116it [23:53,  4.89it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

7117it [23:53,  4.70it/s]

true
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7118it [23:53,  4.67it/s]

false
Determine whether the semantic relation where nerve sheath neoplasms is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7120it [23:53,  4.55it/s]

false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

7121it [23:54,  4.78it/s]

true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7123it [23:54,  4.71it/s]

true
Determine whether the semantic relation where Leydig cell tumor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

7124it [23:54,  4.49it/s]

false
Determine whether the semantic relation where solute carrier family 7 member 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7126it [23:55,  4.71it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

7127it [23:55,  4.85it/s]

true
Determine whether the semantic relation where puerperal infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7129it [23:55,  4.50it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine receptor 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where writing is the subject, used by is the predicate, and human is the object constitutes an accurate semantic relation.

7131it [23:56,  4.85it/s]

false
Determine whether the semantic relation where phospholipase is the subject, found in taxon is the predicate, and Plasmodium berghei is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paranasal sinus disease is the subject, drug or therapy used for treatment is the predicate, and cetirizine is the object constitutes an accurate semantic relation.

7133it [23:56,  4.63it/s]

false
Determine whether the semantic relation where cetirizine is the subject, medical condition treated is the predicate, and paranasal sinus disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

7134it [23:56,  4.81it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

7135it [23:57,  4.73it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

7136it [23:57,  4.73it/s]

true
Determine whether the semantic relation where opium is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7137it [23:57,  4.68it/s]

false
Determine whether the semantic relation where schizophyllan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7139it [23:58,  4.70it/s]

false
Determine whether the semantic relation where progesterone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where zinc sulfate is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

7140it [23:58,  4.92it/s]

true
Determine whether the semantic relation where LDL receptor related protein 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7141it [23:58,  4.90it/s]

false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

7142it [23:58,  4.48it/s]

true
Determine whether the semantic relation where diphtheria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7143it [23:59,  4.09it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

7144it [23:59,  4.14it/s]

true
Determine whether the semantic relation where L-glutamine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7145it [23:59,  4.35it/s]

false
Determine whether the semantic relation where electrode is the subject, connects with is the predicate, and vacuum is the object constitutes an accurate semantic relation.

7147it [23:59,  4.75it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where semen is the subject, natural product of taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7148it [24:00,  4.68it/s]

false
Determine whether the semantic relation where hypervitaminosis A is the subject, subclass of is the predicate, and overnutrition is the object constitutes an accurate semantic relation.

7149it [24:00,  4.48it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and mental disorder is the object constitutes an accurate semantic relation.

7150it [24:00,  4.42it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

7151it [24:00,  4.30it/s]

true
Determine whether the semantic relation where bites and stings is the subject, has cause is the predicate, and animal is the object constitutes an accurate semantic relation.

7152it [24:00,  4.47it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

7153it [24:01,  4.53it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

7155it [24:01,  4.64it/s]

true
Determine whether the semantic relation where Ebstein anomaly is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ebstein anomaly is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7157it [24:02,  4.80it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.

7159it [24:02,  4.90it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where touching (physically feeling) is the subject, contributing factor of is the predicate, and injury is the object constitutes an accurate semantic relation.

7160it [24:02,  4.89it/s]

false
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

7162it [24:03,  4.77it/s]

true
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

7163it [24:03,  5.01it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

7164it [24:03,  4.78it/s]

true
Determine whether the semantic relation where streptococcal infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7166it [24:03,  4.95it/s]

true
Determine whether the semantic relation where Coagulation factor XI is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peritonitis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

7167it [24:04,  4.91it/s]

false
Determine whether the semantic relation where animal structure is the subject, found in taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7169it [24:04,  4.93it/s]

false
Determine whether the semantic relation where Rotaviral gastroenteritis is the subject, has natural reservoir is the predicate, and animal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral encephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7171it [24:04,  5.10it/s]

true
Determine whether the semantic relation where xanthine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF receptor superfamily member 14 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7173it [24:05,  5.17it/s]

true
Determine whether the semantic relation where cantharidin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7174it [24:05,  5.05it/s]

true
Determine whether the semantic relation where Leydig cell tumor is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

7176it [24:05,  4.79it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phentermine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7178it [24:06,  4.87it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and imipramine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

7179it [24:06,  4.89it/s]

true
Determine whether the semantic relation where imipramine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

7181it [24:06,  5.01it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where semen collection is the subject, uses is the predicate, and animal is the object constitutes an accurate semantic relation.

7183it [24:07,  5.18it/s]

false
Determine whether the semantic relation where kidney disease is the subject, different from is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where retinal vein occlusion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7184it [24:07,  5.02it/s]

true
Determine whether the semantic relation where scrub typhus is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7185it [24:07,  4.97it/s]

true
Determine whether the semantic relation where Wiskott-Aldrich syndrome is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

7187it [24:08,  4.81it/s]

true
Determine whether the semantic relation where Histidine ammonia-lyase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

7188it [24:08,  4.73it/s]

false
Determine whether the semantic relation where abscisic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7190it [24:08,  4.88it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7191it [24:08,  4.90it/s]

false
Determine whether the semantic relation where venomous animal is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7193it [24:09,  4.60it/s]

true
Determine whether the semantic relation where trichloroacetic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where wing is the subject, part of is the predicate, and animal is the object constitutes an accurate semantic relation.

7195it [24:09,  4.78it/s]

true
Determine whether the semantic relation where zoo animals is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Placozoa is the subject, parent taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7197it [24:10,  4.89it/s]

true
Determine whether the semantic relation where L-threonine is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where genetically modified animal is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7198it [24:10,  4.99it/s]

true
Determine whether the semantic relation where Q110551902 is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7200it [24:10,  4.97it/s]

true
Determine whether the semantic relation where Q18960 is the subject, parent taxon is the predicate, and animal is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where wild animal is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7202it [24:11,  5.20it/s]

true
Determine whether the semantic relation where South Korea is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and antipyrine is the object constitutes an accurate semantic relation.

7203it [24:11,  5.38it/s]

false
Determine whether the semantic relation where invertebrate is the subject, parent taxon is the predicate, and animal is the object constitutes an accurate semantic relation.

7204it [24:11,  5.08it/s]

true
Determine whether the semantic relation where invertebrate is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7205it [24:11,  4.84it/s]

false
Determine whether the semantic relation where scabies is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

7206it [24:12,  4.80it/s]

true
Determine whether the semantic relation where antipyrine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

7208it [24:12,  4.99it/s]

true
Determine whether the semantic relation where lysergic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

7210it [24:12,  4.88it/s]

true
Determine whether the semantic relation where hemangioblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where domesticated animal is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7212it [24:13,  5.11it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

7214it [24:13,  5.14it/s]

true
Determine whether the semantic relation where lab-on-a-chip is the subject, subclass of is the predicate, and laboratory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dinosaur is the subject, subclass of is the predicate, and animal is the object constitutes an accurate semantic relation.

7216it [24:14,  5.31it/s]

true
Determine whether the semantic relation where molluscum contagiosum is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colipase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7218it [24:14,  5.02it/s]

true
Determine whether the semantic relation where islet amyloid polypeptide is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and smooth endoplasmic reticulum is the object constitutes an accurate semantic relation.

7220it [24:14,  5.28it/s]

false
Determine whether the semantic relation where Prostaglandin E receptor 2 (subtype EP2) is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholecystokinin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7222it [24:15,  5.36it/s]

false
Determine whether the semantic relation where clobetasol is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and clobetasol is the object constitutes an accurate semantic relation.

7224it [24:15,  5.17it/s]

true
Determine whether the semantic relation where artificial organ is the subject, has part(s) is the predicate, and organoid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where organoid is the subject, part of is the predicate, and artificial organ is the object constitutes an accurate semantic relation.

7225it [24:15,  5.02it/s]

false
Determine whether the semantic relation where Survival of motor neuron 2, centromeric is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

7227it [24:16,  5.00it/s]

false
Determine whether the semantic relation where Endothelin 3 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where geographic atrophy is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

7229it [24:16,  4.85it/s]

true
Determine whether the semantic relation where mucoproteins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where London is the subject, twinned administrative body is the predicate, and Moscow is the object constitutes an accurate semantic relation.

7231it [24:17,  5.05it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

7233it [24:17,  5.20it/s]

true
Determine whether the semantic relation where premature ventricular contraction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adaptive immune system is the subject, found in taxon is the predicate, and Q25241 is the object constitutes an accurate semantic relation.

7235it [24:17,  5.25it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and liver is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7237it [24:18,  5.27it/s]

false
Determine whether the semantic relation where osteopenia is the subject, risk factor is the predicate, and alcoholism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where caffeine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7238it [24:18,  5.29it/s]

true
Determine whether the semantic relation where premature heart beat is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7240it [24:18,  5.20it/s]

true
Determine whether the semantic relation where rheumatoid arthritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.

7241it [24:18,  5.26it/s]

true
Determine whether the semantic relation where portal hypertension is the subject, has cause is the predicate, and restrictive cardiomyopathy is the object constitutes an accurate semantic relation.

7242it [24:19,  5.17it/s]

true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7244it [24:19,  5.12it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-deoxy-D-glucose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7246it [24:19,  5.19it/s]

true
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where harmaline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7248it [24:20,  5.09it/s]

false
Determine whether the semantic relation where multiple sclerosis is the subject, medical examination is the predicate, and positron emission tomography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where RUNX family transcription factor 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

7250it [24:20,  5.06it/s]

false
Determine whether the semantic relation where asphyxia is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

7252it [24:21,  4.69it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic obstructive pulmonary disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7254it [24:21,  4.96it/s]

true
Determine whether the semantic relation where chronic obstructive pulmonary disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where formate-tetrahydrofolate ligase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

7255it [24:21,  4.99it/s]

true
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7257it [24:22,  5.14it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

7259it [24:22,  5.29it/s]

true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inflammatory bowel diseases is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

7260it [24:22,  5.16it/s]

true
Determine whether the semantic relation where erysipelas is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7261it [24:22,  4.96it/s]

true
Determine whether the semantic relation where thyroid-stimulating hormone is the subject, found in taxon is the predicate, and Q25241 is the object constitutes an accurate semantic relation.

7263it [24:23,  4.95it/s]

false
Determine whether the semantic relation where sodium is the subject, follows is the predicate, and neon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

7264it [24:23,  4.87it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

7266it [24:23,  4.81it/s]

true
Determine whether the semantic relation where gallic acid is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

7268it [24:24,  5.18it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3-MCPD is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

7270it [24:24,  4.65it/s]

true
Determine whether the semantic relation where France is the subject, located in or next to body of water is the predicate, and North Sea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Sea is the subject, country is the predicate, and France is the object constitutes an accurate semantic relation.

7272it [24:25,  4.86it/s]

false
Determine whether the semantic relation where North Sea is the subject, basin country is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where volunteer is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

7274it [24:25,  5.01it/s]

false
Determine whether the semantic relation where sternum is the subject, found in taxon is the predicate, and Q25241 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where propiolactone is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.

7276it [24:25,  5.06it/s]

true
Determine whether the semantic relation where growth hormone is the subject, found in taxon is the predicate, and Q25241 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aneurysm of heart is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7278it [24:26,  5.20it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

7280it [24:26,  5.14it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cataract is the subject, afflicts is the predicate, and Q25241 is the object constitutes an accurate semantic relation.

7281it [24:26,  5.12it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 24 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7283it [24:27,  4.91it/s]

true
Determine whether the semantic relation where urinary tract infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary tract infection is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7285it [24:27,  4.98it/s]

true
Determine whether the semantic relation where activin complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where caprolactam is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7287it [24:28,  5.00it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

7289it [24:28,  5.11it/s]

true
Determine whether the semantic relation where pleural empyema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

7290it [24:28,  5.18it/s]

true
Determine whether the semantic relation where ret proto-oncogene is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

7291it [24:29,  4.47it/s]

false
Determine whether the semantic relation where Dopamine receptor D3 is the subject, biological process is the predicate, and social behavior is the object constitutes an accurate semantic relation.

7293it [24:29,  4.84it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, possible treatment is the predicate, and steroid is the object constitutes an accurate semantic relation.

7295it [24:29,  4.93it/s]

true
Determine whether the semantic relation where buprenorphine is the subject, medical condition treated is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peripheral neuropathy is the subject, drug or therapy used for treatment is the predicate, and buprenorphine is the object constitutes an accurate semantic relation.

7297it [24:30,  4.98it/s]

false
Determine whether the semantic relation where cachexia is the subject, health specialty is the predicate, and internal medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gnathomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7299it [24:30,  5.22it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7300it [24:30,  5.32it/s]

true
Determine whether the semantic relation where systemic lupus erythematosus is the subject, named after is the predicate, and grey wolf is the object constitutes an accurate semantic relation.

7302it [24:31,  4.92it/s]

false
Determine whether the semantic relation where listeriosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where noma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7303it [24:31,  4.99it/s]

true
Determine whether the semantic relation where self-care is the subject, subclass of is the predicate, and protective factor is the object constitutes an accurate semantic relation.

7304it [24:31,  4.59it/s]

true
Determine whether the semantic relation where paradoxical embolism is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

7305it [24:31,  4.59it/s]

false
Determine whether the semantic relation where amebiasis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

7307it [24:32,  4.81it/s]

false
Determine whether the semantic relation where carnosine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where uroporphyrinogen decarboxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

7309it [24:32,  4.94it/s]

true
Determine whether the semantic relation where glycogen storage disease I is the subject, health specialty is the predicate, and genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

7311it [24:33,  5.15it/s]

true
Determine whether the semantic relation where Japan is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

7312it [24:33,  5.21it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

7313it [24:33,  5.05it/s]

true
Determine whether the semantic relation where aralkylamine N-acetyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7315it [24:33,  4.99it/s]

true
Determine whether the semantic relation where polydimethylsiloxane is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7317it [24:34,  4.97it/s]

true
Determine whether the semantic relation where luminol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

7318it [24:34,  5.09it/s]

Determine whether the semantic relation where chloroquine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where legionellosis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

7319it [24:34,  5.24it/s]

maybe
Determine whether the semantic relation where hypertensive encephalopathy is the subject, subclass of is the predicate, and encephalomyelitis is the object constitutes an accurate semantic relation.

7320it [24:34,  5.07it/s]

false
Determine whether the semantic relation where melanocortin 1 receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

7322it [24:35,  4.72it/s]

false
Determine whether the semantic relation where dissociative disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gonorrhea is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

7323it [24:35,  4.79it/s]

true
Determine whether the semantic relation where Synaptotagmin 2 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

7324it [24:35,  4.79it/s]

false
Determine whether the semantic relation where CD33 molecule is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

7326it [24:36,  4.78it/s]

false
Determine whether the semantic relation where crotoxin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

7328it [24:36,  4.82it/s]

true
Determine whether the semantic relation where Cathepsin D is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where histidine decarboxylase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

7329it [24:36,  4.57it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

7330it [24:37,  4.53it/s]

true
Determine whether the semantic relation where fatty liver disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7331it [24:37,  4.54it/s]

true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7332it [24:37,  4.56it/s]

false
Determine whether the semantic relation where heme oxygenase 1 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.

7333it [24:37,  3.98it/s]

false
Determine whether the semantic relation where bilins is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7335it [24:38,  4.33it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ghana is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

7336it [24:38,  4.52it/s]

true
Determine whether the semantic relation where decision theory is the subject, subclass of is the predicate, and behavioral sciences is the object constitutes an accurate semantic relation.

7337it [24:38,  4.62it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Ghana is the object constitutes an accurate semantic relation.

7338it [24:38,  4.69it/s]

false
Determine whether the semantic relation where cerebral palsy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7340it [24:39,  4.89it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and prednisone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prednisone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7342it [24:39,  4.83it/s]

true
Determine whether the semantic relation where uroporphyrinogen decarboxylase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yersiniosis is the subject, has natural reservoir is the predicate, and dog is the object constitutes an accurate semantic relation.

7344it [24:40,  4.93it/s]

false
Determine whether the semantic relation where D-glucouronic acid is the subject, subclass of is the predicate, and fatty acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diphtheria is the subject, drug or therapy used for treatment is the predicate, and ampicillin is the object constitutes an accurate semantic relation.

7346it [24:40,  4.94it/s]

false
Determine whether the semantic relation where endothelin 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ocular physiological phenomena is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

7348it [24:40,  5.12it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyarteritis nodosa is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7350it [24:41,  5.27it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where boutonneuse fever is the subject, has natural reservoir is the predicate, and Felidae is the object constitutes an accurate semantic relation.

7352it [24:41,  5.34it/s]

false
Determine whether the semantic relation where choline O-acetyltransferase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where protochlorophyllide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7353it [24:41,  5.32it/s]

true
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

7355it [24:42,  5.23it/s]

true
Determine whether the semantic relation where cholic acid is the subject, found in taxon is the predicate, and Pseudomonas aeruginosa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thymol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7357it [24:42,  4.49it/s]

true
Determine whether the semantic relation where adult-onset Still's disease is the subject, afflicts is the predicate, and liver is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

7358it [24:42,  4.71it/s]

true
Determine whether the semantic relation where adamantinoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7359it [24:43,  4.62it/s]

true
Determine whether the semantic relation where Citrus sinensis is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true

7361it [24:43,  4.87it/s]

Determine whether the semantic relation where placental abruption is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

7362it [24:43,  5.05it/s]

true
Determine whether the semantic relation where traumatic intracranial hemorrhage is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7364it [24:44,  4.93it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

7365it [24:44,  4.98it/s]

true
Determine whether the semantic relation where curcumin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7366it [24:44,  4.96it/s]

true
Determine whether the semantic relation where phenylephrine is the subject, medical condition treated is the predicate, and hemorrhoid is the object constitutes an accurate semantic relation.

7368it [24:44,  4.85it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Israel is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Pennsylvania is the subject, shares border with is the predicate, and Ontario is the object constitutes an accurate semantic relation.

7370it [24:45,  5.04it/s]

true
Determine whether the semantic relation where hemorrhoid is the subject, drug or therapy used for treatment is the predicate, and phenylephrine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemic typhus is the subject, symptoms and signs is the predicate, and tremor is the object constitutes an accurate semantic relation.

7371it [24:45,  5.09it/s]

true
Determine whether the semantic relation where Ontario is the subject, shares border with is the predicate, and Pennsylvania is the object constitutes an accurate semantic relation.

7372it [24:45,  4.70it/s]

false
Determine whether the semantic relation where mycobacterium infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7374it [24:46,  4.97it/s]

false
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Chile is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

7375it [24:46,  4.53it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

7377it [24:46,  4.83it/s]

true
Determine whether the semantic relation where public housing is the subject, country is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

7379it [24:47,  4.63it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lactase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7380it [24:47,  4.65it/s]

true
Determine whether the semantic relation where 5-methylcytosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7382it [24:47,  4.48it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and cisapride is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cisapride is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

7384it [24:48,  4.88it/s]

true
Determine whether the semantic relation where methylphenidate is the subject, significant drug interaction is the predicate, and procarbazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glanders is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7386it [24:48,  5.14it/s]

true
Determine whether the semantic relation where exoskeleton is the subject, subclass of is the predicate, and skeleton is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where body surface area is the subject, P642 is the predicate, and physiology is the object constitutes an accurate semantic relation.

7387it [24:48,  5.09it/s]

false
Determine whether the semantic relation where Gaucher's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7389it [24:49,  5.12it/s]

true
Determine whether the semantic relation where endemic typhus is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SRY is the subject, expressed in is the predicate, and islet of Langerhans is the object constitutes an accurate semantic relation.

7390it [24:49,  5.16it/s]

false
Determine whether the semantic relation where visual acuity is the subject, subclass of is the predicate, and aptitude is the object constitutes an accurate semantic relation.

7392it [24:49,  5.05it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Turkmenistan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oral cavity neoplasm is the subject, subclass of is the predicate, and digestive system neoplasm is the object constitutes an accurate semantic relation.

7394it [24:50,  5.29it/s]

true
Determine whether the semantic relation where Turkmenistan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where scleredema is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

7396it [24:50,  5.36it/s]

false
Determine whether the semantic relation where Cephalochordata is the subject, parent taxon is the predicate, and Q10915 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where iproniazid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7397it [24:50,  5.40it/s]

true
Determine whether the semantic relation where glomerulonephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7399it [24:51,  5.16it/s]

true
Determine whether the semantic relation where criminal is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Urochordata is the subject, parent taxon is the predicate, and Q10915 is the object constitutes an accurate semantic relation.

7400it [24:51,  5.18it/s]

false
Determine whether the semantic relation where bird is the subject, subclass of is the predicate, and Q25241 is the object constitutes an accurate semantic relation.

7401it [24:51,  4.95it/s]

false
Determine whether the semantic relation where Nuclear factor kappa B subunit 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

7403it [24:52,  5.02it/s]

false
Determine whether the semantic relation where nonvertebrate Chordata is the subject, subclass of is the predicate, and Q10915 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dendrite is the subject, different from is the predicate, and dendritic cell is the object constitutes an accurate semantic relation.

7404it [24:52,  5.15it/s]

true
Determine whether the semantic relation where dendritic cell is the subject, different from is the predicate, and dendrite is the object constitutes an accurate semantic relation.

7405it [24:52,  4.96it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

7406it [24:52,  4.77it/s]

false
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and (RS)-sulpiride is the object constitutes an accurate semantic relation.

7408it [24:53,  4.94it/s]

true
Determine whether the semantic relation where (RS)-sulpiride is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q25241 is the subject, parent taxon is the predicate, and Q10915 is the object constitutes an accurate semantic relation.

7410it [24:53,  5.12it/s]

true
Determine whether the semantic relation where Q25241 is the subject, subclass of is the predicate, and Q10915 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arteriosclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7412it [24:53,  5.12it/s]

true
Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

7414it [24:54,  5.18it/s]

false
Determine whether the semantic relation where Citrus sinensis is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q20986771 is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7415it [24:54,  5.21it/s]

true
Determine whether the semantic relation where sucrose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7416it [24:54,  5.01it/s]

true
Determine whether the semantic relation where St. Louis encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7418it [24:55,  4.89it/s]

true
Determine whether the semantic relation where Lymphocyte protein tyrosine kinase is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false

7419it [24:55,  5.09it/s]

Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7420it [24:55,  5.13it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

7422it [24:55,  5.09it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

7423it [24:56,  4.90it/s]

true
Determine whether the semantic relation where carbofuran is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7425it [24:56,  4.96it/s]

true
Determine whether the semantic relation where Coagulation factor XI is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

7427it [24:56,  5.03it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7428it [24:57,  5.03it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

7429it [24:57,  4.96it/s]

true
Determine whether the semantic relation where lysergic acid diethylamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7431it [24:57,  4.72it/s]

true
Determine whether the semantic relation where epidermolytic hyperkeratosis is the subject, drug or therapy used for treatment is the predicate, and urea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urea is the subject, medical condition treated is the predicate, and epidermolytic hyperkeratosis is the object constitutes an accurate semantic relation.

7433it [24:58,  4.97it/s]

false
Determine whether the semantic relation where pyogenic liver abscess is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

7435it [24:58,  5.17it/s]

true
Determine whether the semantic relation where cerebrotendinous xanthomatosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyrethrin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7436it [24:58,  4.75it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7438it [24:59,  4.76it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypothermia is the subject, symptoms and signs is the predicate, and hallucination is the object constitutes an accurate semantic relation.

7439it [24:59,  4.43it/s]

true
Determine whether the semantic relation where Usher syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7440it [24:59,  4.42it/s]

true
Determine whether the semantic relation where Usher syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7441it [24:59,  4.30it/s]

true
Determine whether the semantic relation where periodontitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7443it [25:00,  4.44it/s]

true
Determine whether the semantic relation where diabetic foot is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.

7444it [25:00,  4.37it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

7446it [25:01,  4.49it/s]

false
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nerve degeneration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7447it [25:01,  4.51it/s]

true
Determine whether the semantic relation where ascariasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

7448it [25:01,  4.57it/s]

true
Determine whether the semantic relation where fluoxetine is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

7449it [25:01,  4.62it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and fluoxetine is the object constitutes an accurate semantic relation.

7451it [25:02,  3.83it/s]

true
Determine whether the semantic relation where prosencephalon is the subject, instance of is the predicate, and embryonic structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

7453it [25:02,  4.45it/s]

false
Determine whether the semantic relation where intellectual disability is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fever is the subject, drug or therapy used for treatment is the predicate, and diflunisal is the object constitutes an accurate semantic relation.

7455it [25:03,  4.72it/s]

true
Determine whether the semantic relation where dopamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Janus kinase 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7457it [25:03,  5.03it/s]

true
Determine whether the semantic relation where thyroid hormone receptor alpha is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where saliva is the subject, different from is the predicate, and Salvia is the object constitutes an accurate semantic relation.

7458it [25:03,  5.06it/s]

true
Determine whether the semantic relation where osteonecrosis of the femoral head is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

7460it [25:04,  5.11it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

7462it [25:04,  5.05it/s]

true
Determine whether the semantic relation where arterial hypertension is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arterial hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7464it [25:04,  4.99it/s]

true
Determine whether the semantic relation where hypophosphatemic rickets is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lactase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

7466it [25:05,  5.03it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rotaviral gastroenteritis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

7468it [25:05,  5.18it/s]

false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sirtuin 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7469it [25:05,  5.25it/s]

false
Determine whether the semantic relation where fragile X syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

7470it [25:06,  5.15it/s]

false
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

7471it [25:06,  4.96it/s]

false
Determine whether the semantic relation where synovial membrane is the subject, subclass of is the predicate, and serous membrane is the object constitutes an accurate semantic relation.

7472it [25:06,  4.79it/s]

false
Determine whether the semantic relation where Wolff–Parkinson–White syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

7473it [25:06,  4.67it/s]

false
Determine whether the semantic relation where myalgic encephalomyelitis/chronic fatigue syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7475it [25:07,  4.63it/s]

maybe
Determine whether the semantic relation where trachoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon dioxide is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

7477it [25:07,  4.97it/s]

true
Determine whether the semantic relation where alpha-1-antitrypsin deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alpha-1-antitrypsin deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7478it [25:07,  5.13it/s]

true
Determine whether the semantic relation where West Nile fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

7479it [25:07,  5.01it/s]

true
Determine whether the semantic relation where carnosine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

7481it [25:08,  4.97it/s]

false
Determine whether the semantic relation where drug-induced dyskinesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where niacinamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7483it [25:08,  5.10it/s]

true
Determine whether the semantic relation where bluetongue disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hirundinidae is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

7484it [25:08,  4.84it/s]

true
Determine whether the semantic relation where homocystinuria is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

7486it [25:09,  4.98it/s]

true
Determine whether the semantic relation where ulnar nerve entrapment is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diphyllobothriasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

7488it [25:09,  4.98it/s]

true
Determine whether the semantic relation where central nervous system neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pregnenolone is the subject, found in taxon is the predicate, and Apiaceae is the object constitutes an accurate semantic relation.

7490it [25:10,  5.00it/s]

false
Determine whether the semantic relation where (±)-promethazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where antineoplastic protocols is the subject, subclass of is the predicate, and medical guideline is the object constitutes an accurate semantic relation.

7492it [25:10,  5.11it/s]

true
Determine whether the semantic relation where giardiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poly(methacrylic acid) is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7494it [25:10,  5.04it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

7496it [25:11,  5.19it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where educational measurement is the subject, facet of is the predicate, and parenting is the object constitutes an accurate semantic relation.

7497it [25:11,  4.40it/s]

false
Determine whether the semantic relation where dextroamphetamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7499it [25:12,  4.71it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

7501it [25:12,  5.00it/s]

true
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where crystallin alpha A is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

7502it [25:12,  5.01it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Porphyridium is the object constitutes an accurate semantic relation.

7503it [25:12,  4.89it/s]

false
Determine whether the semantic relation where leprosy is the subject, subclass of is the predicate, and eye disease is the object constitutes an accurate semantic relation.

7505it [25:13,  4.84it/s]

false
Determine whether the semantic relation where otitis externa is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

7506it [25:13,  4.80it/s]

true
Determine whether the semantic relation where alpha-linolenic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7507it [25:13,  4.37it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

7509it [25:14,  4.37it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hallux rigidus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7511it [25:14,  4.46it/s]

true
Determine whether the semantic relation where catastrophic illness is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pipemidic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7512it [25:14,  4.59it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

7513it [25:15,  3.89it/s]

true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

7515it [25:15,  4.44it/s]

true
Determine whether the semantic relation where CD14 molecule is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7516it [25:15,  4.71it/s]

true
Determine whether the semantic relation where cefotaxime is the subject, medical condition treated is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.

7517it [25:15,  4.71it/s]

maybe
Determine whether the semantic relation where nitrofurantoin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7518it [25:16,  4.35it/s]

true
Determine whether the semantic relation where female reproductive system disease is the subject, drug or therapy used for treatment is the predicate, and cefotaxime is the object constitutes an accurate semantic relation.

7519it [25:16,  4.46it/s]

maybe
Determine whether the semantic relation where chronic myelomonocytic leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7521it [25:16,  4.55it/s]

true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Q41350 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where p-menthan-3-ol is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

7523it [25:17,  4.86it/s]

false
Determine whether the semantic relation where World War I is the subject, location is the predicate, and Africa is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where World War I is the subject, located in/on physical feature is the predicate, and Africa is the object constitutes an accurate semantic relation.

7525it [25:17,  5.01it/s]

false
Determine whether the semantic relation where occupational disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where occupational disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7527it [25:18,  5.14it/s]

true
Determine whether the semantic relation where Belize is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyclin dependent kinase inhibitor 2A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7529it [25:18,  5.12it/s]

true
Determine whether the semantic relation where mesothelioma is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Joining chain of multimeric IgA and IgM is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

7530it [25:18,  5.14it/s]

false
Determine whether the semantic relation where indomethacin is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

7531it [25:18,  4.75it/s]

false
Determine whether the semantic relation where seasonal affective disorder is the subject, subclass of is the predicate, and psychosomatic disease is the object constitutes an accurate semantic relation.

7533it [25:19,  4.64it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wilson disease is the subject, has cause is the predicate, and genetics is the object constitutes an accurate semantic relation.

7534it [25:19,  4.85it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

7536it [25:19,  4.78it/s]

true
Determine whether the semantic relation where hemolytic-uremic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ATP binding cassette subfamily B member 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

7538it [25:20,  4.86it/s]

false
Determine whether the semantic relation where Taenia solium is the subject, habitat is the predicate, and small intestine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperlipoproteinemia type IV is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

7539it [25:20,  4.67it/s]

false
Determine whether the semantic relation where agmatine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7541it [25:21,  4.75it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

7542it [25:21,  4.90it/s]

true
Determine whether the semantic relation where orotic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7543it [25:21,  4.63it/s]

true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

7544it [25:21,  4.25it/s]

true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

7546it [25:22,  4.66it/s]

true
Determine whether the semantic relation where glycine is the subject, has use is the predicate, and Q4368298 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smallpox is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

7548it [25:22,  4.99it/s]

true
Determine whether the semantic relation where smallpox is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paraldehyde is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7550it [25:22,  5.14it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

7552it [25:23,  4.73it/s]

true
Determine whether the semantic relation where intracranial aneurysm is the subject, symptoms and signs is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
false

7553it [25:23,  4.78it/s]

Determine whether the semantic relation where platelet and endothelial cell adhesion molecule 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where papaverine is the subject, medical condition treated is the predicate, and heart arrhythmia is the object constitutes an accurate semantic relation.

7555it [25:23,  4.93it/s]

false
Determine whether the semantic relation where heart arrhythmia is the subject, drug or therapy used for treatment is the predicate, and papaverine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where antisocial personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7557it [25:24,  5.13it/s]

true
Determine whether the semantic relation where nerve growth factor is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pigmented villonodular synovitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7559it [25:24,  5.16it/s]

true
Determine whether the semantic relation where corneal ulcer is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myofascial pain syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7561it [25:25,  5.08it/s]

true
Determine whether the semantic relation where Fringillidae is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

7562it [25:25,  5.13it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

7564it [25:25,  4.98it/s]

true
Determine whether the semantic relation where adrenoceptor beta 2 is the subject, biological process is the predicate, and bone resorption is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where complications of diabetes mellitus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7566it [25:26,  5.04it/s]

false
Determine whether the semantic relation where polylysine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

7567it [25:26,  5.07it/s]

Determine whether the semantic relation where intracranial aneurysm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poliomyelitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7569it [25:26,  5.15it/s]

true
Determine whether the semantic relation where spermatocele is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

7571it [25:27,  4.77it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where butyric acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

7572it [25:27,  4.89it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 2D is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7573it [25:27,  4.50it/s]

true
Determine whether the semantic relation where El Salvador is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

7575it [25:28,  4.65it/s]

true
Determine whether the semantic relation where anthrax is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and El Salvador is the object constitutes an accurate semantic relation.

7577it [25:28,  5.00it/s]

true
Determine whether the semantic relation where Angelica sinensis is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dichlorvos is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7578it [25:28,  4.98it/s]

true
Determine whether the semantic relation where TNF superfamily member 9 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7579it [25:28,  4.82it/s]

true
Determine whether the semantic relation where stillbirth is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

7580it [25:29,  4.80it/s]

false
Determine whether the semantic relation where KIT ligand is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7582it [25:29,  4.85it/s]

false
Determine whether the semantic relation where necrosis is the subject, drug or therapy used for treatment is the predicate, and phentolamine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypoactive sexual desire disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7584it [25:29,  5.03it/s]

true
Determine whether the semantic relation where phentolamine is the subject, medical condition treated is the predicate, and necrosis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chickenpox is the subject, drug or therapy used for treatment is the predicate, and zinc oxide is the object constitutes an accurate semantic relation.

7586it [25:30,  4.94it/s]

false
Determine whether the semantic relation where CD19 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

7587it [25:30,  4.96it/s]

true
Determine whether the semantic relation where adamantane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7588it [25:30,  4.69it/s]

true
Determine whether the semantic relation where Western equine encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7589it [25:30,  4.71it/s]

true
Determine whether the semantic relation where adenosine triphosphate is the subject, found in taxon is the predicate, and Musca domestica is the object constitutes an accurate semantic relation.

7591it [25:31,  4.80it/s]

false
Determine whether the semantic relation where cutaneous T cell lymphoma is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nucleotide binding oligomerization domain containing 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7592it [25:31,  5.02it/s]

true
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7594it [25:31,  5.01it/s]

false
Determine whether the semantic relation where acute monocytic leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where D-sorbitol is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

7596it [25:32,  5.22it/s]

true
Determine whether the semantic relation where Diclofenac is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quinine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7597it [25:32,  5.10it/s]

true
Determine whether the semantic relation where inducible T cell costimulator ligand is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7599it [25:32,  5.07it/s]

true
Determine whether the semantic relation where hyperlipidemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetanus is the subject, possible treatment is the predicate, and pharmacotherapy is the object constitutes an accurate semantic relation.

7601it [25:33,  5.08it/s]

true
Determine whether the semantic relation where chromoblastomycosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serpin family A member 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

7602it [25:33,  5.11it/s]

false
Determine whether the semantic relation where phthalic anhydride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7604it [25:33,  4.97it/s]

true
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epispadias is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

7605it [25:34,  4.85it/s]

false
Determine whether the semantic relation where 1,4-alpha-glucan branching enzyme 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

7606it [25:34,  4.77it/s]

false
Determine whether the semantic relation where vitamin D deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7608it [25:34,  4.75it/s]

true
Determine whether the semantic relation where (R)-mevalonic acid is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

7609it [25:34,  4.75it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

7611it [25:35,  4.92it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HSPA8 is the subject, expressed in is the predicate, and islet of Langerhans is the object constitutes an accurate semantic relation.

7612it [25:35,  4.96it/s]

false
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7614it [25:35,  5.04it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where riboflavin is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7615it [25:36,  5.04it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

7617it [25:36,  5.02it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-selenocysteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7619it [25:36,  5.21it/s]

true
Determine whether the semantic relation where flat feet is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coagulation factor VII is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7621it [25:37,  5.15it/s]

true
Determine whether the semantic relation where HCK proto-oncogene, Src family tyrosine kinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

7623it [25:37,  5.21it/s]

true
Determine whether the semantic relation where decerebration is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

7624it [25:37,  5.15it/s]

true
Determine whether the semantic relation where meningitis is the subject, medical examination is the predicate, and neurological examination is the object constitutes an accurate semantic relation.

7626it [25:38,  4.90it/s]

false
Determine whether the semantic relation where adenosine is the subject, subject has role is the predicate, and analgesic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phenylalanine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7628it [25:38,  4.99it/s]

true
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, two Ig domains and long cytoplasmic tail 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

7630it [25:39,  5.00it/s]

false
Determine whether the semantic relation where impetigo is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.

7632it [25:39,  4.68it/s]

true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where foodborne illness is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

7633it [25:39,  4.74it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

7635it [25:40,  4.71it/s]

true
Determine whether the semantic relation where iron is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

7636it [25:40,  4.69it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

7637it [25:40,  4.65it/s]

false
Determine whether the semantic relation where Timor-Leste is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

7639it [25:41,  4.45it/s]

true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Timor-Leste is the object constitutes an accurate semantic relation.

7641it [25:41,  4.93it/s]

true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where probucol is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

7642it [25:41,  5.06it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and probucol is the object constitutes an accurate semantic relation.

7644it [25:42,  5.02it/s]

false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

7646it [25:42,  5.01it/s]

true
Determine whether the semantic relation where postural orthostatic tachycardia syndrome is the subject, subclass of is the predicate, and heart conduction disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pigmented spindle cell nevus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7648it [25:42,  5.19it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leghemoglobin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7650it [25:43,  5.09it/s]

false
Determine whether the semantic relation where legal liability is the subject, country is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

7652it [25:43,  5.18it/s]

true
Determine whether the semantic relation where cobalamin binding intrinsic factor is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

7654it [25:44,  5.07it/s]

false
Determine whether the semantic relation where lactose intolerance is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lactose intolerance is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7656it [25:44,  5.23it/s]

true
Determine whether the semantic relation where pseudomembranous colitis is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vulvovaginitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7658it [25:44,  5.38it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echinococcosis is the subject, has natural reservoir is the predicate, and Felidae is the object constitutes an accurate semantic relation.

7660it [25:45,  5.42it/s]

false
Determine whether the semantic relation where concussion is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Secretoglobin family 2A member 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

7662it [25:45,  5.26it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Valeriana officinalis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cataract is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

7663it [25:45,  5.21it/s]

true
Determine whether the semantic relation where blood plasma is the subject, has part(s) is the predicate, and water is the object constitutes an accurate semantic relation.

7664it [25:46,  4.84it/s]

true
Determine whether the semantic relation where Barth syndrome is the subject, symptoms and signs is the predicate, and heart arrhythmia is the object constitutes an accurate semantic relation.

7666it [25:46,  4.69it/s]

true
Determine whether the semantic relation where osteochondritis dissecans is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DNA nucleotidylexotransferase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

7668it [25:46,  5.10it/s]

false
Determine whether the semantic relation where infectious mononucleosis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paired box 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

7669it [25:47,  5.15it/s]

false
Determine whether the semantic relation where hypoactive sexual desire disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

7670it [25:47,  4.48it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

7672it [25:47,  4.73it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Grenada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Grenada is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

7673it [25:47,  4.71it/s]

true
Determine whether the semantic relation where Yugoslavia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

7674it [25:48,  4.76it/s]

true
Determine whether the semantic relation where psoriasis is the subject, risk factor is the predicate, and obesity is the object constitutes an accurate semantic relation.

7676it [25:48,  4.86it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

7678it [25:48,  4.90it/s]

true
Determine whether the semantic relation where uric acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where testosterone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

7680it [25:49,  5.06it/s]

false
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dirofilariasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7681it [25:49,  4.46it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and cyanosis is the object constitutes an accurate semantic relation.

7683it [25:50,  4.59it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurofibromatosis type I is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7684it [25:50,  4.68it/s]

true
Determine whether the semantic relation where prolactinoma is the subject, health specialty is the predicate, and neurosurgery is the object constitutes an accurate semantic relation.

7685it [25:50,  4.69it/s]

false
Determine whether the semantic relation where superoxide is the subject, subclass of is the predicate, and salt is the object constitutes an accurate semantic relation.

7687it [25:50,  4.97it/s]

false
Determine whether the semantic relation where Singapore is the subject, instance of is the predicate, and city is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxytocin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

7689it [25:51,  5.01it/s]

true
Determine whether the semantic relation where Histamine receptor H2 is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7690it [25:51,  5.07it/s]

true
Determine whether the semantic relation where cryptogenic organizing pneumonia is the subject, has phenotype is the predicate, and scar is the object constitutes an accurate semantic relation.

7692it [25:51,  5.02it/s]

true
Determine whether the semantic relation where radiation burn is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coronavirus disease is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

7693it [25:52,  4.84it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Artemisia is the object constitutes an accurate semantic relation.

7695it [25:52,  4.62it/s]

false
Determine whether the semantic relation where deoxyribonucleic acid is the subject, subclass of is the predicate, and biopolymer is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

7697it [25:52,  4.79it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where maxillary disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7699it [25:53,  4.85it/s]

true
Determine whether the semantic relation where Solute carrier family 12, member 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

7701it [25:53,  4.96it/s]

true
Determine whether the semantic relation where SMAD family member 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

7703it [25:54,  5.03it/s]

true
Determine whether the semantic relation where oral candidiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where B-Raf proto-oncogene, serine/threonine kinase is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

7705it [25:54,  5.09it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

7706it [25:54,  5.06it/s]

true
Determine whether the semantic relation where miliary tuberculosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7708it [25:55,  4.75it/s]

true
Determine whether the semantic relation where adenocarcinoma is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where D-sorbitol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

7710it [25:55,  5.04it/s]

false
Determine whether the semantic relation where time and motion study is the subject, instance of is the predicate, and observational study is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 3-hydroxyanthranilate 3,4-dioxygenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

7712it [25:55,  4.97it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and miscarriage is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

7714it [25:56,  5.12it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

7715it [25:56,  4.92it/s]

true
Determine whether the semantic relation where (E)-phytonadione is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7716it [25:56,  4.82it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Guyana is the object constitutes an accurate semantic relation.

7717it [25:57,  4.18it/s]

true
Determine whether the semantic relation where sphingosine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7718it [25:57,  4.26it/s]

true
Determine whether the semantic relation where Guyana is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

7719it [25:57,  4.37it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

7720it [25:57,  4.46it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

7722it [25:58,  4.36it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

7723it [25:58,  4.48it/s]

true
Determine whether the semantic relation where tolosa-hunt syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7725it [25:58,  4.70it/s]

true
Determine whether the semantic relation where brucellosis is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nephrotic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7727it [25:59,  5.00it/s]

true
Determine whether the semantic relation where pulpitis is the subject, instance of is the predicate, and injury is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hymenolepiasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

7728it [25:59,  5.09it/s]

true
Determine whether the semantic relation where Lassa fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

7730it [25:59,  5.13it/s]

false
Determine whether the semantic relation where mycosis fungoides is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where spinal cord compression is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7732it [26:00,  5.23it/s]

true
Determine whether the semantic relation where phimosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where geographic tongue is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7734it [26:00,  5.05it/s]

false
Determine whether the semantic relation where electron is the subject, named after is the predicate, and amber is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prostacyclin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

7735it [26:00,  5.06it/s]

false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

7737it [26:01,  4.64it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

7739it [26:01,  4.94it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hidradenoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7740it [26:01,  4.81it/s]

true
Determine whether the semantic relation where ectopic pregnancy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7741it [26:02,  4.65it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

7743it [26:02,  4.87it/s]

true
Determine whether the semantic relation where tick-borne encephalitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Valeriana officinalis is the object constitutes an accurate semantic relation.

7745it [26:02,  5.05it/s]

false
Determine whether the semantic relation where choledocholithiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

7746it [26:03,  5.03it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

7748it [26:03,  5.10it/s]

true
Determine whether the semantic relation where gastroenteritis is the subject, symptoms and signs is the predicate, and spasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Surfactant protein B is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

7750it [26:03,  4.94it/s]

false
Determine whether the semantic relation where human is the subject, uses is the predicate, and language is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where functional hearing loss is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

7751it [26:04,  4.67it/s]

false
Determine whether the semantic relation where World War II is the subject, location is the predicate, and Africa is the object constitutes an accurate semantic relation.

7753it [26:04,  4.92it/s]

maybe
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diphtheria is the subject, drug or therapy used for treatment is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

7755it [26:04,  5.12it/s]

true
Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where C-C motif chemokine ligand 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7756it [26:05,  5.02it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

7758it [26:05,  5.00it/s]

true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mesothelioma is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

7759it [26:05,  5.01it/s]

true
Determine whether the semantic relation where glycerol is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

7761it [26:06,  4.98it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phobia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7762it [26:06,  5.08it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

7764it [26:06,  4.74it/s]

true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebrospinal fluid leak is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7766it [26:07,  5.11it/s]

false
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

7768it [26:07,  5.29it/s]

true
Determine whether the semantic relation where Guinea is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glutamic-pyruvic transaminase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7770it [26:07,  5.36it/s]

true
Determine whether the semantic relation where uricase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aminomethylphosphonic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7772it [26:08,  5.23it/s]

true
Determine whether the semantic relation where physical fitness is the subject, different from is the predicate, and fitness is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fitness is the subject, different from is the predicate, and physical fitness is the object constitutes an accurate semantic relation.

7774it [26:08,  5.10it/s]

false
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Q methodology is the subject, instance of is the predicate, and scientific method is the object constitutes an accurate semantic relation.

7775it [26:08,  5.16it/s]

true
Determine whether the semantic relation where Natriuretic peptide A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7777it [26:09,  4.79it/s]

false
Determine whether the semantic relation where visceral leishmaniasis is the subject, subclass of is the predicate, and liver disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quinacrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7778it [26:09,  4.78it/s]

false
Determine whether the semantic relation where Calnexin is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

7779it [26:09,  4.72it/s]

false
Determine whether the semantic relation where agoraphobia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7781it [26:10,  4.91it/s]

true
Determine whether the semantic relation where cyclin dependent kinase 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ancylostomiasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

7783it [26:10,  5.14it/s]

false
Determine whether the semantic relation where varicose ulcer is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

7785it [26:10,  5.16it/s]

true
Determine whether the semantic relation where beryllium is the subject, location of discovery is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

7787it [26:11,  5.34it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

7789it [26:11,  5.18it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-chloroethan-1-ol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7790it [26:11,  5.06it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and hematoma is the object constitutes an accurate semantic relation.

7792it [26:12,  5.05it/s]

true
Determine whether the semantic relation where Lyme disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lyme disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7793it [26:12,  5.14it/s]

true
Determine whether the semantic relation where Zellweger syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7794it [26:12,  5.08it/s]

true
Determine whether the semantic relation where iron responsive element binding protein 2 is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

7796it [26:13,  5.12it/s]

false
Determine whether the semantic relation where EPH receptor B3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inosine diphosphate is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

7798it [26:13,  5.05it/s]

false
Determine whether the semantic relation where Guillain–Barré syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ehrlichiosis is the subject, drug or therapy used for treatment is the predicate, and vancomycin is the object constitutes an accurate semantic relation.

7799it [26:13,  4.76it/s]

false
Determine whether the semantic relation where DL-ofloxacin is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.

7800it [26:13,  4.73it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, possible treatment is the predicate, and antihemorrhagic is the object constitutes an accurate semantic relation.

7802it [26:14,  4.93it/s]

false
Determine whether the semantic relation where acute myelomonocytic leukemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow nail syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7803it [26:14,  4.99it/s]

true
Determine whether the semantic relation where bone marrow disease is the subject, subclass of is the predicate, and bone disease is the object constitutes an accurate semantic relation.

7805it [26:14,  5.01it/s]

true
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and shock is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypertrophic cardiomyopathy is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

7807it [26:15,  5.23it/s]

true
Determine whether the semantic relation where lactic acidosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inflammation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7809it [26:15,  5.47it/s]

true
Determine whether the semantic relation where male infertility is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Notch receptor 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7811it [26:16,  5.22it/s]

false
Determine whether the semantic relation where Interleukin 4 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where toothache is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7812it [26:16,  5.20it/s]

false
Determine whether the semantic relation where pyridoxine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

7814it [26:16,  4.99it/s]

false
Determine whether the semantic relation where CNS demyelinating autoimmune diseases is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

7815it [26:16,  5.11it/s]

Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

7817it [26:17,  5.27it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aldehydic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7819it [26:17,  5.37it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where homeostasis is the subject, different from is the predicate, and hemostasis is the object constitutes an accurate semantic relation.

7820it [26:17,  5.18it/s]

true
Determine whether the semantic relation where hemostasis is the subject, different from is the predicate, and homeostasis is the object constitutes an accurate semantic relation.

7821it [26:18,  4.86it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

7822it [26:18,  4.32it/s]

true
Determine whether the semantic relation where colonoscopy is the subject, different from is the predicate, and colposcopy is the object constitutes an accurate semantic relation.

7823it [26:18,  4.10it/s]

true
Determine whether the semantic relation where transient cerebral isolation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7825it [26:18,  4.50it/s]

true
Determine whether the semantic relation where amylopectin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carnitine O-acetyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

7827it [26:19,  4.86it/s]

true
Determine whether the semantic relation where hydroa vacciniforme is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nystatin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

7828it [26:19,  4.87it/s]

false
Determine whether the semantic relation where ethylmercury chloride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7830it [26:19,  4.97it/s]

true
Determine whether the semantic relation where endothelin 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where reflex epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7832it [26:20,  4.98it/s]

true
Determine whether the semantic relation where TNF receptor superfamily member 13B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and France is the object constitutes an accurate semantic relation.

7833it [26:20,  5.00it/s]

true
Determine whether the semantic relation where hepatorenal syndrome is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

7835it [26:20,  5.04it/s]

false
Determine whether the semantic relation where LDL receptor related protein 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major depressive disorder is the subject, risk factor is the predicate, and chronic condition is the object constitutes an accurate semantic relation.

7837it [26:21,  5.16it/s]

false
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and procainamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Receptor activity modifying protein 3 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

7838it [26:21,  5.21it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

7839it [26:21,  4.95it/s]

true
Determine whether the semantic relation where procainamide is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

7840it [26:21,  4.88it/s]

true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

7841it [26:22,  4.72it/s]

false
Determine whether the semantic relation where acetaldehyde is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

7843it [26:22,  4.86it/s]

false
Determine whether the semantic relation where placental insufficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Ireland is the object constitutes an accurate semantic relation.

7845it [26:23,  5.03it/s]

false
Determine whether the semantic relation where Phenylethanolamine N-methyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crohn's disease is the subject, drug or therapy used for treatment is the predicate, and naltrexone is the object constitutes an accurate semantic relation.

7847it [26:23,  5.24it/s]

false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and sulindac is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulindac is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

7849it [26:23,  5.15it/s]

true
Determine whether the semantic relation where congenital toxoplasmosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CGRP receptor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

7851it [26:24,  5.09it/s]

true
Determine whether the semantic relation where Lymphotoxin beta receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

7853it [26:24,  5.01it/s]

true
Determine whether the semantic relation where panic disorder is the subject, drug or therapy used for treatment is the predicate, and propranolol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

7855it [26:24,  5.21it/s]

true
Determine whether the semantic relation where malakoplakia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-dipalmitoylphosphatidylcholine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7857it [26:25,  5.12it/s]

true
Determine whether the semantic relation where propranolol is the subject, medical condition treated is the predicate, and panic disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronology is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

7859it [26:25,  5.20it/s]

false
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Germany is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where human nature is the subject, part of is the predicate, and human is the object constitutes an accurate semantic relation.

7860it [26:25,  5.23it/s]

false
Determine whether the semantic relation where human nature is the subject, facet of is the predicate, and human is the object constitutes an accurate semantic relation.

7862it [26:26,  5.17it/s]

false
Determine whether the semantic relation where tuberculosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melioidosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

7864it [26:26,  5.09it/s]

true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and heart disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

7865it [26:26,  5.28it/s]

true
Determine whether the semantic relation where gout is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7866it [26:27,  5.11it/s]

true
Determine whether the semantic relation where gout is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7868it [26:27,  5.01it/s]

true
Determine whether the semantic relation where congenital rubella syndrome is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cardiomegaly is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7869it [26:27,  4.89it/s]

true
Determine whether the semantic relation where factor VIIa [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

7871it [26:28,  4.95it/s]

false
Determine whether the semantic relation where endophthalmitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD33 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7872it [26:28,  4.89it/s]

true
Determine whether the semantic relation where parasitic helminthiasis infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7874it [26:28,  4.92it/s]

true
Determine whether the semantic relation where anogenital venereal wart is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tumor necrosis factor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

7876it [26:29,  5.14it/s]

false
Determine whether the semantic relation where carotid artery disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where arteriosclerosis obliterans is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

7878it [26:29,  4.86it/s]

false
Determine whether the semantic relation where EPH receptor A2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dengue fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

7880it [26:29,  4.91it/s]

false
Determine whether the semantic relation where sulfonic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Senegal is the object constitutes an accurate semantic relation.

7881it [26:30,  5.08it/s]

true
Determine whether the semantic relation where biological warfare is the subject, different from is the predicate, and biological pest control is the object constitutes an accurate semantic relation.

7882it [26:30,  4.98it/s]

true
Determine whether the semantic relation where biological pest control is the subject, different from is the predicate, and biological warfare is the object constitutes an accurate semantic relation.

7883it [26:30,  4.81it/s]

true
Determine whether the semantic relation where Senegal is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7885it [26:31,  4.86it/s]

true
Determine whether the semantic relation where common bile duct neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where maltose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7887it [26:31,  4.87it/s]

false
Determine whether the semantic relation where infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibromuscular dysplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7888it [26:31,  4.97it/s]

true
Determine whether the semantic relation where fibromyalgia is the subject, afflicts is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

7889it [26:31,  4.90it/s]

true
Determine whether the semantic relation where poison is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

7891it [26:32,  4.85it/s]

false
Determine whether the semantic relation where liver cirrhosis is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

7893it [26:32,  5.08it/s]

false
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pulmonary embolism is the subject, drug or therapy used for treatment is the predicate, and papaverine is the object constitutes an accurate semantic relation.

7895it [26:33,  4.96it/s]

false
Determine whether the semantic relation where papaverine is the subject, medical condition treated is the predicate, and pulmonary embolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where incomplete abortion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7897it [26:33,  4.94it/s]

true
Determine whether the semantic relation where rectal neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where male breast neoplasm is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

7898it [26:33,  5.19it/s]

false
Determine whether the semantic relation where pancreatic fistula is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

7900it [26:34,  5.25it/s]

false
Determine whether the semantic relation where cytomegalovirus retinitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thyroid crisis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7901it [26:34,  4.50it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.

7902it [26:34,  4.28it/s]

true
Determine whether the semantic relation where (RS)-citalopram is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

7903it [26:34,  4.19it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

7904it [26:35,  4.19it/s]

true
Determine whether the semantic relation where conducted energy weapon injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7906it [26:35,  4.55it/s]

false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastritis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7908it [26:35,  4.81it/s]

true
Determine whether the semantic relation where gastritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where High mobility group box 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

7909it [26:36,  4.89it/s]

true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and arthritis is the object constitutes an accurate semantic relation.

7911it [26:36,  4.54it/s]

false
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where linguistics is the subject, subclass of is the predicate, and social science is the object constitutes an accurate semantic relation.

7912it [26:36,  4.60it/s]

true
Determine whether the semantic relation where theobromine is the subject, different from is the predicate, and bromine is the object constitutes an accurate semantic relation.

7913it [26:37,  4.41it/s]

true
Determine whether the semantic relation where hypertrophic cardiomyopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7915it [26:37,  4.46it/s]

true
Determine whether the semantic relation where African trypanosomiasis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dental fluorosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7917it [26:37,  4.95it/s]

true
Determine whether the semantic relation where acetic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aseptic meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7918it [26:38,  4.93it/s]

true
Determine whether the semantic relation where stupor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7920it [26:38,  4.90it/s]

false
Determine whether the semantic relation where myelin associated glycoprotein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Liberia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7921it [26:38,  5.00it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Liberia is the object constitutes an accurate semantic relation.

7922it [26:38,  4.55it/s]

true
Determine whether the semantic relation where LDL receptor related protein 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7924it [26:39,  4.82it/s]

true
Determine whether the semantic relation where pulmonary embolism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Dirofilaria immitis is the subject, endemic to is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

7925it [26:39,  3.88it/s]

true
Determine whether the semantic relation where silver nitrate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7927it [26:40,  4.22it/s]

true
Determine whether the semantic relation where diphtheria is the subject, drug or therapy used for treatment is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peripheral neuropathy is the subject, drug or therapy used for treatment is the predicate, and fentanyl is the object constitutes an accurate semantic relation.

7928it [26:40,  4.19it/s]

false
Determine whether the semantic relation where immunodeficiency is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

7930it [26:40,  4.49it/s]

false
Determine whether the semantic relation where fentanyl is the subject, medical condition treated is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dysmenorrhea is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

7931it [26:40,  4.64it/s]

true
Determine whether the semantic relation where Carboxypeptidase E is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7932it [26:41,  4.21it/s]

false
Determine whether the semantic relation where TNF superfamily member 14 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7933it [26:41,  4.39it/s]

true
Determine whether the semantic relation where paratyphoid fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

7934it [26:41,  4.54it/s]

Determine whether the semantic relation where papilloma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7936it [26:42,  4.76it/s]

true
Determine whether the semantic relation where Calbindin 1 is the subject, biological process is the predicate, and short-term memory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where protein tyrosine kinase 2 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

7937it [26:42,  4.69it/s]

true
Determine whether the semantic relation where tularemia is the subject, anatomical location is the predicate, and skin is the object constitutes an accurate semantic relation.

7939it [26:42,  4.65it/s]

true
Determine whether the semantic relation where Interleukin 5 receptor subunit alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uremia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

7941it [26:43,  4.83it/s]

true
Determine whether the semantic relation where uremia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulfone is the subject, different from is the predicate, and sulfate ester is the object constitutes an accurate semantic relation.

7943it [26:43,  4.69it/s]

true
Determine whether the semantic relation where zymosan is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

7945it [26:43,  4.90it/s]

true
Determine whether the semantic relation where lentinan is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where brucellosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7947it [26:44,  5.03it/s]

true
Determine whether the semantic relation where acne is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

7948it [26:44,  4.93it/s]

true
Determine whether the semantic relation where heat shock protein family D (Hsp60) member 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7949it [26:44,  4.93it/s]

false
Determine whether the semantic relation where polyketide is the subject, subclass of is the predicate, and ketone is the object constitutes an accurate semantic relation.
false

7950it [26:44,  4.94it/s]

Determine whether the semantic relation where antiphospholipid syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

7952it [26:45,  5.02it/s]

true
Determine whether the semantic relation where S100 calcium binding protein B is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

7953it [26:45,  5.08it/s]

true
Determine whether the semantic relation where SMAD family member 9 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

7955it [26:45,  5.10it/s]

false
Determine whether the semantic relation where oxalic acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 9 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

7957it [26:46,  5.00it/s]

true
Determine whether the semantic relation where hyaluronic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where taurine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

7959it [26:46,  5.16it/s]

true
Determine whether the semantic relation where Alagille syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eugenol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

7961it [26:47,  5.22it/s]

true
Determine whether the semantic relation where pentagastrin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where muteness is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

7963it [26:47,  5.16it/s]

false
Determine whether the semantic relation where sialic acids is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gnathomiasis is the subject, has natural reservoir is the predicate, and dog is the object constitutes an accurate semantic relation.

7965it [26:47,  5.26it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

7967it [26:48,  5.00it/s]

true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acne is the subject, does not have cause is the predicate, and diet is the object constitutes an accurate semantic relation.

7969it [26:48,  5.03it/s]

false
Determine whether the semantic relation where hydroxylamine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cystatin C is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

7971it [26:49,  5.18it/s]

false
Determine whether the semantic relation where glycocalyx is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ibogaine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

7973it [26:49,  5.21it/s]

true
Determine whether the semantic relation where Buruli ulcer disease is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where complement C4B (Chido blood group) is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7975it [26:49,  4.88it/s]

false
Determine whether the semantic relation where muscular atrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Heterogeneous nuclear ribonucleoprotein K is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

7977it [26:50,  4.95it/s]

false
Determine whether the semantic relation where nicotinic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true

7978it [26:50,  5.04it/s]

Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where histone deacetylase 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

7980it [26:50,  5.20it/s]

false
Determine whether the semantic relation where lynestrenol is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

7981it [26:51,  5.24it/s]

true
Determine whether the semantic relation where α-streptozocin is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

7983it [26:51,  5.14it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

7984it [26:51,  5.08it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

7986it [26:52,  5.06it/s]

true
Determine whether the semantic relation where circulatory and respiratory physiological phenomena is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azathioprine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

7988it [26:52,  5.10it/s]

true
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crohn's disease is the subject, medical examination is the predicate, and medical imaging is the object constitutes an accurate semantic relation.

7990it [26:52,  5.16it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

7992it [26:53,  5.02it/s]

true
Determine whether the semantic relation where diethyltoluamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peroxiredoxin 6 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

7993it [26:53,  4.95it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, A is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

7995it [26:53,  5.05it/s]

false
Determine whether the semantic relation where macular retinal edema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echinococcosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

7996it [26:54,  5.14it/s]

true
Determine whether the semantic relation where Honduras is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

7997it [26:54,  4.84it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Honduras is the object constitutes an accurate semantic relation.

7999it [26:54,  5.00it/s]

true
Determine whether the semantic relation where cystatin B is the subject, part of is the predicate, and pore-forming toxin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

8000it [26:54,  5.15it/s]

false
Determine whether the semantic relation where solute carrier family 12 member 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8002it [26:55,  4.88it/s]

false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where magnesium is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

8003it [26:55,  5.06it/s]

false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

8004it [26:55,  4.75it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

8006it [26:56,  4.87it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiotensin II receptor type 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

8007it [26:56,  4.88it/s]

false
Determine whether the semantic relation where Von Willebrand factor is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

8009it [26:56,  5.01it/s]

true
Determine whether the semantic relation where speech-language pathology is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

8011it [26:57,  5.12it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

8012it [26:57,  5.15it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

8013it [26:57,  5.08it/s]

true
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, biological process is the predicate, and exploration behavior is the object constitutes an accurate semantic relation.

8015it [26:57,  4.66it/s]

false
Determine whether the semantic relation where human is the subject, has part(s) is the predicate, and human body is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8016it [26:58,  4.85it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

8017it [26:58,  4.75it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

8019it [26:58,  4.80it/s]

true
Determine whether the semantic relation where abscisic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false

8020it [26:59,  4.84it/s]

Determine whether the semantic relation where scurvy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD40 ligand is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8022it [26:59,  5.09it/s]

true
Determine whether the semantic relation where myocardial rupture is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where man is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.

8024it [26:59,  5.15it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, medical examination is the predicate, and electroencephalography is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Alagille syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

8026it [27:00,  5.29it/s]

true
Determine whether the semantic relation where iridocorneal endothelial syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

8028it [27:00,  5.40it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

8030it [27:00,  5.16it/s]

true
Determine whether the semantic relation where catenanes is the subject, subclass of is the predicate, and hydrocarbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

8031it [27:01,  4.87it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

8033it [27:01,  4.95it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and clozapine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where alcoholic hepatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8035it [27:01,  5.08it/s]

true
Determine whether the semantic relation where Sex determining region Y is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ninhydrin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8037it [27:02,  5.30it/s]

true
Determine whether the semantic relation where procaine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chloral hydrate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8039it [27:02,  5.32it/s]

true
Determine whether the semantic relation where phase I clinical trial is the subject, participant is the predicate, and patient is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where morphine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8040it [27:02,  5.11it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

8041it [27:03,  4.98it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

8043it [27:03,  4.68it/s]

true
Determine whether the semantic relation where blastomycosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and methotrexate is the object constitutes an accurate semantic relation.

8044it [27:03,  4.76it/s]

true
Determine whether the semantic relation where mechlorethamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8046it [27:04,  4.43it/s]

true
Determine whether the semantic relation where tetrahydrocannabinol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

8047it [27:04,  4.59it/s]

true
Determine whether the semantic relation where parasitic skin disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8049it [27:04,  4.78it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SMAD family member 4 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8050it [27:05,  4.83it/s]

true
Determine whether the semantic relation where hypercalcemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

8051it [27:05,  4.79it/s]

false
Determine whether the semantic relation where cellular communication network factor 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8053it [27:05,  4.84it/s]

false
Determine whether the semantic relation where fragile X syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 10 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8055it [27:06,  5.05it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

8057it [27:06,  5.12it/s]

true
Determine whether the semantic relation where methylmalonic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where empyema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8058it [27:06,  5.20it/s]

true
Determine whether the semantic relation where neuroendocrine tumor is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

8060it [27:07,  5.11it/s]

true
Determine whether the semantic relation where lymphangitis is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where edrophonium is the subject, subclass of is the predicate, and cation is the object constitutes an accurate semantic relation.

8062it [27:07,  5.34it/s]

false
Determine whether the semantic relation where paradoxical embolism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

8064it [27:07,  5.27it/s]

true
Determine whether the semantic relation where etomidate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

8066it [27:08,  5.21it/s]

true
Determine whether the semantic relation where organic brain syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where benzoyl peroxide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8067it [27:08,  5.00it/s]

true
Determine whether the semantic relation where hyperprolactinemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

8069it [27:08,  4.92it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and paralysis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cocaine is the subject, subclass of is the predicate, and ester is the object constitutes an accurate semantic relation.

8071it [27:09,  5.12it/s]

true
Determine whether the semantic relation where photophobia is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alloxan is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8073it [27:09,  4.99it/s]

false
Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8075it [27:10,  5.14it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

8076it [27:10,  4.95it/s]

true
Determine whether the semantic relation where medical ethics is the subject, instance of is the predicate, and applied psychology is the object constitutes an accurate semantic relation.

8077it [27:10,  4.72it/s]

false
Determine whether the semantic relation where coagulation factor VII is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

8078it [27:10,  4.78it/s]

false
Determine whether the semantic relation where berylliosis is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

8079it [27:10,  4.69it/s]

true
Determine whether the semantic relation where anxiety is the subject, drug or therapy used for treatment is the predicate, and propranolol is the object constitutes an accurate semantic relation.

8081it [27:11,  4.60it/s]

true
Determine whether the semantic relation where propranolol is the subject, medical condition treated is the predicate, and anxiety is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

8082it [27:11,  4.68it/s]

false
Determine whether the semantic relation where codeine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8084it [27:11,  4.85it/s]

true
Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tyramine is the subject, found in taxon is the predicate, and Brassica is the object constitutes an accurate semantic relation.

8086it [27:12,  4.99it/s]

false
Determine whether the semantic relation where luteolin is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

8087it [27:12,  4.98it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8089it [27:12,  4.98it/s]

false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

8091it [27:13,  4.92it/s]

true
Determine whether the semantic relation where Whipple disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where permethrin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

8093it [27:13,  5.02it/s]

false
Determine whether the semantic relation where articulation disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dehydration is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

8095it [27:14,  4.98it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where denervation is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.

8097it [27:14,  5.21it/s]

false
Determine whether the semantic relation where chlorpyrifos is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyester is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8098it [27:14,  5.17it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true

8100it [27:15,  5.24it/s]

Determine whether the semantic relation where CSK is the subject, expressed in is the predicate, and blood is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sirolimus is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8102it [27:15,  5.09it/s]

false
Determine whether the semantic relation where liver cirrhosis is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

8104it [27:15,  5.11it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human is the subject, has characteristic is the predicate, and intelligence is the object constitutes an accurate semantic relation.

8106it [27:16,  5.01it/s]

true
Determine whether the semantic relation where Baker's cyst is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

8107it [27:16,  4.40it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

8109it [27:17,  4.66it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

8110it [27:17,  4.91it/s]

true
Determine whether the semantic relation where asthenozoospermia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8111it [27:17,  4.88it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8113it [27:17,  4.83it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

8115it [27:18,  4.94it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where portal hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8116it [27:18,  4.94it/s]

true
Determine whether the semantic relation where toxoplasmosis is the subject, disease transmission process is the predicate, and organ transplantation is the object constitutes an accurate semantic relation.

8117it [27:18,  4.93it/s]

true
Determine whether the semantic relation where human is the subject, has characteristic is the predicate, and interpersonal relationship is the object constitutes an accurate semantic relation.

8119it [27:19,  5.01it/s]

false
Determine whether the semantic relation where bacterial capsule is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurofibromatoses is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8121it [27:19,  5.18it/s]

true
Determine whether the semantic relation where hip dysplasia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where heptanoic acid is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

8123it [27:19,  5.19it/s]

false
Determine whether the semantic relation where CSK is the subject, expressed in is the predicate, and spleen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lung disease is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

8125it [27:20,  5.30it/s]

true
Determine whether the semantic relation where hepatic porphyria is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where progressive multifocal leukoencephalopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8126it [27:20,  5.22it/s]

true
Determine whether the semantic relation where cooking is the subject, instance of is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.

8128it [27:20,  5.09it/s]

false
Determine whether the semantic relation where chylomicron is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

8129it [27:20,  4.94it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

8131it [27:21,  5.09it/s]

true
Determine whether the semantic relation where alprostadil is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and amoxapine is the object constitutes an accurate semantic relation.

8133it [27:21,  5.25it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ethambutol is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

8135it [27:22,  5.04it/s]

false
Determine whether the semantic relation where EPH receptor A7 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, biological process is the predicate, and chemical synaptic transmission is the object constitutes an accurate semantic relation.

8137it [27:22,  5.16it/s]

false
Determine whether the semantic relation where diamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

8139it [27:22,  4.83it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true

8140it [27:23,  4.84it/s]

Determine whether the semantic relation where connective tissue neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plasmin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

8142it [27:23,  5.06it/s]

false
Determine whether the semantic relation where intra-abdominal abscess is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anabasine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8144it [27:23,  5.03it/s]

true
Determine whether the semantic relation where leukemia is the subject, drug or therapy used for treatment is the predicate, and isotretinoin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isotretinoin is the subject, medical condition treated is the predicate, and leukemia is the object constitutes an accurate semantic relation.

8146it [27:24,  5.08it/s]

false
Determine whether the semantic relation where Pyruvate carboxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

8148it [27:24,  5.25it/s]

false
Determine whether the semantic relation where salicylic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and cyproheptadine is the object constitutes an accurate semantic relation.

8150it [27:25,  5.26it/s]

false
Determine whether the semantic relation where virulent Newcastle disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where kallidin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8151it [27:25,  5.36it/s]

false
Determine whether the semantic relation where giardiasis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

8152it [27:25,  5.02it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

8153it [27:25,  4.88it/s]

true
Determine whether the semantic relation where Columbidae is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

8155it [27:26,  5.01it/s]

true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

8156it [27:26,  4.88it/s]

false
Determine whether the semantic relation where calcium sulfate is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

8157it [27:26,  4.89it/s]

true
Determine whether the semantic relation where succinic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

8158it [27:26,  4.89it/s]

false
Determine whether the semantic relation where Q61788060 is the subject, practiced by is the predicate, and human is the object constitutes an accurate semantic relation.

8160it [27:27,  4.69it/s]

false
Determine whether the semantic relation where human is the subject, participant in is the predicate, and Q61788060 is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 2 is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

8161it [27:27,  4.57it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

8162it [27:27,  4.67it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

8163it [27:27,  4.69it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 24 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8165it [27:28,  4.88it/s]

false
Determine whether the semantic relation where toxocariasis is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Eukaryotic translation initiation factor 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8167it [27:28,  4.99it/s]

false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Scutellaria baicalensis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where D-mannoheptulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8168it [27:28,  5.07it/s]

true
Determine whether the semantic relation where pectin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

8170it [27:29,  5.06it/s]

false
Determine whether the semantic relation where glomerular filtration barrier is the subject, subclass of is the predicate, and circulatory system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phagocyte bactericidal dysfunction is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

8172it [27:29,  5.08it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

8173it [27:29,  4.98it/s]

true
Determine whether the semantic relation where cryptosporidiosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

8174it [27:30,  4.53it/s]

true
Determine whether the semantic relation where trench fever is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

8176it [27:30,  4.56it/s]

false
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteolysis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

8178it [27:30,  4.68it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.

8179it [27:31,  4.31it/s]

true
Determine whether the semantic relation where Diclofenac is the subject, medical condition treated is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.

8180it [27:31,  4.46it/s]

false
Determine whether the semantic relation where peripheral neuropathy is the subject, drug or therapy used for treatment is the predicate, and Diclofenac is the object constitutes an accurate semantic relation.

8181it [27:31,  4.59it/s]

false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

8183it [27:32,  4.79it/s]

true
Determine whether the semantic relation where yersiniosis is the subject, has natural reservoir is the predicate, and bird is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD27 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8185it [27:32,  5.04it/s]

true
Determine whether the semantic relation where paranoid schizophrenia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paranoid schizophrenia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

8186it [27:32,  5.14it/s]

false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

8188it [27:33,  4.94it/s]

true
Determine whether the semantic relation where calcium phosphate is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylmercury compound is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

8190it [27:33,  5.04it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dysphonia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8192it [27:33,  5.22it/s]

false
Determine whether the semantic relation where Dominican Republic is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Dominican Republic is the object constitutes an accurate semantic relation.

8193it [27:33,  5.37it/s]

true
Determine whether the semantic relation where isolation is the subject, instance of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.

8194it [27:34,  5.16it/s]

false
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and osteoporosis is the object constitutes an accurate semantic relation.

8196it [27:34,  5.06it/s]

true
Determine whether the semantic relation where (RS)-diethylpropion is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where KIT proto-oncogene, receptor tyrosine kinase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8198it [27:35,  5.10it/s]

false
Determine whether the semantic relation where heart septal defect is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iceland is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

8200it [27:35,  5.18it/s]

true
Determine whether the semantic relation where EPH receptor B2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tay-Sachs disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8201it [27:35,  5.19it/s]

true
Determine whether the semantic relation where Platelet derived growth factor subunit B is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8203it [27:35,  5.04it/s]

false
Determine whether the semantic relation where nemaline myopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

8204it [27:36,  5.16it/s]

true
Determine whether the semantic relation where Samoa is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

8206it [27:36,  5.19it/s]

true
Determine whether the semantic relation where NMDA receptor is the subject, facilitates flow of is the predicate, and sodium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

8208it [27:36,  5.00it/s]

true
Determine whether the semantic relation where benign neonatal seizures is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

8210it [27:37,  5.09it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Samoa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human is the subject, has characteristic is the predicate, and personality is the object constitutes an accurate semantic relation.

8212it [27:37,  5.07it/s]

true
Determine whether the semantic relation where Quebec is the subject, shares border with is the predicate, and New York is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SMAD family member 9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8213it [27:37,  4.96it/s]

true
Determine whether the semantic relation where gout is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

8214it [27:38,  4.28it/s]

true
Determine whether the semantic relation where New York is the subject, shares border with is the predicate, and Quebec is the object constitutes an accurate semantic relation.

8215it [27:38,  4.29it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8217it [27:38,  4.51it/s]

true
Determine whether the semantic relation where Interleukin 23, alpha subunit p19 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tonic–clonic seizure is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8219it [27:39,  4.86it/s]

true
Determine whether the semantic relation where Kuru is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuru is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8221it [27:39,  5.11it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 14 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8223it [27:40,  5.09it/s]

false
Determine whether the semantic relation where citrullinemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Polymeric immunoglobulin receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8225it [27:40,  5.15it/s]

true
Determine whether the semantic relation where amebiasis is the subject, has part(s) is the predicate, and ulcer is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pressure ulcer is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

8226it [27:40,  5.06it/s]

false
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and dehydration is the object constitutes an accurate semantic relation.

8228it [27:41,  5.12it/s]

true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where poly-ADP-D-ribose is the subject, subclass of is the predicate, and biopolymer is the object constitutes an accurate semantic relation.

8229it [27:41,  4.95it/s]

true
Determine whether the semantic relation where Xanthine dehydrogenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

8231it [27:41,  4.98it/s]

true
Determine whether the semantic relation where urea is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transposition of great vessels is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8233it [27:42,  5.10it/s]

true
Determine whether the semantic relation where β-carotene is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myelodysplastic–myeloproliferative diseases is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8234it [27:42,  5.12it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true

8236it [27:42,  5.10it/s]

Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sclerosing encapsulating peritonitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8238it [27:43,  4.62it/s]

true
Determine whether the semantic relation where lymphangitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Americas is the subject, part of is the predicate, and Earth is the object constitutes an accurate semantic relation.

8240it [27:43,  5.05it/s]

true
Determine whether the semantic relation where Earth is the subject, has part(s) is the predicate, and Americas is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcitonin receptor like receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8242it [27:43,  5.23it/s]

false
Determine whether the semantic relation where chromium is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where harm reduction is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

8243it [27:44,  5.03it/s]

false
Determine whether the semantic relation where Kawasaki disease is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

8245it [27:44,  4.96it/s]

true
Determine whether the semantic relation where SRC proto-oncogene, non-receptor tyrosine kinase is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where butyrolactone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8247it [27:45,  4.63it/s]

true
Determine whether the semantic relation where hyaluronidase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart failure is the subject, risk factor is the predicate, and overweight is the object constitutes an accurate semantic relation.

8248it [27:45,  4.94it/s]

false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Togo is the object constitutes an accurate semantic relation.

8249it [27:45,  4.64it/s]

true
Determine whether the semantic relation where Togo is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

8251it [27:45,  4.61it/s]

false
Determine whether the semantic relation where trachoma is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

8252it [27:46,  4.66it/s]

true
Determine whether the semantic relation where tinea pedis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8254it [27:46,  4.90it/s]

true
Determine whether the semantic relation where tinea pedis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

8255it [27:46,  4.89it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

8257it [27:47,  4.89it/s]

true
Determine whether the semantic relation where hyperkinesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aldehydo-L-arabinose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8259it [27:47,  5.07it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where borreliosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8260it [27:47,  5.15it/s]

true
Determine whether the semantic relation where SMAD family member 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8262it [27:48,  5.02it/s]

true
Determine whether the semantic relation where epidermis is the subject, different from is the predicate, and epidermis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toll like receptor 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8263it [27:48,  5.05it/s]

false
Determine whether the semantic relation where zinc is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

8265it [27:48,  4.98it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8266it [27:48,  4.96it/s]

false
Determine whether the semantic relation where gnathomiasis is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

8268it [27:49,  4.94it/s]

true
Determine whether the semantic relation where maltose is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

8269it [27:49,  5.00it/s]

true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and rheumatoid arthritis is the object constitutes an accurate semantic relation.

8270it [27:49,  4.53it/s]

false
Determine whether the semantic relation where Beta vulgaris is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

8271it [27:49,  4.55it/s]

true
Determine whether the semantic relation where Seychelles is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

8272it [27:50,  4.65it/s]

true
Determine whether the semantic relation where coagulation factor V is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

8273it [27:50,  4.68it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Seychelles is the object constitutes an accurate semantic relation.

8274it [27:50,  4.65it/s]

true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

8276it [27:51,  4.90it/s]

false
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, found in taxon is the predicate, and Streptomyces coelicolor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

8278it [27:51,  5.08it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine monophosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8279it [27:51,  5.13it/s]

true
Determine whether the semantic relation where office automation is the subject, subclass of is the predicate, and automation is the object constitutes an accurate semantic relation.

8281it [27:52,  4.83it/s]

true
Determine whether the semantic relation where campylobacteriosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

8283it [27:52,  4.95it/s]

true
Determine whether the semantic relation where carrageenan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vimentin is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8284it [27:52,  4.79it/s]

false
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and osteoarthritis is the object constitutes an accurate semantic relation.

8286it [27:53,  4.83it/s]

false
Determine whether the semantic relation where Q21173788 is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acetylcholine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8287it [27:53,  4.51it/s]

true
Determine whether the semantic relation where acute disseminated encephalomyelitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

8288it [27:53,  4.48it/s]

false
Determine whether the semantic relation where amyloidosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

8290it [27:53,  4.56it/s]

false
Determine whether the semantic relation where substance-related disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ventricular dysfunction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8292it [27:54,  4.92it/s]

true
Determine whether the semantic relation where mastitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethacridine is the subject, medical condition treated is the predicate, and bacterial infectious disease is the object constitutes an accurate semantic relation.

8293it [27:54,  4.87it/s]

true
Determine whether the semantic relation where liver cirrhosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8294it [27:54,  4.89it/s]

true
Determine whether the semantic relation where liver cirrhosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8295it [27:55,  4.31it/s]

true
Determine whether the semantic relation where bacterial infectious disease is the subject, drug or therapy used for treatment is the predicate, and ethacridine is the object constitutes an accurate semantic relation.

8296it [27:55,  4.42it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

8298it [27:55,  4.61it/s]

true
Determine whether the semantic relation where carcinoid tumor is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

8299it [27:55,  4.79it/s]

false
Determine whether the semantic relation where Adenylate cyclase activating polypeptide 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

8301it [27:56,  4.87it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

8303it [27:56,  4.76it/s]

true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8305it [27:57,  4.81it/s]

true
Determine whether the semantic relation where Janus kinase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

8307it [27:57,  4.99it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where legionnaires' disease is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

8309it [27:57,  5.27it/s]

true
Determine whether the semantic relation where Methionine-tRNA synthetase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Methionine-tRNA synthetase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

8311it [27:58,  5.02it/s]

true
Determine whether the semantic relation where intrauterine hypoxia is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nedocromil is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.

8312it [27:58,  5.08it/s]

false
Determine whether the semantic relation where CD22 molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8314it [27:58,  5.06it/s]

false
Determine whether the semantic relation where hemorrhoid is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemorrhoid is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8316it [27:59,  5.17it/s]

true
Determine whether the semantic relation where Graves' disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bulimia nervosa is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

8318it [27:59,  5.02it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, biological process is the predicate, and autophagy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Far East scarlet-like fever is the subject, symptoms and signs is the predicate, and hepatitis is the object constitutes an accurate semantic relation.

8320it [28:00,  4.96it/s]

false
Determine whether the semantic relation where Jervell-Lange Nielsen syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jervell-Lange Nielsen syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8322it [28:00,  5.19it/s]

true
Determine whether the semantic relation where enema is the subject, different from is the predicate, and edema is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Ganoderma lucidum is the object constitutes an accurate semantic relation.

8323it [28:00,  5.14it/s]

false
Determine whether the semantic relation where isoniazid is the subject, subclass of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

8325it [28:01,  4.89it/s]

true
Determine whether the semantic relation where dentine hypersensitivity is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rett syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8327it [28:01,  4.89it/s]

true
Determine whether the semantic relation where Q2839152 is the subject, instance of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8328it [28:01,  5.07it/s]

true
Determine whether the semantic relation where Hong Kong is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8330it [28:02,  5.05it/s]

false
Determine whether the semantic relation where type I site-specific deoxyribonuclease complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Hong Kong is the object constitutes an accurate semantic relation.

8331it [28:02,  4.95it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and phenol is the object constitutes an accurate semantic relation.

8333it [28:02,  4.81it/s]

false
Determine whether the semantic relation where phenol is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.
false

8334it [28:02,  4.92it/s]

Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tennis elbow is the subject, health specialty is the predicate, and physical medicine and rehabilitation is the object constitutes an accurate semantic relation.

8336it [28:03,  5.12it/s]

true
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Phospholipase A2 receptor 1 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

8338it [28:03,  5.07it/s]

true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where parasitemia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8339it [28:03,  5.08it/s]

false
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

8341it [28:04,  5.09it/s]

true
Determine whether the semantic relation where Erdheim-Chester disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Erdheim-Chester disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8342it [28:04,  4.93it/s]

true
Determine whether the semantic relation where cacao is the subject, instance of is the predicate, and genome is the object constitutes an accurate semantic relation.

8343it [28:04,  4.76it/s]

false
Determine whether the semantic relation where lipoid nephrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8345it [28:05,  4.92it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

8346it [28:05,  4.90it/s]

true
Determine whether the semantic relation where leptospirosis is the subject, anatomical location is the predicate, and lung is the object constitutes an accurate semantic relation.

8348it [28:05,  4.80it/s]

false
Determine whether the semantic relation where dimercaprol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where whistleblower is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

8349it [28:06,  4.99it/s]

false
Determine whether the semantic relation where avian influenza is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8350it [28:06,  4.94it/s]

true
Determine whether the semantic relation where nalidixic acid is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

8351it [28:06,  4.60it/s]

true
Determine whether the semantic relation where Thy-1 cell surface antigen is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8353it [28:06,  4.78it/s]

true
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

8355it [28:07,  4.93it/s]

true
Determine whether the semantic relation where swine vesicular disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurodegeneration is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8357it [28:07,  5.10it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (E)-chlorprothixene (Z according to WHO INN RL 40, conflated wikidata) is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8359it [28:08,  5.19it/s]

true
Determine whether the semantic relation where Epstein–Barr virus infection is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pain is the subject, health specialty is the predicate, and anaesthesiology is the object constitutes an accurate semantic relation.

8360it [28:08,  4.43it/s]

false
Determine whether the semantic relation where hepatic porphyria is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

8362it [28:08,  4.72it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

8364it [28:09,  4.86it/s]

true
Determine whether the semantic relation where toothache is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false

8365it [28:09,  4.88it/s]

Determine whether the semantic relation where Sjögren's syndrome is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true

8366it [28:09,  4.91it/s]

Determine whether the semantic relation where solute carrier family 7 member 5 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Soviet Union is the subject, shares border with is the predicate, and Finland is the object constitutes an accurate semantic relation.

8368it [28:09,  4.96it/s]

true
Determine whether the semantic relation where L-kynurenine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine triphosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8370it [28:10,  5.20it/s]

false
Determine whether the semantic relation where mycetoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Synaptotagmin 1 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

8372it [28:10,  5.27it/s]

false
Determine whether the semantic relation where integrin alpha6beta1 [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

8374it [28:11,  5.25it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sickle-cell disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

8375it [28:11,  5.14it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

8377it [28:11,  5.03it/s]

true
Determine whether the semantic relation where glial fibrillary acidic protein is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dipetalonemiasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

8379it [28:12,  4.12it/s]

false
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where foreign-body migration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8380it [28:12,  4.47it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

8382it [28:12,  4.65it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where venom is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.

8384it [28:13,  5.02it/s]

true
Determine whether the semantic relation where duodenal ulcer is the subject, drug or therapy used for treatment is the predicate, and maprotiline is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where maprotiline is the subject, medical condition treated is the predicate, and duodenal ulcer is the object constitutes an accurate semantic relation.

8386it [28:13,  4.97it/s]

false
Determine whether the semantic relation where Neurofibromin 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intermittent claudication is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

8388it [28:14,  5.13it/s]

false
Determine whether the semantic relation where diet is the subject, has contributing factor is the predicate, and culture is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where macular degeneration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8390it [28:14,  5.03it/s]

true
Determine whether the semantic relation where carcinoid tumor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where filipin III is the subject, subject has role is the predicate, and antiviral agent is the object constitutes an accurate semantic relation.

8392it [28:14,  5.02it/s]

false
Determine whether the semantic relation where Actinomycetales infectious disease is the subject, subclass of is the predicate, and gram-negative bacterial infection is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trypsinogen is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8394it [28:15,  5.10it/s]

false
Determine whether the semantic relation where peripheral nervous system neoplasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.

8396it [28:15,  5.30it/s]

true
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

8397it [28:15,  5.40it/s]

true
Determine whether the semantic relation where atrioventricular block is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.
false

8398it [28:15,  5.26it/s]

Determine whether the semantic relation where Venezuelan equine encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8399it [28:16,  5.13it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

8401it [28:16,  4.92it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where subvalvular aortic stenosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8402it [28:16,  4.98it/s]

true
Determine whether the semantic relation where solute carrier family 6 member 3 is the subject, biological process is the predicate, and lactation is the object constitutes an accurate semantic relation.

8404it [28:17,  4.67it/s]

false
Determine whether the semantic relation where legionnaires' disease is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningococcal disease is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

8405it [28:17,  4.92it/s]

true
Determine whether the semantic relation where methylthiouracil is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8407it [28:17,  4.88it/s]

true
Determine whether the semantic relation where quinine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thymidylate synthase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

8408it [28:18,  4.92it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine receptor 4 is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

8409it [28:18,  4.76it/s]

false
Determine whether the semantic relation where guanidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8411it [28:18,  4.77it/s]

false
Determine whether the semantic relation where silicosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Solute carrier family 5 member 2 is the subject, biological process is the predicate, and ion transport is the object constitutes an accurate semantic relation.

8413it [28:19,  4.98it/s]

false
Determine whether the semantic relation where sickle-cell disease is the subject, subclass of is the predicate, and blood protein disease is the object constitutes an accurate semantic relation.
true

8414it [28:19,  5.06it/s]

Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

8416it [28:19,  5.11it/s]

true
Determine whether the semantic relation where Mediterranean diet is the subject, named after is the predicate, and Mediterranean Sea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where middle cerebral artery infarction is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8418it [28:20,  5.14it/s]

true
Determine whether the semantic relation where Ralstonia solanacearum is the subject, has host is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mannans is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8420it [28:20,  5.25it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where LDL receptor related protein 1 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.

8421it [28:20,  5.32it/s]

false
Determine whether the semantic relation where osteomalacia is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

8423it [28:21,  5.14it/s]

true
Determine whether the semantic relation where sciatic neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ninhydrin is the subject, subject has role is the predicate, and radiosensitizer is the object constitutes an accurate semantic relation.

8425it [28:21,  5.26it/s]

false
Determine whether the semantic relation where polymerase chain reaction is the subject, part of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glycogen storage disease V is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8426it [28:21,  5.18it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8428it [28:22,  5.10it/s]

false
Determine whether the semantic relation where phonetics is the subject, part of is the predicate, and neuroscience is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where integumentary system is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.

8430it [28:22,  5.28it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and integumentary system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 14 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8431it [28:22,  5.32it/s]

false
Determine whether the semantic relation where renal hypertension is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8433it [28:22,  5.23it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where foodborne illness is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8435it [28:23,  5.21it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coal tar is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8436it [28:23,  5.22it/s]

true
Determine whether the semantic relation where smallpox is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

8437it [28:23,  4.97it/s]

false
Determine whether the semantic relation where CD5 molecule is the subject, biological process is the predicate, and endocytosis is the object constitutes an accurate semantic relation.

8438it [28:23,  4.96it/s]

false
Determine whether the semantic relation where tuberous sclerosis is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

8440it [28:24,  5.04it/s]

true
Determine whether the semantic relation where nitrofuran is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Perforin 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8442it [28:24,  5.05it/s]

false
Determine whether the semantic relation where perioperative care is the subject, subclass of is the predicate, and health care is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fabry disease is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

8444it [28:25,  5.19it/s]

true
Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where photon is the subject, interaction is the predicate, and gravity is the object constitutes an accurate semantic relation.

8445it [28:25,  5.09it/s]

true
Determine whether the semantic relation where bladder disease is the subject, drug or therapy used for treatment is the predicate, and acetic acid is the object constitutes an accurate semantic relation.

8447it [28:25,  5.03it/s]

false
Determine whether the semantic relation where acetic acid is the subject, medical condition treated is the predicate, and bladder disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cyclosporiasis is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

8449it [28:26,  5.11it/s]

false
Determine whether the semantic relation where metencephalon is the subject, instance of is the predicate, and embryonic structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where schizophrenia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8451it [28:26,  5.13it/s]

true
Determine whether the semantic relation where aurothioglucose is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycogen phosphorylase L is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

8453it [28:26,  5.08it/s]

true
Determine whether the semantic relation where diethyl pyrocarbonate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Glial cell derived neurotrophic factor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8455it [28:27,  5.26it/s]

true
Determine whether the semantic relation where thrombocytopenic purpura is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nocardiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8457it [28:27,  5.16it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where essential thrombocytosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8459it [28:28,  5.31it/s]

true
Determine whether the semantic relation where Columbiformes is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningioma is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8460it [28:28,  5.45it/s]

true
Determine whether the semantic relation where athlete is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

8462it [28:28,  5.11it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

8464it [28:29,  5.25it/s]

true
Determine whether the semantic relation where clotrimazole is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where picrate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8466it [28:29,  5.05it/s]

true
Determine whether the semantic relation where pectin is the subject, biological process is the predicate, and cell growth is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sphingolipidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8467it [28:29,  5.05it/s]

true
Determine whether the semantic relation where glycogen is the subject, found in taxon is the predicate, and Streptomyces coelicolor is the object constitutes an accurate semantic relation.

8468it [28:29,  4.72it/s]

false
Determine whether the semantic relation where paratyphoid fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8469it [28:30,  4.44it/s]

true
Determine whether the semantic relation where metabolic disease is the subject, afflicts is the predicate, and metabolism is the object constitutes an accurate semantic relation.

8471it [28:30,  4.34it/s]

false
Determine whether the semantic relation where Presenilin-1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

8473it [28:30,  4.76it/s]

true
Determine whether the semantic relation where ventricular septal defect is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adenoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8475it [28:31,  4.61it/s]

true
Determine whether the semantic relation where niclosamide is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8476it [28:31,  4.32it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

8477it [28:31,  4.43it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

8479it [28:32,  4.75it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where renin is the subject, biological process is the predicate, and drinking behavior is the object constitutes an accurate semantic relation.

8481it [28:32,  4.95it/s]

false
Determine whether the semantic relation where pathologic processes is the subject, part of is the predicate, and pathology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

8483it [28:33,  4.95it/s]

true
Determine whether the semantic relation where Wiskott-Aldrich syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

8485it [28:33,  5.08it/s]

true
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

8487it [28:33,  5.30it/s]

true
Determine whether the semantic relation where deoxynucleoside kinase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8489it [28:34,  5.21it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

8490it [28:34,  4.82it/s]

true
Determine whether the semantic relation where CD40 molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8491it [28:34,  4.82it/s]

true
Determine whether the semantic relation where cone cell is the subject, studied by is the predicate, and neuroscience is the object constitutes an accurate semantic relation.

8493it [28:35,  4.68it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 12 is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.

8495it [28:35,  4.97it/s]

false
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glioma is the subject, subclass of is the predicate, and spinal disease is the object constitutes an accurate semantic relation.

8497it [28:35,  5.09it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

8499it [28:36,  5.16it/s]

true
Determine whether the semantic relation where ricin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and tremor is the object constitutes an accurate semantic relation.

8500it [28:36,  4.77it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

8501it [28:36,  4.56it/s]

true
Determine whether the semantic relation where Amylo-alpha-1, 6-glucosidase, 4-alpha-glucanotransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

8503it [28:37,  4.74it/s]

true
Determine whether the semantic relation where lisinopril is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sensation disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8505it [28:37,  5.00it/s]

false
Determine whether the semantic relation where fibromyalgia is the subject, afflicts is the predicate, and joint is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dimercaprol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8506it [28:37,  5.10it/s]

true
Determine whether the semantic relation where heart rate is the subject, part of is the predicate, and cardiology is the object constitutes an accurate semantic relation.

8507it [28:37,  5.03it/s]

false
Determine whether the semantic relation where mucin 5B, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8508it [28:38,  4.64it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

8509it [28:38,  4.64it/s]

true
Determine whether the semantic relation where Ireland is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

8510it [28:38,  4.65it/s]

true
Determine whether the semantic relation where ret proto-oncogene is the subject, biological process is the predicate, and cell adhesion is the object constitutes an accurate semantic relation.

8512it [28:39,  4.76it/s]

false
Determine whether the semantic relation where hemorrhoid is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

8514it [28:39,  4.58it/s]

true
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytidine triphosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8516it [28:39,  4.57it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Perforin 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8517it [28:40,  4.05it/s]

false
Determine whether the semantic relation where serotonin is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

8519it [28:40,  4.42it/s]

false
Determine whether the semantic relation where human is the subject, produced sound is the predicate, and human voice is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Janus kinase 3 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

8521it [28:41,  4.79it/s]

false
Determine whether the semantic relation where lymphatic system is the subject, part of is the predicate, and circulatory system is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where viral skin disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8523it [28:41,  4.91it/s]

true
Determine whether the semantic relation where lipomatosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where picrate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8525it [28:41,  5.08it/s]

true
Determine whether the semantic relation where Saint Lucia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blastoderm is the subject, subclass of is the predicate, and tissue is the object constitutes an accurate semantic relation.

8527it [28:42,  5.01it/s]

false
Determine whether the semantic relation where pancreatitis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diphenhydramine is the subject, side effect is the predicate, and xerostomia is the object constitutes an accurate semantic relation.

8528it [28:42,  5.10it/s]

true
Determine whether the semantic relation where hyperdontia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

8530it [28:42,  5.09it/s]

true
Determine whether the semantic relation where L-isoleucine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Saint Lucia is the object constitutes an accurate semantic relation.

8532it [28:43,  5.23it/s]

true
Determine whether the semantic relation where gonorrhea is the subject, subclass of is the predicate, and eye disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where schizoid personality disorder is the subject, possible treatment is the predicate, and cognitive behavioral therapy is the object constitutes an accurate semantic relation.

8534it [28:43,  5.21it/s]

true
Determine whether the semantic relation where schizoid personality disorder is the subject, drug or therapy used for treatment is the predicate, and cognitive behavioral therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-ascorbic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

8536it [28:44,  5.16it/s]

true
Determine whether the semantic relation where lidocaine is the subject, medical condition treated is the predicate, and mouth disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myeloproliferative disorders is the subject, subclass of is the predicate, and connective tissue neoplasm is the object constitutes an accurate semantic relation.

8538it [28:44,  5.26it/s]

false
Determine whether the semantic relation where spouse is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

8540it [28:44,  5.35it/s]

false
Determine whether the semantic relation where mouth disease is the subject, drug or therapy used for treatment is the predicate, and lidocaine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mauritania is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

8541it [28:44,  5.35it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Mauritania is the object constitutes an accurate semantic relation.

8543it [28:45,  5.04it/s]

true
Determine whether the semantic relation where ovarian hyperstimulation syndrome is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vascular dementia is the subject, has cause is the predicate, and diabetes is the object constitutes an accurate semantic relation.

8545it [28:45,  5.03it/s]

maybe
Determine whether the semantic relation where man is the subject, subclass of is the predicate, and adult is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gastroschisis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

8547it [28:46,  5.23it/s]

false
Determine whether the semantic relation where guanosine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thymidine phosphorylase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

8549it [28:46,  5.12it/s]

false
Determine whether the semantic relation where Q fever is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenoceptor beta 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8550it [28:46,  5.13it/s]

true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8551it [28:46,  4.96it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

8552it [28:47,  4.93it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8554it [28:47,  4.59it/s]

true
Determine whether the semantic relation where vitamin E is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypohidrosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

8555it [28:47,  4.64it/s]

true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

8556it [28:48,  4.72it/s]

true
Determine whether the semantic relation where CD274 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8558it [28:48,  4.91it/s]

true
Determine whether the semantic relation where AT-rich interaction domain 4A is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where physiology is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

8559it [28:48,  5.03it/s]

true
Determine whether the semantic relation where coronavirus disease is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

8561it [28:49,  5.03it/s]

false
Determine whether the semantic relation where Bell's palsy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiotensins is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8563it [28:49,  4.92it/s]

false
Determine whether the semantic relation where cutaneous T cell lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cutaneous T cell lymphoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8565it [28:49,  5.21it/s]

true
Determine whether the semantic relation where migraine is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coccidioidomycosis is the subject, symptoms and signs is the predicate, and arthritis is the object constitutes an accurate semantic relation.

8567it [28:50,  5.32it/s]

true
Determine whether the semantic relation where L-Cysteine is the subject, different from is the predicate, and cytosine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, biological process is the predicate, and embryo implantation is the object constitutes an accurate semantic relation.

8569it [28:50,  5.01it/s]

false
Determine whether the semantic relation where endocarditis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where solute carrier family 7 member 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8571it [28:50,  5.23it/s]

true
Determine whether the semantic relation where pasteurellosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitrofurantoin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8573it [28:51,  5.08it/s]

true
Determine whether the semantic relation where Bahrain is the subject, instance of is the predicate, and island is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

8575it [28:51,  5.11it/s]

true
Determine whether the semantic relation where Sodium voltage-gated channel beta subunit 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where skin is the subject, subclass of is the predicate, and sensory organ is the object constitutes an accurate semantic relation.

8577it [28:52,  4.98it/s]

true
Determine whether the semantic relation where peritoneal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Leber congenital amaurosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8579it [28:52,  5.09it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kartagener syndrome is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

8581it [28:52,  5.31it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and loxapine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where SMAD family member 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8583it [28:53,  5.47it/s]

true
Determine whether the semantic relation where aversion therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aversion therapy is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.

8585it [28:53,  5.34it/s]

true
Determine whether the semantic relation where Cannabinoid receptor 2 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where citrate synthase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8587it [28:54,  5.12it/s]

false
Determine whether the semantic relation where rheumatoid arthritis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

8589it [28:54,  5.09it/s]

true
Determine whether the semantic relation where calcimycin A23187 is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

8591it [28:54,  5.16it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

8593it [28:55,  5.17it/s]

true
Determine whether the semantic relation where infection control is the subject, instance of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sucrose is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

8595it [28:55,  5.18it/s]

false
Determine whether the semantic relation where Piscirickettsia is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, possible treatment is the predicate, and pharmacotherapy is the object constitutes an accurate semantic relation.

8597it [28:56,  5.16it/s]

true
Determine whether the semantic relation where HIV/AIDS is the subject, instance of is the predicate, and endemic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8598it [28:56,  5.18it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

8600it [28:56,  5.15it/s]

true
Determine whether the semantic relation where bruise is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vaginitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

8602it [28:57,  5.19it/s]

true
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.

8604it [28:57,  5.22it/s]

true
Determine whether the semantic relation where suppurative thyroiditis is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8605it [28:57,  5.21it/s]

true
Determine whether the semantic relation where body piercing is the subject, used by is the predicate, and human is the object constitutes an accurate semantic relation.

8607it [28:57,  5.20it/s]

false
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

8609it [28:58,  5.21it/s]

true
Determine whether the semantic relation where phorbol esters is the subject, subclass of is the predicate, and ester is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

8611it [28:58,  5.23it/s]

true
Determine whether the semantic relation where stroke is the subject, health specialty is the predicate, and neurosurgery is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urea is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

8613it [28:59,  5.25it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

8615it [28:59,  5.06it/s]

true
Determine whether the semantic relation where heme oxygenase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false

8616it [28:59,  5.09it/s]

Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

8617it [28:59,  5.09it/s]

true
Determine whether the semantic relation where myeloproliferative disorders is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8619it [29:00,  5.09it/s]

true
Determine whether the semantic relation where myocardial ischemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zalcitabine is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.

8621it [29:00,  5.18it/s]

true
Determine whether the semantic relation where anxiety is the subject, drug or therapy used for treatment is the predicate, and risperidone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where risperidone is the subject, medical condition treated is the predicate, and anxiety is the object constitutes an accurate semantic relation.

8622it [29:00,  5.25it/s]

maybe
Determine whether the semantic relation where taeniasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8624it [29:01,  5.25it/s]

true
Determine whether the semantic relation where migrant is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vagus nerve injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8625it [29:01,  5.24it/s]

false
Determine whether the semantic relation where pseudoaneurysm is the subject, has cause is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

8627it [29:01,  5.16it/s]

maybe
Determine whether the semantic relation where Dystrophin is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ornithosis is the subject, symptoms and signs is the predicate, and polyneuropathy is the object constitutes an accurate semantic relation.

8629it [29:02,  5.22it/s]

false
Determine whether the semantic relation where adenovirus infection is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japanese encephalitis is the subject, drug or therapy used for treatment is the predicate, and D-(-)-mannitol is the object constitutes an accurate semantic relation.

8630it [29:02,  5.24it/s]

false
Determine whether the semantic relation where tetralogy of Fallot is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

8632it [29:02,  5.15it/s]

false
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where natural reservoir is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.

8634it [29:03,  5.30it/s]

false
Determine whether the semantic relation where hepatitis A is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where subacute sclerosing panencephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8636it [29:03,  5.32it/s]

true
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where retinoblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8637it [29:03,  5.12it/s]

true
Determine whether the semantic relation where acromegaly is the subject, comorbidity is the predicate, and type 2 diabetes is the object constitutes an accurate semantic relation.

8638it [29:04,  5.03it/s]

true
Determine whether the semantic relation where cystic fibrosis is the subject, medical examination is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

8639it [29:04,  4.89it/s]

false
Determine whether the semantic relation where peptide YY is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8640it [29:04,  4.83it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.

8642it [29:04,  4.90it/s]

false
Determine whether the semantic relation where complement component C1 complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic condition is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8643it [29:05,  5.03it/s]

true
Determine whether the semantic relation where vulnerable population is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.

8644it [29:05,  4.75it/s]

true
Determine whether the semantic relation where person is the subject, different from is the predicate, and human is the object constitutes an accurate semantic relation.

8646it [29:05,  4.89it/s]

false
Determine whether the semantic relation where Iceland is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Medicago truncatula is the object constitutes an accurate semantic relation.

8647it [29:05,  4.92it/s]

false
Determine whether the semantic relation where traditional medicine is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

8649it [29:06,  5.05it/s]

true
Determine whether the semantic relation where human is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human is the subject, different from is the predicate, and person is the object constitutes an accurate semantic relation.

8651it [29:06,  5.13it/s]

true
Determine whether the semantic relation where febrile neutrophilic dermatosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8653it [29:07,  5.08it/s]

true
Determine whether the semantic relation where Rift Valley fever is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and triamcinolone is the object constitutes an accurate semantic relation.

8654it [29:07,  4.83it/s]

true
Determine whether the semantic relation where tragacanth is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8655it [29:07,  4.70it/s]

false
Determine whether the semantic relation where military dependent is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.

8657it [29:07,  4.82it/s]

true
Determine whether the semantic relation where triamcinolone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where agnosia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

8659it [29:08,  5.03it/s]

false
Determine whether the semantic relation where poliovirus is the subject, significant event is the predicate, and sequencing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where kernicterus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8660it [29:08,  5.01it/s]

true
Determine whether the semantic relation where glutathione is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

8661it [29:08,  4.57it/s]

true
Determine whether the semantic relation where neuritis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

8663it [29:09,  4.76it/s]

true
Determine whether the semantic relation where Federal Trade Commission is the subject, field of work is the predicate, and publishing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where apical granuloma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8664it [29:09,  4.94it/s]

true
Determine whether the semantic relation where perinephritis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8666it [29:09,  5.04it/s]

true
Determine whether the semantic relation where melorheostosis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyaluronic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8668it [29:10,  5.02it/s]

true
Determine whether the semantic relation where Retinol binding protein 4 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vascular endothelial growth factor B is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

8670it [29:10,  5.27it/s]

false
Determine whether the semantic relation where botulism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

8672it [29:10,  5.22it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peptic ulcer disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8674it [29:11,  5.29it/s]

true
Determine whether the semantic relation where ruptured spleen is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Vatican City is the object constitutes an accurate semantic relation.

8676it [29:11,  5.19it/s]

false
Determine whether the semantic relation where diethyltoluamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where D-methamphetamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8677it [29:11,  4.92it/s]

true
Determine whether the semantic relation where Angelman syndrome is the subject, subclass of is the predicate, and organic brain syndrome is the object constitutes an accurate semantic relation.

8678it [29:12,  4.60it/s]

true
Determine whether the semantic relation where personhood is the subject, different from is the predicate, and person is the object constitutes an accurate semantic relation.

8679it [29:12,  4.68it/s]

false
Determine whether the semantic relation where person is the subject, has characteristic is the predicate, and personhood is the object constitutes an accurate semantic relation.

8681it [29:12,  4.72it/s]

false
Determine whether the semantic relation where person is the subject, different from is the predicate, and personhood is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

8682it [29:12,  4.87it/s]

false
Determine whether the semantic relation where REM sleep parasomnia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8684it [29:13,  4.96it/s]

true
Determine whether the semantic relation where arachidonic acid is the subject, found in taxon is the predicate, and Dioscorea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where potassium dichromate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8685it [29:13,  4.91it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

8687it [29:14,  4.85it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Burkitt lymphoma is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

8688it [29:14,  4.95it/s]

true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

8689it [29:14,  4.93it/s]

false
Determine whether the semantic relation where parathyroid hormone like hormone is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8691it [29:14,  4.71it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

8692it [29:15,  4.95it/s]

true
Determine whether the semantic relation where Machado-Joseph disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8694it [29:15,  4.96it/s]

true
Determine whether the semantic relation where Owren's disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

8696it [29:15,  5.15it/s]

true
Determine whether the semantic relation where Lipocalin 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin H is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8698it [29:16,  5.22it/s]

false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystatin A is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8699it [29:16,  5.37it/s]

false
Determine whether the semantic relation where cerebrovascular trauma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8700it [29:16,  5.08it/s]

true
Determine whether the semantic relation where Q82261 is the subject, parent taxon is the predicate, and primate is the object constitutes an accurate semantic relation.

8701it [29:16,  4.74it/s]

true
Determine whether the semantic relation where slipped epiphysis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

8703it [29:17,  4.67it/s]

false
Determine whether the semantic relation where Strepsirrhini is the subject, parent taxon is the predicate, and primate is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where balneology is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

8705it [29:17,  4.96it/s]

true
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, three Ig domains and long cytoplasmic tail 1 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calculus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8706it [29:17,  5.12it/s]

false
Determine whether the semantic relation where phosphorus metabolism disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

8708it [29:18,  5.07it/s]

true
Determine whether the semantic relation where plasminogen activator is the subject, subclass of is the predicate, and aspartate protease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Natural cytotoxicity triggering receptor 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8709it [29:18,  5.17it/s]

true
Determine whether the semantic relation where interleukin 6 receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8711it [29:18,  5.15it/s]

true
Determine whether the semantic relation where stomach rupture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gonorrhea is the subject, symptoms and signs is the predicate, and pelvic pain is the object constitutes an accurate semantic relation.

8712it [29:19,  4.92it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

8714it [29:19,  5.02it/s]

true
Determine whether the semantic relation where dyslexia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dyslexia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8715it [29:19,  4.93it/s]

false
Determine whether the semantic relation where prosopagnosia is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.

8717it [29:20,  4.87it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perphenazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8719it [29:20,  5.01it/s]

true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and spasm is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Greece is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

8720it [29:20,  4.96it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

8721it [29:20,  4.95it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

8722it [29:21,  4.75it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

8724it [29:21,  4.85it/s]

true
Determine whether the semantic relation where β-alanine is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where disease progression is the subject, subclass of is the predicate, and clinical finding is the object constitutes an accurate semantic relation.

8725it [29:21,  4.80it/s]

false
Determine whether the semantic relation where acute kidney injury is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8727it [29:22,  4.83it/s]

true
Determine whether the semantic relation where pemoline is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where child is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.

8729it [29:22,  5.01it/s]

false
Determine whether the semantic relation where teenager is the subject, subclass of is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

8731it [29:22,  5.07it/s]

true
Determine whether the semantic relation where Persian Empire is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hyperthyroidism is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

8733it [29:23,  5.21it/s]

false
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

8734it [29:23,  5.07it/s]

true
Determine whether the semantic relation where anus neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

8736it [29:23,  5.08it/s]

true
Determine whether the semantic relation where chronic granulomatous disease is the subject, subclass of is the predicate, and bone disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where HIV/AIDS is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

8737it [29:24,  5.19it/s]

true
Determine whether the semantic relation where influenza is the subject, has natural reservoir is the predicate, and human is the object constitutes an accurate semantic relation.

8738it [29:24,  5.06it/s]

false
Determine whether the semantic relation where woman is the subject, subclass of is the predicate, and adult is the object constitutes an accurate semantic relation.

8740it [29:24,  4.81it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where solute carrier family 3 member 2 is the subject, part of is the predicate, and glycoside hydrolase superfamily is the object constitutes an accurate semantic relation.

8742it [29:25,  4.98it/s]

false
Determine whether the semantic relation where phenylalanine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitamin B12 deficiency is the subject, symptoms and signs is the predicate, and osteoporosis is the object constitutes an accurate semantic relation.

8744it [29:25,  5.15it/s]

false
Determine whether the semantic relation where nodding disease is the subject, afflicts is the predicate, and human is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alternariosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8746it [29:25,  5.26it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where solute carrier family 12 member 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8747it [29:26,  5.26it/s]

false
Determine whether the semantic relation where coarctation of the aorta is the subject, symptoms and signs is the predicate, and dizziness is the object constitutes an accurate semantic relation.

8749it [29:26,  5.03it/s]

true
Determine whether the semantic relation where cbl proto-oncogene is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

8751it [29:26,  5.00it/s]

true
Determine whether the semantic relation where Nevi and melanomas is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

8752it [29:27,  5.11it/s]

Determine whether the semantic relation where skull fracture is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

8754it [29:27,  5.25it/s]

true
Determine whether the semantic relation where papaverine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where spider bite is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

8756it [29:27,  5.27it/s]

true
Determine whether the semantic relation where cardiac tamponade is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where orangutan is the subject, parent taxon is the predicate, and Hominidae is the object constitutes an accurate semantic relation.

8758it [29:28,  5.22it/s]

true
Determine whether the semantic relation where gonorrhea is the subject, anatomical location is the predicate, and prostate is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chloral hydrate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

8759it [29:28,  4.87it/s]

true
Determine whether the semantic relation where infant respiratory distress syndrome is the subject, health specialty is the predicate, and obstetrics is the object constitutes an accurate semantic relation.

8761it [29:28,  4.60it/s]

false
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nimodipine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8763it [29:29,  4.85it/s]

false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hexosaminidase subunit alpha is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

8764it [29:29,  4.96it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true

8766it [29:29,  5.00it/s]

Determine whether the semantic relation where coccidioidomycosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coccidioidomycosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8767it [29:30,  5.08it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8769it [29:30,  4.86it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 10 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true

8770it [29:30,  4.90it/s]

Determine whether the semantic relation where lentinan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8771it [29:30,  4.99it/s]

true
Determine whether the semantic relation where cerebral hemorrhage is the subject, drug or therapy used for treatment is the predicate, and simvastatin is the object constitutes an accurate semantic relation.

8772it [29:31,  4.80it/s]

false
Determine whether the semantic relation where carbon monoxide is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.

8774it [29:31,  4.87it/s]

false
Determine whether the semantic relation where peracetic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.

8776it [29:31,  4.99it/s]

true
Determine whether the semantic relation where schistosomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where isosorbide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8778it [29:32,  5.12it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where safrole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8780it [29:32,  5.12it/s]

false
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zinc acetate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

8782it [29:33,  5.06it/s]

false
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cross-matching is the subject, subclass of is the predicate, and blood test is the object constitutes an accurate semantic relation.

8783it [29:33,  5.14it/s]

true
Determine whether the semantic relation where foot-and-mouth disease is the subject, symptoms and signs is the predicate, and saliva secretion is the object constitutes an accurate semantic relation.

8784it [29:33,  4.90it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

8785it [29:33,  4.71it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

8786it [29:34,  4.17it/s]

true
Determine whether the semantic relation where BCL6 transcription repressor is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

8787it [29:34,  4.35it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8788it [29:34,  4.36it/s]

false
Determine whether the semantic relation where rosacea is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8790it [29:34,  4.51it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Timor-Leste is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Cordyceps is the object constitutes an accurate semantic relation.

8792it [29:35,  4.55it/s]

false
Determine whether the semantic relation where Timor-Leste is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true

8793it [29:35,  4.72it/s]

Determine whether the semantic relation where veteran is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbohydrate metabolic disorder is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

8794it [29:35,  4.74it/s]

false
Determine whether the semantic relation where World Health Organization is the subject, country is the predicate, and United States is the object constitutes an accurate semantic relation.

8795it [29:36,  4.66it/s]

false
Determine whether the semantic relation where ondansetron is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.

8797it [29:36,  4.85it/s]

true
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and ondansetron is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

8799it [29:36,  4.97it/s]

true
Determine whether the semantic relation where CHARGE syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 2C is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

8801it [29:37,  5.19it/s]

true
Determine whether the semantic relation where oral fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where monocrotaline is the subject, subclass of is the predicate, and macrolides is the object constitutes an accurate semantic relation.

8802it [29:37,  4.90it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 17 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8804it [29:37,  4.81it/s]

true
Determine whether the semantic relation where metronidazole is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8806it [29:38,  5.08it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lysyl oxidase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8807it [29:38,  5.19it/s]

false
Determine whether the semantic relation where United States is the subject, member of is the predicate, and Organization for Economic Cooperation and Development is the object constitutes an accurate semantic relation.

8809it [29:38,  5.15it/s]

true
Determine whether the semantic relation where Korsakoff's syndrome is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Down syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8811it [29:39,  5.19it/s]

true
Determine whether the semantic relation where galactosylceramidase is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Jun proto-oncogene, AP-1 transcription factor subunit is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

8812it [29:39,  5.09it/s]

false
Determine whether the semantic relation where lacrimal duct obstruction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8813it [29:39,  5.02it/s]

true
Determine whether the semantic relation where colorectal polyp is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false

8815it [29:39,  5.13it/s]

Determine whether the semantic relation where intracranial aneurysm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Duchenne muscular dystrophy is the subject, possible treatment is the predicate, and physiotherapy is the object constitutes an accurate semantic relation.

8816it [29:40,  4.86it/s]

true
Determine whether the semantic relation where phosphinic acids is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8817it [29:40,  4.78it/s]

false
Determine whether the semantic relation where 2,2,2-trifluoroethanol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8819it [29:40,  4.47it/s]

true
Determine whether the semantic relation where statistics is the subject, part of is the predicate, and economics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where parathion is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

8821it [29:41,  4.94it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rectal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8823it [29:41,  5.11it/s]

true
Determine whether the semantic relation where cyanocobalamin is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

8825it [29:42,  4.91it/s]

true
Determine whether the semantic relation where morphine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholecystitis is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

8826it [29:42,  4.98it/s]

true
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

8827it [29:42,  4.47it/s]

false
Determine whether the semantic relation where L-citrulline is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

8829it [29:42,  4.72it/s]

false
Determine whether the semantic relation where plantar fasciitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenoceptor beta 3 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

8830it [29:43,  4.72it/s]

false
Determine whether the semantic relation where parathyroid hormone like hormone is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8832it [29:43,  4.82it/s]

true
Determine whether the semantic relation where DL-4-fluorophenylalanine is the subject, subclass of is the predicate, and aromatic compound is the object constitutes an accurate semantic relation.
true

8833it [29:43,  4.90it/s]

Determine whether the semantic relation where campylobacteriosis is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cocaine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8835it [29:44,  5.10it/s]

false
Determine whether the semantic relation where adenosine monophosphate is the subject, found in taxon is the predicate, and Musca domestica is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crohn's disease is the subject, drug or therapy used for treatment is the predicate, and cholecalciferol is the object constitutes an accurate semantic relation.

8836it [29:44,  5.03it/s]

maybe
Determine whether the semantic relation where sarcosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

8837it [29:44,  4.95it/s]

true
Determine whether the semantic relation where Galanin and GMAP prepropeptide is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8838it [29:44,  4.62it/s]

true
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

8840it [29:45,  4.86it/s]

true
Determine whether the semantic relation where butan-1-ol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wolfram syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8842it [29:45,  5.07it/s]

true
Determine whether the semantic relation where medical sociology is the subject, subclass of is the predicate, and public health is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Pancoast tumor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8843it [29:45,  5.08it/s]

true
Determine whether the semantic relation where exhibitionism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8845it [29:46,  5.04it/s]

false
Determine whether the semantic relation where raffinose is the subject, found in taxon is the predicate, and Gossypium is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where milk is the subject, has part(s) is the predicate, and protein is the object constitutes an accurate semantic relation.

8847it [29:46,  5.15it/s]

true
Determine whether the semantic relation where RUNX family transcription factor 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thiamine(1+) ion is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.

8849it [29:46,  5.28it/s]

false
Determine whether the semantic relation where Hermansky-Pudlak syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8850it [29:47,  5.33it/s]

true
Determine whether the semantic relation where Democratic Republic of the Congo is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

8852it [29:47,  5.09it/s]

true
Determine whether the semantic relation where prognosis is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Democratic Republic of the Congo is the object constitutes an accurate semantic relation.

8853it [29:47,  4.80it/s]

true
Determine whether the semantic relation where fasciitis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

8854it [29:48,  4.75it/s]

true
Determine whether the semantic relation where health is the subject, opposite of is the predicate, and disease is the object constitutes an accurate semantic relation.

8856it [29:48,  4.89it/s]

true
Determine whether the semantic relation where disease is the subject, opposite of is the predicate, and health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neutrophil elastase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8857it [29:48,  4.89it/s]

false
Determine whether the semantic relation where guanosine cyclic 3',5'-phosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8859it [29:49,  4.72it/s]

true
Determine whether the semantic relation where Venezuelan equine encephalitis is the subject, anatomical location is the predicate, and spinal cord is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

8861it [29:49,  4.51it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

8862it [29:49,  4.63it/s]

true
Determine whether the semantic relation where basketball is the subject, country of origin is the predicate, and United States is the object constitutes an accurate semantic relation.

8863it [29:49,  4.58it/s]

true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

8864it [29:50,  4.57it/s]

true
Determine whether the semantic relation where G protein-coupled receptor kinase 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8866it [29:50,  4.80it/s]

true
Determine whether the semantic relation where keratin 17 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vagina is the subject, named after is the predicate, and femininity is the object constitutes an accurate semantic relation.

8868it [29:50,  5.07it/s]

false
Determine whether the semantic relation where gonadal tissue neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

8870it [29:51,  4.92it/s]

false
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and DL-methionine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DL-methionine is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.

8872it [29:51,  5.08it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stavudine is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.

8874it [29:52,  5.35it/s]

false
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blood plasma is the subject, has part(s) is the predicate, and glucose is the object constitutes an accurate semantic relation.

8875it [29:52,  4.88it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

8876it [29:52,  4.70it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8877it [29:52,  4.74it/s]

true
Determine whether the semantic relation where pancreatic cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8878it [29:53,  4.62it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

8880it [29:53,  4.67it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where feather is the subject, subclass of is the predicate, and tissue is the object constitutes an accurate semantic relation.

8882it [29:53,  4.59it/s]

false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ancylostomiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8883it [29:54,  4.73it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

8885it [29:54,  4.98it/s]

true
Determine whether the semantic relation where Behçet's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratoconus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8887it [29:54,  5.01it/s]

true
Determine whether the semantic relation where keratoconus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 1A is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8889it [29:55,  5.22it/s]

false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and betamethasone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where betamethasone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

8890it [29:55,  4.67it/s]

true
Determine whether the semantic relation where absence seizure is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

8891it [29:55,  4.56it/s]

true
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

8893it [29:56,  4.41it/s]

true
Determine whether the semantic relation where solute carrier family 1 member 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and bepridil is the object constitutes an accurate semantic relation.

8895it [29:56,  4.87it/s]

true
Determine whether the semantic relation where Greece is the subject, part of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

8896it [29:56,  4.91it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Greece is the object constitutes an accurate semantic relation.

8898it [29:57,  5.01it/s]

false
Determine whether the semantic relation where SMAD family member 7 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperphosphatemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8899it [29:57,  4.79it/s]

true
Determine whether the semantic relation where bepridil is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

8900it [29:57,  4.68it/s]

true
Determine whether the semantic relation where subacute bacterial endocarditis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8902it [29:58,  4.81it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

8904it [29:58,  5.01it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8906it [29:58,  5.05it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

8907it [29:59,  5.04it/s]

true
Determine whether the semantic relation where Ciliophora infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8908it [29:59,  4.98it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8910it [29:59,  4.92it/s]

true
Determine whether the semantic relation where suicidal ideation is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

8911it [29:59,  4.47it/s]

false
Determine whether the semantic relation where systems analysis is the subject, subclass of is the predicate, and scientific method is the object constitutes an accurate semantic relation.

8912it [30:00,  4.49it/s]

false
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false

8914it [30:00,  4.83it/s]

Determine whether the semantic relation where IL-2 receptor is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where failure analysis is the subject, subclass of is the predicate, and risk assessment is the object constitutes an accurate semantic relation.

8915it [30:00,  4.59it/s]

false
Determine whether the semantic relation where galactosylceramidase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

8917it [30:01,  4.78it/s]

false
Determine whether the semantic relation where renovascular hypertension is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where renovascular hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8919it [30:01,  5.03it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tumor necrosis factor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

8920it [30:01,  5.09it/s]

true
Determine whether the semantic relation where 17α-hydroxyprogesterone is the subject, medical condition treated is the predicate, and endometriosis is the object constitutes an accurate semantic relation.

8921it [30:02,  4.96it/s]

false
Determine whether the semantic relation where endometriosis is the subject, drug or therapy used for treatment is the predicate, and 17α-hydroxyprogesterone is the object constitutes an accurate semantic relation.

8922it [30:02,  4.75it/s]

false
Determine whether the semantic relation where crystallins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

8924it [30:02,  4.76it/s]

false
Determine whether the semantic relation where vulvitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Holosporaceae is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.

8926it [30:03,  4.85it/s]

true
Determine whether the semantic relation where chlamydia infection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where troponin complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

8927it [30:03,  4.86it/s]

false
Determine whether the semantic relation where nephritis is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

8928it [30:03,  4.80it/s]

false
Determine whether the semantic relation where tooth loss is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

8929it [30:03,  4.75it/s]

false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

8931it [30:04,  4.82it/s]

true
Determine whether the semantic relation where hydroxymethylbilane synthase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Ganoderma lucidum is the object constitutes an accurate semantic relation.

8932it [30:04,  4.57it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

8933it [30:04,  4.51it/s]

true
Determine whether the semantic relation where common cold is the subject, symptoms and signs is the predicate, and tinnitus is the object constitutes an accurate semantic relation.

8934it [30:04,  4.58it/s]

false
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

8936it [30:05,  4.74it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tendon injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

8937it [30:05,  4.79it/s]

false
Determine whether the semantic relation where Addison's disease is the subject, subclass of is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.

8938it [30:05,  4.63it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

8939it [30:05,  4.64it/s]

true
Determine whether the semantic relation where myalgic encephalomyelitis/chronic fatigue syndrome is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

8940it [30:06,  4.61it/s]

false
Determine whether the semantic relation where hypersensitivity is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8942it [30:06,  4.67it/s]

true
Determine whether the semantic relation where POU class 4 homeobox 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where respiratory disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8943it [30:06,  4.77it/s]

true
Determine whether the semantic relation where interstitial lung disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

8944it [30:07,  4.45it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

8946it [30:07,  4.59it/s]

true
Determine whether the semantic relation where Interleukin 18 receptor accessory protein is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where toxocariasis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

8948it [30:07,  4.96it/s]

true
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and (±)-promethazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (±)-promethazine is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.

8949it [30:08,  4.81it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

8950it [30:08,  4.85it/s]

true
Determine whether the semantic relation where Dominica is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

8952it [30:08,  4.93it/s]

true
Determine whether the semantic relation where pim-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8953it [30:08,  5.05it/s]

true
Determine whether the semantic relation where Connecticut is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true

8954it [30:09,  5.02it/s]

Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Dominica is the object constitutes an accurate semantic relation.

8955it [30:09,  4.80it/s]

true
Determine whether the semantic relation where Central African Republic is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

8956it [30:09,  4.81it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.

8957it [30:09,  4.74it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

8959it [30:10,  4.83it/s]

true
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where citric acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8961it [30:10,  5.16it/s]

true
Determine whether the semantic relation where MEDLINE is the subject, main subject is the predicate, and health is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

8962it [30:10,  5.03it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

8963it [30:10,  4.57it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 5 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8964it [30:11,  4.59it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

8965it [30:11,  4.24it/s]

true
Determine whether the semantic relation where adrenomedullin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

8966it [30:11,  4.33it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

8967it [30:11,  4.45it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

8969it [30:12,  4.73it/s]

true
Determine whether the semantic relation where choline O-acetyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

8971it [30:12,  4.90it/s]

true
Determine whether the semantic relation where adenosine monophosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholera is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8973it [30:13,  5.14it/s]

true
Determine whether the semantic relation where vitamin K deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitamin K deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

8975it [30:13,  5.21it/s]

true
Determine whether the semantic relation where May–Thurner syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

8976it [30:13,  5.15it/s]

true
Determine whether the semantic relation where Gamma-butyrobetaine hydroxylase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

8978it [30:14,  5.11it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

8979it [30:14,  4.75it/s]

true
Determine whether the semantic relation where Q fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

8981it [30:14,  4.76it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protein tyrosine kinase 2 beta is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

8983it [30:15,  4.91it/s]

false
Determine whether the semantic relation where chlorpyrifos is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

8985it [30:15,  5.00it/s]

false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, afflicts is the predicate, and lung is the object constitutes an accurate semantic relation.

8986it [30:15,  5.18it/s]

false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

8987it [30:15,  4.91it/s]

true
Determine whether the semantic relation where Charcot–Marie–Tooth disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

8989it [30:16,  4.95it/s]

true
Determine whether the semantic relation where Phospholipase A2 receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

8990it [30:16,  5.11it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and United States is the object constitutes an accurate semantic relation.

8991it [30:16,  5.03it/s]

false
Determine whether the semantic relation where United States is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true

8993it [30:17,  5.14it/s]

Determine whether the semantic relation where Amphiregulin is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where agar is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8994it [30:17,  4.81it/s]

false
Determine whether the semantic relation where acetylcarnitine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

8995it [30:17,  4.84it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

8997it [30:17,  4.95it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fli-1 proto-oncogene, ETS transcription factor is the subject, biological process is the predicate, and hemostasis is the object constitutes an accurate semantic relation.

8999it [30:18,  5.18it/s]

false
Determine whether the semantic relation where seafood poisoning is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9000it [30:18,  4.89it/s]

true
Determine whether the semantic relation where neurotoxic disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9002it [30:18,  4.77it/s]

true
Determine whether the semantic relation where aortic aneurysm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where St. Louis encephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9004it [30:19,  4.97it/s]

true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nifedipine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9005it [30:19,  5.02it/s]

false
Determine whether the semantic relation where pre-malignant neoplasm is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9007it [30:19,  5.10it/s]

true
Determine whether the semantic relation where hypovolemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where geographic information system is the subject, has use is the predicate, and criminology is the object constitutes an accurate semantic relation.

9009it [30:20,  4.75it/s]

true
Determine whether the semantic relation where MET proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where blood test is the subject, is the study of is the predicate, and blood is the object constitutes an accurate semantic relation.

9011it [30:20,  5.03it/s]

false
Determine whether the semantic relation where sleep is the subject, facet of is the predicate, and health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and basement membrane is the object constitutes an accurate semantic relation.

9012it [30:20,  5.13it/s]

true
Determine whether the semantic relation where diketopiperazine is the subject, subclass of is the predicate, and lactam is the object constitutes an accurate semantic relation.

9014it [30:21,  5.04it/s]

true
Determine whether the semantic relation where glycogen storage disease I is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatoerythropoietic porphyria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9016it [30:21,  4.85it/s]

true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where India is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.

9018it [30:22,  5.08it/s]

false
Determine whether the semantic relation where peptidoglycan is the subject, subclass of is the predicate, and glycosaminoglycan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and skin is the object constitutes an accurate semantic relation.

9020it [30:22,  5.12it/s]

false
Determine whether the semantic relation where spermine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where delayed diagnosis is the subject, facet of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

9022it [30:22,  5.14it/s]

false
Determine whether the semantic relation where Poly(A) binding protein nuclear 1 is the subject, biological process is the predicate, and muscle contraction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neurotensin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9024it [30:23,  4.96it/s]

false
Determine whether the semantic relation where agenesis of the corpus callosum is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where herpes zoster is the subject, anatomical location is the predicate, and nervous system is the object constitutes an accurate semantic relation.

9025it [30:23,  5.08it/s]

true
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

9027it [30:23,  5.14it/s]

true
Determine whether the semantic relation where Gerstmann-Straussler-Scheinker syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where giant cell arteritis is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

9029it [30:24,  5.20it/s]

true
Determine whether the semantic relation where Turkey is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Arnold-Chiari malformation is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9031it [30:24,  5.26it/s]

true
Determine whether the semantic relation where aluminum hydroxide is the subject, has use is the predicate, and flame retardant is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Finland is the object constitutes an accurate semantic relation.

9032it [30:24,  5.15it/s]

false
Determine whether the semantic relation where CD7 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9034it [30:25,  5.18it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

9036it [30:25,  5.15it/s]

true
Determine whether the semantic relation where ginger is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

9037it [30:25,  4.86it/s]

true
Determine whether the semantic relation where programmed cell death 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9039it [30:26,  4.88it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycerol is the subject, medical condition treated is the predicate, and constipation is the object constitutes an accurate semantic relation.

9041it [30:26,  5.13it/s]

true
Determine whether the semantic relation where constipation is the subject, drug or therapy used for treatment is the predicate, and glycerol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

9042it [30:26,  4.85it/s]

true
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

9044it [30:27,  4.94it/s]

true
Determine whether the semantic relation where Uroplakin 3A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where furunculosis is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

9045it [30:27,  5.07it/s]

false
Determine whether the semantic relation where hemorrhagic shock is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9046it [30:27,  4.97it/s]

true
Determine whether the semantic relation where Ireland is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

9047it [30:28,  4.42it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

9049it [30:28,  4.63it/s]

false
Determine whether the semantic relation where genu varum is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

9050it [30:28,  4.67it/s]

true
Determine whether the semantic relation where risk is the subject, facet of is the predicate, and decision making is the object constitutes an accurate semantic relation.
false

9051it [30:28,  4.75it/s]

Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

9053it [30:29,  4.85it/s]

true
Determine whether the semantic relation where carotid-cavernous fistula is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where disease is the subject, has effect is the predicate, and death is the object constitutes an accurate semantic relation.

9054it [30:29,  4.96it/s]

true
Determine whether the semantic relation where carboplatin is the subject, subject has role is the predicate, and cross-linking reagent is the object constitutes an accurate semantic relation.

9055it [30:29,  4.55it/s]

true
Determine whether the semantic relation where myoglobinuria is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9056it [30:29,  4.40it/s]

true
Determine whether the semantic relation where Atropa bella-donna is the subject, has part(s) of the class is the predicate, and flower is the object constitutes an accurate semantic relation.

9057it [30:30,  4.40it/s]

true
Determine whether the semantic relation where camphor is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

9059it [30:30,  3.93it/s]

false
Determine whether the semantic relation where time-lapse is the subject, subclass of is the predicate, and video recording is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acne is the subject, does not have cause is the predicate, and masturbation is the object constitutes an accurate semantic relation.

9060it [30:31,  3.82it/s]

true
Determine whether the semantic relation where pulmonary fibrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9061it [30:31,  3.60it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and buttocks is the object constitutes an accurate semantic relation.

9063it [30:31,  4.18it/s]

true
Determine whether the semantic relation where isopropyl β-D-thiogalactopyranoside is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9064it [30:32,  4.32it/s]

true
Determine whether the semantic relation where balanitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9065it [30:32,  4.41it/s]

true
Determine whether the semantic relation where ret proto-oncogene is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9066it [30:32,  4.43it/s]

true
Determine whether the semantic relation where choline is the subject, found in taxon is the predicate, and Urtica dioica is the object constitutes an accurate semantic relation.

9068it [30:32,  4.21it/s]

false
Determine whether the semantic relation where Nuclear factor kappa B subunit 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Parry–Romberg syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9069it [30:33,  4.50it/s]

true
Determine whether the semantic relation where Erwinia amylovora is the subject, has natural reservoir is the predicate, and insect is the object constitutes an accurate semantic relation.

9071it [30:33,  4.11it/s]

false
Determine whether the semantic relation where local neoplasm recurrence is the subject, subclass of is the predicate, and relapse is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

9073it [30:34,  4.31it/s]

false
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

9074it [30:34,  4.60it/s]

true
Determine whether the semantic relation where tert-butyl hydroperoxide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9076it [30:34,  4.78it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Amphibia is the subject, main food source is the predicate, and Q1358 is the object constitutes an accurate semantic relation.

9077it [30:34,  4.77it/s]

false
Determine whether the semantic relation where sertraline is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

9078it [30:35,  4.54it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and sertraline is the object constitutes an accurate semantic relation.

9079it [30:35,  4.04it/s]

true
Determine whether the semantic relation where uridine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

9081it [30:35,  4.50it/s]

false
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

9083it [30:36,  4.73it/s]

false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 3 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Passeridae is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

9085it [30:36,  4.96it/s]

true
Determine whether the semantic relation where functional gastrointestinal disorder is the subject, drug or therapy used for treatment is the predicate, and prednisolone is the object constitutes an accurate semantic relation.
false

9086it [30:36,  4.98it/s]

Determine whether the semantic relation where subarachnoid hemorrhage is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prednisolone is the subject, medical condition treated is the predicate, and functional gastrointestinal disorder is the object constitutes an accurate semantic relation.

9087it [30:37,  4.50it/s]

false
Determine whether the semantic relation where abnormal uterine bleeding is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9088it [30:37,  4.32it/s]

false
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

9090it [30:37,  4.63it/s]

false
Determine whether the semantic relation where transposition of great vessels is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

9091it [30:38,  4.86it/s]

false
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

9093it [30:38,  5.03it/s]

false
Determine whether the semantic relation where L-tyrosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where biliverdin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9095it [30:38,  5.07it/s]

true
Determine whether the semantic relation where Western equine encephalitis is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 2,3-diphosphoglyceric acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

9097it [30:39,  5.01it/s]

true
Determine whether the semantic relation where protein tyrosine phosphatase non-receptor type 6 is the subject, biological process is the predicate, and platelet aggregation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sleep-wake disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9099it [30:39,  5.01it/s]

false
Determine whether the semantic relation where rheumatoid nodule is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lepromatous leprosy is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9100it [30:39,  5.08it/s]

true
Determine whether the semantic relation where chlorpyrifos is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9101it [30:40,  4.84it/s]

true
Determine whether the semantic relation where hemorrhoid is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

9103it [30:40,  4.94it/s]

true
Determine whether the semantic relation where limb-girdle muscular dystrophy is the subject, possible treatment is the predicate, and occupational therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dysplastic nevus syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

9104it [30:40,  4.94it/s]

true
Determine whether the semantic relation where myocardial stunning is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9106it [30:41,  4.86it/s]

true
Determine whether the semantic relation where integrin subunit beta 1 is the subject, cell component is the predicate, and neuromuscular junction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nicergoline is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

9108it [30:41,  5.10it/s]

false
Determine whether the semantic relation where HIV-associated lipodystrophy is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fungal infectious disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9109it [30:41,  5.07it/s]

true
Determine whether the semantic relation where glucagon is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9110it [30:41,  4.82it/s]

false
Determine whether the semantic relation where Allium sativum is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

9112it [30:42,  4.91it/s]

false
Determine whether the semantic relation where aminolevulinic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alpha fetoprotein is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9114it [30:42,  4.57it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pharmacy is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.

9115it [30:42,  4.76it/s]

false
Determine whether the semantic relation where coarctation of the aorta is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

9117it [30:43,  4.90it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Papua New Guinea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

9118it [30:43,  3.98it/s]

true
Determine whether the semantic relation where organic compound, having C-P covalent bound is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9119it [30:43,  4.18it/s]

true
Determine whether the semantic relation where translation is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

9121it [30:44,  4.36it/s]

false
Determine whether the semantic relation where amyotrophic lateral sclerosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Papua New Guinea is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

9122it [30:44,  4.48it/s]

false
Determine whether the semantic relation where Turkey is the subject, continent is the predicate, and Europe is the object constitutes an accurate semantic relation.

9123it [30:44,  4.58it/s]

maybe
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9124it [30:44,  4.65it/s]

true
Determine whether the semantic relation where homogentisic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9125it [30:45,  4.57it/s]

false
Determine whether the semantic relation where National Institute of Biomedical Imaging and Bioengineering is the subject, field of work is the predicate, and medical imaging is the object constitutes an accurate semantic relation.

9126it [30:45,  4.29it/s]

true
Determine whether the semantic relation where female organism is the subject, does not have part is the predicate, and Y chromosome is the object constitutes an accurate semantic relation.

9127it [30:45,  4.39it/s]

true
Determine whether the semantic relation where DL-lactic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

9128it [30:45,  4.43it/s]

false
Determine whether the semantic relation where peptide is the subject, subclass of is the predicate, and carboxamides is the object constitutes an accurate semantic relation.

9129it [30:46,  4.46it/s]

false
Determine whether the semantic relation where Seychelles is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

9130it [30:46,  4.55it/s]

true
Determine whether the semantic relation where mannitol dehydrogenase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9131it [30:46,  4.65it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Seychelles is the object constitutes an accurate semantic relation.

9132it [30:46,  4.71it/s]

true
Determine whether the semantic relation where gallic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9133it [30:46,  4.66it/s]

true
Determine whether the semantic relation where Werner syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9135it [30:47,  4.83it/s]

true
Determine whether the semantic relation where MYB is the subject, expressed in is the predicate, and thymus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and fluocinonide is the object constitutes an accurate semantic relation.

9136it [30:47,  5.02it/s]

true
Determine whether the semantic relation where fluocinonide is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

9138it [30:47,  4.94it/s]

true
Determine whether the semantic relation where amebiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD44 molecule (Indian blood group) is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

9140it [30:48,  5.18it/s]

false
Determine whether the semantic relation where systemic lupus erythematosus is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where C-C motif chemokine ligand 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9142it [30:48,  5.16it/s]

false
Determine whether the semantic relation where Keratin 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where obturator hernia is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

9143it [30:48,  5.07it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

9145it [30:49,  5.11it/s]

true
Determine whether the semantic relation where yohimbine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where radiology is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

9147it [30:49,  5.00it/s]

false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metabolic brain disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9148it [30:49,  5.05it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

9149it [30:50,  4.84it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

9150it [30:50,  4.75it/s]

true
Determine whether the semantic relation where estrogen receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9151it [30:50,  4.47it/s]

false
Determine whether the semantic relation where lipedema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9152it [30:50,  4.60it/s]

true
Determine whether the semantic relation where laryngeal tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9154it [30:51,  4.78it/s]

true
Determine whether the semantic relation where cefoxitin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MYC is the subject, expressed in is the predicate, and gastric mucosa is the object constitutes an accurate semantic relation.

9156it [30:51,  5.04it/s]

false
Determine whether the semantic relation where choline is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paratyphoid fever is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

9158it [30:52,  5.21it/s]

maybe
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

9159it [30:52,  5.32it/s]

true
Determine whether the semantic relation where Lambert-Eaton myasthenic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9161it [30:52,  5.16it/s]

true
Determine whether the semantic relation where cellular communication network factor 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where allantoin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9162it [30:52,  4.87it/s]

true
Determine whether the semantic relation where Lassa fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9163it [30:53,  4.64it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

9165it [30:53,  4.62it/s]

true
Determine whether the semantic relation where herpes simplex virus keratitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where periodontal abscess is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9166it [30:53,  4.77it/s]

true
Determine whether the semantic relation where human serum albumin is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

9167it [30:53,  4.58it/s]

false
Determine whether the semantic relation where otitis media is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9168it [30:54,  4.57it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

9170it [30:54,  4.87it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Turkey is the object constitutes an accurate semantic relation.

9172it [30:54,  4.93it/s]

false
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Turkey is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

9173it [30:55,  5.03it/s]

true
Determine whether the semantic relation where pre-eclampsia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9174it [30:55,  4.93it/s]

true
Determine whether the semantic relation where chlorisondamine(2+) is the subject, subclass of is the predicate, and ion is the object constitutes an accurate semantic relation.

9175it [30:55,  4.66it/s]

true
Determine whether the semantic relation where CD70 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9176it [30:55,  4.24it/s]

true
Determine whether the semantic relation where nandrolone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9178it [30:56,  4.63it/s]

true
Determine whether the semantic relation where Adenylate cyclase activating polypeptide 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echinococcosis is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

9179it [30:56,  4.24it/s]

false
Determine whether the semantic relation where endometritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9180it [30:56,  4.16it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

9181it [30:57,  3.67it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

9183it [30:57,  4.22it/s]

true
Determine whether the semantic relation where glycogen storage disease I is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

9185it [30:57,  4.72it/s]

true
Determine whether the semantic relation where intracranial embolism and thrombosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sturge–Weber syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

9186it [30:58,  4.86it/s]

true
Determine whether the semantic relation where Minnesota is the subject, shares border with is the predicate, and Ontario is the object constitutes an accurate semantic relation.

9187it [30:58,  4.88it/s]

true
Determine whether the semantic relation where D-mannopyranose is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

9189it [30:58,  4.96it/s]

false
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 1-octanol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

9190it [30:58,  4.75it/s]

false
Determine whether the semantic relation where vascular endothelial growth factor D is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9191it [30:59,  4.61it/s]

true
Determine whether the semantic relation where cyclamate is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

9193it [30:59,  4.83it/s]

true
Determine whether the semantic relation where clinical trial is the subject, follows is the predicate, and pre-clinical development is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ontario is the subject, shares border with is the predicate, and Minnesota is the object constitutes an accurate semantic relation.

9194it [30:59,  4.80it/s]

true
Determine whether the semantic relation where pre-clinical development is the subject, followed by is the predicate, and clinical trial is the object constitutes an accurate semantic relation.

9195it [31:00,  4.70it/s]

false
Determine whether the semantic relation where medulloblastoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9197it [31:00,  4.85it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and hip is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where liver neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

9198it [31:00,  4.97it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

9199it [31:00,  4.62it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

9200it [31:01,  4.48it/s]

true
Determine whether the semantic relation where Circoviridae infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9202it [31:01,  4.79it/s]

false
Determine whether the semantic relation where amelanotic melanoma is the subject, drug or therapy used for treatment is the predicate, and cisplatin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cisplatin is the subject, medical condition treated is the predicate, and amelanotic melanoma is the object constitutes an accurate semantic relation.

9203it [31:01,  4.74it/s]

false
Determine whether the semantic relation where pseudopregnancy is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

9204it [31:01,  4.71it/s]

true
Determine whether the semantic relation where poly(G) is the subject, subclass of is the predicate, and polymer is the object constitutes an accurate semantic relation.

9205it [31:02,  4.68it/s]

true
Determine whether the semantic relation where uroplakin 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9207it [31:02,  4.80it/s]

true
Determine whether the semantic relation where mediastinal cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9208it [31:02,  4.90it/s]

false
Determine whether the semantic relation where celiac disease is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

9209it [31:02,  4.90it/s]

true
Determine whether the semantic relation where hemianopia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9210it [31:03,  4.83it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Rwanda is the object constitutes an accurate semantic relation.

9211it [31:03,  4.44it/s]

true
Determine whether the semantic relation where infertility is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

9212it [31:03,  4.58it/s]

Determine whether the semantic relation where Rwanda is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

9214it [31:04,  4.52it/s]

true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, subject has role is the predicate, and antiviral agent is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

9215it [31:04,  4.38it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

9216it [31:04,  4.50it/s]

true
Determine whether the semantic relation where pain is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9218it [31:04,  4.74it/s]

false
Determine whether the semantic relation where anorexia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anorexia is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

9220it [31:05,  4.85it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

9221it [31:05,  4.76it/s]

true
Determine whether the semantic relation where type 2 diabetes is the subject, symptoms and signs is the predicate, and polyphagia is the object constitutes an accurate semantic relation.

9222it [31:05,  4.37it/s]

true
Determine whether the semantic relation where luteinizing hormone/choriogonadotropin receptor is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

9223it [31:06,  4.24it/s]

true
Determine whether the semantic relation where ketose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9225it [31:06,  4.59it/s]

true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Yugoslavia is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.

9226it [31:06,  4.56it/s]

false
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

9227it [31:06,  4.67it/s]

true
Determine whether the semantic relation where sterol is the subject, subclass of is the predicate, and alcohols is the object constitutes an accurate semantic relation.

9228it [31:07,  4.67it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

9229it [31:07,  4.66it/s]

true
Determine whether the semantic relation where Jun proto-oncogene, AP-1 transcription factor subunit is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

9231it [31:07,  4.84it/s]

maybe
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dehydration is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

9232it [31:08,  4.87it/s]

false
Determine whether the semantic relation where dracunculiasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

9234it [31:08,  5.01it/s]

true
Determine whether the semantic relation where polyethylene terephthalate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Collagen type XVIII [endoplasmic reticulum lumen] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

9236it [31:08,  4.95it/s]

false
Determine whether the semantic relation where ribonuclease A family member 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where motion sickness is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9238it [31:09,  5.17it/s]

false
Determine whether the semantic relation where zygote is the subject, subclass of is the predicate, and eukaryotic cell is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dental leakage is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

9239it [31:09,  5.03it/s]

false
Determine whether the semantic relation where submandibular gland disease is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

9241it [31:09,  4.98it/s]

true
Determine whether the semantic relation where aspirin is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and aspirin is the object constitutes an accurate semantic relation.

9242it [31:10,  4.71it/s]

true
Determine whether the semantic relation where chronic arterial occlusive disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9243it [31:10,  4.60it/s]

true
Determine whether the semantic relation where reproducibility is the subject, part of is the predicate, and scientific method is the object constitutes an accurate semantic relation.

9244it [31:10,  4.36it/s]

false
Determine whether the semantic relation where Major histocompatibility complex, class II, DQ alpha 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9245it [31:10,  4.39it/s]

true
Determine whether the semantic relation where ethylene oxide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9247it [31:11,  4.69it/s]

true
Determine whether the semantic relation where sudden sensorineural hearing loss is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and blindness is the object constitutes an accurate semantic relation.

9248it [31:11,  4.80it/s]

true
Determine whether the semantic relation where gout is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

9249it [31:11,  4.79it/s]

true
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and gout is the object constitutes an accurate semantic relation.

9251it [31:11,  4.90it/s]

true
Determine whether the semantic relation where calcium metabolism disease is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cardiopulmonary resuscitation is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.

9252it [31:12,  4.93it/s]

true
Determine whether the semantic relation where eicosapentaenoic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9253it [31:12,  4.90it/s]

true
Determine whether the semantic relation where cannabis abuse is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

9254it [31:12,  4.74it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

9255it [31:12,  4.73it/s]

false
Determine whether the semantic relation where Phosphofructokinase, muscle is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9257it [31:13,  4.45it/s]

false
Determine whether the semantic relation where reality therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tuberculous peritonitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9258it [31:13,  4.69it/s]

true
Determine whether the semantic relation where legionnaires' disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9259it [31:13,  4.49it/s]

true
Determine whether the semantic relation where burn is the subject, drug or therapy used for treatment is the predicate, and lidocaine is the object constitutes an accurate semantic relation.

9261it [31:14,  4.73it/s]

true
Determine whether the semantic relation where lidocaine is the subject, medical condition treated is the predicate, and burn is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

9263it [31:14,  4.86it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cloxacillin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

9264it [31:14,  4.71it/s]

false
Determine whether the semantic relation where phenylalanine is the subject, found in taxon is the predicate, and Perilla frutescens is the object constitutes an accurate semantic relation.
false

9265it [31:14,  4.78it/s]

Determine whether the semantic relation where nephrosclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9267it [31:15,  4.79it/s]

true
Determine whether the semantic relation where pheromone is the subject, named after is the predicate, and hormone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pseudomembranous colitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

9268it [31:15,  4.89it/s]

true
Determine whether the semantic relation where central nervous system bacterial infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9270it [31:16,  4.91it/s]

true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9272it [31:16,  5.22it/s]

false
Determine whether the semantic relation where nasopharyngeal neoplasm is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thioredoxin reductase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

9273it [31:16,  4.95it/s]

true
Determine whether the semantic relation where traumatic intracranial hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9275it [31:17,  4.87it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yohimbine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

9277it [31:17,  4.99it/s]

true
Determine whether the semantic relation where neuroaspergillosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and halcinonide is the object constitutes an accurate semantic relation.

9279it [31:17,  5.06it/s]

true
Determine whether the semantic relation where halcinonide is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

9281it [31:18,  5.10it/s]

true
Determine whether the semantic relation where integrin subunit beta 1 is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where metal poisoning is the subject, has effect is the predicate, and miscarriage is the object constitutes an accurate semantic relation.

9282it [31:18,  5.21it/s]

true
Determine whether the semantic relation where amsacrine is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

9283it [31:18,  5.11it/s]

true
Determine whether the semantic relation where selenoprotein W is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9284it [31:18,  4.84it/s]

true
Determine whether the semantic relation where Rift Valley fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9286it [31:19,  4.92it/s]

true
Determine whether the semantic relation where dermatomyositis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

9287it [31:19,  5.09it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

9289it [31:19,  4.66it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where obesity is the subject, drug or therapy used for treatment is the predicate, and (+)-norephedrin is the object constitutes an accurate semantic relation.

9291it [31:20,  4.84it/s]

false
Determine whether the semantic relation where gene is the subject, subject has role is the predicate, and heredity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (+)-norephedrin is the subject, medical condition treated is the predicate, and obesity is the object constitutes an accurate semantic relation.

9292it [31:20,  4.97it/s]

false
Determine whether the semantic relation where Ureaplasma infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9294it [31:20,  5.05it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylthiouracil is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

9296it [31:21,  5.15it/s]

true
Determine whether the semantic relation where amylose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where transforming growth factor beta 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9298it [31:21,  5.18it/s]

true
Determine whether the semantic relation where cobalt is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

9300it [31:22,  5.30it/s]

true
Determine whether the semantic relation where bias is the subject, handled, mitigated, or managed by is the predicate, and blind experiment is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fibroblast growth factor 9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9301it [31:22,  5.28it/s]

false
Determine whether the semantic relation where tetraethyllead is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9302it [31:22,  5.11it/s]

true
Determine whether the semantic relation where guanethidine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9303it [31:22,  4.99it/s]

false
Determine whether the semantic relation where functional gastrointestinal disorder is the subject, drug or therapy used for treatment is the predicate, and prednisone is the object constitutes an accurate semantic relation.

9305it [31:23,  4.71it/s]

false
Determine whether the semantic relation where museum is the subject, subject has role is the predicate, and research is the object constitutes an accurate semantic relation.
false

9306it [31:23,  4.77it/s]

Determine whether the semantic relation where coronaropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prednisone is the subject, medical condition treated is the predicate, and functional gastrointestinal disorder is the object constitutes an accurate semantic relation.

9308it [31:23,  5.02it/s]

false
Determine whether the semantic relation where developmental coordination disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where promazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9309it [31:23,  5.01it/s]

true
Determine whether the semantic relation where cycloserine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

9310it [31:24,  4.99it/s]

true
Determine whether the semantic relation where brain ischemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9311it [31:24,  4.80it/s]

true
Determine whether the semantic relation where neuralgia is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

9312it [31:24,  4.51it/s]

false
Determine whether the semantic relation where trifluoperazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

9314it [31:24,  4.74it/s]

true
Determine whether the semantic relation where adrenomedullin receptor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

9316it [31:25,  4.92it/s]

true
Determine whether the semantic relation where bleeding is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fosfomycin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

9317it [31:25,  4.76it/s]

true
Determine whether the semantic relation where interleukin 6 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9319it [31:25,  4.91it/s]

true
Determine whether the semantic relation where neuron is the subject, has part(s) is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Colony stimulating factor 3 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9321it [31:26,  5.02it/s]

true
Determine whether the semantic relation where Guanidinoacetate N-methyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Monaco is the object constitutes an accurate semantic relation.

9322it [31:26,  5.09it/s]

true
Determine whether the semantic relation where Monaco is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

9323it [31:26,  4.13it/s]

true
Determine whether the semantic relation where jet lag is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

9325it [31:27,  4.46it/s]

true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

9327it [31:27,  4.73it/s]

false
Determine whether the semantic relation where hemoperitoneum is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cannabinoid receptor 1 is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

9328it [31:27,  4.81it/s]

true
Determine whether the semantic relation where blood urea nitrogen is the subject, anatomical location is the predicate, and blood is the object constitutes an accurate semantic relation.

9329it [31:28,  4.64it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Rwanda is the object constitutes an accurate semantic relation.

9330it [31:28,  4.58it/s]

true
Determine whether the semantic relation where Rwanda is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

9331it [31:28,  4.57it/s]

true
Determine whether the semantic relation where vulvovaginal candidiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9332it [31:28,  4.41it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

9333it [31:29,  4.38it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

9335it [31:29,  4.54it/s]

true
Determine whether the semantic relation where bulimia nervosa is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

9337it [31:29,  4.42it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eating disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.

9338it [31:30,  4.51it/s]

false
Determine whether the semantic relation where fern is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.

9339it [31:30,  4.59it/s]

maybe
Determine whether the semantic relation where gnathomiasis is the subject, has natural reservoir is the predicate, and Felidae is the object constitutes an accurate semantic relation.

9340it [31:30,  4.58it/s]

false
Determine whether the semantic relation where autoimmune disease is the subject, drug or therapy used for treatment is the predicate, and dexamethasone is the object constitutes an accurate semantic relation.

9341it [31:30,  4.60it/s]

true
Determine whether the semantic relation where norethisterone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
false

9342it [31:31,  4.69it/s]

Determine whether the semantic relation where drinking is the subject, uses is the predicate, and mouth is the object constitutes an accurate semantic relation.

9344it [31:31,  4.84it/s]

false
Determine whether the semantic relation where Ohio is the subject, shares border with is the predicate, and Ontario is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serpin family G member 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

9346it [31:31,  5.07it/s]

false
Determine whether the semantic relation where encephalomalacia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ontario is the subject, shares border with is the predicate, and Ohio is the object constitutes an accurate semantic relation.

9348it [31:32,  5.14it/s]

true
Determine whether the semantic relation where gossypol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, drug or therapy used for treatment is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

9349it [31:32,  5.15it/s]

false
Determine whether the semantic relation where spinal stenosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9351it [31:32,  5.14it/s]

true
Determine whether the semantic relation where dexamethasone is the subject, medical condition treated is the predicate, and autoimmune disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protochlorophyllide is the subject, has part(s) is the predicate, and magnesium is the object constitutes an accurate semantic relation.

9352it [31:33,  5.03it/s]

true
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9354it [31:33,  4.95it/s]

true
Determine whether the semantic relation where endemic typhus is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mucin 5AC, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9355it [31:33,  4.97it/s]

true
Determine whether the semantic relation where nerve tissue neoplasm is the subject, anatomical location is the predicate, and nervous tissue is the object constitutes an accurate semantic relation.

9357it [31:34,  4.06it/s]

true
Determine whether the semantic relation where irritable bowel syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where irritable bowel syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9359it [31:34,  4.53it/s]

true
Determine whether the semantic relation where neoplasm is the subject, has cause is the predicate, and mitotic cell cycle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

9360it [31:34,  4.86it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

9361it [31:35,  4.84it/s]

true
Determine whether the semantic relation where cytochrome-c oxidase deficiency disease is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

9362it [31:35,  4.73it/s]

true
Determine whether the semantic relation where paraffin wax is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.

9364it [31:35,  4.92it/s]

false
Determine whether the semantic relation where transplant recipient is the subject, subclass of is the predicate, and patient is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuru is the subject, symptoms and signs is the predicate, and speech disorder is the object constitutes an accurate semantic relation.

9365it [31:35,  4.92it/s]

true
Determine whether the semantic relation where agoraphobia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

9367it [31:36,  4.83it/s]

true
Determine whether the semantic relation where Niemann–Pick disease, type C is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where prolymphocytic leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9368it [31:36,  4.64it/s]

true
Determine whether the semantic relation where physiological phenomenon is the subject, subclass of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.

9369it [31:36,  4.72it/s]

true
Determine whether the semantic relation where aortic disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

9371it [31:37,  4.96it/s]

true
Determine whether the semantic relation where corneal neovascularization is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ventricular tachycardia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9373it [31:37,  4.98it/s]

true
Determine whether the semantic relation where Sjögren's syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where margarine is the subject, country of origin is the predicate, and France is the object constitutes an accurate semantic relation.

9374it [31:37,  4.95it/s]

false
Determine whether the semantic relation where benserazide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9375it [31:37,  4.88it/s]

false
Determine whether the semantic relation where songbirds is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

9377it [31:38,  4.97it/s]

true
Determine whether the semantic relation where pyomyositis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Polynesia is the subject, country is the predicate, and France is the object constitutes an accurate semantic relation.

9379it [31:38,  4.94it/s]

false
Determine whether the semantic relation where Polynesia is the subject, has part(s) is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where magnesium hydroxide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

9381it [31:39,  5.11it/s]

false
Determine whether the semantic relation where pituitary neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where wart is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9382it [31:39,  5.19it/s]

true
Determine whether the semantic relation where London is the subject, twinned administrative body is the predicate, and Los Angeles is the object constitutes an accurate semantic relation.

9384it [31:39,  5.16it/s]

true
Determine whether the semantic relation where Los Angeles is the subject, twinned administrative body is the predicate, and London is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phytol is the subject, found in taxon is the predicate, and Q25243 is the object constitutes an accurate semantic relation.

9386it [31:40,  5.29it/s]

false
Determine whether the semantic relation where lymphatic system disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethanol is the subject, has part(s) of the class is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9388it [31:40,  5.17it/s]

true
Determine whether the semantic relation where Dent disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system vascular malformation is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9390it [31:40,  5.08it/s]

true
Determine whether the semantic relation where EPH receptor B2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nodding disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9392it [31:41,  5.13it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

9394it [31:41,  5.18it/s]

true
Determine whether the semantic relation where deferoxamine is the subject, medical condition treated is the predicate, and bone disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bone disease is the subject, drug or therapy used for treatment is the predicate, and deferoxamine is the object constitutes an accurate semantic relation.

9395it [31:41,  5.14it/s]

true
Determine whether the semantic relation where simvastatin is the subject, significant drug interaction is the predicate, and lopinavir is the object constitutes an accurate semantic relation.

9397it [31:42,  5.10it/s]

true
Determine whether the semantic relation where Listeria meningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tromethamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9399it [31:42,  5.24it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where disease is the subject, handled, mitigated, or managed by is the predicate, and disease management is the object constitutes an accurate semantic relation.

9400it [31:42,  5.27it/s]

true
Determine whether the semantic relation where sleep arousal disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9402it [31:43,  5.21it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

9403it [31:43,  5.10it/s]

true
Determine whether the semantic relation where factor VIIIa [extracellular region] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

9405it [31:43,  4.68it/s]

false
Determine whether the semantic relation where neuroendocrine tumor is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Seychelles is the object constitutes an accurate semantic relation.

9406it [31:44,  4.74it/s]

false
Determine whether the semantic relation where Seychelles is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

9407it [31:44,  4.54it/s]

false
Determine whether the semantic relation where sick sinus syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9408it [31:44,  4.56it/s]

true
Determine whether the semantic relation where myotonic dystrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9409it [31:44,  4.65it/s]

true
Determine whether the semantic relation where Wernicke encephalopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9410it [31:44,  4.71it/s]

true
Determine whether the semantic relation where Apolipoprotein A2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

9412it [31:45,  4.85it/s]

false
Determine whether the semantic relation where β-carotene is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where portal hypertension is the subject, has cause is the predicate, and pericarditis is the object constitutes an accurate semantic relation.

9414it [31:45,  5.05it/s]

false
Determine whether the semantic relation where guanosine cyclic 3',5'-phosphate is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amyloid neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9415it [31:45,  5.01it/s]

true
Determine whether the semantic relation where beta-glucan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9416it [31:46,  4.83it/s]

false
Determine whether the semantic relation where alcoholic cardiomyopathy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

9417it [31:46,  4.71it/s]

true
Determine whether the semantic relation where phytic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9419it [31:46,  4.74it/s]

true
Determine whether the semantic relation where Neurofibromin 1 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tracheoesophageal fistula is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

9421it [31:47,  4.78it/s]

false
Determine whether the semantic relation where nerve growth factor receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inclusion body myositis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9422it [31:47,  4.58it/s]

true
Determine whether the semantic relation where Mannosidase beta is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9423it [31:47,  4.51it/s]

true
Determine whether the semantic relation where Mannosidase beta is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9424it [31:47,  4.54it/s]

true
Determine whether the semantic relation where pathologic fracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false

9426it [31:48,  4.74it/s]

Determine whether the semantic relation where TNF receptor superfamily member 13C is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true

9427it [31:48,  4.83it/s]

Determine whether the semantic relation where practice is the subject, has use is the predicate, and school is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rhabditida infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9429it [31:48,  5.01it/s]

false
Determine whether the semantic relation where (R)-mevalonic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cranial nerve neoplasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9431it [31:49,  4.93it/s]

true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD55 molecule (Cromer blood group) is the subject, cell component is the predicate, and transport vesicle is the object constitutes an accurate semantic relation.

9433it [31:49,  5.18it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.

9435it [31:50,  5.21it/s]

true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anxiety disorder is the subject, drug or therapy used for treatment is the predicate, and propranolol is the object constitutes an accurate semantic relation.

9437it [31:50,  5.12it/s]

true
Determine whether the semantic relation where propranolol is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Calbindin 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9439it [31:50,  5.06it/s]

true
Determine whether the semantic relation where cystatin B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where proprioception is the subject, part of is the predicate, and thought is the object constitutes an accurate semantic relation.

9441it [31:51,  5.15it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Q7540 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where essential tremor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9443it [31:51,  5.36it/s]

true
Determine whether the semantic relation where thought is the subject, has part(s) is the predicate, and proprioception is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where malnutrition is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

9445it [31:52,  5.21it/s]

false
Determine whether the semantic relation where Calbindin 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

9447it [31:52,  5.16it/s]

true
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where serology is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

9448it [31:52,  5.18it/s]

true
Determine whether the semantic relation where pinta disease is the subject, medical examination is the predicate, and microscopy is the object constitutes an accurate semantic relation.

9449it [31:52,  4.90it/s]

false
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

9451it [31:53,  4.69it/s]

true
Determine whether the semantic relation where G protein-coupled receptor kinase 2 is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mustard gas is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9453it [31:53,  4.87it/s]

true
Determine whether the semantic relation where mycophenolic acid is the subject, found in taxon is the predicate, and Aspergillus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dementia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

9455it [31:54,  4.75it/s]

true
Determine whether the semantic relation where chronic lymphocytic leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

9457it [31:54,  4.79it/s]

true
Determine whether the semantic relation where calprotectin complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

9458it [31:54,  4.83it/s]

true
Determine whether the semantic relation where benzylpenicillin is the subject, medical condition treated is the predicate, and botulism is the object constitutes an accurate semantic relation.

9459it [31:55,  4.37it/s]

false
Determine whether the semantic relation where yersiniosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9461it [31:55,  4.74it/s]

true
Determine whether the semantic relation where adenosine monophosphate is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dopa decarboxylase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9462it [31:55,  4.75it/s]

false
Determine whether the semantic relation where Humboldt's Night Monkey is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

9464it [31:56,  4.63it/s]

true
Determine whether the semantic relation where curcumin is the subject, subject has role is the predicate, and flavor enhancer is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bronchopneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9465it [31:56,  4.86it/s]

true
Determine whether the semantic relation where mumps is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9466it [31:56,  4.86it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

9467it [31:56,  4.74it/s]

true
Determine whether the semantic relation where erysipelothrix rhusiopathiae infectious disease is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

9469it [31:57,  4.68it/s]

false
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, three Ig domains and short cytoplasmic tail 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

9470it [31:57,  4.79it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

9471it [31:57,  4.82it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

9473it [31:57,  4.75it/s]

true
Determine whether the semantic relation where oxyquinoline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetanus is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9475it [31:58,  5.02it/s]

true
Determine whether the semantic relation where lansoprazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paragonimiasis is the subject, subclass of is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

9476it [31:58,  5.03it/s]

false
Determine whether the semantic relation where picrate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9478it [31:58,  5.07it/s]

true
Determine whether the semantic relation where prisoner is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bradycardia is the subject, drug or therapy used for treatment is the predicate, and dopamine is the object constitutes an accurate semantic relation.

9480it [31:59,  5.20it/s]

true
Determine whether the semantic relation where dopamine is the subject, medical condition treated is the predicate, and bradycardia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dimpylate is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

9481it [31:59,  5.24it/s]

true
Determine whether the semantic relation where hepatic encephalopathy is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

9482it [31:59,  5.04it/s]

true
Determine whether the semantic relation where Churg-Strauss syndrome is the subject, symptoms and signs is the predicate, and gastrointestinal bleeding is the object constitutes an accurate semantic relation.

9484it [32:00,  5.14it/s]

true
Determine whether the semantic relation where vascular endothelial growth factor A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where arteriosclerosis is the subject, has cause is the predicate, and heredity is the object constitutes an accurate semantic relation.

9486it [32:00,  5.24it/s]

true
Determine whether the semantic relation where congenital adrenal hyperplasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where β-carotene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9488it [32:00,  5.30it/s]

true
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where duodenitis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

9490it [32:01,  5.16it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Ganoderma lucidum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9492it [32:01,  5.19it/s]

false
Determine whether the semantic relation where gnathomiasis is the subject, has natural reservoir is the predicate, and cat is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isocyanate ester is the subject, subclass of is the predicate, and ester is the object constitutes an accurate semantic relation.

9494it [32:02,  5.02it/s]

true
Determine whether the semantic relation where guanosine monophosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bronchospasm is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

9495it [32:02,  5.16it/s]

false
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

9497it [32:02,  5.17it/s]

false
Determine whether the semantic relation where gastroenteritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

9499it [32:02,  5.26it/s]

true
Determine whether the semantic relation where phagocyte bactericidal dysfunction is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

9501it [32:03,  5.32it/s]

true
Determine whether the semantic relation where Pakistan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

9502it [32:03,  5.29it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

9503it [32:03,  5.12it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

9504it [32:03,  4.83it/s]

true
Determine whether the semantic relation where propranolol is the subject, side effect is the predicate, and asthma is the object constitutes an accurate semantic relation.

9505it [32:04,  4.54it/s]

true
Determine whether the semantic relation where Early growth response 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9506it [32:04,  4.27it/s]

true
Determine whether the semantic relation where Solute carrier organic anion transporter family member 1B1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9507it [32:04,  4.33it/s]

true
Determine whether the semantic relation where pregnancy maintenance is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

9509it [32:05,  4.56it/s]

true
Determine whether the semantic relation where biology is the subject, has part(s) is the predicate, and anatomy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anatomy is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

9511it [32:05,  4.78it/s]

false
Determine whether the semantic relation where anatomy is the subject, part of is the predicate, and biology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Qatar is the object constitutes an accurate semantic relation.

9512it [32:05,  4.88it/s]

true
Determine whether the semantic relation where Qatar is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

9513it [32:05,  4.86it/s]

true
Determine whether the semantic relation where necrobiotic disorders is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9515it [32:06,  4.67it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CNTFR-CLCF1 complex is the subject, part of is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9517it [32:06,  4.88it/s]

true
Determine whether the semantic relation where dilated cardiomyopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where succinic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

9519it [32:07,  5.09it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nuclear receptor subfamily 1 group D member 1 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

9521it [32:07,  5.19it/s]

false
Determine whether the semantic relation where microtia is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amyotrophic lateral sclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9522it [32:07,  5.11it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true

9524it [32:08,  5.08it/s]

Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitoxantrone is the subject, subject has role is the predicate, and analgesic is the object constitutes an accurate semantic relation.

9526it [32:08,  5.08it/s]

false
Determine whether the semantic relation where amebiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9528it [32:08,  5.07it/s]

true
Determine whether the semantic relation where clozapine is the subject, subject has role is the predicate, and H1 antagonist is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

9530it [32:09,  5.17it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

9531it [32:09,  5.10it/s]

false
Determine whether the semantic relation where chlorhexidine is the subject, medical condition treated is the predicate, and gram-negative bacterial infection is the object constitutes an accurate semantic relation.

9533it [32:09,  5.04it/s]

true
Determine whether the semantic relation where leishmaniasis is the subject, risk factor is the predicate, and human migration is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gram-negative bacterial infection is the subject, drug or therapy used for treatment is the predicate, and chlorhexidine is the object constitutes an accurate semantic relation.

9534it [32:10,  5.11it/s]

false
Determine whether the semantic relation where otosclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9535it [32:10,  5.06it/s]

true
Determine whether the semantic relation where cholecystitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

9536it [32:10,  5.03it/s]

Determine whether the semantic relation where Czechoslovakia is the subject, shares border with is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

9537it [32:10,  4.85it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

9538it [32:10,  4.82it/s]

true
Determine whether the semantic relation where guanosine 5'-diphosphate (RRSR form) is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9539it [32:11,  4.83it/s]

true
Determine whether the semantic relation where toxicology is the subject, subclass of is the predicate, and chemistry is the object constitutes an accurate semantic relation.

9541it [32:11,  4.83it/s]

true
Determine whether the semantic relation where hyperphosphatemia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF receptor superfamily member 1A is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

9542it [32:11,  4.57it/s]

false
Determine whether the semantic relation where Niemann-Pick disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9544it [32:12,  4.58it/s]

true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ancient Rome is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.

9545it [32:12,  4.78it/s]

false
Determine whether the semantic relation where nuclear receptor subfamily 0 group B member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9546it [32:12,  4.42it/s]

true
Determine whether the semantic relation where tryptophan 2,3-dioxygenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9548it [32:13,  4.76it/s]

true
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where autoimmune disease is the subject, subclass of is the predicate, and hypersensitivity is the object constitutes an accurate semantic relation.

9549it [32:13,  4.77it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and malnutrition is the object constitutes an accurate semantic relation.

9551it [32:13,  4.86it/s]

false
Determine whether the semantic relation where intracranial arterial disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, medical examination is the predicate, and cell culture is the object constitutes an accurate semantic relation.

9552it [32:13,  4.79it/s]

false
Determine whether the semantic relation where agranulocytosis is the subject, different from is the predicate, and agranulocytes is the object constitutes an accurate semantic relation.

9553it [32:14,  4.78it/s]

false
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

9555it [32:14,  4.83it/s]

true
Determine whether the semantic relation where croup is the subject, medical examination is the predicate, and radiography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fluocinolone acetonide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9557it [32:14,  4.99it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.
true

9558it [32:15,  5.06it/s]

Determine whether the semantic relation where keratin 7 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paired box 2 is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

9559it [32:15,  5.09it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, possible treatment is the predicate, and antipyretic is the object constitutes an accurate semantic relation.

9561it [32:15,  4.86it/s]

true
Determine whether the semantic relation where bacterial meningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Huntington's disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9562it [32:16,  4.79it/s]

true
Determine whether the semantic relation where Gamma-glutamyl hydrolase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9564it [32:16,  5.00it/s]

true
Determine whether the semantic relation where miscarriage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where complement C3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9566it [32:16,  5.09it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, biological process is the predicate, and Q14820671 is the object constitutes an accurate semantic relation.

9568it [32:17,  5.28it/s]

false
Determine whether the semantic relation where Interleukin 2 receptor subunit beta is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carotid artery disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

9569it [32:17,  5.12it/s]

true
Determine whether the semantic relation where epidemic typhus is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9570it [32:17,  4.74it/s]

true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

9572it [32:18,  4.40it/s]

true
Determine whether the semantic relation where hyperesthesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (−)-nicotine is the subject, found in taxon is the predicate, and Q7540 is the object constitutes an accurate semantic relation.

9573it [32:18,  4.52it/s]

false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

9574it [32:18,  4.59it/s]

true
Determine whether the semantic relation where DNA polymerase beta is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9575it [32:18,  4.65it/s]

false
Determine whether the semantic relation where hydroxymethylbilane synthase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9576it [32:18,  4.67it/s]

true
Determine whether the semantic relation where monkey disease is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

9577it [32:19,  4.20it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

9579it [32:19,  4.55it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where systemic lupus erythematosus is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9580it [32:19,  4.79it/s]

true
Determine whether the semantic relation where secondary parkinsonism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9581it [32:20,  4.67it/s]

true
Determine whether the semantic relation where circulatory system is the subject, has part(s) is the predicate, and respiratory system is the object constitutes an accurate semantic relation.

9583it [32:20,  4.86it/s]

false
Determine whether the semantic relation where rifampicin is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glucose-6-phosphate dehydrogenase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9585it [32:20,  4.92it/s]

true
Determine whether the semantic relation where phenylthiourea is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where respiratory system is the subject, part of is the predicate, and circulatory system is the object constitutes an accurate semantic relation.

9586it [32:21,  4.47it/s]

false
Determine whether the semantic relation where MARVEL domain containing 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9588it [32:21,  4.70it/s]

false
Determine whether the semantic relation where trifluperidol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rib fracture is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

9589it [32:21,  4.76it/s]

false
Determine whether the semantic relation where Glycoprotein hormones, alpha polypeptide is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

9591it [32:22,  4.93it/s]

false
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Spain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cowpox is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9593it [32:22,  5.10it/s]

true
Determine whether the semantic relation where malaria is the subject, named after is the predicate, and wetland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where biophysical phenomena is the subject, subclass of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.

9595it [32:22,  5.04it/s]

true
Determine whether the semantic relation where pyridoxine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam War is the subject, participant is the predicate, and Thailand is the object constitutes an accurate semantic relation.

9597it [32:23,  5.12it/s]

true
Determine whether the semantic relation where bias is the subject, facet of is the predicate, and risk factor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxolinic acid is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

9599it [32:23,  5.12it/s]

false
Determine whether the semantic relation where methemoglobin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where services computing is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.

9601it [32:24,  5.13it/s]

false
Determine whether the semantic relation where calcium dobesilate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rheumatoid arthritis is the subject, subclass of is the predicate, and chronic condition is the object constitutes an accurate semantic relation.

9602it [32:24,  5.02it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

9604it [32:24,  5.06it/s]

false
Determine whether the semantic relation where interleukin-5 receptor is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenomedullin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9606it [32:25,  4.95it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Palau is the object constitutes an accurate semantic relation.

9607it [32:25,  5.11it/s]

true
Determine whether the semantic relation where Palau is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

9609it [32:25,  5.12it/s]

true
Determine whether the semantic relation where 1,4-alpha-glucan branching enzyme 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where monoethanolamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9611it [32:26,  5.28it/s]

true
Determine whether the semantic relation where metabolic bone disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cisplatin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

9612it [32:26,  5.29it/s]

false
Determine whether the semantic relation where Thyroid stimulating hormone subunit beta is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9613it [32:26,  4.82it/s]

false
Determine whether the semantic relation where retinoblastoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9614it [32:26,  4.83it/s]

true
Determine whether the semantic relation where cannabinoid receptor 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

9615it [32:26,  4.73it/s]

false
Determine whether the semantic relation where public health is the subject, instance of is the predicate, and work is the object constitutes an accurate semantic relation.

9617it [32:27,  4.73it/s]

false
Determine whether the semantic relation where ovarian cyst is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

9618it [32:27,  4.70it/s]

true
Determine whether the semantic relation where ventilator-associated pneumonia is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

9619it [32:27,  4.54it/s]

true
Determine whether the semantic relation where pneumothorax is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9621it [32:28,  4.76it/s]

true
Determine whether the semantic relation where organotin compound is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

9622it [32:28,  4.76it/s]

true
Determine whether the semantic relation where MPTP Poisoning is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9624it [32:28,  4.61it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Madagascar is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

9625it [32:29,  4.76it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

9627it [32:29,  4.92it/s]

true
Determine whether the semantic relation where Adenosylhomocysteinase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Adenosylhomocysteinase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9629it [32:29,  5.03it/s]

true
Determine whether the semantic relation where hepatitis A is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Amphiregulin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9631it [32:30,  5.02it/s]

false
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where beta thalassemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9632it [32:30,  5.21it/s]

true
Determine whether the semantic relation where beta thalassemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9634it [32:30,  5.06it/s]

true
Determine whether the semantic relation where platelet and endothelial cell adhesion molecule 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where influenza is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9635it [32:31,  5.04it/s]

true
Determine whether the semantic relation where multiple sclerosis is the subject, drug or therapy used for treatment is the predicate, and cyanocobalamin is the object constitutes an accurate semantic relation.

9636it [32:31,  4.61it/s]

false
Determine whether the semantic relation where cyanocobalamin is the subject, medical condition treated is the predicate, and multiple sclerosis is the object constitutes an accurate semantic relation.

9637it [32:31,  3.99it/s]

false
Determine whether the semantic relation where pyruvic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

9639it [32:32,  4.30it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

9641it [32:32,  4.71it/s]

false
Determine whether the semantic relation where cerebrovascular disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where REM sleep behavior disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9642it [32:32,  4.95it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

9643it [32:32,  4.56it/s]

true
Determine whether the semantic relation where Wolff–Parkinson–White syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9644it [32:33,  4.51it/s]

true
Determine whether the semantic relation where creatine kinase B is the subject, biological process is the predicate, and phosphorylation is the object constitutes an accurate semantic relation.

9645it [32:33,  4.21it/s]

false
Determine whether the semantic relation where cancer of unknown primary origin is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9646it [32:33,  4.09it/s]

true
Determine whether the semantic relation where arterial hypertension is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

9647it [32:33,  4.04it/s]

true
Determine whether the semantic relation where anxiety disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9649it [32:34,  4.44it/s]

true
Determine whether the semantic relation where chemistry is the subject, is the study of is the predicate, and chemical element is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chemical element is the subject, studied by is the predicate, and chemistry is the object constitutes an accurate semantic relation.

9650it [32:34,  4.57it/s]

true
Determine whether the semantic relation where Europe is the subject, shares border with is the predicate, and Asia is the object constitutes an accurate semantic relation.

9652it [32:34,  4.62it/s]

true
Determine whether the semantic relation where photoreceptor inner segment is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Asia is the subject, shares border with is the predicate, and Europe is the object constitutes an accurate semantic relation.

9653it [32:35,  4.74it/s]

true
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

9655it [32:35,  4.72it/s]

maybe
Determine whether the semantic relation where pulmonary edema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system tuberculosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9656it [32:35,  4.91it/s]

true
Determine whether the semantic relation where CD24 molecule is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

9657it [32:36,  4.85it/s]

false
Determine whether the semantic relation where strongyloidiasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

9658it [32:36,  4.51it/s]

false
Determine whether the semantic relation where Mycobacterium avium-intracellulare infection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9659it [32:36,  4.52it/s]

true
Determine whether the semantic relation where adult-onset Still's disease is the subject, afflicts is the predicate, and joint is the object constitutes an accurate semantic relation.

9661it [32:36,  4.71it/s]

true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

9662it [32:37,  4.74it/s]

true
Determine whether the semantic relation where voriconazole is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

9663it [32:37,  4.68it/s]

true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and voriconazole is the object constitutes an accurate semantic relation.

9664it [32:37,  4.67it/s]

false
Determine whether the semantic relation where nicotinamide adenine dinucleotide is the subject, medical condition treated is the predicate, and myalgic encephalomyelitis/chronic fatigue syndrome is the object constitutes an accurate semantic relation.

9665it [32:37,  4.40it/s]

false
Determine whether the semantic relation where Adams–Stokes syndrome is the subject, subclass of is the predicate, and brain ischemia is the object constitutes an accurate semantic relation.

9666it [32:38,  4.43it/s]

false
Determine whether the semantic relation where personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9667it [32:38,  4.38it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, has part(s) is the predicate, and congenital disorder is the object constitutes an accurate semantic relation.

9669it [32:38,  4.56it/s]

maybe
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and congenital disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myelin basic protein is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

9670it [32:38,  4.53it/s]

false
Determine whether the semantic relation where raccoon is the subject, invasive to is the predicate, and Iran is the object constitutes an accurate semantic relation.

9671it [32:39,  4.37it/s]

false
Determine whether the semantic relation where lymphocele is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9672it [32:39,  4.31it/s]

true
Determine whether the semantic relation where O-6-methylguanine-DNA methyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9674it [32:39,  4.74it/s]

true
Determine whether the semantic relation where renal artery obstruction is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

9675it [32:39,  4.90it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

9677it [32:40,  4.90it/s]

true
Determine whether the semantic relation where psoralen is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where metalloproteinase is the subject, subclass of is the predicate, and metalloprotein is the object constitutes an accurate semantic relation.

9679it [32:40,  4.90it/s]

true
Determine whether the semantic relation where listeriosis is the subject, drug or therapy used for treatment is the predicate, and doxycycline is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where kidney disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9680it [32:41,  4.98it/s]

true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

9681it [32:41,  4.85it/s]

false
Determine whether the semantic relation where fms related receptor tyrosine kinase 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9683it [32:41,  4.89it/s]

true
Determine whether the semantic relation where amphotericin B is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxalic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

9684it [32:41,  4.96it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

9685it [32:42,  4.88it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

9686it [32:42,  4.62it/s]

true
Determine whether the semantic relation where RUNX family transcription factor 2 is the subject, biological process is the predicate, and hemopoiesis is the object constitutes an accurate semantic relation.

9687it [32:42,  4.37it/s]

true
Determine whether the semantic relation where trichotillomania is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

9689it [32:42,  4.67it/s]

false
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where male urogenital disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9690it [32:43,  4.73it/s]

true
Determine whether the semantic relation where peritonitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9691it [32:43,  4.54it/s]

true
Determine whether the semantic relation where benzydamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9693it [32:43,  4.61it/s]

false
Determine whether the semantic relation where medicine is the subject, part of is the predicate, and life sciences is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myocardial infarction is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9695it [32:44,  4.98it/s]

true
Determine whether the semantic relation where clubfoot is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paroxetine is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

9697it [32:44,  5.21it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and paroxetine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD34 molecule is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

9699it [32:44,  5.17it/s]

false
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, two Ig domains and long cytoplasmic tail 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

9700it [32:45,  5.11it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

9701it [32:45,  4.11it/s]

true
Determine whether the semantic relation where CRK proto-oncogene, adaptor protein is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

9703it [32:45,  4.46it/s]

false
Determine whether the semantic relation where reverse transcription polymerase chain reaction is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nutritional and metabolic diseases is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9705it [32:46,  4.70it/s]

true
Determine whether the semantic relation where D-glucouronic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intestinal parasite infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9706it [32:46,  4.77it/s]

true
Determine whether the semantic relation where Sudeck's syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9708it [32:46,  4.80it/s]

false
Determine whether the semantic relation where oxalic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true

9709it [32:47,  4.88it/s]

Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where attentional blink is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

9710it [32:47,  4.88it/s]

false
Determine whether the semantic relation where attentional blink is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

9712it [32:47,  4.70it/s]

false
Determine whether the semantic relation where quinacrine is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where strongyloidiasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9714it [32:48,  4.92it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD33 molecule is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

9715it [32:48,  5.02it/s]

false
Determine whether the semantic relation where tracheal intubation is the subject, instance of is the predicate, and route of administration is the object constitutes an accurate semantic relation.

9717it [32:48,  4.92it/s]

false
Determine whether the semantic relation where Glial cell derived neurotrophic factor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leprosy is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

9719it [32:49,  5.08it/s]

true
Determine whether the semantic relation where Coats disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Clock circadian regulator is the subject, cell component is the predicate, and chromosome is the object constitutes an accurate semantic relation.

9721it [32:49,  5.25it/s]

false
Determine whether the semantic relation where xanthomatosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chronic subdural hematoma is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9722it [32:49,  5.13it/s]

true
Determine whether the semantic relation where Xanthine dehydrogenase is the subject, cell component is the predicate, and sarcoplasmic reticulum is the object constitutes an accurate semantic relation.
false

9724it [32:50,  5.11it/s]

Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and The Gambia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where The Gambia is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

9726it [32:50,  5.13it/s]

true
Determine whether the semantic relation where The Gambia is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cellophane is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9728it [32:50,  4.92it/s]

false
Determine whether the semantic relation where industrial manufacturing is the subject, has part(s) is the predicate, and food industry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where food industry is the subject, subclass of is the predicate, and industrial manufacturing is the object constitutes an accurate semantic relation.

9730it [32:51,  4.88it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where splenosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9732it [32:51,  4.84it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

9734it [32:52,  5.00it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-glutamic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

9736it [32:52,  5.09it/s]

false
Determine whether the semantic relation where signal transducer and activator of transcription 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rho GDP dissociation inhibitor beta is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

9737it [32:52,  4.91it/s]

false
Determine whether the semantic relation where central auditory disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9739it [32:53,  4.79it/s]

true
Determine whether the semantic relation where cyanocobalamin is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lichen sclerosus is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

9740it [32:53,  4.98it/s]

maybe
Determine whether the semantic relation where eczematous skin disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9741it [32:53,  4.82it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9742it [32:53,  4.82it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.

9744it [32:54,  5.02it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

9745it [32:54,  4.74it/s]

true
Determine whether the semantic relation where chlorpromazine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

9747it [32:54,  4.98it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Janus kinase 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

9748it [32:55,  5.08it/s]

true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

9750it [32:55,  4.96it/s]

true
Determine whether the semantic relation where hyaluronic acid is the subject, subject has role is the predicate, and biomarker is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorpheniramine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9752it [32:55,  5.07it/s]

true
Determine whether the semantic relation where CD27 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hereditary spherocytosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9753it [32:56,  4.93it/s]

true
Determine whether the semantic relation where amino-acid N-acetyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9754it [32:56,  4.58it/s]

true
Determine whether the semantic relation where mitochondrial myopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9755it [32:56,  4.53it/s]

true
Determine whether the semantic relation where Complement C1r is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9756it [32:56,  4.51it/s]

false
Determine whether the semantic relation where Pan American Health Organization is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

9758it [32:57,  4.84it/s]

true
Determine whether the semantic relation where ITGA4:ITGB1 [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and sotalol is the object constitutes an accurate semantic relation.

9760it [32:57,  4.97it/s]

true
Determine whether the semantic relation where DL-amphetamine is the subject, medical condition treated is the predicate, and obesity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where delirium is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9761it [32:57,  4.86it/s]

false
Determine whether the semantic relation where prolactin receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9762it [32:58,  4.51it/s]

false
Determine whether the semantic relation where sotalol is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

9763it [32:58,  4.17it/s]

true
Determine whether the semantic relation where receptive aphasia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9765it [32:58,  4.46it/s]

true
Determine whether the semantic relation where chancroid is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where butane-2,3-dione is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9767it [32:59,  4.68it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, possible treatment is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lithium carbonate is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

9769it [32:59,  5.04it/s]

false
Determine whether the semantic relation where eating disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hong Kong is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

9770it [32:59,  5.10it/s]

false
Determine whether the semantic relation where CD80 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9772it [33:00,  5.03it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Hong Kong is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, symptoms and signs is the predicate, and tachycardia is the object constitutes an accurate semantic relation.

9773it [33:00,  5.14it/s]

true
Determine whether the semantic relation where fluoride toxicity is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9775it [33:00,  5.02it/s]

false
Determine whether the semantic relation where complement C4A (Rodgers blood group) is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

9777it [33:01,  5.01it/s]

true
Determine whether the semantic relation where labor induction is the subject, has contributing factor is the predicate, and diabetes is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiethylperazine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9779it [33:01,  5.12it/s]

true
Determine whether the semantic relation where BCL2 associated agonist of cell death is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

9780it [33:01,  4.66it/s]

true
Determine whether the semantic relation where inclusion body myositis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9781it [33:02,  4.24it/s]

true
Determine whether the semantic relation where nephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9783it [33:02,  4.25it/s]

true
Determine whether the semantic relation where pulmonary sequestration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where formazan is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9785it [33:02,  4.46it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plagiocephaly is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9786it [33:03,  4.75it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.

9788it [33:03,  4.67it/s]

true
Determine whether the semantic relation where KIT ligand is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spondylolisthesis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9789it [33:03,  4.75it/s]

true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

9790it [33:04,  4.75it/s]

true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9792it [33:04,  4.90it/s]

false
Determine whether the semantic relation where green chemistry is the subject, subclass of is the predicate, and chemistry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

9793it [33:04,  4.95it/s]

true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

9795it [33:05,  4.93it/s]

true
Determine whether the semantic relation where Cameroon is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2,2,2-trifluoroethanol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9796it [33:05,  5.02it/s]

true
Determine whether the semantic relation where complement fixation test is the subject, instance of is the predicate, and blood test is the object constitutes an accurate semantic relation.

9798it [33:05,  4.90it/s]

true
Determine whether the semantic relation where (1R,2S)-butaxamine is the subject, subject has role is the predicate, and anti-diabetic medication is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cushing's syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9800it [33:06,  5.10it/s]

true
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where factitious disorder imposed on self is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

9801it [33:06,  5.25it/s]

true
Determine whether the semantic relation where factitious disorder imposed on self is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

9803it [33:06,  4.65it/s]

true
Determine whether the semantic relation where captopril is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where growth hormone releasing hormone is the subject, cell component is the predicate, and axon terminus is the object constitutes an accurate semantic relation.

9805it [33:07,  4.85it/s]

false
Determine whether the semantic relation where epidural cranial hematoma is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Clock circadian regulator is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9807it [33:07,  5.05it/s]

false
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

9808it [33:07,  4.49it/s]

false
Determine whether the semantic relation where hepatitis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

9810it [33:08,  4.60it/s]

true
Determine whether the semantic relation where dibucaine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and dibucaine is the object constitutes an accurate semantic relation.

9812it [33:08,  4.86it/s]

false
Determine whether the semantic relation where Proteolipid protein 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

9814it [33:08,  5.12it/s]

false
Determine whether the semantic relation where TNT is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Melan-A is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

9815it [33:09,  5.23it/s]

false
Determine whether the semantic relation where sodium oxybate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9816it [33:09,  5.09it/s]

false
Determine whether the semantic relation where mononeuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true

9818it [33:09,  5.17it/s]

Determine whether the semantic relation where acute respiratory distress syndrome is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and shock is the object constitutes an accurate semantic relation.

9820it [33:10,  4.84it/s]

true
Determine whether the semantic relation where bartonellosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Germany is the object constitutes an accurate semantic relation.

9821it [33:10,  5.00it/s]

true
Determine whether the semantic relation where aortic valve stenosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9823it [33:10,  5.08it/s]

true
Determine whether the semantic relation where impetigo is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Liberia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

9824it [33:11,  4.83it/s]

true
Determine whether the semantic relation where bipolar disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.

9826it [33:11,  4.86it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Liberia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rac-salbutamol is the subject, legal status (medicine) is the predicate, and prescription drug is the object constitutes an accurate semantic relation.

9827it [33:11,  5.01it/s]

true
Determine whether the semantic relation where leprosy is the subject, possible treatment is the predicate, and pharmacotherapy is the object constitutes an accurate semantic relation.

9829it [33:12,  5.00it/s]

true
Determine whether the semantic relation where corrinoid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inborn metabolic brain disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9830it [33:12,  3.68it/s]

true
Determine whether the semantic relation where CD34 molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9831it [33:12,  3.35it/s]

false
Determine whether the semantic relation where iridoid is the subject, subclass of is the predicate, and epoxy compound is the object constitutes an accurate semantic relation.

9832it [33:13,  3.50it/s]

false
Determine whether the semantic relation where amphetamine-related disorders is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

9833it [33:13,  3.82it/s]

true
Determine whether the semantic relation where glomus jugulare tumor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9835it [33:13,  4.35it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, symptoms and signs is the predicate, and angina pectoris is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Barbados is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

9837it [33:14,  4.68it/s]

true
Determine whether the semantic relation where memory disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where migraine without aura is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9839it [33:14,  4.89it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

9841it [33:14,  5.12it/s]

true
Determine whether the semantic relation where North America is the subject, country is the predicate, and Barbados is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

9842it [33:15,  5.21it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9844it [33:15,  5.16it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

9846it [33:15,  5.23it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where frontotemporal dementia is the subject, possible treatment is the predicate, and antipsychotics is the object constitutes an accurate semantic relation.

9848it [33:16,  5.43it/s]

false
Determine whether the semantic relation where collagen disease is the subject, afflicts is the predicate, and joint is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 3,3'-diaminobenzidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

9849it [33:16,  5.53it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

9851it [33:16,  5.23it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trisaccharide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

9853it [33:17,  5.18it/s]

false
Determine whether the semantic relation where acute hemorrhagic conjunctivitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where infection of the central nervous system is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9854it [33:17,  5.33it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

9855it [33:17,  4.76it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

9856it [33:17,  4.50it/s]

true
Determine whether the semantic relation where stress fracture is the subject, subclass of is the predicate, and occupational disease is the object constitutes an accurate semantic relation.

9857it [33:18,  4.59it/s]

false
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9859it [33:18,  4.90it/s]

true
Determine whether the semantic relation where hydatidiform mole is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where obsessive-compulsive disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9861it [33:18,  5.10it/s]

true
Determine whether the semantic relation where premature ovarian failure is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

9862it [33:19,  4.66it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.

9863it [33:19,  4.66it/s]

true
Determine whether the semantic relation where antiviral agent is the subject, subclass of is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

9865it [33:19,  4.81it/s]

false
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where subarachnoid hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9867it [33:20,  5.01it/s]

true
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ciguatera is the subject, symptoms and signs is the predicate, and gastroenteritis is the object constitutes an accurate semantic relation.

9868it [33:20,  5.18it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

9870it [33:20,  5.09it/s]

true
Determine whether the semantic relation where fasciolosis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

9872it [33:21,  5.20it/s]

false
Determine whether the semantic relation where basal-cell carcinoma of the skin is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where basal-cell carcinoma of the skin is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9874it [33:21,  5.08it/s]

true
Determine whether the semantic relation where Kyrgyzstan is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

9875it [33:21,  4.94it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

9877it [33:22,  4.46it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

9879it [33:22,  4.89it/s]

true
Determine whether the semantic relation where Tyrosine aminotransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where femoral hernia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9881it [33:22,  5.06it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Estonia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ATP citrate lyase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9883it [33:23,  5.11it/s]

true
Determine whether the semantic relation where physostigmine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where border disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9885it [33:23,  5.21it/s]

true
Determine whether the semantic relation where fibromyalgia is the subject, afflicts is the predicate, and muscle is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where complement factor properdin is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

9886it [33:23,  5.12it/s]

false
Determine whether the semantic relation where dopa decarboxylase is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

9887it [33:24,  4.98it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

9888it [33:24,  4.86it/s]

true
Determine whether the semantic relation where naphthoquinone is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

9889it [33:24,  4.76it/s]

false
Determine whether the semantic relation where hereditary spastic paraplegia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9890it [33:24,  4.73it/s]

true
Determine whether the semantic relation where Cyclin D2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

9892it [33:25,  4.89it/s]

true
Determine whether the semantic relation where cutaneous larva migrans is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

9894it [33:25,  5.07it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

9895it [33:25,  5.16it/s]

false
Determine whether the semantic relation where mitoxantrone is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

9897it [33:26,  5.12it/s]

false
Determine whether the semantic relation where Keratin 16 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major histocompatibility complex, class I, C is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

9899it [33:26,  5.09it/s]

true
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

9900it [33:26,  4.89it/s]

false
Determine whether the semantic relation where inosine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9902it [33:27,  5.03it/s]

true
Determine whether the semantic relation where disease is the subject, has characteristic is the predicate, and disease qualifier is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where disease qualifier is the subject, facet of is the predicate, and disease is the object constitutes an accurate semantic relation.

9903it [33:27,  4.87it/s]

false
Determine whether the semantic relation where osteoarthritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9904it [33:27,  4.88it/s]

true
Determine whether the semantic relation where HSPA8 is the subject, expressed in is the predicate, and kidney is the object constitutes an accurate semantic relation.

9906it [33:27,  4.92it/s]

false
Determine whether the semantic relation where carcinoma is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sodium voltage-gated channel alpha subunit 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9908it [33:28,  4.79it/s]

true
Determine whether the semantic relation where autoimmune disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where femoral hernia is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

9909it [33:28,  4.93it/s]

false
Determine whether the semantic relation where mercury poisoning is the subject, afflicts is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

9911it [33:28,  5.02it/s]

true
Determine whether the semantic relation where diphenhydramine is the subject, side effect is the predicate, and constipation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system viral disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

9912it [33:29,  5.19it/s]

true
Determine whether the semantic relation where ascariasis is the subject, symptoms and signs is the predicate, and urticaria is the object constitutes an accurate semantic relation.

9914it [33:29,  5.19it/s]

true
Determine whether the semantic relation where procarbazine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Czechoslovakia is the subject, continent is the predicate, and Europe is the object constitutes an accurate semantic relation.

9916it [33:29,  5.19it/s]

true
Determine whether the semantic relation where orthostatic hypotension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where angiotensin II receptor type 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

9917it [33:30,  5.07it/s]

true
Determine whether the semantic relation where tetanus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9919it [33:30,  4.72it/s]

true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

9920it [33:30,  4.78it/s]

true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9922it [33:31,  4.95it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and pentamidine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pentamidine is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

9924it [33:31,  5.14it/s]

true
Determine whether the semantic relation where methanol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.

9926it [33:31,  5.42it/s]

false
Determine whether the semantic relation where islet amyloid polypeptide is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where delirium tremens is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

9927it [33:32,  4.99it/s]

true
Determine whether the semantic relation where Serpin family E member 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

9928it [33:32,  4.78it/s]

true
Determine whether the semantic relation where refractive error is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9930it [33:32,  4.81it/s]

false
Determine whether the semantic relation where ligature is the subject, subclass of is the predicate, and medical equipment is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ciguatera is the subject, symptoms and signs is the predicate, and neurological disorder is the object constitutes an accurate semantic relation.

9931it [33:33,  4.79it/s]

true
Determine whether the semantic relation where FOS is the subject, expressed in is the predicate, and gastric mucosa is the object constitutes an accurate semantic relation.

9933it [33:33,  4.93it/s]

false
Determine whether the semantic relation where generalized dystonia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Complement C9 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

9935it [33:33,  4.94it/s]

false
Determine whether the semantic relation where sepharose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

9936it [33:34,  5.10it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

9937it [33:34,  4.96it/s]

true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

9938it [33:34,  4.66it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

9939it [33:34,  4.53it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

9941it [33:35,  4.73it/s]

true
Determine whether the semantic relation where arbovirosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

9942it [33:35,  4.79it/s]

Determine whether the semantic relation where Wisconsin is the subject, shares border with is the predicate, and Ontario is the object constitutes an accurate semantic relation.
true

9943it [33:35,  4.89it/s]

Determine whether the semantic relation where galantamine is the subject, route of administration is the predicate, and intramuscular injection is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where freezing is the subject, different from is the predicate, and blood coagulation is the object constitutes an accurate semantic relation.

9945it [33:35,  5.02it/s]

true
Determine whether the semantic relation where L-lysine is the subject, part of is the predicate, and fish proteins is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ontario is the subject, shares border with is the predicate, and Wisconsin is the object constitutes an accurate semantic relation.

9946it [33:36,  4.78it/s]

false
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

9948it [33:36,  4.78it/s]

true
Determine whether the semantic relation where strychnine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where indapamide is the subject, medical condition treated is the predicate, and nephrotic syndrome is the object constitutes an accurate semantic relation.

9950it [33:36,  4.72it/s]

false
Determine whether the semantic relation where nephrotic syndrome is the subject, drug or therapy used for treatment is the predicate, and indapamide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peroxiredoxin 6 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

9951it [33:37,  4.87it/s]

true
Determine whether the semantic relation where ethylene oxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9952it [33:37,  4.85it/s]

true
Determine whether the semantic relation where dimethyl sulfoxide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

9953it [33:37,  4.86it/s]

false
Determine whether the semantic relation where biliary tract neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

9954it [33:37,  4.67it/s]

true
Determine whether the semantic relation where progressive myoclonus epilepsy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

9956it [33:38,  4.92it/s]

true
Determine whether the semantic relation where phencyclidine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vestibular neuronitis is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

9957it [33:38,  4.81it/s]

false
Determine whether the semantic relation where Africa is the subject, shares border with is the predicate, and Asia is the object constitutes an accurate semantic relation.

9959it [33:38,  4.84it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and bronchitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Asia is the subject, shares border with is the predicate, and Africa is the object constitutes an accurate semantic relation.

9961it [33:39,  5.16it/s]

true
Determine whether the semantic relation where Lyme disease is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ghrelin is the subject, biological process is the predicate, and cartilage development is the object constitutes an accurate semantic relation.

9963it [33:39,  5.16it/s]

false
Determine whether the semantic relation where toxin is the subject, studied by is the predicate, and toxicology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vanillic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

9965it [33:39,  5.18it/s]

true
Determine whether the semantic relation where myelodysplastic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myelodysplastic syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

9967it [33:40,  5.37it/s]

true
Determine whether the semantic relation where mumps is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CD24 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

9968it [33:40,  5.45it/s]

true
Determine whether the semantic relation where 2',3'-cyclic nucleotide 3' phosphodiesterase is the subject, biological process is the predicate, and chemical synaptic transmission is the object constitutes an accurate semantic relation.

9970it [33:40,  4.87it/s]

false
Determine whether the semantic relation where POU class 4 homeobox 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bronchopneumonia is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

9972it [33:41,  4.95it/s]

true
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 1C is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where N-acylsphingosine amidohydrolase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9974it [33:41,  5.23it/s]

true
Determine whether the semantic relation where N-acylsphingosine amidohydrolase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiotensins is the subject, biological process is the predicate, and operant conditioning is the object constitutes an accurate semantic relation.

9976it [33:42,  4.81it/s]

false
Determine whether the semantic relation where toxicology is the subject, is the study of is the predicate, and toxin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where odor is the subject, subclass of is the predicate, and physical phenomenon is the object constitutes an accurate semantic relation.

9977it [33:42,  4.88it/s]

true
Determine whether the semantic relation where Erinaceidae is the subject, main food source is the predicate, and Mus is the object constitutes an accurate semantic relation.

9979it [33:42,  4.99it/s]

false
Determine whether the semantic relation where ambulance is the subject, carries passengers or cargo is the predicate, and patient is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD14 molecule is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

9980it [33:43,  4.72it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.

9982it [33:43,  4.93it/s]

true
Determine whether the semantic relation where subacute bacterial endocarditis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart failure is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

9983it [33:43,  4.95it/s]

true
Determine whether the semantic relation where selectin E is the subject, biological process is the predicate, and calcium-mediated signaling is the object constitutes an accurate semantic relation.

9985it [33:44,  4.99it/s]

false
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spirochetal diseases is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

9987it [33:44,  4.94it/s]

true
Determine whether the semantic relation where hairy cell leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Sierra Leone is the object constitutes an accurate semantic relation.

9989it [33:44,  5.15it/s]

true
Determine whether the semantic relation where Sierra Leone is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Orcinus orca is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

9990it [33:44,  5.38it/s]

true
Determine whether the semantic relation where Argininosuccinate lyase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

9991it [33:45,  5.15it/s]

true
Determine whether the semantic relation where Argininosuccinate lyase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

9992it [33:45,  5.03it/s]

true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

9994it [33:45,  4.92it/s]

false
Determine whether the semantic relation where complex and mixed tumor is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hong Kong is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

9995it [33:46,  5.16it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Hong Kong is the object constitutes an accurate semantic relation.

9997it [33:46,  5.15it/s]

false
Determine whether the semantic relation where diverticulitis is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 11 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

9998it [33:46,  5.08it/s]

false
Determine whether the semantic relation where balantidiasis is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

9999it [33:46,  4.95it/s]

false
Determine whether the semantic relation where fasciolosis is the subject, has natural reservoir is the predicate, and pig is the object constitutes an accurate semantic relation.

10000it [33:47,  4.66it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Guyana is the object constitutes an accurate semantic relation.

10001it [33:47,  4.15it/s]

true
Determine whether the semantic relation where fumarate hydratase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10003it [33:47,  4.54it/s]

true
Determine whether the semantic relation where Guyana is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where endemic typhus is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

10004it [33:48,  4.22it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and 1-octanol is the object constitutes an accurate semantic relation.

10005it [33:48,  4.07it/s]

false
Determine whether the semantic relation where Melanesia is the subject, country is the predicate, and France is the object constitutes an accurate semantic relation.

10006it [33:48,  4.22it/s]

false
Determine whether the semantic relation where Melanesia is the subject, has part(s) is the predicate, and France is the object constitutes an accurate semantic relation.

10007it [33:48,  4.40it/s]

false
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10008it [33:48,  4.48it/s]

true
Determine whether the semantic relation where gastrointestinal system disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10009it [33:49,  4.56it/s]

true
Determine whether the semantic relation where gastrointestinal system disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10011it [33:49,  4.63it/s]

true
Determine whether the semantic relation where prosencephalon is the subject, develops from is the predicate, and neural tube is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fetal erythroblastosis is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

10012it [33:49,  4.50it/s]

true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.

10014it [33:50,  4.66it/s]

false
Determine whether the semantic relation where intussusception is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and fluvoxamine is the object constitutes an accurate semantic relation.

10015it [33:50,  4.66it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

10016it [33:50,  4.63it/s]

true
Determine whether the semantic relation where biopolymer is the subject, has part(s) of the class is the predicate, and nucleic acids is the object constitutes an accurate semantic relation.

10018it [33:51,  4.63it/s]

true
Determine whether the semantic relation where fluvoxamine is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pure red-cell aplasia is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

10019it [33:51,  4.71it/s]

true
Determine whether the semantic relation where vaccinia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10020it [33:51,  4.68it/s]

false
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10021it [33:51,  4.57it/s]

true
Determine whether the semantic relation where translation is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

10022it [33:52,  4.32it/s]

false
Determine whether the semantic relation where melibiose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10023it [33:52,  4.33it/s]

false
Determine whether the semantic relation where fentanyl is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

10024it [33:52,  4.49it/s]

true
Determine whether the semantic relation where nitrofuran is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10026it [33:52,  4.63it/s]

true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cartilage oligomeric matrix protein is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

10027it [33:53,  4.68it/s]

false
Determine whether the semantic relation where neurotensin is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

10028it [33:53,  4.41it/s]

true
Determine whether the semantic relation where copper(II) sulfate pentahydrate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10029it [33:53,  4.28it/s]

true
Determine whether the semantic relation where kwashiorkor is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10030it [33:53,  4.39it/s]

false
Determine whether the semantic relation where phytic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10032it [33:54,  4.61it/s]

false
Determine whether the semantic relation where tyramine is the subject, found in taxon is the predicate, and Anthozoa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sleep apnea is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10033it [33:54,  4.73it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

10034it [33:54,  4.54it/s]

true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

10035it [33:54,  4.55it/s]

true
Determine whether the semantic relation where interleukin 1 receptor antagonist is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10037it [33:55,  4.69it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ryanodine receptor is the subject, subclass of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

10038it [33:55,  3.75it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

10039it [33:55,  3.97it/s]

true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

10040it [33:56,  3.61it/s]

true
Determine whether the semantic relation where alcohol withdrawal seizure is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10041it [33:56,  3.80it/s]

true
Determine whether the semantic relation where Israel is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

10043it [33:56,  4.30it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

10045it [33:57,  4.61it/s]

true
Determine whether the semantic relation where penetrating head injury is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastroparesis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10047it [33:57,  4.73it/s]

true
Determine whether the semantic relation where chronic granulomatous disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic granulomatous disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10048it [33:58,  3.21it/s]

true
Determine whether the semantic relation where Heat shock protein family B (small) member 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10049it [33:58,  3.48it/s]

false
Determine whether the semantic relation where aminohippuric acid is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

10050it [33:58,  3.67it/s]

false
Determine whether the semantic relation where galantamine is the subject, route of administration is the predicate, and subcutaneous injection is the object constitutes an accurate semantic relation.

10051it [33:58,  3.91it/s]

false
Determine whether the semantic relation where conjunctivitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10052it [33:59,  4.08it/s]

true
Determine whether the semantic relation where adult T-cell leukemia/lymphoma is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

10053it [33:59,  4.29it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

10054it [33:59,  4.43it/s]

true
Determine whether the semantic relation where pervasive developmental disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10056it [34:00,  4.69it/s]

true
Determine whether the semantic relation where L-glutamine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

10058it [34:00,  4.89it/s]

true
Determine whether the semantic relation where pyromania is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where restrictive cardiomyopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10059it [34:00,  4.96it/s]

true
Determine whether the semantic relation where restrictive cardiomyopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10061it [34:01,  4.75it/s]

true
Determine whether the semantic relation where sulfite oxidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central sleep apnea is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10063it [34:01,  5.00it/s]

true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where geriatrics is the subject, medical condition treated is the predicate, and hypercholesterolemia is the object constitutes an accurate semantic relation.

10065it [34:01,  5.29it/s]

false
Determine whether the semantic relation where pulmonary sarcoidosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

10067it [34:02,  4.94it/s]

false
Determine whether the semantic relation where mastocytosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Diclofenac is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

10069it [34:02,  5.13it/s]

true
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.

10071it [34:02,  5.19it/s]

true
Determine whether the semantic relation where World War I is the subject, location is the predicate, and Asia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10073it [34:03,  5.06it/s]

true
Determine whether the semantic relation where Mauritius is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ribonuclease A family member 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10075it [34:03,  5.30it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Mauritius is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where candidiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10076it [34:03,  4.99it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

10078it [34:04,  5.02it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor alpha is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

10079it [34:04,  5.01it/s]

false
Determine whether the semantic relation where deoxyuridine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10080it [34:04,  4.82it/s]

false
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

10082it [34:05,  4.98it/s]

true
Determine whether the semantic relation where alveolar osteitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

10083it [34:05,  4.82it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

10085it [34:05,  4.94it/s]

true
Determine whether the semantic relation where CD19 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10086it [34:06,  4.84it/s]

true
Determine whether the semantic relation where oxiglutatione is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

10088it [34:06,  4.88it/s]

false
Determine whether the semantic relation where complement component C1 complex is the subject, part of is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false

10089it [34:06,  5.03it/s]

Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Heat shock protein family B (small) member 1 is the subject, cell component is the predicate, and spindle is the object constitutes an accurate semantic relation.

10091it [34:07,  5.00it/s]

false
Determine whether the semantic relation where rickettsiosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

10092it [34:07,  4.92it/s]

false
Determine whether the semantic relation where low tension glaucoma is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10093it [34:07,  4.75it/s]

false
Determine whether the semantic relation where Ras homolog family member B is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10095it [34:07,  4.71it/s]

false
Determine whether the semantic relation where Interleukin 18 receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascariasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10096it [34:08,  4.83it/s]

true
Determine whether the semantic relation where rhombencephalon is the subject, instance of is the predicate, and embryonic structure is the object constitutes an accurate semantic relation.

10097it [34:08,  4.86it/s]

true
Determine whether the semantic relation where integrin subunit alpha 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10099it [34:08,  4.65it/s]

true
Determine whether the semantic relation where Interleukin 6 signal transducer is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toxicology is the subject, subclass of is the predicate, and pharmaceutical sciences is the object constitutes an accurate semantic relation.

10101it [34:09,  5.00it/s]

false
Determine whether the semantic relation where Serpin family G member 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where autoimmune thrombocytopenic purpura is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10102it [34:09,  4.74it/s]

true
Determine whether the semantic relation where pharmaceutical sciences is the subject, has part(s) is the predicate, and toxicology is the object constitutes an accurate semantic relation.

10104it [34:09,  4.81it/s]

true
Determine whether the semantic relation where Seychelles is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Taenia solium is the subject, habitat is the predicate, and muscle is the object constitutes an accurate semantic relation.

10106it [34:10,  5.18it/s]

true
Determine whether the semantic relation where KEL is the subject, expressed in is the predicate, and bone marrow is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Seychelles is the object constitutes an accurate semantic relation.

10108it [34:10,  5.11it/s]

true
Determine whether the semantic relation where malnutrition is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anthrax is the subject, symptoms and signs is the predicate, and ulcer is the object constitutes an accurate semantic relation.

10109it [34:10,  5.08it/s]

true
Determine whether the semantic relation where Cathepsin H is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

10110it [34:10,  5.01it/s]

false
Determine whether the semantic relation where Spinacia oleracea is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

10112it [34:11,  4.88it/s]

true
Determine whether the semantic relation where formaldehyde is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sodium cyanide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10114it [34:11,  5.13it/s]

true
Determine whether the semantic relation where CD55 molecule (Cromer blood group) is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where allantoin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10116it [34:12,  5.05it/s]

false
Determine whether the semantic relation where Prostaglandin G/H synthase 2 is the subject, subclass of is the predicate, and heme protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psychological techniques is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

10117it [34:12,  4.98it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

10118it [34:12,  4.90it/s]

true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

10119it [34:12,  4.22it/s]

true
Determine whether the semantic relation where Adenylate cyclase activating polypeptide 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10120it [34:13,  4.37it/s]

false
Determine whether the semantic relation where diabetic cardiomyopathy is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10122it [34:13,  4.72it/s]

false
Determine whether the semantic relation where chikungunya is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where progressive myoclonus epilepsy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10124it [34:13,  4.80it/s]

true
Determine whether the semantic relation where Denmark is the subject, shares border with is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10125it [34:14,  4.73it/s]

true
Determine whether the semantic relation where eradication of infectious diseases is the subject, subclass of is the predicate, and extinction is the object constitutes an accurate semantic relation.

10126it [34:14,  4.66it/s]

false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and naproxen is the object constitutes an accurate semantic relation.

10128it [34:14,  4.80it/s]

true
Determine whether the semantic relation where naproxen is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, shares border with is the predicate, and Denmark is the object constitutes an accurate semantic relation.

10129it [34:14,  4.91it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

10131it [34:15,  4.93it/s]

true
Determine whether the semantic relation where hiccups is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intestinal volvulus is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10132it [34:15,  4.85it/s]

true
Determine whether the semantic relation where GNAS complex locus is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10133it [34:15,  4.86it/s]

false
Determine whether the semantic relation where hemolytic anemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10134it [34:16,  4.82it/s]

maybe
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

10136it [34:16,  4.93it/s]

true
Determine whether the semantic relation where growth hormone deficiency is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phosphatidyl serine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10138it [34:16,  4.90it/s]

true
Determine whether the semantic relation where Insulin Lispro is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

10139it [34:17,  4.79it/s]

true
Determine whether the semantic relation where erythema infectiosum is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

10140it [34:17,  4.80it/s]

true
Determine whether the semantic relation where Norway is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

10141it [34:17,  4.68it/s]

true
Determine whether the semantic relation where ovarian hyperstimulation syndrome is the subject, health specialty is the predicate, and gynaecology is the object constitutes an accurate semantic relation.

10142it [34:17,  4.53it/s]

true
Determine whether the semantic relation where phosphoramide is the subject, subclass of is the predicate, and phosphorus compound is the object constitutes an accurate semantic relation.

10143it [34:17,  4.58it/s]

true
Determine whether the semantic relation where sexually transmitted infection is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

10144it [34:18,  4.53it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10146it [34:18,  4.87it/s]

true
Determine whether the semantic relation where adenosine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angioedema is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

10148it [34:18,  5.03it/s]

false
Determine whether the semantic relation where aviation is the subject, has use is the predicate, and research is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sexually transmitted infection is the subject, possible treatment is the predicate, and local anti-infective agent is the object constitutes an accurate semantic relation.

10149it [34:19,  5.08it/s]

true
Determine whether the semantic relation where type 2 diabetes is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

10150it [34:19,  4.88it/s]

true
Determine whether the semantic relation where inosine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10151it [34:19,  4.87it/s]

false
Determine whether the semantic relation where autoimmune lymphoproliferative syndrome is the subject, subclass of is the predicate, and type IV hypersensitivity is the object constitutes an accurate semantic relation.

10153it [34:19,  4.89it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where embolism and thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

10155it [34:20,  5.02it/s]

false
Determine whether the semantic relation where Mycoplasma is the subject, studied by is the predicate, and microbiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

10156it [34:20,  5.01it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, symptoms and signs is the predicate, and blindness is the object constitutes an accurate semantic relation.

10157it [34:20,  4.84it/s]

true
Determine whether the semantic relation where labor induction is the subject, has contributing factor is the predicate, and obesity is the object constitutes an accurate semantic relation.

10158it [34:20,  4.70it/s]

true
Determine whether the semantic relation where alpha-linolenic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

10160it [34:21,  4.88it/s]

true
Determine whether the semantic relation where Killer cell lectin like receptor C2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart arrhythmia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10162it [34:21,  4.95it/s]

true
Determine whether the semantic relation where buspirone is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and buspirone is the object constitutes an accurate semantic relation.

10164it [34:22,  5.17it/s]

true
Determine whether the semantic relation where diphenhydramine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

10166it [34:22,  4.91it/s]

true
Determine whether the semantic relation where gas is the subject, has characteristic is the predicate, and viscosity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and spindle is the object constitutes an accurate semantic relation.

10168it [34:23,  4.82it/s]

false
Determine whether the semantic relation where gonorrhea is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thymidine phosphorylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10170it [34:23,  5.11it/s]

true
Determine whether the semantic relation where thymidine phosphorylase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where suicidal ideation is the subject, subclass of is the predicate, and thought is the object constitutes an accurate semantic relation.

10172it [34:23,  5.31it/s]

true
Determine whether the semantic relation where dopa decarboxylase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stomatitis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10173it [34:23,  5.28it/s]

true
Determine whether the semantic relation where autoimmune disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

10175it [34:24,  5.03it/s]

false
Determine whether the semantic relation where etiolation is the subject, subclass of is the predicate, and growth is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10176it [34:24,  5.14it/s]

true
Determine whether the semantic relation where hypothalamic neoplasm is the subject, subclass of is the predicate, and connective tissue neoplasm is the object constitutes an accurate semantic relation.

10178it [34:24,  5.04it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

10179it [34:25,  4.59it/s]

true
Determine whether the semantic relation where MET proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10180it [34:25,  4.59it/s]

true
Determine whether the semantic relation where peptide nucleic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10181it [34:25,  4.49it/s]

true
Determine whether the semantic relation where glutamate carboxypeptidase II is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10183it [34:26,  4.79it/s]

true
Determine whether the semantic relation where sirtuin 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uracil is the subject, found in taxon is the predicate, and Angelica sinensis is the object constitutes an accurate semantic relation.

10185it [34:26,  5.04it/s]

false
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Daucus carota is the object constitutes an accurate semantic relation.

10186it [34:26,  5.06it/s]

false
Determine whether the semantic relation where ethacrynic acid is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

10187it [34:26,  4.85it/s]

true
Determine whether the semantic relation where ornithosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10188it [34:27,  4.45it/s]

true
Determine whether the semantic relation where tuberculoid leprosy is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10190it [34:27,  4.86it/s]

true
Determine whether the semantic relation where anthrax is the subject, has natural reservoir is the predicate, and soil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where proteostasis deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10191it [34:27,  4.92it/s]

false
Determine whether the semantic relation where isopropyl β-D-thiogalactopyranoside is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10193it [34:28,  4.97it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Cucumis sativus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chylous ascites is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10194it [34:28,  4.99it/s]

true
Determine whether the semantic relation where Central Asia is the subject, country is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

10195it [34:28,  4.83it/s]

false
Determine whether the semantic relation where L-Cysteine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

10197it [34:28,  4.97it/s]

false
Determine whether the semantic relation where cbl proto-oncogene is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mesothelioma is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

10199it [34:29,  5.03it/s]

false
Determine whether the semantic relation where macrophage activation syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cross-cultural competence is the subject, subclass of is the predicate, and social skill is the object constitutes an accurate semantic relation.

10200it [34:29,  5.10it/s]

true
Determine whether the semantic relation where therapy is the subject, facet of is the predicate, and health care is the object constitutes an accurate semantic relation.

10201it [34:29,  4.83it/s]

true
Determine whether the semantic relation where obesity is the subject, contributing factor of is the predicate, and cardiovascular disease is the object constitutes an accurate semantic relation.

10203it [34:30,  4.81it/s]

true
Determine whether the semantic relation where Legg–Calvé–Perthes disease is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where community health center is the subject, country is the predicate, and Germany is the object constitutes an accurate semantic relation.

10205it [34:30,  5.03it/s]

maybe
Determine whether the semantic relation where DL-dipalmitoylphosphatidylcholine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Croatia is the object constitutes an accurate semantic relation.

10207it [34:30,  5.08it/s]

false
Determine whether the semantic relation where staphylococcal skin infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

10209it [34:31,  5.03it/s]

false
Determine whether the semantic relation where Histidine ammonia-lyase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true

10210it [34:31,  5.11it/s]

Determine whether the semantic relation where Tonga is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where communicable disease control is the subject, part of is the predicate, and risk management is the object constitutes an accurate semantic relation.

10211it [34:31,  5.13it/s]

true
Determine whether the semantic relation where glutamyl-prolyl-tRNA synthetase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10213it [34:32,  4.97it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where maprotiline is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

10214it [34:32,  4.69it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and maprotiline is the object constitutes an accurate semantic relation.

10215it [34:32,  4.74it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.

10216it [34:32,  4.78it/s]

true
Determine whether the semantic relation where thiourea is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

10218it [34:33,  4.92it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where female organism is the subject, instance of is the predicate, and sex is the object constitutes an accurate semantic relation.

10220it [34:33,  4.76it/s]

false
Determine whether the semantic relation where gait abnormality is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where keratin 5 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10221it [34:33,  4.51it/s]

false
Determine whether the semantic relation where porphobilinogen is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10222it [34:34,  4.01it/s]

false
Determine whether the semantic relation where cataract is the subject, has cause is the predicate, and vitiligo is the object constitutes an accurate semantic relation.

10223it [34:34,  3.73it/s]

false
Determine whether the semantic relation where niacinamide is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

10224it [34:34,  3.57it/s]

false
Determine whether the semantic relation where splenic tuberculosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10226it [34:35,  4.14it/s]

true
Determine whether the semantic relation where ankylosing spondylitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

10227it [34:35,  4.35it/s]

Determine whether the semantic relation where Vietnam is the subject, religion or worldview is the predicate, and Protestantism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10229it [34:35,  4.72it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lead poisoning is the subject, symptoms and signs is the predicate, and kidney disease is the object constitutes an accurate semantic relation.

10230it [34:36,  4.68it/s]

true
Determine whether the semantic relation where Central African Republic is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

10232it [34:36,  4.92it/s]

true
Determine whether the semantic relation where complement C4A (Rodgers blood group) is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetralogy of Fallot is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10233it [34:36,  4.87it/s]

true
Determine whether the semantic relation where pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10234it [34:36,  4.81it/s]

true
Determine whether the semantic relation where arthus reaction is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.

10235it [34:37,  4.77it/s]

true
Determine whether the semantic relation where polymyositis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.

10236it [34:37,  4.57it/s]

true
Determine whether the semantic relation where casein is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10237it [34:37,  4.53it/s]

false
Determine whether the semantic relation where female urogenital diseases and pregnancy complications is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10238it [34:37,  4.55it/s]

false
Determine whether the semantic relation where transaminase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10239it [34:38,  4.35it/s]

true
Determine whether the semantic relation where transaminase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

10240it [34:38,  4.34it/s]

true
Determine whether the semantic relation where porphyria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10241it [34:38,  4.33it/s]

true
Determine whether the semantic relation where inositol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10243it [34:38,  4.37it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where seasonal affective disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

10244it [34:39,  4.64it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

10245it [34:39,  4.70it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

10246it [34:39,  4.67it/s]

true
Determine whether the semantic relation where Caspase 8 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

10248it [34:39,  4.83it/s]

false
Determine whether the semantic relation where hydroxysteroid 11-beta dehydrogenase 2 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

10249it [34:40,  5.00it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

10251it [34:40,  4.37it/s]

true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

10252it [34:40,  4.41it/s]

true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

10254it [34:41,  4.81it/s]

true
Determine whether the semantic relation where Glanzmann's thrombasthenia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-lactic acid is the subject, subclass of is the predicate, and fatty alcohol is the object constitutes an accurate semantic relation.

10256it [34:41,  4.89it/s]

false
Determine whether the semantic relation where guanosine monophosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where soybean is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

10258it [34:42,  5.25it/s]

false
Determine whether the semantic relation where L-ornithine is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phenolphthalein is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10260it [34:42,  5.28it/s]

false
Determine whether the semantic relation where abscess is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acidosis is the subject, subclass of is the predicate, and hematopoietic system disease is the object constitutes an accurate semantic relation.

10261it [34:42,  5.30it/s]

false
Determine whether the semantic relation where egg chorion is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

10262it [34:42,  4.89it/s]

true
Determine whether the semantic relation where ciprofloxacin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

10263it [34:43,  4.87it/s]

true
Determine whether the semantic relation where retinal detachment is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

10264it [34:43,  4.71it/s]

false
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.

10266it [34:43,  4.86it/s]

true
Determine whether the semantic relation where Serpin family A member 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

10267it [34:43,  4.98it/s]

false
Determine whether the semantic relation where Heterogeneous nuclear ribonucleoprotein K is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

10268it [34:44,  4.72it/s]

false
Determine whether the semantic relation where intracranial hemorrhage is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

10269it [34:44,  4.73it/s]

true
Determine whether the semantic relation where cholecystokinin is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

10271it [34:44,  4.67it/s]

false
Determine whether the semantic relation where coronary artery vasospasm is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

10273it [34:45,  4.95it/s]

false
Determine whether the semantic relation where accessory nerve injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Behçet's disease is the subject, possible treatment is the predicate, and immunoglobulin therapy is the object constitutes an accurate semantic relation.

10274it [34:45,  4.95it/s]

true
Determine whether the semantic relation where transforming growth factor beta 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10275it [34:45,  4.56it/s]

true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

10277it [34:46,  4.58it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

10279it [34:46,  4.87it/s]

true
Determine whether the semantic relation where spermatic cord torsion is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tyrosine O-phosphate is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10280it [34:46,  4.92it/s]

false
Determine whether the semantic relation where norepinephrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10282it [34:47,  4.84it/s]

true
Determine whether the semantic relation where solute carrier family 46 member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aminolevulinic acid is the subject, found in taxon is the predicate, and Serratia marcescens is the object constitutes an accurate semantic relation.

10283it [34:47,  5.06it/s]

false
Determine whether the semantic relation where Dupuytren's contracture is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10285it [34:47,  4.68it/s]

true
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and valproic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and carbachol is the object constitutes an accurate semantic relation.

10287it [34:48,  4.92it/s]

maybe
Determine whether the semantic relation where delirium is the subject, symptoms and signs is the predicate, and speech disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where N-acylsphingosine amidohydrolase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10289it [34:48,  5.25it/s]

false
Determine whether the semantic relation where GC vitamin D binding protein is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10290it [34:48,  5.36it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.

10292it [34:49,  5.20it/s]

true
Determine whether the semantic relation where diet is the subject, contributing factor of is the predicate, and health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and metronidazole is the object constitutes an accurate semantic relation.

10293it [34:49,  5.29it/s]

true
Determine whether the semantic relation where posterior reversible encephalopathy syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10294it [34:49,  5.12it/s]

true
Determine whether the semantic relation where coagulation factor II thrombin receptor is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

10296it [34:49,  4.86it/s]

false
Determine whether the semantic relation where magnesium sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parathyroid hormone is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10298it [34:50,  5.21it/s]

true
Determine whether the semantic relation where dopa decarboxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where doxylamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10299it [34:50,  5.28it/s]

true
Determine whether the semantic relation where hiatus hernia is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.

10301it [34:50,  5.31it/s]

true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where liver abscess is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10302it [34:51,  5.31it/s]

maybe
Determine whether the semantic relation where power station is the subject, subclass of is the predicate, and organization is the object constitutes an accurate semantic relation.

10304it [34:51,  5.17it/s]

false
Determine whether the semantic relation where hafnium is the subject, location of discovery is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 27 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10306it [34:51,  5.11it/s]

true
Determine whether the semantic relation where mucin 5B, oligomeric mucus/gel-forming is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japanese encephalitis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

10308it [34:52,  4.89it/s]

true
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and lung is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gonorrhea is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

10309it [34:52,  5.09it/s]

false
Determine whether the semantic relation where insulin aspart is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

10310it [34:52,  4.81it/s]

true
Determine whether the semantic relation where 3-aminopropanenitrile is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

10311it [34:52,  4.77it/s]

true
Determine whether the semantic relation where toll like receptor 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10312it [34:53,  4.79it/s]

true
Determine whether the semantic relation where selectin E is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10313it [34:53,  4.84it/s]

true
Determine whether the semantic relation where Finland is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

10315it [34:53,  4.85it/s]

true
Determine whether the semantic relation where aldosterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where furosemide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10316it [34:53,  4.94it/s]

false
Determine whether the semantic relation where C-X-C motif chemokine ligand 10 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10318it [34:54,  5.03it/s]

false
Determine whether the semantic relation where Neurocalcin delta is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydrogen peroxide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10319it [34:54,  5.16it/s]

true
Determine whether the semantic relation where adnexal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10321it [34:54,  4.96it/s]

true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cardiac arrest is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10322it [34:55,  4.85it/s]

false
Determine whether the semantic relation where cysticercosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10324it [34:55,  4.88it/s]

true
Determine whether the semantic relation where parathyroid hormone is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Venezuelan equine encephalitis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

10326it [34:55,  4.97it/s]

true
Determine whether the semantic relation where materia medica is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sickle-cell disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10328it [34:56,  4.92it/s]

true
Determine whether the semantic relation where cardiolipin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where leptospirosis is the subject, medical examination is the predicate, and urinalysis is the object constitutes an accurate semantic relation.

10330it [34:56,  5.06it/s]

true
Determine whether the semantic relation where Lesch-Nyhan syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where infant is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.

10331it [34:56,  5.08it/s]

false
Determine whether the semantic relation where salicylic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10333it [34:57,  4.94it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
true

10334it [34:57,  5.00it/s]

Determine whether the semantic relation where Leigh disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where animal parasitic disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10336it [34:57,  5.07it/s]

true
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false

10337it [34:58,  5.17it/s]

Determine whether the semantic relation where Meckel's diverticulum is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hydrocephalus is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10339it [34:58,  5.14it/s]

true
Determine whether the semantic relation where methylglyoxal is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-baclofen is the subject, medical condition treated is the predicate, and transverse myelitis is the object constitutes an accurate semantic relation.

10341it [34:58,  5.43it/s]

false
Determine whether the semantic relation where salicylic acid is the subject, subject has role is the predicate, and anti-infective agent is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbon monoxide poisoning is the subject, symptoms and signs is the predicate, and hallucination is the object constitutes an accurate semantic relation.

10342it [34:59,  5.14it/s]

true
Determine whether the semantic relation where psilocybin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10343it [34:59,  5.04it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

10344it [34:59,  4.91it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

10346it [34:59,  4.78it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transverse myelitis is the subject, drug or therapy used for treatment is the predicate, and (RS)-baclofen is the object constitutes an accurate semantic relation.

10347it [35:00,  4.67it/s]

true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

10349it [35:00,  4.74it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true

10350it [35:00,  4.95it/s]

Determine whether the semantic relation where leukotriene B4 is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.

10352it [35:01,  5.25it/s]

true
Determine whether the semantic relation where no reflow phenomenon is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coagulation factor IX is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

10354it [35:01,  5.31it/s]

false
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

10356it [35:01,  5.33it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EDAR associated death domain is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

10358it [35:02,  5.20it/s]

false
Determine whether the semantic relation where epidermoid cyst is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where learning disability is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10359it [35:02,  5.16it/s]

false
Determine whether the semantic relation where bladder exstrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10361it [35:02,  4.94it/s]

true
Determine whether the semantic relation where bladder exstrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

10363it [35:03,  5.20it/s]

true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ketorolac tromethamine is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10365it [35:03,  5.42it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and ketorolac tromethamine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypopituitarism is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10367it [35:04,  5.32it/s]

true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

10368it [35:04,  5.12it/s]

true
Determine whether the semantic relation where reproductive and urinary physiological phenomena is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

10370it [35:04,  5.01it/s]

true
Determine whether the semantic relation where dicumarol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Parkinson's disease is the subject, genetic association is the predicate, and NSF is the object constitutes an accurate semantic relation.

10372it [35:05,  5.14it/s]

true
Determine whether the semantic relation where respiratory tract infection is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where NSF is the subject, genetic association is the predicate, and Parkinson's disease is the object constitutes an accurate semantic relation.

10374it [35:05,  5.00it/s]

false
Determine whether the semantic relation where BRCA1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nematocyst is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

10376it [35:05,  5.08it/s]

true
Determine whether the semantic relation where Fibroblast growth factor 8 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pharynx neoplasm is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

10377it [35:06,  5.03it/s]

true
Determine whether the semantic relation where influenza is the subject, health specialty is the predicate, and family medicine is the object constitutes an accurate semantic relation.

10379it [35:06,  5.08it/s]

false
Determine whether the semantic relation where pneumomediastinum is the subject, health specialty is the predicate, and radiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where impulse control disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.

10381it [35:06,  5.26it/s]

true
Determine whether the semantic relation where Denys-Drash syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (−)-nicotine is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

10383it [35:07,  5.23it/s]

false
Determine whether the semantic relation where HCK proto-oncogene, Src family tyrosine kinase is the subject, cell component is the predicate, and transport vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where central nervous system vasculitis is the subject, anatomical location is the predicate, and central nervous system is the object constitutes an accurate semantic relation.

10385it [35:07,  5.19it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where giant-cell tumor of bone is the subject, health specialty is the predicate, and orthopedic surgery is the object constitutes an accurate semantic relation.

10387it [35:07,  5.10it/s]

true
Determine whether the semantic relation where amino sugar is the subject, subclass of is the predicate, and amine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

10389it [35:08,  5.05it/s]

true
Determine whether the semantic relation where Canada is the subject, separated from is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin L is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10391it [35:08,  5.17it/s]

false
Determine whether the semantic relation where postterm pregnancy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Krabbe disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10393it [35:09,  5.12it/s]

true
Determine whether the semantic relation where metabolic disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metabolic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10395it [35:09,  5.16it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gastroesophageal reflux disease is the subject, drug or therapy used for treatment is the predicate, and calcium carbonate is the object constitutes an accurate semantic relation.

10396it [35:09,  5.28it/s]

true
Determine whether the semantic relation where calcium carbonate is the subject, medical condition treated is the predicate, and gastroesophageal reflux disease is the object constitutes an accurate semantic relation.

10398it [35:10,  5.15it/s]

true
Determine whether the semantic relation where aequorin is the subject, instance of is the predicate, and enzyme is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.

10400it [35:10,  5.18it/s]

true
Determine whether the semantic relation where genetic disease is the subject, has cause is the predicate, and pathology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

10402it [35:10,  5.19it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10403it [35:11,  5.06it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

10405it [35:11,  5.09it/s]

true
Determine whether the semantic relation where granulosa cell tumour is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10407it [35:11,  5.18it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where organic brain syndrome is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

10409it [35:12,  5.13it/s]

false
Determine whether the semantic relation where apolipoprotein(a) is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where health informatics is the subject, facet of is the predicate, and medicine is the object constitutes an accurate semantic relation.

10410it [35:12,  5.05it/s]

true
Determine whether the semantic relation where erythromelalgia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

10411it [35:12,  4.94it/s]

false
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

10413it [35:13,  5.07it/s]

false
Determine whether the semantic relation where AIDS-related complex is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CXADR Ig-like cell adhesion molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10415it [35:13,  4.85it/s]

false
Determine whether the semantic relation where coarctation of the aorta is the subject, symptoms and signs is the predicate, and nosebleed is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lactoylglutathione lyase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

10416it [35:13,  4.95it/s]

true
Determine whether the semantic relation where vitellogenins is the subject, subclass of is the predicate, and lipases is the object constitutes an accurate semantic relation.

10417it [35:13,  4.70it/s]

false
Determine whether the semantic relation where Signal transducer and activator of transcription 6 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

10418it [35:14,  4.45it/s]

true
Determine whether the semantic relation where Q106951292 is the subject, has use is the predicate, and textile industry is the object constitutes an accurate semantic relation.

10419it [35:14,  4.56it/s]

false
Determine whether the semantic relation where amitriptyline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10421it [35:14,  4.57it/s]

true
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where follistatin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10423it [35:15,  4.85it/s]

true
Determine whether the semantic relation where paired box 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

10425it [35:15,  5.06it/s]

false
Determine whether the semantic relation where prostacyclin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

10427it [35:16,  4.87it/s]

true
Determine whether the semantic relation where Listeria meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

10428it [35:16,  4.95it/s]

true
Determine whether the semantic relation where paracetamol is the subject, significant drug interaction is the predicate, and rifampicin is the object constitutes an accurate semantic relation.

10429it [35:16,  4.90it/s]

true
Determine whether the semantic relation where pulmonary aspiration is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

10431it [35:16,  4.80it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.

10433it [35:17,  5.09it/s]

true
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10435it [35:17,  5.15it/s]

false
Determine whether the semantic relation where diphtheria is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where evolution is the subject, has cause is the predicate, and germline mutation is the object constitutes an accurate semantic relation.

10436it [35:17,  5.25it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

10438it [35:18,  5.22it/s]

true
Determine whether the semantic relation where dermatitis herpetiformis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

10440it [35:18,  4.88it/s]

true
Determine whether the semantic relation where germline mutation is the subject, has effect is the predicate, and evolution is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-deoxy-D-glucose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10442it [35:19,  5.06it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where long QT syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10443it [35:19,  5.07it/s]

true
Determine whether the semantic relation where Sweden is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

10445it [35:19,  5.11it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Niger is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rabies is the subject, symptoms and signs is the predicate, and paresthesia is the object constitutes an accurate semantic relation.

10447it [35:19,  5.28it/s]

true
Determine whether the semantic relation where caffeine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where S100 calcium binding protein B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10448it [35:20,  5.21it/s]

false
Determine whether the semantic relation where tuberculous meningitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10449it [35:20,  4.88it/s]

true
Determine whether the semantic relation where Niger is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

10451it [35:20,  4.94it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gangliosidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10453it [35:21,  4.93it/s]

true
Determine whether the semantic relation where (RS)-ketamine is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Adenosylhomocysteinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10454it [35:21,  5.07it/s]

true
Determine whether the semantic relation where nuclear receptor corepressor 2 is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

10455it [35:21,  4.80it/s]

false
Determine whether the semantic relation where Lycopersicon esculentum is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

10457it [35:22,  4.94it/s]

false
Determine whether the semantic relation where urinary bladder fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

10458it [35:22,  5.04it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

10459it [35:22,  4.64it/s]

true
Determine whether the semantic relation where ornithine carbamoyltransferase deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10460it [35:22,  4.70it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10461it [35:22,  4.57it/s]

true
Determine whether the semantic relation where E2F transcription factor 1 is the subject, cell component is the predicate, and centrosome is the object constitutes an accurate semantic relation.

10463it [35:23,  4.64it/s]

false
Determine whether the semantic relation where cardiovascular disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where minichromosome maintenance complex component 7 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

10465it [35:23,  4.96it/s]

false
Determine whether the semantic relation where arteriosclerosis is the subject, has cause is the predicate, and ageing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where War in Afghanistan (2001–2021) is the subject, participant is the predicate, and Germany is the object constitutes an accurate semantic relation.

10467it [35:24,  5.12it/s]

true
Determine whether the semantic relation where Germany is the subject, significant event is the predicate, and War in Afghanistan (2001–2021) is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium selenite is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.

10468it [35:24,  5.19it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10470it [35:24,  4.99it/s]

true
Determine whether the semantic relation where doxorubicin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Estonia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

10472it [35:25,  4.83it/s]

true
Determine whether the semantic relation where hyperthyroidism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Estonia is the object constitutes an accurate semantic relation.

10474it [35:25,  5.05it/s]

true
Determine whether the semantic relation where copper is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acute intermittent porphyria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10476it [35:25,  5.16it/s]

true
Determine whether the semantic relation where fasciolosis is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rheumatism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10477it [35:26,  5.04it/s]

true
Determine whether the semantic relation where Broad Bean is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

10478it [35:26,  4.95it/s]

true
Determine whether the semantic relation where cholesteatoma is the subject, drug or therapy used for treatment is the predicate, and ciprofloxacin is the object constitutes an accurate semantic relation.

10480it [35:26,  4.92it/s]

false
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where reproductive physiological phenomenon is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

10481it [35:26,  4.84it/s]

true
Determine whether the semantic relation where apolipoprotein H is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

10482it [35:27,  4.85it/s]

false
Determine whether the semantic relation where chronic atrophic rhinitis is the subject, subclass of is the predicate, and chronic condition is the object constitutes an accurate semantic relation.

10484it [35:27,  4.97it/s]

true
Determine whether the semantic relation where Thromboxane A synthase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gynecomastia is the subject, has cause is the predicate, and obesity is the object constitutes an accurate semantic relation.

10485it [35:27,  5.05it/s]

true
Determine whether the semantic relation where prefrontal cortex is the subject, arterial supply is the predicate, and middle cerebral artery is the object constitutes an accurate semantic relation.

10486it [35:28,  4.80it/s]

true
Determine whether the semantic relation where pentachlorophenol is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

10487it [35:28,  4.70it/s]

true
Determine whether the semantic relation where spondyloarthropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10488it [35:28,  4.62it/s]

true
Determine whether the semantic relation where ciprofloxacin is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

10490it [35:28,  4.71it/s]

true
Determine whether the semantic relation where Coagulation factor XII is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where propylthiouracil is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

10491it [35:29,  4.89it/s]

false
Determine whether the semantic relation where phytol is the subject, subclass of is the predicate, and fatty alcohol is the object constitutes an accurate semantic relation.

10493it [35:29,  4.80it/s]

true
Determine whether the semantic relation where DL-ofloxacin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and ciprofloxacin is the object constitutes an accurate semantic relation.

10495it [35:29,  4.86it/s]

maybe
Determine whether the semantic relation where common cold is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DIDS is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10497it [35:30,  5.18it/s]

false
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Streptomyces coelicolor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

10498it [35:30,  5.22it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

10500it [35:30,  5.16it/s]

true
Determine whether the semantic relation where Cyclin D1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system vasculitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10502it [35:31,  5.13it/s]

true
Determine whether the semantic relation where creatine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aneurysm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10504it [35:31,  5.11it/s]

true
Determine whether the semantic relation where vascular endothelial growth factor C is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where High mobility group box 1 is the subject, biological process is the predicate, and developmental process is the object constitutes an accurate semantic relation.

10506it [35:32,  5.13it/s]

false
Determine whether the semantic relation where DIDS is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.

10507it [35:32,  4.87it/s]

false
Determine whether the semantic relation where phenylethyl alcohol is the subject, subject has role is the predicate, and local anti-infective agent is the object constitutes an accurate semantic relation.

10508it [35:32,  4.78it/s]

true
Determine whether the semantic relation where granulomatosis with polyangiitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10509it [35:32,  4.63it/s]

true
Determine whether the semantic relation where ulcer is the subject, subclass of is the predicate, and pathologic processes is the object constitutes an accurate semantic relation.

10511it [35:33,  4.87it/s]

true
Determine whether the semantic relation where melanocortin 2 receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where zeta chain of T cell receptor associated protein kinase 70 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

10513it [35:33,  4.59it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true

10514it [35:33,  4.70it/s]

Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phosphate regulating endopeptidase homolog X-linked is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10516it [35:34,  4.80it/s]

true
Determine whether the semantic relation where cervicitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where museum is the subject, subject has role is the predicate, and communication is the object constitutes an accurate semantic relation.

10517it [35:34,  4.58it/s]

false
Determine whether the semantic relation where International Statistical Classification of Diseases and Related Health Problems is the subject, instance of is the predicate, and reference work is the object constitutes an accurate semantic relation.

10518it [35:34,  4.67it/s]

true
Determine whether the semantic relation where molluscum contagiosum is the subject, different from is the predicate, and Mollusca is the object constitutes an accurate semantic relation.

10519it [35:34,  4.41it/s]

true
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

10521it [35:35,  4.43it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular dementia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10523it [35:35,  4.99it/s]

true
Determine whether the semantic relation where 17-ketosteroid is the subject, subclass of is the predicate, and ketone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Schnitzler syndrome is the subject, subclass of is the predicate, and type IV hypersensitivity is the object constitutes an accurate semantic relation.

10525it [35:36,  4.98it/s]

false
Determine whether the semantic relation where dirofilariasis is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where compartment syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10526it [35:36,  5.12it/s]

true
Determine whether the semantic relation where diethyltoluamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10527it [35:36,  4.67it/s]

true
Determine whether the semantic relation where burning mouth syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10528it [35:36,  4.72it/s]

true
Determine whether the semantic relation where milk is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.

10530it [35:37,  4.97it/s]

true
Determine whether the semantic relation where social conditions is the subject, facet of is the predicate, and quality of life is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zeta chain of T cell receptor associated protein kinase 70 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10531it [35:37,  4.91it/s]

true
Determine whether the semantic relation where Follicle stimulating hormone subunit beta is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10532it [35:37,  4.83it/s]

true
Determine whether the semantic relation where 3-phosphoshikimate 1-carboxyvinyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

10534it [35:37,  5.03it/s]

true
Determine whether the semantic relation where microtubule associated protein tau is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neuropsychiatric systemic lupus erythematosus is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

10535it [35:38,  4.75it/s]

false
Determine whether the semantic relation where Secretagogin, EF-hand calcium binding protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10537it [35:38,  4.59it/s]

true
Determine whether the semantic relation where gastrin releasing peptide is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amyloidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10538it [35:38,  4.84it/s]

true
Determine whether the semantic relation where metal metabolism disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10540it [35:39,  4.92it/s]

true
Determine whether the semantic relation where hyper-IgM immunodeficiency syndrome, Type 1 is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jamaica is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

10542it [35:39,  5.15it/s]

true
Determine whether the semantic relation where female urogenital disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypertriglyceridemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10543it [35:39,  5.22it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, cell component is the predicate, and microvillus is the object constitutes an accurate semantic relation.

10544it [35:40,  5.03it/s]

false
Determine whether the semantic relation where Epiregulin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10545it [35:40,  4.70it/s]

true
Determine whether the semantic relation where cerebral hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

10547it [35:40,  4.84it/s]

Determine whether the semantic relation where North America is the subject, country is the predicate, and Jamaica is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hexosaminidase subunit alpha is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10549it [35:41,  5.05it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebrovascular disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10551it [35:41,  4.94it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where teratoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10552it [35:41,  4.74it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

10554it [35:42,  4.79it/s]

true
Determine whether the semantic relation where ornithosis is the subject, symptoms and signs is the predicate, and hepatomegaly is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where compartment syndrome is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

10555it [35:42,  4.50it/s]

false
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

10556it [35:42,  4.58it/s]

true
Determine whether the semantic relation where phytic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10558it [35:42,  4.80it/s]

true
Determine whether the semantic relation where cycloserine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serpin family G member 1 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

10560it [35:43,  4.96it/s]

false
Determine whether the semantic relation where luteolin is the subject, found in taxon is the predicate, and Pinus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where papaverine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10561it [35:43,  5.02it/s]

false
Determine whether the semantic relation where fluoroquinolone is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.

10562it [35:43,  4.98it/s]

true
Determine whether the semantic relation where butyrolactone is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10564it [35:44,  4.84it/s]

true
Determine whether the semantic relation where tyropanic acid is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10566it [35:44,  5.01it/s]

true
Determine whether the semantic relation where alpha-linolenic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acetone is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10567it [35:44,  4.81it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

10568it [35:45,  4.81it/s]

true
Determine whether the semantic relation where liver disease is the subject, drug or therapy used for treatment is the predicate, and furosemide is the object constitutes an accurate semantic relation.

10569it [35:45,  4.84it/s]

false
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10570it [35:45,  4.83it/s]

true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

10572it [35:45,  4.90it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EPH receptor A4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10574it [35:46,  5.12it/s]

false
Determine whether the semantic relation where furosemide is the subject, medical condition treated is the predicate, and liver disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

10575it [35:46,  5.14it/s]

true
Determine whether the semantic relation where skin infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10577it [35:46,  5.18it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10579it [35:47,  5.22it/s]

false
Determine whether the semantic relation where docosahexaenoic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, founder is the predicate, and West Germany is the object constitutes an accurate semantic relation.

10581it [35:47,  5.32it/s]

false
Determine whether the semantic relation where dirofilariasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sleep-wake disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10582it [35:47,  5.40it/s]

true
Determine whether the semantic relation where premature ejaculation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

10584it [35:48,  5.37it/s]

Determine whether the semantic relation where sinusitis is the subject, drug or therapy used for treatment is the predicate, and cetirizine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cetirizine is the subject, medical condition treated is the predicate, and sinusitis is the object constitutes an accurate semantic relation.

10585it [35:48,  5.27it/s]

true
Determine whether the semantic relation where Janus kinase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10587it [35:48,  5.10it/s]

true
Determine whether the semantic relation where CSK is the subject, expressed in is the predicate, and monocyte is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chikungunya is the subject, drug or therapy used for treatment is the predicate, and non-steroidal anti-inflammatory drug is the object constitutes an accurate semantic relation.

10589it [35:49,  4.93it/s]

true
Determine whether the semantic relation where cooking is the subject, location is the predicate, and workplace is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alkalosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10591it [35:49,  4.92it/s]

false
Determine whether the semantic relation where furazolidone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quinine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10593it [35:49,  4.75it/s]

true
Determine whether the semantic relation where Czechoslovakia is the subject, shares border with is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czechoslovakia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10594it [35:50,  4.97it/s]

true
Determine whether the semantic relation where methimazole is the subject, subject has role is the predicate, and protein synthesis inhibitor is the object constitutes an accurate semantic relation.

10595it [35:50,  4.78it/s]

true
Determine whether the semantic relation where biotin is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

10597it [35:50,  4.87it/s]

false
Determine whether the semantic relation where paragonimiasis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where S-nitroso-N-acetyl-D-penicillamine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10599it [35:51,  4.99it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

10600it [35:51,  5.02it/s]

true
Determine whether the semantic relation where gingivitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10602it [35:51,  5.05it/s]

true
Determine whether the semantic relation where West Germany is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phosphocreatine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10603it [35:52,  4.92it/s]

true
Determine whether the semantic relation where endothelin 1 is the subject, biological process is the predicate, and cartilage development is the object constitutes an accurate semantic relation.

10605it [35:52,  4.64it/s]

false
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where celiac disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10606it [35:52,  4.89it/s]

true
Determine whether the semantic relation where Bradykinin receptor B1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

10608it [35:53,  5.04it/s]

false
Determine whether the semantic relation where acetyl coenzyme A is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acetic anhydride is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10609it [35:53,  5.04it/s]

true
Determine whether the semantic relation where cerebral infarction is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10610it [35:53,  4.94it/s]

true
Determine whether the semantic relation where token economy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

10611it [35:53,  4.74it/s]

true
Determine whether the semantic relation where anxiety is the subject, drug or therapy used for treatment is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

10612it [35:53,  4.30it/s]

false
Determine whether the semantic relation where haloperidol is the subject, medical condition treated is the predicate, and anxiety is the object constitutes an accurate semantic relation.

10613it [35:54,  4.41it/s]

false
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.

10615it [35:54,  4.57it/s]

true
Determine whether the semantic relation where normetanephrine is the subject, found in taxon is the predicate, and Q146555 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inositol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10617it [35:54,  4.96it/s]

true
Determine whether the semantic relation where cranial nerve injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

10619it [35:55,  4.97it/s]

true
Determine whether the semantic relation where central nervous system vascular malformation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where histamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10620it [35:55,  5.04it/s]

false
Determine whether the semantic relation where phenylketonuria is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10622it [35:56,  4.79it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydrogen cyanide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

10624it [35:56,  5.05it/s]

false
Determine whether the semantic relation where ceftriaxone is the subject, medical condition treated is the predicate, and enteritis is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

10625it [35:56,  4.98it/s]

true
Determine whether the semantic relation where Cathepsin L is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10627it [35:57,  5.02it/s]

false
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and flecainide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where enteritis is the subject, drug or therapy used for treatment is the predicate, and ceftriaxone is the object constitutes an accurate semantic relation.

10628it [35:57,  5.01it/s]

maybe
Determine whether the semantic relation where flecainide is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

10630it [35:57,  5.11it/s]

true
Determine whether the semantic relation where Sanfilippo syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 11 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10632it [35:58,  5.05it/s]

true
Determine whether the semantic relation where Zimbabwe is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where achlorhydria is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10633it [35:58,  5.12it/s]

true
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.

10635it [35:58,  5.09it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

10636it [35:58,  5.14it/s]

true
Determine whether the semantic relation where European Union is the subject, shares border with is the predicate, and Russia is the object constitutes an accurate semantic relation.

10638it [35:59,  4.92it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Zimbabwe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hand deformity is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

10640it [35:59,  4.90it/s]

false
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, biological process is the predicate, and developmental process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF receptor superfamily member 11b is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10642it [35:59,  5.28it/s]

false
Determine whether the semantic relation where hyoscyamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bilirubin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10644it [36:00,  5.15it/s]

false
Determine whether the semantic relation where phosphoglycerate dehydrogenase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lupus nephritis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10645it [36:00,  5.28it/s]

true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

10647it [36:01,  4.72it/s]

false
Determine whether the semantic relation where Addison's disease is the subject, subclass of is the predicate, and kidney disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inguinal hernia is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10649it [36:01,  5.07it/s]

false
Determine whether the semantic relation where monoethanolamine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Caspase 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10651it [36:01,  5.09it/s]

false
Determine whether the semantic relation where MEDLINE is the subject, main subject is the predicate, and biology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where integrin subunit beta 1 is the subject, cell component is the predicate, and synaptic membrane is the object constitutes an accurate semantic relation.

10652it [36:02,  4.59it/s]

false
Determine whether the semantic relation where renal aminoaciduria is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

10653it [36:02,  4.61it/s]

false
Determine whether the semantic relation where angiomyolipoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10655it [36:02,  4.79it/s]

true
Determine whether the semantic relation where congenital hemolytic anemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and chlorzoxazone is the object constitutes an accurate semantic relation.

10656it [36:02,  4.96it/s]

false
Determine whether the semantic relation where chlorzoxazone is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

10657it [36:03,  4.72it/s]

true
Determine whether the semantic relation where gallic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10659it [36:03,  4.85it/s]

true
Determine whether the semantic relation where infant respiratory distress syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bread is the subject, country of origin is the predicate, and Europe is the object constitutes an accurate semantic relation.

10660it [36:03,  4.54it/s]

false
Determine whether the semantic relation where bread is the subject, location of creation is the predicate, and Europe is the object constitutes an accurate semantic relation.

10662it [36:04,  4.68it/s]

maybe
Determine whether the semantic relation where bread is the subject, first appearance is the predicate, and Europe is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Glucokinase family is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

10664it [36:04,  4.96it/s]

true
Determine whether the semantic relation where mental disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit alpha M is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10665it [36:04,  5.02it/s]

true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

10666it [36:05,  4.69it/s]

false
Determine whether the semantic relation where Artemisia annua is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.

10668it [36:05,  4.89it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10669it [36:05,  5.10it/s]

false
Determine whether the semantic relation where aplastic anemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true

10670it [36:05,  5.06it/s]

Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and hypotension is the object constitutes an accurate semantic relation.

10672it [36:06,  4.91it/s]

true
Determine whether the semantic relation where biochemistry is the subject, subclass of is the predicate, and organic chemistry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10673it [36:06,  5.06it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

10674it [36:06,  4.93it/s]

true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10676it [36:07,  4.98it/s]

true
Determine whether the semantic relation where parathyroid hormone 1 receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where N-acetylneuraminic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10677it [36:07,  4.93it/s]

true
Determine whether the semantic relation where periodic paralysis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10679it [36:07,  4.99it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10681it [36:08,  5.14it/s]

true
Determine whether the semantic relation where Serbia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where farnesyl diphosphate synthase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10682it [36:08,  5.07it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.

10683it [36:08,  4.96it/s]

false
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

10684it [36:08,  4.80it/s]

false
Determine whether the semantic relation where Glial cell derived neurotrophic factor is the subject, biological process is the predicate, and peristalsis is the object constitutes an accurate semantic relation.

10685it [36:08,  4.81it/s]

false
Determine whether the semantic relation where hydroxocobalamin is the subject, medical condition treated is the predicate, and multiple sclerosis is the object constitutes an accurate semantic relation.

10686it [36:09,  4.73it/s]

false
Determine whether the semantic relation where Behçet's disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

10687it [36:09,  4.77it/s]

true
Determine whether the semantic relation where multiple sclerosis is the subject, drug or therapy used for treatment is the predicate, and hydroxocobalamin is the object constitutes an accurate semantic relation.

10689it [36:09,  4.70it/s]

false
Determine whether the semantic relation where traumatology is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Galectin 1 is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

10691it [36:10,  4.84it/s]

false
Determine whether the semantic relation where neurogenic bladder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurogenic bladder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10692it [36:10,  5.08it/s]

true
Determine whether the semantic relation where partial thromboplastin time is the subject, instance of is the predicate, and blood test is the object constitutes an accurate semantic relation.

10694it [36:10,  5.13it/s]

true
Determine whether the semantic relation where Usher syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, drug or therapy used for treatment is the predicate, and ampicillin is the object constitutes an accurate semantic relation.

10696it [36:11,  5.25it/s]

false
Determine whether the semantic relation where Churg-Strauss syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

10697it [36:11,  5.34it/s]

false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

10699it [36:11,  5.12it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

10700it [36:11,  5.27it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, drug or therapy used for treatment is the predicate, and neostigmine is the object constitutes an accurate semantic relation.

10701it [36:12,  5.07it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.

10703it [36:12,  5.00it/s]

true
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.

10705it [36:12,  5.15it/s]

true
Determine whether the semantic relation where indomethacin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CXADR Ig-like cell adhesion molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10706it [36:13,  5.32it/s]

true
Determine whether the semantic relation where chylous ascites is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10708it [36:13,  5.17it/s]

true
Determine whether the semantic relation where Norway is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Norway is the object constitutes an accurate semantic relation.

10710it [36:13,  5.15it/s]

false
Determine whether the semantic relation where parasitic infectious diseases is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parasitic infectious diseases is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10712it [36:14,  5.19it/s]

true
Determine whether the semantic relation where estrogen receptor 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where atrioventricular septal defect is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

10714it [36:14,  5.15it/s]

false
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sepharose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10716it [36:14,  5.30it/s]

false
Determine whether the semantic relation where gyrate atrophy of the choroid is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mitogen-activated protein kinase 10 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10718it [36:15,  5.18it/s]

false
Determine whether the semantic relation where coxa vara is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where polylysine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

10719it [36:15,  5.20it/s]

false
Determine whether the semantic relation where demyelinating disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10721it [36:15,  5.11it/s]

true
Determine whether the semantic relation where keratitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where World Health Organization is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

10723it [36:16,  5.06it/s]

true
Determine whether the semantic relation where pilonidal cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where saxitoxin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10725it [36:16,  5.15it/s]

true
Determine whether the semantic relation where encephalomyelitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Galectin 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10727it [36:17,  5.30it/s]

false
Determine whether the semantic relation where public health practice is the subject, subclass of is the predicate, and health care is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

10729it [36:17,  5.17it/s]

true
Determine whether the semantic relation where harm reduction is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intestinal fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10731it [36:17,  5.38it/s]

true
Determine whether the semantic relation where cat-scratch disease is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where food storage is the subject, instance of is the predicate, and technology is the object constitutes an accurate semantic relation.

10733it [36:18,  5.40it/s]

false
Determine whether the semantic relation where ETS proto-oncogene 1, transcription factor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where relapsing fever borreliosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10735it [36:18,  4.93it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 23, alpha subunit p19 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10736it [36:18,  5.04it/s]

true
Determine whether the semantic relation where leukemic infiltration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10738it [36:19,  4.97it/s]

false
Determine whether the semantic relation where plant pathology is the subject, part of is the predicate, and science is the object constitutes an accurate semantic relation.
true

10739it [36:19,  5.15it/s]

Determine whether the semantic relation where nursing is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where subdural empyema is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10741it [36:19,  5.03it/s]

true
Determine whether the semantic relation where Somalia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Shiga toxin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

10742it [36:20,  5.16it/s]

false
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10744it [36:20,  5.10it/s]

true
Determine whether the semantic relation where endomyocardial fibrosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tear gas is the subject, subclass of is the predicate, and gas is the object constitutes an accurate semantic relation.

10746it [36:20,  5.23it/s]

true
Determine whether the semantic relation where 4-aminobenzoic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

10748it [36:21,  5.05it/s]

true
Determine whether the semantic relation where subarachnoid hemorrhage is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thymine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10749it [36:21,  5.03it/s]

true
Determine whether the semantic relation where pervasive developmental disorder is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

10750it [36:21,  4.93it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

10752it [36:22,  4.83it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where abdominal cavity is the subject, has part(s) is the predicate, and adrenal gland is the object constitutes an accurate semantic relation.

10753it [36:22,  4.95it/s]

true
Determine whether the semantic relation where galactosemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10754it [36:22,  4.90it/s]

true
Determine whether the semantic relation where interstitial lung disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10756it [36:22,  5.01it/s]

true
Determine whether the semantic relation where visceral leishmaniasis is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

10758it [36:23,  5.07it/s]

true
Determine whether the semantic relation where diabetic ketoacidosis is the subject, symptoms and signs is the predicate, and mental confusion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where experimental nervous system autoimmune disease is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

10760it [36:23,  5.03it/s]

true
Determine whether the semantic relation where Cucumis melo is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (±)-deprenyl is the subject, medical condition treated is the predicate, and schizophrenia is the object constitutes an accurate semantic relation.

10762it [36:24,  5.19it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

10763it [36:24,  5.13it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

10765it [36:24,  4.94it/s]

true
Determine whether the semantic relation where dibucaine is the subject, subclass of is the predicate, and allergen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

10766it [36:24,  5.08it/s]

true
Determine whether the semantic relation where RUNX family transcription factor 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10767it [36:25,  5.02it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

10769it [36:25,  4.97it/s]

true
Determine whether the semantic relation where 17β-estradiol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

10771it [36:25,  5.12it/s]

true
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, biological process is the predicate, and Q14820671 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10772it [36:26,  4.87it/s]

true
Determine whether the semantic relation where cadmium chloride is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

10773it [36:26,  4.59it/s]

true
Determine whether the semantic relation where calcium carbonate is the subject, medical condition treated is the predicate, and indigestion is the object constitutes an accurate semantic relation.

10775it [36:26,  4.80it/s]

true
Determine whether the semantic relation where iron overload is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where indigestion is the subject, drug or therapy used for treatment is the predicate, and calcium carbonate is the object constitutes an accurate semantic relation.

10776it [36:26,  4.82it/s]

true
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

10778it [36:27,  4.71it/s]

true
Determine whether the semantic relation where parasitic Ichthyosporea infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

10780it [36:27,  4.17it/s]

true
Determine whether the semantic relation where supraglottitis is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Great Lakes region is the subject, located in the administrative territorial entity is the predicate, and Ontario is the object constitutes an accurate semantic relation.

10781it [36:28,  4.27it/s]

false
Determine whether the semantic relation where epidermis is the subject, studied by is the predicate, and cell biology is the object constitutes an accurate semantic relation.

10782it [36:28,  4.36it/s]

true
Determine whether the semantic relation where Cathepsin C is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10783it [36:28,  4.41it/s]

true
Determine whether the semantic relation where experimental autoimmune encephalomyelitis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

10785it [36:28,  4.73it/s]

true
Determine whether the semantic relation where (RS)-rabeprazole is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Medicago sativa is the subject, invasive to is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

10787it [36:29,  5.05it/s]

false
Determine whether the semantic relation where Medicago sativa is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

10789it [36:29,  5.03it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where voltage-gated sodium channel complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

10790it [36:29,  4.90it/s]

true
Determine whether the semantic relation where hyperprolactinemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10792it [36:30,  5.00it/s]

true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and pimozide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine cyclic phosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10793it [36:30,  5.14it/s]

true
Determine whether the semantic relation where pimozide is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

10794it [36:30,  4.89it/s]

true
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

10796it [36:31,  4.72it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.

10797it [36:31,  3.76it/s]

true
Determine whether the semantic relation where plasmin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10799it [36:32,  4.33it/s]

false
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.

10800it [36:32,  4.53it/s]

true
Determine whether the semantic relation where pemphigus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10801it [36:32,  4.61it/s]

true
Determine whether the semantic relation where appendicitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10802it [36:32,  4.30it/s]

true
Determine whether the semantic relation where 3-hydroxybutyric acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10803it [36:32,  4.25it/s]

true
Determine whether the semantic relation where Fabry disease is the subject, subclass of is the predicate, and vascular skin disease is the object constitutes an accurate semantic relation.

10805it [36:33,  3.90it/s]

false
Determine whether the semantic relation where Cell division cycle 20 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adult lead poisoning of the nervous system is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10806it [36:33,  3.95it/s]

true
Determine whether the semantic relation where computational biology is the subject, subclass of is the predicate, and computational science is the object constitutes an accurate semantic relation.

10808it [36:34,  4.30it/s]

true
Determine whether the semantic relation where meningococcal disease is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD86 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10809it [36:34,  4.38it/s]

true
Determine whether the semantic relation where Panama is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

10811it [36:34,  4.67it/s]

false
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

10812it [36:35,  4.70it/s]

false
Determine whether the semantic relation where butylated hydroxytoluene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10814it [36:35,  4.87it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10816it [36:35,  5.10it/s]

true
Determine whether the semantic relation where leukoencephalopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.

10817it [36:36,  5.17it/s]

true
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true

10819it [36:36,  5.22it/s]

Determine whether the semantic relation where cholera is the subject, symptoms and signs is the predicate, and hypovolemia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-X-C motif chemokine receptor 4 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

10820it [36:36,  5.22it/s]

false
Determine whether the semantic relation where Eastern equine encephalitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

10821it [36:36,  4.86it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

10822it [36:37,  4.88it/s]

true
Determine whether the semantic relation where acrolein is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10823it [36:37,  4.87it/s]

false
Determine whether the semantic relation where apolipoprotein H is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10825it [36:37,  4.96it/s]

true
Determine whether the semantic relation where Histamine receptor H1 is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nitroprusside is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

10827it [36:38,  5.05it/s]

true
Determine whether the semantic relation where citric acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where herpes zoster is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

10829it [36:38,  5.20it/s]

true
Determine whether the semantic relation where health survey is the subject, subclass of is the predicate, and health informatics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

10830it [36:38,  5.35it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

10831it [36:38,  5.13it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

10833it [36:39,  5.17it/s]

true
Determine whether the semantic relation where acetaldehyde is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cefoperazone is the subject, medical condition treated is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.

10835it [36:39,  5.25it/s]

maybe
Determine whether the semantic relation where sorbic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.

10836it [36:39,  4.82it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10838it [36:40,  4.93it/s]

true
Determine whether the semantic relation where female reproductive system disease is the subject, drug or therapy used for treatment is the predicate, and cefoperazone is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where (RS)-thioctic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10840it [36:40,  5.12it/s]

true
Determine whether the semantic relation where thermodynamics is the subject, subclass of is the predicate, and physical science is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital diaphragmatic hernia is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

10841it [36:40,  5.06it/s]

false
Determine whether the semantic relation where sexology is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

10843it [36:41,  5.03it/s]

true
Determine whether the semantic relation where alloxan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 9 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10844it [36:41,  5.09it/s]

true
Determine whether the semantic relation where Amylo-alpha-1, 6-glucosidase, 4-alpha-glucanotransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10846it [36:41,  4.96it/s]

true
Determine whether the semantic relation where spermidine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where caregiver is the subject, instance of is the predicate, and health profession is the object constitutes an accurate semantic relation.

10847it [36:41,  5.11it/s]

false
Determine whether the semantic relation where nasopharynx is the subject, innervates is the predicate, and mandibular nerve is the object constitutes an accurate semantic relation.

10849it [36:42,  5.04it/s]

false
Determine whether the semantic relation where linoleic acid is the subject, subject has role is the predicate, and 5-alpha-reductase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where skin disease is the subject, drug or therapy used for treatment is the predicate, and bacitracin a is the object constitutes an accurate semantic relation.

10851it [36:42,  5.22it/s]

true
Determine whether the semantic relation where integrin subunit alpha M is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein A9 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

10852it [36:42,  5.24it/s]

false
Determine whether the semantic relation where bacitracin a is the subject, medical condition treated is the predicate, and skin disease is the object constitutes an accurate semantic relation.

10854it [36:43,  5.07it/s]

true
Determine whether the semantic relation where bilins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Complement C6 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

10855it [36:43,  4.83it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

10856it [36:43,  4.71it/s]

true
Determine whether the semantic relation where blood donor is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

10858it [36:44,  4.86it/s]

false
Determine whether the semantic relation where mRNA cleavage and polyadenylation specificity factor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where midazolam is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.

10860it [36:44,  4.98it/s]

true
Determine whether the semantic relation where microscopic polyangiitis is the subject, subclass of is the predicate, and peripheral vascular disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anxiety disorder is the subject, drug or therapy used for treatment is the predicate, and midazolam is the object constitutes an accurate semantic relation.

10861it [36:44,  4.97it/s]

false
Determine whether the semantic relation where Kyrgyzstan is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

10863it [36:45,  4.98it/s]

true
Determine whether the semantic relation where interstitial lung disease is the subject, drug or therapy used for treatment is the predicate, and tacrolimus is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where formaldehyde is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10865it [36:45,  4.86it/s]

true
Determine whether the semantic relation where mucopolysaccharidosis VI is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mathematics is the subject, has use is the predicate, and engineering is the object constitutes an accurate semantic relation.

10866it [36:45,  5.01it/s]

true
Determine whether the semantic relation where tacrolimus is the subject, medical condition treated is the predicate, and interstitial lung disease is the object constitutes an accurate semantic relation.

10867it [36:46,  4.91it/s]

false
Determine whether the semantic relation where maple syrup urine disease is the subject, has phenotype is the predicate, and hypertonia is the object constitutes an accurate semantic relation.

10869it [36:46,  4.93it/s]

true
Determine whether the semantic relation where methylglyoxal is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dextran is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

10870it [36:46,  5.03it/s]

false
Determine whether the semantic relation where adrenoceptor beta 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10872it [36:47,  4.98it/s]

false
Determine whether the semantic relation where sudden infant death syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypoglossal nerve disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10873it [36:47,  4.85it/s]

true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

10875it [36:47,  4.94it/s]

true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

10876it [36:47,  5.10it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

10877it [36:48,  4.83it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10879it [36:48,  4.95it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where orchitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10881it [36:48,  5.11it/s]

true
Determine whether the semantic relation where paresthesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

10882it [36:49,  5.11it/s]

true
Determine whether the semantic relation where fluoroquinolone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true

10884it [36:49,  5.08it/s]

Determine whether the semantic relation where chlorpromazine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where High mobility group box 1 is the subject, cell component is the predicate, and chromosome is the object constitutes an accurate semantic relation.

10886it [36:49,  5.06it/s]

true
Determine whether the semantic relation where NPH insulin is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where immunoblastic lymphadenopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10887it [36:50,  5.05it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

10888it [36:50,  4.92it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

10889it [36:50,  4.87it/s]

true
Determine whether the semantic relation where emergency medical technician is the subject, instance of is the predicate, and allied health profession is the object constitutes an accurate semantic relation.

10890it [36:50,  4.82it/s]

true
Determine whether the semantic relation where α-D-xylopyranose is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

10892it [36:51,  4.79it/s]

false
Determine whether the semantic relation where influenza is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alcohol amnestic disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

10894it [36:51,  5.03it/s]

true
Determine whether the semantic relation where tularemia is the subject, has natural reservoir is the predicate, and sheep is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hydroxy(4-hydroxy-3-methoxyphenyl)acetic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10896it [36:51,  5.30it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, religion or worldview is the predicate, and Christianity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where median nerve neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10898it [36:52,  5.24it/s]

true
Determine whether the semantic relation where diphosphate is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smoke is the subject, immediate cause of is the predicate, and death is the object constitutes an accurate semantic relation.

10899it [36:52,  5.29it/s]

maybe
Determine whether the semantic relation where cognitive behavioral therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

10901it [36:52,  5.03it/s]

true
Determine whether the semantic relation where body dysmorphic disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acromegaly is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

10902it [36:53,  5.08it/s]

true
Determine whether the semantic relation where peptone is the subject, has part(s) is the predicate, and peptide is the object constitutes an accurate semantic relation.

10904it [36:53,  5.07it/s]

true
Determine whether the semantic relation where coagulation factor II thrombin receptor is the subject, cell component is the predicate, and neuromuscular junction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where doxycycline is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

10905it [36:53,  5.07it/s]

true
Determine whether the semantic relation where nocturnal enuresis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

10907it [36:54,  4.97it/s]

true
Determine whether the semantic relation where thiram is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and doxycycline is the object constitutes an accurate semantic relation.

10909it [36:54,  5.05it/s]

true
Determine whether the semantic relation where arthritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wolfram syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

10911it [36:54,  5.14it/s]

true
Determine whether the semantic relation where granuloma is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlorpromazine is the subject, physically interacts with is the predicate, and Dopamine receptor D3 is the object constitutes an accurate semantic relation.

10912it [36:55,  4.88it/s]

true
Determine whether the semantic relation where Dopamine receptor D3 is the subject, physically interacts with is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

10913it [36:55,  4.38it/s]

true
Determine whether the semantic relation where craniology is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

10915it [36:55,  4.70it/s]

true
Determine whether the semantic relation where ferritin complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where asphyxia neonatorum is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10916it [36:55,  4.82it/s]

true
Determine whether the semantic relation where Interleukin 12A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

10917it [36:56,  4.73it/s]

true
Determine whether the semantic relation where reserpine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10919it [36:56,  4.75it/s]

false
Determine whether the semantic relation where myristic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Regenerating family member 1 alpha is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

10920it [36:56,  4.87it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

10922it [36:57,  4.96it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where β-lactulose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10924it [36:57,  5.11it/s]

false
Determine whether the semantic relation where galactosemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where primary pulmonary hypertension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

10926it [36:57,  5.14it/s]

true
Determine whether the semantic relation where meconium is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10928it [36:58,  5.08it/s]

false
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intracranial arterial disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10930it [36:58,  5.12it/s]

true
Determine whether the semantic relation where gingivitis is the subject, health specialty is the predicate, and oral medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor beta 2 is the subject, biological process is the predicate, and hemopoiesis is the object constitutes an accurate semantic relation.

10932it [36:59,  5.15it/s]

false
Determine whether the semantic relation where ischemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chickenpox is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10933it [36:59,  5.08it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.

10934it [36:59,  4.81it/s]

true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true

10935it [36:59,  4.86it/s]

Determine whether the semantic relation where Hereditary CNS demyelinating disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10937it [37:00,  4.56it/s]

true
Determine whether the semantic relation where listeriosis is the subject, has natural reservoir is the predicate, and livestock is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ADCYAP receptor type I is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10939it [37:00,  4.96it/s]

false
Determine whether the semantic relation where marker of proliferation Ki-67 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tyrosinemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10940it [37:00,  4.95it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

10942it [37:01,  5.00it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydroxysteroid 11-beta dehydrogenase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

10943it [37:01,  4.93it/s]

true
Determine whether the semantic relation where Klinefelter's syndrome is the subject, symptoms and signs is the predicate, and obesity is the object constitutes an accurate semantic relation.

10945it [37:01,  4.92it/s]

true
Determine whether the semantic relation where intestinal disease is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stiff-person syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

10947it [37:02,  5.00it/s]

true
Determine whether the semantic relation where health service is the subject, studied by is the predicate, and public health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bionics is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

10949it [37:02,  5.12it/s]

false
Determine whether the semantic relation where N-acylsphingosine amidohydrolase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Hibiscus is the object constitutes an accurate semantic relation.

10951it [37:02,  5.24it/s]

true
Determine whether the semantic relation where Gene Ontology is the subject, main subject is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where growth disorder is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

10953it [37:03,  4.99it/s]

false
Determine whether the semantic relation where endometrial hyperplasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Matrix metallopeptidase 7 is the subject, biological process is the predicate, and estrous cycle is the object constitutes an accurate semantic relation.

10955it [37:03,  5.09it/s]

false
Determine whether the semantic relation where adenosine diphosphate ribose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epidemiological method is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

10957it [37:04,  5.16it/s]

true
Determine whether the semantic relation where erythromycin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary edema is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

10958it [37:04,  5.23it/s]

true
Determine whether the semantic relation where buspirone is the subject, medical condition treated is the predicate, and intellectual disability is the object constitutes an accurate semantic relation.

10959it [37:04,  4.40it/s]

false
Determine whether the semantic relation where meat is the subject, natural product of taxon is the predicate, and Reptilia is the object constitutes an accurate semantic relation.

10960it [37:04,  3.95it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.

10962it [37:05,  4.38it/s]

true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Dystrophin is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

10964it [37:05,  4.83it/s]

false
Determine whether the semantic relation where Galectin 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anovulation is the subject, health specialty is the predicate, and gynaecology is the object constitutes an accurate semantic relation.

10966it [37:06,  4.81it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 4 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatotoxicity is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

10968it [37:06,  4.77it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

10969it [37:06,  4.77it/s]

true
Determine whether the semantic relation where vertically transmitted infection is the subject, subclass of is the predicate, and congenital disorder is the object constitutes an accurate semantic relation.

10971it [37:07,  4.85it/s]

false
Determine whether the semantic relation where Coagulation factor XII is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

10973it [37:07,  4.92it/s]

false
Determine whether the semantic relation where aztreonam is the subject, medical condition treated is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where female reproductive system disease is the subject, drug or therapy used for treatment is the predicate, and aztreonam is the object constitutes an accurate semantic relation.

10975it [37:08,  5.26it/s]

false
Determine whether the semantic relation where D-glucosamine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (RS)-acetoin is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

10976it [37:08,  5.20it/s]

false
Determine whether the semantic relation where intercellular adhesion molecule 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10978it [37:08,  5.25it/s]

true
Determine whether the semantic relation where parvovirus infectious disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zinc acetate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

10980it [37:08,  5.17it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 20 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and stomatitis is the object constitutes an accurate semantic relation.

10981it [37:09,  5.01it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

10982it [37:09,  4.99it/s]

true
Determine whether the semantic relation where lansoprazole is the subject, legal status (medicine) is the predicate, and prescription drug is the object constitutes an accurate semantic relation.

10983it [37:09,  4.62it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

10984it [37:09,  4.59it/s]

true
Determine whether the semantic relation where scrub typhus is the subject, anatomical location is the predicate, and skin is the object constitutes an accurate semantic relation.

10985it [37:10,  4.38it/s]

false
Determine whether the semantic relation where muteness is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

10987it [37:10,  4.56it/s]

false
Determine whether the semantic relation where vitiligo is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebral palsy is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.

10988it [37:10,  4.61it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Botswana is the object constitutes an accurate semantic relation.

10990it [37:11,  4.83it/s]

true
Determine whether the semantic relation where panophthalmitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Phosphofructokinase, muscle is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

10992it [37:11,  4.37it/s]

true
Determine whether the semantic relation where heart disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

10994it [37:12,  4.63it/s]

true
Determine whether the semantic relation where Botswana is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

10996it [37:12,  4.92it/s]

false
Determine whether the semantic relation where chromophore-assisted light inactivation is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone demineralization technique is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

10997it [37:12,  4.94it/s]

true
Determine whether the semantic relation where hypovolemia is the subject, subclass of is the predicate, and hematopoietic system disease is the object constitutes an accurate semantic relation.

10999it [37:13,  5.12it/s]

false
Determine whether the semantic relation where anisomycin is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sound spectrography is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11000it [37:13,  5.14it/s]

false
Determine whether the semantic relation where endpoint determination is the subject, instance of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11002it [37:13,  4.47it/s]

false
Determine whether the semantic relation where microchip analytical procedure is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

11003it [37:13,  4.66it/s]

false
Determine whether the semantic relation where chylous ascites is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

11004it [37:14,  4.38it/s]

false
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.

11006it [37:14,  4.68it/s]

true
Determine whether the semantic relation where decision support techniques is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where electrochemical technique is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11008it [37:15,  4.99it/s]

maybe
Determine whether the semantic relation where in vitro experiment is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where medical equipment failure is the subject, facet of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11009it [37:15,  5.10it/s]

false
Determine whether the semantic relation where biomedical equipment design is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11011it [37:15,  4.74it/s]

false
Determine whether the semantic relation where Glycyl-tRNA synthetase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where molecular probe techniques is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11012it [37:15,  4.85it/s]

true
Determine whether the semantic relation where ergometry is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11014it [37:16,  4.97it/s]

true
Determine whether the semantic relation where oxamic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neoplasm transplantation is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11016it [37:16,  4.93it/s]

true
Determine whether the semantic relation where dilatation is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
false

11017it [37:16,  4.99it/s]

Determine whether the semantic relation where tibial neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trauma severity indices is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11018it [37:17,  4.69it/s]

false
Determine whether the semantic relation where choristoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11019it [37:17,  4.76it/s]

true
Determine whether the semantic relation where schistosomiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

11021it [37:17,  4.81it/s]

true
Determine whether the semantic relation where glomus tumor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aortic valve insufficiency is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

11023it [37:18,  5.12it/s]

true
Determine whether the semantic relation where choledochal cyst is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intracranial aneurysm is the subject, medical examination is the predicate, and electroencephalography is the object constitutes an accurate semantic relation.

11024it [37:18,  5.14it/s]

false
Determine whether the semantic relation where blood coagulation is the subject, part of is the predicate, and wound healing is the object constitutes an accurate semantic relation.

11025it [37:18,  5.06it/s]

true
Determine whether the semantic relation where spermine is the subject, found in taxon is the predicate, and Pseudomonas is the object constitutes an accurate semantic relation.

11027it [37:18,  4.73it/s]

false
Determine whether the semantic relation where esophageal cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where geotrichosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

11029it [37:19,  4.62it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

11030it [37:19,  4.59it/s]

true
Determine whether the semantic relation where methenamine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11031it [37:19,  4.58it/s]

true
Determine whether the semantic relation where ectodysplasin A2 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11032it [37:20,  4.54it/s]

true
Determine whether the semantic relation where Serbia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11034it [37:20,  4.79it/s]

true
Determine whether the semantic relation where plastic is the subject, made from material is the predicate, and fossil fuel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromycin is the subject, medical condition treated is the predicate, and anthrax is the object constitutes an accurate semantic relation.

11036it [37:20,  4.91it/s]

true
Determine whether the semantic relation where anthrax is the subject, drug or therapy used for treatment is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ecological parameter monitoring is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.

11038it [37:21,  4.93it/s]

false
Determine whether the semantic relation where clioquinol is the subject, subclass of is the predicate, and allergen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glutamate carboxypeptidase II is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11040it [37:21,  5.20it/s]

true
Determine whether the semantic relation where neuromuscular blockade is the subject, subclass of is the predicate, and biomedical investigative technique is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

11042it [37:22,  5.13it/s]

false
Determine whether the semantic relation where pituitary apoplexy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

11044it [37:22,  5.14it/s]

true
Determine whether the semantic relation where ficoll is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false

11045it [37:22,  5.14it/s]

Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Montenegro is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

11046it [37:22,  5.17it/s]

true
Determine whether the semantic relation where Montenegro is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

11048it [37:23,  4.81it/s]

true
Determine whether the semantic relation where biomarker is the subject, part of is the predicate, and biology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where African Americans is the subject, religion or worldview is the predicate, and Islam is the object constitutes an accurate semantic relation.

11050it [37:23,  5.05it/s]

maybe
Determine whether the semantic relation where DL-lactic acid is the subject, medical condition treated is the predicate, and facial dermatosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where facial dermatosis is the subject, drug or therapy used for treatment is the predicate, and DL-lactic acid is the object constitutes an accurate semantic relation.

11052it [37:24,  5.06it/s]

false
Determine whether the semantic relation where solute carrier family 7 member 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chromium is the subject, found in taxon is the predicate, and Passiflora is the object constitutes an accurate semantic relation.

11054it [37:24,  5.15it/s]

false
Determine whether the semantic relation where hydrocephalus is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ERBB2 is the subject, expressed in is the predicate, and sural nerve is the object constitutes an accurate semantic relation.

11055it [37:24,  5.01it/s]

false
Determine whether the semantic relation where Plummer–Vinson syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

11057it [37:25,  5.10it/s]

true
Determine whether the semantic relation where metronidazole is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where giant cell arteritis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

11059it [37:25,  5.21it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

11060it [37:25,  5.12it/s]

true
Determine whether the semantic relation where cutaneous lupus erythematosus is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

11061it [37:25,  4.97it/s]

false
Determine whether the semantic relation where clomipramine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

11063it [37:26,  4.74it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and clomipramine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where facioscapulohumeral muscular dystrophy is the subject, possible treatment is the predicate, and occupational therapy is the object constitutes an accurate semantic relation.

11065it [37:26,  4.96it/s]

true
Determine whether the semantic relation where Perforin 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leishmaniasis is the subject, risk factor is the predicate, and immunosuppression is the object constitutes an accurate semantic relation.

11066it [37:26,  4.41it/s]

true
Determine whether the semantic relation where butane-2,3-dione is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11068it [37:27,  4.62it/s]

true
Determine whether the semantic relation where glutamic-pyruvic transaminase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vaginal discharge is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.

11070it [37:27,  4.88it/s]

true
Determine whether the semantic relation where sialic acids is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pleural tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

11072it [37:28,  5.05it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Araceae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where impulsivity is the subject, facet of is the predicate, and risk is the object constitutes an accurate semantic relation.

11074it [37:28,  5.00it/s]

false
Determine whether the semantic relation where Urachal cyst is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and Datura stramonium is the object constitutes an accurate semantic relation.

11075it [37:28,  5.22it/s]

false
Determine whether the semantic relation where parathyroid hormone 1 receptor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11076it [37:28,  5.12it/s]

false
Determine whether the semantic relation where brucellosis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

11077it [37:29,  4.76it/s]

true
Determine whether the semantic relation where crystallin alpha B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11079it [37:29,  4.64it/s]

false
Determine whether the semantic relation where oxiglutatione is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sisomicin is the subject, subject has role is the predicate, and protein synthesis inhibitor is the object constitutes an accurate semantic relation.

11080it [37:29,  4.79it/s]

true
Determine whether the semantic relation where biliary fistula is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

11082it [37:30,  4.99it/s]

false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

11084it [37:30,  5.27it/s]

true
Determine whether the semantic relation where familial hypophosphatemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopa decarboxylase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11086it [37:30,  5.35it/s]

true
Determine whether the semantic relation where postmenopausal osteoporosis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nerve growth factor receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11088it [37:31,  5.26it/s]

false
Determine whether the semantic relation where cardiovascular disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where severe acute respiratory syndrome is the subject, health specialty is the predicate, and microbiology is the object constitutes an accurate semantic relation.

11089it [37:31,  5.29it/s]

false
Determine whether the semantic relation where aralkylamine N-acetyltransferase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11090it [37:31,  5.10it/s]

false
Determine whether the semantic relation where premenstrual dysphoric disorder is the subject, instance of is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.

11091it [37:31,  5.03it/s]

true
Determine whether the semantic relation where CD40 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11092it [37:32,  4.88it/s]

true
Determine whether the semantic relation where protein tyrosine kinase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11094it [37:32,  4.96it/s]

false
Determine whether the semantic relation where stroke is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where polyuria is the subject, health specialty is the predicate, and nephrology is the object constitutes an accurate semantic relation.

11095it [37:32,  5.10it/s]

false
Determine whether the semantic relation where arylamine N-acetyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11097it [37:33,  4.98it/s]

true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Belize is the object constitutes an accurate semantic relation.

11099it [37:33,  5.09it/s]

true
Determine whether the semantic relation where Belize is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Susac's syndrome is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

11101it [37:33,  4.98it/s]

true
Determine whether the semantic relation where zymosan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mucinosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

11102it [37:34,  4.75it/s]

false
Determine whether the semantic relation where phytanic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11103it [37:34,  4.56it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

11104it [37:34,  4.55it/s]

true
Determine whether the semantic relation where CD40 ligand is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11105it [37:34,  4.51it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

11107it [37:35,  4.46it/s]

true
Determine whether the semantic relation where disorder of sex development is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where starch is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11108it [37:35,  4.59it/s]

false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

11110it [37:35,  4.86it/s]

true
Determine whether the semantic relation where myiasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where daunorubicin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

11112it [37:36,  5.12it/s]

false
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Bolivia is the object constitutes an accurate semantic relation.

11113it [37:36,  4.99it/s]

true
Determine whether the semantic relation where Bolivia is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

11115it [37:36,  5.04it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where California encephalitis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

11116it [37:37,  5.12it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, subclass of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

11118it [37:37,  5.18it/s]

true
Determine whether the semantic relation where creatine kinase B is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Waterhouse-Friderichsen syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11120it [37:37,  5.18it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true

11121it [37:38,  5.13it/s]

Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Complement C5 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11122it [37:38,  5.04it/s]

false
Determine whether the semantic relation where lysergic acid is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

11124it [37:38,  4.86it/s]

true
Determine whether the semantic relation where putrescine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptorchidism is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

11125it [37:38,  4.81it/s]

false
Determine whether the semantic relation where S-antigen visual arrestin is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11127it [37:39,  4.85it/s]

false
Determine whether the semantic relation where gait abnormality is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

11129it [37:39,  5.06it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

11131it [37:40,  5.11it/s]

true
Determine whether the semantic relation where filarial elephantiasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Cucumis melo is the object constitutes an accurate semantic relation.

11132it [37:40,  4.85it/s]

false
Determine whether the semantic relation where secondary parkinsonism is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11134it [37:40,  4.97it/s]

true
Determine whether the semantic relation where dacryocystitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.

11136it [37:41,  5.07it/s]

true
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.

11138it [37:41,  5.06it/s]

true
Determine whether the semantic relation where arsenite is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phosphoglycerate dehydrogenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11140it [37:41,  5.26it/s]

true
Determine whether the semantic relation where phosphoglycerate dehydrogenase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulfur oxoacid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11141it [37:42,  4.90it/s]

true
Determine whether the semantic relation where mass media is the subject, subclass of is the predicate, and information system is the object constitutes an accurate semantic relation.

11143it [37:42,  4.71it/s]

true
Determine whether the semantic relation where neonatal abstinence syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow nail syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

11144it [37:42,  4.83it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

11146it [37:43,  4.94it/s]

true
Determine whether the semantic relation where Argininosuccinate lyase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

11147it [37:43,  5.03it/s]

true
Determine whether the semantic relation where arsenic poisoning is the subject, has effect is the predicate, and anemia is the object constitutes an accurate semantic relation.

11149it [37:43,  4.62it/s]

true
Determine whether the semantic relation where Q21173788 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where blood plasma is the subject, has part(s) is the predicate, and globulins is the object constitutes an accurate semantic relation.

11151it [37:44,  4.96it/s]

true
Determine whether the semantic relation where scarlet fever is the subject, drug or therapy used for treatment is the predicate, and histamine antagonist is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nonunion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11153it [37:44,  4.98it/s]

false
Determine whether the semantic relation where levofloxacin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nuclear power plant is the subject, product or material produced is the predicate, and electricity is the object constitutes an accurate semantic relation.

11155it [37:45,  5.10it/s]

true
Determine whether the semantic relation where Solute carrier family 12 member 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

11157it [37:45,  5.15it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11158it [37:45,  4.75it/s]

true
Determine whether the semantic relation where hemophagocytic lymphohistiocytosis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

11159it [37:45,  4.71it/s]

true
Determine whether the semantic relation where person is the subject, has characteristic is the predicate, and personality is the object constitutes an accurate semantic relation.

11160it [37:46,  4.74it/s]

true
Determine whether the semantic relation where neurotensin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11162it [37:46,  4.79it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intracranial vasospasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11163it [37:46,  5.03it/s]

true
Determine whether the semantic relation where DNA nucleotidylexotransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11164it [37:46,  4.60it/s]

true
Determine whether the semantic relation where sulfite oxidase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11165it [37:47,  4.63it/s]

false
Determine whether the semantic relation where seasonal allergic rhinitis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

11166it [37:47,  4.55it/s]

false
Determine whether the semantic relation where dexamethasone is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11168it [37:47,  4.81it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and meninges is the object constitutes an accurate semantic relation.

11170it [37:48,  4.84it/s]

false
Determine whether the semantic relation where carcinoid syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

11171it [37:48,  4.86it/s]

true
Determine whether the semantic relation where Vinculin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false

11173it [37:48,  5.00it/s]

Determine whether the semantic relation where opisthorchiasis is the subject, subclass of is the predicate, and pancreas disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where recurrent miscarriage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11175it [37:49,  5.15it/s]

true
Determine whether the semantic relation where pentose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

11177it [37:49,  5.16it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Apolipoprotein B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11179it [37:49,  5.25it/s]

true
Determine whether the semantic relation where prednimustine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where meningococcal disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

11180it [37:50,  5.24it/s]

true
Determine whether the semantic relation where isatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11181it [37:50,  4.88it/s]

false
Determine whether the semantic relation where Adenosylhomocysteinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11183it [37:50,  4.51it/s]

false
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true

11184it [37:51,  4.63it/s]

Determine whether the semantic relation where legionnaires' disease is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fetal death is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11185it [37:51,  4.30it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

11186it [37:51,  4.33it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and neck is the object constitutes an accurate semantic relation.

11188it [37:51,  4.68it/s]

true
Determine whether the semantic relation where atheroma is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where E1A binding protein p300 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11190it [37:52,  5.04it/s]

false
Determine whether the semantic relation where Msh homeobox 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

11192it [37:52,  5.19it/s]

true
Determine whether the semantic relation where canthaxanthin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prostaglandin E receptor 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11194it [37:53,  5.04it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

11196it [37:53,  5.05it/s]

false
Determine whether the semantic relation where amnesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rett syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

11197it [37:53,  5.02it/s]

true
Determine whether the semantic relation where AMPA receptor is the subject, facilitates flow of is the predicate, and sodium is the object constitutes an accurate semantic relation.

11199it [37:54,  4.96it/s]

true
Determine whether the semantic relation where Denmark is the subject, member of is the predicate, and Organization for Economic Cooperation and Development is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11200it [37:54,  4.46it/s]

true
Determine whether the semantic relation where transformed cell line is the subject, has cause is the predicate, and transformation is the object constitutes an accurate semantic relation.

11202it [37:54,  4.62it/s]

false
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, cell component is the predicate, and spindle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where zearalenone is the subject, subclass of is the predicate, and macrolides is the object constitutes an accurate semantic relation.

11204it [37:55,  5.00it/s]

false
Determine whether the semantic relation where urinary schistosomiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oxytocin is the subject, different from is the predicate, and oxycodone is the object constitutes an accurate semantic relation.

11205it [37:55,  4.98it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

11207it [37:55,  5.00it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic granulomatous disease is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

11208it [37:56,  4.85it/s]

false
Determine whether the semantic relation where insulin is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

11210it [37:56,  4.92it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 5 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where iatrogenesis is the subject, has cause is the predicate, and therapy is the object constitutes an accurate semantic relation.

11211it [37:56,  5.07it/s]

true
Determine whether the semantic relation where ubiquitin C is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

11213it [37:57,  4.99it/s]

false
Determine whether the semantic relation where Galectin 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral capsid is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

11215it [37:57,  5.14it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DNA polymerase beta is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

11217it [37:57,  5.17it/s]

maybe
Determine whether the semantic relation where air embolism is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where apolipoproteins E is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11219it [37:58,  5.23it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

11221it [37:58,  5.15it/s]

true
Determine whether the semantic relation where chromium is the subject, found in taxon is the predicate, and Streptomyces griseus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adult-onset Still's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11222it [37:58,  4.83it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Brassica rapa is the object constitutes an accurate semantic relation.

11224it [37:59,  4.76it/s]

false
Determine whether the semantic relation where intellectual disability is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intellectual disability is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

11225it [37:59,  4.59it/s]

false
Determine whether the semantic relation where carpal tunnel syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11227it [37:59,  4.70it/s]

maybe
Determine whether the semantic relation where trichotillomania is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true

11228it [38:00,  4.77it/s]

Determine whether the semantic relation where proguanil is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.
false

11229it [38:00,  4.90it/s]

Determine whether the semantic relation where vaccinia is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and blood is the object constitutes an accurate semantic relation.

11231it [38:00,  4.87it/s]

true
Determine whether the semantic relation where Q13522706 is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Behçet's disease is the subject, has cause is the predicate, and immune system is the object constitutes an accurate semantic relation.

11233it [38:01,  5.03it/s]

maybe
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

11235it [38:01,  4.88it/s]

true
Determine whether the semantic relation where POU class 4 homeobox 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where keratin 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11236it [38:01,  4.86it/s]

true
Determine whether the semantic relation where BCL2 is the subject, expressed in is the predicate, and optic nerve is the object constitutes an accurate semantic relation.

11237it [38:01,  4.88it/s]

false
Determine whether the semantic relation where bromodeoxyuridine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11239it [38:02,  4.90it/s]

true
Determine whether the semantic relation where Tyrosine aminotransferase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where physical science is the subject, has part(s) is the predicate, and crystallography is the object constitutes an accurate semantic relation.

11241it [38:02,  4.95it/s]

true
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cystathionine gamma-lyase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11242it [38:02,  4.73it/s]

true
Determine whether the semantic relation where Cystathionine gamma-lyase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11244it [38:03,  4.93it/s]

true
Determine whether the semantic relation where adrenochrome is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tooth discoloration is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

11246it [38:03,  5.09it/s]

false
Determine whether the semantic relation where Kaposi's sarcoma is the subject, symptoms and signs is the predicate, and metastasis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where parathyroid hormone 1 receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11248it [38:04,  5.00it/s]

false
Determine whether the semantic relation where cytochrome P450 family 2 subfamily A member 6 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where taurine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

11250it [38:04,  5.21it/s]

false
Determine whether the semantic relation where gallic acid is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ergoloid mesylate is the subject, route of administration is the predicate, and subcutaneous injection is the object constitutes an accurate semantic relation.

11252it [38:04,  5.24it/s]

false
Determine whether the semantic relation where malaria is the subject, possible treatment is the predicate, and antipyretic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (RS)-baclofen is the subject, subclass of is the predicate, and aromatic amino acid is the object constitutes an accurate semantic relation.

11253it [38:05,  5.24it/s]

false
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.

11255it [38:05,  4.70it/s]

true
Determine whether the semantic relation where legionellosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carnosine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11256it [38:05,  4.90it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

11258it [38:06,  4.82it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

11259it [38:06,  4.98it/s]

true
Determine whether the semantic relation where formazan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11260it [38:06,  4.97it/s]

false
Determine whether the semantic relation where melanoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11262it [38:07,  4.79it/s]

false
Determine whether the semantic relation where putrescine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pneumococcal infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

11264it [38:07,  5.04it/s]

true
Determine whether the semantic relation where acariasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brugada syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11266it [38:07,  5.11it/s]

true
Determine whether the semantic relation where transient cerebral isolation is the subject, health specialty is the predicate, and neurosurgery is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where crush syndrome is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

11268it [38:08,  5.25it/s]

true
Determine whether the semantic relation where vitamin deficiency is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where posterior reversible encephalopathy syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11270it [38:08,  5.11it/s]

true
Determine whether the semantic relation where calcium carbonate is the subject, medical condition treated is the predicate, and peptic esophagitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where peptic esophagitis is the subject, drug or therapy used for treatment is the predicate, and calcium carbonate is the object constitutes an accurate semantic relation.

11272it [38:08,  5.13it/s]

false
Determine whether the semantic relation where Crigler-Najjar syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where silicon dioxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11273it [38:09,  5.03it/s]

true
Determine whether the semantic relation where myelin sheath is the subject, subclass of is the predicate, and lipoprotein is the object constitutes an accurate semantic relation.

11274it [38:09,  5.00it/s]

false
Determine whether the semantic relation where cortisone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11275it [38:09,  4.68it/s]

false
Determine whether the semantic relation where arteriovenous fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11277it [38:10,  4.83it/s]

false
Determine whether the semantic relation where 17α-hydroxyprogesterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alcoholic hepatitis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

11278it [38:10,  5.01it/s]

true
Determine whether the semantic relation where systemic lupus erythematosus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11279it [38:10,  4.67it/s]

true
Determine whether the semantic relation where C-reactive protein is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

11281it [38:10,  4.68it/s]

false
Determine whether the semantic relation where idiopathic interstitial pneumonia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where idiopathic interstitial pneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11282it [38:11,  4.83it/s]

true
Determine whether the semantic relation where right heart bypass is the subject, subclass of is the predicate, and coronary artery bypass surgery is the object constitutes an accurate semantic relation.

11284it [38:11,  4.85it/s]

false
Determine whether the semantic relation where sciatica is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thrombogavitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11285it [38:11,  5.02it/s]

true
Determine whether the semantic relation where insulin like growth factor 1 receptor is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

11286it [38:11,  4.95it/s]

false
Determine whether the semantic relation where branchial cleft cyst is the subject, instance of is the predicate, and congenital disorder is the object constitutes an accurate semantic relation.
true

11288it [38:12,  4.99it/s]

Determine whether the semantic relation where hemimegalencephaly is the subject, subclass of is the predicate, and neurodevelopmental disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where LDL receptor related protein 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11290it [38:12,  5.11it/s]

false
Determine whether the semantic relation where hyperopia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Benin is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

11291it [38:12,  4.90it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Benin is the object constitutes an accurate semantic relation.

11293it [38:13,  4.77it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

11295it [38:13,  4.78it/s]

true
Determine whether the semantic relation where neurology is the subject, is the study of is the predicate, and nervous system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nervous system is the subject, studied by is the predicate, and neurology is the object constitutes an accurate semantic relation.

11296it [38:13,  4.74it/s]

true
Determine whether the semantic relation where acute kidney tubular necrosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11297it [38:14,  4.30it/s]

true
Determine whether the semantic relation where acute kidney tubular necrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11299it [38:14,  4.63it/s]

true
Determine whether the semantic relation where squalene is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and Astragalus membranaceus is the object constitutes an accurate semantic relation.

11300it [38:14,  4.82it/s]

false
Determine whether the semantic relation where dermatomyositis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

11301it [38:15,  4.28it/s]

false
Determine whether the semantic relation where myocardial reperfusion injury is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

11302it [38:15,  4.06it/s]

false
Determine whether the semantic relation where pneumopericardium is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

11304it [38:15,  4.33it/s]

false
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, medical condition treated is the predicate, and lung disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MELAS syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11305it [38:16,  4.42it/s]

true
Determine whether the semantic relation where herpangina is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

11307it [38:16,  4.71it/s]

true
Determine whether the semantic relation where lung disease is the subject, drug or therapy used for treatment is the predicate, and N-acetyl-L-cysteine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acatalasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11309it [38:16,  4.95it/s]

true
Determine whether the semantic relation where Job's syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperbaric medicine is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

11311it [38:17,  5.05it/s]

false
Determine whether the semantic relation where endocrine system disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mycosis fungoides is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11313it [38:17,  4.99it/s]

true
Determine whether the semantic relation where Calbindin 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dicloxacillin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

11315it [38:18,  5.07it/s]

false
Determine whether the semantic relation where extracellular fluid is the subject, opposite of is the predicate, and intracellular fluid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ammonium sulfate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11316it [38:18,  4.88it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Denmark is the object constitutes an accurate semantic relation.

11317it [38:18,  4.62it/s]

false
Determine whether the semantic relation where intracellular fluid is the subject, opposite of is the predicate, and extracellular fluid is the object constitutes an accurate semantic relation.

11318it [38:18,  4.69it/s]

true
Determine whether the semantic relation where palmoplantar keratosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

11319it [38:18,  4.65it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

11321it [38:19,  4.93it/s]

true
Determine whether the semantic relation where odontogenic cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paroxysmal nocturnal hemoglobinuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11322it [38:19,  5.02it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

11324it [38:19,  5.05it/s]

true
Determine whether the semantic relation where blood group antigen is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alpha-linolenic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11325it [38:20,  5.11it/s]

true
Determine whether the semantic relation where Germany is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11326it [38:20,  4.64it/s]

true
Determine whether the semantic relation where urethane is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11327it [38:20,  4.57it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

11328it [38:20,  4.64it/s]

true
Determine whether the semantic relation where insulin receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

11330it [38:21,  4.76it/s]

false
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true

11331it [38:21,  4.96it/s]

Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thymidine monophosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11332it [38:21,  5.06it/s]

true
Determine whether the semantic relation where gas gangrene is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11333it [38:21,  4.85it/s]

true
Determine whether the semantic relation where Solute carrier family 12, member 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11335it [38:22,  4.89it/s]

true
Determine whether the semantic relation where peptidase inhibitor 3 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Phosphofructokinase, liver type is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11337it [38:22,  5.11it/s]

true
Determine whether the semantic relation where CSK is the subject, expressed in is the predicate, and thymus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major histocompatibility complex, class I, C is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

11338it [38:22,  5.13it/s]

false
Determine whether the semantic relation where geography is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.

11340it [38:23,  4.97it/s]

true
Determine whether the semantic relation where viral meningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true

11341it [38:23,  5.04it/s]

Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

11342it [38:23,  5.02it/s]

false
Determine whether the semantic relation where Canada is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

11344it [38:24,  4.98it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where latex allergy is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

11346it [38:24,  5.22it/s]

false
Determine whether the semantic relation where occupational medicine is the subject, different from is the predicate, and occupational therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acridine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11348it [38:24,  5.28it/s]

true
Determine whether the semantic relation where Janus kinase 1 is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DL-dopa is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

11349it [38:24,  5.22it/s]

false
Determine whether the semantic relation where Kallikrein related peptidase 3 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

11350it [38:25,  5.02it/s]

true
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

11351it [38:25,  4.91it/s]

false
Determine whether the semantic relation where auramine hydrochloride is the subject, subject has role is the predicate, and anti-infective agent is the object constitutes an accurate semantic relation.

11352it [38:25,  4.75it/s]

false
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

11354it [38:26,  4.81it/s]

false
Determine whether the semantic relation where CD1d molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where monoethanolamine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

11355it [38:26,  4.74it/s]

false
Determine whether the semantic relation where hyperaldosteronism is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11356it [38:26,  4.41it/s]

true
Determine whether the semantic relation where syphilis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11358it [38:26,  4.53it/s]

true
Determine whether the semantic relation where equine Strongyle infections is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, two Ig domains and long cytoplasmic tail 3 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

11360it [38:27,  4.88it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Xanthine dehydrogenase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11362it [38:27,  4.97it/s]

true
Determine whether the semantic relation where uridine diphosphate glucuronic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

11363it [38:27,  4.82it/s]

true
Determine whether the semantic relation where Dystrophin is the subject, biological process is the predicate, and peptide biosynthetic process is the object constitutes an accurate semantic relation.

11364it [38:28,  4.59it/s]

false
Determine whether the semantic relation where abscess is the subject, symptoms and signs is the predicate, and erythema is the object constitutes an accurate semantic relation.

11366it [38:28,  4.83it/s]

true
Determine whether the semantic relation where scrofula is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cellulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11367it [38:28,  4.99it/s]

false
Determine whether the semantic relation where glucose-6-phosphate isomerase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11368it [38:28,  4.92it/s]

true
Determine whether the semantic relation where skin disease is the subject, drug or therapy used for treatment is the predicate, and botulinum toxin type A is the object constitutes an accurate semantic relation.

11369it [38:29,  4.89it/s]

true
Determine whether the semantic relation where liver is the subject, anatomical location is the predicate, and abdominal cavity is the object constitutes an accurate semantic relation.

11370it [38:29,  4.86it/s]

true
Determine whether the semantic relation where abdominal cavity is the subject, has part(s) is the predicate, and liver is the object constitutes an accurate semantic relation.

11371it [38:29,  4.72it/s]

true
Determine whether the semantic relation where neurotensin is the subject, cell component is the predicate, and transport vesicle is the object constitutes an accurate semantic relation.

11372it [38:29,  4.77it/s]

true
Determine whether the semantic relation where botulinum toxin type A is the subject, medical condition treated is the predicate, and skin disease is the object constitutes an accurate semantic relation.

11374it [38:30,  4.87it/s]

false
Determine whether the semantic relation where spermine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbon tetrachloride exposure is the subject, symptoms and signs is the predicate, and kidney disease is the object constitutes an accurate semantic relation.

11376it [38:30,  4.96it/s]

true
Determine whether the semantic relation where glanders is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nephrocalcinosis is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

11377it [38:30,  4.89it/s]

true
Determine whether the semantic relation where torture is the subject, has effect is the predicate, and pain is the object constitutes an accurate semantic relation.

11379it [38:31,  4.70it/s]

true
Determine whether the semantic relation where homocystinuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein B is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

11381it [38:31,  4.73it/s]

maybe
Determine whether the semantic relation where vimentin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 11 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11383it [38:32,  4.90it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

11384it [38:32,  5.02it/s]

true
Determine whether the semantic relation where cardiomyopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11386it [38:32,  4.89it/s]

true
Determine whether the semantic relation where Ludwig's angina is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral leishmaniasis is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

11387it [38:32,  4.94it/s]

false
Determine whether the semantic relation where D-(-)-mannitol is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

11388it [38:33,  4.80it/s]

false
Determine whether the semantic relation where optic nerve tumor is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11389it [38:33,  4.84it/s]

false
Determine whether the semantic relation where heart disease is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

11391it [38:33,  4.84it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spermidine is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

11392it [38:33,  4.91it/s]

false
Determine whether the semantic relation where Aryl hydrocarbon receptor nuclear translocator like is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11393it [38:34,  4.90it/s]

true
Determine whether the semantic relation where beta-hexosaminidase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11395it [38:34,  5.02it/s]

true
Determine whether the semantic relation where megaloblastic anemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where population dynamics is the subject, subclass of is the predicate, and life sciences is the object constitutes an accurate semantic relation.

11397it [38:34,  5.09it/s]

true
Determine whether the semantic relation where E2F transcription factor 1 is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bisphosphonate-associated osteonecrosis of the jaw is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

11398it [38:35,  5.15it/s]

false
Determine whether the semantic relation where poliomyelitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11399it [38:35,  4.89it/s]

true
Determine whether the semantic relation where motion sickness is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11400it [38:35,  4.67it/s]

true
Determine whether the semantic relation where diethylhexyl phthalate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11401it [38:35,  4.73it/s]

true
Determine whether the semantic relation where tumor protein p53 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11403it [38:36,  4.80it/s]

true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 4 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibrous dysplasia of bone is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

11404it [38:36,  4.86it/s]

false
Determine whether the semantic relation where Finland is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

11406it [38:36,  4.96it/s]

true
Determine whether the semantic relation where neonatal anemia is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carpal tunnel syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11407it [38:37,  4.97it/s]

false
Determine whether the semantic relation where gamma globulin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11408it [38:37,  4.89it/s]

false
Determine whether the semantic relation where L-alanine is the subject, part of is the predicate, and zein is the object constitutes an accurate semantic relation.

11410it [38:37,  4.69it/s]

false
Determine whether the semantic relation where parotid disease is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gallbladder disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11411it [38:37,  4.84it/s]

true
Determine whether the semantic relation where rhodopsin is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

11413it [38:38,  4.86it/s]

false
Determine whether the semantic relation where hepatitis E is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true

11414it [38:38,  4.95it/s]

Determine whether the semantic relation where inhibitor of DNA binding 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cecal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

11415it [38:38,  5.06it/s]

true
Determine whether the semantic relation where Indonesia is the subject, religion or worldview is the predicate, and Buddhism is the object constitutes an accurate semantic relation.

11417it [38:39,  5.00it/s]

true
Determine whether the semantic relation where hypoglycemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyclin dependent kinase 5 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11419it [38:39,  5.06it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where learning disability is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

11420it [38:39,  4.92it/s]

false
Determine whether the semantic relation where chemically induced disorder is the subject, subclass of is the predicate, and environmental disease is the object constitutes an accurate semantic relation.

11422it [38:40,  5.07it/s]

true
Determine whether the semantic relation where plague is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystathionine gamma-lyase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11423it [38:40,  5.05it/s]

false
Determine whether the semantic relation where SMAD family member 7 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

11424it [38:40,  4.98it/s]

true
Determine whether the semantic relation where Thy-1 cell surface antigen is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

11425it [38:40,  4.74it/s]

true
Determine whether the semantic relation where 4-thiouridine is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.

11426it [38:40,  4.51it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and meclofenamic acid is the object constitutes an accurate semantic relation.

11427it [38:41,  4.36it/s]

false
Determine whether the semantic relation where meclofenamic acid is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

11429it [38:41,  4.47it/s]

true
Determine whether the semantic relation where polyphosphate is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sensorineural hearing loss is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11431it [38:42,  4.78it/s]

true
Determine whether the semantic relation where Chagas disease is the subject, symptoms and signs is the predicate, and splenomegaly is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where furanocoumarin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11433it [38:42,  5.01it/s]

true
Determine whether the semantic relation where Apolipoprotein B is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxolinic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11435it [38:42,  5.10it/s]

true
Determine whether the semantic relation where cerebellar ataxia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where seborrheic keratosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11437it [38:43,  5.01it/s]

false
Determine whether the semantic relation where Q fever is the subject, medical examination is the predicate, and echocardiography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

11438it [38:43,  5.06it/s]

false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Canada is the object constitutes an accurate semantic relation.

11439it [38:43,  4.98it/s]

false
Determine whether the semantic relation where Canada is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11440it [38:43,  4.94it/s]

true
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

11441it [38:44,  4.63it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.

11442it [38:44,  4.60it/s]

true
Determine whether the semantic relation where tumor necrosis factor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11444it [38:44,  4.42it/s]

true
Determine whether the semantic relation where propyl alcohol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ribonuclease A family is the subject, subclass of is the predicate, and lyase is the object constitutes an accurate semantic relation.

11445it [38:45,  3.55it/s]

false
Determine whether the semantic relation where Luchelli is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11447it [38:45,  4.07it/s]

false
Determine whether the semantic relation where UDP-glucose 6-dehydrogenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paternity is the subject, subclass of is the predicate, and interpersonal relationship is the object constitutes an accurate semantic relation.

11449it [38:46,  4.58it/s]

true
Determine whether the semantic relation where ethology is the subject, different from is the predicate, and ethics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystic fibrosis is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

11451it [38:46,  4.75it/s]

false
Determine whether the semantic relation where allantoin is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and sotalol is the object constitutes an accurate semantic relation.

11453it [38:46,  5.01it/s]

true
Determine whether the semantic relation where congenital structural myopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sotalol is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

11455it [38:47,  5.23it/s]

true
Determine whether the semantic relation where meningococcal disease is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where amitriptyline is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

11457it [38:47,  5.30it/s]

false
Determine whether the semantic relation where MERRF syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Scutellaria baicalensis is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

11458it [38:47,  4.84it/s]

true
Determine whether the semantic relation where epichlorohydrin is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.

11460it [38:48,  4.84it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulfasalazine is the subject, subject has role is the predicate, and anti-infective agent is the object constitutes an accurate semantic relation.

11461it [38:48,  4.75it/s]

false
Determine whether the semantic relation where fibroma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11462it [38:48,  4.65it/s]

true
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

11464it [38:49,  4.80it/s]

true
Determine whether the semantic relation where TEK receptor tyrosine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

11466it [38:49,  4.93it/s]

true
Determine whether the semantic relation where World Health Organization is the subject, country is the predicate, and Denmark is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where protein is the subject, has part(s) is the predicate, and amino acid is the object constitutes an accurate semantic relation.

11468it [38:49,  4.88it/s]

true
Determine whether the semantic relation where melphalan is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, symptoms and signs is the predicate, and insomnia is the object constitutes an accurate semantic relation.

11470it [38:50,  5.00it/s]

true
Determine whether the semantic relation where mercury poisoning is the subject, has effect is the predicate, and insomnia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North America is the subject, country is the predicate, and Grenada is the object constitutes an accurate semantic relation.

11471it [38:50,  4.97it/s]

true
Determine whether the semantic relation where Grenada is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

11473it [38:50,  4.88it/s]

true
Determine whether the semantic relation where cellobiose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

11475it [38:51,  5.03it/s]

false
Determine whether the semantic relation where melioidosis is the subject, symptoms and signs is the predicate, and pleurisy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where speech disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

11477it [38:51,  4.98it/s]

false
Determine whether the semantic relation where speech disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sequence homology is the subject, facet of is the predicate, and genetics is the object constitutes an accurate semantic relation.

11478it [38:51,  4.87it/s]

false
Determine whether the semantic relation where autoimmune thyroiditis is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

11479it [38:52,  4.74it/s]

true
Determine whether the semantic relation where binge eating disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

11481it [38:52,  4.91it/s]

true
Determine whether the semantic relation where binge eating disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

11483it [38:52,  4.82it/s]

true
Determine whether the semantic relation where viral nucleocapsid is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where high-frequency hearing loss is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

11485it [38:53,  5.05it/s]

true
Determine whether the semantic relation where fistula is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coarctation of the aorta is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.

11487it [38:53,  5.15it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

11488it [38:53,  5.07it/s]

true
Determine whether the semantic relation where receptor interacting serine/threonine kinase 2 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

11489it [38:54,  4.87it/s]

false
Determine whether the semantic relation where betel is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.

11491it [38:54,  4.97it/s]

true
Determine whether the semantic relation where Melia azedarach is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where schizotypal personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11493it [38:55,  4.56it/s]

true
Determine whether the semantic relation where MCL1 apoptosis regulator, BCL2 family member is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arsenite is the subject, subclass of is the predicate, and salt is the object constitutes an accurate semantic relation.

11495it [38:55,  4.85it/s]

false
Determine whether the semantic relation where safrole is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF receptor superfamily member 1B is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11497it [38:55,  4.98it/s]

true
Determine whether the semantic relation where Bone morphogenetic protein 5 is the subject, cell component is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hereditary coproporphyria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11499it [38:56,  4.98it/s]

true
Determine whether the semantic relation where Portugal is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and prednisolone is the object constitutes an accurate semantic relation.

11500it [38:56,  4.80it/s]

true
Determine whether the semantic relation where Solute carrier family 5 member 1 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

11501it [38:56,  4.76it/s]

false
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11502it [38:56,  4.67it/s]

true
Determine whether the semantic relation where Cathepsin H is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11503it [38:57,  4.62it/s]

true
Determine whether the semantic relation where niacinamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11504it [38:57,  4.51it/s]

true
Determine whether the semantic relation where prednisolone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

11506it [38:57,  4.79it/s]

true
Determine whether the semantic relation where Japan is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neutral ceramidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11507it [38:57,  4.86it/s]

true
Determine whether the semantic relation where Algeria is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11509it [38:58,  4.86it/s]

true
Determine whether the semantic relation where vesicoureteral reflux is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiamine(1+) ion is the subject, different from is the predicate, and thymine is the object constitutes an accurate semantic relation.

11510it [38:58,  4.89it/s]

true
Determine whether the semantic relation where chromosomal fragile site is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11512it [38:59,  4.71it/s]

false
Determine whether the semantic relation where hyperparathyroidism is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Squalene epoxidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11513it [38:59,  4.82it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.

11515it [38:59,  4.73it/s]

true
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where orthoperiodic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11517it [39:00,  4.93it/s]

true
Determine whether the semantic relation where hypoglycemia is the subject, symptoms and signs is the predicate, and tremor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wilson disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11518it [39:00,  5.08it/s]

true
Determine whether the semantic relation where nephritis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

11519it [39:00,  4.99it/s]

true
Determine whether the semantic relation where acid–base imbalance is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

11521it [39:00,  5.11it/s]

false
Determine whether the semantic relation where acetylcarnitine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phospholipase A2 group VI is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11523it [39:01,  5.15it/s]

true
Determine whether the semantic relation where Japan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

11525it [39:01,  5.29it/s]

true
Determine whether the semantic relation where spondylitis is the subject, subclass of is the predicate, and neurological symptom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11526it [39:01,  4.96it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

11528it [39:02,  4.99it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Japan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where decompression sickness is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11530it [39:02,  5.03it/s]

true
Determine whether the semantic relation where Marburg virus disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DNA polymerase beta is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11531it [39:02,  5.06it/s]

true
Determine whether the semantic relation where Notch receptor 1 is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

11532it [39:03,  5.00it/s]

false
Determine whether the semantic relation where Belize is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11534it [39:03,  5.00it/s]

true
Determine whether the semantic relation where lice infestation is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11536it [39:03,  5.00it/s]

false
Determine whether the semantic relation where renin is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

11538it [39:04,  5.13it/s]

true
Determine whether the semantic relation where piperacillin is the subject, medical condition treated is the predicate, and skin infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.

11539it [39:04,  5.27it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

11541it [39:04,  4.58it/s]

true
Determine whether the semantic relation where shikimic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tick toxicosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11542it [39:05,  4.61it/s]

true
Determine whether the semantic relation where skin infection is the subject, drug or therapy used for treatment is the predicate, and piperacillin is the object constitutes an accurate semantic relation.

11543it [39:05,  4.51it/s]

true
Determine whether the semantic relation where facial nerve injuries is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11544it [39:05,  4.58it/s]

false
Determine whether the semantic relation where idarubicin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

11545it [39:05,  4.68it/s]

false
Determine whether the semantic relation where theophylline is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11547it [39:06,  4.60it/s]

false
Determine whether the semantic relation where anthrax is the subject, drug or therapy used for treatment is the predicate, and minocycline is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where minocycline is the subject, medical condition treated is the predicate, and anthrax is the object constitutes an accurate semantic relation.

11549it [39:06,  4.38it/s]

true
Determine whether the semantic relation where Bradykinin receptor B1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where emodin is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.

11551it [39:07,  4.63it/s]

false
Determine whether the semantic relation where methenamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Rhinella arenarum is the object constitutes an accurate semantic relation.

11553it [39:07,  4.78it/s]

false
Determine whether the semantic relation where book is the subject, has use is the predicate, and imagination is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Monaco is the object constitutes an accurate semantic relation.

11554it [39:07,  4.44it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.

11555it [39:08,  4.38it/s]

false
Determine whether the semantic relation where Monaco is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

11557it [39:08,  4.53it/s]

true
Determine whether the semantic relation where typhoid fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where multiple system atrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11558it [39:08,  4.68it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

11559it [39:08,  4.68it/s]

false
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and chlorpropamide is the object constitutes an accurate semantic relation.
true

11560it [39:09,  4.76it/s]

Determine whether the semantic relation where Coats disease is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

11561it [39:09,  4.63it/s]

true
Determine whether the semantic relation where A-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

11563it [39:09,  4.91it/s]

false
Determine whether the semantic relation where amikacin is the subject, subject has role is the predicate, and protein synthesis inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Early growth response 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11564it [39:09,  4.77it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11565it [39:10,  4.62it/s]

false
Determine whether the semantic relation where estrogen receptor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11566it [39:10,  4.51it/s]

true
Determine whether the semantic relation where ribonucleic acid is the subject, subclass of is the predicate, and biopolymer is the object constitutes an accurate semantic relation.

11567it [39:10,  4.52it/s]

true
Determine whether the semantic relation where nerve growth factor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11568it [39:10,  4.38it/s]

true
Determine whether the semantic relation where phosphopyruvate hydratase complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

11569it [39:11,  4.39it/s]

false
Determine whether the semantic relation where epinephrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11570it [39:11,  4.28it/s]

true
Determine whether the semantic relation where factor XII deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11571it [39:11,  4.25it/s]

true
Determine whether the semantic relation where SMAD family member 9 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11573it [39:11,  4.55it/s]

true
Determine whether the semantic relation where Germany is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chickenpox is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

11575it [39:12,  4.90it/s]

true
Determine whether the semantic relation where histidine decarboxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Beta-carotene oxygenase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11576it [39:12,  4.98it/s]

true
Determine whether the semantic relation where nitrous acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11578it [39:12,  4.89it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

11579it [39:13,  4.93it/s]

true
Determine whether the semantic relation where CNTFR-CLCF1 complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

11580it [39:13,  4.89it/s]

false
Determine whether the semantic relation where Paget's disease of bone is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11581it [39:13,  4.76it/s]

true
Determine whether the semantic relation where Prostaglandin E receptor 2 (subtype EP2) is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11583it [39:13,  4.83it/s]

true
Determine whether the semantic relation where glucagon is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11585it [39:14,  4.86it/s]

true
Determine whether the semantic relation where vitronectin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where computer is the subject, uses is the predicate, and electricity is the object constitutes an accurate semantic relation.

11586it [39:14,  5.05it/s]

true
Determine whether the semantic relation where pneumonia is the subject, risk factor is the predicate, and asthma is the object constitutes an accurate semantic relation.

11587it [39:14,  4.79it/s]

false
Determine whether the semantic relation where Janus kinase 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11588it [39:15,  4.68it/s]

true
Determine whether the semantic relation where orthostatic intolerance is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11590it [39:15,  4.80it/s]

false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

11592it [39:15,  5.00it/s]

true
Determine whether the semantic relation where adenosine triphosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false

11593it [39:16,  5.01it/s]

Determine whether the semantic relation where protein tyrosine phosphatase non-receptor type 6 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where autoimmune thyroiditis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11595it [39:16,  5.00it/s]

true
Determine whether the semantic relation where Fiji is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Fiji is the object constitutes an accurate semantic relation.

11596it [39:16,  4.87it/s]

true
Determine whether the semantic relation where tarsal tunnel syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11597it [39:16,  4.15it/s]

true
Determine whether the semantic relation where sigmoid disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

11598it [39:17,  4.28it/s]

true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and myocarditis is the object constitutes an accurate semantic relation.

11600it [39:17,  4.61it/s]

true
Determine whether the semantic relation where solute carrier family 6 member 3 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inguinal hernia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11602it [39:18,  4.78it/s]

true
Determine whether the semantic relation where fluorouracil is the subject, subject has role is the predicate, and immunosuppressive drug is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where naproxen is the subject, medical condition treated is the predicate, and fibromyalgia is the object constitutes an accurate semantic relation.

11603it [39:18,  4.04it/s]

false
Determine whether the semantic relation where leukotriene B4 is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true

11605it [39:18,  4.58it/s]

Determine whether the semantic relation where casein kinase 1 delta is the subject, biological process is the predicate, and endocytosis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where collodion is the subject, has part(s) is the predicate, and ethanol is the object constitutes an accurate semantic relation.

11606it [39:18,  4.81it/s]

true
Determine whether the semantic relation where coxa valga is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11607it [39:19,  4.58it/s]

true
Determine whether the semantic relation where inflammasome complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

11609it [39:19,  4.75it/s]

true
Determine whether the semantic relation where mediastinitis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where insulin like growth factor 1 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11610it [39:19,  4.90it/s]

true
Determine whether the semantic relation where trimethoprim is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

11612it [39:20,  4.80it/s]

true
Determine whether the semantic relation where Sodium voltage-gated channel beta subunit 1 is the subject, biological process is the predicate, and locomotion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hemorrhagic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11613it [39:20,  4.47it/s]

true
Determine whether the semantic relation where adult is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.

11614it [39:20,  4.55it/s]

true
Determine whether the semantic relation where lymphadenitis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

11616it [39:21,  4.71it/s]

false
Determine whether the semantic relation where blowout fracture is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coagulation factor V is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

11618it [39:21,  4.84it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Lebanon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11620it [39:22,  4.28it/s]

true
Determine whether the semantic relation where Lebanon is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where environmental disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11622it [39:22,  4.73it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucagon is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11624it [39:22,  4.88it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carcinoid syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11626it [39:23,  4.65it/s]

true
Determine whether the semantic relation where erethism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium aurothiosulfate is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.

11628it [39:23,  4.91it/s]

true
Determine whether the semantic relation where physiological phenomenon is the subject, studied by is the predicate, and physiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholecalciferol is the subject, medical condition treated is the predicate, and skin disease is the object constitutes an accurate semantic relation.

11629it [39:23,  4.85it/s]

maybe
Determine whether the semantic relation where skin disease is the subject, drug or therapy used for treatment is the predicate, and cholecalciferol is the object constitutes an accurate semantic relation.

11630it [39:24,  4.85it/s]

true
Determine whether the semantic relation where epidemic typhus is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

11632it [39:24,  4.95it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

11633it [39:24,  5.03it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 20 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11634it [39:24,  4.96it/s]

false
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and sotalol is the object constitutes an accurate semantic relation.

11636it [39:25,  4.99it/s]

true
Determine whether the semantic relation where alcoholic liver cirrhosis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where liver is the subject, studied by is the predicate, and anatomy is the object constitutes an accurate semantic relation.

11637it [39:25,  5.07it/s]

true
Determine whether the semantic relation where C-X-C motif chemokine ligand 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11639it [39:25,  4.72it/s]

true
Determine whether the semantic relation where crystallin alpha B is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where LDL receptor related protein 5 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

11640it [39:26,  4.70it/s]

true
Determine whether the semantic relation where Orientia tsutsugamushi is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.

11642it [39:26,  4.88it/s]

false
Determine whether the semantic relation where acrylamide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sotalol is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

11643it [39:26,  4.79it/s]

true
Determine whether the semantic relation where Dopamine receptor D3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11645it [39:27,  4.90it/s]

true
Determine whether the semantic relation where dependent personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphopenia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11647it [39:27,  4.90it/s]

true
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

11648it [39:27,  5.02it/s]

true
Determine whether the semantic relation where raffinose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11649it [39:27,  4.86it/s]

false
Determine whether the semantic relation where interstitial nephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11650it [39:28,  4.65it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

11651it [39:28,  4.52it/s]

true
Determine whether the semantic relation where phytanic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11653it [39:28,  4.78it/s]

false
Determine whether the semantic relation where alcoholism is the subject, afflicts is the predicate, and teenager is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spinacia oleracea is the subject, significant event is the predicate, and sequencing is the object constitutes an accurate semantic relation.

11655it [39:29,  5.07it/s]

false
Determine whether the semantic relation where coproporphyrinogen oxidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where esophageal atresia is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

11656it [39:29,  4.47it/s]

false
Determine whether the semantic relation where aza compounds is the subject, subclass of is the predicate, and nitrogen compound is the object constitutes an accurate semantic relation.

11658it [39:29,  4.77it/s]

true
Determine whether the semantic relation where South America is the subject, part of is the predicate, and Earth is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Dopamine receptor D4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11660it [39:30,  5.01it/s]

true
Determine whether the semantic relation where Q2839152 is the subject, facet of is the predicate, and patient is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where least squares method is the subject, instance of is the predicate, and scientific method is the object constitutes an accurate semantic relation.

11662it [39:30,  5.13it/s]

true
Determine whether the semantic relation where type 2 diabetes is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where internal carotid artery dissection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11664it [39:31,  5.08it/s]

true
Determine whether the semantic relation where administration is the subject, subclass of is the predicate, and humanities is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where MDMA is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

11665it [39:31,  4.93it/s]

true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

11666it [39:31,  4.09it/s]

false
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.

11667it [39:31,  4.30it/s]

true
Determine whether the semantic relation where Ritter's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11668it [39:32,  3.90it/s]

true
Determine whether the semantic relation where transforming growth factor alpha is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11670it [39:32,  4.32it/s]

true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where N-acetyl-L-cysteine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11671it [39:32,  4.56it/s]

true
Determine whether the semantic relation where BAK1 is the subject, expressed in is the predicate, and blood is the object constitutes an accurate semantic relation.

11672it [39:33,  4.49it/s]

false
Determine whether the semantic relation where lipoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11673it [39:33,  4.56it/s]

true
Determine whether the semantic relation where Aminomethyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11674it [39:33,  4.65it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

11675it [39:33,  4.03it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

11677it [39:34,  4.57it/s]

false
Determine whether the semantic relation where subclavian steal syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

11679it [39:34,  4.86it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and desonide is the object constitutes an accurate semantic relation.

11680it [39:34,  4.74it/s]

true
Determine whether the semantic relation where desonide is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

11682it [39:35,  4.86it/s]

true
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rhinosporidiosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11684it [39:35,  4.95it/s]

true
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Solute carrier family 29 member 1 (Augustine blood group) is the subject, biological process is the predicate, and sleep is the object constitutes an accurate semantic relation.

11685it [39:35,  4.74it/s]

false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

11687it [39:36,  4.86it/s]

true
Determine whether the semantic relation where gynecomastia is the subject, has cause is the predicate, and chronic renal insufficiency is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Guinea-Bissau is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

11689it [39:36,  4.87it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Guinea-Bissau is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Notch receptor 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11690it [39:36,  4.78it/s]

false
Determine whether the semantic relation where actinomycosis is the subject, anatomical location is the predicate, and respiratory system is the object constitutes an accurate semantic relation.

11691it [39:37,  4.78it/s]

true
Determine whether the semantic relation where selectin P is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11692it [39:37,  4.79it/s]

true
Determine whether the semantic relation where differential diagnosis is the subject, subclass of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

11693it [39:37,  4.70it/s]

true
Determine whether the semantic relation where fluoxetine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

11694it [39:37,  4.71it/s]

true
Determine whether the semantic relation where neurotoxic disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true

11696it [39:38,  5.00it/s]

Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

11698it [39:38,  5.20it/s]

true
Determine whether the semantic relation where cellular communication network factor 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where delirium tremens is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11699it [39:38,  5.13it/s]

true
Determine whether the semantic relation where D-glucosamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

11701it [39:39,  4.98it/s]

true
Determine whether the semantic relation where hemodynamics is the subject, subclass of is the predicate, and physiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quinolone antibiotic is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11703it [39:39,  5.19it/s]

true
Determine whether the semantic relation where Maryland is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Maryland is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

11705it [39:39,  5.31it/s]

true
Determine whether the semantic relation where progenism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 5-methyltetrahydrofolate-homocysteine S-methyltransferase, bacterial is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11707it [39:40,  5.37it/s]

true
Determine whether the semantic relation where cervicitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cervicitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11709it [39:40,  5.24it/s]

true
Determine whether the semantic relation where sea-blue histiocyte syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where exocrine pancreatic insufficiency is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

11710it [39:40,  5.16it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

11711it [39:40,  5.04it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

11713it [39:41,  4.85it/s]

true
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and hydrocephalus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CREST syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11715it [39:41,  5.14it/s]

true
Determine whether the semantic relation where paroxysmal tachycardia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebral venous sinus thrombosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11716it [39:41,  5.20it/s]

true
Determine whether the semantic relation where hemoglobinopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11718it [39:42,  5.01it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

11720it [39:42,  5.09it/s]

true
Determine whether the semantic relation where acidophil adenoma is the subject, subclass of is the predicate, and leukocyte disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hydroxocobalamin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11721it [39:42,  4.87it/s]

true
Determine whether the semantic relation where carbon dioxide is the subject, subject has role is the predicate, and vasodilator agent is the object constitutes an accurate semantic relation.

11722it [39:43,  4.46it/s]

true
Determine whether the semantic relation where cerebral arterial disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11723it [39:43,  4.33it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 4 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11725it [39:43,  4.60it/s]

true
Determine whether the semantic relation where capillary leak syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MDMA is the subject, route of administration is the predicate, and Q10268830 is the object constitutes an accurate semantic relation.

11727it [39:44,  4.71it/s]

false
Determine whether the semantic relation where pyridoxine is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Spain is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11728it [39:44,  4.82it/s]

true
Determine whether the semantic relation where pain is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

11730it [39:44,  4.94it/s]

false
Determine whether the semantic relation where C-C motif chemokine receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mushroom poisoning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

11732it [39:45,  4.82it/s]

false
Determine whether the semantic relation where cyclin dependent kinase inhibitor 2A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where postpartum depression is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

11734it [39:45,  4.78it/s]

true
Determine whether the semantic relation where encephalopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11736it [39:46,  5.07it/s]

true
Determine whether the semantic relation where Equatorial Guinea is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MPL proto-oncogene, thrombopoietin receptor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11738it [39:46,  5.11it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where temporal lobe epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11740it [39:46,  5.13it/s]

true
Determine whether the semantic relation where human serum albumin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

11742it [39:47,  5.18it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Equatorial Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD2 molecule is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

11743it [39:47,  5.09it/s]

false
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

11744it [39:47,  5.04it/s]

true
Determine whether the semantic relation where brain infarction is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11745it [39:47,  4.76it/s]

true
Determine whether the semantic relation where keratin 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11747it [39:48,  4.86it/s]

true
Determine whether the semantic relation where hypoxanthine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bites and stings is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

11748it [39:48,  4.98it/s]

true
Determine whether the semantic relation where courtship is the subject, subclass of is the predicate, and role is the object constitutes an accurate semantic relation.

11749it [39:48,  4.80it/s]

false
Determine whether the semantic relation where NSF is the subject, instance of is the predicate, and gene is the object constitutes an accurate semantic relation.

11750it [39:49,  4.72it/s]

false
Determine whether the semantic relation where methenamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

11751it [39:49,  4.69it/s]

true
Determine whether the semantic relation where feasibility study is the subject, facet of is the predicate, and risk management is the object constitutes an accurate semantic relation.

11752it [39:49,  4.59it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and piroxicam is the object constitutes an accurate semantic relation.

11754it [39:49,  4.82it/s]

true
Determine whether the semantic relation where piroxicam is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Forkhead box A2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11756it [39:50,  4.89it/s]

false
Determine whether the semantic relation where L-threonine is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false

11757it [39:50,  4.98it/s]

Determine whether the semantic relation where pyridoxine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oncostatin M receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11758it [39:50,  5.14it/s]

true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.

11759it [39:50,  4.97it/s]

false
Determine whether the semantic relation where pityriasis rubra pilaris is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11760it [39:51,  4.82it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

11761it [39:51,  4.65it/s]

true
Determine whether the semantic relation where Goodpasture syndrome is the subject, health specialty is the predicate, and nephrology is the object constitutes an accurate semantic relation.

11762it [39:51,  4.72it/s]

true
Determine whether the semantic relation where LDL receptor related protein 2 is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

11763it [39:51,  4.52it/s]

false
Determine whether the semantic relation where cortisol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11765it [39:52,  4.60it/s]

false
Determine whether the semantic relation where biotin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HIV/AIDS is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

11767it [39:52,  4.74it/s]

true
Determine whether the semantic relation where asphyxia neonatorum is the subject, has cause is the predicate, and congenital heart disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where penicillin G procaine hydrate is the subject, has part(s) is the predicate, and water is the object constitutes an accurate semantic relation.

11769it [39:53,  4.82it/s]

true
Determine whether the semantic relation where Secretory leukocyte peptidase inhibitor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital heart disease is the subject, has effect is the predicate, and asphyxia neonatorum is the object constitutes an accurate semantic relation.

11771it [39:53,  5.07it/s]

maybe
Determine whether the semantic relation where medroxyprogesterone acetate is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where headache is the subject, drug or therapy used for treatment is the predicate, and sodium benzoate is the object constitutes an accurate semantic relation.

11772it [39:53,  4.96it/s]

false
Determine whether the semantic relation where dengue fever is the subject, possible treatment is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.
false

11774it [39:53,  4.95it/s]

Determine whether the semantic relation where Israel is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium benzoate is the subject, medical condition treated is the predicate, and headache is the object constitutes an accurate semantic relation.

11776it [39:54,  4.98it/s]

false
Determine whether the semantic relation where police is the subject, instance of is the predicate, and government agency is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

11777it [39:54,  4.99it/s]

true
Determine whether the semantic relation where vidarabine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

11779it [39:55,  4.83it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

11781it [39:55,  5.06it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, possible treatment is the predicate, and massage is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

11783it [39:55,  5.28it/s]

true
Determine whether the semantic relation where nicotinic acid is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

11785it [39:56,  5.38it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rac family small GTPase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11786it [39:56,  5.31it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

11788it [39:56,  5.20it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aged is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.

11790it [39:57,  5.38it/s]

false
Determine whether the semantic relation where child is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where health care quality is the subject, facet of is the predicate, and health care is the object constitutes an accurate semantic relation.

11792it [39:57,  5.17it/s]

false
Determine whether the semantic relation where health care is the subject, has characteristic is the predicate, and health care quality is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and abortion is the object constitutes an accurate semantic relation.

11794it [39:57,  5.24it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypoalphalipoproteinemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11796it [39:58,  5.26it/s]

true
Determine whether the semantic relation where cortisol is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

11798it [39:58,  5.30it/s]

true
Determine whether the semantic relation where theobromine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where NLR family apoptosis inhibitory protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11800it [39:59,  5.34it/s]

true
Determine whether the semantic relation where tracheomalacia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

11802it [39:59,  5.16it/s]

false
Determine whether the semantic relation where Thymine DNA glycosylase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit beta 2 is the subject, cell component is the predicate, and focal adhesion is the object constitutes an accurate semantic relation.

11804it [39:59,  5.01it/s]

true
Determine whether the semantic relation where lactase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11805it [40:00,  4.65it/s]

false
Determine whether the semantic relation where cerebral edema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11807it [40:00,  4.84it/s]

true
Determine whether the semantic relation where cerebral edema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where linoleic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

11808it [40:00,  4.68it/s]

false
Determine whether the semantic relation where α-D-xylopyranose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11810it [40:01,  4.79it/s]

true
Determine whether the semantic relation where Sporotrichosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Horner's syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11812it [40:01,  5.03it/s]

true
Determine whether the semantic relation where deletion mutation is the subject, studied by is the predicate, and genetics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where progressive multifocal leukoencephalopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11814it [40:01,  5.13it/s]

true
Determine whether the semantic relation where thiamine deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, symptoms and signs is the predicate, and cyanosis is the object constitutes an accurate semantic relation.

11815it [40:02,  4.76it/s]

false
Determine whether the semantic relation where health informatics is the subject, facet of is the predicate, and health care is the object constitutes an accurate semantic relation.

11816it [40:02,  4.71it/s]

false
Determine whether the semantic relation where phaeohyphomycosis is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

11818it [40:02,  4.85it/s]

false
Determine whether the semantic relation where intermittent claudication is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

11819it [40:02,  4.76it/s]

true
Determine whether the semantic relation where United States is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

11821it [40:03,  4.84it/s]

true
Determine whether the semantic relation where encephalitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where encephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11823it [40:03,  4.93it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tajikistan is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

11824it [40:03,  5.05it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Tajikistan is the object constitutes an accurate semantic relation.

11825it [40:04,  4.95it/s]

true
Determine whether the semantic relation where aortitis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

11826it [40:04,  4.91it/s]

maybe
Determine whether the semantic relation where platelet-derived growth factor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

11827it [40:04,  4.87it/s]

false
Determine whether the semantic relation where chitosan is the subject, subject has role is the predicate, and anticholesteremic agents is the object constitutes an accurate semantic relation.

11829it [40:05,  4.96it/s]

true
Determine whether the semantic relation where Angelman syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (S)-(−)-colchicine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

11831it [40:05,  5.15it/s]

false
Determine whether the semantic relation where acute liver failure is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pervasive developmental disorder is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.

11832it [40:05,  4.50it/s]

true
Determine whether the semantic relation where (±)-promethazine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

11833it [40:05,  4.61it/s]

false
Determine whether the semantic relation where Pyroglutamyl-peptidase I is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11834it [40:06,  4.41it/s]

false
Determine whether the semantic relation where pyridoxine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

11835it [40:06,  3.91it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and (±)-promethazine is the object constitutes an accurate semantic relation.

11837it [40:06,  4.28it/s]

false
Determine whether the semantic relation where thymol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where streptococcal infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11839it [40:07,  4.63it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dihydroxyacetone is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

11841it [40:07,  4.91it/s]

false
Determine whether the semantic relation where hypersensitivity is the subject, drug or therapy used for treatment is the predicate, and dexamethasone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where N-bromosuccinimide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

11843it [40:08,  5.06it/s]

true
Determine whether the semantic relation where dexamethasone is the subject, medical condition treated is the predicate, and hypersensitivity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where obsessive-compulsive personality disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11844it [40:08,  4.99it/s]

true
Determine whether the semantic relation where dementia is the subject, drug or therapy used for treatment is the predicate, and perphenazine is the object constitutes an accurate semantic relation.
false

11846it [40:08,  5.00it/s]

Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Azerbaijan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Azerbaijan is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

11847it [40:08,  4.89it/s]

true
Determine whether the semantic relation where perphenazine is the subject, medical condition treated is the predicate, and dementia is the object constitutes an accurate semantic relation.

11849it [40:09,  4.97it/s]

false
Determine whether the semantic relation where alfadex is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dysarthria is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11851it [40:09,  4.96it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

11852it [40:09,  5.12it/s]

true
Determine whether the semantic relation where myopia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11853it [40:10,  4.93it/s]

true
Determine whether the semantic relation where Reye syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11854it [40:10,  4.87it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

11856it [40:10,  4.80it/s]

true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amblyopia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11858it [40:11,  4.86it/s]

true
Determine whether the semantic relation where amblyopia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where movement disorders is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11859it [40:11,  5.00it/s]

true
Determine whether the semantic relation where 1918–1920 flu pandemic is the subject, country of origin is the predicate, and France is the object constitutes an accurate semantic relation.

11860it [40:11,  4.62it/s]

false
Determine whether the semantic relation where focal epithelial hyperplasia is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

11861it [40:11,  4.70it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Uganda is the object constitutes an accurate semantic relation.

11862it [40:11,  4.74it/s]

true
Determine whether the semantic relation where Uganda is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true

11864it [40:12,  4.89it/s]

Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

11866it [40:12,  4.99it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ovarian hyperstimulation syndrome is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

11867it [40:13,  4.86it/s]

true
Determine whether the semantic relation where plus-end-directed kinesin ATPase is the subject, subclass of is the predicate, and isomerase is the object constitutes an accurate semantic relation.

11868it [40:13,  4.67it/s]

false
Determine whether the semantic relation where gonorrhea is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

11869it [40:13,  4.70it/s]

false
Determine whether the semantic relation where skin neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11870it [40:13,  4.75it/s]

true
Determine whether the semantic relation where neutrophil elastase is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

11871it [40:13,  4.50it/s]

false
Determine whether the semantic relation where C-X-C motif chemokine ligand 9 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11873it [40:14,  4.63it/s]

true
Determine whether the semantic relation where High mobility group box 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

11874it [40:14,  4.56it/s]

false
Determine whether the semantic relation where tooth demineralization is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

11875it [40:14,  4.63it/s]

false
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

11877it [40:15,  4.90it/s]

false
Determine whether the semantic relation where thymus neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pasteurellosis is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

11879it [40:15,  4.60it/s]

true
Determine whether the semantic relation where zeaxanthin is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where FOS is the subject, expressed in is the predicate, and monocyte is the object constitutes an accurate semantic relation.

11880it [40:15,  4.69it/s]

false
Determine whether the semantic relation where Complement C6 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11881it [40:16,  4.75it/s]

true
Determine whether the semantic relation where facioscapulohumeral muscular dystrophy is the subject, symptoms and signs is the predicate, and blindness is the object constitutes an accurate semantic relation.

11882it [40:16,  4.51it/s]

false
Determine whether the semantic relation where carpal tunnel syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11883it [40:16,  4.54it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Australia is the object constitutes an accurate semantic relation.

11885it [40:17,  4.22it/s]

false
Determine whether the semantic relation where genetic phenomena is the subject, subclass of is the predicate, and biological phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yersiniosis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

11886it [40:17,  4.32it/s]

true
Determine whether the semantic relation where hypertensive intracranial hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11887it [40:17,  4.37it/s]

true
Determine whether the semantic relation where Australia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

11889it [40:17,  4.66it/s]

true
Determine whether the semantic relation where CD1d molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mitochondrial encephalomyopathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

11891it [40:18,  4.90it/s]

true
Determine whether the semantic relation where CD33 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where community health center is the subject, country is the predicate, and Belgium is the object constitutes an accurate semantic relation.

11892it [40:18,  4.94it/s]

maybe
Determine whether the semantic relation where caffeine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11893it [40:18,  4.75it/s]

false
Determine whether the semantic relation where Cathepsin H is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11894it [40:18,  4.75it/s]

false
Determine whether the semantic relation where kidney is the subject, part of is the predicate, and endocrine system is the object constitutes an accurate semantic relation.

11896it [40:19,  4.81it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

11897it [40:19,  4.74it/s]

false
Determine whether the semantic relation where Wnt family member 3A is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

11898it [40:19,  4.63it/s]

true
Determine whether the semantic relation where dextrin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

11900it [40:20,  4.80it/s]

false
Determine whether the semantic relation where xanthine oxidase is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where membranoproliferative glomerulonephritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11902it [40:20,  5.09it/s]

true
Determine whether the semantic relation where integrin subunit alpha M is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Wechsler Adult Intelligence Scale is the subject, intended public is the predicate, and adult is the object constitutes an accurate semantic relation.

11903it [40:20,  5.13it/s]

true
Determine whether the semantic relation where cleidocranial dysplasia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11904it [40:20,  5.07it/s]

true
Determine whether the semantic relation where dibutyl phthalate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11906it [40:21,  5.08it/s]

true
Determine whether the semantic relation where postural orthostatic tachycardia syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichostrongyloidosis is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.

11908it [40:21,  5.09it/s]

true
Determine whether the semantic relation where functional colonic disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

11909it [40:21,  5.09it/s]

true
Determine whether the semantic relation where carbachol is the subject, subject has role is the predicate, and non-opioid analgesic is the object constitutes an accurate semantic relation.

11910it [40:22,  5.03it/s]

false
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

11911it [40:22,  4.92it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

11912it [40:22,  4.75it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

11913it [40:22,  4.66it/s]

true
Determine whether the semantic relation where Chagas cardiomyopathy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

11914it [40:23,  4.50it/s]

true
Determine whether the semantic relation where transcription factor 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

11916it [40:23,  4.68it/s]

true
Determine whether the semantic relation where cardiac tamponade is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glycogen is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

11917it [40:23,  4.78it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

11918it [40:23,  4.78it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

11920it [40:24,  5.01it/s]

true
Determine whether the semantic relation where complement factor D is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

11922it [40:24,  5.18it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3'-phosphoadenosine 5'-phosphosulfate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11923it [40:24,  5.35it/s]

true
Determine whether the semantic relation where transmissible spongiform encephalopathy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11925it [40:25,  5.23it/s]

true
Determine whether the semantic relation where dilated cardiomyopathy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Heat shock protein family B (small) member 1 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

11927it [40:25,  5.10it/s]

false
Determine whether the semantic relation where congenital myasthenic syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where procarbazine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

11929it [40:25,  5.15it/s]

true
Determine whether the semantic relation where pertussis is the subject, symptoms and signs is the predicate, and apnea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.

11930it [40:26,  5.10it/s]

false
Determine whether the semantic relation where Langerhans cell is the subject, different from is the predicate, and islet of Langerhans is the object constitutes an accurate semantic relation.

11931it [40:26,  5.04it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

11933it [40:26,  4.98it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Integrin subunit alpha L is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

11934it [40:27,  4.94it/s]

false
Determine whether the semantic relation where peer review is the subject, has use is the predicate, and engineering is the object constitutes an accurate semantic relation.

11936it [40:27,  4.95it/s]

true
Determine whether the semantic relation where islet of Langerhans is the subject, different from is the predicate, and Langerhans cell is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.

11938it [40:27,  5.13it/s]

true
Determine whether the semantic relation where tyrosine kinase 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.

11939it [40:27,  5.07it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

11940it [40:28,  4.97it/s]

true
Determine whether the semantic relation where silicon dioxide is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

11941it [40:28,  4.74it/s]

true
Determine whether the semantic relation where parotitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11942it [40:28,  4.72it/s]

true
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

11943it [40:28,  4.70it/s]

true
Determine whether the semantic relation where glaucoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11945it [40:29,  4.93it/s]

true
Determine whether the semantic relation where aminolevulinic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gout is the subject, has contributing factor is the predicate, and diet is the object constitutes an accurate semantic relation.

11947it [40:29,  4.98it/s]

true
Determine whether the semantic relation where meningoencephalitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Furin, paired basic amino acid cleaving enzyme is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

11949it [40:30,  4.91it/s]

false
Determine whether the semantic relation where allantoin is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false

11950it [40:30,  5.00it/s]

Determine whether the semantic relation where Felty's syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulfobromophthalein is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

11951it [40:30,  4.85it/s]

true
Determine whether the semantic relation where gastric inhibitory polypeptide is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

11952it [40:30,  4.75it/s]

false
Determine whether the semantic relation where mumps is the subject, anatomical location is the predicate, and gonad is the object constitutes an accurate semantic relation.

11953it [40:30,  4.74it/s]

false
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

11954it [40:31,  4.74it/s]

true
Determine whether the semantic relation where Inositol-3-phosphate synthase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

11955it [40:31,  4.69it/s]

true
Determine whether the semantic relation where Inositol-3-phosphate synthase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

11956it [40:31,  4.76it/s]

true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

11957it [40:31,  4.65it/s]

true
Determine whether the semantic relation where Laron syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

11958it [40:31,  4.73it/s]

true
Determine whether the semantic relation where phenylethyl alcohol is the subject, subject has role is the predicate, and disinfectant is the object constitutes an accurate semantic relation.

11959it [40:32,  4.59it/s]

true
Determine whether the semantic relation where nutritional deficiency disease is the subject, drug or therapy used for treatment is the predicate, and manganese is the object constitutes an accurate semantic relation.

11960it [40:32,  4.57it/s]

false
Determine whether the semantic relation where Mallory–Weiss syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11962it [40:32,  4.81it/s]

true
Determine whether the semantic relation where manganese is the subject, medical condition treated is the predicate, and nutritional deficiency disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

11963it [40:33,  4.19it/s]

true
Determine whether the semantic relation where KIT ligand is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11965it [40:33,  4.57it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.

11966it [40:33,  4.66it/s]

true
Determine whether the semantic relation where inosine pranobex is the subject, instance of is the predicate, and combination drug is the object constitutes an accurate semantic relation.

11967it [40:33,  4.62it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

11969it [40:34,  4.58it/s]

true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where marker of proliferation Ki-67 is the subject, cell component is the predicate, and chromosome is the object constitutes an accurate semantic relation.

11970it [40:34,  4.75it/s]

false
Determine whether the semantic relation where tretinoin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

11972it [40:35,  4.97it/s]

true
Determine whether the semantic relation where Republic of the Congo is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Republic of the Congo is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

11973it [40:35,  4.94it/s]

true
Determine whether the semantic relation where α-amanitin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11975it [40:35,  4.96it/s]

true
Determine whether the semantic relation where cyclodextrin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Keratin 14 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

11976it [40:35,  4.98it/s]

true
Determine whether the semantic relation where Growth differentiation factor 15 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

11978it [40:36,  4.79it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bulbar polio is the subject, anatomical location is the predicate, and brain stem is the object constitutes an accurate semantic relation.

11980it [40:36,  4.76it/s]

true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salicylic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11982it [40:37,  4.94it/s]

true
Determine whether the semantic relation where Phosphofructokinase, muscle is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nuclear receptor subfamily 1 group D member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11983it [40:37,  5.09it/s]

true
Determine whether the semantic relation where psychotherapy is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.

11984it [40:37,  5.01it/s]

true
Determine whether the semantic relation where psychotherapy is the subject, part of is the predicate, and therapy is the object constitutes an accurate semantic relation.

11985it [40:37,  4.70it/s]

true
Determine whether the semantic relation where choreatic disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11986it [40:37,  4.75it/s]

true
Determine whether the semantic relation where beta thalassemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

11987it [40:38,  4.74it/s]

true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, drug or therapy used for treatment is the predicate, and amoxicillin is the object constitutes an accurate semantic relation.

11988it [40:38,  4.75it/s]

true
Determine whether the semantic relation where nutrition disorder is the subject, drug or therapy used for treatment is the predicate, and linoleic acid is the object constitutes an accurate semantic relation.

11990it [40:38,  4.92it/s]

false
Determine whether the semantic relation where laryngostenosis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and lymphatic system is the object constitutes an accurate semantic relation.

11991it [40:38,  5.00it/s]

false
Determine whether the semantic relation where hypervitaminosis A is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

11992it [40:39,  4.69it/s]

true
Determine whether the semantic relation where hypervitaminosis A is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

11993it [40:39,  4.44it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

11995it [40:39,  4.70it/s]

false
Determine whether the semantic relation where Colorado tick fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arbutin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

11997it [40:40,  4.63it/s]

false
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Cucumis sativus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium sensing receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

11998it [40:40,  4.68it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

11999it [40:40,  4.73it/s]

true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.

12000it [40:40,  4.61it/s]

true
Determine whether the semantic relation where neuromuscular manifestations is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12001it [40:41,  3.99it/s]

true
Determine whether the semantic relation where secondary headache disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12003it [40:41,  4.34it/s]

true
Determine whether the semantic relation where osteophyte is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

12005it [40:42,  4.80it/s]

true
Determine whether the semantic relation where erythromycin ethylsuccinate is the subject, subject has role is the predicate, and gastrointestinal agent is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.

12006it [40:42,  4.63it/s]

true
Determine whether the semantic relation where Algeria is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

12008it [40:42,  4.84it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

12009it [40:42,  4.87it/s]

true
Determine whether the semantic relation where multiple endocrine neoplasia type 1 is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12010it [40:43,  4.57it/s]

true
Determine whether the semantic relation where nephroblastoma is the subject, genetic association is the predicate, and BRCA2 is the object constitutes an accurate semantic relation.

12011it [40:43,  4.61it/s]

false
Determine whether the semantic relation where cystinuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12013it [40:43,  4.74it/s]

true
Determine whether the semantic relation where intercellular adhesion molecule 1 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and anuria is the object constitutes an accurate semantic relation.

12015it [40:44,  4.92it/s]

true
Determine whether the semantic relation where L-serine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Georgia is the object constitutes an accurate semantic relation.

12017it [40:44,  4.92it/s]

false
Determine whether the semantic relation where Togo is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where small for gestational age is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

12019it [40:44,  5.10it/s]

false
Determine whether the semantic relation where 4-amino-5-imidazole carboxamide is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myotonic disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12020it [40:45,  5.01it/s]

true
Determine whether the semantic relation where Fox-Fordyce disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12021it [40:45,  4.96it/s]

true
Determine whether the semantic relation where urea cycle disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

12022it [40:45,  4.72it/s]

false
Determine whether the semantic relation where L-selenocysteine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

12024it [40:46,  4.78it/s]

true
Determine whether the semantic relation where intercellular adhesion molecule 1 is the subject, cell component is the predicate, and focal adhesion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where endemic typhus is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

12026it [40:46,  4.87it/s]

true
Determine whether the semantic relation where myelitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oleic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12027it [40:46,  5.04it/s]

false
Determine whether the semantic relation where 17β-estradiol is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

12028it [40:46,  4.96it/s]

true
Determine whether the semantic relation where ancylostomiasis is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

12030it [40:47,  4.98it/s]

true
Determine whether the semantic relation where Endo-1,3(4)-beta-glucanase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tannin is the subject, has use is the predicate, and ink is the object constitutes an accurate semantic relation.

12032it [40:47,  4.89it/s]

true
Determine whether the semantic relation where panic disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium carbonate is the subject, medical condition treated is the predicate, and gastric ulcer is the object constitutes an accurate semantic relation.

12034it [40:48,  4.73it/s]

true
Determine whether the semantic relation where gastric ulcer is the subject, drug or therapy used for treatment is the predicate, and calcium carbonate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipid metabolism disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12036it [40:48,  4.99it/s]

true
Determine whether the semantic relation where lipid metabolism disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and glycine is the object constitutes an accurate semantic relation.

12038it [40:48,  5.10it/s]

false
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and indomethacin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where linoleic acid is the subject, medical condition treated is the predicate, and nutrition disorder is the object constitutes an accurate semantic relation.

12040it [40:49,  5.11it/s]

false
Determine whether the semantic relation where CD70 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ocular hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12041it [40:49,  5.10it/s]

true
Determine whether the semantic relation where anisomycin is the subject, subject has role is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

12043it [40:49,  4.97it/s]

false
Determine whether the semantic relation where diverticulum is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 2,4-dinitrochlorobenzene is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

12044it [40:50,  5.04it/s]

true
Determine whether the semantic relation where congenital syphilis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12045it [40:50,  4.75it/s]

true
Determine whether the semantic relation where frostbite is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12047it [40:50,  4.70it/s]

true
Determine whether the semantic relation where phytol is the subject, found in taxon is the predicate, and basil is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dopamine is the subject, contributing factor of is the predicate, and decision making is the object constitutes an accurate semantic relation.

12049it [40:51,  4.87it/s]

true
Determine whether the semantic relation where amylose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nuclear receptor subfamily 4 group A member 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

12051it [40:51,  5.23it/s]

false
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chicago is the subject, twinned administrative body is the predicate, and Paris is the object constitutes an accurate semantic relation.

12053it [40:51,  5.17it/s]

true
Determine whether the semantic relation where Lysyl oxidase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Trinidad and Tobago is the object constitutes an accurate semantic relation.

12054it [40:52,  5.22it/s]

true
Determine whether the semantic relation where Trinidad and Tobago is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

12056it [40:52,  5.17it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethacrynic acid is the subject, medical condition treated is the predicate, and liver disease is the object constitutes an accurate semantic relation.

12057it [40:52,  4.95it/s]

false
Determine whether the semantic relation where liver disease is the subject, drug or therapy used for treatment is the predicate, and ethacrynic acid is the object constitutes an accurate semantic relation.

12059it [40:53,  4.87it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin K is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12061it [40:53,  4.98it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where conjunctivitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12063it [40:53,  5.01it/s]

true
Determine whether the semantic relation where polymyositis is the subject, medical examination is the predicate, and Q73401885 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where primate disease is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

12065it [40:54,  5.03it/s]

false
Determine whether the semantic relation where sirolimus is the subject, route of administration is the predicate, and intraperitoneal injection is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pyruvic acid is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

12066it [40:54,  4.90it/s]

false
Determine whether the semantic relation where mitral valve stenosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12067it [40:54,  4.71it/s]

true
Determine whether the semantic relation where dactinomycin is the subject, subject has role is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

12069it [40:55,  4.81it/s]

true
Determine whether the semantic relation where Czechoslovakia is the subject, official religion is the predicate, and Catholicism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fragile X syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12070it [40:55,  3.94it/s]

true
Determine whether the semantic relation where peritoneal panniculitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12071it [40:55,  4.14it/s]

true
Determine whether the semantic relation where otitis media is the subject, drug or therapy used for treatment is the predicate, and antipyrine is the object constitutes an accurate semantic relation.

12072it [40:55,  4.27it/s]

true
Determine whether the semantic relation where antipyrine is the subject, medical condition treated is the predicate, and otitis media is the object constitutes an accurate semantic relation.

12073it [40:56,  4.43it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, B is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12075it [40:56,  4.59it/s]

true
Determine whether the semantic relation where carotid artery stenosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where laryngospasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12076it [40:56,  4.78it/s]

true
Determine whether the semantic relation where sirtuin 1 is the subject, biological process is the predicate, and DNA replication is the object constitutes an accurate semantic relation.

12078it [40:57,  4.98it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Carthamus tinctorius is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hepatitis A is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

12079it [40:57,  5.04it/s]

false
Determine whether the semantic relation where boxing is the subject, country of origin is the predicate, and England is the object constitutes an accurate semantic relation.

12081it [40:57,  5.01it/s]

true
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and astemizole is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Opioid receptor delta 1 is the subject, physically interacts with is the predicate, and pethidine is the object constitutes an accurate semantic relation.

12082it [40:57,  5.10it/s]

true
Determine whether the semantic relation where glaucoma is the subject, drug or therapy used for treatment is the predicate, and carbachol is the object constitutes an accurate semantic relation.

12083it [40:58,  4.78it/s]

false
Determine whether the semantic relation where pethidine is the subject, physically interacts with is the predicate, and Opioid receptor delta 1 is the object constitutes an accurate semantic relation.

12085it [40:58,  4.93it/s]

false
Determine whether the semantic relation where astemizole is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where crowdsourcing is the subject, subclass of is the predicate, and human resource management is the object constitutes an accurate semantic relation.

12086it [40:58,  4.94it/s]

false
Determine whether the semantic relation where cell is the subject, part of is the predicate, and tissue is the object constitutes an accurate semantic relation.

12087it [40:58,  4.87it/s]

true
Determine whether the semantic relation where carbachol is the subject, medical condition treated is the predicate, and glaucoma is the object constitutes an accurate semantic relation.

12089it [40:59,  5.00it/s]

true
Determine whether the semantic relation where Cyclin B1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where labor induction is the subject, has contributing factor is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

12091it [40:59,  5.13it/s]

false
Determine whether the semantic relation where nausea is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where motor skill is the subject, uses is the predicate, and muscle is the object constitutes an accurate semantic relation.

12092it [40:59,  5.04it/s]

false
Determine whether the semantic relation where pantothenic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

12094it [41:00,  5.00it/s]

false
Determine whether the semantic relation where complement C1s is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erythro-5-hydroxy-L-lysine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12096it [41:00,  5.07it/s]

true
Determine whether the semantic relation where angiotensin II receptor type 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Solute carrier family 12 member 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12097it [41:01,  3.89it/s]

false
Determine whether the semantic relation where spinal cord disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12098it [41:01,  4.12it/s]

true
Determine whether the semantic relation where tonsillitis is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

12099it [41:01,  4.29it/s]

true
Determine whether the semantic relation where hydroxysteroid 11-beta dehydrogenase 2 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12101it [41:01,  4.67it/s]

true
Determine whether the semantic relation where nitrogen is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and tonsillitis is the object constitutes an accurate semantic relation.

12103it [41:02,  4.79it/s]

true
Determine whether the semantic relation where prostaglandin E2 is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chondropathy is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

12104it [41:02,  4.69it/s]

true
Determine whether the semantic relation where periodontal disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12105it [41:02,  4.72it/s]

true
Determine whether the semantic relation where infection of the central nervous system is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12107it [41:03,  4.98it/s]

true
Determine whether the semantic relation where intellectual disability is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

12109it [41:03,  5.14it/s]

true
Determine whether the semantic relation where American Public Health Association is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where microtubule associated protein tau is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

12111it [41:03,  5.10it/s]

false
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and arachnoiditis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

12113it [41:04,  5.22it/s]

true
Determine whether the semantic relation where selenic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningococcal vaccine is the subject, route of administration is the predicate, and subcutaneous injection is the object constitutes an accurate semantic relation.

12114it [41:04,  5.26it/s]

false
Determine whether the semantic relation where phytol is the subject, found in taxon is the predicate, and Lactuca sativa is the object constitutes an accurate semantic relation.

12116it [41:04,  4.97it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inosine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12117it [41:05,  5.03it/s]

false
Determine whether the semantic relation where asparaginase is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12118it [41:05,  4.76it/s]

false
Determine whether the semantic relation where nasopharyngeal disease is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

12119it [41:05,  4.75it/s]

true
Determine whether the semantic relation where E2F transcription factor 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12121it [41:06,  4.61it/s]

false
Determine whether the semantic relation where lutein is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New York is the subject, shares border with is the predicate, and Ontario is the object constitutes an accurate semantic relation.

12122it [41:06,  4.74it/s]

true
Determine whether the semantic relation where Neurofibromin 1 is the subject, biological process is the predicate, and cell communication is the object constitutes an accurate semantic relation.

12123it [41:06,  4.35it/s]

true
Determine whether the semantic relation where Ontario is the subject, shares border with is the predicate, and New York is the object constitutes an accurate semantic relation.

12125it [41:06,  4.59it/s]

true
Determine whether the semantic relation where Keratin 8 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Australia is the subject, located in or next to body of water is the predicate, and Indian Ocean is the object constitutes an accurate semantic relation.

12126it [41:07,  4.80it/s]

true
Determine whether the semantic relation where sarcocystosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

12128it [41:07,  4.75it/s]

true
Determine whether the semantic relation where yersiniosis is the subject, has natural reservoir is the predicate, and Rodent is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Liberia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

12130it [41:07,  5.00it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Liberia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic lymphocytic leukemia is the subject, drug or therapy used for treatment is the predicate, and dexamethasone is the object constitutes an accurate semantic relation.

12131it [41:08,  5.04it/s]

maybe
Determine whether the semantic relation where Von Hippel-Lindau tumor suppressor is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12132it [41:08,  5.00it/s]

false
Determine whether the semantic relation where dexamethasone is the subject, medical condition treated is the predicate, and chronic lymphocytic leukemia is the object constitutes an accurate semantic relation.

12133it [41:08,  4.97it/s]

true
Determine whether the semantic relation where amylopectin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12135it [41:09,  4.72it/s]

false
Determine whether the semantic relation where cacao is the subject, owned by is the predicate, and Indigenous peoples of South America is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

12136it [41:09,  4.90it/s]

true
Determine whether the semantic relation where Natural cytotoxicity triggering receptor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12137it [41:09,  4.73it/s]

true
Determine whether the semantic relation where actinic keratosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12138it [41:09,  4.74it/s]

true
Determine whether the semantic relation where plant physiological phenomena is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

12139it [41:09,  4.74it/s]

true
Determine whether the semantic relation where Finland is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

12140it [41:10,  4.74it/s]

true
Determine whether the semantic relation where campylobacteriosis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

12142it [41:10,  4.90it/s]

true
Determine whether the semantic relation where prehypertension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where estrogen receptor 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12143it [41:10,  4.99it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Finland is the object constitutes an accurate semantic relation.

12145it [41:11,  4.92it/s]

true
Determine whether the semantic relation where hippocalcin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and fatigue is the object constitutes an accurate semantic relation.

12147it [41:11,  4.98it/s]

true
Determine whether the semantic relation where magnesium hydroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12148it [41:11,  5.08it/s]

true
Determine whether the semantic relation where burn is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

12150it [41:12,  5.08it/s]

false
Determine whether the semantic relation where hip dysplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where proglucagon is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12151it [41:12,  5.12it/s]

true
Determine whether the semantic relation where West Nile fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12153it [41:12,  4.94it/s]

true
Determine whether the semantic relation where Cucumis melo is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salmonellosis is the subject, symptoms and signs is the predicate, and dehydration is the object constitutes an accurate semantic relation.

12155it [41:13,  5.23it/s]

true
Determine whether the semantic relation where TNF superfamily member 14 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and droperidol is the object constitutes an accurate semantic relation.

12156it [41:13,  5.17it/s]

true
Determine whether the semantic relation where droperidol is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

12158it [41:13,  5.07it/s]

true
Determine whether the semantic relation where myelofibrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where GATA binding protein 5 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12160it [41:14,  5.12it/s]

true
Determine whether the semantic relation where paracoccidioidomycosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cardiomegaly is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

12161it [41:14,  5.05it/s]

true
Determine whether the semantic relation where Wiskott-Aldrich syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12163it [41:14,  5.18it/s]

true
Determine whether the semantic relation where Tyrosine kinase with immunoglobulin like and EGF like domains 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where desmoglein 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12165it [41:15,  5.07it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

12167it [41:15,  5.12it/s]

true
Determine whether the semantic relation where auscultation is the subject, uses is the predicate, and hearing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where JUN is the subject, expressed in is the predicate, and Q11394395 is the object constitutes an accurate semantic relation.

12169it [41:15,  5.17it/s]

maybe
Determine whether the semantic relation where etomidate is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CD14 molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12171it [41:16,  5.05it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and etomidate is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

12173it [41:16,  5.22it/s]

true
Determine whether the semantic relation where homoveratrylamine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serpin family F member 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12175it [41:16,  5.29it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylene blue is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12176it [41:17,  5.28it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

12178it [41:17,  5.15it/s]

true
Determine whether the semantic relation where propyl alcohol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TNF superfamily member 11 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12180it [41:17,  5.19it/s]

true
Determine whether the semantic relation where creatinine is the subject, subclass of is the predicate, and organic compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vesicle associated membrane protein 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12182it [41:18,  5.00it/s]

false
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethanol is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

12184it [41:18,  5.11it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase 2 is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where eyelid neoplasm is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12186it [41:19,  5.11it/s]

true
Determine whether the semantic relation where clomifene is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where zinc oxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12188it [41:19,  5.30it/s]

true
Determine whether the semantic relation where early medical intervention is the subject, facet of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vitamin B12 deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12189it [41:19,  5.28it/s]

true
Determine whether the semantic relation where vitamin B12 deficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12191it [41:20,  5.22it/s]

true
Determine whether the semantic relation where meningitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12193it [41:20,  5.25it/s]

true
Determine whether the semantic relation where fluoxetine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nocardiosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12194it [41:20,  5.29it/s]

true
Determine whether the semantic relation where pneumoperitoneum is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12196it [41:21,  5.28it/s]

false
Determine whether the semantic relation where plantar fasciitis is the subject, drug or therapy used for treatment is the predicate, and acetic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hypersensitivity is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

12197it [41:21,  5.30it/s]

false
Determine whether the semantic relation where (−)-nicotine is the subject, different from is the predicate, and nicotinic acid is the object constitutes an accurate semantic relation.

12198it [41:21,  5.01it/s]

true
Determine whether the semantic relation where peripheral nerve injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12200it [41:21,  5.08it/s]

true
Determine whether the semantic relation where diphenylamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where parathyroid hormone like hormone is the subject, subclass of is the predicate, and protein precursor is the object constitutes an accurate semantic relation.

12202it [41:22,  4.94it/s]

false
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and nafcillin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cyclotide is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

12204it [41:22,  5.12it/s]

true
Determine whether the semantic relation where nafcillin is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intestinal disease is the subject, drug or therapy used for treatment is the predicate, and hyoscyamine is the object constitutes an accurate semantic relation.

12206it [41:23,  5.14it/s]

true
Determine whether the semantic relation where nuclear receptor subfamily 4 group A member 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hyoscyamine is the subject, medical condition treated is the predicate, and intestinal disease is the object constitutes an accurate semantic relation.

12207it [41:23,  5.10it/s]

true
Determine whether the semantic relation where Amphiregulin is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12208it [41:23,  4.98it/s]

false
Determine whether the semantic relation where Bassia scoparia is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

12210it [41:23,  4.74it/s]

true
Determine whether the semantic relation where glutamate carboxypeptidase II is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bleeding is the subject, drug or therapy used for treatment is the predicate, and silver nitrate is the object constitutes an accurate semantic relation.

12212it [41:24,  5.03it/s]

true
Determine whether the semantic relation where silver nitrate is the subject, medical condition treated is the predicate, and bleeding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MDMA is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

12213it [41:24,  5.09it/s]

true
Determine whether the semantic relation where abdominal cavity is the subject, has part(s) is the predicate, and kidney is the object constitutes an accurate semantic relation.

12214it [41:24,  5.04it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

12216it [41:25,  5.03it/s]

false
Determine whether the semantic relation where West Nile fever is the subject, disease transmission process is the predicate, and organ transplantation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, lowest point is the predicate, and Indian Ocean is the object constitutes an accurate semantic relation.

12217it [41:25,  4.97it/s]

false
Determine whether the semantic relation where lacrimal apparatus disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12218it [41:25,  4.82it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and dexamethasone is the object constitutes an accurate semantic relation.

12219it [41:25,  4.79it/s]

true
Determine whether the semantic relation where bile duct neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

12221it [41:26,  4.91it/s]

true
Determine whether the semantic relation where vertically transmitted infection is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where physical birth injuries is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

12222it [41:26,  5.09it/s]

false
Determine whether the semantic relation where keratin 10 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12223it [41:26,  4.92it/s]

true
Determine whether the semantic relation where hereditary fructose intolerance syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12224it [41:26,  4.85it/s]

true
Determine whether the semantic relation where beer is the subject, has part(s) is the predicate, and water is the object constitutes an accurate semantic relation.

12226it [41:27,  4.96it/s]

true
Determine whether the semantic relation where cacao is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ciprofloxacin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12227it [41:27,  5.11it/s]

true
Determine whether the semantic relation where Costa Rica is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

12228it [41:27,  5.01it/s]

true
Determine whether the semantic relation where dexamethasone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

12230it [41:27,  5.05it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where North America is the subject, country is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

12232it [41:28,  5.11it/s]

true
Determine whether the semantic relation where melarsoprol is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where focal segmental glomerulosclerosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12233it [41:28,  5.21it/s]

true
Determine whether the semantic relation where sodium bicarbonate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

12235it [41:28,  5.03it/s]

true
Determine whether the semantic relation where glutamic-oxaloacetic transaminase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, shares border with is the predicate, and Russia is the object constitutes an accurate semantic relation.

12236it [41:29,  4.96it/s]

true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

12238it [41:29,  5.14it/s]

true
Determine whether the semantic relation where azaserine is the subject, subject has role is the predicate, and antifungal is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Amphibia is the subject, main food source is the predicate, and insect is the object constitutes an accurate semantic relation.

12240it [41:29,  5.20it/s]

true
Determine whether the semantic relation where phosphatidylinositol 3-kinase complex, class IB is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and Poland is the object constitutes an accurate semantic relation.

12242it [41:30,  5.27it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, designated as terrorist by is the predicate, and Poland is the object constitutes an accurate semantic relation.

12244it [41:30,  5.30it/s]

false
Determine whether the semantic relation where transplant is the subject, subclass of is the predicate, and tissue is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where o-phthalaldehyde is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

12246it [41:31,  5.21it/s]

true
Determine whether the semantic relation where tularemia is the subject, has natural reservoir is the predicate, and Q25916 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where middle age is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.

12247it [41:31,  5.08it/s]

true
Determine whether the semantic relation where auranofin is the subject, inhibitor of is the predicate, and growth is the object constitutes an accurate semantic relation.

12248it [41:31,  4.86it/s]

maybe
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

12250it [41:31,  4.80it/s]

true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

12251it [41:32,  4.97it/s]

true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

12252it [41:32,  4.72it/s]

false
Determine whether the semantic relation where endometrial carcinoma is the subject, drug or therapy used for treatment is the predicate, and estrone is the object constitutes an accurate semantic relation.

12254it [41:32,  4.75it/s]

false
Determine whether the semantic relation where estrone is the subject, medical condition treated is the predicate, and endometrial carcinoma is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Aconitase 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

12255it [41:32,  4.71it/s]

false
Determine whether the semantic relation where bile acids is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

12257it [41:33,  4.72it/s]

true
Determine whether the semantic relation where Cholecystokinin B receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inhibitor of DNA binding 1, HLH protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12259it [41:33,  4.97it/s]

false
Determine whether the semantic relation where multiple chemical sensitivity is the subject, health specialty is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nuclear power is the subject, subclass of is the predicate, and technology is the object constitutes an accurate semantic relation.

12261it [41:34,  5.12it/s]

true
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

12263it [41:34,  5.10it/s]

false
Determine whether the semantic relation where norfloxacin is the subject, found in taxon is the predicate, and Bacillus subtilis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands is the subject, member of is the predicate, and Organization for Economic Cooperation and Development is the object constitutes an accurate semantic relation.

12264it [41:34,  5.03it/s]

true
Determine whether the semantic relation where dimethyltryptamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12266it [41:35,  4.98it/s]

true
Determine whether the semantic relation where CD151 molecule (Raph blood group) is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-Cysteine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12267it [41:35,  5.06it/s]

true
Determine whether the semantic relation where cellulitis is the subject, anatomical location is the predicate, and connective tissue is the object constitutes an accurate semantic relation.

12269it [41:35,  5.09it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoproteins E is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

12271it [41:36,  5.02it/s]

true
Determine whether the semantic relation where diastasis symphysis pubis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wolfram syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

12272it [41:36,  4.88it/s]

true
Determine whether the semantic relation where mycophenolic acid is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

12274it [41:36,  4.75it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where car is the subject, source of energy is the predicate, and ethanol is the object constitutes an accurate semantic relation.

12276it [41:37,  5.11it/s]

true
Determine whether the semantic relation where Quebec is the subject, shares border with is the predicate, and New Hampshire is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Hampshire is the subject, shares border with is the predicate, and Quebec is the object constitutes an accurate semantic relation.

12278it [41:37,  5.19it/s]

true
Determine whether the semantic relation where Vascular endothelial growth factor B is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

12279it [41:37,  5.39it/s]

true
Determine whether the semantic relation where 1918–1920 flu pandemic is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12280it [41:37,  4.75it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

12282it [41:38,  4.76it/s]

true
Determine whether the semantic relation where L-threonine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

12284it [41:38,  5.21it/s]

true
Determine whether the semantic relation where scarlet fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where apolipoproteins E is the subject, biological process is the predicate, and regulation of gene expression is the object constitutes an accurate semantic relation.

12285it [41:38,  5.10it/s]

false
Determine whether the semantic relation where Ukraine is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true

12287it [41:39,  5.04it/s]

Determine whether the semantic relation where Interleukin 6 signal transducer is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 19 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

12289it [41:39,  5.13it/s]

false
Determine whether the semantic relation where copper is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where agar is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

12290it [41:39,  5.27it/s]

false
Determine whether the semantic relation where furazolidone is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

12292it [41:40,  5.00it/s]

true
Determine whether the semantic relation where Growth factor receptor bound protein 10 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, has part(s) is the predicate, and Belgium is the object constitutes an accurate semantic relation.

12293it [41:40,  4.61it/s]

false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Belgium is the object constitutes an accurate semantic relation.

12295it [41:40,  4.94it/s]

false
Determine whether the semantic relation where Belgium is the subject, part of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Belgium is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

12297it [41:41,  5.22it/s]

true
Determine whether the semantic relation where Williams-Beuren syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitamin B12 deficiency is the subject, symptoms and signs is the predicate, and cognitive dysfunction is the object constitutes an accurate semantic relation.

12298it [41:41,  5.16it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

12300it [41:41,  5.03it/s]

false
Determine whether the semantic relation where Ebstein anomaly is the subject, subclass of is the predicate, and aortic disease is the object constitutes an accurate semantic relation.
false

12301it [41:42,  5.10it/s]

Determine whether the semantic relation where postural orthostatic tachycardia syndrome is the subject, subclass of is the predicate, and autoimmune disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

12302it [41:42,  5.17it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

12303it [41:42,  5.00it/s]

true
Determine whether the semantic relation where listeriosis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

12305it [41:42,  4.90it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Sweden is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fecal incontinence is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12307it [41:43,  4.82it/s]

true
Determine whether the semantic relation where twin-to-twin transfusion syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where O-phospho-L-serine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

12309it [41:43,  4.84it/s]

false
Determine whether the semantic relation where thyroiditis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where southern pig-tailed macaque is the subject, IUCN conservation status is the predicate, and endangered species is the object constitutes an accurate semantic relation.

12310it [41:44,  4.60it/s]

false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

12311it [41:44,  4.08it/s]

true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

12313it [41:44,  4.47it/s]

true
Determine whether the semantic relation where hepatitis A is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leprosy is the subject, symptoms and signs is the predicate, and nosebleed is the object constitutes an accurate semantic relation.

12315it [41:45,  4.73it/s]

maybe
Determine whether the semantic relation where hydrofluorocarbon is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholecystokinin is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

12316it [41:45,  4.71it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

12317it [41:45,  4.64it/s]

true
Determine whether the semantic relation where Lymphatic Malformation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12318it [41:45,  4.69it/s]

true
Determine whether the semantic relation where KIT proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and acrosomal vesicle is the object constitutes an accurate semantic relation.

12320it [41:46,  4.80it/s]

false
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

12322it [41:46,  4.94it/s]

true
Determine whether the semantic relation where abscess is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

12324it [41:47,  5.14it/s]

true
Determine whether the semantic relation where factor XII deficiency is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where person is the subject, has characteristic is the predicate, and marital status is the object constitutes an accurate semantic relation.

12326it [41:47,  5.22it/s]

true
Determine whether the semantic relation where nocardiosis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where colonic neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

12327it [41:47,  5.12it/s]

true
Determine whether the semantic relation where squalene is the subject, found in taxon is the predicate, and Bacillus is the object constitutes an accurate semantic relation.

12329it [41:47,  5.12it/s]

false
Determine whether the semantic relation where vitamin D receptor is the subject, biological process is the predicate, and lactation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sparganosis is the subject, symptoms and signs is the predicate, and hydrocephalus is the object constitutes an accurate semantic relation.

12331it [41:48,  5.12it/s]

true
Determine whether the semantic relation where Li-Fraumeni syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Dual specificity phosphatase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12332it [41:48,  5.19it/s]

true
Determine whether the semantic relation where pleural disease is the subject, symptoms and signs is the predicate, and heart failure is the object constitutes an accurate semantic relation.

12333it [41:48,  4.95it/s]

false
Determine whether the semantic relation where antisocial personality disorder is the subject, drug or therapy used for treatment is the predicate, and antipsychotics is the object constitutes an accurate semantic relation.

12334it [41:49,  4.92it/s]

maybe
Determine whether the semantic relation where life support system is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

12335it [41:49,  4.93it/s]

false
Determine whether the semantic relation where bursitis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.

12337it [41:49,  4.98it/s]

true
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12339it [41:49,  5.16it/s]

false
Determine whether the semantic relation where bepridil is the subject, subject has role is the predicate, and antihypertensive drug is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pervasive developmental disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

12340it [41:50,  4.97it/s]

true
Determine whether the semantic relation where hypokalemic periodic paralysis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12342it [41:50,  4.94it/s]

true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where West Nile fever is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.

12344it [41:50,  5.19it/s]

false
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malaria is the subject, has contributing factor is the predicate, and poverty is the object constitutes an accurate semantic relation.

12346it [41:51,  5.20it/s]

true
Determine whether the semantic relation where intraocular pressure is the subject, subclass of is the predicate, and pressure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where post-traumatic epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12347it [41:51,  5.20it/s]

true
Determine whether the semantic relation where cytochrome P450 family 1 subfamily A member 1 is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

12349it [41:51,  4.94it/s]

false
Determine whether the semantic relation where Catechin (no stereochemistry defined) is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where C-X-C motif chemokine ligand 9 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12350it [41:52,  4.50it/s]

false
Determine whether the semantic relation where protein tyrosine kinase 2 beta is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.

12352it [41:52,  4.92it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tanzania is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

12353it [41:52,  4.92it/s]

true
Determine whether the semantic relation where guanosine triphosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12354it [41:53,  4.89it/s]

false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Tanzania is the object constitutes an accurate semantic relation.

12355it [41:53,  4.87it/s]

true
Determine whether the semantic relation where cotinine is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

12356it [41:53,  4.83it/s]

false
Determine whether the semantic relation where Job's syndrome is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

12358it [41:53,  4.95it/s]

true
Determine whether the semantic relation where suramin is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary atresia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

12360it [41:54,  5.13it/s]

true
Determine whether the semantic relation where emerging communicable disease is the subject, health specialty is the predicate, and public health is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12362it [41:54,  5.33it/s]

true
Determine whether the semantic relation where dysentery is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12364it [41:54,  5.34it/s]

false
Determine whether the semantic relation where central nervous system bacterial infection is the subject, anatomical location is the predicate, and central nervous system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperammonemia is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

12366it [41:55,  4.99it/s]

false
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Aspergillus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mali is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

12367it [41:55,  5.09it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Mali is the object constitutes an accurate semantic relation.

12368it [41:55,  5.00it/s]

true
Determine whether the semantic relation where primary hyperoxaluria is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

12370it [41:56,  4.88it/s]

true
Determine whether the semantic relation where attitude to health is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

12371it [41:56,  4.93it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

12373it [41:56,  4.94it/s]

true
Determine whether the semantic relation where Norway is the subject, shares border with is the predicate, and Russia is the object constitutes an accurate semantic relation.
true

12374it [41:57,  5.06it/s]

Determine whether the semantic relation where Norway is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

12375it [41:57,  5.22it/s]

true
Determine whether the semantic relation where postcholecystectomy syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12377it [41:57,  4.71it/s]

true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Aryl hydrocarbon receptor nuclear translocator like is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

12378it [41:57,  4.57it/s]

false
Determine whether the semantic relation where pelvic floor dysfunction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12380it [41:58,  4.38it/s]

true
Determine whether the semantic relation where gastroenteritis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Killer cell lectin like receptor D1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12382it [41:58,  4.61it/s]

true
Determine whether the semantic relation where Russia is the subject, shares border with is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Norway is the object constitutes an accurate semantic relation.

12383it [41:59,  4.71it/s]

true
Determine whether the semantic relation where solute carrier family 3 member 2 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.

12385it [41:59,  4.81it/s]

false
Determine whether the semantic relation where 1-octanol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Collagen type XIII [endoplasmic reticulum lumen] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

12387it [41:59,  4.58it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Methylmalonyl-CoA mutase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12388it [42:00,  4.86it/s]

false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

12389it [42:00,  4.86it/s]

true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

12391it [42:00,  4.54it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where medical algorithm is the subject, has use is the predicate, and medicine is the object constitutes an accurate semantic relation.

12393it [42:01,  4.77it/s]

true
Determine whether the semantic relation where Uzbekistan is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EPH receptor B6 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

12394it [42:01,  4.98it/s]

true
Determine whether the semantic relation where hypoesthesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12395it [42:01,  4.91it/s]

false
Determine whether the semantic relation where Erinaceidae is the subject, main food source is the predicate, and insect is the object constitutes an accurate semantic relation.

12397it [42:01,  4.86it/s]

true
Determine whether the semantic relation where Stevens–Johnson syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thrombocytopenia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12398it [42:02,  4.31it/s]

true
Determine whether the semantic relation where Far East scarlet-like fever is the subject, has natural reservoir is the predicate, and Rodent is the object constitutes an accurate semantic relation.

12400it [42:02,  4.50it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Low density lipoprotein receptor is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

12402it [42:03,  3.80it/s]

false
Determine whether the semantic relation where angiotensin II receptor type 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glutathione is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12404it [42:03,  4.36it/s]

false
Determine whether the semantic relation where ret proto-oncogene is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azacitidine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

12406it [42:04,  4.58it/s]

false
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aniridia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12408it [42:04,  4.88it/s]

true
Determine whether the semantic relation where rheumatoid arthritis is the subject, afflicts is the predicate, and sclera is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

12409it [42:05,  3.59it/s]

true
Determine whether the semantic relation where MDMA is the subject, route of administration is the predicate, and sublingual administration is the object constitutes an accurate semantic relation.

12411it [42:05,  3.97it/s]

true
Determine whether the semantic relation where AP-2 complex is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

12412it [42:05,  3.95it/s]

true
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12413it [42:06,  3.50it/s]

false
Determine whether the semantic relation where mucin 1, cell surface associated is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12415it [42:06,  4.02it/s]

false
Determine whether the semantic relation where zidovudine is the subject, significant drug interaction is the predicate, and paracetamol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where health is the subject, studied by is the predicate, and public health is the object constitutes an accurate semantic relation.

12417it [42:07,  4.28it/s]

false
Determine whether the semantic relation where piroxicam is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where β-carotene is the subject, found in taxon is the predicate, and Cucumis sativus is the object constitutes an accurate semantic relation.

12419it [42:07,  4.68it/s]

true
Determine whether the semantic relation where lichen planus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nontuberculous mycobacterial infectious disease is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

12421it [42:07,  5.01it/s]

true
Determine whether the semantic relation where mucocutaneous leishmaniasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

12423it [42:08,  5.03it/s]

true
Determine whether the semantic relation where oleanolic acid is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where St. Louis encephalitis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

12424it [42:08,  5.16it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.

12425it [42:08,  4.99it/s]

true
Determine whether the semantic relation where vaccination is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.

12427it [42:08,  4.92it/s]

true
Determine whether the semantic relation where myasthenia gravis is the subject, drug or therapy used for treatment is the predicate, and (RS)-cyclophosphamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and liver cirrhosis is the object constitutes an accurate semantic relation.

12429it [42:09,  5.06it/s]

true
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, medical condition treated is the predicate, and myasthenia gravis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

12430it [42:09,  4.42it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

12432it [42:10,  4.22it/s]

true
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Phosphofructokinase, liver type is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12433it [42:10,  4.46it/s]

true
Determine whether the semantic relation where EPH receptor B6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12435it [42:10,  4.66it/s]

false
Determine whether the semantic relation where Korean War is the subject, participant is the predicate, and Australia is the object constitutes an accurate semantic relation.
true

12436it [42:10,  4.76it/s]

Determine whether the semantic relation where transforming growth factor alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.

12437it [42:11,  4.89it/s]

true
Determine whether the semantic relation where European Union is the subject, shares border with is the predicate, and Moldova is the object constitutes an accurate semantic relation.

12439it [42:11,  4.78it/s]

true
Determine whether the semantic relation where Australia is the subject, participant in is the predicate, and Korean War is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where optical coherence tomography is the subject, subclass of is the predicate, and microscopy is the object constitutes an accurate semantic relation.

12441it [42:11,  5.11it/s]

true
Determine whether the semantic relation where sarcocystosis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

12443it [42:12,  5.23it/s]

true
Determine whether the semantic relation where prochlorperazine is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paraplegia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12444it [42:12,  5.28it/s]

false
Determine whether the semantic relation where United States is the subject, located in or next to body of water is the predicate, and Pacific Ocean is the object constitutes an accurate semantic relation.

12446it [42:12,  5.00it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 2 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true

12447it [42:13,  4.99it/s]

Determine whether the semantic relation where common variable immunodeficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where abnormal reflex is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

12449it [42:13,  5.05it/s]

false
Determine whether the semantic relation where latex allergy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

12450it [42:13,  5.06it/s]

true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

12452it [42:14,  5.08it/s]

true
Determine whether the semantic relation where information science is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coagulation factor XIII A chain is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12453it [42:14,  5.19it/s]

false
Determine whether the semantic relation where phospholipase A2 group III is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12454it [42:14,  5.10it/s]

true
Determine whether the semantic relation where bleeding gums is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

12456it [42:14,  5.20it/s]

false
Determine whether the semantic relation where tricuspid insufficiency is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovenia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

12458it [42:15,  5.22it/s]

true
Determine whether the semantic relation where diphyllobothriasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Slovenia is the object constitutes an accurate semantic relation.

12460it [42:15,  5.21it/s]

true
Determine whether the semantic relation where information theory is the subject, facet of is the predicate, and statistics is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where adenosine triphosphate is the subject, found in taxon is the predicate, and Bacteria is the object constitutes an accurate semantic relation.

12461it [42:15,  5.28it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

12462it [42:16,  4.88it/s]

true
Determine whether the semantic relation where keratin 17 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12463it [42:16,  4.79it/s]

true
Determine whether the semantic relation where vitamin D receptor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12465it [42:16,  4.97it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phlebotomus fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

12467it [42:17,  5.03it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arteriosclerosis is the subject, has cause is the predicate, and stress is the object constitutes an accurate semantic relation.

12468it [42:17,  5.18it/s]

maybe
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

12469it [42:17,  4.79it/s]

true
Determine whether the semantic relation where school of public health is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

12471it [42:17,  4.89it/s]

true
Determine whether the semantic relation where CD86 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where masochism is the subject, has characteristic is the predicate, and pain is the object constitutes an accurate semantic relation.

12472it [42:18,  5.00it/s]

true
Determine whether the semantic relation where herpes gestationis is the subject, health specialty is the predicate, and obstetrics is the object constitutes an accurate semantic relation.

12474it [42:18,  5.14it/s]

true
Determine whether the semantic relation where ileal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, main food source is the predicate, and bird is the object constitutes an accurate semantic relation.

12476it [42:18,  5.32it/s]

false
Determine whether the semantic relation where chlorophyll is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where art is the subject, subclass of is the predicate, and recreation is the object constitutes an accurate semantic relation.

12477it [42:19,  5.30it/s]

maybe
Determine whether the semantic relation where BCL2 is the subject, expressed in is the predicate, and trigeminal ganglion is the object constitutes an accurate semantic relation.

12479it [42:19,  5.00it/s]

false
Determine whether the semantic relation where styrene is the subject, found in taxon is the predicate, and Aspergillus niger is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-kynurenine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12481it [42:19,  4.99it/s]

false
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where paper is the subject, has characteristic is the predicate, and permeability is the object constitutes an accurate semantic relation.

12483it [42:20,  5.10it/s]

true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acidosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

12484it [42:20,  5.16it/s]

false
Determine whether the semantic relation where Broad Bean is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

12486it [42:20,  4.93it/s]

false
Determine whether the semantic relation where glucosamine-phosphate N-acetyltransferase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true

12487it [42:21,  5.07it/s]

Determine whether the semantic relation where partial pressure is the subject, studied by is the predicate, and thermodynamics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12489it [42:21,  5.24it/s]

false
Determine whether the semantic relation where infectious mononucleosis is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where retinoid X receptor gamma is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12491it [42:21,  5.13it/s]

true
Determine whether the semantic relation where atelectasis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where soap is the subject, subclass of is the predicate, and organic compound is the object constitutes an accurate semantic relation.

12493it [42:22,  5.07it/s]

false
Determine whether the semantic relation where observation is the subject, different from is the predicate, and observational study is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cortical blindness is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12494it [42:22,  5.10it/s]

true
Determine whether the semantic relation where major histocompatibility complex, class I, A is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12496it [42:22,  5.00it/s]

true
Determine whether the semantic relation where retinal vein occlusion is the subject, drug or therapy used for treatment is the predicate, and betamethasone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where drug tolerance is the subject, subclass of is the predicate, and drug resistance is the object constitutes an accurate semantic relation.

12498it [42:23,  5.16it/s]

false
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and splenomegaly is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pemphigus is the subject, drug or therapy used for treatment is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

12499it [42:23,  5.22it/s]

true
Determine whether the semantic relation where chloroquine is the subject, medical condition treated is the predicate, and pemphigus is the object constitutes an accurate semantic relation.

12501it [42:23,  5.04it/s]

true
Determine whether the semantic relation where aminocaproic acid is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyridoxine is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.

12502it [42:24,  5.00it/s]

false
Determine whether the semantic relation where (RS)-thioctic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12503it [42:24,  4.85it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

12505it [42:24,  5.10it/s]

true
Determine whether the semantic relation where cardiovascular infection is the subject, subclass of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vestibulocochlear nerve injury is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12506it [42:24,  4.80it/s]

false
Determine whether the semantic relation where fragile X syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12508it [42:25,  4.93it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where preterm birth is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

12509it [42:25,  4.45it/s]

true
Determine whether the semantic relation where aortic valve insufficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12511it [42:25,  4.71it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thioridazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

12513it [42:26,  4.83it/s]

true
Determine whether the semantic relation where okadaic acid is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where patient information leaflet is the subject, subclass of is the predicate, and user guide is the object constitutes an accurate semantic relation.

12515it [42:26,  5.04it/s]

true
Determine whether the semantic relation where SMAD family member 7 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sinusitis is the subject, drug or therapy used for treatment is the predicate, and ciprofloxacin is the object constitutes an accurate semantic relation.

12517it [42:27,  4.90it/s]

maybe
Determine whether the semantic relation where ciprofloxacin is the subject, medical condition treated is the predicate, and sinusitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fluphenazine is the subject, subclass of is the predicate, and alcohols is the object constitutes an accurate semantic relation.

12518it [42:27,  4.97it/s]

false
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12520it [42:27,  5.08it/s]

true
Determine whether the semantic relation where 2-chloroacetophenone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyanocobalamin is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

12521it [42:27,  5.07it/s]

true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and bleeding is the object constitutes an accurate semantic relation.

12522it [42:28,  4.63it/s]

true
Determine whether the semantic relation where serotonin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12524it [42:28,  4.44it/s]

true
Determine whether the semantic relation where Creutzfeldt-Jakob disease is the subject, medical examination is the predicate, and neurological examination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where corneal ulcer is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12526it [42:29,  4.84it/s]

true
Determine whether the semantic relation where gelatin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cameroon is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

12528it [42:29,  5.08it/s]

true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Cameroon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where proinsulin is the subject, instance of is the predicate, and protein fragment is the object constitutes an accurate semantic relation.

12529it [42:29,  5.07it/s]

false
Determine whether the semantic relation where dysmenorrhea is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12531it [42:30,  4.86it/s]

true
Determine whether the semantic relation where hydroxysteroid 17-beta dehydrogenase 4 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czechoslovakia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

12533it [42:30,  4.97it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Czechoslovakia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sympathetic ophthalmia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12535it [42:30,  5.03it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Honduras is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Honduras is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

12536it [42:31,  5.05it/s]

true
Determine whether the semantic relation where lymphopenia is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

12538it [42:31,  4.89it/s]

false
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

12540it [42:31,  5.14it/s]

true
Determine whether the semantic relation where rac-warfarin is the subject, route of administration is the predicate, and intravenous injection is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where strongyloidiasis is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

12542it [42:32,  5.16it/s]

false
Determine whether the semantic relation where Slovakia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Kyrgyzstan is the object constitutes an accurate semantic relation.

12543it [42:32,  5.00it/s]

true
Determine whether the semantic relation where Methylmalonyl-CoA mutase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

12544it [42:32,  4.58it/s]

false
Determine whether the semantic relation where genome is the subject, part of is the predicate, and cell is the object constitutes an accurate semantic relation.

12545it [42:33,  3.55it/s]

true
Determine whether the semantic relation where cytotoxin is the subject, subclass of is the predicate, and poison is the object constitutes an accurate semantic relation.

12546it [42:33,  3.77it/s]

true
Determine whether the semantic relation where pulmonary surfactant is the subject, instance of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

12548it [42:33,  4.28it/s]

false
Determine whether the semantic relation where hemangioendothelioma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kyrgyzstan is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

12549it [42:34,  4.54it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

12550it [42:34,  4.63it/s]

true
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

12552it [42:34,  4.65it/s]

true
Determine whether the semantic relation where Texas is the subject, named after is the predicate, and friend is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where leukopenia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12553it [42:34,  4.81it/s]

true
Determine whether the semantic relation where siderosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12555it [42:35,  4.95it/s]

true
Determine whether the semantic relation where nitrofurazone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Los Angeles is the subject, twinned administrative body is the predicate, and Berlin is the object constitutes an accurate semantic relation.

12557it [42:35,  5.23it/s]

true
Determine whether the semantic relation where Berlin is the subject, twinned administrative body is the predicate, and Los Angeles is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where murexide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12559it [42:36,  5.07it/s]

true
Determine whether the semantic relation where citric acid is the subject, found in taxon is the predicate, and Scutellaria baicalensis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular malformation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12561it [42:36,  5.19it/s]

true
Determine whether the semantic relation where aspirin is the subject, medical condition treated is the predicate, and osteoarthritis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, first aid measures is the predicate, and Q21893647 is the object constitutes an accurate semantic relation.

12562it [42:36,  5.25it/s]

false
Determine whether the semantic relation where climatotherapy is the subject, studied by is the predicate, and medicine is the object constitutes an accurate semantic relation.

12564it [42:37,  4.86it/s]

true
Determine whether the semantic relation where sinusitis is the subject, drug or therapy used for treatment is the predicate, and methylprednisolone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylprednisolone is the subject, medical condition treated is the predicate, and sinusitis is the object constitutes an accurate semantic relation.

12565it [42:37,  5.07it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12567it [42:37,  5.06it/s]

false
Determine whether the semantic relation where osteoarthritis is the subject, drug or therapy used for treatment is the predicate, and aspirin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 7 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12569it [42:38,  5.00it/s]

true
Determine whether the semantic relation where aminolevulinic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

12571it [42:38,  5.22it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q45874067 is the subject, different from is the predicate, and plant-based diet is the object constitutes an accurate semantic relation.

12573it [42:38,  5.10it/s]

false
Determine whether the semantic relation where paraffin wax is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and bepridil is the object constitutes an accurate semantic relation.

12575it [42:39,  5.00it/s]

true
Determine whether the semantic relation where hemophilia C is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bepridil is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

12577it [42:39,  5.12it/s]

true
Determine whether the semantic relation where physiotherapy is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.

12578it [42:39,  5.19it/s]

true
Determine whether the semantic relation where Platelet derived growth factor subunit B is the subject, biological process is the predicate, and hemopoiesis is the object constitutes an accurate semantic relation.

12580it [42:40,  5.14it/s]

false
Determine whether the semantic relation where mercaptopurine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where car is the subject, source of energy is the predicate, and electricity is the object constitutes an accurate semantic relation.

12581it [42:40,  5.18it/s]

maybe
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

12583it [42:40,  5.12it/s]

true
Determine whether the semantic relation where cell is the subject, different from is the predicate, and cell biology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cell is the subject, studied by is the predicate, and cell biology is the object constitutes an accurate semantic relation.

12584it [42:40,  5.01it/s]

true
Determine whether the semantic relation where cell biology is the subject, is the study of is the predicate, and cell is the object constitutes an accurate semantic relation.

12585it [42:41,  4.96it/s]

true
Determine whether the semantic relation where bone morphogenetic protein 4 is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

12586it [42:41,  4.61it/s]

false
Determine whether the semantic relation where sphincter of Oddi dysfunction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12587it [42:41,  4.60it/s]

true
Determine whether the semantic relation where procollagen-proline 4-dioxygenase complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

12588it [42:41,  4.68it/s]

false
Determine whether the semantic relation where aortic dissection is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12589it [42:42,  4.50it/s]

true
Determine whether the semantic relation where noma is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

12591it [42:42,  4.71it/s]

true
Determine whether the semantic relation where showdomycin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystathionine gamma-lyase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12592it [42:42,  4.89it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

12593it [42:42,  4.86it/s]

true
Determine whether the semantic relation where mucolipidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12595it [42:43,  5.05it/s]

true
Determine whether the semantic relation where Keratin 8 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and France is the object constitutes an accurate semantic relation.

12597it [42:43,  5.14it/s]

false
Determine whether the semantic relation where France is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smoking is the subject, has effect is the predicate, and Crohn's disease is the object constitutes an accurate semantic relation.

12598it [42:43,  5.18it/s]

false
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and thioridazine is the object constitutes an accurate semantic relation.

12599it [42:44,  4.98it/s]

true
Determine whether the semantic relation where thioridazine is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.
true

12601it [42:44,  4.99it/s]

Determine whether the semantic relation where Histamine receptor H2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypothermia is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

12603it [42:44,  5.20it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, cell component is the predicate, and nuclear envelope is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Herpes labialis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

12605it [42:45,  4.53it/s]

true
Determine whether the semantic relation where hyperinsulinism is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Keratin 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12606it [42:45,  4.45it/s]

false
Determine whether the semantic relation where oligospermia is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

12607it [42:45,  4.48it/s]

true
Determine whether the semantic relation where meningitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

12609it [42:46,  4.73it/s]

true
Determine whether the semantic relation where coproporphyrinogen oxidase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vancomycin is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

12610it [42:46,  4.95it/s]

false
Determine whether the semantic relation where emphysema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12612it [42:46,  4.92it/s]

true
Determine whether the semantic relation where systemic scleroderma is the subject, drug or therapy used for treatment is the predicate, and tolazoline is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and vancomycin is the object constitutes an accurate semantic relation.

12613it [42:47,  5.04it/s]

false
Determine whether the semantic relation where tolazoline is the subject, medical condition treated is the predicate, and systemic scleroderma is the object constitutes an accurate semantic relation.

12615it [42:47,  4.97it/s]

false
Determine whether the semantic relation where pectin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

12617it [42:47,  4.92it/s]

true
Determine whether the semantic relation where spermidine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where didanosine is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.

12618it [42:48,  4.99it/s]

false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.

12619it [42:48,  4.97it/s]

true
Determine whether the semantic relation where abnormal lordosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12620it [42:48,  4.70it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

12622it [42:49,  4.17it/s]

true
Determine whether the semantic relation where anterior spinal artery syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

12623it [42:49,  4.11it/s]

true
Determine whether the semantic relation where domperidone is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

12624it [42:49,  4.26it/s]

true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and domperidone is the object constitutes an accurate semantic relation.

12625it [42:49,  4.32it/s]

true
Determine whether the semantic relation where fire is the subject, subclass of is the predicate, and physical phenomenon is the object constitutes an accurate semantic relation.

12626it [42:49,  4.45it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

12627it [42:50,  4.45it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

12629it [42:50,  4.68it/s]

true
Determine whether the semantic relation where dicrocoeliasis is the subject, has natural reservoir is the predicate, and pig is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where renin–angiotensin system is the subject, subclass of is the predicate, and endocrine system is the object constitutes an accurate semantic relation.

12631it [42:50,  4.93it/s]

true
Determine whether the semantic relation where Cardiac Edema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Proline dehydrogenase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12633it [42:51,  5.01it/s]

true
Determine whether the semantic relation where Proline dehydrogenase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase kinase kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12634it [42:51,  5.15it/s]

true
Determine whether the semantic relation where glycogen phosphorylase, muscle associated is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

12635it [42:51,  4.92it/s]

false
Determine whether the semantic relation where malformation of cortical development is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12637it [42:52,  4.79it/s]

true
Determine whether the semantic relation where preventive medicine is the subject, subclass of is the predicate, and health care is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where preventive medicine is the subject, different from is the predicate, and health care is the object constitutes an accurate semantic relation.

12639it [42:52,  4.78it/s]

false
Determine whether the semantic relation where health care is the subject, different from is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fibroblast growth factor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12641it [42:53,  4.75it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-serine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12642it [42:53,  4.58it/s]

true
Determine whether the semantic relation where Complement factor H is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12644it [42:53,  4.39it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where theophylline is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12646it [42:54,  4.73it/s]

false
Determine whether the semantic relation where neonatal jaundice is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diphtheria is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12648it [42:54,  4.86it/s]

true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 11 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

12650it [42:54,  5.03it/s]

true
Determine whether the semantic relation where thiamine(1+) ion is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where obsessive-compulsive disorder is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

12651it [42:55,  4.95it/s]

maybe
Determine whether the semantic relation where vestibular neuronitis is the subject, medical examination is the predicate, and neuroimaging is the object constitutes an accurate semantic relation.

12653it [42:55,  4.71it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.

12654it [42:55,  4.81it/s]

true
Determine whether the semantic relation where Aconitase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12656it [42:56,  4.73it/s]

false
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salicylic acid is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

12658it [42:56,  5.13it/s]

false
Determine whether the semantic relation where anxiety is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

12660it [42:57,  5.11it/s]

true
Determine whether the semantic relation where fetal erythroblastosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thromboangiitis obliterans is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12662it [42:57,  4.77it/s]

true
Determine whether the semantic relation where CD80 molecule is the subject, biological process is the predicate, and viral entry into host cell is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.

12664it [42:58,  4.28it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Panama is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Panama is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

12665it [42:58,  4.55it/s]

true
Determine whether the semantic relation where social isolation is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.

12667it [42:58,  4.90it/s]

true
Determine whether the semantic relation where ethionamide is the subject, subject has role is the predicate, and protein synthesis inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prison is the subject, subclass of is the predicate, and organization is the object constitutes an accurate semantic relation.

12669it [42:59,  4.84it/s]

true
Determine whether the semantic relation where camphor is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where X-linked adrenoleukodystrophy is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

12671it [42:59,  5.13it/s]

false
Determine whether the semantic relation where physician is the subject, country is the predicate, and Poland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tennis elbow is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12672it [42:59,  4.96it/s]

true
Determine whether the semantic relation where herpes simplex is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

12674it [43:00,  4.93it/s]

true
Determine whether the semantic relation where Keratin 14 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (Z)-flupentixol is the subject, subclass of is the predicate, and alcohols is the object constitutes an accurate semantic relation.

12676it [43:00,  5.05it/s]

false
Determine whether the semantic relation where optic nerve injury is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SOS Ras/Rac guanine nucleotide exchange factor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12678it [43:00,  4.97it/s]

true
Determine whether the semantic relation where pulmonary emphysema is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital toxoplasmosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12679it [43:01,  4.98it/s]

true
Determine whether the semantic relation where osteosclerosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false

12680it [43:01,  4.97it/s]

Determine whether the semantic relation where mitomycin is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

12682it [43:01,  5.02it/s]

true
Determine whether the semantic relation where Morocco is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.

12684it [43:01,  5.17it/s]

false
Determine whether the semantic relation where pulmonary valve insufficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coarctation of the aorta is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

12686it [43:02,  4.93it/s]

false
Determine whether the semantic relation where mediastinitis is the subject, subclass of is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and bradycardia is the object constitutes an accurate semantic relation.

12687it [43:02,  4.96it/s]

false
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12689it [43:03,  4.80it/s]

true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, shares border with is the predicate, and Morocco is the object constitutes an accurate semantic relation.

12691it [43:03,  5.00it/s]

true
Determine whether the semantic relation where DNA nucleotidylexotransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where St. Louis encephalitis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

12693it [43:03,  4.55it/s]

true
Determine whether the semantic relation where polysaccharide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where non-Hodgkin lymphoma is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

12694it [43:04,  3.86it/s]

true
Determine whether the semantic relation where melioidosis is the subject, has natural reservoir is the predicate, and domesticated animal is the object constitutes an accurate semantic relation.

12696it [43:04,  4.34it/s]

false
Determine whether the semantic relation where Felty's syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fludeoxyglucose (18F) is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12698it [43:05,  4.63it/s]

true
Determine whether the semantic relation where perphenazine is the subject, subclass of is the predicate, and alcohols is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where copper(II) sulfate pentahydrate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12699it [43:05,  4.76it/s]

true
Determine whether the semantic relation where parathyroid hormone like hormone is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12701it [43:05,  4.39it/s]

false
Determine whether the semantic relation where articaine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Iran is the object constitutes an accurate semantic relation.

12702it [43:06,  4.66it/s]

false
Determine whether the semantic relation where Iran is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

12704it [43:06,  4.55it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Sudan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amino acid metabolic disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12706it [43:06,  4.79it/s]

true
Determine whether the semantic relation where brucellosis is the subject, symptoms and signs is the predicate, and arthritis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sudan is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

12708it [43:07,  4.96it/s]

true
Determine whether the semantic relation where dermatomyositis is the subject, medical examination is the predicate, and Q73401885 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lysosomal storage disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12710it [43:07,  5.09it/s]

true
Determine whether the semantic relation where putrescine is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where heptyl alcohol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.

12712it [43:08,  5.06it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Leber hereditary optic neuropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12713it [43:08,  4.83it/s]

true
Determine whether the semantic relation where gastroenteritis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

12714it [43:08,  4.79it/s]

true
Determine whether the semantic relation where potassium dichromate is the subject, has part(s) is the predicate, and potassium is the object constitutes an accurate semantic relation.

12715it [43:08,  4.81it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

12717it [43:09,  4.84it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chancroid is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12719it [43:09,  5.12it/s]

true
Determine whether the semantic relation where bronchiolitis is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.

12720it [43:09,  5.21it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

12721it [43:09,  5.01it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

12722it [43:10,  4.75it/s]

true
Determine whether the semantic relation where arachidonic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12723it [43:10,  4.67it/s]

false
Determine whether the semantic relation where frontotemporal lobar degeneration is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12724it [43:10,  4.59it/s]

true
Determine whether the semantic relation where GC vitamin D binding protein is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

12726it [43:10,  4.73it/s]

true
Determine whether the semantic relation where acute promyelocytic leukemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where electrical burn is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

12728it [43:11,  5.06it/s]

false
Determine whether the semantic relation where droperidol is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and droperidol is the object constitutes an accurate semantic relation.

12730it [43:11,  5.27it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Ivory Coast is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ivory Coast is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

12732it [43:12,  5.37it/s]

true
Determine whether the semantic relation where diet is the subject, has contributing factor is the predicate, and oral health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where butyric acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.

12734it [43:12,  5.42it/s]

false
Determine whether the semantic relation where Ras homolog family member A is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where C-C motif chemokine ligand 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12735it [43:12,  5.52it/s]

true
Determine whether the semantic relation where contactin 2 is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.

12737it [43:13,  5.24it/s]

false
Determine whether the semantic relation where asphyxia neonatorum is the subject, subclass of is the predicate, and respiratory disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where A-Raf proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cellular component is the object constitutes an accurate semantic relation.

12739it [43:13,  5.04it/s]

false
Determine whether the semantic relation where peer group is the subject, different from is the predicate, and age group is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where age group is the subject, different from is the predicate, and peer group is the object constitutes an accurate semantic relation.

12741it [43:13,  5.11it/s]

false
Determine whether the semantic relation where mucus is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (+)-pseudoephedrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12742it [43:14,  5.11it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

12744it [43:14,  4.99it/s]

false
Determine whether the semantic relation where long QT syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where autoimmune thrombocytopenic purpura is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12746it [43:14,  4.98it/s]

true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

12748it [43:15,  4.80it/s]

true
Determine whether the semantic relation where trisaccharide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

12749it [43:15,  4.89it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

12750it [43:15,  4.83it/s]

true
Determine whether the semantic relation where United States is the subject, shares border with is the predicate, and Canada is the object constitutes an accurate semantic relation.

12752it [43:16,  4.78it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Symbolism is the subject, country is the predicate, and Russian Empire is the object constitutes an accurate semantic relation.

12754it [43:16,  5.04it/s]

false
Determine whether the semantic relation where essential fatty acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where France is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

12755it [43:16,  4.94it/s]

true
Determine whether the semantic relation where systemic lupus erythematosus is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

12756it [43:16,  4.86it/s]

true
Determine whether the semantic relation where gamma-glutamylcyclotransferase is the subject, subclass of is the predicate, and lyase is the object constitutes an accurate semantic relation.
false

12758it [43:17,  5.03it/s]

Determine whether the semantic relation where Von Hippel-Lindau tumor suppressor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Latvia is the object constitutes an accurate semantic relation.

12759it [43:17,  5.10it/s]

true
Determine whether the semantic relation where edetic acid is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

12761it [43:17,  5.03it/s]

true
Determine whether the semantic relation where Bermuda is the subject, country is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where narcolepsy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12763it [43:18,  5.13it/s]

true
Determine whether the semantic relation where Latvia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.

12765it [43:18,  5.32it/s]

true
Determine whether the semantic relation where CD4 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12767it [43:19,  5.37it/s]

true
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anesthesia dolorosa is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12768it [43:19,  5.31it/s]

true
Determine whether the semantic relation where guanidine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12769it [43:19,  5.17it/s]

true
Determine whether the semantic relation where Hydroxyacyl-CoA dehydrogenase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12770it [43:19,  4.86it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

12771it [43:19,  4.82it/s]

true
Determine whether the semantic relation where radiation syndrome is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
false

12773it [43:20,  4.98it/s]

Determine whether the semantic relation where [5-(2,4-Dioxopyrimidin-1-yl)-3,4-dihydroxyoxolan-2-yl]methyl dihydrogen phosphate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Farber lipogranulomatosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12774it [43:20,  4.95it/s]

true
Determine whether the semantic relation where sucrose is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

12775it [43:20,  4.92it/s]

false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

12777it [43:21,  5.05it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cucumis sativus is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

12778it [43:21,  4.83it/s]

false
Determine whether the semantic relation where ubidecarenone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12780it [43:21,  4.61it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pectus excavatum is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

12781it [43:21,  4.83it/s]

maybe
Determine whether the semantic relation where ghrelin is the subject, biological process is the predicate, and excitatory postsynaptic potential is the object constitutes an accurate semantic relation.

12782it [43:22,  4.86it/s]

false
Determine whether the semantic relation where septic arthritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12784it [43:22,  4.97it/s]

true
Determine whether the semantic relation where phosphocreatine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and clomipramine is the object constitutes an accurate semantic relation.

12786it [43:22,  5.10it/s]

true
Determine whether the semantic relation where marker of proliferation Ki-67 is the subject, cell component is the predicate, and chromosome, centromeric region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where clomipramine is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

12787it [43:23,  5.20it/s]

true
Determine whether the semantic relation where Leigh disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

12788it [43:23,  5.12it/s]

true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, has natural reservoir is the predicate, and Rodent is the object constitutes an accurate semantic relation.

12790it [43:23,  4.67it/s]

true
Determine whether the semantic relation where salmonellosis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fatty liver disease is the subject, subclass of is the predicate, and lipid storage disease is the object constitutes an accurate semantic relation.

12792it [43:24,  4.75it/s]

false
Determine whether the semantic relation where complement component 5a is the subject, instance of is the predicate, and glycopeptide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where desipramine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

12794it [43:24,  5.06it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Colombia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sarcoidosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

12796it [43:24,  5.22it/s]

maybe
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Brassica napus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Colombia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

12797it [43:25,  4.21it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

12799it [43:25,  4.65it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Addison's disease is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

12801it [43:26,  4.95it/s]

true
Determine whether the semantic relation where agar is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where baseball is the subject, country of origin is the predicate, and United States is the object constitutes an accurate semantic relation.

12803it [43:26,  5.19it/s]

true
Determine whether the semantic relation where solute carrier family 7 member 5 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Guatemala is the object constitutes an accurate semantic relation.

12805it [43:26,  5.11it/s]

true
Determine whether the semantic relation where Pyroglutamyl-peptidase I is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pyroglutamyl-peptidase I is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

12807it [43:27,  5.15it/s]

true
Determine whether the semantic relation where Guatemala is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where borate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12809it [43:27,  5.00it/s]

true
Determine whether the semantic relation where goiter is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholic acid is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

12811it [43:28,  5.20it/s]

false
Determine whether the semantic relation where cetirizine is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where plague is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

12813it [43:28,  5.04it/s]

true
Determine whether the semantic relation where Kyasanur forest disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where benzoic acid is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

12814it [43:28,  5.04it/s]

false
Determine whether the semantic relation where ulcerative colitis is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

12816it [43:29,  4.89it/s]

true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and ulcerative colitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Epstein–Barr virus infection is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

12817it [43:29,  4.91it/s]

false
Determine whether the semantic relation where HIV/AIDS is the subject, symptoms and signs is the predicate, and chills is the object constitutes an accurate semantic relation.

12818it [43:29,  4.85it/s]

true
Determine whether the semantic relation where classical conditioning is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.

12819it [43:29,  4.66it/s]

true
Determine whether the semantic relation where classical conditioning is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.

12820it [43:29,  4.60it/s]

true
Determine whether the semantic relation where protein tyrosine phosphatase non-receptor type 6 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

12821it [43:30,  4.53it/s]

false
Determine whether the semantic relation where cholecystokinin is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

12823it [43:30,  4.79it/s]

false
Determine whether the semantic relation where tilidine is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where echolalia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

12825it [43:30,  5.09it/s]

false
Determine whether the semantic relation where sirolimus is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenylketonuria is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12826it [43:31,  5.10it/s]

true
Determine whether the semantic relation where stable angina is the subject, risk factor is the predicate, and hyperlipidemia is the object constitutes an accurate semantic relation.

12828it [43:31,  5.12it/s]

false
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

12830it [43:31,  5.05it/s]

true
Determine whether the semantic relation where cycloserine is the subject, medical condition treated is the predicate, and Gaucher's disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where propolis is the subject, has use is the predicate, and anthelmintic is the object constitutes an accurate semantic relation.

12831it [43:32,  4.86it/s]

true
Determine whether the semantic relation where Caspase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12832it [43:32,  4.56it/s]

false
Determine whether the semantic relation where diuron is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

12834it [43:32,  4.80it/s]

true
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and mental confusion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vaginal discharge is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.

12835it [43:33,  4.57it/s]

false
Determine whether the semantic relation where Gaucher's disease is the subject, drug or therapy used for treatment is the predicate, and cycloserine is the object constitutes an accurate semantic relation.

12837it [43:33,  4.82it/s]

false
Determine whether the semantic relation where neurochemistry is the subject, subclass of is the predicate, and organic chemistry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbonic anhydrase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12839it [43:33,  4.94it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 1 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.

12840it [43:34,  5.10it/s]

true
Determine whether the semantic relation where homophobia is the subject, subclass of is the predicate, and bias is the object constitutes an accurate semantic relation.

12842it [43:34,  4.99it/s]

true
Determine whether the semantic relation where rutin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major histocompatibility complex, class II, DR alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12843it [43:34,  5.00it/s]

true
Determine whether the semantic relation where tick-borne encephalitis is the subject, drug or therapy used for treatment is the predicate, and ribonuclease is the object constitutes an accurate semantic relation.

12844it [43:34,  4.90it/s]

false
Determine whether the semantic relation where myalgic encephalomyelitis/chronic fatigue syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12846it [43:35,  4.97it/s]

true
Determine whether the semantic relation where heart failure is the subject, risk factor is the predicate, and diabetes is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where protein engineering is the subject, subclass of is the predicate, and bioengineering is the object constitutes an accurate semantic relation.

12848it [43:35,  5.17it/s]

true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sparganosis is the subject, symptoms and signs is the predicate, and exophthalmos is the object constitutes an accurate semantic relation.

12849it [43:35,  5.19it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

12851it [43:36,  5.08it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 1,4-alpha-glucan branching enzyme 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12852it [43:36,  5.27it/s]

false
Determine whether the semantic relation where Babesiosis is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.

12854it [43:36,  5.26it/s]

true
Determine whether the semantic relation where citrate synthase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitroprusside is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.

12855it [43:36,  5.42it/s]

true
Determine whether the semantic relation where ankylosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12857it [43:37,  5.16it/s]

true
Determine whether the semantic relation where congenital rubella syndrome is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where extrahepatic cholestasis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

12858it [43:37,  5.07it/s]

true
Determine whether the semantic relation where Adnexal and skin appendage neoplasms is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12859it [43:37,  4.99it/s]

true
Determine whether the semantic relation where granuloma inguinale is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

12860it [43:37,  4.97it/s]

true
Determine whether the semantic relation where 2'-deoxyguanosine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

12861it [43:38,  4.24it/s]

false
Determine whether the semantic relation where steroid 5-alpha reductase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

12863it [43:38,  4.59it/s]

true
Determine whether the semantic relation where transcription factor AP-1 complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dental public health is the subject, subclass of is the predicate, and public health is the object constitutes an accurate semantic relation.

12864it [43:38,  4.78it/s]

true
Determine whether the semantic relation where Medical Subject Headings is the subject, main subject is the predicate, and medicine is the object constitutes an accurate semantic relation.

12865it [43:39,  4.65it/s]

false
Determine whether the semantic relation where respiratory alkalosis is the subject, health specialty is the predicate, and intensive care medicine is the object constitutes an accurate semantic relation.

12867it [43:39,  4.88it/s]

false
Determine whether the semantic relation where DNA damage inducible transcript 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 8 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

12868it [43:39,  4.46it/s]

false
Determine whether the semantic relation where Luchelli is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

12869it [43:40,  3.96it/s]

false
Determine whether the semantic relation where neurogranin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

12870it [43:40,  4.15it/s]

true
Determine whether the semantic relation where Cathepsin D is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12871it [43:40,  4.34it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

12872it [43:40,  4.29it/s]

false
Determine whether the semantic relation where nephrotic syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

12873it [43:40,  4.45it/s]

true
Determine whether the semantic relation where migraine is the subject, possible treatment is the predicate, and monoclonal antibody is the object constitutes an accurate semantic relation.

12875it [43:41,  4.69it/s]

true
Determine whether the semantic relation where chronic kidney disease-mineral and bone disorder is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myocardial infarction is the subject, drug or therapy used for treatment is the predicate, and pindolol is the object constitutes an accurate semantic relation.

12876it [43:41,  4.71it/s]

false
Determine whether the semantic relation where adenosine diphosphate ribose is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

12877it [43:41,  4.75it/s]

false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

12878it [43:41,  4.74it/s]

true
Determine whether the semantic relation where Byzantine Empire is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.

12880it [43:42,  4.97it/s]

false
Determine whether the semantic relation where pindolol is the subject, medical condition treated is the predicate, and myocardial infarction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vitamin A is the subject, subject has role is the predicate, and free radical scavengers is the object constitutes an accurate semantic relation.

12881it [43:42,  4.72it/s]

true
Determine whether the semantic relation where social determinants of health is the subject, subclass of is the predicate, and public health is the object constitutes an accurate semantic relation.

12883it [43:43,  4.86it/s]

true
Determine whether the semantic relation where hymenolepiasis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteonecrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12885it [43:43,  5.05it/s]

true
Determine whether the semantic relation where duodenal ulcer is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methyltestosterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12886it [43:43,  5.18it/s]

true
Determine whether the semantic relation where L-leucine is the subject, part of is the predicate, and gluten is the object constitutes an accurate semantic relation.

12887it [43:43,  4.82it/s]

false
Determine whether the semantic relation where Egypt is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.

12888it [43:44,  4.62it/s]

false
Determine whether the semantic relation where keratin 10 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

12889it [43:44,  4.71it/s]

false
Determine whether the semantic relation where polycythemia vera is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12891it [43:44,  4.72it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucagon is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

12893it [43:45,  5.13it/s]

false
Determine whether the semantic relation where neutron is the subject, interaction is the predicate, and gravity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mediator complex subunit 1 is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

12894it [43:45,  5.04it/s]

false
Determine whether the semantic relation where Czech Republic is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

12895it [43:45,  4.79it/s]

true
Determine whether the semantic relation where L-leucine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

12897it [43:45,  5.00it/s]

false
Determine whether the semantic relation where electrical injury is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where postpartum thyroiditis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12899it [43:46,  4.98it/s]

true
Determine whether the semantic relation where lacunar stroke is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anesthesia and analgesia is the subject, facet of is the predicate, and therapy is the object constitutes an accurate semantic relation.

12900it [43:46,  5.13it/s]

true
Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

12902it [43:46,  5.13it/s]

false
Determine whether the semantic relation where Belgium is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Toll-like receptor 8 is the subject, subclass of is the predicate, and RNA-binding proteins is the object constitutes an accurate semantic relation.

12904it [43:47,  5.11it/s]

false
Determine whether the semantic relation where California encephalitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and bradycardia is the object constitutes an accurate semantic relation.

12905it [43:47,  5.13it/s]

false
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Northern Ireland is the object constitutes an accurate semantic relation.

12907it [43:47,  4.83it/s]

false
Determine whether the semantic relation where acrylamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uncertainty is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.

12909it [43:48,  5.03it/s]

true
Determine whether the semantic relation where uncertainty is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where multiple sclerosis is the subject, drug or therapy used for treatment is the predicate, and (RS)-cyclophosphamide is the object constitutes an accurate semantic relation.

12910it [43:48,  5.06it/s]

true
Determine whether the semantic relation where hemophilia B is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

12911it [43:48,  4.89it/s]

true
Determine whether the semantic relation where (RS)-cyclophosphamide is the subject, medical condition treated is the predicate, and multiple sclerosis is the object constitutes an accurate semantic relation.

12912it [43:48,  4.87it/s]

true
Determine whether the semantic relation where sn-glycero-3-phosphocholine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12914it [43:49,  4.69it/s]

false
Determine whether the semantic relation where (4RS)-4-hydroxy-DL-proline is the subject, subclass of is the predicate, and pyrrolidine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic condition is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.

12916it [43:49,  4.91it/s]

false
Determine whether the semantic relation where calcium hydroxide is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitro compound is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

12918it [43:50,  5.12it/s]

true
Determine whether the semantic relation where bismuth is the subject, medical condition treated is the predicate, and Escherichia coli infectious disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rosa is the subject, subclass of is the predicate, and food plant is the object constitutes an accurate semantic relation.

12920it [43:50,  5.31it/s]

true
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hair diseases is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

12922it [43:50,  5.29it/s]

false
Determine whether the semantic relation where phlebotomus fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Escherichia coli infectious disease is the subject, drug or therapy used for treatment is the predicate, and bismuth is the object constitutes an accurate semantic relation.

12924it [43:51,  5.10it/s]

true
Determine whether the semantic relation where HIV/AIDS is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where foreign body is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

12926it [43:51,  5.13it/s]

false
Determine whether the semantic relation where amine is the subject, different from is the predicate, and ammonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ammonia is the subject, different from is the predicate, and amine is the object constitutes an accurate semantic relation.

12928it [43:52,  5.30it/s]

true
Determine whether the semantic relation where gastrointestinal tuberculosis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tabes dorsalis is the subject, drug or therapy used for treatment is the predicate, and glucocorticoid is the object constitutes an accurate semantic relation.

12930it [43:52,  5.32it/s]

false
Determine whether the semantic relation where myocarditis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

12932it [43:52,  5.13it/s]

false
Determine whether the semantic relation where Italy is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where milk allergy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12933it [43:53,  5.12it/s]

true
Determine whether the semantic relation where integrin alpha3beta1 [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

12935it [43:53,  4.78it/s]

true
Determine whether the semantic relation where osteonecrosis of the femoral head is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD14 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12936it [43:53,  4.61it/s]

true
Determine whether the semantic relation where arteriovenous malformation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12937it [43:53,  4.40it/s]

true
Determine whether the semantic relation where autism is the subject, does not have cause is the predicate, and vaccine is the object constitutes an accurate semantic relation.

12939it [43:54,  4.72it/s]

true
Determine whether the semantic relation where rutin is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where subacute sclerosing panencephalitis is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

12941it [43:54,  4.99it/s]

false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

12942it [43:54,  5.11it/s]

true
Determine whether the semantic relation where L-tyrosine is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.

12943it [43:55,  5.00it/s]

false
Determine whether the semantic relation where hydroxyeicosatetraenoic acid is the subject, subclass of is the predicate, and organic compound is the object constitutes an accurate semantic relation.

12945it [43:55,  5.10it/s]

true
Determine whether the semantic relation where indican is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium carbonate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

12946it [43:55,  4.61it/s]

true
Determine whether the semantic relation where lanosterol is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

12948it [43:56,  4.66it/s]

false
Determine whether the semantic relation where bronchitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bronchitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12950it [43:56,  4.76it/s]

true
Determine whether the semantic relation where chromophobe adenoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gallic acid is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.

12952it [43:57,  4.91it/s]

true
Determine whether the semantic relation where tularemia is the subject, anatomical location is the predicate, and pleura is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Amylo-alpha-1, 6-glucosidase, 4-alpha-glucanotransferase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

12953it [43:57,  4.50it/s]

false
Determine whether the semantic relation where occludin is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

12955it [43:57,  4.82it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Chile is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where papain is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12956it [43:57,  4.91it/s]

true
Determine whether the semantic relation where Chile is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

12958it [43:58,  4.83it/s]

true
Determine whether the semantic relation where criminal is the subject, instance of is the predicate, and social class is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Klippel–Trénaunay–Weber syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

12960it [43:58,  4.94it/s]

false
Determine whether the semantic relation where cholesterol is the subject, found in taxon is the predicate, and Xestospongia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyclin dependent kinase 4 is the subject, cell component is the predicate, and chromatin is the object constitutes an accurate semantic relation.

12961it [43:58,  4.87it/s]

true
Determine whether the semantic relation where Teschen disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

12962it [43:59,  4.87it/s]

true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and facial dermatosis is the object constitutes an accurate semantic relation.

12963it [43:59,  4.85it/s]

false
Determine whether the semantic relation where facial dermatosis is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

12964it [43:59,  4.87it/s]

true
Determine whether the semantic relation where Interleukin 18 receptor accessory protein is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

12965it [43:59,  4.75it/s]

false
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, biological process is the predicate, and pigmentation is the object constitutes an accurate semantic relation.

12966it [43:59,  4.77it/s]

false
Determine whether the semantic relation where von Willebrand's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12968it [44:00,  4.84it/s]

true
Determine whether the semantic relation where bowel obstruction is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where major histocompatibility complex, class I, G is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

12970it [44:00,  5.08it/s]

true
Determine whether the semantic relation where activated leukocyte cell adhesion molecule is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Phenylethanolamine N-methyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

12971it [44:00,  5.21it/s]

true
Determine whether the semantic relation where olfactory nerve disease is the subject, subclass of is the predicate, and encephalopathy is the object constitutes an accurate semantic relation.

12972it [44:01,  4.85it/s]

false
Determine whether the semantic relation where veterinary medicine is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

12973it [44:01,  4.77it/s]

true
Determine whether the semantic relation where migraine is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

12975it [44:01,  4.99it/s]

true
Determine whether the semantic relation where migraine is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Republic of the Congo is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

12976it [44:01,  5.04it/s]

true
Determine whether the semantic relation where DL-homocysteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

12978it [44:02,  5.02it/s]

true
Determine whether the semantic relation where intercellular adhesion molecule 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Republic of the Congo is the object constitutes an accurate semantic relation.

12980it [44:02,  5.13it/s]

true
Determine whether the semantic relation where abdominal hernia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angioedema is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12982it [44:03,  5.35it/s]

true
Determine whether the semantic relation where Rotaviral gastroenteritis is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and laryngitis is the object constitutes an accurate semantic relation.

12984it [44:03,  5.15it/s]

true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where major histocompatibility complex, class I, G is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

12985it [44:03,  5.19it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

12987it [44:04,  5.20it/s]

true
Determine whether the semantic relation where musculoskeletal physiological phenomena is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

12989it [44:04,  5.23it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase kinase 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where insulin resistance is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

12991it [44:04,  5.29it/s]

false
Determine whether the semantic relation where neoplasm of oropharynx is the subject, subclass of is the predicate, and respiratory disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neuroleptic malignant syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

12992it [44:05,  5.06it/s]

true
Determine whether the semantic relation where soman is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.

12994it [44:05,  4.87it/s]

true
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cutis laxa is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

12996it [44:05,  4.95it/s]

true
Determine whether the semantic relation where myoclonic epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where γ-aminobutyric acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

12997it [44:06,  4.83it/s]

true
Determine whether the semantic relation where nordazepam is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

12999it [44:06,  4.64it/s]

false
Determine whether the semantic relation where adenine is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where corticotropin releasing hormone is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

13000it [44:06,  4.86it/s]

false
Determine whether the semantic relation where alloxan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13002it [44:07,  4.68it/s]

false
Determine whether the semantic relation where POU class 2 homeobox 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and hemoptysis is the object constitutes an accurate semantic relation.

13004it [44:07,  5.00it/s]

true
Determine whether the semantic relation where Croatia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where duodenitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13006it [44:08,  5.06it/s]

true
Determine whether the semantic relation where inducible T cell costimulator is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clonorchiasis is the subject, has natural reservoir is the predicate, and Canidae is the object constitutes an accurate semantic relation.

13008it [44:08,  5.16it/s]

false
Determine whether the semantic relation where complement C3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
maybe

13009it [44:08,  5.12it/s]

Determine whether the semantic relation where lymphogranuloma venereum is the subject, symptoms and signs is the predicate, and abscess is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Aortopulmonary septal defect is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

13010it [44:08,  5.07it/s]

false
Determine whether the semantic relation where artificial intelligence is the subject, influenced by is the predicate, and philosophy is the object constitutes an accurate semantic relation.

13012it [44:09,  5.14it/s]

true
Determine whether the semantic relation where glycerol is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vimentin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13014it [44:09,  5.35it/s]

false
Determine whether the semantic relation where mimosine is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Secretagogin, EF-hand calcium binding protein is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13016it [44:09,  5.28it/s]

false
Determine whether the semantic relation where RAB2A, member RAS oncogene family is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false

13017it [44:10,  5.36it/s]

Determine whether the semantic relation where triphenylmethyl compound is the subject, subclass of is the predicate, and polycyclic compound is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

13018it [44:10,  5.43it/s]

true
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

13020it [44:10,  4.70it/s]

true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and lisuride is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hypersomnia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13022it [44:11,  5.06it/s]

true
Determine whether the semantic relation where nitrilotriacetic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypoxanthine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

13023it [44:11,  5.04it/s]

false
Determine whether the semantic relation where trichinosis is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

13025it [44:11,  5.01it/s]

true
Determine whether the semantic relation where phospholipase A2 group IB is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phospholipase A2 group IB is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

13027it [44:12,  5.25it/s]

true
Determine whether the semantic relation where mpox is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alloy is the subject, subclass of is the predicate, and solution is the object constitutes an accurate semantic relation.

13029it [44:12,  5.42it/s]

true
Determine whether the semantic relation where DNA polymerase beta is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fatigue is the subject, medical examination is the predicate, and physical examination is the object constitutes an accurate semantic relation.

13031it [44:12,  5.31it/s]

false
Determine whether the semantic relation where yellow fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isopropylidenediphenyl bisoxyhydroxypropyl methacrylate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13033it [44:13,  5.24it/s]

true
Determine whether the semantic relation where alcoholic neuropathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where alcoholic neuropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13035it [44:13,  5.40it/s]

true
Determine whether the semantic relation where glyoxal is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cementoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13037it [44:14,  5.15it/s]

true
Determine whether the semantic relation where skin disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Primary autonomic failure is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13038it [44:14,  5.05it/s]

true
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.

13040it [44:14,  4.96it/s]

true
Determine whether the semantic relation where sulindac is the subject, has part(s) is the predicate, and fluorine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Iran is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13041it [44:14,  4.95it/s]

true
Determine whether the semantic relation where doxycycline is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

13043it [44:15,  4.87it/s]

true
Determine whether the semantic relation where New Hampshire is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where New Hampshire is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

13045it [44:15,  5.09it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methylprednisolone is the subject, medical condition treated is the predicate, and contact dermatitis is the object constitutes an accurate semantic relation.

13046it [44:15,  4.94it/s]

true
Determine whether the semantic relation where contact dermatitis is the subject, drug or therapy used for treatment is the predicate, and methylprednisolone is the object constitutes an accurate semantic relation.

13048it [44:16,  4.90it/s]

true
Determine whether the semantic relation where skin and connective tissue diseases is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Histamine receptor H1 is the subject, physically interacts with is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

13050it [44:16,  5.25it/s]

true
Determine whether the semantic relation where haloperidol is the subject, physically interacts with is the predicate, and Histamine receptor H1 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where data mining is the subject, subclass of is the predicate, and statistics is the object constitutes an accurate semantic relation.

13052it [44:16,  5.35it/s]

true
Determine whether the semantic relation where bezoar is the subject, facet of is the predicate, and digestion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where delirium is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13054it [44:17,  5.33it/s]

true
Determine whether the semantic relation where Interleukin 15 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SRC proto-oncogene, non-receptor tyrosine kinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13056it [44:17,  5.32it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mauritius is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13057it [44:17,  4.99it/s]

true
Determine whether the semantic relation where tooth mobility is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

13059it [44:18,  4.98it/s]

false
Determine whether the semantic relation where DL-glyceraldehyde is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pravastatin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

13061it [44:18,  5.26it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pentoxifylline is the subject, medical condition treated is the predicate, and cerebrovascular disease is the object constitutes an accurate semantic relation.

13063it [44:19,  5.20it/s]

true
Determine whether the semantic relation where Coagulation factor II, thrombin is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where betahistine is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

13065it [44:19,  5.10it/s]

false
Determine whether the semantic relation where Glycyrrhiza uralensis is the subject, has use is the predicate, and food is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where large-cell immunoblastic lymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13067it [44:19,  5.21it/s]

true
Determine whether the semantic relation where hepatocellular adenoma is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Equatorial Guinea is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

13068it [44:20,  5.38it/s]

true
Determine whether the semantic relation where canthaxanthin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13070it [44:20,  5.10it/s]

true
Determine whether the semantic relation where antiphospholipid syndrome is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary blastoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13072it [44:20,  5.16it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Equatorial Guinea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perimeningeal infections is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13074it [44:21,  5.21it/s]

true
Determine whether the semantic relation where Yugoslavia is the subject, continent is the predicate, and Europe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13076it [44:21,  4.94it/s]

true
Determine whether the semantic relation where dactinomycin is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where D-glucouronic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13078it [44:22,  5.15it/s]

true
Determine whether the semantic relation where aortic valve stenosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 15 receptor subunit alpha is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

13080it [44:22,  5.37it/s]

false
Determine whether the semantic relation where back pain is the subject, has cause is the predicate, and injury is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EPH receptor A2 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

13082it [44:22,  5.34it/s]

true
Determine whether the semantic relation where O-6-methylguanine-DNA methyltransferase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pica is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13083it [44:23,  5.35it/s]

true
Determine whether the semantic relation where myocardial infarction is the subject, drug or therapy used for treatment is the predicate, and nadolol is the object constitutes an accurate semantic relation.

13085it [44:23,  5.11it/s]

true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nadolol is the subject, medical condition treated is the predicate, and myocardial infarction is the object constitutes an accurate semantic relation.

13086it [44:23,  4.95it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

13088it [44:24,  5.09it/s]

true
Determine whether the semantic relation where gum arabic is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemoglobinuria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13090it [44:24,  4.42it/s]

true
Determine whether the semantic relation where Panama is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rickets is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

13092it [44:24,  4.93it/s]

false
Determine whether the semantic relation where dentinal fluid is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where substernal goiter is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13093it [44:25,  5.12it/s]

true
Determine whether the semantic relation where North America is the subject, country is the predicate, and Panama is the object constitutes an accurate semantic relation.

13095it [44:25,  5.01it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where liver function test is the subject, subclass of is the predicate, and clinical chemistry is the object constitutes an accurate semantic relation.

13097it [44:25,  4.94it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13099it [44:26,  5.06it/s]

false
Determine whether the semantic relation where premelanosome protein is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where subcutaneous emphysema is the subject, symptoms and signs is the predicate, and dysphagia is the object constitutes an accurate semantic relation.

13101it [44:26,  5.02it/s]

false
Determine whether the semantic relation where biology is the subject, instance of is the predicate, and science is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where normal pressure hydrocephalus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13103it [44:27,  5.23it/s]

true
Determine whether the semantic relation where normal pressure hydrocephalus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where collagen type III trimer is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

13105it [44:27,  5.12it/s]

false
Determine whether the semantic relation where cerebral infarction is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Algeria is the object constitutes an accurate semantic relation.

13107it [44:27,  5.23it/s]

true
Determine whether the semantic relation where Calbindin 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where signal transducer and activator of transcription 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13109it [44:28,  5.36it/s]

true
Determine whether the semantic relation where heme oxygenase 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where SRY is the subject, expressed in is the predicate, and placenta is the object constitutes an accurate semantic relation.

13110it [44:28,  5.39it/s]

false
Determine whether the semantic relation where frontotemporal dementia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13112it [44:28,  5.09it/s]

true
Determine whether the semantic relation where tyrosine kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where clotting time is the subject, instance of is the predicate, and blood test is the object constitutes an accurate semantic relation.

13113it [44:29,  5.02it/s]

false
Determine whether the semantic relation where Lymphotoxin beta receptor is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

13115it [44:29,  5.09it/s]

false
Determine whether the semantic relation where aggrecan is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nutrition is the subject, contributing factor of is the predicate, and metabolism is the object constitutes an accurate semantic relation.

13117it [44:29,  5.32it/s]

true
Determine whether the semantic relation where metabolism is the subject, has contributing factor is the predicate, and nutrition is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pernicious anemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13118it [44:29,  5.43it/s]

true
Determine whether the semantic relation where immunoglobulin therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

13120it [44:30,  5.20it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, route of administration is the predicate, and Q10268830 is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where resorcin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13122it [44:30,  5.20it/s]

true
Determine whether the semantic relation where Lyme disease is the subject, symptoms and signs is the predicate, and heart arrhythmia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Czech Republic is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13123it [44:30,  5.31it/s]

true
Determine whether the semantic relation where glial fibrillary acidic protein is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

13125it [44:31,  5.30it/s]

false
Determine whether the semantic relation where Q18388377 is the subject, subclass of is the predicate, and excipient is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Secretogranin II is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13127it [44:31,  5.31it/s]

true
Determine whether the semantic relation where malaria is the subject, disease transmission process is the predicate, and blood transfusion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

13129it [44:32,  5.37it/s]

false
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, cell component is the predicate, and caveola is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and South Africa is the object constitutes an accurate semantic relation.

13131it [44:32,  5.09it/s]

false
Determine whether the semantic relation where C-X-C motif chemokine receptor 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mercury poisoning is the subject, route of administration is the predicate, and Q10268830 is the object constitutes an accurate semantic relation.

13133it [44:32,  5.29it/s]

false
Determine whether the semantic relation where (E)-phytonadione is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where X-linked inhibitor of apoptosis is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13135it [44:33,  5.28it/s]

true
Determine whether the semantic relation where medical error is the subject, facet of is the predicate, and health care quality is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where motor neuron disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13137it [44:33,  5.30it/s]

true
Determine whether the semantic relation where coformycin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neuroscience is the subject, partially coincident with is the predicate, and robotics is the object constitutes an accurate semantic relation.

13139it [44:34,  5.11it/s]

maybe
Determine whether the semantic relation where organic compound is the subject, opposite of is the predicate, and inorganic compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inorganic compound is the subject, opposite of is the predicate, and organic compound is the object constitutes an accurate semantic relation.

13141it [44:34,  5.21it/s]

true
Determine whether the semantic relation where autism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where retinal vasculitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

13143it [44:34,  5.19it/s]

true
Determine whether the semantic relation where Q7540 is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 1,2-dibromoethane is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

13145it [44:35,  5.14it/s]

true
Determine whether the semantic relation where Cathepsin G is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phospholipase A2 group III is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13147it [44:35,  5.08it/s]

false
Determine whether the semantic relation where chromium is the subject, subclass of is the predicate, and allergen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Erb-b2 receptor tyrosine kinase 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13149it [44:35,  5.17it/s]

true
Determine whether the semantic relation where sialadenitis is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glutamic-pyruvic transaminase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13151it [44:36,  5.13it/s]

true
Determine whether the semantic relation where case-control study is the subject, subclass of is the predicate, and observational study is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rickets is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13153it [44:36,  5.21it/s]

true
Determine whether the semantic relation where Cronkhite-Canada syndrome is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pyridoxine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13155it [44:37,  5.25it/s]

true
Determine whether the semantic relation where brucellosis is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mammuthus is the subject, location of discovery is the predicate, and Europe is the object constitutes an accurate semantic relation.

13156it [44:37,  5.04it/s]

true
Determine whether the semantic relation where varicose veins is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13157it [44:37,  4.95it/s]

true
Determine whether the semantic relation where varicose veins is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13159it [44:37,  4.90it/s]

true
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ehrlichiosis is the subject, drug or therapy used for treatment is the predicate, and chloramphenicol is the object constitutes an accurate semantic relation.

13161it [44:38,  4.62it/s]

false
Determine whether the semantic relation where epidermoid cyst is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 7 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13163it [44:38,  5.02it/s]

false
Determine whether the semantic relation where Rac family small GTPase 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nitrofurazone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13165it [44:39,  5.16it/s]

true
Determine whether the semantic relation where actinobacillosis is the subject, subclass of is the predicate, and respiratory disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where liver cirrhosis is the subject, medical examination is the predicate, and blood test is the object constitutes an accurate semantic relation.

13166it [44:39,  4.45it/s]

false
Determine whether the semantic relation where calcium pyrophosphate is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

13167it [44:39,  4.58it/s]

true
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and dysphagia is the object constitutes an accurate semantic relation.

13169it [44:40,  4.76it/s]

true
Determine whether the semantic relation where clonorchiasis is the subject, symptoms and signs is the predicate, and hepatitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paracetamol is the subject, significant drug interaction is the predicate, and propranolol is the object constitutes an accurate semantic relation.

13171it [44:40,  5.04it/s]

false
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ribonucleic acid is the subject, has part(s) is the predicate, and ribonucleotide is the object constitutes an accurate semantic relation.

13173it [44:40,  5.25it/s]

true
Determine whether the semantic relation where acrolein is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

13174it [44:41,  5.17it/s]

true
Determine whether the semantic relation where central nervous system bacterial infection is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13176it [44:41,  5.12it/s]

true
Determine whether the semantic relation where tuberculous meningitis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Coagulation factor VIII is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13178it [44:41,  5.35it/s]

true
Determine whether the semantic relation where apyrase family is the subject, subclass of is the predicate, and calcium-binding proteins is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where isopropyl alcohol is the subject, has use is the predicate, and insecticide is the object constitutes an accurate semantic relation.

13179it [44:41,  5.37it/s]

false
Determine whether the semantic relation where monosodium L-glutamate is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.

13181it [44:42,  5.22it/s]

true
Determine whether the semantic relation where stretcher is the subject, item operated is the predicate, and patient is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where stretcher is the subject, carries passengers or cargo is the predicate, and patient is the object constitutes an accurate semantic relation.

13183it [44:42,  5.28it/s]

true
Determine whether the semantic relation where Natriuretic peptide A is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovakia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13185it [44:43,  5.36it/s]

true
Determine whether the semantic relation where anencephaly is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arteriosclerosis is the subject, has cause is the predicate, and obesity is the object constitutes an accurate semantic relation.

13187it [44:43,  5.02it/s]

true
Determine whether the semantic relation where mitral valve prolapse is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Keratin 1 is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

13188it [44:43,  5.04it/s]

false
Determine whether the semantic relation where animal protozoan infections is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

13190it [44:44,  4.94it/s]

true
Determine whether the semantic relation where Interleukin 12A is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 10 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13192it [44:44,  4.99it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 5A is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mucin 5AC, oligomeric mucus/gel-forming is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

13194it [44:44,  5.13it/s]

false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Symbolism is the subject, country is the predicate, and Belgium is the object constitutes an accurate semantic relation.

13196it [44:45,  5.15it/s]

false
Determine whether the semantic relation where cobalt is the subject, subject has role is the predicate, and allergen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sulfur hexafluoride is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

13197it [44:45,  5.25it/s]

true
Determine whether the semantic relation where New Zealand is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

13199it [44:45,  4.75it/s]

true
Determine whether the semantic relation where chancroid is the subject, anatomical location is the predicate, and sex organ is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

13200it [44:46,  4.82it/s]

true
Determine whether the semantic relation where FES proto-oncogene, tyrosine kinase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13202it [44:46,  4.80it/s]

false
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where niacinamide is the subject, subject has role is the predicate, and enzyme activator is the object constitutes an accurate semantic relation.

13204it [44:46,  5.17it/s]

false
Determine whether the semantic relation where Glutamate metabotropic receptor 5 is the subject, biological process is the predicate, and cognition is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sodium azide is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

13206it [44:47,  5.22it/s]

true
Determine whether the semantic relation where central nervous system neoplasm is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glutamic-oxaloacetic transaminase 2 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

13207it [44:47,  5.08it/s]

true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13208it [44:47,  4.63it/s]

true
Determine whether the semantic relation where Dual specificity phosphatase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13209it [44:48,  4.42it/s]

true
Determine whether the semantic relation where Dopamine receptor D4 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

13211it [44:48,  4.37it/s]

false
Determine whether the semantic relation where embolism is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 15 is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.

13213it [44:48,  4.81it/s]

false
Determine whether the semantic relation where cytomegaloviral disease is the subject, symptoms and signs is the predicate, and holoprosencephaly is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where growth hormone secreting pituitary adenoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

13214it [44:49,  4.98it/s]

true
Determine whether the semantic relation where West Nile fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

13215it [44:49,  4.74it/s]

true
Determine whether the semantic relation where pleasure is the subject, opposite of is the predicate, and pain is the object constitutes an accurate semantic relation.

13216it [44:49,  4.40it/s]

true
Determine whether the semantic relation where calcium sensing receptor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13218it [44:49,  4.76it/s]

true
Determine whether the semantic relation where editorial policy is the subject, subclass of is the predicate, and policy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tokyo is the subject, twinned administrative body is the predicate, and Berlin is the object constitutes an accurate semantic relation.

13220it [44:50,  5.09it/s]

true
Determine whether the semantic relation where Belarus is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pharmacologic action is the subject, facet of is the predicate, and pharmacology is the object constitutes an accurate semantic relation.

13221it [44:50,  5.00it/s]

false
Determine whether the semantic relation where pain is the subject, opposite of is the predicate, and pleasure is the object constitutes an accurate semantic relation.

13223it [44:50,  4.95it/s]

true
Determine whether the semantic relation where leprosy is the subject, symptoms and signs is the predicate, and contracture is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Berlin is the subject, twinned administrative body is the predicate, and Tokyo is the object constitutes an accurate semantic relation.

13225it [44:51,  5.34it/s]

true
Determine whether the semantic relation where CD40 ligand is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where periodontal attachment loss is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

13227it [44:51,  5.41it/s]

false
Determine whether the semantic relation where Calbindin 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where progesterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13228it [44:51,  5.40it/s]

true
Determine whether the semantic relation where cefamandole is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

13230it [44:52,  5.11it/s]

false
Determine whether the semantic relation where Protein-L-isoaspartate (D-aspartate) O-methyltransferase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where orotic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

13232it [44:52,  5.06it/s]

false
Determine whether the semantic relation where Growth factor receptor bound protein 10 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyyne is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13234it [44:53,  5.15it/s]

true
Determine whether the semantic relation where dioxole is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glyoxal is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13236it [44:53,  5.17it/s]

true
Determine whether the semantic relation where diarrhea is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

13237it [44:53,  5.17it/s]

Determine whether the semantic relation where Growth factor receptor bound protein 2 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cariogenic diet is the subject, instance of is the predicate, and risk factor is the object constitutes an accurate semantic relation.

13239it [44:54,  5.23it/s]

true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.

13241it [44:54,  5.16it/s]

true
Determine whether the semantic relation where vocabulary is the subject, subclass of is the predicate, and data set is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bone marrow disease is the subject, drug or therapy used for treatment is the predicate, and carboplatin is the object constitutes an accurate semantic relation.

13243it [44:54,  5.14it/s]

false
Determine whether the semantic relation where erysipelas is the subject, different from is the predicate, and rubella is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carboplatin is the subject, medical condition treated is the predicate, and bone marrow disease is the object constitutes an accurate semantic relation.

13244it [44:55,  4.91it/s]

false
Determine whether the semantic relation where CD34 molecule is the subject, biological process is the predicate, and transdifferentiation is the object constitutes an accurate semantic relation.

13246it [44:55,  4.89it/s]

false
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and procainamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where duodenal obstruction is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

13248it [44:55,  5.04it/s]

true
Determine whether the semantic relation where hemic and lymphatic diseases is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where procainamide is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

13250it [44:56,  5.28it/s]

true
Determine whether the semantic relation where normal pressure hydrocephalus is the subject, subclass of is the predicate, and nervous system heredodegenerative disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vascular endothelial growth factor D is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

13252it [44:56,  5.19it/s]

true
Determine whether the semantic relation where paired box 9 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where immunology is the subject, is the study of is the predicate, and immune system is the object constitutes an accurate semantic relation.

13253it [44:56,  5.11it/s]

true
Determine whether the semantic relation where immune system is the subject, studied by is the predicate, and immunology is the object constitutes an accurate semantic relation.

13254it [44:57,  4.97it/s]

true
Determine whether the semantic relation where observation is the subject, has part(s) is the predicate, and perception is the object constitutes an accurate semantic relation.

13255it [44:57,  4.69it/s]

false
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

13256it [44:57,  4.71it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

13257it [44:57,  4.76it/s]

true
Determine whether the semantic relation where Cyclin A1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13258it [44:57,  4.63it/s]

true
Determine whether the semantic relation where chlorphenesin is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

13260it [44:58,  4.62it/s]

false
Determine whether the semantic relation where EPH receptor B2 is the subject, biological process is the predicate, and learning is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD4 molecule is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

13262it [44:58,  4.79it/s]

false
Determine whether the semantic relation where integrin subunit alpha 2b is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sweden is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

13264it [44:59,  4.87it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Sweden is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myogenin is the subject, biological process is the predicate, and ossification is the object constitutes an accurate semantic relation.

13266it [44:59,  5.16it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and chlorphenesin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cervical rib syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13267it [44:59,  5.23it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

13269it [45:00,  5.14it/s]

true
Determine whether the semantic relation where African trypanosomiasis is the subject, medical examination is the predicate, and agglutination is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hemoglobin C is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13271it [45:00,  5.30it/s]

false
Determine whether the semantic relation where stomach neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myoclonus is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13273it [45:00,  5.30it/s]

true
Determine whether the semantic relation where vasculitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mumps is the subject, anatomical location is the predicate, and pancreas is the object constitutes an accurate semantic relation.

13275it [45:01,  5.35it/s]

false
Determine whether the semantic relation where Cannabinoid receptor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

13277it [45:01,  5.26it/s]

true
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pentostatin is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

13279it [45:02,  5.17it/s]

false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.
true

13280it [45:02,  5.32it/s]

Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Cyprus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where busulfan is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

13281it [45:02,  5.08it/s]

true
Determine whether the semantic relation where nerve growth factor is the subject, biological process is the predicate, and memory is the object constitutes an accurate semantic relation.

13282it [45:02,  5.04it/s]

false
Determine whether the semantic relation where synaptosome associated protein 25 is the subject, cell component is the predicate, and myelin sheath is the object constitutes an accurate semantic relation.

13284it [45:03,  4.99it/s]

false
Determine whether the semantic relation where Cyprus is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cellophane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13286it [45:03,  5.19it/s]

false
Determine whether the semantic relation where berylliosis is the subject, possible treatment is the predicate, and oxygen therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where linoleic acid is the subject, found in taxon is the predicate, and Aspergillus is the object constitutes an accurate semantic relation.

13287it [45:03,  5.23it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13289it [45:03,  5.08it/s]

true
Determine whether the semantic relation where Solute carrier family 5 member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diphosphate is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

13291it [45:04,  5.08it/s]

true
Determine whether the semantic relation where agranulocytosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and leukopenia is the object constitutes an accurate semantic relation.

13293it [45:04,  5.28it/s]

true
Determine whether the semantic relation where pulmonary embolism is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aristolochic acids is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

13294it [45:05,  4.82it/s]

false
Determine whether the semantic relation where health impact assessment is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

13295it [45:05,  4.79it/s]

true
Determine whether the semantic relation where (±)-promethazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

13296it [45:05,  4.49it/s]

true
Determine whether the semantic relation where endoscopy is the subject, subclass of is the predicate, and medical imaging is the object constitutes an accurate semantic relation.

13297it [45:05,  4.57it/s]

false
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Q2453469 is the object constitutes an accurate semantic relation.

13299it [45:06,  4.85it/s]

false
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Poland is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Poland is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

13300it [45:06,  5.05it/s]

true
Determine whether the semantic relation where Phospholipase A2 receptor 1 is the subject, biological process is the predicate, and endocytosis is the object constitutes an accurate semantic relation.

13302it [45:06,  5.01it/s]

true
Determine whether the semantic relation where citric acid is the subject, found in taxon is the predicate, and Camellia sinensis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DL-glutamic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13303it [45:06,  5.02it/s]

true
Determine whether the semantic relation where bleeding is the subject, subclass of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

13305it [45:07,  5.01it/s]

false
Determine whether the semantic relation where Ukraine is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where androgen-binding protein is the subject, subclass of is the predicate, and glycoprotein is the object constitutes an accurate semantic relation.

13307it [45:07,  5.12it/s]

true
Determine whether the semantic relation where Hong Kong is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CD40 molecule is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

13309it [45:08,  4.66it/s]

false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Hong Kong is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Goodpasture syndrome is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

13311it [45:08,  4.78it/s]

true
Determine whether the semantic relation where hepatitis E is the subject, symptoms and signs is the predicate, and anorexia is the object constitutes an accurate semantic relation.
true

13312it [45:08,  4.98it/s]

Determine whether the semantic relation where hydroxycarbamide is the subject, medical condition treated is the predicate, and melanoma is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.

13314it [45:09,  5.20it/s]

true
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Proteus syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

13315it [45:09,  5.28it/s]

true
Determine whether the semantic relation where dichlorvos is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

13317it [45:09,  5.10it/s]

true
Determine whether the semantic relation where melanoma is the subject, drug or therapy used for treatment is the predicate, and hydroxycarbamide is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where endothelin 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13319it [45:10,  5.14it/s]

true
Determine whether the semantic relation where pseudouridine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

13321it [45:10,  4.95it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where microvascular angina is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13323it [45:10,  4.62it/s]

true
Determine whether the semantic relation where dermatomyositis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sparganosis is the subject, symptoms and signs is the predicate, and edema is the object constitutes an accurate semantic relation.

13325it [45:11,  4.87it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, afflicts is the predicate, and central nervous system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium hypochlorite is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13326it [45:11,  4.71it/s]

true
Determine whether the semantic relation where xanthine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

13327it [45:11,  4.74it/s]

false
Determine whether the semantic relation where phlebitis is the subject, subclass of is the predicate, and venous thromboembolism is the object constitutes an accurate semantic relation.

13329it [45:12,  4.89it/s]

false
Determine whether the semantic relation where rubella is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

13330it [45:12,  4.89it/s]

true
Determine whether the semantic relation where carbohydrate is the subject, different from is the predicate, and hydrocarbon is the object constitutes an accurate semantic relation.

13332it [45:12,  4.95it/s]

true
Determine whether the semantic relation where hydrocarbon is the subject, different from is the predicate, and carbohydrate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where borderline leprosy is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

13334it [45:13,  4.79it/s]

true
Determine whether the semantic relation where unnecessary health care is the subject, facet of is the predicate, and health care quality is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urinary tract infection is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

13335it [45:13,  4.67it/s]

true
Determine whether the semantic relation where nervous system paraneoplastic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13336it [45:13,  4.59it/s]

true
Determine whether the semantic relation where delusion is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13337it [45:13,  4.68it/s]

false
Determine whether the semantic relation where delusion is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13339it [45:14,  4.42it/s]

false
Determine whether the semantic relation where spondylosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sex chromosome disorder of sex development is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13341it [45:14,  4.56it/s]

true
Determine whether the semantic relation where caprolactam is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Phenylethanolamine N-methyltransferase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13342it [45:15,  4.16it/s]

false
Determine whether the semantic relation where ocular albinism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13344it [45:15,  4.63it/s]

true
Determine whether the semantic relation where congenital nonspherocytic hemolytic anemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Fukushima Daiichi nuclear disaster is the subject, damaged is the predicate, and biodiversity is the object constitutes an accurate semantic relation.

13346it [45:15,  4.71it/s]

maybe
Determine whether the semantic relation where ileal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Melkersson-Rosenthal syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13348it [45:16,  4.97it/s]

true
Determine whether the semantic relation where hepatitis B is the subject, symptoms and signs is the predicate, and splenomegaly is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rac-salbutamol is the subject, instance of is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

13350it [45:16,  5.11it/s]

true
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and tonsillitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Georgia is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.

13352it [45:17,  5.08it/s]

true
Determine whether the semantic relation where hydrocarbon is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where botulism is the subject, possible treatment is the predicate, and enema is the object constitutes an accurate semantic relation.

13353it [45:17,  5.17it/s]

false
Determine whether the semantic relation where progeria is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

13354it [45:17,  4.71it/s]

false
Determine whether the semantic relation where heme oxygenase 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

13355it [45:17,  4.51it/s]

true
Determine whether the semantic relation where adjustment disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13356it [45:18,  4.33it/s]

true
Determine whether the semantic relation where neuropsychiatric systemic lupus erythematosus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13357it [45:18,  4.41it/s]

true
Determine whether the semantic relation where SAPHO syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13359it [45:18,  4.75it/s]

true
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 1 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.

13360it [45:18,  4.45it/s]

true
Determine whether the semantic relation where oxalic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13361it [45:19,  4.49it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Portugal is the object constitutes an accurate semantic relation.

13363it [45:19,  4.77it/s]

true
Determine whether the semantic relation where Portugal is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Oman is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

13365it [45:19,  5.05it/s]

true
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Oman is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphadenitis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

13366it [45:20,  4.92it/s]

false
Determine whether the semantic relation where ascending colon is the subject, innervated by is the predicate, and vagus nerve is the object constitutes an accurate semantic relation.

13368it [45:20,  5.09it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

13370it [45:20,  4.89it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, route of administration is the predicate, and skin absorption is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where azotemia is the subject, subclass of is the predicate, and hematopoietic system disease is the object constitutes an accurate semantic relation.

13371it [45:21,  4.48it/s]

false
Determine whether the semantic relation where Central Asia is the subject, shares border with is the predicate, and West Asia is the object constitutes an accurate semantic relation.
true

13372it [45:21,  4.62it/s]

Determine whether the semantic relation where West Asia is the subject, shares border with is the predicate, and Central Asia is the object constitutes an accurate semantic relation.

13373it [45:21,  4.66it/s]

true
Determine whether the semantic relation where World War I is the subject, located in/on physical feature is the predicate, and West Asia is the object constitutes an accurate semantic relation.

13375it [45:22,  4.66it/s]

false
Determine whether the semantic relation where Charcot–Marie–Tooth disease is the subject, medical examination is the predicate, and neurological diagnostic techniques is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and pimozide is the object constitutes an accurate semantic relation.

13377it [45:22,  4.81it/s]

true
Determine whether the semantic relation where hydrocarbon is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pimozide is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.

13379it [45:22,  4.48it/s]

true
Determine whether the semantic relation where clonorchiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Methionine-tRNA synthetase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13381it [45:23,  4.83it/s]

false
Determine whether the semantic relation where L-kynurenine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paracetamol is the subject, route of administration is the predicate, and intramuscular injection is the object constitutes an accurate semantic relation.

13383it [45:23,  5.04it/s]

false
Determine whether the semantic relation where cholesterol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where brain tumor is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13385it [45:24,  5.24it/s]

true
Determine whether the semantic relation where adenine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where C-C motif chemokine ligand 20 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

13387it [45:24,  5.27it/s]

false
Determine whether the semantic relation where meningitis is the subject, has cause is the predicate, and virus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mpox is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

13388it [45:24,  5.38it/s]

false
Determine whether the semantic relation where flavin adenine dinucleotide is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

13389it [45:24,  5.19it/s]

false
Determine whether the semantic relation where urethritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13391it [45:25,  5.13it/s]

true
Determine whether the semantic relation where L-methionine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aralkylamine N-acetyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

13392it [45:25,  5.10it/s]

true
Determine whether the semantic relation where aralkylamine N-acetyltransferase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

13394it [45:25,  4.99it/s]

true
Determine whether the semantic relation where X-linked intellectual disability is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

13396it [45:26,  5.15it/s]

true
Determine whether the semantic relation where hernia is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

13397it [45:26,  5.23it/s]

false
Determine whether the semantic relation where casein is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false

13399it [45:26,  5.22it/s]

Determine whether the semantic relation where prenatal care is the subject, subclass of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

13400it [45:27,  4.87it/s]

true
Determine whether the semantic relation where guanosine triphosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13402it [45:27,  4.90it/s]

true
Determine whether the semantic relation where sodium lactate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (+)-pseudoephedrine is the subject, medical condition treated is the predicate, and asthma is the object constitutes an accurate semantic relation.

13403it [45:27,  5.04it/s]

false
Determine whether the semantic relation where asthma is the subject, drug or therapy used for treatment is the predicate, and (+)-pseudoephedrine is the object constitutes an accurate semantic relation.

13404it [45:27,  4.76it/s]

false
Determine whether the semantic relation where diabetic nephropathy is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

13406it [45:28,  4.85it/s]

maybe
Determine whether the semantic relation where Turner syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turner syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13408it [45:28,  4.84it/s]

true
Determine whether the semantic relation where benzylpenicillin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melanoma cell adhesion molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13410it [45:29,  4.67it/s]

true
Determine whether the semantic relation where choline O-acetyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where overactive bladder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13412it [45:29,  4.95it/s]

true
Determine whether the semantic relation where zinc acetate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where poisoning is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

13413it [45:29,  4.58it/s]

true
Determine whether the semantic relation where Interleukin 12B is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

13415it [45:30,  4.61it/s]

false
Determine whether the semantic relation where Notch receptor 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cystic fibrosis is the subject, symptoms and signs is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

13417it [45:30,  5.01it/s]

true
Determine whether the semantic relation where dextroamphetamine is the subject, significant drug interaction is the predicate, and procarbazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, risk factor is the predicate, and cystic fibrosis is the object constitutes an accurate semantic relation.

13419it [45:31,  5.08it/s]

false
Determine whether the semantic relation where widowhood is the subject, instance of is the predicate, and role is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where keratin 15 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13420it [45:31,  5.25it/s]

false
Determine whether the semantic relation where exophthalmos is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13422it [45:31,  5.19it/s]

true
Determine whether the semantic relation where TNF receptor superfamily member 1A is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where organophosphate poisoning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

13424it [45:31,  5.26it/s]

true
Determine whether the semantic relation where psychological stress is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where iron responsive element binding protein 2 is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

13425it [45:32,  5.14it/s]

false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and indomethacin is the object constitutes an accurate semantic relation.

13427it [45:32,  4.88it/s]

true
Determine whether the semantic relation where pharmacist is the subject, instance of is the predicate, and health profession is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where indomethacin is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

13428it [45:32,  4.72it/s]

true
Determine whether the semantic relation where homebound person is the subject, subclass of is the predicate, and patient is the object constitutes an accurate semantic relation.

13430it [45:33,  4.78it/s]

true
Determine whether the semantic relation where paper chromatography is the subject, has part(s) is the predicate, and ethanol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where premature ovarian failure is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

13432it [45:33,  5.01it/s]

true
Determine whether the semantic relation where Prinzmetal's angina is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Histamine receptor H3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13434it [45:34,  5.04it/s]

true
Determine whether the semantic relation where Adenine phosphoribosyltransferase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arthropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13436it [45:34,  5.22it/s]

true
Determine whether the semantic relation where creatinine is the subject, subclass of is the predicate, and imidazolidine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ATP citrate lyase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13438it [45:34,  5.05it/s]

false
Determine whether the semantic relation where Nepal is the subject, religion or worldview is the predicate, and Islam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where stomatognathic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13439it [45:35,  4.79it/s]

true
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

13441it [45:35,  4.76it/s]

false
Determine whether the semantic relation where paracetamol is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Anetoderma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13443it [45:35,  4.86it/s]

true
Determine whether the semantic relation where NatA complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lesch-Nyhan syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13445it [45:36,  5.19it/s]

true
Determine whether the semantic relation where lupus anticoagulant is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nicaragua is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

13446it [45:36,  5.09it/s]

true
Determine whether the semantic relation where gram-positive bacterial infections is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

13448it [45:36,  5.06it/s]

true
Determine whether the semantic relation where ribavirin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Gabon is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

13450it [45:37,  5.26it/s]

true
Determine whether the semantic relation where North America is the subject, country is the predicate, and Nicaragua is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where minocycline is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

13452it [45:37,  5.15it/s]

false
Determine whether the semantic relation where infant respiratory distress syndrome is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where retroperitoneal fibrosis is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

13453it [45:37,  5.20it/s]

false
Determine whether the semantic relation where cyst is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13455it [45:38,  5.15it/s]

false
Determine whether the semantic relation where airway obstruction is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bulgaria is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

13457it [45:38,  5.21it/s]

true
Determine whether the semantic relation where niacinamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 1A is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13459it [45:38,  5.29it/s]

true
Determine whether the semantic relation where encephalitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCR activator of RhoGEF and GTPase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13461it [45:39,  5.26it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Bulgaria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholesterol is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

13463it [45:39,  5.23it/s]

true
Determine whether the semantic relation where optic disk drusen is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where histidine decarboxylase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13465it [45:40,  5.28it/s]

true
Determine whether the semantic relation where psoralen is the subject, subject has role is the predicate, and anthelmintic is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Solute carrier family 5 member 2 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.

13467it [45:40,  4.95it/s]

false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenylalanine hydroxylase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

13469it [45:40,  5.12it/s]

false
Determine whether the semantic relation where subarachnoid hemorrhage is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

13471it [45:41,  5.37it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 3 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbonic anhydrase 3 is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

13473it [45:41,  5.19it/s]

true
Determine whether the semantic relation where microtubule associated protein tau is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where testosterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13475it [45:42,  5.11it/s]

true
Determine whether the semantic relation where The Bahamas is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Gamma-butyrobetaine hydroxylase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13476it [45:42,  5.08it/s]

false
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

13477it [45:42,  5.01it/s]

false
Determine whether the semantic relation where LDL receptor related protein 1 is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

13478it [45:42,  4.97it/s]

false
Determine whether the semantic relation where Slovenia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

13480it [45:43,  4.82it/s]

true
Determine whether the semantic relation where staphylococcal infection is the subject, drug or therapy used for treatment is the predicate, and Cefotetan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diffuse scleroderma is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

13482it [45:43,  5.19it/s]

true
Determine whether the semantic relation where Cefotetan is the subject, medical condition treated is the predicate, and staphylococcal infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-threonine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

13483it [45:43,  5.21it/s]

false
Determine whether the semantic relation where Austria is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

13484it [45:43,  4.88it/s]

true
Determine whether the semantic relation where Protein kinase C, alpha is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

13486it [45:44,  4.11it/s]

false
Determine whether the semantic relation where yellow fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tryptophan is the subject, found in taxon is the predicate, and moringa is the object constitutes an accurate semantic relation.

13487it [45:44,  4.36it/s]

false
Determine whether the semantic relation where β-carotene is the subject, found in taxon is the predicate, and Neurospora crassa is the object constitutes an accurate semantic relation.

13489it [45:45,  4.81it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where small business is the subject, country is the predicate, and Germany is the object constitutes an accurate semantic relation.

13490it [45:45,  4.36it/s]

false
Determine whether the semantic relation where paroxetine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

13492it [45:45,  4.52it/s]

true
Determine whether the semantic relation where pseudomyxoma peritonei is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where choreatic disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13494it [45:46,  4.96it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where microtubule associated protein tau is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13496it [45:46,  5.15it/s]

false
Determine whether the semantic relation where juvenile spinal muscular atrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

13498it [45:46,  4.96it/s]

true
Determine whether the semantic relation where cyclin dependent kinase 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

13500it [45:47,  4.73it/s]

true
Determine whether the semantic relation where panniculitis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where splenomegaly is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

13502it [45:47,  5.15it/s]

false
Determine whether the semantic relation where CD79a molecule is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pyridone is the subject, subclass of is the predicate, and dihydropyridine is the object constitutes an accurate semantic relation.

13504it [45:48,  5.13it/s]

false
Determine whether the semantic relation where thymidine phosphorylase is the subject, biological process is the predicate, and chemotaxis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inclusion body myositis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

13505it [45:48,  4.78it/s]

true
Determine whether the semantic relation where encephalitis is the subject, subclass of is the predicate, and neurological symptom is the object constitutes an accurate semantic relation.

13506it [45:48,  4.82it/s]

false
Determine whether the semantic relation where longevity is the subject, instance of is the predicate, and quality of life is the object constitutes an accurate semantic relation.

13508it [45:49,  4.72it/s]

false
Determine whether the semantic relation where SMAD family member 3 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where phospholipase A2 group X is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13510it [45:49,  4.95it/s]

true
Determine whether the semantic relation where Cathepsin B is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanidine is the subject, subclass of is the predicate, and amine is the object constitutes an accurate semantic relation.

13512it [45:49,  5.12it/s]

false
Determine whether the semantic relation where Crohn's disease is the subject, symptoms and signs is the predicate, and constipation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

13513it [45:50,  5.05it/s]

true
Determine whether the semantic relation where tricuspid valve prolapse is the subject, subclass of is the predicate, and vascular disease is the object constitutes an accurate semantic relation.

13515it [45:50,  4.95it/s]

false
Determine whether the semantic relation where Prostaglandin E receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

13516it [45:50,  5.01it/s]

true
Determine whether the semantic relation where CD80 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13518it [45:51,  4.99it/s]

true
Determine whether the semantic relation where Sp3 transcription factor is the subject, biological process is the predicate, and ossification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Costa Rica is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

13519it [45:51,  5.00it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Costa Rica is the object constitutes an accurate semantic relation.

13521it [45:51,  5.03it/s]

false
Determine whether the semantic relation where maize is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

13523it [45:52,  4.83it/s]

true
Determine whether the semantic relation where fluoroquinolone is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cannabis abuse is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13524it [45:52,  4.88it/s]

true
Determine whether the semantic relation where geographic information system is the subject, has use is the predicate, and marketing is the object constitutes an accurate semantic relation.

13525it [45:52,  4.85it/s]

true
Determine whether the semantic relation where Cucumis sativus is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.

13527it [45:52,  4.97it/s]

true
Determine whether the semantic relation where cooking is the subject, part of is the predicate, and culture is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where xylitol is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

13529it [45:53,  5.22it/s]

false
Determine whether the semantic relation where emerging communicable disease is the subject, subclass of is the predicate, and risk factor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where necatoriasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

13530it [45:53,  5.09it/s]

true
Determine whether the semantic relation where ribitol is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

13532it [45:53,  5.10it/s]

true
Determine whether the semantic relation where tick-borne encephalitis is the subject, drug or therapy used for treatment is the predicate, and piracetam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Glutathione-disulphide reductase is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

13533it [45:54,  5.11it/s]

true
Determine whether the semantic relation where Mannosidase beta is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

13534it [45:54,  4.53it/s]

false
Determine whether the semantic relation where N,N-dimethylformamide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13536it [45:54,  4.78it/s]

true
Determine whether the semantic relation where inborn error of lipid metabolism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitrophenol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

13538it [45:55,  5.05it/s]

true
Determine whether the semantic relation where acetyl-CoA carboxylase complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where venous insufficiency is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

13540it [45:55,  4.82it/s]

maybe
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glutathione is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.

13541it [45:55,  4.72it/s]

false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and (±)-flurbiprofen is the object constitutes an accurate semantic relation.

13542it [45:55,  4.70it/s]

true
Determine whether the semantic relation where thromboxane is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13544it [45:56,  4.76it/s]

false
Determine whether the semantic relation where neoplasm is the subject, health specialty is the predicate, and anatomy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (±)-flurbiprofen is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.

13545it [45:56,  4.84it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

13546it [45:56,  4.75it/s]

true
Determine whether the semantic relation where adult-onset Still's disease is the subject, symptoms and signs is the predicate, and liver disease is the object constitutes an accurate semantic relation.

13548it [45:57,  4.95it/s]

true
Determine whether the semantic relation where Duchenne muscular dystrophy is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

13549it [45:57,  4.99it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

13551it [45:57,  5.00it/s]

true
Determine whether the semantic relation where DNA damage inducible transcript 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where boutonneuse fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

13553it [45:58,  5.17it/s]

false
Determine whether the semantic relation where Glycyl-tRNA synthetase 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where calciphylaxis is the subject, subclass of is the predicate, and vascular disease is the object constitutes an accurate semantic relation.

13555it [45:58,  5.19it/s]

true
Determine whether the semantic relation where metabolic skin disease is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13557it [45:58,  5.23it/s]

true
Determine whether the semantic relation where airway obstruction is the subject, drug or therapy used for treatment is the predicate, and epinephrine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where epinephrine is the subject, medical condition treated is the predicate, and airway obstruction is the object constitutes an accurate semantic relation.

13559it [45:59,  5.31it/s]

true
Determine whether the semantic relation where acetyl coenzyme A is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dermatitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13560it [45:59,  5.39it/s]

true
Determine whether the semantic relation where dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13562it [46:00,  4.55it/s]

true
Determine whether the semantic relation where nectar is the subject, subclass of is the predicate, and animal feed is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where New Zealand is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13564it [46:00,  4.85it/s]

true
Determine whether the semantic relation where paralysis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where emergency medicine is the subject, practiced by is the predicate, and nurse is the object constitutes an accurate semantic relation.

13566it [46:00,  5.12it/s]

true
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 2C is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital diaphragmatic hernia is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

13568it [46:01,  5.21it/s]

true
Determine whether the semantic relation where anisakiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Eritrea is the object constitutes an accurate semantic relation.

13570it [46:01,  5.12it/s]

true
Determine whether the semantic relation where Eritrea is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Peroxisome proliferator activated receptor delta is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13571it [46:01,  5.05it/s]

true
Determine whether the semantic relation where Glutaredoxin is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13573it [46:02,  5.06it/s]

true
Determine whether the semantic relation where anal disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and tolbutamide is the object constitutes an accurate semantic relation.

13575it [46:02,  5.25it/s]

true
Determine whether the semantic relation where spinal cord injury is the subject, medical examination is the predicate, and radiography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

13577it [46:02,  4.94it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemolytic anemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13579it [46:03,  5.05it/s]

true
Determine whether the semantic relation where left ventricular hypertrophy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Charadriiformes is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.

13581it [46:03,  5.00it/s]

true
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ice cream is the subject, regulated by is the predicate, and United States Food and Drug Administration is the object constitutes an accurate semantic relation.

13583it [46:04,  5.02it/s]

true
Determine whether the semantic relation where KLRC4-KLRK1 readthrough is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where growth differentiation factor 5 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13585it [46:04,  5.08it/s]

true
Determine whether the semantic relation where dichlorvos is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13586it [46:04,  5.07it/s]

true
Determine whether the semantic relation where protein fragment is the subject, subclass of is the predicate, and polymer is the object constitutes an accurate semantic relation.

13588it [46:05,  5.12it/s]

true
Determine whether the semantic relation where methylene blue is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Paget's disease of bone is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

13590it [46:05,  5.28it/s]

true
Determine whether the semantic relation where smallpox is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

13591it [46:05,  5.00it/s]

true
Determine whether the semantic relation where Fanconi syndrome is the subject, health specialty is the predicate, and nephrology is the object constitutes an accurate semantic relation.

13593it [46:06,  5.02it/s]

true
Determine whether the semantic relation where pneumothorax is the subject, medical examination is the predicate, and medical ultrasonography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where factitious disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13595it [46:06,  4.61it/s]

true
Determine whether the semantic relation where factitious disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 7 receptor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13596it [46:06,  4.79it/s]

true
Determine whether the semantic relation where precipitation is the subject, made from material is the predicate, and solution is the object constitutes an accurate semantic relation.

13598it [46:07,  4.87it/s]

false
Determine whether the semantic relation where CD22 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cefaclor is the subject, medical condition treated is the predicate, and infectious bone disease is the object constitutes an accurate semantic relation.

13600it [46:07,  5.09it/s]

true
Determine whether the semantic relation where infectious bone disease is the subject, drug or therapy used for treatment is the predicate, and cefaclor is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where cartilage oligomeric matrix protein is the subject, biological process is the predicate, and regulation of gene expression is the object constitutes an accurate semantic relation.

13602it [46:07,  5.32it/s]

false
Determine whether the semantic relation where dihydrotachysterol is the subject, subject has role is the predicate, and bone density conservation agents is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bacterial pneumonia is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

13603it [46:08,  5.27it/s]

true
Determine whether the semantic relation where Madagascar is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

13605it [46:08,  5.15it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Madagascar is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 11b is the subject, cell component is the predicate, and extracellular matrix is the object constitutes an accurate semantic relation.

13607it [46:08,  5.20it/s]

false
Determine whether the semantic relation where Cyclin dependent kinase 9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 3-phosphoglyceraldehyde is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13609it [46:09,  5.32it/s]

false
Determine whether the semantic relation where maltose is the subject, found in taxon is the predicate, and Candida albicans is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nortriptyline is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

13611it [46:09,  5.40it/s]

true
Determine whether the semantic relation where transposition of great vessels is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyarteritis nodosa is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

13613it [46:10,  5.42it/s]

false
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

13614it [46:10,  5.43it/s]

false
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and nortriptyline is the object constitutes an accurate semantic relation.

13616it [46:10,  5.22it/s]

true
Determine whether the semantic relation where Adenylosuccinate lyase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13617it [46:10,  5.18it/s]

true
Determine whether the semantic relation where parotitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

13618it [46:11,  5.10it/s]

true
Determine whether the semantic relation where blepharitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13619it [46:11,  3.62it/s]

true
Determine whether the semantic relation where maleic anhydride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13621it [46:11,  4.22it/s]

true
Determine whether the semantic relation where TEK receptor tyrosine kinase is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metal poisoning is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13623it [46:12,  4.65it/s]

false
Determine whether the semantic relation where gastrointestinal tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 2 subfamily E member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13624it [46:12,  4.71it/s]

false
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

13626it [46:12,  4.88it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where melanocortin 1 receptor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13627it [46:13,  5.02it/s]

false
Determine whether the semantic relation where gamolenic acid is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

13628it [46:13,  4.93it/s]

true
Determine whether the semantic relation where rhinoscleroma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13630it [46:13,  4.77it/s]

true
Determine whether the semantic relation where rhinoscleroma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetralogy of Fallot is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13631it [46:13,  4.79it/s]

true
Determine whether the semantic relation where autosomal dominant polycystic kidney is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

13633it [46:14,  4.91it/s]

true
Determine whether the semantic relation where paraneoplastic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tuberous sclerosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13635it [46:14,  5.06it/s]

true
Determine whether the semantic relation where alpha-linolenic acid is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium/calmodulin dependent protein kinase I is the subject, biological process is the predicate, and cell cycle is the object constitutes an accurate semantic relation.

13636it [46:14,  5.16it/s]

false
Determine whether the semantic relation where spinal cord injury is the subject, medical examination is the predicate, and computed tomography is the object constitutes an accurate semantic relation.

13637it [46:15,  5.04it/s]

false
Determine whether the semantic relation where oxygen is the subject, named after is the predicate, and acid is the object constitutes an accurate semantic relation.

13639it [46:15,  5.02it/s]

false
Determine whether the semantic relation where potato is the subject, has use is the predicate, and medicinal plant is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where collagen type I trimer is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

13640it [46:15,  4.99it/s]

false
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

13642it [46:16,  5.17it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

13643it [46:16,  5.07it/s]

true
Determine whether the semantic relation where D-glucouronic acid is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

13644it [46:16,  4.95it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.

13645it [46:16,  4.81it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and India is the object constitutes an accurate semantic relation.

13646it [46:17,  4.45it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

13648it [46:17,  4.51it/s]

true
Determine whether the semantic relation where sweat gland neoplasm is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Activating transcription factor 3 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.

13650it [46:17,  4.76it/s]

false
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Sri Lanka is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13652it [46:18,  5.01it/s]

false
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United States is the subject, significant event is the predicate, and World War I is the object constitutes an accurate semantic relation.

13654it [46:18,  4.99it/s]

true
Determine whether the semantic relation where microtubule associated protein tau is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where humanities is the subject, has part(s) is the predicate, and linguistics is the object constitutes an accurate semantic relation.

13656it [46:19,  5.18it/s]

true
Determine whether the semantic relation where tragacanth is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Natural cytotoxicity triggering receptor 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13658it [46:19,  5.15it/s]

true
Determine whether the semantic relation where Sri Lanka is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where laryngitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13659it [46:19,  4.86it/s]

true
Determine whether the semantic relation where linguistics is the subject, subclass of is the predicate, and humanities is the object constitutes an accurate semantic relation.

13660it [46:19,  4.70it/s]

true
Determine whether the semantic relation where pulmonary valve stenosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

13662it [46:20,  4.77it/s]

false
Determine whether the semantic relation where dynein is the subject, subclass of is the predicate, and isomerase is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where opisthorchiasis is the subject, anatomical location is the predicate, and pancreas is the object constitutes an accurate semantic relation.

13664it [46:20,  4.91it/s]

false
Determine whether the semantic relation where vitamin is the subject, subclass of is the predicate, and organic compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where butyric acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13666it [46:21,  5.08it/s]

true
Determine whether the semantic relation where trifluoroacetic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viremia is the subject, subclass of is the predicate, and hematopoietic system disease is the object constitutes an accurate semantic relation.

13668it [46:21,  5.02it/s]

false
Determine whether the semantic relation where grey wolf is the subject, main food source is the predicate, and cattle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myasthenia gravis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13669it [46:21,  5.12it/s]

true
Determine whether the semantic relation where recombination signal binding protein for immunoglobulin kappa J region is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13671it [46:22,  4.96it/s]

false
Determine whether the semantic relation where Nepal is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true

13672it [46:22,  5.06it/s]

Determine whether the semantic relation where Nepal is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

13674it [46:22,  5.23it/s]

true
Determine whether the semantic relation where cyclopentolate-(RS) is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Nepal is the object constitutes an accurate semantic relation.

13675it [46:22,  5.16it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Nepal is the object constitutes an accurate semantic relation.

13677it [46:23,  4.91it/s]

true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where simvastatin is the subject, significant drug interaction is the predicate, and verapamil is the object constitutes an accurate semantic relation.

13679it [46:23,  4.88it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Paraguay is the object constitutes an accurate semantic relation.

13681it [46:24,  5.19it/s]

true
Determine whether the semantic relation where Paraguay is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiamine(1+) ion is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

13682it [46:24,  5.18it/s]

false
Determine whether the semantic relation where abdominal cavity is the subject, has part(s) is the predicate, and pancreas is the object constitutes an accurate semantic relation.

13684it [46:24,  4.84it/s]

true
Determine whether the semantic relation where aberrations of the eye is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where signal transducer and activator of transcription 3 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

13686it [46:25,  4.76it/s]

false
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Venezuela is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pancreas is the subject, anatomical location is the predicate, and abdominal cavity is the object constitutes an accurate semantic relation.

13687it [46:25,  4.61it/s]

true
Determine whether the semantic relation where Venezuela is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

13688it [46:25,  4.56it/s]

true
Determine whether the semantic relation where compulsive behavior is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

13689it [46:25,  4.59it/s]

false
Determine whether the semantic relation where seborrhoeic dermatitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13691it [46:26,  4.78it/s]

true
Determine whether the semantic relation where Janus kinase 3 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspirin-exacerbated respiratory disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13693it [46:26,  4.97it/s]

true
Determine whether the semantic relation where anthrax is the subject, anatomical location is the predicate, and lymph node is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where East Germany is the subject, continent is the predicate, and Europe is the object constitutes an accurate semantic relation.

13695it [46:26,  5.27it/s]

true
Determine whether the semantic relation where Shy-Drager syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nicergoline is the subject, route of administration is the predicate, and intramuscular injection is the object constitutes an accurate semantic relation.

13697it [46:27,  5.34it/s]

false
Determine whether the semantic relation where focal epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tularemia is the subject, has natural reservoir is the predicate, and sheep is the object constitutes an accurate semantic relation.

13698it [46:27,  5.28it/s]

false
Determine whether the semantic relation where combinatorial chemistry is the subject, subclass of is the predicate, and chemistry is the object constitutes an accurate semantic relation.

13700it [46:27,  5.04it/s]

true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Wiskott-Aldrich syndrome is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

13702it [46:28,  5.00it/s]

false
Determine whether the semantic relation where ERCC excision repair 2, TFIIH core complex helicase subunit is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

13704it [46:28,  5.20it/s]

true
Determine whether the semantic relation where familial adenomatous polyposis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipid is the subject, subclass of is the predicate, and organic compound is the object constitutes an accurate semantic relation.

13705it [46:28,  4.85it/s]

true
Determine whether the semantic relation where limbic encephalitis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13706it [46:29,  4.82it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.
true

13708it [46:29,  4.94it/s]

Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Prinzmetal's angina is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13710it [46:30,  4.85it/s]

true
Determine whether the semantic relation where Chenopodium album is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sirtuin 1 is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

13711it [46:30,  4.23it/s]

false
Determine whether the semantic relation where mononuclear phagocyte system is the subject, different from is the predicate, and reticulocyte is the object constitutes an accurate semantic relation.

13712it [46:30,  4.31it/s]

true
Determine whether the semantic relation where triploid syndrome is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

13714it [46:30,  4.51it/s]

true
Determine whether the semantic relation where Medical Subject Headings is the subject, country of origin is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arteriolosclerosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13715it [46:31,  4.66it/s]

true
Determine whether the semantic relation where musculoskeletal and neural physiological phenomenon is the subject, subclass of is the predicate, and physiological phenomenon is the object constitutes an accurate semantic relation.

13717it [46:31,  4.84it/s]

true
Determine whether the semantic relation where dementia is the subject, risk factor is the predicate, and social isolation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where capsule endoscopy is the subject, country of origin is the predicate, and Israel is the object constitutes an accurate semantic relation.

13718it [46:31,  4.88it/s]

true
Determine whether the semantic relation where eating disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

13720it [46:32,  4.99it/s]

true
Determine whether the semantic relation where FYN proto-oncogene, Src family tyrosine kinase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystatin A is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

13722it [46:32,  5.02it/s]

true
Determine whether the semantic relation where second primary neoplasm is the subject, subclass of is the predicate, and relapse is the object constitutes an accurate semantic relation.
false

13723it [46:32,  5.04it/s]

Determine whether the semantic relation where thalassemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where siloxane is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

13725it [46:33,  5.18it/s]

true
Determine whether the semantic relation where Klinefelter's syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit alpha 5 is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.

13727it [46:33,  5.20it/s]

false
Determine whether the semantic relation where Ghana is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where environmental health is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.

13728it [46:33,  5.17it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Uzbekistan is the object constitutes an accurate semantic relation.

13730it [46:34,  5.11it/s]

true
Determine whether the semantic relation where macroglossia is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Fuchs' endothelial dystrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13731it [46:34,  5.12it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Ghana is the object constitutes an accurate semantic relation.

13733it [46:34,  5.19it/s]

true
Determine whether the semantic relation where hepatitis B is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phenanthridine is the subject, subclass of is the predicate, and pyridine is the object constitutes an accurate semantic relation.

13734it [46:34,  5.03it/s]

false
Determine whether the semantic relation where thymidine monophosphate is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.

13735it [46:35,  4.46it/s]

true
Determine whether the semantic relation where secretion or excretion is the subject, has contributing factor is the predicate, and secretion is the object constitutes an accurate semantic relation.

13737it [46:35,  4.68it/s]

false
Determine whether the semantic relation where SMAD family member 6 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where apatite is the subject, subclass of is the predicate, and fertilizer is the object constitutes an accurate semantic relation.

13738it [46:35,  4.78it/s]

false
Determine whether the semantic relation where ethanol is the subject, has part(s) of the class is the predicate, and carbon is the object constitutes an accurate semantic relation.

13739it [46:36,  4.67it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, G is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true

13741it [46:36,  4.85it/s]

Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein B is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

13743it [46:36,  4.97it/s]

true
Determine whether the semantic relation where Fabry disease is the subject, symptoms and signs is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibrillar collagen trimer is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

13744it [46:37,  5.01it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

13745it [46:37,  4.84it/s]

true
Determine whether the semantic relation where viral pneumonia is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

13747it [46:37,  5.05it/s]

true
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where high fructose corn syrup is the subject, made from material is the predicate, and water is the object constitutes an accurate semantic relation.

13749it [46:38,  5.13it/s]

false
Determine whether the semantic relation where chondroma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arterial hypertension is the subject, drug or therapy used for treatment is the predicate, and bumetanide is the object constitutes an accurate semantic relation.

13751it [46:38,  5.25it/s]

false
Determine whether the semantic relation where bumetanide is the subject, medical condition treated is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

13753it [46:38,  5.28it/s]

true
Determine whether the semantic relation where eugenics is the subject, based on is the predicate, and evolution is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fluorescent dye is the subject, has use is the predicate, and food coloring is the object constitutes an accurate semantic relation.

13755it [46:39,  5.26it/s]

false
Determine whether the semantic relation where phospholipase A2 group X is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phospholipase A2 group X is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

13757it [46:39,  5.37it/s]

true
Determine whether the semantic relation where raccoon is the subject, invasive to is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fever of unknown origin is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13758it [46:39,  5.30it/s]

true
Determine whether the semantic relation where acetic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13760it [46:40,  5.19it/s]

true
Determine whether the semantic relation where atropine is the subject, medical condition treated is the predicate, and uveitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uveitis is the subject, drug or therapy used for treatment is the predicate, and atropine is the object constitutes an accurate semantic relation.

13762it [46:40,  5.03it/s]

true
Determine whether the semantic relation where High mobility group AT-hook 2 is the subject, biological process is the predicate, and cell division is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where atovaquone is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

13764it [46:40,  5.14it/s]

true
Determine whether the semantic relation where focal infection of oral origin is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tracheitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13766it [46:41,  5.28it/s]

true
Determine whether the semantic relation where amnesia is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where subtilisin is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

13767it [46:41,  4.97it/s]

true
Determine whether the semantic relation where virtual reality exposure therapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

13768it [46:41,  4.89it/s]

true
Determine whether the semantic relation where Ipomoea nil is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

13770it [46:42,  4.90it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Iraq is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mathematics is the subject, has use is the predicate, and science is the object constitutes an accurate semantic relation.

13771it [46:42,  4.94it/s]

true
Determine whether the semantic relation where Datura stramonium is the subject, has use is the predicate, and insecticide is the object constitutes an accurate semantic relation.

13773it [46:42,  5.01it/s]

true
Determine whether the semantic relation where paired box 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where South Korea is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

13774it [46:42,  4.91it/s]

false
Determine whether the semantic relation where South Korea is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

13775it [46:43,  4.35it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Jordan is the object constitutes an accurate semantic relation.

13776it [46:43,  4.51it/s]

true
Determine whether the semantic relation where Jordan is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

13777it [46:43,  4.50it/s]

true
Determine whether the semantic relation where Iraq is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

13779it [46:44,  4.61it/s]

true
Determine whether the semantic relation where SMAD family member 5 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Retinol binding protein 4 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13781it [46:44,  4.99it/s]

false
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and South Korea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and South Korea is the object constitutes an accurate semantic relation.

13782it [46:44,  5.03it/s]

true
Determine whether the semantic relation where premenstrual syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13783it [46:44,  4.99it/s]

true
Determine whether the semantic relation where Peroxisome proliferator activated receptor delta is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

13785it [46:45,  5.03it/s]

true
Determine whether the semantic relation where Activating transcription factor 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where depression is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

13787it [46:45,  5.17it/s]

false
Determine whether the semantic relation where C-X-C motif chemokine ligand 6 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where luteolin is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

13788it [46:45,  4.81it/s]

false
Determine whether the semantic relation where vasovagal response is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13789it [46:46,  4.83it/s]

false
Determine whether the semantic relation where HSPA8 is the subject, instance of is the predicate, and gene is the object constitutes an accurate semantic relation.

13790it [46:46,  4.82it/s]

true
Determine whether the semantic relation where peptide YY is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

13791it [46:46,  4.82it/s]

true
Determine whether the semantic relation where Diclofenac is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13792it [46:46,  4.71it/s]

true
Determine whether the semantic relation where adverse drug reaction is the subject, subclass of is the predicate, and iatrogenesis is the object constitutes an accurate semantic relation.

13794it [46:47,  4.83it/s]

true
Determine whether the semantic relation where starvation is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where schizophyllan is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13796it [46:47,  5.07it/s]

true
Determine whether the semantic relation where acute kidney injury is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where omeprazole is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

13797it [46:47,  4.98it/s]

true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

13798it [46:47,  4.86it/s]

true
Determine whether the semantic relation where CD58 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13800it [46:48,  4.84it/s]

true
Determine whether the semantic relation where Interleukin 12B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CADASIL is the subject, possible treatment is the predicate, and statin is the object constitutes an accurate semantic relation.

13801it [46:48,  4.92it/s]

false
Determine whether the semantic relation where cryptosporidiosis is the subject, symptoms and signs is the predicate, and dehydration is the object constitutes an accurate semantic relation.

13802it [46:48,  4.65it/s]

true
Determine whether the semantic relation where post-traumatic headache is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13804it [46:49,  4.79it/s]

true
Determine whether the semantic relation where neonatal anemia is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where typhoid fever is the subject, symptoms and signs is the predicate, and bradycardia is the object constitutes an accurate semantic relation.

13805it [46:49,  4.77it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 27 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13806it [46:49,  4.56it/s]

true
Determine whether the semantic relation where Arnold-Chiari malformation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13808it [46:50,  4.83it/s]

true
Determine whether the semantic relation where ethidium bromide is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malta is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

13810it [46:50,  5.03it/s]

true
Determine whether the semantic relation where dextran is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oxprenolol is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.

13812it [46:50,  5.00it/s]

true
Determine whether the semantic relation where neutropenia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

13813it [46:51,  4.98it/s]

Determine whether the semantic relation where L-valine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Malta is the object constitutes an accurate semantic relation.

13814it [46:51,  4.47it/s]

true
Determine whether the semantic relation where facial paralysis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13815it [46:51,  4.04it/s]

true
Determine whether the semantic relation where Malta is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

13817it [46:52,  4.50it/s]

true
Determine whether the semantic relation where poliomyelitis is the subject, subclass of is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Serpin family G member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13819it [46:52,  4.89it/s]

true
Determine whether the semantic relation where renin is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Scotland is the object constitutes an accurate semantic relation.

13821it [46:52,  5.14it/s]

false
Determine whether the semantic relation where American football is the subject, country of origin is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Angelica sinensis is the object constitutes an accurate semantic relation.

13823it [46:53,  5.25it/s]

true
Determine whether the semantic relation where risperidone is the subject, medical condition treated is the predicate, and sleep-wake disorder is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 5 receptor subunit alpha is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.

13824it [46:53,  5.30it/s]

false
Determine whether the semantic relation where E2F transcription factor 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13826it [46:53,  5.01it/s]

false
Determine whether the semantic relation where malignant hyperthermia is the subject, medical examination is the predicate, and temperature measurement is the object constitutes an accurate semantic relation.
false

13827it [46:53,  4.99it/s]

Determine whether the semantic relation where sleep-wake disorder is the subject, drug or therapy used for treatment is the predicate, and risperidone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where respiratory failure is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13828it [46:54,  4.57it/s]

true
Determine whether the semantic relation where auditory ossicle is the subject, develops from is the predicate, and jaw is the object constitutes an accurate semantic relation.

13830it [46:54,  4.65it/s]

true
Determine whether the semantic relation where RRR-alpha-tocopherol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Czech Republic is the object constitutes an accurate semantic relation.

13831it [46:54,  4.74it/s]

true
Determine whether the semantic relation where Czech Republic is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

13833it [46:55,  4.85it/s]

true
Determine whether the semantic relation where woman is the subject, has characteristic is the predicate, and menstrual cycle is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kaposi's sarcoma is the subject, medical examination is the predicate, and histology is the object constitutes an accurate semantic relation.

13835it [46:55,  5.13it/s]

false
Determine whether the semantic relation where West Germany is the subject, continent is the predicate, and Europe is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (−)-nicotine is the subject, medical condition treated is the predicate, and ulcerative colitis is the object constitutes an accurate semantic relation.

13836it [46:55,  5.23it/s]

false
Determine whether the semantic relation where granuloma inguinale is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13838it [46:56,  5.10it/s]

true
Determine whether the semantic relation where collagen type II trimer is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13839it [46:56,  5.06it/s]

true
Determine whether the semantic relation where HSPA8 is the subject, chromosome is the predicate, and human chromosome 11 is the object constitutes an accurate semantic relation.

13841it [46:56,  5.01it/s]

true
Determine whether the semantic relation where Myanmar is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pulmonary hypertension is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

13842it [46:57,  4.89it/s]

true
Determine whether the semantic relation where myocardial infarction is the subject, drug or therapy used for treatment is the predicate, and penbutolol is the object constitutes an accurate semantic relation.

13843it [46:57,  4.72it/s]

false
Determine whether the semantic relation where penbutolol is the subject, medical condition treated is the predicate, and myocardial infarction is the object constitutes an accurate semantic relation.

13845it [46:57,  4.86it/s]

false
Determine whether the semantic relation where phaeochromocytoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Myanmar is the object constitutes an accurate semantic relation.

13847it [46:58,  4.97it/s]

true
Determine whether the semantic relation where EGFR is the subject, expressed in is the predicate, and vulva is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Jamaica is the object constitutes an accurate semantic relation.

13849it [46:58,  4.93it/s]

true
Determine whether the semantic relation where Jamaica is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perfusion is the subject, different from is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.

13850it [46:58,  4.49it/s]

false
Determine whether the semantic relation where urea is the subject, found in taxon is the predicate, and Chlamydomonas reinhardtii is the object constitutes an accurate semantic relation.

13851it [46:58,  4.61it/s]

false
Determine whether the semantic relation where government is the subject, manifestation of is the predicate, and power is the object constitutes an accurate semantic relation.

13853it [46:59,  4.72it/s]

false
Determine whether the semantic relation where Barbados is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lipid storage disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13854it [46:59,  4.77it/s]

true
Determine whether the semantic relation where odontoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13855it [46:59,  4.60it/s]

false
Determine whether the semantic relation where cloning is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

13857it [47:00,  4.84it/s]

false
Determine whether the semantic relation where acrylonitrile is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13858it [47:00,  4.95it/s]

false
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Barbados is the object constitutes an accurate semantic relation.

13859it [47:00,  4.75it/s]

true
Determine whether the semantic relation where ileum is the subject, innervates is the predicate, and vagus nerve is the object constitutes an accurate semantic relation.

13860it [47:00,  4.63it/s]

false
Determine whether the semantic relation where amyloid P component, serum is the subject, biological process is the predicate, and protein folding is the object constitutes an accurate semantic relation.

13862it [47:01,  4.88it/s]

false
Determine whether the semantic relation where pseudomembranous colitis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2-mercaptoethanol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13864it [47:01,  5.13it/s]

false
Determine whether the semantic relation where mitral valve insufficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitral valve insufficiency is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13866it [47:01,  5.16it/s]

true
Determine whether the semantic relation where integrin subunit alpha 1 is the subject, biological process is the predicate, and vasodilation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where disaster is the subject, subclass of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

13868it [47:02,  5.21it/s]

false
Determine whether the semantic relation where disease susceptibility is the subject, has cause is the predicate, and lifestyle is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thanatology is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

13869it [47:02,  5.18it/s]

true
Determine whether the semantic relation where Nucleotide binding oligomerization domain containing 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

13871it [47:02,  5.01it/s]

true
Determine whether the semantic relation where immunoblastic lymphadenopathy is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where histone deacetylase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13873it [47:03,  5.07it/s]

false
Determine whether the semantic relation where clinical pathology is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mRNA cleavage stimulating factor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

13874it [47:03,  5.05it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and terfenadine is the object constitutes an accurate semantic relation.

13876it [47:03,  5.10it/s]

true
Determine whether the semantic relation where terfenadine is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Keratin 14 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

13878it [47:04,  5.30it/s]

false
Determine whether the semantic relation where Bernard-Soulier syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where leptospirosis is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.

13880it [47:04,  5.30it/s]

true
Determine whether the semantic relation where Dynamin 3 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, symptoms and signs is the predicate, and apnea is the object constitutes an accurate semantic relation.

13881it [47:04,  5.18it/s]

true
Determine whether the semantic relation where ecdysone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13883it [47:05,  5.05it/s]

true
Determine whether the semantic relation where injury is the subject, handled, mitigated, or managed by is the predicate, and rehabilitation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yaws is the subject, subclass of is the predicate, and bone disease is the object constitutes an accurate semantic relation.

13885it [47:05,  4.98it/s]

false
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

13886it [47:05,  4.90it/s]

true
Determine whether the semantic relation where phospholipids is the subject, subclass of is the predicate, and organophosphate is the object constitutes an accurate semantic relation.

13887it [47:06,  4.76it/s]

false
Determine whether the semantic relation where alcoholism is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13889it [47:06,  4.83it/s]

false
Determine whether the semantic relation where alcoholism is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Rift Valley fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

13891it [47:06,  5.05it/s]

false
Determine whether the semantic relation where liver cirrhosis is the subject, drug or therapy used for treatment is the predicate, and bumetanide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bumetanide is the subject, medical condition treated is the predicate, and liver cirrhosis is the object constitutes an accurate semantic relation.

13892it [47:07,  5.06it/s]

false
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Pinus sylvestris is the object constitutes an accurate semantic relation.

13894it [47:07,  5.06it/s]

true
Determine whether the semantic relation where cystatin B is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphomatoid papulosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

13896it [47:07,  5.08it/s]

true
Determine whether the semantic relation where malaria is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where problem gambling is the subject, health specialty is the predicate, and clinical psychology is the object constitutes an accurate semantic relation.

13898it [47:08,  4.77it/s]

false
Determine whether the semantic relation where meningoencephalitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where platelet and endothelial cell adhesion molecule 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

13899it [47:08,  4.93it/s]

false
Determine whether the semantic relation where botulism is the subject, drug or therapy used for treatment is the predicate, and metronidazole is the object constitutes an accurate semantic relation.

13900it [47:08,  4.68it/s]

false
Determine whether the semantic relation where epididymitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

13902it [47:09,  4.65it/s]

true
Determine whether the semantic relation where nutrition disorder is the subject, drug or therapy used for treatment is the predicate, and alpha-linolenic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alpha-linolenic acid is the subject, medical condition treated is the predicate, and nutrition disorder is the object constitutes an accurate semantic relation.

13904it [47:09,  4.72it/s]

maybe
Determine whether the semantic relation where type-1 diabetes is the subject, symptoms and signs is the predicate, and polyphagia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

13906it [47:10,  4.94it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCL6 transcription repressor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13907it [47:10,  5.02it/s]

true
Determine whether the semantic relation where dihydrocholesterol is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.

13909it [47:10,  5.09it/s]

false
Determine whether the semantic relation where Dominica is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where veratridine is the subject, has use is the predicate, and insecticide is the object constitutes an accurate semantic relation.

13910it [47:10,  4.72it/s]

false
Determine whether the semantic relation where nitric acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

13911it [47:11,  4.76it/s]

true
Determine whether the semantic relation where smoking is the subject, risk factor is the predicate, and anhedonia is the object constitutes an accurate semantic relation.

13913it [47:11,  4.88it/s]

maybe
Determine whether the semantic relation where North America is the subject, country is the predicate, and Dominica is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where smoking is the subject, risk factor is the predicate, and mental disorder is the object constitutes an accurate semantic relation.

13915it [47:11,  5.08it/s]

true
Determine whether the semantic relation where cardioplegia is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ancylostomiasis is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

13917it [47:12,  5.25it/s]

true
Determine whether the semantic relation where prokaryotic cell is the subject, has part(s) is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where optic atrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13918it [47:12,  5.03it/s]

true
Determine whether the semantic relation where central nervous system trauma is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

13920it [47:12,  5.08it/s]

false
Determine whether the semantic relation where dimethyl sulfoxide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sorbose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

13922it [47:13,  5.24it/s]

true
Determine whether the semantic relation where restless legs syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

13924it [47:13,  5.31it/s]

false
Determine whether the semantic relation where Burundi is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Burundi is the object constitutes an accurate semantic relation.

13926it [47:14,  5.00it/s]

true
Determine whether the semantic relation where MCL1 apoptosis regulator, BCL2 family member is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where paleopathology is the subject, part of is the predicate, and pathology is the object constitutes an accurate semantic relation.

13928it [47:14,  4.96it/s]

true
Determine whether the semantic relation where infection of the central nervous system is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diverticulitis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

13930it [47:14,  4.89it/s]

true
Determine whether the semantic relation where twin-to-twin transfusion syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where salivary gland disease is the subject, health specialty is the predicate, and oral and maxillofacial surgery is the object constitutes an accurate semantic relation.

13931it [47:15,  4.72it/s]

true
Determine whether the semantic relation where vimentin is the subject, cell component is the predicate, and ribonucleoprotein complex is the object constitutes an accurate semantic relation.

13932it [47:15,  4.78it/s]

false
Determine whether the semantic relation where phosphates is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

13933it [47:15,  4.79it/s]

true
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and headache is the object constitutes an accurate semantic relation.
true

13935it [47:15,  5.00it/s]

Determine whether the semantic relation where mycotoxicosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acetic acid is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

13936it [47:16,  4.99it/s]

false
Determine whether the semantic relation where triamcinolone is the subject, medical condition treated is the predicate, and systemic lupus erythematosus is the object constitutes an accurate semantic relation.

13938it [47:16,  5.01it/s]

true
Determine whether the semantic relation where systemic lupus erythematosus is the subject, drug or therapy used for treatment is the predicate, and triamcinolone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where basilar skull fracture is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

13940it [47:16,  5.31it/s]

false
Determine whether the semantic relation where trichotillomania is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trichotillomania is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13941it [47:17,  5.36it/s]

true
Determine whether the semantic relation where septic shock is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

13942it [47:17,  5.04it/s]

true
Determine whether the semantic relation where Polymeric immunoglobulin receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

13944it [47:17,  4.91it/s]

true
Determine whether the semantic relation where platelet and endothelial cell adhesion molecule 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Eunice Kennedy Shriver National Institute of Child Health and Human Development is the subject, field of work is the predicate, and intellectual disability is the object constitutes an accurate semantic relation.

13945it [47:17,  5.04it/s]

true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

13947it [47:18,  4.46it/s]

false
Determine whether the semantic relation where Matrix metallopeptidase 3 is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Tonga is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

13949it [47:18,  4.81it/s]

true
Determine whether the semantic relation where batroxobin is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where major histocompatibility complex, class I, G is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

13951it [47:19,  4.97it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Tonga is the object constitutes an accurate semantic relation.
true

13952it [47:19,  5.05it/s]

Determine whether the semantic relation where maltose is the subject, found in taxon is the predicate, and Streptococcus pneumoniae is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome P450 family 11 subfamily A member 1 is the subject, biological process is the predicate, and lipid metabolism is the object constitutes an accurate semantic relation.

13954it [47:19,  5.28it/s]

true
Determine whether the semantic relation where patent ductus arteriosus is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where porphobilinogen is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

13956it [47:20,  5.32it/s]

false
Determine whether the semantic relation where toxocariasis is the subject, subclass of is the predicate, and liver disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where RNA polymerase III is the subject, subclass of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

13958it [47:20,  5.44it/s]

true
Determine whether the semantic relation where medicine is the subject, industry is the predicate, and health care industry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where vinblastine is the subject, route of administration is the predicate, and injection is the object constitutes an accurate semantic relation.

13960it [47:20,  5.31it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

13962it [47:21,  5.32it/s]

true
Determine whether the semantic relation where instructional materials is the subject, part of is the predicate, and learning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13964it [47:21,  5.33it/s]

true
Determine whether the semantic relation where paraneoplastic endocrine syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where midazolam is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

13966it [47:21,  5.35it/s]

true
Determine whether the semantic relation where pertussis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Growth factor receptor bound protein 10 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

13968it [47:22,  5.28it/s]

true
Determine whether the semantic relation where fumarate hydratase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where MDMA is the subject, route of administration is the predicate, and injection is the object constitutes an accurate semantic relation.

13970it [47:22,  5.26it/s]

true
Determine whether the semantic relation where patent ductus arteriosus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where essential fatty acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13972it [47:23,  5.28it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and alprazolam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where functional gastrointestinal disorder is the subject, drug or therapy used for treatment is the predicate, and dicyclomine is the object constitutes an accurate semantic relation.

13973it [47:23,  5.24it/s]

true
Determine whether the semantic relation where dicyclomine is the subject, medical condition treated is the predicate, and functional gastrointestinal disorder is the object constitutes an accurate semantic relation.

13975it [47:23,  5.15it/s]

true
Determine whether the semantic relation where alprazolam is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where corticosterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

13977it [47:24,  5.32it/s]

true
Determine whether the semantic relation where acute cholecystitis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where congenital adrenal hyperplasia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

13979it [47:24,  4.81it/s]

true
Determine whether the semantic relation where subacute bacterial endocarditis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where War in Afghanistan (2001–2021) is the subject, participant is the predicate, and Canada is the object constitutes an accurate semantic relation.

13980it [47:24,  5.02it/s]

true
Determine whether the semantic relation where autism is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13981it [47:24,  4.84it/s]

false
Determine whether the semantic relation where autism is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

13983it [47:25,  5.03it/s]

false
Determine whether the semantic relation where cryptosporidiosis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteochondrosis is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.

13985it [47:25,  5.14it/s]

false
Determine whether the semantic relation where Amylo-alpha-1, 6-glucosidase, 4-alpha-glucanotransferase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where staphylococcal infection is the subject, drug or therapy used for treatment is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.

13987it [47:26,  5.18it/s]

true
Determine whether the semantic relation where clarithromycin is the subject, medical condition treated is the predicate, and staphylococcal infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-proline is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

13989it [47:26,  5.27it/s]

false
Determine whether the semantic relation where tetrose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Iceland is the object constitutes an accurate semantic relation.

13990it [47:26,  5.21it/s]

true
Determine whether the semantic relation where Iceland is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

13992it [47:27,  5.06it/s]

true
Determine whether the semantic relation where heme oxygenase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crohn's disease is the subject, drug or therapy used for treatment is the predicate, and tacrolimus is the object constitutes an accurate semantic relation.

13993it [47:27,  5.06it/s]

false
Determine whether the semantic relation where beta-1,3-glucuronyltransferase 1 is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.

13995it [47:27,  5.09it/s]

false
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uridine diphosphate glucose is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

13997it [47:28,  5.24it/s]

false
Determine whether the semantic relation where High mobility group box 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where clonorchiasis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

13999it [47:28,  5.21it/s]

true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where erythromelalgia is the subject, subclass of is the predicate, and genodermatosis is the object constitutes an accurate semantic relation.

14000it [47:28,  4.99it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, has part(s) is the predicate, and chlorine is the object constitutes an accurate semantic relation.

14002it [47:29,  4.79it/s]

true
Determine whether the semantic relation where Calbindin 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Vogt–Koyanagi–Harada syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14004it [47:29,  4.95it/s]

true
Determine whether the semantic relation where Falconiformes is the subject, taxon range is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14006it [47:29,  5.22it/s]

true
Determine whether the semantic relation where Regenerating family member 1 alpha is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diazepam is the subject, medical condition treated is the predicate, and sleep-wake disorder is the object constitutes an accurate semantic relation.

14007it [47:30,  5.29it/s]

true
Determine whether the semantic relation where testicular disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14008it [47:30,  5.18it/s]

true
Determine whether the semantic relation where chancre is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

14009it [47:30,  4.92it/s]

false
Determine whether the semantic relation where peritonitis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

14011it [47:30,  4.95it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sleep-wake disorder is the subject, drug or therapy used for treatment is the predicate, and diazepam is the object constitutes an accurate semantic relation.

14013it [47:31,  5.04it/s]

true
Determine whether the semantic relation where cholesterol is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where EPH receptor A2 is the subject, biological process is the predicate, and bone remodeling is the object constitutes an accurate semantic relation.

14015it [47:31,  5.33it/s]

false
Determine whether the semantic relation where Egypt is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where World Health Organization is the subject, country is the predicate, and Egypt is the object constitutes an accurate semantic relation.

14016it [47:31,  4.87it/s]

false
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and thioridazine is the object constitutes an accurate semantic relation.

14017it [47:32,  4.86it/s]

true
Determine whether the semantic relation where intermittent pneumatic compression device is the subject, subclass of is the predicate, and hospital equipment and supplies is the object constitutes an accurate semantic relation.

14019it [47:32,  4.90it/s]

true
Determine whether the semantic relation where measles is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blood coagulation disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14021it [47:32,  5.01it/s]

true
Determine whether the semantic relation where blood coagulation disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycoprotein Ib-IX-V complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

14023it [47:33,  4.96it/s]

true
Determine whether the semantic relation where reactive nitrogen species is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thioridazine is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

14024it [47:33,  5.01it/s]

true
Determine whether the semantic relation where sociology is the subject, is the study of is the predicate, and work is the object constitutes an accurate semantic relation.

14026it [47:33,  5.05it/s]

false
Determine whether the semantic relation where vascular endothelial growth factor C is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

14027it [47:34,  4.55it/s]

true
Determine whether the semantic relation where ADP ribosylation factor 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

14029it [47:34,  4.75it/s]

false
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scrofula is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

14031it [47:34,  5.05it/s]

false
Determine whether the semantic relation where ceftizoxime is the subject, medical condition treated is the predicate, and female reproductive system disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycerol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14032it [47:35,  5.14it/s]

true
Determine whether the semantic relation where hyperhomocysteinemia is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

14033it [47:35,  4.91it/s]

false
Determine whether the semantic relation where oxalic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

14034it [47:35,  4.68it/s]

true
Determine whether the semantic relation where histone code is the subject, subclass of is the predicate, and molecular geometry is the object constitutes an accurate semantic relation.

14036it [47:36,  4.62it/s]

false
Determine whether the semantic relation where female reproductive system disease is the subject, drug or therapy used for treatment is the predicate, and ceftizoxime is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where agar is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.

14037it [47:36,  4.63it/s]

true
Determine whether the semantic relation where collodion is the subject, subclass of is the predicate, and solution is the object constitutes an accurate semantic relation.

14039it [47:36,  4.63it/s]

true
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and rac-warfarin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sex worker is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

14041it [47:37,  4.77it/s]

true
Determine whether the semantic relation where rac-warfarin is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14042it [47:37,  4.78it/s]

false
Determine whether the semantic relation where Takayasu's arteritis is the subject, drug or therapy used for treatment is the predicate, and alprostadil is the object constitutes an accurate semantic relation.

14043it [47:37,  4.61it/s]

false
Determine whether the semantic relation where alprostadil is the subject, medical condition treated is the predicate, and Takayasu's arteritis is the object constitutes an accurate semantic relation.

14045it [47:37,  4.67it/s]

false
Determine whether the semantic relation where halo nevus is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where twin study method is the subject, subclass of is the predicate, and genetic technique is the object constitutes an accurate semantic relation.

14046it [47:38,  4.70it/s]

false
Determine whether the semantic relation where brain hypoxia-ischemia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14048it [47:38,  4.92it/s]

true
Determine whether the semantic relation where sinus arrhythmia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Von Hippel-Lindau tumor suppressor is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

14050it [47:38,  5.05it/s]

true
Determine whether the semantic relation where interferon is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ZFP36 ring finger protein like 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14051it [47:39,  5.01it/s]

true
Determine whether the semantic relation where Vinculin is the subject, biological process is the predicate, and muscle contraction is the object constitutes an accurate semantic relation.

14053it [47:39,  5.05it/s]

false
Determine whether the semantic relation where Leishmania is the subject, has natural reservoir is the predicate, and Rodent is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rodent is the subject, natural reservoir of is the predicate, and Leishmania is the object constitutes an accurate semantic relation.

14055it [47:39,  5.18it/s]

false
Determine whether the semantic relation where Kosovo is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where necrotizing enterocolitis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

14056it [47:40,  4.95it/s]

true
Determine whether the semantic relation where cavity of bony thorax is the subject, has part(s) is the predicate, and heart is the object constitutes an accurate semantic relation.

14057it [47:40,  4.84it/s]

true
Determine whether the semantic relation where Cathepsin L is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14059it [47:40,  4.96it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Kosovo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

14061it [47:41,  5.00it/s]

true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Manitoba is the subject, shares border with is the predicate, and Minnesota is the object constitutes an accurate semantic relation.

14063it [47:41,  5.24it/s]

true
Determine whether the semantic relation where Minnesota is the subject, shares border with is the predicate, and Manitoba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where heart is the subject, anatomical location is the predicate, and cavity of bony thorax is the object constitutes an accurate semantic relation.

14064it [47:41,  5.30it/s]

true
Determine whether the semantic relation where biotin is the subject, found in taxon is the predicate, and Achromobacter is the object constitutes an accurate semantic relation.

14066it [47:42,  4.86it/s]

false
Determine whether the semantic relation where neurogenic arthropathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where calcium phosphate is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

14068it [47:42,  4.96it/s]

true
Determine whether the semantic relation where clonazepam is the subject, medical condition treated is the predicate, and post-traumatic stress disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where post-traumatic stress disorder is the subject, drug or therapy used for treatment is the predicate, and clonazepam is the object constitutes an accurate semantic relation.

14070it [47:42,  5.09it/s]

true
Determine whether the semantic relation where receptor interacting serine/threonine kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hippuric acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

14071it [47:43,  5.13it/s]

true
Determine whether the semantic relation where miliary tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14073it [47:43,  4.90it/s]

true
Determine whether the semantic relation where propidium is the subject, subclass of is the predicate, and cation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lynch syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14074it [47:43,  5.04it/s]

true
Determine whether the semantic relation where hydronephrosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14076it [47:44,  4.90it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.

14078it [47:44,  5.04it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and United States is the object constitutes an accurate semantic relation.

14080it [47:44,  5.10it/s]

true
Determine whether the semantic relation where amebiasis is the subject, has part(s) is the predicate, and hepatitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Belarus is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

14081it [47:45,  4.98it/s]

true
Determine whether the semantic relation where neutral red is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14082it [47:45,  4.80it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

14084it [47:45,  4.86it/s]

true
Determine whether the semantic relation where autoanalysis is the subject, subclass of is the predicate, and laboratory diagnostics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiotepa is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

14086it [47:46,  4.57it/s]

true
Determine whether the semantic relation where sarcosine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tick-borne encephalitis is the subject, drug or therapy used for treatment is the predicate, and immunoglobulin therapy is the object constitutes an accurate semantic relation.

14088it [47:46,  4.77it/s]

true
Determine whether the semantic relation where hemolymph is the subject, subclass of is the predicate, and body fluid is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase kinase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14090it [47:47,  4.99it/s]

true
Determine whether the semantic relation where collagen is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Proliferating cell nuclear antigen is the subject, biological process is the predicate, and estrous cycle is the object constitutes an accurate semantic relation.

14092it [47:47,  5.09it/s]

false
Determine whether the semantic relation where potassium chloride is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and (RS)-sulpiride is the object constitutes an accurate semantic relation.

14094it [47:47,  4.87it/s]

true
Determine whether the semantic relation where (RS)-sulpiride is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

14095it [47:48,  4.23it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

14097it [47:48,  4.64it/s]

true
Determine whether the semantic relation where oligomenorrhea is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quinidine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

14099it [47:49,  4.84it/s]

true
Determine whether the semantic relation where pyloric stenosis is the subject, health specialty is the predicate, and general surgery is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Daucus carota is the subject, invasive to is the predicate, and Ontario is the object constitutes an accurate semantic relation.

14101it [47:49,  4.47it/s]

false
Determine whether the semantic relation where anorexia nervosa is the subject, drug or therapy used for treatment is the predicate, and tetrahydrocannabinol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetrahydrocannabinol is the subject, medical condition treated is the predicate, and anorexia nervosa is the object constitutes an accurate semantic relation.

14103it [47:49,  4.81it/s]

maybe
Determine whether the semantic relation where Diclofenac is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and Diclofenac is the object constitutes an accurate semantic relation.

14105it [47:50,  5.13it/s]

true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BRCA1 is the subject, cell component is the predicate, and ribonucleoprotein complex is the object constitutes an accurate semantic relation.

14106it [47:50,  5.19it/s]

false
Determine whether the semantic relation where glutathione S-transferase, pi class is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

14108it [47:50,  5.06it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chloral hydrate is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

14110it [47:51,  5.05it/s]

true
Determine whether the semantic relation where cytochalasin B is the subject, subclass of is the predicate, and macrolides is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.

14111it [47:51,  5.12it/s]

true
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and methylprednisolone is the object constitutes an accurate semantic relation.

14113it [47:51,  5.15it/s]

true
Determine whether the semantic relation where methylprednisolone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where single person is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.

14114it [47:52,  5.06it/s]

false
Determine whether the semantic relation where Cathepsin K is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14116it [47:52,  4.69it/s]

true
Determine whether the semantic relation where Cathepsin K is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eosinophilic esophagitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

14117it [47:52,  4.70it/s]

true
Determine whether the semantic relation where intussusception is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.

14119it [47:53,  4.88it/s]

false
Determine whether the semantic relation where celebrity is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where monensin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

14121it [47:53,  4.93it/s]

false
Determine whether the semantic relation where drop-outs is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where food allergy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14122it [47:53,  4.72it/s]

true
Determine whether the semantic relation where peripheral vascular disease is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14123it [47:53,  4.66it/s]

false
Determine whether the semantic relation where giardiasis is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

14125it [47:54,  4.90it/s]

true
Determine whether the semantic relation where thiourea is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and dicloxacillin is the object constitutes an accurate semantic relation.

14126it [47:54,  5.11it/s]

maybe
Determine whether the semantic relation where dicloxacillin is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.

14128it [47:54,  4.97it/s]

true
Determine whether the semantic relation where Solute carrier family 12 member 2 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cathepsin B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14130it [47:55,  5.16it/s]

false
Determine whether the semantic relation where health services research is the subject, subclass of is the predicate, and health care quality is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Q15978181 is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.

14131it [47:55,  5.22it/s]

false
Determine whether the semantic relation where parathyroid hormone like hormone is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

14133it [47:55,  5.06it/s]

true
Determine whether the semantic relation where homeless person is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where expressive aphasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14135it [47:56,  5.14it/s]

true
Determine whether the semantic relation where research participant is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbonic acid is the subject, different from is the predicate, and phenol is the object constitutes an accurate semantic relation.

14137it [47:56,  5.34it/s]

true
Determine whether the semantic relation where splenomegaly is the subject, medical examination is the predicate, and medical ultrasonography is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where first responder is the subject, subclass of is the predicate, and person is the object constitutes an accurate semantic relation.

14138it [47:56,  5.37it/s]

true
Determine whether the semantic relation where bacteriochlorophylls is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

14140it [47:57,  5.24it/s]

true
Determine whether the semantic relation where outpatient surgery is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where central hearing loss is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

14142it [47:57,  5.22it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.
false

14143it [47:57,  5.38it/s]

Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyclin D1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

14144it [47:58,  5.25it/s]

false
Determine whether the semantic relation where coccidioidomycosis is the subject, symptoms and signs is the predicate, and conjunctivitis is the object constitutes an accurate semantic relation.

14145it [47:58,  5.08it/s]

true
Determine whether the semantic relation where β-carotene is the subject, found in taxon is the predicate, and Ciona intestinalis is the object constitutes an accurate semantic relation.

14147it [47:58,  4.90it/s]

false
Determine whether the semantic relation where blue toe syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EPH receptor B4 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14149it [47:59,  5.05it/s]

true
Determine whether the semantic relation where heart valve disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphocytic choriomeningitis is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

14151it [47:59,  5.23it/s]

false
Determine whether the semantic relation where acne is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD24 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14153it [47:59,  5.17it/s]

true
Determine whether the semantic relation where enoxolone is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where calcium sensing receptor is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

14155it [48:00,  5.14it/s]

false
Determine whether the semantic relation where SCF ubiquitin ligase complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where anthracene is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

14157it [48:00,  5.24it/s]

false
Determine whether the semantic relation where aspiration pneumonia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ras homolog family member A is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

14159it [48:01,  5.08it/s]

false
Determine whether the semantic relation where Tunisia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Samoa is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

14160it [48:01,  5.03it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Samoa is the object constitutes an accurate semantic relation.

14162it [48:01,  5.04it/s]

false
Determine whether the semantic relation where interleukin-2 is the subject, subject has role is the predicate, and antineoplastic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where decalcification is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14164it [48:02,  5.05it/s]

false
Determine whether the semantic relation where primary headache disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14166it [48:02,  5.03it/s]

true
Determine whether the semantic relation where chikungunya is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cryptorchidism is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

14168it [48:02,  4.83it/s]

maybe
Determine whether the semantic relation where C-C motif chemokine ligand 11 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intertrigo is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14170it [48:03,  5.02it/s]

true
Determine whether the semantic relation where Kallmann syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transcription factor 7 like 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

14172it [48:03,  5.12it/s]

false
Determine whether the semantic relation where Nuclear factor kappa B subunit 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where embryology is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.

14174it [48:03,  5.18it/s]

true
Determine whether the semantic relation where Cathepsin D is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin D is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

14176it [48:04,  5.28it/s]

true
Determine whether the semantic relation where arteriosclerosis obliterans is the subject, subclass of is the predicate, and coronary artery disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where SMAD family member 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14178it [48:04,  5.08it/s]

true
Determine whether the semantic relation where GNAS complex locus is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

14179it [48:04,  5.15it/s]

true
Determine whether the semantic relation where Malaysia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14181it [48:05,  5.04it/s]

true
Determine whether the semantic relation where tear is the subject, has part(s) is the predicate, and sodium chloride is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

14182it [48:05,  5.07it/s]

true
Determine whether the semantic relation where Parkinson's disease is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.

14184it [48:06,  4.88it/s]

false
Determine whether the semantic relation where acromegaly is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurological disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14185it [48:06,  5.12it/s]

true
Determine whether the semantic relation where neurological disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14187it [48:06,  5.04it/s]

true
Determine whether the semantic relation where atypical chemokine receptor 1 (Duffy blood group) is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, medical examination is the predicate, and viral culture is the object constitutes an accurate semantic relation.

14189it [48:06,  4.99it/s]

false
Determine whether the semantic relation where anogenital venereal wart is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myocardial infarction is the subject, drug or therapy used for treatment is the predicate, and labetalol is the object constitutes an accurate semantic relation.

14191it [48:07,  5.19it/s]

true
Determine whether the semantic relation where labetalol is the subject, medical condition treated is the predicate, and myocardial infarction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where depression is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

14193it [48:07,  5.34it/s]

true
Determine whether the semantic relation where vaccination is the subject, uses is the predicate, and injection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where angiotensin II receptor type 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14195it [48:08,  5.21it/s]

false
Determine whether the semantic relation where ulcerative colitis is the subject, drug or therapy used for treatment is the predicate, and methotrexate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methotrexate is the subject, medical condition treated is the predicate, and ulcerative colitis is the object constitutes an accurate semantic relation.

14197it [48:08,  5.23it/s]

true
Determine whether the semantic relation where educational stage is the subject, has part(s) is the predicate, and continuing education is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thymoma is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14199it [48:08,  5.20it/s]

true
Determine whether the semantic relation where continuing education is the subject, instance of is the predicate, and educational stage is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hexose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

14201it [48:09,  5.25it/s]

true
Determine whether the semantic relation where amphotericin B is the subject, medical condition treated is the predicate, and cystitis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neurobehavioral manifestation is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14203it [48:09,  5.25it/s]

false
Determine whether the semantic relation where RNA polymerase I is the subject, subclass of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystitis is the subject, drug or therapy used for treatment is the predicate, and amphotericin B is the object constitutes an accurate semantic relation.

14205it [48:10,  5.27it/s]

false
Determine whether the semantic relation where zinc oxide is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and zinc oxide is the object constitutes an accurate semantic relation.

14207it [48:10,  5.13it/s]

true
Determine whether the semantic relation where cat-scratch disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where levamisole is the subject, subject has role is the predicate, and disease-modifying antirheumatic drug is the object constitutes an accurate semantic relation.

14209it [48:10,  5.43it/s]

true
Determine whether the semantic relation where pancreatic pseudocyst is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where immunohistochemistry is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

14211it [48:11,  5.32it/s]

false
Determine whether the semantic relation where hidradenitis suppurativa is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where guanosine monophosphate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

14213it [48:11,  5.30it/s]

true
Determine whether the semantic relation where multiple pulmonary nodules is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where book is the subject, has use is the predicate, and pleasure is the object constitutes an accurate semantic relation.

14215it [48:11,  5.26it/s]

true
Determine whether the semantic relation where angiotensin II receptor type 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where fluorenes is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

14217it [48:12,  5.04it/s]

false
Determine whether the semantic relation where hepatitis is the subject, has cause is the predicate, and autoimmunity is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

14219it [48:12,  5.14it/s]

true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where extramammary Paget's disease is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

14220it [48:12,  5.15it/s]

true
Determine whether the semantic relation where nitroglycerin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14222it [48:13,  5.07it/s]

false
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where headache disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14224it [48:13,  4.82it/s]

true
Determine whether the semantic relation where epidemic typhus is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nuclear receptor subfamily 3 group C member 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14226it [48:14,  4.99it/s]

true
Determine whether the semantic relation where glial fibrillary acidic protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and disopyramide is the object constitutes an accurate semantic relation.

14228it [48:14,  4.81it/s]

true
Determine whether the semantic relation where EPH receptor B1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

14230it [48:14,  5.14it/s]

true
Determine whether the semantic relation where cortisol is the subject, medical condition treated is the predicate, and hemorrhoid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glycogen phosphorylase B is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

14232it [48:15,  5.15it/s]

false
Determine whether the semantic relation where disopyramide is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

14234it [48:15,  5.29it/s]

true
Determine whether the semantic relation where type 2 diabetes is the subject, symptoms and signs is the predicate, and polyuria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD2 molecule is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14235it [48:15,  5.19it/s]

true
Determine whether the semantic relation where hemorrhoid is the subject, drug or therapy used for treatment is the predicate, and cortisol is the object constitutes an accurate semantic relation.

14237it [48:16,  5.13it/s]

false
Determine whether the semantic relation where keratoconjunctivitis sicca is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ginger is the subject, has use is the predicate, and vegetable is the object constitutes an accurate semantic relation.

14239it [48:16,  5.16it/s]

false
Determine whether the semantic relation where DNA polymerase III complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where egtazic acid is the subject, subject has role is the predicate, and antidote is the object constitutes an accurate semantic relation.

14240it [48:17,  4.39it/s]

false
Determine whether the semantic relation where generalized epilepsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14242it [48:17,  4.69it/s]

true
Determine whether the semantic relation where channelopathy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vascular dementia is the subject, possible treatment is the predicate, and statin is the object constitutes an accurate semantic relation.

14244it [48:17,  4.83it/s]

maybe
Determine whether the semantic relation where ATP binding cassette subfamily B member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where crystallin alpha A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14246it [48:18,  5.04it/s]

false
Determine whether the semantic relation where interleukin-10 receptor is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gibberellins is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14247it [48:18,  5.03it/s]

false
Determine whether the semantic relation where stroke is the subject, subclass of is the predicate, and neurological symptom is the object constitutes an accurate semantic relation.

14249it [48:18,  5.06it/s]

true
Determine whether the semantic relation where esophageal neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Alagille syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

14251it [48:19,  5.24it/s]

true
Determine whether the semantic relation where parapsoriasis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transurethral resection of the prostate is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.

14253it [48:19,  5.38it/s]

true
Determine whether the semantic relation where chronic granulomatous disease is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Salvia miltiorrhiza is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

14254it [48:19,  5.32it/s]

true
Determine whether the semantic relation where Histamine receptor H2 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

14256it [48:20,  4.99it/s]

false
Determine whether the semantic relation where homovanillic acid is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where organometallic compound is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14258it [48:20,  5.01it/s]

true
Determine whether the semantic relation where Galectin 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mitogen-activated protein kinase kinase kinase 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14260it [48:20,  5.02it/s]

true
Determine whether the semantic relation where tularemia is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where common variable immunodeficiency is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

14261it [48:21,  5.10it/s]

true
Determine whether the semantic relation where familial Mediterranean fever is the subject, symptoms and signs is the predicate, and chest pain is the object constitutes an accurate semantic relation.

14263it [48:21,  5.10it/s]

true
Determine whether the semantic relation where chloroquine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where perinatal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14265it [48:21,  5.01it/s]

true
Determine whether the semantic relation where dimpylate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where genistein is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

14266it [48:22,  4.71it/s]

false
Determine whether the semantic relation where estrone is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

14267it [48:22,  4.76it/s]

maybe
Determine whether the semantic relation where glycoside is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14269it [48:22,  4.99it/s]

false
Determine whether the semantic relation where echinococcosis is the subject, medical examination is the predicate, and magnetic resonance imaging is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where succinic acid is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.

14270it [48:23,  4.80it/s]

false
Determine whether the semantic relation where sorbic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14272it [48:23,  4.82it/s]

true
Determine whether the semantic relation where Japanese encephalitis is the subject, symptoms and signs is the predicate, and coma is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

14274it [48:23,  5.04it/s]

true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where central nervous system viral disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14275it [48:24,  5.18it/s]

true
Determine whether the semantic relation where tryptophan 2,3-dioxygenase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14276it [48:24,  4.99it/s]

false
Determine whether the semantic relation where Algeria is the subject, shares border with is the predicate, and Italy is the object constitutes an accurate semantic relation.

14278it [48:24,  4.96it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amiodarone is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.

14280it [48:25,  4.96it/s]

true
Determine whether the semantic relation where Goodpasture syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and amiodarone is the object constitutes an accurate semantic relation.

14282it [48:25,  4.97it/s]

true
Determine whether the semantic relation where infanticide is the subject, participant is the predicate, and child is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypoactive sexual desire disorder is the subject, health specialty is the predicate, and gynaecology is the object constitutes an accurate semantic relation.

14283it [48:25,  4.44it/s]

maybe
Determine whether the semantic relation where Forkhead box A1 is the subject, cell component is the predicate, and microvillus is the object constitutes an accurate semantic relation.
false

14284it [48:25,  4.58it/s]

Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

14286it [48:26,  4.79it/s]

true
Determine whether the semantic relation where severe combined immunodeficiency is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and (RS)-etodolac is the object constitutes an accurate semantic relation.

14288it [48:26,  5.09it/s]

true
Determine whether the semantic relation where Huntington's disease is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Neurofibromin 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14290it [48:27,  5.15it/s]

true
Determine whether the semantic relation where group 16 is the subject, followed by is the predicate, and halogens is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where substance-related disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

14291it [48:27,  5.27it/s]

true
Determine whether the semantic relation where benzyl alcohol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14293it [48:27,  5.12it/s]

false
Determine whether the semantic relation where aviation is the subject, has use is the predicate, and recreation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where putrescine is the subject, found in taxon is the predicate, and Atropa bella-donna is the object constitutes an accurate semantic relation.

14295it [48:28,  5.30it/s]

true
Determine whether the semantic relation where acute disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where restless legs syndrome is the subject, subclass of is the predicate, and central nervous system disease is the object constitutes an accurate semantic relation.

14296it [48:28,  4.98it/s]

true
Determine whether the semantic relation where respiratory syncytial virus infectious disease is the subject, symptoms and signs is the predicate, and cyanosis is the object constitutes an accurate semantic relation.

14298it [48:28,  5.12it/s]

true
Determine whether the semantic relation where stereotypic movement disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where maltose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

14299it [48:28,  5.26it/s]

false
Determine whether the semantic relation where phospholipase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14301it [48:29,  5.18it/s]

true
Determine whether the semantic relation where ornithosis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

14303it [48:29,  5.19it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Georgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rocky Mountain spotted fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

14305it [48:30,  5.12it/s]

true
Determine whether the semantic relation where India is the subject, diplomatic relation is the predicate, and Kenya is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-Cysteine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

14306it [48:30,  5.09it/s]

false
Determine whether the semantic relation where Kenya is the subject, diplomatic relation is the predicate, and India is the object constitutes an accurate semantic relation.
true

14308it [48:30,  5.06it/s]

Determine whether the semantic relation where marketing is the subject, subclass of is the predicate, and research is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cameroon is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

14309it [48:30,  5.16it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Cameroon is the object constitutes an accurate semantic relation.

14311it [48:31,  5.06it/s]

true
Determine whether the semantic relation where threonine phosphate is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Amphiregulin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14312it [48:31,  4.96it/s]

true
Determine whether the semantic relation where water is the subject, part of is the predicate, and food is the object constitutes an accurate semantic relation.

14314it [48:31,  4.76it/s]

false
Determine whether the semantic relation where cardiac tamponade is the subject, has cause is the predicate, and kidney failure is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Timor-Leste is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14316it [48:32,  4.93it/s]

true
Determine whether the semantic relation where opisthorchiasis is the subject, symptoms and signs is the predicate, and pancreatitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where familial hypercholesterolemia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

14318it [48:32,  5.00it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ADCYAP receptor type I is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14319it [48:32,  5.02it/s]

true
Determine whether the semantic relation where embolism and thrombosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14320it [48:33,  4.76it/s]

true
Determine whether the semantic relation where nephrogenic diabetes insipidus is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14322it [48:33,  4.62it/s]

true
Determine whether the semantic relation where calcium sensing receptor is the subject, cell component is the predicate, and axon terminus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Caspase 8 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14324it [48:34,  4.47it/s]

false
Determine whether the semantic relation where Mobius syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cyclin/CDK positive transcription elongation factor complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

14326it [48:34,  4.75it/s]

false
Determine whether the semantic relation where Singapore is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiourea is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

14328it [48:34,  4.91it/s]

true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.

14330it [48:35,  5.17it/s]

true
Determine whether the semantic relation where methyl cellulose is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ancient Rome is the subject, continent is the predicate, and Africa is the object constitutes an accurate semantic relation.

14332it [48:35,  4.96it/s]

false
Determine whether the semantic relation where methylprednisolone is the subject, medical condition treated is the predicate, and congenital adrenal hyperplasia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hantavirus pulmonary syndrome is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

14333it [48:35,  5.11it/s]

true
Determine whether the semantic relation where congenital adrenal hyperplasia is the subject, drug or therapy used for treatment is the predicate, and methylprednisolone is the object constitutes an accurate semantic relation.

14335it [48:36,  5.06it/s]

true
Determine whether the semantic relation where captopril is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin-12 receptor is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

14336it [48:36,  5.05it/s]

true
Determine whether the semantic relation where High mobility group AT-hook 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14338it [48:36,  4.95it/s]

true
Determine whether the semantic relation where Chlorella is the subject, instance of is the predicate, and food is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

14340it [48:37,  5.03it/s]

true
Determine whether the semantic relation where Tunisia is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where gallstone is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

14341it [48:37,  4.95it/s]

true
Determine whether the semantic relation where galantamine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

14342it [48:37,  4.71it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 13 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14343it [48:38,  3.99it/s]

true
Determine whether the semantic relation where Austria is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14344it [48:38,  4.16it/s]

true
Determine whether the semantic relation where Dopamine receptor D4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14345it [48:38,  4.20it/s]

true
Determine whether the semantic relation where Mexico is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

14346it [48:38,  4.39it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

14347it [48:38,  4.50it/s]

true
Determine whether the semantic relation where HAM is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14348it [48:39,  4.55it/s]

true
Determine whether the semantic relation where United States is the subject, shares border with is the predicate, and Mexico is the object constitutes an accurate semantic relation.

14350it [48:39,  4.73it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glycogen storage disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14352it [48:39,  5.10it/s]

true
Determine whether the semantic relation where mouth disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where elastin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14354it [48:40,  5.35it/s]

false
Determine whether the semantic relation where diphtheria toxin is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where kinase insert domain receptor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

14355it [48:40,  5.29it/s]

false
Determine whether the semantic relation where Phosphofructokinase, platelet is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14357it [48:40,  4.91it/s]

true
Determine whether the semantic relation where SMAD family member 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where EcoRI is the subject, subclass of is the predicate, and DNA-binding protein is the object constitutes an accurate semantic relation.

14359it [48:41,  5.03it/s]

true
Determine whether the semantic relation where Caenorhabditis elegans is the subject, has part(s) of the class is the predicate, and cell is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Malaysia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

14361it [48:41,  5.02it/s]

true
Determine whether the semantic relation where New Zealand is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and paresis is the object constitutes an accurate semantic relation.

14362it [48:41,  5.10it/s]

true
Determine whether the semantic relation where utrophin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

14364it [48:42,  4.73it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and New Zealand is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where interstitial lung disease is the subject, drug or therapy used for treatment is the predicate, and cyclosporine is the object constitutes an accurate semantic relation.

14366it [48:42,  4.84it/s]

maybe
Determine whether the semantic relation where cyclosporine is the subject, medical condition treated is the predicate, and interstitial lung disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Turkmenistan is the object constitutes an accurate semantic relation.

14367it [48:42,  4.80it/s]

true
Determine whether the semantic relation where melatonin is the subject, found in taxon is the predicate, and Glycyrrhiza uralensis is the object constitutes an accurate semantic relation.

14368it [48:43,  4.79it/s]

false
Determine whether the semantic relation where pyrene is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

14370it [48:43,  4.94it/s]

false
Determine whether the semantic relation where cytosine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Turkmenistan is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

14371it [48:43,  4.88it/s]

true
Determine whether the semantic relation where angiomyoma is the subject, anatomical location is the predicate, and blood vessel is the object constitutes an accurate semantic relation.

14372it [48:44,  4.50it/s]

false
Determine whether the semantic relation where insurance is the subject, part of is the predicate, and risk management is the object constitutes an accurate semantic relation.

14374it [48:44,  4.72it/s]

true
Determine whether the semantic relation where dihydrotestosterone is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lovastatin is the subject, significant drug interaction is the predicate, and verapamil is the object constitutes an accurate semantic relation.

14375it [48:44,  4.87it/s]

true
Determine whether the semantic relation where cholecystokinin is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14377it [48:45,  4.90it/s]

true
Determine whether the semantic relation where ribonuclease III is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Tunisia is the object constitutes an accurate semantic relation.

14379it [48:45,  4.97it/s]

true
Determine whether the semantic relation where work is the subject, opposite of is the predicate, and recreation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where recreation is the subject, opposite of is the predicate, and work is the object constitutes an accurate semantic relation.

14381it [48:45,  4.58it/s]

true
Determine whether the semantic relation where glycogen is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L-argininosuccinic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

14383it [48:46,  4.82it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, medical condition treated is the predicate, and anxiety disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14385it [48:46,  5.19it/s]

true
Determine whether the semantic relation where goal is the subject, different from is the predicate, and prison is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where El Salvador is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

14387it [48:47,  5.29it/s]

true
Determine whether the semantic relation where anxiety disorder is the subject, drug or therapy used for treatment is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where branchial cleft cyst is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

14389it [48:47,  5.34it/s]

false
Determine whether the semantic relation where influenza is the subject, anatomical location is the predicate, and respiratory system is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and El Salvador is the object constitutes an accurate semantic relation.

14391it [48:47,  5.13it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and European Union is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where European Union is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

14393it [48:48,  5.33it/s]

true
Determine whether the semantic relation where ataxia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Korean War is the subject, participant is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

14394it [48:48,  4.66it/s]

true
Determine whether the semantic relation where schizophrenic psychology is the subject, part of is the predicate, and psychology is the object constitutes an accurate semantic relation.

14396it [48:48,  4.84it/s]

true
Determine whether the semantic relation where schizophrenic psychology is the subject, part of is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where powder is the subject, fabrication method is the predicate, and precipitation is the object constitutes an accurate semantic relation.

14397it [48:49,  4.90it/s]

false
Determine whether the semantic relation where morphinan is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

14398it [48:49,  4.91it/s]

false
Determine whether the semantic relation where color blindness is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14400it [48:49,  4.98it/s]

true
Determine whether the semantic relation where hypertrophic pyloric stenosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

14401it [48:49,  4.86it/s]

true
Determine whether the semantic relation where carbon monoxide poisoning is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

14403it [48:50,  4.90it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

14404it [48:50,  5.07it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

14406it [48:50,  5.01it/s]

true
Determine whether the semantic relation where elementary particle is the subject, interaction is the predicate, and gravity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cor pulmonale is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14408it [48:51,  5.28it/s]

true
Determine whether the semantic relation where phenylbutazone is the subject, physically interacts with is the predicate, and Prostaglandin-endoperoxide synthase 1 is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14409it [48:51,  5.41it/s]

false
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, physically interacts with is the predicate, and phenylbutazone is the object constitutes an accurate semantic relation.

14411it [48:51,  5.21it/s]

true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meningoencephalitis is the subject, subclass of is the predicate, and neurological symptom is the object constitutes an accurate semantic relation.

14412it [48:51,  5.26it/s]

false
Determine whether the semantic relation where FES proto-oncogene, tyrosine kinase is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14413it [48:52,  4.67it/s]

true
Determine whether the semantic relation where (E)-chlorprothixene (Z according to WHO INN RL 40, conflated wikidata) is the subject, subject has role is the predicate, and alpha blocker is the object constitutes an accurate semantic relation.

14415it [48:52,  4.80it/s]

false
Determine whether the semantic relation where Colony stimulating factor 3 receptor is the subject, biological process is the predicate, and cell adhesion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where bone morphogenetic protein 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14416it [48:52,  4.58it/s]

true
Determine whether the semantic relation where Gulf War is the subject, participant is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

14418it [48:53,  4.65it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Timor-Leste is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cholera is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.

14419it [48:53,  4.65it/s]

true
Determine whether the semantic relation where Timor-Leste is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.

14420it [48:53,  4.57it/s]

true
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

14422it [48:54,  4.59it/s]

false
Determine whether the semantic relation where cyclosporine is the subject, medical condition treated is the predicate, and myasthenia gravis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where LDL receptor related protein 5 is the subject, biological process is the predicate, and endocytosis is the object constitutes an accurate semantic relation.

14424it [48:54,  4.82it/s]

false
Determine whether the semantic relation where CD14 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myasthenia gravis is the subject, drug or therapy used for treatment is the predicate, and cyclosporine is the object constitutes an accurate semantic relation.

14426it [48:54,  5.04it/s]

true
Determine whether the semantic relation where epidemiological method is the subject, facet of is the predicate, and epidemiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hexestrol is the subject, subject has role is the predicate, and hormonal antineoplastic agent is the object constitutes an accurate semantic relation.

14428it [48:55,  4.79it/s]

true
Determine whether the semantic relation where prostacyclin is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cerebral venous sinus thrombosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14430it [48:55,  4.95it/s]

true
Determine whether the semantic relation where health care resources is the subject, field of work is the predicate, and health is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where schizotypal personality disorder is the subject, possible treatment is the predicate, and antidepressant is the object constitutes an accurate semantic relation.

14431it [48:56,  5.06it/s]

true
Determine whether the semantic relation where erysipelas is the subject, drug or therapy used for treatment is the predicate, and ciprofloxacin is the object constitutes an accurate semantic relation.

14433it [48:56,  4.98it/s]

false
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Klüver–Bucy syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14434it [48:56,  5.06it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

14435it [48:56,  4.90it/s]

true
Determine whether the semantic relation where Perilla frutescens is the subject, has use is the predicate, and vegetable is the object constitutes an accurate semantic relation.

14437it [48:57,  4.98it/s]

true
Determine whether the semantic relation where inhalation is the subject, instance of is the predicate, and route of administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phospholipase A2 group VI is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

14438it [48:57,  4.59it/s]

false
Determine whether the semantic relation where research expedition is the subject, subclass of is the predicate, and research is the object constitutes an accurate semantic relation.

14439it [48:57,  4.37it/s]

false
Determine whether the semantic relation where neurotensin is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

14441it [48:58,  4.60it/s]

false
Determine whether the semantic relation where sudden infant death syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurofibromatoses is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14442it [48:58,  4.77it/s]

true
Determine whether the semantic relation where cathepsin F is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14443it [48:58,  4.82it/s]

true
Determine whether the semantic relation where tonsillitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14445it [48:58,  4.84it/s]

true
Determine whether the semantic relation where zidovudine is the subject, route of administration is the predicate, and intravenous infusion and defusion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hepatic encephalopathy is the subject, symptoms and signs is the predicate, and euphoria is the object constitutes an accurate semantic relation.

14447it [48:59,  5.07it/s]

false
Determine whether the semantic relation where cytochrome c, somatic is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Heterogeneous nuclear ribonucleoprotein L is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

14448it [48:59,  5.17it/s]

false
Determine whether the semantic relation where thiamine(1+) ion is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

14449it [48:59,  4.56it/s]

false
Determine whether the semantic relation where hyperandrogenism is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14450it [49:00,  4.59it/s]

true
Determine whether the semantic relation where hyperandrogenism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14452it [49:00,  4.07it/s]

true
Determine whether the semantic relation where electrode is the subject, connects with is the predicate, and electrolyte is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where biotin is the subject, subclass of is the predicate, and carboxylic acid is the object constitutes an accurate semantic relation.

14454it [49:00,  4.67it/s]

false
Determine whether the semantic relation where chorismic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where TATA-box binding protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14455it [49:01,  4.94it/s]

false
Determine whether the semantic relation where Clock circadian regulator is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

14457it [49:01,  4.91it/s]

false
Determine whether the semantic relation where Von Hippel-Lindau tumor suppressor is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

14458it [49:01,  4.88it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

14459it [49:01,  4.88it/s]

true
Determine whether the semantic relation where extra-adrenal paraganglioma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14461it [49:02,  4.77it/s]

true
Determine whether the semantic relation where Serpin family E member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Russia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

14462it [49:02,  4.95it/s]

true
Determine whether the semantic relation where plague is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

14463it [49:02,  4.51it/s]

false
Determine whether the semantic relation where G protein-coupled receptor kinase 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

14465it [49:03,  4.65it/s]

false
Determine whether the semantic relation where LIF receptor subunit alpha is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inherited metabolic disorder is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14466it [49:03,  4.79it/s]

true
Determine whether the semantic relation where organ torsion is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14468it [49:03,  4.86it/s]

true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where occludin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14470it [49:04,  5.08it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

14472it [49:04,  5.21it/s]

true
Determine whether the semantic relation where Hexosaminidase subunit alpha is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where megacolon is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

14473it [49:04,  5.06it/s]

true
Determine whether the semantic relation where CREB binding protein is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14475it [49:05,  5.05it/s]

false
Determine whether the semantic relation where conditioning is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where conditioning is the subject, studied by is the predicate, and psychology is the object constitutes an accurate semantic relation.

14477it [49:05,  5.22it/s]

true
Determine whether the semantic relation where Southern Africa is the subject, shares border with is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Inositol-3-phosphate synthase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14478it [49:05,  5.28it/s]

true
Determine whether the semantic relation where mitogen-activated protein kinase 14 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

14480it [49:06,  5.15it/s]

true
Determine whether the semantic relation where nocturnal enuresis is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

14482it [49:06,  5.19it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tracheal disease is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

14484it [49:07,  5.07it/s]

true
Determine whether the semantic relation where shock is the subject, instance of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where taurine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14486it [49:07,  5.08it/s]

true
Determine whether the semantic relation where leprosy is the subject, symptoms and signs is the predicate, and keratitis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where propoxur is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

14487it [49:07,  5.07it/s]

true
Determine whether the semantic relation where encephalomyelitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14488it [49:07,  4.72it/s]

true
Determine whether the semantic relation where chloroquine is the subject, medical condition treated is the predicate, and systemic scleroderma is the object constitutes an accurate semantic relation.

14490it [49:08,  4.83it/s]

false
Determine whether the semantic relation where systemic scleroderma is the subject, drug or therapy used for treatment is the predicate, and chloroquine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mastitis is the subject, health specialty is the predicate, and gynaecology is the object constitutes an accurate semantic relation.

14492it [49:08,  5.00it/s]

false
Determine whether the semantic relation where aluminium oxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Parkinson's disease is the subject, symptoms and signs is the predicate, and spasticity is the object constitutes an accurate semantic relation.

14494it [49:09,  5.16it/s]

false
Determine whether the semantic relation where Nuclear factor kappa B subunit 2 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where listeriosis is the subject, symptoms and signs is the predicate, and hepatomegaly is the object constitutes an accurate semantic relation.

14496it [49:09,  5.23it/s]

true
Determine whether the semantic relation where chemical burn is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlorpromazine is the subject, physically interacts with is the predicate, and Dopamine receptor D4 is the object constitutes an accurate semantic relation.

14498it [49:09,  5.26it/s]

true
Determine whether the semantic relation where celiac disease is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypereosinophilic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14500it [49:10,  5.11it/s]

true
Determine whether the semantic relation where glucaric acid is the subject, subclass of is the predicate, and dicarboxylic acid is the object constitutes an accurate semantic relation.
true

14501it [49:10,  5.07it/s]

Determine whether the semantic relation where myelitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myeloperoxidase is the subject, subclass of is the predicate, and heme protein is the object constitutes an accurate semantic relation.

14502it [49:10,  4.95it/s]

true
Determine whether the semantic relation where Charcot–Marie–Tooth disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14503it [49:10,  4.34it/s]

true
Determine whether the semantic relation where Dopamine receptor D4 is the subject, physically interacts with is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.

14505it [49:11,  4.65it/s]

true
Determine whether the semantic relation where collagen disease is the subject, afflicts is the predicate, and kidney is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where progesterone congener is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14507it [49:11,  4.61it/s]

true
Determine whether the semantic relation where hepatopulmonary syndrome is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Aleutian disease is the subject, symptoms and signs is the predicate, and anemia is the object constitutes an accurate semantic relation.

14508it [49:12,  4.48it/s]

true
Determine whether the semantic relation where sick sinus syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14510it [49:12,  4.61it/s]

true
Determine whether the semantic relation where propylthiouracil is the subject, subject has role is the predicate, and protein synthesis inhibitor is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Nuclear receptor subfamily 3 group C member 2 is the subject, physically interacts with is the predicate, and prednisolone is the object constitutes an accurate semantic relation.

14511it [49:12,  4.34it/s]

false
Determine whether the semantic relation where anomic aphasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14512it [49:12,  4.39it/s]

true
Determine whether the semantic relation where nitrophenol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14514it [49:13,  4.69it/s]

true
Determine whether the semantic relation where labyrinthitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where medical needle is the subject, subclass of is the predicate, and hospital equipment and supplies is the object constitutes an accurate semantic relation.

14516it [49:13,  5.01it/s]

true
Determine whether the semantic relation where data collection is the subject, has use is the predicate, and sociology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prednisolone is the subject, physically interacts with is the predicate, and Nuclear receptor subfamily 3 group C member 2 is the object constitutes an accurate semantic relation.

14517it [49:13,  5.06it/s]

true
Determine whether the semantic relation where integrin subunit alpha 5 is the subject, cell component is the predicate, and cell-cell junction is the object constitutes an accurate semantic relation.

14519it [49:14,  5.06it/s]

false
Determine whether the semantic relation where rac-warfarin is the subject, significant drug interaction is the predicate, and fenofibrate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Survival of motor neuron 2, centromeric is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14520it [49:14,  4.84it/s]

false
Determine whether the semantic relation where mibefradil is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

14522it [49:14,  4.83it/s]

true
Determine whether the semantic relation where polylysine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where congenital diaphragmatic hernia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14524it [49:15,  4.55it/s]

true
Determine whether the semantic relation where L-isoleucine is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
false

14525it [49:15,  4.73it/s]

Determine whether the semantic relation where Janus kinase 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

14527it [49:15,  4.88it/s]

false
Determine whether the semantic relation where minichromosome maintenance complex component 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Dystrophin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14528it [49:16,  5.06it/s]

true
Determine whether the semantic relation where biliary reflux is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

14530it [49:16,  5.14it/s]

true
Determine whether the semantic relation where Russia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where blackwater fever is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14532it [49:17,  4.38it/s]

true
Determine whether the semantic relation where chickenpox is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where constipation is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14534it [49:17,  4.82it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, cell component is the predicate, and focal adhesion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dirofilariasis is the subject, subclass of is the predicate, and lung disease is the object constitutes an accurate semantic relation.

14535it [49:17,  4.94it/s]

false
Determine whether the semantic relation where Argininosuccinate lyase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14537it [49:18,  4.94it/s]

false
Determine whether the semantic relation where soman is the subject, has part(s) is the predicate, and phosphorus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arachidonic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14538it [49:18,  4.51it/s]

true
Determine whether the semantic relation where POU class 4 homeobox 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14539it [49:18,  3.90it/s]

true
Determine whether the semantic relation where calcium sulfate is the subject, has part(s) is the predicate, and calcium is the object constitutes an accurate semantic relation.

14541it [49:19,  4.33it/s]

true
Determine whether the semantic relation where papaverine is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dopamine beta-hydroxylase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14543it [49:19,  4.77it/s]

false
Determine whether the semantic relation where conditioned culture medium is the subject, instance of is the predicate, and body fluid is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tularemia is the subject, symptoms and signs is the predicate, and pneumonia is the object constitutes an accurate semantic relation.

14545it [49:19,  4.90it/s]

true
Determine whether the semantic relation where High mobility group box 3 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-threonine is the subject, found in taxon is the predicate, and Sinorhizobium meliloti is the object constitutes an accurate semantic relation.

14547it [49:20,  5.16it/s]

false
Determine whether the semantic relation where poly(methacrylic acid) is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where visceral larva migrans is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14548it [49:20,  4.95it/s]

true
Determine whether the semantic relation where cor pulmonale is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14550it [49:20,  5.02it/s]

true
Determine whether the semantic relation where out-of-hospital cardiac arrest is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spirituality is the subject, subclass of is the predicate, and cognitive process is the object constitutes an accurate semantic relation.

14552it [49:21,  4.91it/s]

false
Determine whether the semantic relation where follistatin is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where physiotherapist is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

14554it [49:21,  5.07it/s]

true
Determine whether the semantic relation where mycophenolic acid is the subject, subject has role is the predicate, and antitubercular antibiotics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Italy is the subject, member of is the predicate, and International Red Cross and Red Crescent Movement is the object constitutes an accurate semantic relation.

14555it [49:21,  5.17it/s]

false
Determine whether the semantic relation where peptoids is the subject, subclass of is the predicate, and polymer is the object constitutes an accurate semantic relation.

14557it [49:22,  5.15it/s]

true
Determine whether the semantic relation where cholecystolithiasis is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Thyroid stimulating hormone receptor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14559it [49:22,  4.99it/s]

false
Determine whether the semantic relation where overcrowding is the subject, criterion used is the predicate, and public policy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where overcrowding is the subject, has contributing factor is the predicate, and public policy is the object constitutes an accurate semantic relation.

14560it [49:22,  4.71it/s]

true
Determine whether the semantic relation where ADCYAP receptor type I is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14561it [49:23,  4.53it/s]

false
Determine whether the semantic relation where balantidiasis is the subject, drug or therapy used for treatment is the predicate, and ampicillin is the object constitutes an accurate semantic relation.

14563it [49:23,  4.40it/s]

false
Determine whether the semantic relation where epichlorohydrin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protein kinase C beta is the subject, biological process is the predicate, and platelet activation is the object constitutes an accurate semantic relation.

14565it [49:24,  4.74it/s]

true
Determine whether the semantic relation where protein kinase cGMP-dependent 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin D1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14567it [49:24,  5.11it/s]

true
Determine whether the semantic relation where Cathepsin C is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where UDP-glucose 6-dehydrogenase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

14568it [49:24,  5.24it/s]

false
Determine whether the semantic relation where obsessive-compulsive disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

14570it [49:24,  5.18it/s]

true
Determine whether the semantic relation where obsessive-compulsive disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where West Germany is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.

14572it [49:25,  5.29it/s]

true
Determine whether the semantic relation where SMAD family member 1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where coronary thrombosis is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14574it [49:25,  5.12it/s]

true
Determine whether the semantic relation where hypothyroidism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q106951292 is the subject, has use is the predicate, and food preservation is the object constitutes an accurate semantic relation.

14576it [49:26,  5.20it/s]

true
Determine whether the semantic relation where chlorambucil is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kyasanur forest disease is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

14577it [49:26,  5.23it/s]

false
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 2 is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

14578it [49:26,  5.07it/s]

true
Determine whether the semantic relation where ergoloid mesylate is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

14580it [49:26,  4.84it/s]

true
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Algeria is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Algeria is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.

14582it [49:27,  5.01it/s]

false
Determine whether the semantic relation where digestive system neoplasm is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hermeneutics is the subject, subclass of is the predicate, and occupation is the object constitutes an accurate semantic relation.

14583it [49:27,  5.06it/s]

false
Determine whether the semantic relation where milk is the subject, has part(s) is the predicate, and sodium chloride is the object constitutes an accurate semantic relation.

14584it [49:27,  4.97it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Wales is the object constitutes an accurate semantic relation.

14586it [49:28,  5.00it/s]

false
Determine whether the semantic relation where Lassa fever is the subject, symptoms and signs is the predicate, and vertigo is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiamine(1+) ion is the subject, medical condition treated is the predicate, and metabolic disease is the object constitutes an accurate semantic relation.

14588it [49:28,  5.14it/s]

false
Determine whether the semantic relation where cystitis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

14590it [49:28,  5.20it/s]

false
Determine whether the semantic relation where L-glutamine is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where capsule endoscopy is the subject, industry is the predicate, and internal medicine is the object constitutes an accurate semantic relation.

14591it [49:29,  5.29it/s]

false
Determine whether the semantic relation where Kazakhstan is the subject, shares border with is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

14593it [49:29,  5.18it/s]

true
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where forskolin is the subject, subject has role is the predicate, and immunologic adjuvant is the object constitutes an accurate semantic relation.

14594it [49:29,  5.18it/s]

false
Determine whether the semantic relation where squalene is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

14595it [49:29,  4.94it/s]

true
Determine whether the semantic relation where schizoid personality disorder is the subject, possible treatment is the predicate, and benzodiazepine drug is the object constitutes an accurate semantic relation.

14597it [49:30,  4.98it/s]

maybe
Determine whether the semantic relation where schizoid personality disorder is the subject, drug or therapy used for treatment is the predicate, and benzodiazepine drug is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where Kazakhstan is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

14599it [49:30,  5.12it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.

14601it [49:31,  5.09it/s]

true
Determine whether the semantic relation where People's Republic of China is the subject, shares border with is the predicate, and Kazakhstan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cervical incompetence is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14602it [49:31,  5.00it/s]

true
Determine whether the semantic relation where Belarus is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

14603it [49:31,  4.94it/s]

true
Determine whether the semantic relation where Carboxypeptidase E is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14604it [49:31,  4.91it/s]

true
Determine whether the semantic relation where Cyprus is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14605it [49:31,  4.62it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Belarus is the object constitutes an accurate semantic relation.

14607it [49:32,  4.80it/s]

true
Determine whether the semantic relation where Tunisia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scrofula is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14608it [49:32,  4.57it/s]

true
Determine whether the semantic relation where pertussis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

14610it [49:33,  4.83it/s]

true
Determine whether the semantic relation where adenosine diphosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Interleukin 15 receptor subunit alpha is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

14612it [49:33,  4.90it/s]

true
Determine whether the semantic relation where EPH receptor B1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where connective tissue neoplasm is the subject, location is the predicate, and connective tissue is the object constitutes an accurate semantic relation.

14614it [49:33,  5.00it/s]

true
Determine whether the semantic relation where integrin subunit beta 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where linoleic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14616it [49:34,  5.17it/s]

false
Determine whether the semantic relation where enzyme multiplied immunoassay technique is the subject, subclass of is the predicate, and laboratory diagnostics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rain is the subject, has use is the predicate, and laundry is the object constitutes an accurate semantic relation.

14618it [49:34,  5.24it/s]

false
Determine whether the semantic relation where hereditary hemorrhagic telangiectasia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

14619it [49:34,  5.26it/s]

Determine whether the semantic relation where perceptual disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sericin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14621it [49:35,  5.18it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where labyrinthitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14622it [49:35,  5.20it/s]

true
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

14623it [49:35,  5.10it/s]

true
Determine whether the semantic relation where peroxiredoxin 6 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14625it [49:35,  5.10it/s]

true
Determine whether the semantic relation where botulism is the subject, possible treatment is the predicate, and hyperbaric medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where point-of-care system is the subject, subclass of is the predicate, and biomedical engineering is the object constitutes an accurate semantic relation.

14626it [49:36,  4.47it/s]

false
Determine whether the semantic relation where violence is the subject, has effect is the predicate, and injury is the object constitutes an accurate semantic relation.

14627it [49:36,  4.34it/s]

true
Determine whether the semantic relation where phloroglucinol is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

14629it [49:36,  4.76it/s]

true
Determine whether the semantic relation where indinavir is the subject, significant drug interaction is the predicate, and carbamazepin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Lennox-Gastaut sindrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14631it [49:37,  4.85it/s]

true
Determine whether the semantic relation where beta-1,3-glucuronyltransferase 1 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nervous system lysosomal storage disease is the subject, subclass of is the predicate, and peripheral neuropathy is the object constitutes an accurate semantic relation.

14633it [49:37,  5.15it/s]

false
Determine whether the semantic relation where prednisone is the subject, medical condition treated is the predicate, and eye disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eye disease is the subject, drug or therapy used for treatment is the predicate, and prednisone is the object constitutes an accurate semantic relation.

14634it [49:37,  5.17it/s]

true
Determine whether the semantic relation where arthritis is the subject, drug or therapy used for treatment is the predicate, and meclofenamic acid is the object constitutes an accurate semantic relation.

14635it [49:38,  5.06it/s]

true
Determine whether the semantic relation where meclofenamic acid is the subject, medical condition treated is the predicate, and arthritis is the object constitutes an accurate semantic relation.

14637it [49:38,  5.05it/s]

true
Determine whether the semantic relation where monosaccharide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vestibulocochlear nerve disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14639it [49:38,  5.20it/s]

true
Determine whether the semantic relation where benzophenone is the subject, subclass of is the predicate, and polycyclic compound is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where major depressive disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

14641it [49:39,  5.28it/s]

true
Determine whether the semantic relation where cocaine is the subject, significant drug interaction is the predicate, and domperidone is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where domperidone is the subject, significant drug interaction is the predicate, and cocaine is the object constitutes an accurate semantic relation.

14643it [49:39,  5.21it/s]

false
Determine whether the semantic relation where rectocele is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where immunology is the subject, is the study of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

14645it [49:39,  5.21it/s]

false
Determine whether the semantic relation where Pyrus is the subject, source of energy is the predicate, and carbohydrate is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where immune disorder is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

14647it [49:40,  5.24it/s]

false
Determine whether the semantic relation where Wernicke encephalopathy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lymphedema is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

14649it [49:40,  5.02it/s]

true
Determine whether the semantic relation where fluphenazine is the subject, subject has role is the predicate, and alpha blocker is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where G protein subunit alpha i2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14651it [49:41,  4.98it/s]

true
Determine whether the semantic relation where anxiety is the subject, drug or therapy used for treatment is the predicate, and bupropion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and acetazolamide is the object constitutes an accurate semantic relation.

14653it [49:41,  4.97it/s]

true
Determine whether the semantic relation where bupropion is the subject, medical condition treated is the predicate, and anxiety is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where ubiquitin C is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14655it [49:41,  4.98it/s]

true
Determine whether the semantic relation where Armenia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peripheral artery disease is the subject, risk factor is the predicate, and arterial hypertension is the object constitutes an accurate semantic relation.

14657it [49:42,  5.22it/s]

false
Determine whether the semantic relation where ocular motility disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where refugee is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

14659it [49:42,  5.25it/s]

false
Determine whether the semantic relation where L-tyrosine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tobacco industry is the subject, instance of is the predicate, and agriculture is the object constitutes an accurate semantic relation.

14661it [49:43,  5.19it/s]

false
Determine whether the semantic relation where dermatitis is the subject, drug or therapy used for treatment is the predicate, and doxycycline is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where doxycycline is the subject, medical condition treated is the predicate, and dermatitis is the object constitutes an accurate semantic relation.

14663it [49:43,  5.16it/s]

true
Determine whether the semantic relation where teenager is the subject, instance of is the predicate, and population group is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ribosomal RNA is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14664it [49:43,  5.25it/s]

false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Silybum marianum is the object constitutes an accurate semantic relation.

14666it [49:44,  5.14it/s]

true
Determine whether the semantic relation where Armenia is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Armenia is the object constitutes an accurate semantic relation.

14668it [49:44,  5.15it/s]

true
Determine whether the semantic relation where Greece is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Greece is the object constitutes an accurate semantic relation.

14670it [49:44,  5.20it/s]

true
Determine whether the semantic relation where injury is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and microtubule organizing center is the object constitutes an accurate semantic relation.

14671it [49:45,  5.22it/s]

false
Determine whether the semantic relation where hepatitis C is the subject, symptoms and signs is the predicate, and ascites is the object constitutes an accurate semantic relation.

14673it [49:45,  5.26it/s]

true
Determine whether the semantic relation where methanol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlormerodrin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14674it [49:45,  5.19it/s]

true
Determine whether the semantic relation where Platelet derived growth factor subunit B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14675it [49:45,  4.81it/s]

true
Determine whether the semantic relation where psychophysiology is the subject, subclass of is the predicate, and psychology is the object constitutes an accurate semantic relation.

14676it [49:46,  4.85it/s]

true
Determine whether the semantic relation where psychophysiology is the subject, subclass of is the predicate, and psychology is the object constitutes an accurate semantic relation.

14678it [49:46,  4.88it/s]

true
Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, cell component is the predicate, and nuclear envelope is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where protein-losing enteropathy is the subject, subclass of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

14680it [49:46,  5.07it/s]

false
Determine whether the semantic relation where neuropsychiatric systemic lupus erythematosus is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thiourea is the subject, has use is the predicate, and indicators and reagents is the object constitutes an accurate semantic relation.

14682it [49:47,  5.05it/s]

true
Determine whether the semantic relation where histone deacetylase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Melkersson-Rosenthal syndrome is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

14683it [49:47,  5.08it/s]

false
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

14685it [49:47,  5.16it/s]

true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where extrinsic allergic alveolitis is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

14686it [49:48,  5.17it/s]

true
Determine whether the semantic relation where insulin resistance is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

14688it [49:48,  5.02it/s]

true
Determine whether the semantic relation where formaldehyde is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin D is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

14689it [49:48,  5.07it/s]

false
Determine whether the semantic relation where Gulf War syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14691it [49:49,  4.98it/s]

true
Determine whether the semantic relation where delta thalassemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

14692it [49:49,  5.13it/s]

Determine whether the semantic relation where androstenol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thrombotic thrombocytopenic purpura is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

14694it [49:49,  5.04it/s]

true
Determine whether the semantic relation where canthaxanthin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where right ventricular hypertrophy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14695it [49:49,  5.02it/s]

false
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14697it [49:50,  5.13it/s]

true
Determine whether the semantic relation where Micronesia is the subject, has part(s) is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

14699it [49:50,  5.15it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bupropion is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

14701it [49:51,  5.08it/s]

true
Determine whether the semantic relation where monosaccharide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CAMP responsive element modulator is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14703it [49:51,  5.24it/s]

false
Determine whether the semantic relation where acute generalized exanthematous pustulosis is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acarbose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

14705it [49:51,  5.03it/s]

false
Determine whether the semantic relation where rutin is the subject, found in taxon is the predicate, and Beta vulgaris is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coronary artery disease is the subject, drug or therapy used for treatment is the predicate, and dextrothyroxine is the object constitutes an accurate semantic relation.

14707it [49:52,  4.67it/s]

false
Determine whether the semantic relation where sialadenitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dextrothyroxine is the subject, medical condition treated is the predicate, and coronary artery disease is the object constitutes an accurate semantic relation.

14708it [49:52,  4.77it/s]

false
Determine whether the semantic relation where diabetic cardiomyopathy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14709it [49:52,  4.70it/s]

true
Determine whether the semantic relation where benzoic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14710it [49:52,  4.68it/s]

true
Determine whether the semantic relation where activated leukocyte cell adhesion molecule is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

14712it [49:53,  4.69it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

14714it [49:53,  5.02it/s]

true
Determine whether the semantic relation where D-penicillamine is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where benzopyrene is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

14715it [49:53,  5.14it/s]

false
Determine whether the semantic relation where dopamine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14716it [49:54,  5.07it/s]

true
Determine whether the semantic relation where striated muscle tissue is the subject, opposite of is the predicate, and smooth muscle tissue is the object constitutes an accurate semantic relation.

14718it [49:54,  5.10it/s]

true
Determine whether the semantic relation where kidney disease is the subject, health specialty is the predicate, and urology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 2C is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14719it [49:54,  5.10it/s]

true
Determine whether the semantic relation where car is the subject, source of energy is the predicate, and solar energy is the object constitutes an accurate semantic relation.

14721it [49:55,  5.23it/s]

maybe
Determine whether the semantic relation where guaiacol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where allergic conjunctivitis is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

14723it [49:55,  5.05it/s]

true
Determine whether the semantic relation where ribonuclease A family member 3 is the subject, biological process is the predicate, and innate immune response is the object constitutes an accurate semantic relation.
false

14724it [49:55,  5.14it/s]

Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebral hemorrhage is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14726it [49:56,  5.09it/s]

true
Determine whether the semantic relation where sulfacetamide is the subject, medical condition treated is the predicate, and ear disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ear disease is the subject, drug or therapy used for treatment is the predicate, and sulfacetamide is the object constitutes an accurate semantic relation.

14728it [49:56,  5.11it/s]

true
Determine whether the semantic relation where choroideremia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true

14729it [49:56,  5.19it/s]

Determine whether the semantic relation where Hereditary CNS demyelinating disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cycloheximide is the subject, found in taxon is the predicate, and Streptomyces is the object constitutes an accurate semantic relation.

14730it [49:56,  5.23it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

14732it [49:57,  5.21it/s]

true
Determine whether the semantic relation where schizotypal personality disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where immunology is the subject, subclass of is the predicate, and biology is the object constitutes an accurate semantic relation.

14734it [49:57,  5.16it/s]

true
Determine whether the semantic relation where S-adenosyl-L-homocysteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

14736it [49:58,  5.16it/s]

true
Determine whether the semantic relation where elastin is the subject, biological process is the predicate, and cell population proliferation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where inflammation is the subject, drug or therapy used for treatment is the predicate, and fluorometholone is the object constitutes an accurate semantic relation.

14738it [49:58,  4.92it/s]

true
Determine whether the semantic relation where human digestive system is the subject, location is the predicate, and abdomen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rubella is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

14740it [49:58,  5.02it/s]

true
Determine whether the semantic relation where fluorometholone is the subject, medical condition treated is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Crimean-Congo hemorrhagic fever is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.

14742it [49:59,  5.14it/s]

true
Determine whether the semantic relation where United Kingdom is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.

14743it [49:59,  5.26it/s]

true
Determine whether the semantic relation where hyperinsulinism is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

14745it [49:59,  5.19it/s]

true
Determine whether the semantic relation where experimental autoimmune neuritis is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where desipramine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

14747it [50:00,  5.27it/s]

true
Determine whether the semantic relation where haloperidol is the subject, significant drug interaction is the predicate, and quinidine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where quinidine is the subject, significant drug interaction is the predicate, and haloperidol is the object constitutes an accurate semantic relation.

14749it [50:00,  5.17it/s]

true
Determine whether the semantic relation where Potassium voltage-gated channel subfamily Q member 1 is the subject, cell component is the predicate, and endosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where guaiacol is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14751it [50:01,  5.11it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Medicago sativa is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Melan-A is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

14752it [50:01,  5.15it/s]

false
Determine whether the semantic relation where interleukin 27 is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

14753it [50:01,  5.00it/s]

false
Determine whether the semantic relation where Seoul is the subject, twinned administrative body is the predicate, and New York City is the object constitutes an accurate semantic relation.

14755it [50:01,  5.05it/s]

true
Determine whether the semantic relation where New York City is the subject, twinned administrative body is the predicate, and Seoul is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

14756it [50:02,  5.06it/s]

true
Determine whether the semantic relation where methotrexate is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.

14757it [50:02,  5.00it/s]

false
Determine whether the semantic relation where alveolar macrophage is the subject, subclass of is the predicate, and histiocyte is the object constitutes an accurate semantic relation.

14759it [50:02,  5.03it/s]

true
Determine whether the semantic relation where FA complementation group L is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

14760it [50:02,  4.84it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Colombia is the object constitutes an accurate semantic relation.

14762it [50:03,  4.82it/s]

false
Determine whether the semantic relation where (S)-(−)-timolol is the subject, different from is the predicate, and thymol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S-adenosylmethionine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

14763it [50:03,  4.98it/s]

false
Determine whether the semantic relation where Kaposi's sarcoma is the subject, subclass of is the predicate, and connective tissue neoplasm is the object constitutes an accurate semantic relation.

14764it [50:03,  4.94it/s]

false
Determine whether the semantic relation where Prostaglandin E receptor 3 is the subject, biological process is the predicate, and cell death is the object constitutes an accurate semantic relation.

14766it [50:04,  4.93it/s]

false
Determine whether the semantic relation where pleurisy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where endocrine gland is the subject, opposite of is the predicate, and exocrine gland is the object constitutes an accurate semantic relation.

14768it [50:04,  5.10it/s]

false
Determine whether the semantic relation where (E)-chlorogenic acid is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cholecystokinin is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

14770it [50:04,  5.25it/s]

false
Determine whether the semantic relation where leptospirosis is the subject, possible treatment is the predicate, and antibiotic is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where folic acid is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

14772it [50:05,  5.35it/s]

false
Determine whether the semantic relation where DL-proline is the subject, found in taxon is the predicate, and Streptomyces griseus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where DNA damage inducible transcript 3 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

14774it [50:05,  5.34it/s]

false
Determine whether the semantic relation where D-(-)-mannitol is the subject, found in taxon is the predicate, and Aspergillus niger is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where exocrine gland is the subject, opposite of is the predicate, and endocrine gland is the object constitutes an accurate semantic relation.

14776it [50:05,  5.27it/s]

true
Determine whether the semantic relation where scrub typhus is the subject, symptoms and signs is the predicate, and cough is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cysticercosis is the subject, subclass of is the predicate, and muscular disease is the object constitutes an accurate semantic relation.

14778it [50:06,  5.19it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

14780it [50:06,  5.12it/s]

false
Determine whether the semantic relation where Dubin-Johnson syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where school is the subject, intended public is the predicate, and child is the object constitutes an accurate semantic relation.

14782it [50:07,  5.10it/s]

true
Determine whether the semantic relation where C-C motif chemokine ligand 4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where methotrexate is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

14784it [50:07,  5.17it/s]

true
Determine whether the semantic relation where Nobel Prize is the subject, country is the predicate, and Norway is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where metformin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

14785it [50:07,  5.24it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Chile is the object constitutes an accurate semantic relation.

14786it [50:07,  5.10it/s]

false
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.

14787it [50:08,  4.90it/s]

true
Determine whether the semantic relation where Saint Kitts and Nevis is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

14788it [50:08,  4.67it/s]

true
Determine whether the semantic relation where anthrax is the subject, symptoms and signs is the predicate, and lymphadenitis is the object constitutes an accurate semantic relation.

14790it [50:08,  4.88it/s]

true
Determine whether the semantic relation where North America is the subject, country is the predicate, and Saint Kitts and Nevis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BRCA2 DNA repair associated is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14791it [50:08,  5.08it/s]

false
Determine whether the semantic relation where exostosis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

14792it [50:09,  4.89it/s]

false
Determine whether the semantic relation where attention deficit hyperactivity disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.
true

14793it [50:09,  4.91it/s]

Determine whether the semantic relation where attention deficit hyperactivity disorder is the subject, studied by is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

14795it [50:09,  4.91it/s]

true
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and Israel is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hepatitis is the subject, has cause is the predicate, and alcoholism is the object constitutes an accurate semantic relation.

14797it [50:10,  4.76it/s]

true
Determine whether the semantic relation where polysaccharide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Israel is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

14799it [50:10,  5.11it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypergammaglobulinemia is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

14800it [50:10,  4.96it/s]

true
Determine whether the semantic relation where Cathepsin G is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14802it [50:11,  4.59it/s]

true
Determine whether the semantic relation where gallstone disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gallstone disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14803it [50:11,  4.59it/s]

true
Determine whether the semantic relation where infant nutrition disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14805it [50:11,  4.66it/s]

true
Determine whether the semantic relation where oligospermia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Notch receptor 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14806it [50:12,  4.69it/s]

true
Determine whether the semantic relation where Azerbaijan is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14807it [50:12,  4.30it/s]

true
Determine whether the semantic relation where public housing is the subject, country is the predicate, and New Zealand is the object constitutes an accurate semantic relation.

14808it [50:12,  4.34it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and spindle is the object constitutes an accurate semantic relation.

14810it [50:13,  4.47it/s]

false
Determine whether the semantic relation where smoke is the subject, facet of is the predicate, and breathing is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carcinoma is the subject, drug or therapy used for treatment is the predicate, and sirolimus is the object constitutes an accurate semantic relation.

14811it [50:13,  3.83it/s]

false
Determine whether the semantic relation where ventricular septal defect is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14813it [50:13,  4.35it/s]

true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.

14815it [50:14,  4.81it/s]

true
Determine whether the semantic relation where asthma is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ephrin B1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14816it [50:14,  4.94it/s]

false
Determine whether the semantic relation where Q5272105 is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

14818it [50:14,  4.83it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adrenomedullin is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14820it [50:15,  4.80it/s]

true
Determine whether the semantic relation where salpingitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where protein is the subject, subclass of is the predicate, and biopolymer is the object constitutes an accurate semantic relation.

14822it [50:15,  5.06it/s]

true
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where osteopetrosis is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

14824it [50:16,  5.24it/s]

true
Determine whether the semantic relation where craniosynostosis is the subject, subclass of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurofibromatosis type I is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14826it [50:16,  5.22it/s]

true
Determine whether the semantic relation where neurofibromatosis type I is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

14828it [50:16,  5.37it/s]

true
Determine whether the semantic relation where enteritis is the subject, subclass of is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chlorquinaldol is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

14829it [50:16,  5.40it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14830it [50:17,  5.20it/s]

true
Determine whether the semantic relation where salicylic acid is the subject, found in taxon is the predicate, and Pseudomonas aeruginosa is the object constitutes an accurate semantic relation.

14831it [50:17,  5.12it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Kuwait is the object constitutes an accurate semantic relation.

14832it [50:17,  5.04it/s]

true
Determine whether the semantic relation where Kuwait is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

14834it [50:17,  4.96it/s]

true
Determine whether the semantic relation where benzo[a]pyrene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where synaptosome associated protein 25 is the subject, cell component is the predicate, and cytoskeleton is the object constitutes an accurate semantic relation.

14836it [50:18,  5.19it/s]

false
Determine whether the semantic relation where Cathepsin C is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where interferon regulatory factor 9 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

14837it [50:18,  5.16it/s]

true
Determine whether the semantic relation where L-arginine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

14839it [50:18,  4.95it/s]

true
Determine whether the semantic relation where Nicaragua is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.

14840it [50:19,  4.96it/s]

true
Determine whether the semantic relation where eukaryotic translation initiation factor 2B complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

14841it [50:19,  4.80it/s]

false
Determine whether the semantic relation where Dystrophin is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14843it [50:19,  5.02it/s]

false
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Rac family small GTPase 1 is the subject, biological process is the predicate, and bone resorption is the object constitutes an accurate semantic relation.

14845it [50:20,  5.19it/s]

false
Determine whether the semantic relation where protein kinase cGMP-dependent 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase kinase 5 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14847it [50:20,  5.14it/s]

true
Determine whether the semantic relation where Angelman syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitamin D deficiency is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

14849it [50:20,  5.27it/s]

true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Carthamus tinctorius is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.

14851it [50:21,  5.24it/s]

true
Determine whether the semantic relation where Cyclin D2 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where promazine is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.

14853it [50:21,  5.35it/s]

false
Determine whether the semantic relation where Secretory leukocyte peptidase inhibitor is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where thyroid-stimulating hormone is the subject, subclass of is the predicate, and glycoprotein is the object constitutes an accurate semantic relation.

14854it [50:21,  4.93it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Brazil is the object constitutes an accurate semantic relation.

14855it [50:22,  4.85it/s]

false
Determine whether the semantic relation where dermoid cyst is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14856it [50:22,  4.73it/s]

true
Determine whether the semantic relation where Brazil is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

14858it [50:22,  4.89it/s]

true
Determine whether the semantic relation where concussion is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oncogenic retroviridae proteins is the subject, subclass of is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

14860it [50:23,  4.79it/s]

false
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Artemisia is the object constitutes an accurate semantic relation.

14861it [50:23,  4.69it/s]

false
Determine whether the semantic relation where ergot alkaloids is the subject, subject has role is the predicate, and mycotoxins is the object constitutes an accurate semantic relation.

14862it [50:23,  4.61it/s]

true
Determine whether the semantic relation where polymyositis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

14864it [50:24,  4.90it/s]

true
Determine whether the semantic relation where magnesium sulfate is the subject, has part(s) is the predicate, and sulfur is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where spinocerebellar ataxia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14866it [50:24,  4.88it/s]

true
Determine whether the semantic relation where cisapride is the subject, significant drug interaction is the predicate, and azithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where azithromycin is the subject, significant drug interaction is the predicate, and cisapride is the object constitutes an accurate semantic relation.

14867it [50:24,  5.04it/s]

true
Determine whether the semantic relation where integrin alphaVbeta3 [plasma membrane] is the subject, instance of is the predicate, and protein complex is the object constitutes an accurate semantic relation.

14869it [50:25,  4.98it/s]

true
Determine whether the semantic relation where Serpin family A member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ascending cholangitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14871it [50:25,  5.15it/s]

true
Determine whether the semantic relation where toll like receptor 4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where herpes zoster is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14873it [50:25,  5.27it/s]

true
Determine whether the semantic relation where amnesia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Netherlands is the subject, diplomatic relation is the predicate, and Albania is the object constitutes an accurate semantic relation.

14874it [50:25,  5.30it/s]

true
Determine whether the semantic relation where programmed cell death 1 is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

14876it [50:26,  5.12it/s]

false
Determine whether the semantic relation where paroxetine is the subject, medical condition treated is the predicate, and eating disorder is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eating disorder is the subject, drug or therapy used for treatment is the predicate, and paroxetine is the object constitutes an accurate semantic relation.

14878it [50:26,  5.16it/s]

true
Determine whether the semantic relation where parakeratosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Albania is the subject, diplomatic relation is the predicate, and Netherlands is the object constitutes an accurate semantic relation.

14880it [50:27,  5.24it/s]

true
Determine whether the semantic relation where domperidone is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and domperidone is the object constitutes an accurate semantic relation.

14882it [50:27,  5.24it/s]

true
Determine whether the semantic relation where body fluid is the subject, subclass of is the predicate, and secretion or excretion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trichinosis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

14884it [50:27,  5.38it/s]

true
Determine whether the semantic relation where Aconitase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where actinomycosis is the subject, subclass of is the predicate, and respiratory disease is the object constitutes an accurate semantic relation.

14886it [50:28,  5.25it/s]

false
Determine whether the semantic relation where California encephalitis is the subject, anatomical location is the predicate, and meninges is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Chile is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14887it [50:28,  5.29it/s]

true
Determine whether the semantic relation where clinical psychological interview is the subject, subclass of is the predicate, and interview is the object constitutes an accurate semantic relation.

14888it [50:28,  4.92it/s]

true
Determine whether the semantic relation where paresis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14889it [50:28,  4.57it/s]

false
Determine whether the semantic relation where Lennox-Gastaut sindrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14891it [50:29,  4.56it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, shares border with is the predicate, and Iran is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Iran is the object constitutes an accurate semantic relation.

14892it [50:29,  4.77it/s]

true
Determine whether the semantic relation where Iran is the subject, shares border with is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

14894it [50:30,  4.43it/s]

true
Determine whether the semantic relation where Iran is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ainhum is the subject, subclass of is the predicate, and connective tissue disease is the object constitutes an accurate semantic relation.

14895it [50:30,  4.74it/s]

true
Determine whether the semantic relation where open-angle glaucoma is the subject, drug or therapy used for treatment is the predicate, and phenylephrine is the object constitutes an accurate semantic relation.

14896it [50:30,  4.76it/s]

false
Determine whether the semantic relation where phenylephrine is the subject, medical condition treated is the predicate, and open-angle glaucoma is the object constitutes an accurate semantic relation.

14897it [50:30,  4.79it/s]

false
Determine whether the semantic relation where coronary artery disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

14899it [50:31,  4.82it/s]

false
Determine whether the semantic relation where major histocompatibility complex, class I, C is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true

14900it [50:31,  4.94it/s]

Determine whether the semantic relation where enzyme is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where crystallin alpha B is the subject, biological process is the predicate, and muscle contraction is the object constitutes an accurate semantic relation.

14902it [50:31,  5.01it/s]

false
Determine whether the semantic relation where infectious bone disease is the subject, drug or therapy used for treatment is the predicate, and Cefotetan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hungary is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

14904it [50:32,  5.02it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Hungary is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neuroscience is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.

14906it [50:32,  5.14it/s]

true
Determine whether the semantic relation where botulism is the subject, drug or therapy used for treatment is the predicate, and clindamycin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cefotetan is the subject, medical condition treated is the predicate, and infectious bone disease is the object constitutes an accurate semantic relation.

14907it [50:32,  5.16it/s]

true
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.

14909it [50:33,  4.95it/s]

true
Determine whether the semantic relation where Natriuretic peptide A is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where etomidate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

14910it [50:33,  5.02it/s]

true
Determine whether the semantic relation where disease outbreak is the subject, subclass of is the predicate, and medicine is the object constitutes an accurate semantic relation.

14912it [50:33,  4.96it/s]

false
Determine whether the semantic relation where S100 calcium binding protein B is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Protein-L-isoaspartate (D-aspartate) O-methyltransferase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14914it [50:34,  5.02it/s]

true
Determine whether the semantic relation where British Virgin Islands is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Killer cell lectin like receptor C2 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

14916it [50:34,  5.11it/s]

false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phlebitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.

14918it [50:34,  5.15it/s]

true
Determine whether the semantic relation where fibroblast growth factor receptor 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where thrombophilia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14920it [50:35,  5.17it/s]

true
Determine whether the semantic relation where Endothelin 3 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false

14921it [50:35,  5.27it/s]

Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Laos is the object constitutes an accurate semantic relation.

14923it [50:35,  5.21it/s]

true
Determine whether the semantic relation where triacetin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where RAB5A, member RAS oncogene family is the subject, cell component is the predicate, and axon terminus is the object constitutes an accurate semantic relation.

14924it [50:35,  5.34it/s]

false
Determine whether the semantic relation where pseudolymphoma is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14926it [50:36,  5.20it/s]

true
Determine whether the semantic relation where Laos is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pim-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14928it [50:36,  5.23it/s]

true
Determine whether the semantic relation where hexose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cytochrome P450 family 11 subfamily A member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14930it [50:37,  5.28it/s]

false
Determine whether the semantic relation where foetal-maternal haemorrhage is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where carbofuran is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

14931it [50:37,  5.23it/s]

false
Determine whether the semantic relation where Notch receptor 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

14932it [50:37,  5.12it/s]

true
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Germany is the object constitutes an accurate semantic relation.

14933it [50:37,  4.77it/s]

false
Determine whether the semantic relation where Lysyl oxidase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14934it [50:37,  4.76it/s]

true
Determine whether the semantic relation where chronic diarrhea of infancy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14935it [50:38,  4.73it/s]

true
Determine whether the semantic relation where medical student is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

14937it [50:38,  4.74it/s]

false
Determine whether the semantic relation where rickets is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where HEK293 is the subject, research intervention is the predicate, and Q4859345 is the object constitutes an accurate semantic relation.

14938it [50:38,  4.95it/s]

false
Determine whether the semantic relation where New South Wales is the subject, located in or next to body of water is the predicate, and Pacific Ocean is the object constitutes an accurate semantic relation.

14939it [50:39,  4.88it/s]

true
Determine whether the semantic relation where ZFP36 ring finger protein is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

14940it [50:39,  4.89it/s]

true
Determine whether the semantic relation where erythromelalgia is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

14941it [50:39,  4.85it/s]

true
Determine whether the semantic relation where folliculitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

14943it [50:39,  4.93it/s]

true
Determine whether the semantic relation where folliculitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 11a is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

14945it [50:40,  5.11it/s]

true
Determine whether the semantic relation where neurotic disorder is the subject, drug or therapy used for treatment is the predicate, and desipramine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovenia is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14946it [50:40,  4.43it/s]

true
Determine whether the semantic relation where guanine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

14948it [50:40,  4.76it/s]

true
Determine whether the semantic relation where proton is the subject, interaction is the predicate, and gravity is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where desipramine is the subject, medical condition treated is the predicate, and neurotic disorder is the object constitutes an accurate semantic relation.

14949it [50:41,  4.81it/s]

true
Determine whether the semantic relation where SMAD family member 4 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

14951it [50:41,  4.86it/s]

false
Determine whether the semantic relation where blogging is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where brain ischemia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

14953it [50:41,  5.01it/s]

true
Determine whether the semantic relation where Sodium voltage-gated channel beta subunit 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Singapore is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

14955it [50:42,  4.95it/s]

true
Determine whether the semantic relation where The Bahamas is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mining is the subject, subclass of is the predicate, and engineering is the object constitutes an accurate semantic relation.

14957it [50:42,  5.27it/s]

true
Determine whether the semantic relation where plague is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Protein tyrosine phosphatase non-receptor type 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

14958it [50:42,  5.13it/s]

true
Determine whether the semantic relation where Southeast Asia is the subject, country is the predicate, and Australia is the object constitutes an accurate semantic relation.

14959it [50:43,  4.01it/s]

false
Determine whether the semantic relation where North America is the subject, country is the predicate, and The Bahamas is the object constitutes an accurate semantic relation.

14961it [50:43,  4.31it/s]

false
Determine whether the semantic relation where putrescine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where toxoplasmosis is the subject, symptoms and signs is the predicate, and splenomegaly is the object constitutes an accurate semantic relation.

14963it [50:44,  4.78it/s]

true
Determine whether the semantic relation where fluconazole is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true

14964it [50:44,  4.96it/s]

Determine whether the semantic relation where Phosphofructokinase, platelet is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

14966it [50:44,  4.90it/s]

true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true

14967it [50:44,  4.95it/s]

Determine whether the semantic relation where Q180686 is the subject, country is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stable angina is the subject, risk factor is the predicate, and diabetes is the object constitutes an accurate semantic relation.

14969it [50:45,  5.12it/s]

false
Determine whether the semantic relation where carbon monoxide poisoning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and irritability is the object constitutes an accurate semantic relation.

14971it [50:45,  5.16it/s]

true
Determine whether the semantic relation where beriberi is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hydrops fetalis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.

14972it [50:45,  5.12it/s]

true
Determine whether the semantic relation where neutrophil elastase is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

14974it [50:46,  5.10it/s]

true
Determine whether the semantic relation where tinea is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eclampsia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14976it [50:46,  5.20it/s]

true
Determine whether the semantic relation where sex chromosome disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dissociative identity disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

14978it [50:46,  5.27it/s]

true
Determine whether the semantic relation where dissociative identity disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase kinase kinase 3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

14979it [50:47,  5.30it/s]

true
Determine whether the semantic relation where endemic typhus is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

14980it [50:47,  5.17it/s]

false
Determine whether the semantic relation where diphtheria is the subject, drug or therapy used for treatment is the predicate, and benzylpenicillin is the object constitutes an accurate semantic relation.

14982it [50:47,  5.02it/s]

false
Determine whether the semantic relation where benzylpenicillin is the subject, medical condition treated is the predicate, and diphtheria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ganglion cyst is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

14984it [50:48,  5.16it/s]

false
Determine whether the semantic relation where paraplegia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Riley-Day syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14985it [50:48,  4.92it/s]

true
Determine whether the semantic relation where Stigmatella aurantiaca is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.

14987it [50:48,  4.93it/s]

true
Determine whether the semantic relation where harm reduction is the subject, facet of is the predicate, and medical ethics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cavity of bony thorax is the subject, has part(s) is the predicate, and circulatory system is the object constitutes an accurate semantic relation.

14989it [50:49,  5.05it/s]

false
Determine whether the semantic relation where ribavirin is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where trisaccharide is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

14991it [50:49,  5.10it/s]

false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and stomatitis is the object constitutes an accurate semantic relation.
true

14992it [50:49,  5.08it/s]

Determine whether the semantic relation where paired box 2 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where heroin dependence is the subject, symptoms and signs is the predicate, and depression is the object constitutes an accurate semantic relation.

14994it [50:50,  4.94it/s]

true
Determine whether the semantic relation where sickness behavior is the subject, part of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urea is the subject, found in taxon is the predicate, and Broad Bean is the object constitutes an accurate semantic relation.

14996it [50:50,  5.04it/s]

false
Determine whether the semantic relation where fungal eye infection is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lung abscess is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

14998it [50:50,  5.26it/s]

true
Determine whether the semantic relation where alpha 2-HS glycoprotein is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where L1210 is the subject, instance of is the predicate, and cancer cell line is the object constitutes an accurate semantic relation.

14999it [50:51,  5.27it/s]

true
Determine whether the semantic relation where Apolipoprotein A1 is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

15000it [50:51,  5.15it/s]

false
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and fibromyalgia is the object constitutes an accurate semantic relation.

15001it [50:51,  4.59it/s]

false
Determine whether the semantic relation where dicumarol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15003it [50:52,  4.82it/s]

true
Determine whether the semantic relation where Survival of motor neuron 2, centromeric is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peptide biosynthetic process is the subject, has part(s) is the predicate, and peptide is the object constitutes an accurate semantic relation.

15005it [50:52,  5.07it/s]

false
Determine whether the semantic relation where peptide is the subject, part of is the predicate, and peptide biosynthetic process is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where LDL receptor related protein 6 is the subject, cell component is the predicate, and synapse is the object constitutes an accurate semantic relation.

15006it [50:52,  5.14it/s]

false
Determine whether the semantic relation where Q19869268 is the subject, field of work is the predicate, and health care is the object constitutes an accurate semantic relation.

15008it [50:52,  5.12it/s]

true
Determine whether the semantic relation where phospholipase A2 group V is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where phospholipase A2 group V is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

15009it [50:53,  5.07it/s]

true
Determine whether the semantic relation where complement C3d receptor 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15010it [50:53,  4.87it/s]

true
Determine whether the semantic relation where Brazil is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

15011it [50:53,  4.73it/s]

true
Determine whether the semantic relation where medical illustration is the subject, field of work is the predicate, and medicine is the object constitutes an accurate semantic relation.

15012it [50:53,  4.75it/s]

true
Determine whether the semantic relation where creatine kinase, M-type is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15014it [50:54,  5.00it/s]

true
Determine whether the semantic relation where thymidine monophosphate is the subject, subclass of is the predicate, and anion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where body dysmorphic disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

15015it [50:54,  5.05it/s]

true
Determine whether the semantic relation where Sjogren-Larsson syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15017it [50:54,  5.02it/s]

true
Determine whether the semantic relation where vitronectin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tannin is the subject, has use is the predicate, and food coloring is the object constitutes an accurate semantic relation.

15018it [50:55,  5.17it/s]

true
Determine whether the semantic relation where D-methamphetamine is the subject, medical condition treated is the predicate, and attention deficit hyperactivity disorder is the object constitutes an accurate semantic relation.

15020it [50:55,  5.17it/s]

true
Determine whether the semantic relation where attention deficit hyperactivity disorder is the subject, drug or therapy used for treatment is the predicate, and D-methamphetamine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where weaning is the subject, subclass of is the predicate, and meal is the object constitutes an accurate semantic relation.

15022it [50:55,  5.25it/s]

false
Determine whether the semantic relation where nerve growth factor is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anaphylaxis is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

15024it [50:56,  5.29it/s]

false
Determine whether the semantic relation where sodium salicylate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Q13522706 is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15026it [50:56,  5.25it/s]

true
Determine whether the semantic relation where drug psychosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fms related receptor tyrosine kinase 4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15028it [50:56,  5.31it/s]

true
Determine whether the semantic relation where schizotypal personality disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where schizotypal personality disorder is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

15030it [50:57,  5.16it/s]

true
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and sotalol is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Morocco is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

15032it [50:57,  5.25it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Ireland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Morocco is the object constitutes an accurate semantic relation.

15033it [50:57,  5.00it/s]

true
Determine whether the semantic relation where yellow fever is the subject, subclass of is the predicate, and skin infection is the object constitutes an accurate semantic relation.

15035it [50:58,  4.97it/s]

false
Determine whether the semantic relation where sotalol is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ireland is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

15037it [50:58,  5.11it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

15039it [50:59,  5.18it/s]

false
Determine whether the semantic relation where Austria is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MCL1 apoptosis regulator, BCL2 family member is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

15040it [50:59,  5.10it/s]

false
Determine whether the semantic relation where Peru is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

15042it [50:59,  5.10it/s]

true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Peru is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ebstein anomaly is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15044it [51:00,  5.26it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Austria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

15046it [51:00,  5.27it/s]

false
Determine whether the semantic relation where thioredoxin reductase 2 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where speciation is the subject, has part(s) is the predicate, and mutation is the object constitutes an accurate semantic relation.

15047it [51:00,  5.30it/s]

false
Determine whether the semantic relation where cat-scratch disease is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

15049it [51:00,  5.22it/s]

true
Determine whether the semantic relation where intestinal parasite infection is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ephrin A1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

15051it [51:01,  5.25it/s]

false
Determine whether the semantic relation where psychotropic drug is the subject, has use is the predicate, and pharmacotherapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where myotonic dystrophy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15052it [51:01,  5.30it/s]

true
Determine whether the semantic relation where Bloom syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15053it [51:01,  5.17it/s]

true
Determine whether the semantic relation where intestinal atresia is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15054it [51:01,  5.06it/s]

false
Determine whether the semantic relation where amebiasis is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

15055it [51:02,  4.95it/s]

true
Determine whether the semantic relation where Nijmegen breakage syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

15057it [51:02,  4.99it/s]

true
Determine whether the semantic relation where Turkey is the subject, shares border with is the predicate, and European Union is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where European Union is the subject, shares border with is the predicate, and Turkey is the object constitutes an accurate semantic relation.

15058it [51:02,  5.10it/s]

false
Determine whether the semantic relation where dihydroergotamine is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

15060it [51:03,  4.88it/s]

true
Determine whether the semantic relation where tobramycin is the subject, found in taxon is the predicate, and Aspergillus fumigatus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where depression is the subject, drug or therapy used for treatment is the predicate, and lysergic acid diethylamide is the object constitutes an accurate semantic relation.

15062it [51:03,  5.04it/s]

false
Determine whether the semantic relation where TNT is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cbl proto-oncogene is the subject, cell component is the predicate, and cilium is the object constitutes an accurate semantic relation.

15064it [51:03,  5.09it/s]

false
Determine whether the semantic relation where drowning is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where quinic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15066it [51:04,  5.03it/s]

true
Determine whether the semantic relation where Thyroid stimulating hormone subunit beta is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peripheral neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15067it [51:04,  5.14it/s]

true
Determine whether the semantic relation where Protein C, inactivator of coagulation factors Va and VIIIa is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.

15069it [51:05,  4.93it/s]

false
Determine whether the semantic relation where Gamma-butyrobetaine hydroxylase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Dopamine receptor D3 is the subject, biological process is the predicate, and gastric emptying is the object constitutes an accurate semantic relation.

15071it [51:05,  5.08it/s]

false
Determine whether the semantic relation where ethanol is the subject, has part(s) of the class is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Ebola hemorrhagic fever is the subject, medical examination is the predicate, and ELISA is the object constitutes an accurate semantic relation.

15072it [51:05,  5.01it/s]

false
Determine whether the semantic relation where linoleic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

15073it [51:05,  4.87it/s]

false
Determine whether the semantic relation where Neurofibromin 1 is the subject, biological process is the predicate, and pigmentation is the object constitutes an accurate semantic relation.

15075it [51:06,  4.99it/s]

true
Determine whether the semantic relation where Philippines is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Philippines is the object constitutes an accurate semantic relation.

15076it [51:06,  5.17it/s]

true
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Afghanistan is the object constitutes an accurate semantic relation.

15078it [51:06,  5.13it/s]

true
Determine whether the semantic relation where beta-1,3-glucuronyltransferase 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.

15080it [51:07,  5.11it/s]

true
Determine whether the semantic relation where Bosnia and Herzegovina is the subject, located in or next to body of water is the predicate, and Mediterranean Sea is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Mediterranean Sea is the subject, country is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.

15082it [51:07,  5.05it/s]

false
Determine whether the semantic relation where Mediterranean Sea is the subject, basin country is the predicate, and Bosnia and Herzegovina is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where CD34 molecule is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15084it [51:07,  5.05it/s]

true
Determine whether the semantic relation where intracranial embolism and thrombosis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where polyyne is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15085it [51:08,  5.09it/s]

true
Determine whether the semantic relation where East Germany is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

15086it [51:08,  5.03it/s]

true
Determine whether the semantic relation where indomethacin is the subject, subclass of is the predicate, and indole alkaloid is the object constitutes an accurate semantic relation.
false

15087it [51:08,  5.01it/s]

Determine whether the semantic relation where humanities is the subject, is the study of is the predicate, and language is the object constitutes an accurate semantic relation.

15088it [51:08,  4.83it/s]

false
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 5 is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

15090it [51:09,  4.94it/s]

true
Determine whether the semantic relation where drug reaction with eosinophilia and systemic symptoms is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Wolbachia is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.

15091it [51:09,  5.00it/s]

false
Determine whether the semantic relation where grey wolf is the subject, taxon range is the predicate, and Greece is the object constitutes an accurate semantic relation.

15092it [51:09,  4.77it/s]

true
Determine whether the semantic relation where SMAD family member 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15094it [51:10,  4.97it/s]

true
Determine whether the semantic relation where Signal transducer and activator of transcription 4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chrysene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15096it [51:10,  5.14it/s]

true
Determine whether the semantic relation where bacterial infectious disease is the subject, drug or therapy used for treatment is the predicate, and demeclocycline is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where demeclocycline is the subject, medical condition treated is the predicate, and bacterial infectious disease is the object constitutes an accurate semantic relation.

15097it [51:10,  5.21it/s]

true
Determine whether the semantic relation where arthropathy is the subject, drug or therapy used for treatment is the predicate, and cloxacillin is the object constitutes an accurate semantic relation.

15099it [51:10,  5.12it/s]

false
Determine whether the semantic relation where peripheral vascular disease is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cloxacillin is the subject, medical condition treated is the predicate, and arthropathy is the object constitutes an accurate semantic relation.

15100it [51:11,  5.17it/s]

false
Determine whether the semantic relation where C-C motif chemokine ligand 2 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.

15102it [51:11,  5.07it/s]

true
Determine whether the semantic relation where Middle East is the subject, shares border with is the predicate, and Central Asia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where G protein subunit alpha i2 is the subject, biological process is the predicate, and protein folding is the object constitutes an accurate semantic relation.

15104it [51:11,  5.33it/s]

false
Determine whether the semantic relation where Prostaglandin-endoperoxide synthase 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where subvalvular aortic stenosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15106it [51:12,  5.05it/s]

true
Determine whether the semantic relation where peptidylprolyl isomerase A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hirschsprung's disease is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15108it [51:12,  5.14it/s]

true
Determine whether the semantic relation where selectin E is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Klinefelter's syndrome is the subject, symptoms and signs is the predicate, and muscle weakness is the object constitutes an accurate semantic relation.

15109it [51:12,  5.18it/s]

true
Determine whether the semantic relation where anxiety is the subject, symptoms and signs is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true

15111it [51:13,  5.20it/s]

Determine whether the semantic relation where legionnaires' disease is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neurotic disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15113it [51:13,  5.19it/s]

true
Determine whether the semantic relation where β-carotene is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Nitric oxide synthase 3 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15114it [51:13,  5.15it/s]

true
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and metronidazole is the object constitutes an accurate semantic relation.

15115it [51:14,  4.63it/s]

maybe
Determine whether the semantic relation where metronidazole is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.

15117it [51:14,  4.68it/s]

true
Determine whether the semantic relation where Twist family bHLH transcription factor 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lutein is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.

15119it [51:15,  4.79it/s]

false
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

15121it [51:15,  4.94it/s]

true
Determine whether the semantic relation where Carbonic anhydrase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Madagascar is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.

15122it [51:15,  4.93it/s]

false
Determine whether the semantic relation where SMAD family member 5 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15123it [51:15,  4.89it/s]

true
Determine whether the semantic relation where nitrazepam is the subject, subclass of is the predicate, and alkaloid is the object constitutes an accurate semantic relation.

15124it [51:16,  4.81it/s]

false
Determine whether the semantic relation where refractory anemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15126it [51:16,  4.87it/s]

true
Determine whether the semantic relation where magnesium oxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chorismic acid is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15128it [51:16,  5.18it/s]

false
Determine whether the semantic relation where Mozambique is the subject, diplomatic relation is the predicate, and Brazil is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where YY1 transcription factor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15130it [51:17,  5.22it/s]

true
Determine whether the semantic relation where Brazil is the subject, diplomatic relation is the predicate, and Mozambique is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tic disorder is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

15132it [51:17,  4.92it/s]

true
Determine whether the semantic relation where Janus kinase 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where osteomyelitis is the subject, health specialty is the predicate, and podiatry is the object constitutes an accurate semantic relation.

15133it [51:17,  4.95it/s]

maybe
Determine whether the semantic relation where neutrophil elastase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15134it [51:18,  4.80it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and Latvia is the object constitutes an accurate semantic relation.

15135it [51:18,  4.78it/s]

false
Determine whether the semantic relation where brain ischemia is the subject, drug or therapy used for treatment is the predicate, and etomidate is the object constitutes an accurate semantic relation.

15137it [51:18,  4.95it/s]

false
Determine whether the semantic relation where etomidate is the subject, medical condition treated is the predicate, and brain ischemia is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tuberous sclerosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15139it [51:19,  5.10it/s]

true
Determine whether the semantic relation where retrograde amnesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nialamide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15140it [51:19,  5.05it/s]

false
Determine whether the semantic relation where Puerto Rico is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

15141it [51:19,  5.00it/s]

true
Determine whether the semantic relation where autoimmune disease is the subject, afflicts is the predicate, and immune system is the object constitutes an accurate semantic relation.

15142it [51:19,  4.96it/s]

true
Determine whether the semantic relation where cadaverine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

15143it [51:19,  4.92it/s]

true
Determine whether the semantic relation where Dual specificity phosphatase 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15145it [51:20,  4.98it/s]

true
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Italy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Samoan Islands is the subject, country is the predicate, and United States is the object constitutes an accurate semantic relation.

15147it [51:20,  5.02it/s]

false
Determine whether the semantic relation where chilblains is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Italy is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

15148it [51:20,  5.16it/s]

true
Determine whether the semantic relation where complement C4A (Rodgers blood group) is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.

15149it [51:21,  4.77it/s]

false
Determine whether the semantic relation where public health nurse is the subject, instance of is the predicate, and occupation is the object constitutes an accurate semantic relation.

15151it [51:21,  4.85it/s]

true
Determine whether the semantic relation where diffuse myelinoclastic sclerosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true

15152it [51:21,  4.92it/s]

Determine whether the semantic relation where apigenin is the subject, found in taxon is the predicate, and cacao is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where β-alanine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

15154it [51:22,  5.01it/s]

false
Determine whether the semantic relation where pellagra is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

15156it [51:22,  5.10it/s]

false
Determine whether the semantic relation where nerve growth factor is the subject, cell component is the predicate, and cytoplasmic vesicle is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15158it [51:22,  5.24it/s]

false
Determine whether the semantic relation where apigenin is the subject, found in taxon is the predicate, and Spinacia oleracea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where skin epithelioid hemangioma is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

15159it [51:23,  5.27it/s]

true
Determine whether the semantic relation where Meniere's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15161it [51:23,  5.03it/s]

true
Determine whether the semantic relation where thanatology is the subject, subclass of is the predicate, and applied psychology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where farnesyl diphosphate synthase is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

15162it [51:23,  5.20it/s]

false
Determine whether the semantic relation where guanosine 5'-diphosphate (RRSR form) is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

15164it [51:24,  5.12it/s]

false
Determine whether the semantic relation where Castleman's disease is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase kinase 3 is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

15165it [51:24,  5.26it/s]

false
Determine whether the semantic relation where congenital hyperinsulinism is the subject, instance of is the predicate, and genetic disease is the object constitutes an accurate semantic relation.

15167it [51:24,  5.18it/s]

true
Determine whether the semantic relation where beta-glucan is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cathepsin A is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15168it [51:24,  5.04it/s]

true
Determine whether the semantic relation where atrioventricular septal defect is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15170it [51:25,  5.05it/s]

true
Determine whether the semantic relation where MAF bZIP transcription factor is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where viral interference is the subject, participant is the predicate, and cell is the object constitutes an accurate semantic relation.

15171it [51:25,  5.12it/s]

false
Determine whether the semantic relation where von Willebrand's disease is the subject, symptoms and signs is the predicate, and cerebral hemorrhage is the object constitutes an accurate semantic relation.

15173it [51:25,  5.15it/s]

true
Determine whether the semantic relation where medicine is the subject, different from is the predicate, and homeopathy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where eating is the subject, uses is the predicate, and human digestive system is the object constitutes an accurate semantic relation.

15174it [51:25,  5.22it/s]

false
Determine whether the semantic relation where prostaglandin reductase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15176it [51:26,  5.10it/s]

true
Determine whether the semantic relation where homeopathy is the subject, different from is the predicate, and medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Judaism is the subject, instance of is the predicate, and lifestyle is the object constitutes an accurate semantic relation.

15178it [51:26,  5.20it/s]

false
Determine whether the semantic relation where hypoalphalipoproteinemia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where complement C1s is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.

15180it [51:27,  5.25it/s]

false
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Musa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where acetic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

15182it [51:27,  5.37it/s]

false
Determine whether the semantic relation where Apolipoprotein B is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sirtuin 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15184it [51:27,  5.30it/s]

false
Determine whether the semantic relation where phlebotomus fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Complement C5 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15185it [51:28,  5.29it/s]

true
Determine whether the semantic relation where intussusception is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15187it [51:28,  5.20it/s]

true
Determine whether the semantic relation where Angola is the subject, diplomatic relation is the predicate, and Ukraine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Moldova is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.

15188it [51:28,  5.21it/s]

true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Moldova is the object constitutes an accurate semantic relation.

15190it [51:29,  5.08it/s]

true
Determine whether the semantic relation where Cogan syndrome is the subject, has effect is the predicate, and fatigue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Ukraine is the subject, diplomatic relation is the predicate, and Angola is the object constitutes an accurate semantic relation.

15192it [51:29,  5.14it/s]

true
Determine whether the semantic relation where chemotherapy-induced acral erythema is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where relapsing polychondritis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15194it [51:29,  5.15it/s]

true
Determine whether the semantic relation where cardiovascular disorder in pregnancy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diphtheria is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

15195it [51:30,  4.92it/s]

true
Determine whether the semantic relation where protein tyrosine kinase 2 beta is the subject, cell component is the predicate, and axon is the object constitutes an accurate semantic relation.

15197it [51:30,  4.82it/s]

false
Determine whether the semantic relation where eicosapentaenoic acid is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where blastomycosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15199it [51:30,  4.97it/s]

true
Determine whether the semantic relation where treatment outcome is the subject, facet of is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where polyester is the subject, subclass of is the predicate, and ester is the object constitutes an accurate semantic relation.

15200it [51:31,  5.00it/s]

true
Determine whether the semantic relation where CD7 molecule is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15201it [51:31,  4.67it/s]

true
Determine whether the semantic relation where sodium bicarbonate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15203it [51:31,  4.78it/s]

true
Determine whether the semantic relation where tumor protein p53 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malaria is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.

15205it [51:32,  5.05it/s]

true
Determine whether the semantic relation where cerebral palsy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetraplegia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15206it [51:32,  4.80it/s]

true
Determine whether the semantic relation where ankylosing spondylitis is the subject, drug or therapy used for treatment is the predicate, and ibuprofen is the object constitutes an accurate semantic relation.

15207it [51:32,  4.54it/s]

true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.

15208it [51:32,  4.63it/s]

true
Determine whether the semantic relation where Serpin family E member 2 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.

15209it [51:33,  4.68it/s]

false
Determine whether the semantic relation where ibuprofen is the subject, medical condition treated is the predicate, and ankylosing spondylitis is the object constitutes an accurate semantic relation.

15211it [51:33,  4.78it/s]

true
Determine whether the semantic relation where potassium acetate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Mexico is the object constitutes an accurate semantic relation.

15212it [51:33,  4.75it/s]

true
Determine whether the semantic relation where Mexico is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.

15214it [51:34,  4.92it/s]

true
Determine whether the semantic relation where maize is the subject, taxon range is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.

15215it [51:34,  5.04it/s]

true
Determine whether the semantic relation where myotonic dystrophy is the subject, subclass of is the predicate, and hypertrophic cardiomyopathy is the object constitutes an accurate semantic relation.

15216it [51:34,  4.83it/s]

false
Determine whether the semantic relation where immunoglobulin A deficiency is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

15217it [51:34,  4.62it/s]

true
Determine whether the semantic relation where Crohn's disease is the subject, drug or therapy used for treatment is the predicate, and 4-aminosalicylic acid is the object constitutes an accurate semantic relation.

15219it [51:35,  4.87it/s]

true
Determine whether the semantic relation where gout is the subject, symptoms and signs is the predicate, and erythema is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cerebrosides is the subject, subclass of is the predicate, and glycoside is the object constitutes an accurate semantic relation.

15221it [51:35,  5.03it/s]

true
Determine whether the semantic relation where Follicle stimulating hormone subunit beta is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TEK receptor tyrosine kinase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15222it [51:35,  4.78it/s]

true
Determine whether the semantic relation where thioredoxin reductase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15224it [51:36,  4.82it/s]

false
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and People's Republic of China is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cecal disease is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15226it [51:36,  5.15it/s]

true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where People's Republic of China is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

15228it [51:36,  5.13it/s]

true
Determine whether the semantic relation where Rickettsia conorii is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where 4-aminobenzoic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15229it [51:37,  5.03it/s]

true
Determine whether the semantic relation where alprenolol is the subject, subject has role is the predicate, and antihypertensive drug is the object constitutes an accurate semantic relation.

15231it [51:37,  4.91it/s]

true
Determine whether the semantic relation where L-xylulose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where citric acid is the subject, subclass of is the predicate, and fatty alcohol is the object constitutes an accurate semantic relation.

15233it [51:37,  5.11it/s]

false
Determine whether the semantic relation where Seychelles is the subject, shares border with is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlorhexidine is the subject, medical condition treated is the predicate, and skin infection is the object constitutes an accurate semantic relation.

15235it [51:38,  5.24it/s]

true
Determine whether the semantic relation where traumatic brain stem hemorrhage is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where distal muscular dystrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15236it [51:38,  5.29it/s]

true
Determine whether the semantic relation where pulmonary tuberculosis is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

15237it [51:38,  5.14it/s]

true
Determine whether the semantic relation where benzoic acid is the subject, found in taxon is the predicate, and Lactobacillus plantarum is the object constitutes an accurate semantic relation.

15239it [51:39,  5.08it/s]

false
Determine whether the semantic relation where plantar fasciitis is the subject, drug or therapy used for treatment is the predicate, and Diclofenac is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Diclofenac is the subject, medical condition treated is the predicate, and plantar fasciitis is the object constitutes an accurate semantic relation.

15240it [51:39,  5.14it/s]

true
Determine whether the semantic relation where skin infection is the subject, drug or therapy used for treatment is the predicate, and chlorhexidine is the object constitutes an accurate semantic relation.

15242it [51:39,  5.06it/s]

true
Determine whether the semantic relation where Cambodia is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Cambodia is the object constitutes an accurate semantic relation.

15243it [51:39,  4.99it/s]

true
Determine whether the semantic relation where anticholinergic toxidrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15244it [51:40,  4.89it/s]

true
Determine whether the semantic relation where Belize is the subject, continent is the predicate, and North America is the object constitutes an accurate semantic relation.

15245it [51:40,  4.74it/s]

true
Determine whether the semantic relation where cutaneous leishmaniasis is the subject, has natural reservoir is the predicate, and dog is the object constitutes an accurate semantic relation.

15247it [51:40,  4.77it/s]

false
Determine whether the semantic relation where parathyroid hormone 1 receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Afghanistan is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

15249it [51:41,  4.86it/s]

true
Determine whether the semantic relation where anti-obesity medication is the subject, subclass of is the predicate, and central nervous system agent is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Georgia is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

15251it [51:41,  5.18it/s]

true
Determine whether the semantic relation where Georgia is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cellulose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15253it [51:41,  5.24it/s]

false
Determine whether the semantic relation where magnesium hydroxide is the subject, medical condition treated is the predicate, and chronic renal insufficiency is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where chronic renal insufficiency is the subject, drug or therapy used for treatment is the predicate, and magnesium hydroxide is the object constitutes an accurate semantic relation.

15255it [51:42,  4.88it/s]

false
Determine whether the semantic relation where Sodium voltage-gated channel alpha subunit 5 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Potassium voltage-gated channel subfamily Q member 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15257it [51:42,  5.01it/s]

true
Determine whether the semantic relation where 46,XX disorders of sex development is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sucrose is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.

15259it [51:43,  4.94it/s]

false
Determine whether the semantic relation where benzoic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Zambia is the object constitutes an accurate semantic relation.

15261it [51:43,  5.13it/s]

true
Determine whether the semantic relation where orthopedic procedures is the subject, subclass of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15262it [51:43,  5.19it/s]

true
Determine whether the semantic relation where cystitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15263it [51:43,  5.04it/s]

true
Determine whether the semantic relation where prurigo is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15264it [51:44,  4.96it/s]

true
Determine whether the semantic relation where Cardiac Edema is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15266it [51:44,  5.02it/s]

true
Determine whether the semantic relation where Zambia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pharynx neoplasm is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

15268it [51:44,  4.92it/s]

true
Determine whether the semantic relation where L-arginine is the subject, found in taxon is the predicate, and Azotobacter vinelandii is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where integrin subunit beta 2 is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

15269it [51:45,  4.50it/s]

false
Determine whether the semantic relation where foreign body granuloma is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.

15271it [51:45,  4.80it/s]

false
Determine whether the semantic relation where CD33 molecule is the subject, biological process is the predicate, and cell adhesion is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where yohimbine is the subject, subject has role is the predicate, and urological agents is the object constitutes an accurate semantic relation.

15273it [51:46,  4.46it/s]

true
Determine whether the semantic relation where diabetic coma is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SMAD family member 4 is the subject, biological process is the predicate, and spermatogenesis is the object constitutes an accurate semantic relation.

15275it [51:46,  4.72it/s]

false
Determine whether the semantic relation where Ras homolog family member B is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where adenosine monophosphate is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15276it [51:46,  4.61it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Chile is the object constitutes an accurate semantic relation.

15278it [51:47,  4.60it/s]

false
Determine whether the semantic relation where dengue fever is the subject, symptoms and signs is the predicate, and arthralgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF superfamily member 10 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15280it [51:47,  4.89it/s]

true
Determine whether the semantic relation where Chile is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where patent ductus arteriosus is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15282it [51:47,  5.09it/s]

true
Determine whether the semantic relation where cystatin A is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where digestive system abnormality is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15284it [51:48,  5.26it/s]

true
Determine whether the semantic relation where interferon regulatory factor 9 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where MPTP is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15285it [51:48,  5.31it/s]

true
Determine whether the semantic relation where essential thrombocytosis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15287it [51:49,  4.56it/s]

true
Determine whether the semantic relation where stanozolol is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where malignant hypertension is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15289it [51:49,  4.70it/s]

true
Determine whether the semantic relation where dextroamphetamine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where overnutrition is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

15290it [51:49,  4.31it/s]

false
Determine whether the semantic relation where Histocompatibility 2, D region locus 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15292it [51:50,  4.28it/s]

true
Determine whether the semantic relation where uveitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where butan-1-ol is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15293it [51:50,  4.43it/s]

true
Determine whether the semantic relation where toxocariasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

15294it [51:50,  4.50it/s]

true
Determine whether the semantic relation where hydroxylapatite is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15296it [51:51,  4.74it/s]

true
Determine whether the semantic relation where suppurative uveitis is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibromyalgia is the subject, drug or therapy used for treatment is the predicate, and non-steroidal anti-inflammatory drug is the object constitutes an accurate semantic relation.

15297it [51:51,  4.80it/s]

true
Determine whether the semantic relation where CD79a molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15299it [51:51,  4.94it/s]

true
Determine whether the semantic relation where myogenic differentiation 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Daucus carota is the subject, invasive to is the predicate, and Alberta is the object constitutes an accurate semantic relation.

15301it [51:51,  5.18it/s]

false
Determine whether the semantic relation where KLRC4-KLRK1 readthrough is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where RRR-alpha-tocopherol is the subject, found in taxon is the predicate, and Chlorella vulgaris is the object constitutes an accurate semantic relation.

15303it [51:52,  5.27it/s]

false
Determine whether the semantic relation where achalasia is the subject, health specialty is the predicate, and thoracic surgery is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where sirtuin 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15305it [51:52,  5.27it/s]

false
Determine whether the semantic relation where bradycardia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Q14905298 is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

15307it [51:53,  5.35it/s]

true
Determine whether the semantic relation where overweight is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Melan-A is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15309it [51:53,  5.39it/s]

false
Determine whether the semantic relation where L-lysine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neuronal migration disorder is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15310it [51:53,  5.26it/s]

true
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and itch is the object constitutes an accurate semantic relation.

15311it [51:53,  5.10it/s]

true
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

15313it [51:54,  5.16it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where plasmid is the subject, subclass of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

15314it [51:54,  5.17it/s]

true
Determine whether the semantic relation where vitamin E is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15315it [51:54,  5.00it/s]

false
Determine whether the semantic relation where simvastatin is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

15317it [51:55,  4.99it/s]

true
Determine whether the semantic relation where lactose intolerance is the subject, has cause is the predicate, and eating is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and ondansetron is the object constitutes an accurate semantic relation.

15318it [51:55,  5.15it/s]

true
Determine whether the semantic relation where ondansetron is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.
true

15320it [51:55,  5.18it/s]

Determine whether the semantic relation where protein tyrosine phosphatase non-receptor type 6 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD14 molecule is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

15322it [51:56,  5.11it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Nigeria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (−)-nicotine is the subject, has use is the predicate, and insecticide is the object constitutes an accurate semantic relation.

15324it [51:56,  4.93it/s]

true
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Palau is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oral mucosa leukoplakia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15326it [51:56,  5.02it/s]

true
Determine whether the semantic relation where Nigeria is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Palau is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

15328it [51:57,  5.13it/s]

true
Determine whether the semantic relation where quercetin is the subject, found in taxon is the predicate, and Valeriana officinalis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where altitude sickness is the subject, health specialty is the predicate, and emergency medicine is the object constitutes an accurate semantic relation.

15329it [51:57,  5.06it/s]

false
Determine whether the semantic relation where North America is the subject, country is the predicate, and Belize is the object constitutes an accurate semantic relation.

15330it [51:57,  4.98it/s]

true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, biological process is the predicate, and sensory perception of pain is the object constitutes an accurate semantic relation.

15332it [51:58,  5.04it/s]

false
Determine whether the semantic relation where vaginitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mestranol is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.

15334it [51:58,  5.08it/s]

true
Determine whether the semantic relation where Spain is the subject, member of is the predicate, and Organization for Economic Cooperation and Development is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Yugoslavia is the subject, diplomatic relation is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

15335it [51:58,  5.07it/s]

true
Determine whether the semantic relation where Soviet Union is the subject, diplomatic relation is the predicate, and Yugoslavia is the object constitutes an accurate semantic relation.

15336it [51:58,  4.97it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15338it [51:59,  5.05it/s]

true
Determine whether the semantic relation where angiotensin I converting enzyme is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cowpox is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

15340it [51:59,  5.19it/s]

false
Determine whether the semantic relation where hypoxanthine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aggrecan is the subject, cell component is the predicate, and basement membrane is the object constitutes an accurate semantic relation.

15342it [52:00,  5.19it/s]

false
Determine whether the semantic relation where adenosine diphosphate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where FES proto-oncogene, tyrosine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15344it [52:00,  5.20it/s]

true
Determine whether the semantic relation where blood clotting test is the subject, subclass of is the predicate, and blood test is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oral medicine is the subject, part of is the predicate, and medicine is the object constitutes an accurate semantic relation.

15346it [52:00,  5.27it/s]

true
Determine whether the semantic relation where Joint Commission is the subject, industry is the predicate, and health care is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 1 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15348it [52:01,  5.41it/s]

true
Determine whether the semantic relation where rhizosphere is the subject, studied by is the predicate, and botany is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where arsenic poisoning is the subject, symptoms and signs is the predicate, and erythema is the object constitutes an accurate semantic relation.

15350it [52:01,  5.25it/s]

true
Determine whether the semantic relation where thrombosis is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where safety is the subject, opposite of is the predicate, and risk is the object constitutes an accurate semantic relation.

15352it [52:02,  4.60it/s]

true
Determine whether the semantic relation where floxuridine is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where examination table is the subject, has use is the predicate, and physical examination is the object constitutes an accurate semantic relation.

15354it [52:02,  4.96it/s]

true
Determine whether the semantic relation where cytarabine is the subject, subject has role is the predicate, and antiviral agent is the object constitutes an accurate semantic relation.
false

15355it [52:02,  5.08it/s]

Determine whether the semantic relation where coagulation factor V is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone morphogenetic protein 4 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15357it [52:02,  5.16it/s]

false
Determine whether the semantic relation where Libya is the subject, diplomatic relation is the predicate, and Switzerland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Switzerland is the subject, diplomatic relation is the predicate, and Libya is the object constitutes an accurate semantic relation.

15358it [52:03,  4.76it/s]

true
Determine whether the semantic relation where communication disorder is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15359it [52:03,  4.65it/s]

true
Determine whether the semantic relation where venous thromboembolism is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15360it [52:03,  4.37it/s]

false
Determine whether the semantic relation where respiratory failure is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
true

15361it [52:03,  4.53it/s]

Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and pharyngitis is the object constitutes an accurate semantic relation.

15363it [52:04,  4.64it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true

15364it [52:04,  4.77it/s]

Determine whether the semantic relation where Early growth response 1 is the subject, biological process is the predicate, and estrous cycle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coronary thrombosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15366it [52:04,  4.93it/s]

true
Determine whether the semantic relation where strongyloidiasis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where LDL receptor related protein associated protein 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15367it [52:05,  5.04it/s]

true
Determine whether the semantic relation where tuberculosis is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

15369it [52:05,  5.00it/s]

true
Determine whether the semantic relation where keratin 17 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

15370it [52:05,  4.97it/s]

true
Determine whether the semantic relation where Russia is the subject, designated as terrorist by is the predicate, and Slovakia is the object constitutes an accurate semantic relation.

15372it [52:06,  5.08it/s]

false
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where bone marrow is the subject, instance of is the predicate, and tissue is the object constitutes an accurate semantic relation.

15374it [52:06,  4.88it/s]

true
Determine whether the semantic relation where bone marrow is the subject, subclass of is the predicate, and tissue is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (+)-pseudoephedrine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

15376it [52:07,  4.32it/s]

true
Determine whether the semantic relation where Turkey is the subject, diplomatic relation is the predicate, and Croatia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mansonelliasis is the subject, subclass of is the predicate, and skin disease is the object constitutes an accurate semantic relation.

15377it [52:07,  4.62it/s]

false
Determine whether the semantic relation where Croatia is the subject, diplomatic relation is the predicate, and Turkey is the object constitutes an accurate semantic relation.

15378it [52:07,  4.51it/s]

true
Determine whether the semantic relation where thoracic diaphragm is the subject, muscle insertion is the predicate, and thoracic vertebra is the object constitutes an accurate semantic relation.

15380it [52:07,  4.70it/s]

false
Determine whether the semantic relation where keratin 10 is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where chlortetracycline is the subject, subject has role is the predicate, and antiprotozoal is the object constitutes an accurate semantic relation.

15382it [52:08,  4.93it/s]

false
Determine whether the semantic relation where skatol is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where S100 calcium binding protein A8 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15384it [52:08,  5.06it/s]

true
Determine whether the semantic relation where pain is the subject, subclass of is the predicate, and perception is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where diaphragmatic hernia is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15386it [52:09,  5.05it/s]

false
Determine whether the semantic relation where kallidin is the subject, subject has role is the predicate, and antihypertensive drug is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Histocompatibility 2, D region locus 1 is the subject, cell component is the predicate, and Golgi apparatus is the object constitutes an accurate semantic relation.

15387it [52:09,  4.76it/s]

false
Determine whether the semantic relation where cranial nerve disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15389it [52:09,  4.88it/s]

true
Determine whether the semantic relation where propyl gallate is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Raf-1 proto-oncogene, serine/threonine kinase is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15390it [52:09,  5.01it/s]

true
Determine whether the semantic relation where Tyrosine hydroxylase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15391it [52:10,  4.44it/s]

false
Determine whether the semantic relation where disease-free survival is the subject, facet of is the predicate, and therapy is the object constitutes an accurate semantic relation.

15392it [52:10,  4.51it/s]

false
Determine whether the semantic relation where cherubism is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15394it [52:10,  4.69it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and black pepper is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where tetanus is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

15396it [52:11,  4.73it/s]

true
Determine whether the semantic relation where Killer cell immunoglobulin like receptor, two Ig domains and long cytoplasmic tail 1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SMAD family member 4 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15397it [52:11,  4.87it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Brunei is the object constitutes an accurate semantic relation.
true

15399it [52:11,  5.04it/s]

Determine whether the semantic relation where immunoglobulin D is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ethidium bromide is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15401it [52:12,  5.18it/s]

true
Determine whether the semantic relation where Heterogeneous nuclear ribonucleoprotein L is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Argentina is the subject, diplomatic relation is the predicate, and South Africa is the object constitutes an accurate semantic relation.

15403it [52:12,  4.70it/s]

true
Determine whether the semantic relation where Brunei is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where South Africa is the subject, diplomatic relation is the predicate, and Argentina is the object constitutes an accurate semantic relation.

15404it [52:12,  4.90it/s]

true
Determine whether the semantic relation where Kuwait is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

15405it [52:13,  4.78it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and pentamidine is the object constitutes an accurate semantic relation.

15406it [52:13,  4.42it/s]

true
Determine whether the semantic relation where pentamidine is the subject, significant drug interaction is the predicate, and (RS)-methadone is the object constitutes an accurate semantic relation.

15407it [52:13,  4.33it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Soviet Union is the object constitutes an accurate semantic relation.

15409it [52:14,  4.41it/s]

false
Determine whether the semantic relation where Soviet Union is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where raffinose is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15411it [52:14,  4.77it/s]

false
Determine whether the semantic relation where Serbia is the subject, diplomatic relation is the predicate, and Poland is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Poland is the subject, diplomatic relation is the predicate, and Serbia is the object constitutes an accurate semantic relation.

15412it [52:14,  4.96it/s]

true
Determine whether the semantic relation where bronchoconstriction is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.

15413it [52:15,  4.05it/s]

false
Determine whether the semantic relation where hyperkalemic periodic paralysis is the subject, possible treatment is the predicate, and glucose is the object constitutes an accurate semantic relation.

15415it [52:15,  4.32it/s]

true
Determine whether the semantic relation where appendicitis is the subject, symptoms and signs is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hypertrophic cardiomyopathy is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15416it [52:15,  4.60it/s]

true
Determine whether the semantic relation where keto-D-fructose is the subject, found in taxon is the predicate, and Sorghum is the object constitutes an accurate semantic relation.

15417it [52:15,  4.69it/s]

false
Determine whether the semantic relation where progressive nonfluent aphasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15419it [52:16,  4.78it/s]

true
Determine whether the semantic relation where ethinylestradiol is the subject, subject has role is the predicate, and carcinogen is the object constitutes an accurate semantic relation.
true

15420it [52:16,  4.90it/s]

Determine whether the semantic relation where mitogen-activated protein kinase 7 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where TNF receptor superfamily member 6b is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15422it [52:16,  5.16it/s]

true
Determine whether the semantic relation where inosine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where neurofibromin 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

15424it [52:17,  5.11it/s]

true
Determine whether the semantic relation where France is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Extra spindle pole bodies like 1, separase is the subject, biological process is the predicate, and apoptotic process is the object constitutes an accurate semantic relation.

15426it [52:17,  5.13it/s]

false
Determine whether the semantic relation where cerebellar disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Africa is the subject, has part(s) is the predicate, and Middle East is the object constitutes an accurate semantic relation.

15427it [52:17,  4.99it/s]

false
Determine whether the semantic relation where chlormequat is the subject, subclass of is the predicate, and cation is the object constitutes an accurate semantic relation.

15429it [52:18,  5.04it/s]

false
Determine whether the semantic relation where Atlantic Ocean is the subject, basin country is the predicate, and France is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where intercellular adhesion molecule 1 is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

15431it [52:18,  5.10it/s]

false
Determine whether the semantic relation where mathematical concept is the subject, facet of is the predicate, and mathematics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where mathematical concept is the subject, studied by is the predicate, and mathematics is the object constitutes an accurate semantic relation.

15433it [52:18,  5.22it/s]

false
Determine whether the semantic relation where proscillaridin is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dyskinesia is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15435it [52:19,  5.14it/s]

false
Determine whether the semantic relation where Middle East is the subject, continent is the predicate, and Africa is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Middle East is the subject, part of is the predicate, and Africa is the object constitutes an accurate semantic relation.

15437it [52:19,  5.31it/s]

false
Determine whether the semantic relation where Romania is the subject, diplomatic relation is the predicate, and Spain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Spain is the subject, diplomatic relation is the predicate, and Romania is the object constitutes an accurate semantic relation.

15438it [52:19,  5.33it/s]

true
Determine whether the semantic relation where public health is the subject, facet of is the predicate, and risk management is the object constitutes an accurate semantic relation.

15439it [52:20,  4.89it/s]

false
Determine whether the semantic relation where cryoglobulinemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15441it [52:20,  5.01it/s]

true
Determine whether the semantic relation where L-Cysteine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where monosodium L-glutamate is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

15443it [52:20,  4.96it/s]

true
Determine whether the semantic relation where fatal familial insomnia is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Malaysia is the subject, diplomatic relation is the predicate, and Yemen is the object constitutes an accurate semantic relation.

15445it [52:21,  5.12it/s]

true
Determine whether the semantic relation where South Caucasus is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Yemen is the subject, diplomatic relation is the predicate, and Malaysia is the object constitutes an accurate semantic relation.

15446it [52:21,  5.20it/s]

true
Determine whether the semantic relation where L-histidine is the subject, found in taxon is the predicate, and soybean is the object constitutes an accurate semantic relation.

15447it [52:21,  5.07it/s]

false
Determine whether the semantic relation where phenylalanine hydroxylase is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15449it [52:22,  4.78it/s]

false
Determine whether the semantic relation where trifluoroacetic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where camphor is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15450it [52:22,  4.99it/s]

false
Determine whether the semantic relation where Schiff base is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15452it [52:22,  4.91it/s]

false
Determine whether the semantic relation where Cuba is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where dilated cardiomyopathy is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15453it [52:22,  5.02it/s]

true
Determine whether the semantic relation where IKAROS family zinc finger 1 is the subject, biological process is the predicate, and cell cycle is the object constitutes an accurate semantic relation.

15455it [52:23,  4.99it/s]

false
Determine whether the semantic relation where Creutzfeldt-Jakob disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where product packaging is the subject, has use is the predicate, and education is the object constitutes an accurate semantic relation.

15457it [52:23,  4.94it/s]

false
Determine whether the semantic relation where diffuse idiopathic skeletal hyperostosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where major histocompatibility complex, class II, DR alpha is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

15459it [52:24,  5.11it/s]

false
Determine whether the semantic relation where mitogen-activated protein kinase 3 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and Canada is the object constitutes an accurate semantic relation.

15461it [52:24,  5.11it/s]

true
Determine whether the semantic relation where visceral leishmaniasis is the subject, anatomical location is the predicate, and liver is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myocardial infarction is the subject, risk factor is the predicate, and smoking is the object constitutes an accurate semantic relation.

15463it [52:24,  5.12it/s]

false
Determine whether the semantic relation where Henoch-Schoenlein purpura is the subject, symptoms and signs is the predicate, and arthritis is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smoking is the subject, has effect is the predicate, and myocardial infarction is the object constitutes an accurate semantic relation.

15465it [52:25,  5.30it/s]

true
Determine whether the semantic relation where Cyclin D3 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fibroblast growth factor receptor 2 is the subject, biological process is the predicate, and wound healing is the object constitutes an accurate semantic relation.

15467it [52:25,  5.09it/s]

true
Determine whether the semantic relation where glanders is the subject, symptoms and signs is the predicate, and abscess is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where serum sickness is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15468it [52:25,  5.01it/s]

true
Determine whether the semantic relation where Jun proto-oncogene, AP-1 transcription factor subunit is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15470it [52:26,  4.90it/s]

false
Determine whether the semantic relation where miliaria is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acute stress reaction is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

15471it [52:26,  4.83it/s]

true
Determine whether the semantic relation where acute stress reaction is the subject, health specialty is the predicate, and psychology is the object constitutes an accurate semantic relation.

15473it [52:27,  4.84it/s]

true
Determine whether the semantic relation where gout is the subject, has contributing factor is the predicate, and obesity is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fentanyl is the subject, subclass of is the predicate, and phenethylamine is the object constitutes an accurate semantic relation.

15475it [52:27,  5.11it/s]

false
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Namibia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Namibia is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

15477it [52:27,  5.17it/s]

true
Determine whether the semantic relation where leprosy is the subject, symptoms and signs is the predicate, and polyneuropathy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where integrin subunit alpha 2 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15478it [52:28,  4.55it/s]

true
Determine whether the semantic relation where SRC proto-oncogene, non-receptor tyrosine kinase is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

15479it [52:28,  4.25it/s]

false
Determine whether the semantic relation where chlorofluorocarbon is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15481it [52:28,  4.61it/s]

true
Determine whether the semantic relation where familial adenomatous polyposis is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acute respiratory distress syndrome is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.

15482it [52:28,  4.89it/s]

false
Determine whether the semantic relation where Trinidad and Tobago is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

15484it [52:29,  4.98it/s]

true
Determine whether the semantic relation where childhood obesity is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cytochrome-c oxidase deficiency disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15486it [52:29,  4.92it/s]

true
Determine whether the semantic relation where dextran is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cathepsin K is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15488it [52:30,  5.06it/s]

false
Determine whether the semantic relation where Follicle stimulating hormone subunit beta is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Peutz-Jeghers syndrome is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15490it [52:30,  5.22it/s]

true
Determine whether the semantic relation where calcium carbonate is the subject, medical condition treated is the predicate, and peptic ulcer disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where peptic ulcer disease is the subject, drug or therapy used for treatment is the predicate, and calcium carbonate is the object constitutes an accurate semantic relation.

15492it [52:30,  5.21it/s]

true
Determine whether the semantic relation where Germany is the subject, diplomatic relation is the predicate, and Slovakia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Slovakia is the subject, diplomatic relation is the predicate, and Germany is the object constitutes an accurate semantic relation.

15494it [52:31,  5.09it/s]

true
Determine whether the semantic relation where cell death is the subject, has contributing factor is the predicate, and necrosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where necrosis is the subject, subclass of is the predicate, and cell death is the object constitutes an accurate semantic relation.

15495it [52:31,  5.23it/s]

true
Determine whether the semantic relation where necrosis is the subject, contributing factor of is the predicate, and cell death is the object constitutes an accurate semantic relation.

15497it [52:31,  5.06it/s]

false
Determine whether the semantic relation where cellular communication network factor 1 is the subject, biological process is the predicate, and post-translational protein modification is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where glanders is the subject, drug or therapy used for treatment is the predicate, and ampicillin is the object constitutes an accurate semantic relation.

15498it [52:32,  5.05it/s]

false
Determine whether the semantic relation where mucopolysaccharidosis II is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15500it [52:32,  5.05it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and phenazopyridine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where alpha-linolenic acid is the subject, found in taxon is the predicate, and onion is the object constitutes an accurate semantic relation.

15501it [52:32,  4.96it/s]

false
Determine whether the semantic relation where phenazopyridine is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.

15502it [52:32,  4.59it/s]

true
Determine whether the semantic relation where dactinomycin is the subject, medical condition treated is the predicate, and melanoma is the object constitutes an accurate semantic relation.

15504it [52:33,  4.65it/s]

true
Determine whether the semantic relation where Anti-Mullerian hormone is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Ethiopia is the object constitutes an accurate semantic relation.

15505it [52:33,  4.69it/s]

true
Determine whether the semantic relation where melanoma is the subject, drug or therapy used for treatment is the predicate, and dactinomycin is the object constitutes an accurate semantic relation.

15506it [52:33,  4.21it/s]

false
Determine whether the semantic relation where ileitis is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15508it [52:34,  4.55it/s]

true
Determine whether the semantic relation where nephroblastoma is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Proprotein convertase subtilisin/kexin type 5 is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15509it [52:34,  4.68it/s]

true
Determine whether the semantic relation where Ethiopia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.

15511it [52:34,  4.92it/s]

true
Determine whether the semantic relation where anisomycin is the subject, subject has role is the predicate, and antiprotozoal is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15512it [52:35,  5.02it/s]

true
Determine whether the semantic relation where St. Louis encephalitis is the subject, symptoms and signs is the predicate, and mental confusion is the object constitutes an accurate semantic relation.

15513it [52:35,  4.53it/s]

true
Determine whether the semantic relation where NME/NM23 nucleoside diphosphate kinase 4 is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.

15515it [52:35,  4.76it/s]

false
Determine whether the semantic relation where Pan American Health Organization is the subject, country is the predicate, and United States is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where isothiocyanate is the subject, subclass of is the predicate, and nitrogen compound is the object constitutes an accurate semantic relation.

15516it [52:35,  4.95it/s]

true
Determine whether the semantic relation where 4-aminobenzoic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

15518it [52:36,  4.93it/s]

false
Determine whether the semantic relation where guanine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where dichloromethane is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15520it [52:36,  5.04it/s]

true
Determine whether the semantic relation where Graves' disease is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where emergency treatment is the subject, subclass of is the predicate, and health care is the object constitutes an accurate semantic relation.

15521it [52:36,  5.02it/s]

true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

15523it [52:37,  4.89it/s]

true
Determine whether the semantic relation where nitric oxide synthase 2 is the subject, cell component is the predicate, and peroxisome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where nutritional science is the subject, subclass of is the predicate, and science is the object constitutes an accurate semantic relation.

15524it [52:37,  4.90it/s]

true
Determine whether the semantic relation where imperforate anus is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

15525it [52:37,  4.88it/s]

false
Determine whether the semantic relation where chlorhexidine is the subject, medical condition treated is the predicate, and fungal infectious disease is the object constitutes an accurate semantic relation.

15527it [52:38,  4.94it/s]

false
Determine whether the semantic relation where isosorbide is the subject, medical condition treated is the predicate, and cyanosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cyanosis is the subject, drug or therapy used for treatment is the predicate, and isosorbide is the object constitutes an accurate semantic relation.

15529it [52:38,  5.11it/s]

false
Determine whether the semantic relation where fungal infectious disease is the subject, drug or therapy used for treatment is the predicate, and chlorhexidine is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where neuromuscular junction disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15531it [52:38,  5.22it/s]

true
Determine whether the semantic relation where sleep phase chronotherapy is the subject, instance of is the predicate, and therapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Histamine receptor H1 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15533it [52:39,  5.20it/s]

true
Determine whether the semantic relation where apigenin is the subject, found in taxon is the predicate, and Ginkgo biloba is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where autonomic neuropathy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15535it [52:39,  5.18it/s]

true
Determine whether the semantic relation where AKT serine/threonine kinase 1 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Tarlov cyst is the subject, health specialty is the predicate, and radiology is the object constitutes an accurate semantic relation.

15536it [52:39,  5.08it/s]

false
Determine whether the semantic relation where Wilson disease is the subject, subclass of is the predicate, and organic brain syndrome is the object constitutes an accurate semantic relation.

15538it [52:40,  5.01it/s]

false
Determine whether the semantic relation where hepatocellular carcinoma is the subject, symptoms and signs is the predicate, and jaundice is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fenclonine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

15540it [52:40,  5.16it/s]

true
Determine whether the semantic relation where Cystatin C is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coagulation factor II thrombin receptor is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15542it [52:41,  5.15it/s]

true
Determine whether the semantic relation where peptidylprolyl isomerase A is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where carbenicillin phenyl is the subject, subject has role is the predicate, and antibiotic is the object constitutes an accurate semantic relation.

15544it [52:41,  4.60it/s]

true
Determine whether the semantic relation where domestic violence is the subject, instance of is the predicate, and cause of death is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where school is the subject, intended public is the predicate, and teenager is the object constitutes an accurate semantic relation.

15546it [52:41,  4.95it/s]

true
Determine whether the semantic relation where thiamine(1+) ion is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Carbamoyl-phosphate synthase 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15548it [52:42,  5.09it/s]

false
Determine whether the semantic relation where World War II is the subject, location is the predicate, and Middle East is the object constitutes an accurate semantic relation.
maybe
Determine whether the semantic relation where orangutan is the subject, main food source is the predicate, and fruit is the object constitutes an accurate semantic relation.

15549it [52:42,  5.21it/s]

true
Determine whether the semantic relation where seizure is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15551it [52:42,  5.05it/s]

true
Determine whether the semantic relation where Glycoprotein hormones, alpha polypeptide is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Scutellaria baicalensis is the subject, has use is the predicate, and drink is the object constitutes an accurate semantic relation.

15553it [52:43,  5.25it/s]

false
Determine whether the semantic relation where RUNX family transcription factor 3 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where relapsing-remitting multiple sclerosis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15555it [52:43,  5.27it/s]

true
Determine whether the semantic relation where Singapore is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Singapore is the object constitutes an accurate semantic relation.

15557it [52:44,  5.40it/s]

true
Determine whether the semantic relation where cholecystitis is the subject, symptoms and signs is the predicate, and inflammation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Byzantine Empire is the subject, continent is the predicate, and Africa is the object constitutes an accurate semantic relation.

15558it [52:44,  5.26it/s]

false
Determine whether the semantic relation where Hong Kong is the subject, instance of is the predicate, and city is the object constitutes an accurate semantic relation.

15559it [52:44,  5.03it/s]

true
Determine whether the semantic relation where (RS)-methadone is the subject, significant drug interaction is the predicate, and phenelzine is the object constitutes an accurate semantic relation.

15561it [52:44,  5.09it/s]

true
Determine whether the semantic relation where Amish is the subject, country is the predicate, and Canada is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where autopsy is the subject, product or material produced is the predicate, and diagnosis is the object constitutes an accurate semantic relation.

15563it [52:45,  5.06it/s]

false
Determine whether the semantic relation where MET proto-oncogene, receptor tyrosine kinase is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where hemorrhagic fever with renal syndrome is the subject, health specialty is the predicate, and nephrology is the object constitutes an accurate semantic relation.

15565it [52:45,  5.27it/s]

true
Determine whether the semantic relation where diagnosis is the subject, part of is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where diagnosis is the subject, has immediate cause is the predicate, and medical diagnosis is the object constitutes an accurate semantic relation.

15567it [52:45,  5.17it/s]

false
Determine whether the semantic relation where medical diagnosis is the subject, part of is the predicate, and diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where medical diagnosis is the subject, has effect is the predicate, and diagnosis is the object constitutes an accurate semantic relation.

15569it [52:46,  5.44it/s]

false
Determine whether the semantic relation where glycine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where collagen disease is the subject, drug or therapy used for treatment is the predicate, and prednisone is the object constitutes an accurate semantic relation.

15571it [52:46,  5.54it/s]

true
Determine whether the semantic relation where prednisone is the subject, medical condition treated is the predicate, and collagen disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (RS)-nefopam is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

15573it [52:47,  5.45it/s]

true
Determine whether the semantic relation where magnetic resonance imaging is the subject, subclass of is the predicate, and diagnosis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where early diagnosis is the subject, subclass of is the predicate, and diagnosis is the object constitutes an accurate semantic relation.

15574it [52:47,  5.48it/s]

true
Determine whether the semantic relation where natriuretic peptide is the subject, subclass of is the predicate, and protein is the object constitutes an accurate semantic relation.

15576it [52:47,  4.82it/s]

true
Determine whether the semantic relation where Jamaica is the subject, shares border with is the predicate, and United Kingdom is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where keratin 13 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15578it [52:48,  4.92it/s]

true
Determine whether the semantic relation where thioredoxin reductase 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where West Asia is the subject, has part(s) is the predicate, and Georgia is the object constitutes an accurate semantic relation.

15580it [52:48,  4.98it/s]

true
Determine whether the semantic relation where Organization for Economic Cooperation and Development is the subject, instance of is the predicate, and government agency is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where cryoglobulinemia is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.

15581it [52:48,  5.05it/s]

true
Determine whether the semantic relation where Hungary is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

15583it [52:49,  5.06it/s]

true
Determine whether the semantic relation where sodium hydroxide is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where nitric oxide synthase 1 is the subject, cell component is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

15585it [52:49,  5.16it/s]

true
Determine whether the semantic relation where Nuclear receptor subfamily 3 group C member 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Glutaredoxin is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

15587it [52:49,  5.05it/s]

false
Determine whether the semantic relation where aspirin is the subject, medical condition treated is the predicate, and pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where RISC complex is the subject, instance of is the predicate, and cellular component is the object constitutes an accurate semantic relation.

15589it [52:50,  5.26it/s]

true
Determine whether the semantic relation where pain is the subject, drug or therapy used for treatment is the predicate, and aspirin is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where transverse myelitis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15591it [52:50,  5.28it/s]

true
Determine whether the semantic relation where Prostaglandin E receptor 3 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Enterovirus infectious disease is the subject, symptoms and signs is the predicate, and fever is the object constitutes an accurate semantic relation.

15593it [52:51,  5.20it/s]

true
Determine whether the semantic relation where ubiquitin C-terminal hydrolase L1 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where harm reduction is the subject, facet of is the predicate, and risk management is the object constitutes an accurate semantic relation.

15595it [52:51,  5.29it/s]

true
Determine whether the semantic relation where angiotensins is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where transforming growth factor is the subject, subclass of is the predicate, and biomarker is the object constitutes an accurate semantic relation.

15597it [52:51,  5.33it/s]

false
Determine whether the semantic relation where glutamate carboxypeptidase II is the subject, biological process is the predicate, and proteolysis is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where postoperative complications is the subject, drug or therapy used for treatment is the predicate, and oxacillin is the object constitutes an accurate semantic relation.

15599it [52:52,  5.20it/s]

maybe
Determine whether the semantic relation where CREST syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yersiniosis is the subject, symptoms and signs is the predicate, and poisoning is the object constitutes an accurate semantic relation.

15601it [52:52,  5.32it/s]

false
Determine whether the semantic relation where Suriname is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where uridine 5'-diphosphate is the subject, found in taxon is the predicate, and Caenorhabditis elegans is the object constitutes an accurate semantic relation.

15602it [52:52,  4.95it/s]

false
Determine whether the semantic relation where oxacillin is the subject, medical condition treated is the predicate, and postoperative complications is the object constitutes an accurate semantic relation.

15603it [52:53,  4.51it/s]

true
Determine whether the semantic relation where Glycyl-tRNA synthetase 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15605it [52:53,  4.67it/s]

true
Determine whether the semantic relation where Nuclear receptor subfamily 3 group C member 2 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true

15606it [52:53,  4.83it/s]

Determine whether the semantic relation where insulin receptor is the subject, biological process is the predicate, and carbohydrate metabolic process is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where glucose is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15608it [52:54,  5.12it/s]

false
Determine whether the semantic relation where human head is the subject, part of is the predicate, and human body is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where self-injury is the subject, subclass of is the predicate, and injury is the object constitutes an accurate semantic relation.

15609it [52:54,  5.11it/s]

true
Determine whether the semantic relation where human body is the subject, has part(s) is the predicate, and human head is the object constitutes an accurate semantic relation.

15611it [52:54,  4.93it/s]

true
Determine whether the semantic relation where butyric acid is the subject, found in taxon is the predicate, and Fragaria is the object constitutes an accurate semantic relation.
false

15612it [52:54,  5.02it/s]

Determine whether the semantic relation where electronic prescribing is the subject, uses is the predicate, and computer is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where yellow fever is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.

15613it [52:55,  5.13it/s]

true
Determine whether the semantic relation where Mitogen-activated protein kinase 9 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15614it [52:55,  4.71it/s]

true
Determine whether the semantic relation where obesity is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

15616it [52:55,  4.85it/s]

false
Determine whether the semantic relation where bacterial infectious disease is the subject, drug or therapy used for treatment is the predicate, and cephaloglycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cytochrome P450 family 7 subfamily A member 1 is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.

15618it [52:56,  5.14it/s]

true
Determine whether the semantic relation where cephaloglycin is the subject, medical condition treated is the predicate, and bacterial infectious disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Canada is the subject, diplomatic relation is the predicate, and Australia is the object constitutes an accurate semantic relation.

15620it [52:56,  5.27it/s]

true
Determine whether the semantic relation where carbon tetrachloride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where gout is the subject, drug or therapy used for treatment is the predicate, and aspirin is the object constitutes an accurate semantic relation.

15622it [52:56,  5.19it/s]

false
Determine whether the semantic relation where G protein-coupled receptor kinase 2 is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where vitelliform macular dystrophy is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

15624it [52:57,  5.18it/s]

true
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Vietnam is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where lopinavir is the subject, significant drug interaction is the predicate, and carbamazepin is the object constitutes an accurate semantic relation.

15626it [52:57,  5.34it/s]

true
Determine whether the semantic relation where Australia is the subject, diplomatic relation is the predicate, and Canada is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystinosis is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.

15628it [52:57,  5.21it/s]

false
Determine whether the semantic relation where zidovudine is the subject, subject has role is the predicate, and antimetabolite is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Vietnam is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.

15629it [52:58,  5.37it/s]

true
Determine whether the semantic relation where Surfactant protein D is the subject, cell component is the predicate, and lysosome is the object constitutes an accurate semantic relation.

15631it [52:58,  4.99it/s]

false
Determine whether the semantic relation where Fibroblast growth factor 10 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where pudendal nerve entrapment is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15633it [52:59,  4.86it/s]

true
Determine whether the semantic relation where hymenolepiasis is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where kwashiorkor is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15635it [52:59,  5.08it/s]

true
Determine whether the semantic relation where matrix metallopeptidase 2 is the subject, cell component is the predicate, and sarcomere is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where erythromycin is the subject, significant drug interaction is the predicate, and ondansetron is the object constitutes an accurate semantic relation.

15636it [52:59,  4.38it/s]

true
Determine whether the semantic relation where ondansetron is the subject, significant drug interaction is the predicate, and erythromycin is the object constitutes an accurate semantic relation.

15638it [53:00,  4.64it/s]

true
Determine whether the semantic relation where carnosine is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Interleukin 6 signal transducer is the subject, cell component is the predicate, and dendrite is the object constitutes an accurate semantic relation.

15640it [53:00,  4.99it/s]

false
Determine whether the semantic relation where bleomycin is the subject, subject has role is the predicate, and DNA polymerase inhibitors is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where central auditory disease is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.

15642it [53:00,  5.20it/s]

true
Determine whether the semantic relation where Bangladesh is the subject, diplomatic relation is the predicate, and Syria is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Syria is the subject, diplomatic relation is the predicate, and Bangladesh is the object constitutes an accurate semantic relation.

15644it [53:01,  5.33it/s]

true
Determine whether the semantic relation where dicrocoeliasis is the subject, has natural reservoir is the predicate, and rabbit is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where abducens nerve palsy is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

15646it [53:01,  5.33it/s]

true
Determine whether the semantic relation where intestinal pseudo-obstruction is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Bloodstream infection is the subject, subclass of is the predicate, and hematopoietic system disease is the object constitutes an accurate semantic relation.

15647it [53:01,  4.89it/s]

true
Determine whether the semantic relation where sex is the subject, facet of is the predicate, and reproduction is the object constitutes an accurate semantic relation.

15649it [53:02,  4.83it/s]

false
Determine whether the semantic relation where type IV hypersensitivity is the subject, health specialty is the predicate, and immunology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where L-alanine is the subject, found in taxon is the predicate, and Pisum sativum is the object constitutes an accurate semantic relation.

15650it [53:02,  4.80it/s]

false
Determine whether the semantic relation where sarcopenia is the subject, health specialty is the predicate, and geriatrics is the object constitutes an accurate semantic relation.

15652it [53:02,  4.90it/s]

true
Determine whether the semantic relation where connective tissue disease is the subject, afflicts is the predicate, and connective tissue is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where connective tissue disease is the subject, anatomical location is the predicate, and connective tissue is the object constitutes an accurate semantic relation.

15653it [53:03,  4.77it/s]

false
Determine whether the semantic relation where phase III clinical trial is the subject, participant is the predicate, and research participant is the object constitutes an accurate semantic relation.

15655it [53:03,  4.89it/s]

true
Determine whether the semantic relation where Growth factor receptor bound protein 7 is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Korea is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

15657it [53:03,  5.01it/s]

true
Determine whether the semantic relation where fragile X syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where acute kidney tubular necrosis is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.

15659it [53:04,  5.24it/s]

false
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and North Korea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2',3'-cyclic nucleotide 3' phosphodiesterase is the subject, cell component is the predicate, and microtubule is the object constitutes an accurate semantic relation.

15660it [53:04,  4.73it/s]

false
Determine whether the semantic relation where Tight junction protein 1 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.

15662it [53:04,  4.83it/s]

false
Determine whether the semantic relation where junctional ectopic tachycardia is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true

15663it [53:05,  4.93it/s]

Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and Ganoderma lucidum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Solute carrier family 22 member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15665it [53:05,  4.99it/s]

false
Determine whether the semantic relation where vascular endothelial growth factor A is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD1d molecule is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15666it [53:05,  5.12it/s]

true
Determine whether the semantic relation where Saudi Arabia is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.

15667it [53:05,  4.92it/s]

true
Determine whether the semantic relation where MutS homolog 2 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

15668it [53:06,  4.84it/s]

true
Determine whether the semantic relation where inhibitor of DNA binding 2 is the subject, cell component is the predicate, and cytosol is the object constitutes an accurate semantic relation.
false

15669it [53:06,  4.87it/s]

Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Saudi Arabia is the object constitutes an accurate semantic relation.

15670it [53:06,  4.85it/s]

true
Determine whether the semantic relation where mediastinal disease is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false

15672it [53:06,  4.87it/s]

Determine whether the semantic relation where hyperhomocysteinemia is the subject, health specialty is the predicate, and nutrition is the object constitutes an accurate semantic relation.
false

15673it [53:07,  4.87it/s]

Determine whether the semantic relation where epidemiological transition is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.
true

15674it [53:07,  5.06it/s]

Determine whether the semantic relation where methylcholanthrene is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where smoke is the subject, has part(s) is the predicate, and gas is the object constitutes an accurate semantic relation.

15676it [53:07,  5.10it/s]

true
Determine whether the semantic relation where preventive medicine is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where preventive medicine is the subject, part of is the predicate, and public health is the object constitutes an accurate semantic relation.

15678it [53:08,  5.05it/s]

true
Determine whether the semantic relation where consumer product safety is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.
true

15679it [53:08,  5.03it/s]

Determine whether the semantic relation where vanillic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where health indicator is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

15681it [53:08,  5.25it/s]

false
Determine whether the semantic relation where caffeine is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where equipment contamination is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.

15683it [53:09,  5.16it/s]

false
Determine whether the semantic relation where Hirschsprung's disease is the subject, health specialty is the predicate, and pediatrics is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pericardial effusion is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.

15685it [53:09,  5.29it/s]

true
Determine whether the semantic relation where quality-adjusted life year is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Natural cytotoxicity triggering receptor 2 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

15686it [53:09,  5.35it/s]

true
Determine whether the semantic relation where life expectancy is the subject, field of work is the predicate, and public health is the object constitutes an accurate semantic relation.

15688it [53:10,  5.24it/s]

false
Determine whether the semantic relation where CD55 molecule (Cromer blood group) is the subject, biological process is the predicate, and respiratory burst is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where public health practice is the subject, part of is the predicate, and public health is the object constitutes an accurate semantic relation.

15690it [53:10,  5.05it/s]

true
Determine whether the semantic relation where cellulose is the subject, has use is the predicate, and food additive is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where opioid receptor kappa 1 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.

15691it [53:10,  5.19it/s]

false
Determine whether the semantic relation where morphine is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.

15693it [53:11,  5.05it/s]

true
Determine whether the semantic relation where epidemiologic measurements is the subject, facet of is the predicate, and public health is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Kuwait is the subject, member of is the predicate, and World Health Organization is the object constitutes an accurate semantic relation.

15695it [53:11,  5.24it/s]

true
Determine whether the semantic relation where Rho family GTPase CDC42 YLR229C is the subject, part of is the predicate, and membrane protein is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where SMAD family member 2 is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

15697it [53:11,  5.15it/s]

false
Determine whether the semantic relation where foodborne illness is the subject, symptoms and signs is the predicate, and abdominal pain is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where DL-glutamic acid is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.

15699it [53:12,  5.21it/s]

true
Determine whether the semantic relation where National Aeronautics and Space Administration is the subject, industry is the predicate, and public sector is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where keratin 10 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

15701it [53:12,  5.31it/s]

false
Determine whether the semantic relation where chlorpromazine is the subject, significant drug interaction is the predicate, and (RS)-citalopram is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Egypt is the subject, diplomatic relation is the predicate, and Mongolia is the object constitutes an accurate semantic relation.

15703it [53:12,  5.28it/s]

true
Determine whether the semantic relation where Mongolia is the subject, diplomatic relation is the predicate, and Egypt is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pierre Robin syndrome is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

15705it [53:13,  5.35it/s]

true
Determine whether the semantic relation where skin disease is the subject, drug or therapy used for treatment is the predicate, and tretinoin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tretinoin is the subject, medical condition treated is the predicate, and skin disease is the object constitutes an accurate semantic relation.

15707it [53:13,  5.28it/s]

true
Determine whether the semantic relation where (RS)-citalopram is the subject, significant drug interaction is the predicate, and chlorpromazine is the object constitutes an accurate semantic relation.
true

15708it [53:13,  5.28it/s]

Determine whether the semantic relation where cyanocobalamin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hyperplasia is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15709it [53:14,  5.22it/s]

true
Determine whether the semantic relation where G protein-coupled receptor kinase 1 is the subject, biological process is the predicate, and visual perception is the object constitutes an accurate semantic relation.

15711it [53:14,  4.50it/s]

false
Determine whether the semantic relation where Canada is the subject, located in or next to body of water is the predicate, and Pacific Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where histoplasmosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15712it [53:14,  4.74it/s]

true
Determine whether the semantic relation where focal epilepsy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15714it [53:15,  4.91it/s]

true
Determine whether the semantic relation where focal epilepsy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where 2,2′-bipyridine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15716it [53:15,  5.02it/s]

true
Determine whether the semantic relation where common cold is the subject, health specialty is the predicate, and otolaryngology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where BAK1 is the subject, instance of is the predicate, and gene is the object constitutes an accurate semantic relation.

15718it [53:16,  4.92it/s]

true
Determine whether the semantic relation where hypercalcemia is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where urethane is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15720it [53:16,  5.02it/s]

true
Determine whether the semantic relation where influenza is the subject, symptoms and signs is the predicate, and myalgia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where trichotillomania is the subject, comorbidity is the predicate, and post-traumatic stress disorder is the object constitutes an accurate semantic relation.

15722it [53:16,  5.12it/s]

true
Determine whether the semantic relation where erectile dysfunction is the subject, possible treatment is the predicate, and psychotherapy is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cattle is the subject, main food source is the predicate, and Q43238 is the object constitutes an accurate semantic relation.

15723it [53:16,  5.26it/s]

false
Determine whether the semantic relation where cyanide is the subject, subclass of is the predicate, and salt is the object constitutes an accurate semantic relation.

15725it [53:17,  5.14it/s]

false
Determine whether the semantic relation where colestyramine is the subject, medical condition treated is the predicate, and coronary artery disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where coronary artery disease is the subject, drug or therapy used for treatment is the predicate, and colestyramine is the object constitutes an accurate semantic relation.

15727it [53:17,  5.02it/s]

false
Determine whether the semantic relation where poisoning is the subject, has effect is the predicate, and nausea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where science is the subject, has part(s) is the predicate, and social science is the object constitutes an accurate semantic relation.

15729it [53:18,  5.23it/s]

true
Determine whether the semantic relation where corrinoid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where binding site is the subject, part of is the predicate, and protein is the object constitutes an accurate semantic relation.

15731it [53:18,  5.12it/s]

true
Determine whether the semantic relation where aspirin is the subject, significant drug interaction is the predicate, and phenytoin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where stupor is the subject, health specialty is the predicate, and psychiatry is the object constitutes an accurate semantic relation.

15732it [53:18,  5.21it/s]

false
Determine whether the semantic relation where Thailand is the subject, diplomatic relation is the predicate, and Pakistan is the object constitutes an accurate semantic relation.

15734it [53:19,  4.92it/s]

true
Determine whether the semantic relation where dihydroergotamine is the subject, significant drug interaction is the predicate, and itraconazole is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Pakistan is the subject, diplomatic relation is the predicate, and Thailand is the object constitutes an accurate semantic relation.

15736it [53:19,  5.05it/s]

true
Determine whether the semantic relation where argyria is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CCAAT enhancer binding protein beta is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15738it [53:19,  5.16it/s]

false
Determine whether the semantic relation where Mexico is the subject, member of is the predicate, and International Red Cross and Red Crescent Movement is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Cyclin dependent kinase inhibitor 1C is the subject, biological process is the predicate, and ageing is the object constitutes an accurate semantic relation.

15740it [53:20,  5.13it/s]

false
Determine whether the semantic relation where Protein kinase C, alpha is the subject, cell component is the predicate, and endoplasmic reticulum is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where United Arab Emirates is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

15741it [53:20,  5.02it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and United Arab Emirates is the object constitutes an accurate semantic relation.

15743it [53:20,  4.97it/s]

true
Determine whether the semantic relation where respiratory system abnormality is the subject, health specialty is the predicate, and pulmonology is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Japan is the subject, shares border with is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

15744it [53:21,  5.11it/s]

false
Determine whether the semantic relation where Japan is the subject, diplomatic relation is the predicate, and Taiwan is the object constitutes an accurate semantic relation.

15746it [53:21,  5.11it/s]

false
Determine whether the semantic relation where Taiwan is the subject, diplomatic relation is the predicate, and Japan is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Taiwan is the subject, shares border with is the predicate, and Japan is the object constitutes an accurate semantic relation.

15748it [53:21,  5.15it/s]

false
Determine whether the semantic relation where retinoid X receptor beta is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where optic nerve tumor is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.

15750it [53:22,  5.21it/s]

true
Determine whether the semantic relation where chlorpromazine is the subject, route of administration is the predicate, and injection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where collagen disease is the subject, drug or therapy used for treatment is the predicate, and prednisolone is the object constitutes an accurate semantic relation.

15752it [53:22,  5.15it/s]

true
Determine whether the semantic relation where mezlocillin is the subject, medical condition treated is the predicate, and skin infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where solute carrier family 1 member 1 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15753it [53:22,  5.15it/s]

false
Determine whether the semantic relation where skin infection is the subject, drug or therapy used for treatment is the predicate, and mezlocillin is the object constitutes an accurate semantic relation.

15754it [53:23,  4.87it/s]

true
Determine whether the semantic relation where cytidine triphosphate is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15755it [53:23,  4.86it/s]

true
Determine whether the semantic relation where prednisolone is the subject, medical condition treated is the predicate, and collagen disease is the object constitutes an accurate semantic relation.

15756it [53:23,  4.82it/s]

true
Determine whether the semantic relation where trichinosis is the subject, disease transmission process is the predicate, and pathogen transmission is the object constitutes an accurate semantic relation.
false

15758it [53:23,  5.05it/s]

Determine whether the semantic relation where Caveolin 2 is the subject, biological process is the predicate, and cell differentiation is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Samoa is the subject, shares border with is the predicate, and United States is the object constitutes an accurate semantic relation.

15760it [53:24,  5.10it/s]

false
Determine whether the semantic relation where Samoa is the subject, diplomatic relation is the predicate, and United States is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where meglutol is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

15762it [53:24,  5.17it/s]

true
Determine whether the semantic relation where decompression sickness is the subject, symptoms and signs is the predicate, and dyspnea is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where amantadine is the subject, subject has role is the predicate, and non-opioid analgesic is the object constitutes an accurate semantic relation.

15763it [53:24,  5.15it/s]

false
Determine whether the semantic relation where United States is the subject, diplomatic relation is the predicate, and Samoa is the object constitutes an accurate semantic relation.

15764it [53:25,  5.06it/s]

true
Determine whether the semantic relation where cyanate is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.

15766it [53:25,  4.95it/s]

true
Determine whether the semantic relation where haloperidol is the subject, subject has role is the predicate, and WHO essential medicines is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where oculocerebrorenal syndrome is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15768it [53:25,  4.93it/s]

true
Determine whether the semantic relation where hypertensive intracranial hemorrhage is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where SRY-box transcription factor 9 is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15770it [53:26,  5.10it/s]

true
Determine whether the semantic relation where Protein C, inactivator of coagulation factors Va and VIIIa is the subject, different from is the predicate, and C-reactive protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where relapsing polychondritis is the subject, subclass of is the predicate, and immune disorder is the object constitutes an accurate semantic relation.

15772it [53:26,  4.95it/s]

true
Determine whether the semantic relation where Duchenne muscular dystrophy is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where aldehyde dehydrogenase 6 family member A1 is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.

15773it [53:26,  4.45it/s]

false
Determine whether the semantic relation where boutonneuse fever is the subject, medical examination is the predicate, and polymerase chain reaction is the object constitutes an accurate semantic relation.

15775it [53:27,  4.70it/s]

true
Determine whether the semantic relation where palmitic acid is the subject, found in taxon is the predicate, and maize is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where urea is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15777it [53:27,  5.08it/s]

true
Determine whether the semantic relation where cluster headache is the subject, medical examination is the predicate, and neurological diagnostic techniques is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where prazosin is the subject, route of administration is the predicate, and oral administration is the object constitutes an accurate semantic relation.

15778it [53:27,  5.02it/s]

true
Determine whether the semantic relation where hydromorphone is the subject, medical condition treated is the predicate, and cough is the object constitutes an accurate semantic relation.

15779it [53:28,  4.77it/s]

false
Determine whether the semantic relation where sleepwalking is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15780it [53:28,  4.74it/s]

true
Determine whether the semantic relation where prolidase deficiency is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15781it [53:28,  4.78it/s]

true
Determine whether the semantic relation where pneumothorax is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.

15782it [53:28,  4.65it/s]

false
Determine whether the semantic relation where cough is the subject, drug or therapy used for treatment is the predicate, and hydromorphone is the object constitutes an accurate semantic relation.

15784it [53:29,  4.62it/s]

false
Determine whether the semantic relation where dermatan sulfate is the subject, instance of is the predicate, and polymer is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where intestinal perforation is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15786it [53:29,  4.97it/s]

false
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, biological process is the predicate, and metabolism is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where oculomotor nerve paralysis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15788it [53:30,  4.96it/s]

true
Determine whether the semantic relation where therapeutic failure is the subject, facet of is the predicate, and therapy is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where deoxyribonucleic acid is the subject, part of is the predicate, and mitochondrion is the object constitutes an accurate semantic relation.

15790it [53:30,  5.20it/s]

true
Determine whether the semantic relation where luteinizing hormone subunit beta is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Zollinger–Ellison syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15792it [53:30,  5.26it/s]

true
Determine whether the semantic relation where Zollinger–Ellison syndrome is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where inclusion body myositis is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.

15794it [53:31,  5.19it/s]

true
Determine whether the semantic relation where G protein subunit alpha i2 is the subject, biological process is the predicate, and cell cycle is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where esophagitis is the subject, instance of is the predicate, and thoracic disease is the object constitutes an accurate semantic relation.

15796it [53:31,  5.21it/s]

true
Determine whether the semantic relation where situs inversus is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Bloom syndrome is the subject, subclass of is the predicate, and tumor of hematopoietic and lymphoid tissues is the object constitutes an accurate semantic relation.

15798it [53:31,  5.19it/s]

false
Determine whether the semantic relation where paraquat dichloride is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where furosemide is the subject, subclass of is the predicate, and heterocyclic compound is the object constitutes an accurate semantic relation.

15800it [53:32,  5.27it/s]

true
Determine whether the semantic relation where Massachusetts is the subject, lowest point is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Massachusetts is the subject, located in or next to body of water is the predicate, and Atlantic Ocean is the object constitutes an accurate semantic relation.

15802it [53:32,  5.20it/s]

true
Determine whether the semantic relation where Indonesia is the subject, diplomatic relation is the predicate, and Cuba is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sirtuin 1 is the subject, biological process is the predicate, and circadian rhythm is the object constitutes an accurate semantic relation.

15804it [53:33,  5.22it/s]

true
Determine whether the semantic relation where formaldehyde is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Cuba is the subject, diplomatic relation is the predicate, and Indonesia is the object constitutes an accurate semantic relation.

15805it [53:33,  5.13it/s]

true
Determine whether the semantic relation where United Nations is the subject, founder is the predicate, and Venezuela is the object constitutes an accurate semantic relation.

15807it [53:33,  5.12it/s]

false
Determine whether the semantic relation where atrophic muscular disease is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Venezuela is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.

15808it [53:33,  5.26it/s]

true
Determine whether the semantic relation where thrombotic thrombocytopenic purpura is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15810it [53:34,  5.02it/s]

true
Determine whether the semantic relation where sarcoidosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Burkholderia pseudomallei is the subject, Gram staining is the predicate, and gram-negative bacteria is the object constitutes an accurate semantic relation.

15812it [53:34,  4.97it/s]

true
Determine whether the semantic relation where Reye syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

15814it [53:35,  5.23it/s]

true
Determine whether the semantic relation where hypertrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where secretin is the subject, subject has role is the predicate, and protein fragment is the object constitutes an accurate semantic relation.

15816it [53:35,  5.13it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where ventricular fibrillation is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15818it [53:35,  5.15it/s]

true
Determine whether the semantic relation where Papillon-Lefevre disease is the subject, health specialty is the predicate, and dermatology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where selenic acid is the subject, has part(s) is the predicate, and hydrogen is the object constitutes an accurate semantic relation.

15819it [53:36,  5.37it/s]

true
Determine whether the semantic relation where paragonimiasis is the subject, symptoms and signs is the predicate, and encephalitis is the object constitutes an accurate semantic relation.

15821it [53:36,  5.09it/s]

maybe
Determine whether the semantic relation where rheumatoid factor is the subject, subject has role is the predicate, and immunologic factor is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where myristic acid is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

15822it [53:36,  5.20it/s]

false
Determine whether the semantic relation where Far East scarlet-like fever is the subject, symptoms and signs is the predicate, and diarrhea is the object constitutes an accurate semantic relation.

15824it [53:37,  5.13it/s]

true
Determine whether the semantic relation where nalidixic acid is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Stevens–Johnson syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

15825it [53:37,  4.91it/s]

true
Determine whether the semantic relation where acetone is the subject, has part(s) is the predicate, and oxygen is the object constitutes an accurate semantic relation.

15826it [53:37,  4.74it/s]

true
Determine whether the semantic relation where thyroid hormone receptor alpha is the subject, cell component is the predicate, and cytoplasm is the object constitutes an accurate semantic relation.

15827it [53:37,  4.78it/s]

true
Determine whether the semantic relation where irritant is the subject, has effect is the predicate, and inflammation is the object constitutes an accurate semantic relation.

15829it [53:38,  4.90it/s]

true
Determine whether the semantic relation where dental pulp calcification is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where genistein is the subject, found in taxon is the predicate, and Streptomyces griseus is the object constitutes an accurate semantic relation.

15831it [53:38,  5.01it/s]

false
Determine whether the semantic relation where CD40 molecule is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and oxygen therapy is the object constitutes an accurate semantic relation.

15833it [53:38,  5.28it/s]

true
Determine whether the semantic relation where Cystathionine beta-synthase is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where lung abscess is the subject, symptoms and signs is the predicate, and necrosis is the object constitutes an accurate semantic relation.

15834it [53:39,  5.33it/s]

false
Determine whether the semantic relation where Denmark is the subject, diplomatic relation is the predicate, and Lithuania is the object constitutes an accurate semantic relation.

15836it [53:39,  5.21it/s]

true
Determine whether the semantic relation where Lithuania is the subject, diplomatic relation is the predicate, and Denmark is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where (−)-ephedrine is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15838it [53:39,  5.21it/s]

true
Determine whether the semantic relation where grooming behavior is the subject, facet of is the predicate, and hygiene is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where RB transcriptional corepressor like 2 is the subject, cell component is the predicate, and nucleolus is the object constitutes an accurate semantic relation.

15840it [53:40,  5.21it/s]

false
Determine whether the semantic relation where tobramycin is the subject, medical condition treated is the predicate, and pneumonia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pneumonia is the subject, drug or therapy used for treatment is the predicate, and tobramycin is the object constitutes an accurate semantic relation.

15841it [53:40,  4.88it/s]

false
Determine whether the semantic relation where stomach is the subject, anatomical location is the predicate, and abdominal cavity is the object constitutes an accurate semantic relation.

15843it [53:40,  4.98it/s]

true
Determine whether the semantic relation where abdominal cavity is the subject, has part(s) is the predicate, and stomach is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psychological stress is the subject, subclass of is the predicate, and stress is the object constitutes an accurate semantic relation.

15845it [53:41,  5.02it/s]

true
Determine whether the semantic relation where Armenia is the subject, member of is the predicate, and United Nations is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where midwifery is the subject, country is the predicate, and Togo is the object constitutes an accurate semantic relation.

15847it [53:41,  5.23it/s]

false
Determine whether the semantic relation where Belgium is the subject, diplomatic relation is the predicate, and Uruguay is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Uruguay is the subject, diplomatic relation is the predicate, and Belgium is the object constitutes an accurate semantic relation.

15849it [53:42,  5.19it/s]

true
Determine whether the semantic relation where lymphoma is the subject, health specialty is the predicate, and hematology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where CD5 molecule is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.

15851it [53:42,  5.35it/s]

true
Determine whether the semantic relation where cryopyrin-associated periodic syndrome is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Heat shock protein family B (small) member 1 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

15853it [53:42,  5.17it/s]

true
Determine whether the semantic relation where transforming growth factor alpha is the subject, cell component is the predicate, and extracellular region is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where periostitis is the subject, health specialty is the predicate, and rheumatology is the object constitutes an accurate semantic relation.

15855it [53:43,  5.23it/s]

false
Determine whether the semantic relation where glycogen phosphorylase B is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scarlet fever is the subject, instance of is the predicate, and infectious disease is the object constitutes an accurate semantic relation.

15856it [53:43,  5.28it/s]

true
Determine whether the semantic relation where cold is the subject, subclass of is the predicate, and sensation is the object constitutes an accurate semantic relation.

15858it [53:43,  4.63it/s]

true
Determine whether the semantic relation where primary prevention is the subject, instance of is the predicate, and preventive medicine is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pericarditis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15860it [53:44,  4.50it/s]

true
Determine whether the semantic relation where inulin is the subject, different from is the predicate, and insulin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where mitogen-activated protein kinase 1 is the subject, biological process is the predicate, and sensory perception of pain is the object constitutes an accurate semantic relation.

15861it [53:44,  4.66it/s]

false
Determine whether the semantic relation where persistent truncus arteriosus is the subject, health specialty is the predicate, and medical genetics is the object constitutes an accurate semantic relation.

15862it [53:44,  4.63it/s]

false
Determine whether the semantic relation where putrescine is the subject, found in taxon is the predicate, and potato is the object constitutes an accurate semantic relation.

15863it [53:45,  3.77it/s]

false
Determine whether the semantic relation where riboflavin is the subject, has part(s) is the predicate, and carbon is the object constitutes an accurate semantic relation.

15864it [53:45,  4.02it/s]

true
Determine whether the semantic relation where rodent disease is the subject, health specialty is the predicate, and veterinary medicine is the object constitutes an accurate semantic relation.

15865it [53:45,  4.21it/s]

false
Determine whether the semantic relation where CD44 molecule (Indian blood group) is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15867it [53:45,  4.62it/s]

true
Determine whether the semantic relation where adult Refsum disease is the subject, instance of is the predicate, and rare disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where sodium lauryl sulfate is the subject, has part(s) is the predicate, and sodium is the object constitutes an accurate semantic relation.

15869it [53:46,  5.03it/s]

false
Determine whether the semantic relation where peptidylprolyl isomerase A is the subject, instance of is the predicate, and protein is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anuria is the subject, health specialty is the predicate, and nephrology is the object constitutes an accurate semantic relation.

15870it [53:46,  5.15it/s]

false
Determine whether the semantic relation where cryptogenic organizing pneumonia is the subject, symptoms and signs is the predicate, and weight loss is the object constitutes an accurate semantic relation.

15872it [53:46,  5.01it/s]

true
Determine whether the semantic relation where lead poisoning is the subject, afflicts is the predicate, and kidney is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where tetraphene is the subject, subclass of is the predicate, and substituted benzene is the object constitutes an accurate semantic relation.

15874it [53:47,  5.19it/s]

false
Determine whether the semantic relation where pyran is the subject, subclass of is the predicate, and oxygen compound is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Integrin subunit alpha L is the subject, cell component is the predicate, and plasma membrane is the object constitutes an accurate semantic relation.

15875it [53:47,  5.26it/s]

true
Determine whether the semantic relation where myotonic dystrophy is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15877it [53:47,  5.07it/s]

true
Determine whether the semantic relation where Rotavirus is the subject, has effect is the predicate, and vomiting is the object constitutes an accurate semantic relation.
true

15878it [53:48,  5.22it/s]

Determine whether the semantic relation where acute retinal necrosis syndrome is the subject, health specialty is the predicate, and ophthalmology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where pre-exposure prophylaxis against HIV is the subject, approved by is the predicate, and England is the object constitutes an accurate semantic relation.

15880it [53:48,  5.29it/s]

false
Determine whether the semantic relation where vomiting is the subject, has cause is the predicate, and Rotavirus is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cystatin B is the subject, cell component is the predicate, and intracellular anatomical structure is the object constitutes an accurate semantic relation.

15882it [53:48,  5.43it/s]

true
Determine whether the semantic relation where familial adenomatous polyposis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where cobblestone lissencephaly is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15884it [53:49,  5.48it/s]

true
Determine whether the semantic relation where L-arginine is the subject, has part(s) is the predicate, and nitrogen is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where X-linked intellectual disability is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15886it [53:49,  5.44it/s]

true
Determine whether the semantic relation where adenosine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where Crohn's disease is the subject, medical examination is the predicate, and biopsy is the object constitutes an accurate semantic relation.

15888it [53:49,  5.36it/s]

false
Determine whether the semantic relation where psychophysics is the subject, part of is the predicate, and psychology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where psychophysics is the subject, part of is the predicate, and psychology is the object constitutes an accurate semantic relation.

15890it [53:50,  5.50it/s]

true
Determine whether the semantic relation where Dopamine receptor D3 is the subject, biological process is the predicate, and signal transduction is the object constitutes an accurate semantic relation.
false
Determine whether the semantic relation where adenine is the subject, found in taxon is the predicate, and Escherichia coli is the object constitutes an accurate semantic relation.

15892it [53:50,  5.42it/s]

false
Determine whether the semantic relation where luteolin is the subject, found in taxon is the predicate, and Allium sativum is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where North Macedonia is the subject, diplomatic relation is the predicate, and Russia is the object constitutes an accurate semantic relation.

15893it [53:50,  5.46it/s]

true
Determine whether the semantic relation where Russia is the subject, diplomatic relation is the predicate, and North Macedonia is the object constitutes an accurate semantic relation.

15895it [53:51,  5.26it/s]

true
Determine whether the semantic relation where France is the subject, diplomatic relation is the predicate, and Haiti is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Haiti is the subject, diplomatic relation is the predicate, and France is the object constitutes an accurate semantic relation.

15897it [53:51,  5.28it/s]

true
Determine whether the semantic relation where moringa is the subject, has use is the predicate, and vegetable is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where human body is the subject, has characteristic is the predicate, and body surface area is the object constitutes an accurate semantic relation.

15899it [53:51,  5.32it/s]

true
Determine whether the semantic relation where chloroquine is the subject, significant drug interaction is the predicate, and procainamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where anal fissure is the subject, health specialty is the predicate, and gastroenterology is the object constitutes an accurate semantic relation.

15900it [53:52,  5.32it/s]

false
Determine whether the semantic relation where clarithromycin is the subject, medical condition treated is the predicate, and cellulitis is the object constitutes an accurate semantic relation.

15902it [53:52,  5.03it/s]

true
Determine whether the semantic relation where cellulitis is the subject, drug or therapy used for treatment is the predicate, and clarithromycin is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where procainamide is the subject, significant drug interaction is the predicate, and chloroquine is the object constitutes an accurate semantic relation.

15904it [53:52,  5.22it/s]

true
Determine whether the semantic relation where metabolic syndrome is the subject, health specialty is the predicate, and endocrinology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where rafoxanide is the subject, inhibitor of is the predicate, and growth is the object constitutes an accurate semantic relation.

15905it [53:53,  5.33it/s]

false
Determine whether the semantic relation where capillary action is the subject, subclass of is the predicate, and physical phenomenon is the object constitutes an accurate semantic relation.

15907it [53:53,  5.29it/s]

true
Determine whether the semantic relation where botulism is the subject, symptoms and signs is the predicate, and xerostomia is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where BCL2 associated X, apoptosis regulator is the subject, cell component is the predicate, and extracellular exosome is the object constitutes an accurate semantic relation.

15908it [53:53,  5.24it/s]

false
Determine whether the semantic relation where staphylococcal infection is the subject, drug or therapy used for treatment is the predicate, and cefixime is the object constitutes an accurate semantic relation.

15909it [53:53,  4.90it/s]

false
Determine whether the semantic relation where perphenazine is the subject, subject has role is the predicate, and alpha blocker is the object constitutes an accurate semantic relation.

15911it [53:54,  5.09it/s]

false
Determine whether the semantic relation where cefixime is the subject, medical condition treated is the predicate, and staphylococcal infection is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where fusaric acid is the subject, subject has role is the predicate, and enzyme inhibitor is the object constitutes an accurate semantic relation.

15913it [53:54,  5.19it/s]

true
Determine whether the semantic relation where experimental mammary neoplasms is the subject, instance of is the predicate, and animal disease is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Hemoglobin subunit delta is the subject, molecular function is the predicate, and protein binding is the object constitutes an accurate semantic relation.

15914it [53:54,  5.25it/s]

true
Determine whether the semantic relation where Loeys-Dietz syndrome is the subject, subclass of is the predicate, and syndrome is the object constitutes an accurate semantic relation.

15915it [53:55,  5.05it/s]

true
Determine whether the semantic relation where cyclin dependent kinase 5 is the subject, cell component is the predicate, and nucleus is the object constitutes an accurate semantic relation.

15916it [53:55,  4.95it/s]

true
Determine whether the semantic relation where tetanus is the subject, possible treatment is the predicate, and anticonvulsant agent is the object constitutes an accurate semantic relation.

15918it [53:55,  4.74it/s]

true
Determine whether the semantic relation where saccharin is the subject, subclass of is the predicate, and sulfonamide is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where hereditary optic atrophy is the subject, instance of is the predicate, and disease is the object constitutes an accurate semantic relation.

15920it [53:56,  4.83it/s]

true
Determine whether the semantic relation where postpericardiotomy syndrome is the subject, health specialty is the predicate, and cardiology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where Armenia is the subject, continent is the predicate, and Asia is the object constitutes an accurate semantic relation.

15922it [53:56,  5.05it/s]

true
Determine whether the semantic relation where lead poisoning of the nervous system is the subject, health specialty is the predicate, and neurology is the object constitutes an accurate semantic relation.
true
Determine whether the semantic relation where scoliosis is the subject, subclass of is the predicate, and disease is the object constitutes an accurate semantic relation.

15923it [53:56,  5.15it/s]

true
Determine whether the semantic relation where inguinal hernia is the subject, subclass of is the predicate, and intestinal disease is the object constitutes an accurate semantic relation.

15925it [53:57,  4.92it/s]

false
Determine whether the semantic relation where transformation is the subject, different from is the predicate, and genetics is the object constitutes an accurate semantic relation.
false

In [ ]:
df["choice"] = findings

In [ ]:
df['choice'].value_counts()

choice
true     10407
false     5355
maybe      163
Name: count, dtype: int64

In [ ]:
df.to_excel("Low PMI.xlsx", index=False)